import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'adminPage',
  content: {
    title: t({
      ru: 'Административная панель',
      en: 'Admin panel',
      kk: 'Әкімшілік панелі',
      de: 'Administrationsbereich',
      fr: 'Panneau d\'administration',
      es: 'Panel de administración',
      pt: 'Painel de administração',
      tr: 'Yönetici paneli',
      uk: 'Адміністративна панель',
      zh: '管理面板',
      ar: 'لوحة الإدارة',
      pl: 'Panel administracyjny',
      it: 'Pannello di amministrazione',
    }),
    tabs: {
      statementsLog: t({
        ru: 'Журнал выписок',
        en: 'Statements log',
        kk: 'Үзінділер журналы',
        de: 'Kontoauszugsprotokoll',
        fr: 'Journal des relevés',
        es: 'Registro de extractos',
        pt: 'Log de extratos',
        tr: 'Ekstre günlüğü',
        uk: 'Журнал виписок',
        zh: '账单日志',
        ar: 'سجل الكشوفات',
        pl: 'Dziennik wyciągów',
        it: 'Log estratti',
      }),
      users: t({
        ru: 'Управление пользователями',
        en: 'User management',
        kk: 'Пайдаланушыларды басқару',
        de: 'Benutzerverwaltung',
        fr: 'Gestion des utilisateurs',
        es: 'Gestión de usuarios',
        pt: 'Gerenciamento de usuários',
        tr: 'Kullanıcı yönetimi',
        uk: 'Управління користувачами',
        zh: '用户管理',
        ar: 'إدارة المستخدمين',
        pl: 'Zarządzanie użytkownikami',
        it: 'Gestione utenti',
      }),
      audit: t({
        ru: 'Аудит-лог',
        en: 'Audit log',
        kk: 'Аудит журналы',
        de: 'Audit-Protokoll',
        fr: 'Journal d\'audit',
        es: 'Registro de auditoría',
        pt: 'Log de auditoria',
        tr: 'Denetim günlüğü',
        uk: 'Журнал аудиту',
        zh: '审计日志',
        ar: 'سجل التدقيق',
        pl: 'Dziennik audytu',
        it: 'Log di audit',
      }),
    },
    errors: {
      loadStatements: t({
        ru: 'Ошибка загрузки выписок',
        en: 'Failed to load statements',
        kk: 'Үзінділерді жүктеу қатесі',
        de: 'Fehler beim Laden der Kontoauszüge',
        fr: 'Erreur lors du chargement des relevés',
        es: 'Error al cargar extractos',
        pt: 'Erro ao carregar extratos',
        tr: 'Ekstreler yüklenemedi',
        uk: 'Помилка завантаження виписок',
        zh: '加载账单失败',
        ar: 'فشل تحميل الكشوفات',
        pl: 'Błąd ładowania wyciągów',
        it: 'Errore nel caricamento degli estratti',
      }),
      loadAudit: t({
        ru: 'Ошибка загрузки аудит-лога',
        en: 'Failed to load audit log',
        kk: 'Аудит журналын жүктеу қатесі',
        de: 'Fehler beim Laden des Audit-Protokolls',
        fr: 'Erreur lors du chargement du journal d\'audit',
        es: 'Error al cargar el registro de auditoría',
        pt: 'Erro ao carregar log de auditoria',
        tr: 'Denetim günlüğü yüklenemedi',
        uk: 'Помилка завантаження журналу аудиту',
        zh: '加载审计日志失败',
        ar: 'فشل تحميل سجل التدقيق',
        pl: 'Błąd ładowania dziennika audytu',
        it: 'Errore nel caricamento del log di audit',
      }),
      reprocess: t({
        ru: 'Ошибка повторной обработки',
        en: 'Failed to reprocess',
        kk: 'Қайта өңдеу қатесі',
        de: 'Fehler bei der erneuten Verarbeitung',
        fr: 'Erreur lors du retraitement',
        es: 'Error al reprocesar',
        pt: 'Erro ao reprocessar',
        tr: 'Yeniden işleme başarısız',
        uk: 'Помилка повторної обробки',
        zh: '重新处理失败',
        ar: 'فشل إعادة المعالجة',
        pl: 'Błąd ponownego przetwarzania',
        it: 'Errore nel rielaborazione',
      }),
      delete: t({
        ru: 'Ошибка удаления выписки',
        en: 'Failed to delete statement',
        kk: 'Үзіндіні жою қатесі',
        de: 'Fehler beim Löschen des Kontoauszugs',
        fr: 'Erreur lors de la suppression du relevé',
        es: 'Error al eliminar el extracto',
        pt: 'Erro ao excluir extrato',
        tr: 'Ekstre silinemedi',
        uk: 'Помилка видалення виписки',
        zh: '删除账单失败',
        ar: 'فشل حذف الكشف',
        pl: 'Błąd usuwania wyciągu',
        it: 'Errore nell\'eliminazione dell\'estratto',
      }),
    },
    confirmDelete: t({
      ru: 'Вы уверены, что хотите удалить эту выписку?',
      en: 'Are you sure you want to delete this statement?',
      kk: 'Осы үзіндіні жойғыңыз келетініне сенімдісіз бе?',
      de: 'Sind Sie sicher, dass Sie diesen Kontoauszug löschen möchten?',
      fr: 'Êtes-vous sûr de vouloir supprimer ce relevé ?',
      es: '¿Estás seguro de que quieres eliminar este extracto?',
      pt: 'Tem certeza de que deseja excluir este extrato?',
      tr: 'Bu ekstreyi silmek istediğinizden emin misiniz?',
      uk: 'Ви впевнені, що хочете видалити цю виписку?',
      zh: '您确定要删除此账单吗？',
      ar: 'هل أنت متأكد أنك تريد حذف هذا الكشف؟',
      pl: 'Czy na pewno chcesz usunąć ten wyciąg?',
      it: 'Sei sicuro di voler eliminare questo estratto?',
    }),
    status: {
      completed: t({
        ru: 'Завершено',
        en: 'Completed',
        kk: 'Аяқталды',
        de: 'Abgeschlossen',
        fr: 'Terminé',
        es: 'Completado',
        pt: 'Concluído',
        tr: 'Tamamlandı',
        uk: 'Завершено',
        zh: '已完成',
        ar: 'مكتمل',
        pl: 'Ukończone',
        it: 'Completato',
      }),
      processing: t({
        ru: 'Обрабатывается',
        en: 'Processing',
        kk: 'Өңделуде',
        de: 'Wird verarbeitet',
        fr: 'En cours de traitement',
        es: 'Procesando',
        pt: 'Processando',
        tr: 'İşleniyor',
        uk: 'Обробляється',
        zh: '处理中',
        ar: 'قيد المعالجة',
        pl: 'Przetwarzanie',
        it: 'In elaborazione',
      }),
      error: t({
        ru: 'Ошибка',
        en: 'Error',
        kk: 'Қате',
        de: 'Fehler',
        fr: 'Erreur',
        es: 'Error',
        pt: 'Erro',
        tr: 'Hata',
        uk: 'Помилка',
        zh: '错误',
        ar: 'خطأ',
        pl: 'Błąd',
        it: 'Errore',
      }),
    },
    search: t({
      ru: 'Поиск',
      en: 'Search',
      kk: 'Іздеу',
      de: 'Suche',
      fr: 'Recherche',
      es: 'Buscar',
      pt: 'Pesquisar',
      tr: 'Ara',
      uk: 'Пошук',
      zh: '搜索',
      ar: 'بحث',
      pl: 'Szukaj',
      it: 'Cerca',
    }),
    refresh: t({
      ru: 'Обновить',
      en: 'Refresh',
      kk: 'Жаңарту',
      de: 'Aktualisieren',
      fr: 'Actualiser',
      es: 'Actualizar',
      pt: 'Atualizar',
      tr: 'Yenile',
      uk: 'Оновити',
      zh: '刷新',
      ar: 'تحديث',
      pl: 'Odśwież',
      it: 'Aggiorna',
    }),
    table: {
      file: t({
        ru: 'Файл',
        en: 'File',
        kk: 'Файл',
        de: 'Datei',
        fr: 'Fichier',
        es: 'Archivo',
        pt: 'Arquivo',
        tr: 'Dosya',
        uk: 'Файл',
        zh: '文件',
        ar: 'الملف',
        pl: 'Plik',
        it: 'File',
      }),
      type: t({
        ru: 'Тип',
        en: 'Type',
        kk: 'Түрі',
        de: 'Typ',
        fr: 'Type',
        es: 'Tipo',
        pt: 'Tipo',
        tr: 'Tür',
        uk: 'Тип',
        zh: '类型',
        ar: 'النوع',
        pl: 'Typ',
        it: 'Tipo',
      }),
      bank: t({
        ru: 'Банк',
        en: 'Bank',
        kk: 'Банк',
        de: 'Bank',
        fr: 'Banque',
        es: 'Banco',
        pt: 'Banco',
        tr: 'Banka',
        uk: 'Банк',
        zh: '银行',
        ar: 'البنك',
        pl: 'Bank',
        it: 'Banca',
      }),
      status: t({
        ru: 'Статус',
        en: 'Status',
        kk: 'Күйі',
        de: 'Status',
        fr: 'Statut',
        es: 'Estado',
        pt: 'Status',
        tr: 'Durum',
        uk: 'Статус',
        zh: '状态',
        ar: 'الحالة',
        pl: 'Status',
        it: 'Stato',
      }),
      transactions: t({
        ru: 'Операций',
        en: 'Transactions',
        kk: 'Операциялар',
        de: 'Transaktionen',
        fr: 'Transactions',
        es: 'Transacciones',
        pt: 'Transações',
        tr: 'İşlemler',
        uk: 'Операції',
        zh: '交易',
        ar: 'المعاملات',
        pl: 'Transakcje',
        it: 'Transazioni',
      }),
      uploadedAt: t({
        ru: 'Дата загрузки',
        en: 'Upload date',
        kk: 'Жүктеу күні',
        de: 'Hochladedatum',
        fr: 'Date de téléchargement',
        es: 'Fecha de carga',
        pt: 'Data de upload',
        tr: 'Yükleme tarihi',
        uk: 'Дата завантаження',
        zh: '上传日期',
        ar: 'تاريخ الرفع',
        pl: 'Data przesłania',
        it: 'Data caricamento',
      }),
      processedAt: t({
        ru: 'Дата обработки',
        en: 'Processed at',
        kk: 'Өңделген күні',
        de: 'Verarbeitungsdatum',
        fr: 'Date de traitement',
        es: 'Fecha de procesamiento',
        pt: 'Data de processamento',
        tr: 'İşlenme tarihi',
        uk: 'Дата обробки',
        zh: '处理日期',
        ar: 'تاريخ المعالجة',
        pl: 'Data przetworzenia',
        it: 'Data elaborazione',
      }),
      actions: t({
        ru: 'Действия',
        en: 'Actions',
        kk: 'Әрекеттер',
        de: 'Aktionen',
        fr: 'Actions',
        es: 'Acciones',
        pt: 'Ações',
        tr: 'İşlemler',
        uk: 'Дії',
        zh: '操作',
        ar: 'الإجراءات',
        pl: 'Akcje',
        it: 'Azioni',
      }),
    },
    usersTab: {
      hint: t({
        ru: 'Перейдите на страницу управления пользователями для настройки прав доступа.',
        en: 'Go to the user management page to configure access permissions.',
        kk: 'Қол жеткізу құқықтарын баптау үшін пайдаланушыларды басқару бетіне өтіңіз.',
        de: 'Gehen Sie zur Benutzerverwaltungsseite, um Zugriffsberechtigungen zu konfigurieren.',
        fr: 'Accédez à la page de gestion des utilisateurs pour configurer les autorisations d\'accès.',
        es: 'Ve a la página de gestión de usuarios para configurar los permisos de acceso.',
        pt: 'Acesse a página de gerenciamento de usuários para configurar permissões de acesso.',
        tr: 'Erişim izinlerini yapılandırmak için kullanıcı yönetimi sayfasına gidin.',
        uk: 'Перейдіть на сторінку управління користувачами для налаштування прав доступу.',
        zh: '前往用户管理页面配置访问权限。',
        ar: 'انتقل إلى صفحة إدارة المستخدمين لتكوين أذونات الوصول.',
        pl: 'Przejdź do strony zarządzania użytkownikami, aby skonfigurować uprawnienia dostępu.',
        it: 'Vai alla pagina di gestione utenti per configurare le autorizzazioni di accesso.',
      }),
      button: t({
        ru: 'Управление пользователями',
        en: 'Manage users',
        kk: 'Пайдаланушыларды басқару',
        de: 'Benutzer verwalten',
        fr: 'Gérer les utilisateurs',
        es: 'Gestionar usuarios',
        pt: 'Gerenciar usuários',
        tr: 'Kullanıcıları yönet',
        uk: 'Управління користувачами',
        zh: '管理用户',
        ar: 'إدارة المستخدمين',
        pl: 'Zarządzaj użytkownikami',
        it: 'Gestisci utenti',
      }),
    },
    auditTab: {
      empty: t({
        ru: 'Пока записей нет',
        en: 'No entries yet',
        kk: 'Әзірге жазбалар жоқ',
        de: 'Noch keine Einträge',
        fr: 'Aucune entrée pour l\'instant',
        es: 'Aún no hay entradas',
        pt: 'Nenhuma entrada ainda',
        tr: 'Henüz kayıt yok',
        uk: 'Поки записів немає',
        zh: '暂无记录',
        ar: 'لا توجد إدخالات بعد',
        pl: 'Brak wpisów',
        it: 'Nessuna voce ancora',
      }),
      title: t({
        ru: 'Аудит-лог',
        en: 'Audit log',
        kk: 'Аудит журналы',
        de: 'Audit-Protokoll',
        fr: 'Journal d\'audit',
        es: 'Registro de auditoría',
        pt: 'Log de auditoria',
        tr: 'Denetim günlüğü',
        uk: 'Журнал аудиту',
        zh: '审计日志',
        ar: 'سجل التدقيق',
        pl: 'Dziennik audytu',
        it: 'Log di audit',
      }),
      helper: t({
        ru: 'Отслеживайте действия в рабочем пространстве и откаты.',
        en: 'Track workspace activity and rollbacks.',
        kk: 'Жұмыс кеңістігіндегі әрекеттер мен қайтаруларды бақылаңыз.',
        de: 'Verfolgen Sie Workspace-Aktivitäten und Rollbacks.',
        fr: 'Suivez l\'activité de l\'espace de travail et les annulations.',
        es: 'Rastrea la actividad del workspace y las reversiones.',
        pt: 'Rastreie a atividade do workspace e reversões.',
        tr: 'Çalışma alanı etkinliğini ve geri almaları takip edin.',
        uk: 'Відстежуйте дії у робочому просторі та відкати.',
        zh: '跟踪工作空间活动和回滚。',
        ar: 'تتبع نشاط مساحة العمل وعمليات التراجع.',
        pl: 'Śledź aktywność obszaru roboczego i wycofania.',
        it: 'Monitora l\'attività del workspace e i rollback.',
      }),
      action: t({
        ru: 'Действие',
        en: 'Action',
        kk: 'Әрекет',
        de: 'Aktion',
        fr: 'Action',
        es: 'Acción',
        pt: 'Ação',
        tr: 'Eylem',
        uk: 'Дія',
        zh: '操作',
        ar: 'الإجراء',
        pl: 'Akcja',
        it: 'Azione',
      }),
      description: t({
        ru: 'Описание',
        en: 'Description',
        kk: 'Сипаттама',
        de: 'Beschreibung',
        fr: 'Description',
        es: 'Descripción',
        pt: 'Descrição',
        tr: 'Açıklama',
        uk: 'Опис',
        zh: '描述',
        ar: 'الوصف',
        pl: 'Opis',
        it: 'Descrizione',
      }),
      user: t({
        ru: 'Пользователь',
        en: 'User',
        kk: 'Пайдаланушы',
        de: 'Benutzer',
        fr: 'Utilisateur',
        es: 'Usuario',
        pt: 'Usuário',
        tr: 'Kullanıcı',
        uk: 'Користувач',
        zh: '用户',
        ar: 'المستخدم',
        pl: 'Użytkownik',
        it: 'Utente',
      }),
      date: t({
        ru: 'Дата',
        en: 'Date',
        kk: 'Күні',
        de: 'Datum',
        fr: 'Date',
        es: 'Fecha',
        pt: 'Data',
        tr: 'Tarih',
        uk: 'Дата',
        zh: '日期',
        ar: 'التاريخ',
        pl: 'Data',
        it: 'Data',
      }),
      loading: t({
        ru: 'Загрузка событий аудита...',
        en: 'Loading audit events...',
        kk: 'Аудит оқиғалары жүктелуде...',
        de: 'Audit-Ereignisse werden geladen...',
        fr: 'Chargement des événements d\'audit...',
        es: 'Cargando eventos de auditoría...',
        pt: 'Carregando eventos de auditoria...',
        tr: 'Denetim olayları yükleniyor...',
        uk: 'Завантаження подій аудиту...',
        zh: '加载审计事件中...',
        ar: 'جارٍ تحميل أحداث التدقيق...',
        pl: 'Ładowanie zdarzeń audytu...',
        it: 'Caricamento eventi di audit...',
      }),
      filters: {
        title: t({
          ru: 'Фильтры',
          en: 'Filters',
          kk: 'Сүзгілер',
          de: 'Filter',
          fr: 'Filtres',
          es: 'Filtros',
          pt: 'Filtros',
          tr: 'Filtreler',
          uk: 'Фільтри',
          zh: '筛选',
          ar: 'الفلاتر',
          pl: 'Filtry',
          it: 'Filtri',
        }),
        all: t({
          ru: 'Все',
          en: 'All',
          kk: 'Барлығы',
          de: 'Alle',
          fr: 'Tout',
          es: 'Todos',
          pt: 'Todos',
          tr: 'Tümü',
          uk: 'Всі',
          zh: '全部',
          ar: 'الكل',
          pl: 'Wszystkie',
          it: 'Tutti',
        }),
        entityType: t({
          ru: 'Тип сущности',
          en: 'Entity Type',
          kk: 'Мән түрі',
          de: 'Entitätstyp',
          fr: 'Type d\'entité',
          es: 'Tipo de entidad',
          pt: 'Tipo de entidade',
          tr: 'Varlık türü',
          uk: 'Тип сутності',
          zh: '实体类型',
          ar: 'نوع الكيان',
          pl: 'Typ encji',
          it: 'Tipo entità',
        }),
        user: t({
          ru: 'Пользователь',
          en: 'User',
          kk: 'Пайдаланушы',
          de: 'Benutzer',
          fr: 'Utilisateur',
          es: 'Usuario',
          pt: 'Usuário',
          tr: 'Kullanıcı',
          uk: 'Користувач',
          zh: '用户',
          ar: 'المستخدم',
          pl: 'Użytkownik',
          it: 'Utente',
        }),
        action: t({
          ru: 'Действие',
          en: 'Action',
          kk: 'Әрекет',
          de: 'Aktion',
          fr: 'Action',
          es: 'Acción',
          pt: 'Ação',
          tr: 'Eylem',
          uk: 'Дія',
          zh: '操作',
          ar: 'الإجراء',
          pl: 'Akcja',
          it: 'Azione',
        }),
        entityId: t({
          ru: 'ID сущности',
          en: 'Entity ID',
          kk: 'Мән ID',
          de: 'Entitäts-ID',
          fr: 'ID d\'entité',
          es: 'ID de entidad',
          pt: 'ID da entidade',
          tr: 'Varlık ID\'si',
          uk: 'ID сутності',
          zh: '实体 ID',
          ar: 'معرّف الكيان',
          pl: 'ID encji',
          it: 'ID entità',
        }),
        severity: t({
          ru: 'Серьезность',
          en: 'Severity',
          kk: 'Маңыздылық',
          de: 'Schweregrad',
          fr: 'Gravité',
          es: 'Gravedad',
          pt: 'Severidade',
          tr: 'Önem derecesi',
          uk: 'Серйозність',
          zh: '严重性',
          ar: 'الخطورة',
          pl: 'Powaga',
          it: 'Gravità',
        }),
        dateFrom: t({
          ru: 'Дата от',
          en: 'Date From',
          kk: 'Күні бастап',
          de: 'Datum von',
          fr: 'Date de début',
          es: 'Fecha desde',
          pt: 'Data de início',
          tr: 'Başlangıç tarihi',
          uk: 'Дата від',
          zh: '开始日期',
          ar: 'التاريخ من',
          pl: 'Data od',
          it: 'Data da',
        }),
        dateTo: t({
          ru: 'Дата до',
          en: 'Date To',
          kk: 'Күні дейін',
          de: 'Datum bis',
          fr: 'Date de fin',
          es: 'Fecha hasta',
          pt: 'Data de fim',
          tr: 'Bitiş tarihi',
          uk: 'Дата до',
          zh: '结束日期',
          ar: 'التاريخ إلى',
          pl: 'Data do',
          it: 'Data a',
        }),
      },
    },
    errorDialog: {
      title: t({
        ru: 'Детали ошибки',
        en: 'Error details',
        kk: 'Қате мәліметтері',
        de: 'Fehlerdetails',
        fr: 'Détails de l\'erreur',
        es: 'Detalles del error',
        pt: 'Detalhes do erro',
        tr: 'Hata ayrıntıları',
        uk: 'Деталі помилки',
        zh: '错误详情',
        ar: 'تفاصيل الخطأ',
        pl: 'Szczegóły błędu',
        it: 'Dettagli errore',
      }),
      close: t({
        ru: 'Закрыть',
        en: 'Close',
        kk: 'Жабу',
        de: 'Schließen',
        fr: 'Fermer',
        es: 'Cerrar',
        pt: 'Fechar',
        tr: 'Kapat',
        uk: 'Закрити',
        zh: '关闭',
        ar: 'إغلاق',
        pl: 'Zamknij',
        it: 'Chiudi',
      }),
    },
  },
} satisfies Dictionary;

export default content;
