import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'integrationsPage',
  content: {
    title: t({
      ru: 'Интеграции',
      en: 'Integrations',
      kk: 'Интеграциялар',
      de: 'Integrationen',
      fr: 'Intégrations',
      es: 'Integraciones',
      pt: 'Integrações',
      tr: 'Entegrasyonlar',
      uk: 'Інтеграції',
      zh: '集成',
      ar: 'التكاملات',
      pl: 'Integracje',
      it: 'Integrazioni',
      sk: 'Integracje',
    }),
    subtitle: t({
      ru: 'Подключайте внешние сервисы и автоматизируйте обмен данными.',
      en: 'Connect external services and automate data exchange.',
      kk: 'Сыртқы сервистерді қосып, деректер алмасуын автоматтандырыңыз.',
      de: 'Verbinden Sie externe Dienste und automatisieren Sie den Datenaustausch.',
      fr: 'Connectez des services externes et automatisez les échanges de données.',
      es: 'Conecta servicios externos y automatiza el intercambio de datos.',
      pt: 'Conecte serviços externos e automatize a troca de dados.',
      tr: 'Harici hizmetleri bağlayın ve veri alışverişini otomatikleştirin.',
      uk: 'Підключайте зовнішні сервіси та автоматизуйте обмін даними.',
      zh: '连接外部服务并自动化数据交换。',
      ar: 'قم بتوصيل الخدمات الخارجية وأتمتة تبادل البيانات.',
      pl: 'Połącz zewnętrzne usługi i zautomatyzuj wymianę danych.',
      it: 'Connetti servizi esterni e automatizza lo scambio di dati.',
      sk: 'Połącz zewnętrzne usługi i zautomatyzuj wymianę danych.',
    }),
    sections: {
      connected: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылған',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlı',
        uk: 'Підключено',
        zh: '已连接',
        ar: 'متصل',
        pl: 'Połączone',
        it: 'Connesso',
        sk: 'Połączone',
      }),
      available: t({
        ru: 'Доступно к подключению',
        en: 'Available',
        kk: 'Қолжетімді',
        de: 'Verfügbar',
        fr: 'Disponible',
        es: 'Disponible',
        pt: 'Disponível',
        tr: 'Mevcut',
        uk: 'Доступно',
        zh: '可用',
        ar: 'متاح',
        pl: 'Dostępne',
        it: 'Disponibile',
        sk: 'Dostępne',
      }),
    },
    banner: t({
      ru: 'Начните отсюда: подключите Gmail или Google Диск для автоматического импорта чеков и выписок.',
      en: 'Start here: Connect Gmail or Google Drive to automatically import receipts and statements.',
      kk: 'Осыдан бастаңыз: түбіртектер мен үзінділерді автоматты түрде импорттау үшін Gmail немесе Google Drive қосыңыз.',
      de: 'Starten Sie hier: Verbinden Sie Gmail oder Google Drive, um Belege und Kontoauszüge automatisch zu importieren.',
      fr: 'Commencez ici : connectez Gmail ou Google Drive pour importer automatiquement les reçus et relevés.',
      es: 'Empieza aquí: conecta Gmail o Google Drive para importar automáticamente recibos y extractos.',
      pt: 'Comece aqui: conecte o Gmail ou o Google Drive para importar automaticamente recibos e extratos.',
      tr: 'Buradan başlayın: Makbuz ve ekstreleri otomatik olarak içe aktarmak için Gmail veya Google Drive\'ı bağlayın.',
      uk: 'Почніть тут: підключіть Gmail або Google Диск для автоматичного імпорту чеків та виписок.',
      zh: '从这里开始：连接 Gmail 或 Google Drive 以自动导入收据和账单。',
      ar: 'ابدأ من هنا: قم بتوصيل Gmail أو Google Drive لاستيراد الإيصالات والكشوفات تلقائيًا.',
      pl: 'Zacznij tutaj: połącz Gmail lub Google Drive, aby automatycznie importować paragony i wyciągi.',
      it: 'Inizia qui: collega Gmail o Google Drive per importare automaticamente ricevute ed estratti conto.',
      sk: 'Zacznij tutaj: połącz Gmail lub Google Drive, aby automatycznie importować paragony i wyciągi.',
    }),
    recommendedBadge: t({
      ru: 'Рекомендуется',
      en: 'Recommended',
      kk: 'Ұсынылады',
      de: 'Empfohlen',
      fr: 'Recommandé',
      es: 'Recomendado',
      pt: 'Recomendado',
      tr: 'Önerilen',
      uk: 'Рекомендовано',
      zh: '推荐',
      ar: 'موصى به',
      pl: 'Polecane',
      it: 'Consigliato',
      sk: 'Polecane',
    }),
    empty: {
      connected: t({
        ru: 'Пока нет активных интеграций.',
        en: 'No active integrations yet.',
        kk: 'Әзірше белсенді интеграциялар жоқ.',
        de: 'Noch keine aktiven Integrationen.',
        fr: 'Aucune intégration active pour l\'instant.',
        es: 'Aún no hay integraciones activas.',
        pt: 'Nenhuma integração ativa ainda.',
        tr: 'Henüz aktif entegrasyon yok.',
        uk: 'Поки немає активних інтеграцій.',
        zh: '暂无活跃的集成。',
        ar: 'لا توجد تكاملات نشطة حتى الآن.',
        pl: 'Brak aktywnych integracji.',
        it: 'Nessuna integrazione attiva ancora.',
        sk: 'Brak aktywnych integracji.',
      }),
      available: t({
        ru: 'Нет доступных интеграций.',
        en: 'No integrations available.',
        kk: 'Қолжетімді интеграциялар жоқ.',
        de: 'Keine Integrationen verfügbar.',
        fr: 'Aucune intégration disponible.',
        es: 'No hay integraciones disponibles.',
        pt: 'Nenhuma integração disponível.',
        tr: 'Mevcut entegrasyon yok.',
        uk: 'Немає доступних інтеграцій.',
        zh: '没有可用的集成。',
        ar: 'لا تتوفر تكاملات.',
        pl: 'Brak dostępnych integracji.',
        it: 'Nessuna integrazione disponibile.',
        sk: 'Brak dostępnych integracji.',
      }),
    },
    categories: {
      storage: t({
        ru: 'Файловые хранилища',
        en: 'Storage',
        kk: 'Файл қоймалары',
        de: 'Datenspeicher',
        fr: 'Stockage',
        es: 'Almacenamiento',
        pt: 'Armazenamento',
        tr: 'Depolama',
        uk: 'Файлові сховища',
        zh: '存储',
        ar: 'التخزين',
        pl: 'Przechowywanie',
        it: 'Archiviazione',
        sk: 'Przechowywanie',
      }),
      email: t({
        ru: 'Почта',
        en: 'Email',
        kk: 'Пошта',
        de: 'E-Mail',
        fr: 'E-mail',
        es: 'Correo electrónico',
        pt: 'E-mail',
        tr: 'E-posta',
        uk: 'Пошта',
        zh: '邮件',
        ar: 'البريد الإلكتروني',
        pl: 'Poczta',
        it: 'Email',
        sk: 'Poczta',
      }),
      spreadsheets: t({
        ru: 'Таблицы',
        en: 'Spreadsheets',
        kk: 'Кестелер',
        de: 'Tabellen',
        fr: 'Tableurs',
        es: 'Hojas de cálculo',
        pt: 'Planilhas',
        tr: 'Tablolar',
        uk: 'Таблиці',
        zh: '电子表格',
        ar: 'جداول البيانات',
        pl: 'Arkusze',
        it: 'Fogli di calcolo',
        sk: 'Arkusze',
      }),
      messaging: t({
        ru: 'Мессенджеры',
        en: 'Messaging',
        kk: 'Мессенджерлер',
        de: 'Messenger',
        fr: 'Messagerie',
        es: 'Mensajería',
        pt: 'Mensagens',
        tr: 'Mesajlaşma',
        uk: 'Месенджери',
        zh: '消息',
        ar: 'المراسلة',
        pl: 'Komunikatory',
        it: 'Messaggistica',
        sk: 'Komunikatory',
      }),
    },
    searchPlaceholder: t({
      ru: 'Поиск интеграций...',
      en: 'Search integrations...',
      kk: 'Интеграцияларды іздеу...',
      de: 'Integrationen suchen...',
      fr: 'Rechercher des intégrations...',
      es: 'Buscar integraciones...',
      pt: 'Pesquisar integrações...',
      tr: 'Entegrasyon ara...',
      uk: 'Пошук інтеграцій...',
      zh: '搜索集成...',
      ar: 'البحث عن التكاملات...',
      pl: 'Szukaj integracji...',
      it: 'Cerca integrazioni...',
      sk: 'Szukaj integracji...',
    }),
    noResults: t({
      ru: 'Ничего не найдено',
      en: 'Nothing found',
      kk: 'Ештеңе табылмады',
      de: 'Nichts gefunden',
      fr: 'Aucun résultat',
      es: 'No se encontró nada',
      pt: 'Nada encontrado',
      tr: 'Hiçbir şey bulunamadı',
      uk: 'Нічого не знайдено',
      zh: '未找到任何内容',
      ar: 'لم يتم العثور على شيء',
      pl: 'Nic nie znaleziono',
      it: 'Nessun risultato',
      sk: 'Nic nie znaleziono',
    }),
    noResultsDescription: t({
      ru: 'По запросу «{{query}}» нет подходящих интеграций.',
      en: 'No matching integrations found for "{{query}}".',
      kk: '«{{query}}» сұрауы бойынша сәйкес интеграциялар табылмады.',
      de: 'Keine passenden Integrationen für „{{query}}" gefunden.',
      fr: 'Aucune intégration correspondante trouvée pour « {{query}} ».',
      es: 'No se encontraron integraciones para "{{query}}".',
      pt: 'Nenhuma integração encontrada para "{{query}}".',
      tr: '"{{query}}" için eşleşen entegrasyon bulunamadı.',
      uk: 'За запитом «{{query}}» не знайдено відповідних інтеграцій.',
      zh: '未找到与"{{query}}"匹配的集成。',
      ar: 'لم يتم العثور على تكاملات مطابقة لـ "{{query}}".',
      pl: 'Nie znaleziono integracji pasujących do „{{query}}".',
      it: 'Nessuna integrazione trovata per "{{query}}".',
      sk: 'Nie znaleziono integracji pasujących do „{{query}}".',
    }),
    resetSearch: t({
      ru: 'Сбросить поиск',
      en: 'Reset search',
      kk: 'Іздеуді қалпына келтіру',
      de: 'Suche zurücksetzen',
      fr: 'Réinitialiser la recherche',
      es: 'Restablecer búsqueda',
      pt: 'Redefinir busca',
      tr: 'Aramayı sıfırla',
      uk: 'Скинути пошук',
      zh: '重置搜索',
      ar: 'إعادة تعيين البحث',
      pl: 'Resetuj wyszukiwanie',
      it: 'Reimposta ricerca',
      sk: 'Resetuj wyszukiwanie',
    }),
    cards: {
      dropbox: {
        description: t({
          ru: 'Синхронизируйте выписки с Dropbox и импортируйте файлы за пару кликов.',
          en: 'Sync statements with Dropbox and import files in a few clicks.',
          kk: 'Үзінділерді Dropbox-пен синхрондап, файлдарды оңай импорттаңыз.',
          de: 'Synchronisieren Sie Kontoauszüge mit Dropbox und importieren Sie Dateien mit wenigen Klicks.',
          fr: 'Synchronisez les relevés avec Dropbox et importez des fichiers en quelques clics.',
          es: 'Sincroniza extractos con Dropbox e importa archivos en pocos clics.',
          pt: 'Sincronize extratos com o Dropbox e importe arquivos em poucos cliques.',
          tr: 'Ekstreleri Dropbox ile senkronize edin ve dosyaları birkaç tıkla içe aktarın.',
          uk: 'Синхронізуйте виписки з Dropbox та імпортуйте файли за кілька кліків.',
          zh: '将账单与 Dropbox 同步，几次点击即可导入文件。',
          ar: 'زامن الكشوفات مع Dropbox واستورد الملفات بنقرات قليلة.',
          pl: 'Synchronizuj wyciągi z Dropbox i importuj pliki za pomocą kilku kliknięć.',
          it: 'Sincronizza gli estratti con Dropbox e importa file in pochi clic.',
          sk: 'Synchronizuj wyciągi z Dropbox i importuj pliki za pomocą kilku kliknięć.',
        }),
        badge: t({
          ru: 'Доступно',
          en: 'Available',
          kk: 'Қолжетімді',
          de: 'Verfügbar',
          fr: 'Disponible',
          es: 'Disponible',
          pt: 'Disponível',
          tr: 'Mevcut',
          uk: 'Доступно',
          zh: '可用',
          ar: 'متاح',
          pl: 'Dostępne',
          it: 'Disponibile',
          sk: 'Dostępne',
        }),
        actions: {
          connect: t({
            ru: 'Подключить',
            en: 'Connect',
            kk: 'Қосу',
            de: 'Verbinden',
            fr: 'Connecter',
            es: 'Conectar',
            pt: 'Conectar',
            tr: 'Bağlan',
            uk: 'Підключити',
            zh: '连接',
            ar: 'اتصال',
            pl: 'Połącz',
            it: 'Connetti',
            sk: 'Połącz',
          }),
          docs: t({
            ru: 'Документация',
            en: 'Documentation',
            kk: 'Құжаттама',
            de: 'Dokumentation',
            fr: 'Documentation',
            es: 'Documentación',
            pt: 'Documentação',
            tr: 'Belgeler',
            uk: 'Документація',
            zh: '文档',
            ar: 'التوثيق',
            pl: 'Dokumentacja',
            it: 'Documentazione',
            sk: 'Dokumentacja',
          }),
        },
      },
      googleDrive: {
        description: t({
          ru: 'Синхронизируйте выписки с Google Drive и импортируйте файлы за пару кликов.',
          en: 'Sync statements with Google Drive and import files in a few clicks.',
          kk: 'Үзінділерді Google Drive-пен синхрондап, файлдарды оңай импорттаңыз.',
          de: 'Synchronisieren Sie Kontoauszüge mit Google Drive und importieren Sie Dateien mit wenigen Klicks.',
          fr: 'Synchronisez les relevés avec Google Drive et importez des fichiers en quelques clics.',
          es: 'Sincroniza extractos con Google Drive e importa archivos en pocos clics.',
          pt: 'Sincronize extratos com o Google Drive e importe arquivos em poucos cliques.',
          tr: 'Ekstreleri Google Drive ile senkronize edin ve dosyaları birkaç tıkla içe aktarın.',
          uk: 'Синхронізуйте виписки з Google Drive та імпортуйте файли за кілька кліків.',
          zh: '将账单与 Google Drive 同步，几次点击即可导入文件。',
          ar: 'زامن الكشوفات مع Google Drive واستورد الملفات بنقرات قليلة.',
          pl: 'Synchronizuj wyciągi z Google Drive i importuj pliki za pomocą kilku kliknięć.',
          it: 'Sincronizza gli estratti con Google Drive e importa file in pochi clic.',
          sk: 'Synchronizuj wyciągi z Google Drive i importuj pliki za pomocą kilku kliknięć.',
        }),
        badge: t({
          ru: 'Доступно',
          en: 'Available',
          kk: 'Қолжетімді',
          de: 'Verfügbar',
          fr: 'Disponible',
          es: 'Disponible',
          pt: 'Disponível',
          tr: 'Mevcut',
          uk: 'Доступно',
          zh: '可用',
          ar: 'متاح',
          pl: 'Dostępne',
          it: 'Disponibile',
          sk: 'Dostępne',
        }),
        actions: {
          connect: t({
            ru: 'Подключить',
            en: 'Connect',
            kk: 'Қосу',
            de: 'Verbinden',
            fr: 'Connecter',
            es: 'Conectar',
            pt: 'Conectar',
            tr: 'Bağlan',
            uk: 'Підключити',
            zh: '连接',
            ar: 'اتصال',
            pl: 'Połącz',
            it: 'Connetti',
            sk: 'Połącz',
          }),
          docs: t({
            ru: 'Документация',
            en: 'Documentation',
            kk: 'Құжаттама',
            de: 'Dokumentation',
            fr: 'Documentation',
            es: 'Documentación',
            pt: 'Documentação',
            tr: 'Belgeler',
            uk: 'Документація',
            zh: '文档',
            ar: 'التوثيق',
            pl: 'Dokumentacja',
            it: 'Documentazione',
            sk: 'Dokumentacja',
          }),
        },
      },
      googleSheets: {
        description: t({
          ru: 'Отправляйте распарсенные транзакции в выбранную таблицу.',
          en: 'Send parsed transactions to a selected spreadsheet.',
          kk: 'Өңделген транзакцияларды таңдалған кестеге жіберіңіз.',
          de: 'Senden Sie geparste Transaktionen an eine ausgewählte Tabelle.',
          fr: 'Envoyez les transactions analysées vers la feuille de calcul choisie.',
          es: 'Envía transacciones procesadas a la hoja de cálculo seleccionada.',
          pt: 'Envie transações processadas para a planilha selecionada.',
          tr: 'İşlenmiş işlemleri seçilen tabloya gönderin.',
          uk: 'Надсилайте оброблені транзакції до вибраної таблиці.',
          zh: '将解析的交易发送到选定的电子表格。',
          ar: 'أرسل المعاملات المعالجة إلى جدول البيانات المحدد.',
          pl: 'Wysyłaj przetworzone transakcje do wybranego arkusza.',
          it: 'Invia le transazioni elaborate al foglio di calcolo selezionato.',
          sk: 'Wysyłaj przetworzone transakcje do wybranego arkusza.',
        }),
        badge: t({
          ru: 'Доступно',
          en: 'Available',
          kk: 'Қолжетімді',
          de: 'Verfügbar',
          fr: 'Disponible',
          es: 'Disponible',
          pt: 'Disponível',
          tr: 'Mevcut',
          uk: 'Доступно',
          zh: '可用',
          ar: 'متاح',
          pl: 'Dostępne',
          it: 'Disponibile',
          sk: 'Dostępne',
        }),
        actions: {
          connect: t({
            ru: 'Подключить',
            en: 'Connect',
            kk: 'Қосу',
            de: 'Verbinden',
            fr: 'Connecter',
            es: 'Conectar',
            pt: 'Conectar',
            tr: 'Bağlan',
            uk: 'Підключити',
            zh: '连接',
            ar: 'اتصال',
            pl: 'Połącz',
            it: 'Connetti',
            sk: 'Połącz',
          }),
          docs: t({
            ru: 'Документация',
            en: 'Documentation',
            kk: 'Құжаттама',
            de: 'Dokumentation',
            fr: 'Documentation',
            es: 'Documentación',
            pt: 'Documentação',
            tr: 'Belgeler',
            uk: 'Документація',
            zh: '文档',
            ar: 'التوثيق',
            pl: 'Dokumentacja',
            it: 'Documentazione',
            sk: 'Dokumentacja',
          }),
        },
      },
      telegram: {
        description: t({
          ru: 'Получайте уведомления и отправляйте выписки через бота.',
          en: 'Receive notifications and send statements via a bot.',
          kk: 'Хабарламалар алып, үзінділерді бот арқылы жіберіңіз.',
          de: 'Erhalten Sie Benachrichtigungen und senden Sie Kontoauszüge über einen Bot.',
          fr: 'Recevez des notifications et envoyez des relevés via un bot.',
          es: 'Recibe notificaciones y envía extractos a través de un bot.',
          pt: 'Receba notificações e envie extratos por meio de um bot.',
          tr: 'Bildirim alın ve bir bot aracılığıyla ekstre gönderin.',
          uk: 'Отримуйте сповіщення та надсилайте виписки через бота.',
          zh: '通过机器人接收通知并发送账单。',
          ar: 'تلقَّ الإشعارات وأرسل الكشوفات عبر روبوت.',
          pl: 'Otrzymuj powiadomienia i wysyłaj wyciągi przez bota.',
          it: 'Ricevi notifiche e invia estratti tramite un bot.',
          sk: 'Otrzymuj powiadomienia i wysyłaj wyciągi przez bota.',
        }),
        badge: t({
          ru: 'Скоро',
          en: 'Coming soon',
          kk: 'Жақында',
          de: 'Demnächst',
          fr: 'Bientôt disponible',
          es: 'Próximamente',
          pt: 'Em breve',
          tr: 'Yakında',
          uk: 'Незабаром',
          zh: '即将推出',
          ar: 'قريبًا',
          pl: 'Wkrótce',
          it: 'Prossimamente',
          sk: 'Wkrótce',
        }),
        actions: {
          setup: t({
            ru: 'Настроить бота',
            en: 'Set up bot',
            kk: 'Ботты баптау',
            de: 'Bot einrichten',
            fr: 'Configurer le bot',
            es: 'Configurar bot',
            pt: 'Configurar bot',
            tr: 'Botu kur',
            uk: 'Налаштувати бота',
            zh: '设置机器人',
            ar: 'إعداد الروبوت',
            pl: 'Skonfiguruj bota',
            it: 'Configura bot',
            sk: 'Skonfiguruj bota',
          }),
          guide: t({
            ru: 'Руководство',
            en: 'Guide',
            kk: 'Нұсқаулық',
            de: 'Anleitung',
            fr: 'Guide',
            es: 'Guía',
            pt: 'Guia',
            tr: 'Kılavuz',
            uk: 'Посібник',
            zh: '指南',
            ar: 'دليل',
            pl: 'Przewodnik',
            it: 'Guida',
            sk: 'Przewodnik',
          }),
        },
      },
    },
  },
} satisfies Dictionary;

export default content;
