import { type DeclarationContent, t } from 'intlayer';

export default {
  key: 'workspaces-selector',
  content: {
    title: t({
      en: 'Select Workspace',
      ru: 'Выбрать рабочее пространство',
      kk: 'Жұмыс кеңістігін таңдау',
      de: 'Arbeitsbereich auswählen',
      fr: 'Sélectionner un espace de travail',
      es: 'Seleccionar espacio de trabajo',
      pt: 'Selecionar espaço de trabalho',
      tr: 'Çalışma Alanı Seç',
      uk: 'Вибрати робочий простір',
      zh: '选择工作区',
      ar: 'اختر مساحة العمل',
      pl: 'Wybierz obszar roboczy',
      it: 'Seleziona area di lavoro',
      sk: 'Wybierz obszar roboczy',
    }),
    subtitle: t({
      en: 'Choose a workspace to continue',
      ru: 'Выберите рабочее пространство для продолжения',
      kk: 'Жалғастыру үшін жұмыс кеңістігін таңдаңыз',
      de: 'Wählen Sie einen Arbeitsbereich, um fortzufahren',
      fr: 'Choisissez un espace de travail pour continuer',
      es: 'Elige un espacio de trabajo para continuar',
      pt: 'Escolha um espaço de trabalho para continuar',
      tr: 'Devam etmek için bir çalışma alanı seçin',
      uk: 'Виберіть робочий простір для продовження',
      zh: '选择一个工作区以继续',
      ar: 'اختر مساحة عمل للمتابعة',
      pl: 'Wybierz obszar roboczy, aby kontynuować',
      it: 'Scegli un\'area di lavoro per continuare',
      sk: 'Wybierz obszar roboczy, aby kontynuować',
    }),
    createWorkspace: t({
      en: 'Create New Workspace',
      ru: 'Создать новое пространство',
      kk: 'Жаңа кеңістік құру',
      de: 'Neuen Arbeitsbereich erstellen',
      fr: 'Créer un nouvel espace de travail',
      es: 'Crear nuevo espacio de trabajo',
      pt: 'Criar novo espaço de trabalho',
      tr: 'Yeni Çalışma Alanı Oluştur',
      uk: 'Створити новий робочий простір',
      zh: '创建新工作区',
      ar: 'إنشاء مساحة عمل جديدة',
      pl: 'Utwórz nowy obszar roboczy',
      it: 'Crea nuova area di lavoro',
      sk: 'Utwórz nowy obszar roboczy',
    }),
    noWorkspaces: t({
      en: 'You have no workspaces yet',
      ru: 'У вас пока нет рабочих пространств',
      kk: 'Әзірге жұмыс кеңістіктері жоқ',
      de: 'Sie haben noch keine Arbeitsbereiche',
      fr: 'Vous n\'avez pas encore d\'espaces de travail',
      es: 'Aún no tienes espacios de trabajo',
      pt: 'Você ainda não tem espaços de trabalho',
      tr: 'Henüz çalışma alanınız yok',
      uk: 'У вас ще немає робочих просторів',
      zh: '您还没有工作区',
      ar: 'ليس لديك مساحات عمل بعد',
      pl: 'Nie masz jeszcze obszarów roboczych',
      it: 'Non hai ancora aree di lavoro',
      sk: 'Nie masz jeszcze obszarów roboczych',
    }),
    loading: t({
      en: 'Loading workspaces...',
      ru: 'Загрузка пространств...',
      kk: 'Кеңістіктерді жүктеу...',
      de: 'Arbeitsbereiche werden geladen...',
      fr: 'Chargement des espaces de travail...',
      es: 'Cargando espacios de trabajo...',
      pt: 'Carregando espaços de trabalho...',
      tr: 'Çalışma alanları yükleniyor...',
      uk: 'Завантаження просторів...',
      zh: '正在加载工作区...',
      ar: 'جارٍ تحميل مساحات العمل...',
      pl: 'Ładowanie obszarów roboczych...',
      it: 'Caricamento aree di lavoro...',
      sk: 'Ładowanie obszarów roboczych...',
    }),
    searchPlaceholder: t({
      en: 'Search workspaces...',
      ru: 'Поиск по рабочим пространствам...',
      kk: 'Жұмыс кеңістіктері бойынша іздеу...',
      de: 'Arbeitsbereiche suchen...',
      fr: 'Rechercher des espaces de travail...',
      es: 'Buscar espacios de trabajo...',
      pt: 'Pesquisar espaços de trabalho...',
      tr: 'Çalışma alanlarında ara...',
      uk: 'Пошук по робочих просторах...',
      zh: '搜索工作区...',
      ar: 'البحث في مساحات العمل...',
      pl: 'Szukaj obszarów roboczych...',
      it: 'Cerca aree di lavoro...',
      sk: 'Szukaj obszarów roboczych...',
    }),
    members: t({
      en: 'members',
      ru: 'участников',
      kk: 'мүшелер',
      de: 'Mitglieder',
      fr: 'membres',
      es: 'miembros',
      pt: 'membros',
      tr: 'üye',
      uk: 'учасників',
      zh: '成员',
      ar: 'أعضاء',
      pl: 'członków',
      it: 'membri',
      sk: 'członków',
    }),
    integrations: t({
      en: 'integrations',
      ru: 'интеграций',
      kk: 'интеграциялар',
      de: 'Integrationen',
      fr: 'intégrations',
      es: 'integraciones',
      pt: 'integrações',
      tr: 'entegrasyonlar',
      uk: 'інтеграцій',
      zh: '集成',
      ar: 'تكاملات',
      pl: 'integracji',
      it: 'integrazioni',
      sk: 'integracji',
    }),
    activeRecently: t({
      en: 'Active recently',
      ru: 'Активно недавно',
      kk: 'Жақында белсенді',
      de: 'Kürzlich aktiv',
      fr: 'Actif récemment',
      es: 'Activo recientemente',
      pt: 'Ativo recentemente',
      tr: 'Son zamanlarda aktif',
      uk: 'Нещодавно активний',
      zh: '最近活跃',
      ar: 'نشط مؤخراً',
      pl: 'Niedawno aktywny',
      it: 'Attivo di recente',
      sk: 'Niedawno aktywny',
    }),
    roles: {
      owner: t({
        en: 'Owner',
        ru: 'Владелец',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
        sk: 'Właściciel',
      }),
      admin: t({
        en: 'Admin',
        ru: 'Администратор',
        kk: 'Әкімші',
        de: 'Administrator',
        fr: 'Administrateur',
        es: 'Administrador',
        pt: 'Administrador',
        tr: 'Yönetici',
        uk: 'Адміністратор',
        zh: '管理员',
        ar: 'مسؤول',
        pl: 'Administrator',
        it: 'Amministratore',
        sk: 'Administrator',
      }),
      member: t({
        en: 'Member',
        ru: 'Участник',
        kk: 'Мүше',
        de: 'Mitglied',
        fr: 'Membre',
        es: 'Miembro',
        pt: 'Membro',
        tr: 'Üye',
        uk: 'Учасник',
        zh: '成员',
        ar: 'عضو',
        pl: 'Członek',
        it: 'Membro',
        sk: 'Członek',
      }),
      viewer: t({
        en: 'Viewer',
        ru: 'Наблюдатель',
        kk: 'Қараушы',
        de: 'Betrachter',
        fr: 'Observateur',
        es: 'Observador',
        pt: 'Visualizador',
        tr: 'İzleyici',
        uk: 'Спостерігач',
        zh: '查看者',
        ar: 'مشاهد',
        pl: 'Obserwator',
        it: 'Visualizzatore',
        sk: 'Obserwator',
      }),
    },
  },
} satisfies DeclarationContent;
