import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'aiAssistantDrawer',
  content: {
    title: t({
      ru: 'AI Ассистент',
      en: 'AI Assistant',
      kk: 'AI Көмекші',
      de: 'KI-Assistent',
      fr: 'Assistant IA',
      es: 'Asistente IA',
      pt: 'Assistente IA',
      tr: 'Yapay Zeka Asistanı',
      uk: 'AI Асистент',
      zh: 'AI 助手',
      ar: 'مساعد الذكاء الاصطناعي',
      pl: 'Asystent AI',
      it: 'Assistente IA',
    }),
    subtitle: t({
      ru: 'Выберите анализ — данные будут переданы в ChatGPT',
      en: 'Choose an analysis — your data will be sent to ChatGPT',
      kk: 'Талдауды таңдаңыз — деректер ChatGPT-ге жіберіледі',
      de: 'Wählen Sie eine Analyse — Ihre Daten werden an ChatGPT gesendet',
      fr: 'Choisissez une analyse — vos données seront envoyées à ChatGPT',
      es: 'Elige un análisis — tus datos se enviarán a ChatGPT',
      pt: 'Escolha uma análise — seus dados serão enviados ao ChatGPT',
      tr: 'Bir analiz seçin — verileriniz ChatGPT\'ye gönderilecek',
      uk: 'Оберіть аналіз — дані будуть передані в ChatGPT',
      zh: '选择分析 — 您的数据将发送到 ChatGPT',
      ar: 'اختر تحليلًا — سيتم إرسال بياناتك إلى ChatGPT',
      pl: 'Wybierz analizę — dane zostaną wysłane do ChatGPT',
      it: 'Scegli un\'analisi — i tuoi dati verranno inviati a ChatGPT',
    }),
    run: t({
      ru: 'Открыть в ChatGPT',
      en: 'Open in ChatGPT',
      kk: 'ChatGPT-де ашу',
      de: 'In ChatGPT öffnen',
      fr: 'Ouvrir dans ChatGPT',
      es: 'Abrir en ChatGPT',
      pt: 'Abrir no ChatGPT',
      tr: 'ChatGPT\'de aç',
      uk: 'Відкрити в ChatGPT',
      zh: '在 ChatGPT 中打开',
      ar: 'فتح في ChatGPT',
      pl: 'Otwórz w ChatGPT',
      it: 'Apri in ChatGPT',
    }),
    loading: t({
      ru: 'Загрузка данных...',
      en: 'Loading data...',
      kk: 'Деректер жүктелуде...',
      de: 'Daten werden geladen...',
      fr: 'Chargement des données...',
      es: 'Cargando datos...',
      pt: 'Carregando dados...',
      tr: 'Veriler yükleniyor...',
      uk: 'Завантаження даних...',
      zh: '加载数据...',
      ar: 'جارٍ تحميل البيانات...',
      pl: 'Ładowanie danych...',
      it: 'Caricamento dati...',
    }),
    copied: t({
      ru: 'Промпт скопирован — вставьте в ChatGPT',
      en: 'Prompt copied — paste it into ChatGPT',
      kk: 'Промпт көшірілді — ChatGPT-ге қойыңыз',
      de: 'Prompt kopiert — in ChatGPT einfügen',
      fr: 'Prompt copié — collez-le dans ChatGPT',
      es: 'Prompt copiado — pégalo en ChatGPT',
      pt: 'Prompt copiado — cole no ChatGPT',
      tr: 'Prompt kopyalandı — ChatGPT\'ye yapıştırın',
      uk: 'Промпт скопійовано — вставте в ChatGPT',
      zh: '提示已复制 — 粘贴到 ChatGPT',
      ar: 'تم نسخ المطالبة — الصقها في ChatGPT',
      pl: 'Prompt skopiowany — wklej go do ChatGPT',
      it: 'Prompt copiato — incollalo in ChatGPT',
    }),
    cards: {
      expenseSummary: {
        title: t({
          ru: 'Анализ расходов',
          en: 'Expense Summary',
          kk: 'Шығыстар талдауы',
          de: 'Ausgabenübersicht',
          fr: 'Résumé des dépenses',
          es: 'Resumen de gastos',
          pt: 'Resumo de despesas',
          tr: 'Harcama özeti',
          uk: 'Аналіз витрат',
          zh: '费用摘要',
          ar: 'ملخص المصروفات',
          pl: 'Podsumowanie wydatków',
          it: 'Riepilogo spese',
        }),
        description: t({
          ru: 'Разбивка расходов по категориям за 30 дней с рекомендациями',
          en: 'Expense breakdown by category for 30 days with recommendations',
          kk: '30 күнге санаттар бойынша шығыстар бөлінісі мен ұсыныстар',
          de: 'Ausgabenaufschlüsselung nach Kategorie für 30 Tage mit Empfehlungen',
          fr: 'Ventilation des dépenses par catégorie sur 30 jours avec recommandations',
          es: 'Desglose de gastos por categoría de 30 días con recomendaciones',
          pt: 'Detalhamento de despesas por categoria de 30 dias com recomendações',
          tr: '30 günlük kategoriye göre harcama dökümü ve öneriler',
          uk: 'Розбивка витрат за категоріями за 30 днів з рекомендаціями',
          zh: '30天按类别的费用明细及建议',
          ar: 'تفصيل المصروفات حسب الفئة لمدة 30 يومًا مع التوصيات',
          pl: 'Zestawienie wydatków wg kategorii za 30 dni z rekomendacjami',
          it: 'Ripartizione spese per categoria di 30 giorni con raccomandazioni',
        }),
      },
      cashFlow: {
        title: t({
          ru: 'Денежный поток',
          en: 'Cash Flow Analysis',
          kk: 'Ақша ағыны',
          de: 'Cashflow-Analyse',
          fr: 'Analyse des flux de trésorerie',
          es: 'Análisis de flujo de caja',
          pt: 'Análise de fluxo de caixa',
          tr: 'Nakit akışı analizi',
          uk: 'Грошовий потік',
          zh: '现金流分析',
          ar: 'تحليل التدفق النقدي',
          pl: 'Analiza przepływów pieniężnych',
          it: 'Analisi flusso di cassa',
        }),
        description: t({
          ru: 'Тренды доходов и расходов с прогнозом',
          en: 'Income and expense trends with forecast',
          kk: 'Кірістер мен шығыстар трендтері болжаммен',
          de: 'Einnahmen- und Ausgabentrends mit Prognose',
          fr: 'Tendances revenus et dépenses avec prévision',
          es: 'Tendencias de ingresos y gastos con pronóstico',
          pt: 'Tendências de receitas e despesas com previsão',
          tr: 'Gelir ve gider trendleri tahminle birlikte',
          uk: 'Тренди доходів та витрат з прогнозом',
          zh: '收入和支出趋势及预测',
          ar: 'اتجاهات الدخل والمصروفات مع التوقعات',
          pl: 'Trendy przychodów i wydatków z prognozą',
          it: 'Tendenze entrate e uscite con previsione',
        }),
      },
      topCounterparties: {
        title: t({
          ru: 'Контрагенты',
          en: 'Top Counterparties',
          kk: 'Контрагенттер',
          de: 'Top-Geschäftspartner',
          fr: 'Principaux partenaires',
          es: 'Principales contrapartes',
          pt: 'Principais parceiros',
          tr: 'En çok işlem yapılanlar',
          uk: 'Контрагенти',
          zh: '主要交易对手',
          ar: 'أبرز الأطراف المقابلة',
          pl: 'Najważniejsi kontrahenci',
          it: 'Principali controparti',
        }),
        description: t({
          ru: 'Анализ ваших основных финансовых партнёров',
          en: 'Analysis of your key financial relationships',
          kk: 'Негізгі қаржылық серіктестеріңізді талдау',
          de: 'Analyse Ihrer wichtigsten Finanzbeziehungen',
          fr: 'Analyse de vos principales relations financières',
          es: 'Análisis de tus relaciones financieras clave',
          pt: 'Análise dos seus principais relacionamentos financeiros',
          tr: 'Temel finansal ilişkilerinizin analizi',
          uk: 'Аналіз ваших ключових фінансових партнерів',
          zh: '分析您的主要财务关系',
          ar: 'تحليل علاقاتك المالية الرئيسية',
          pl: 'Analiza kluczowych relacji finansowych',
          it: 'Analisi delle principali relazioni finanziarie',
        }),
      },
      taxPreparation: {
        title: t({
          ru: 'Налоговая подготовка',
          en: 'Tax Preparation',
          kk: 'Салық дайындығы',
          de: 'Steuervorbereitung',
          fr: 'Préparation fiscale',
          es: 'Preparación fiscal',
          pt: 'Preparação fiscal',
          tr: 'Vergi hazırlığı',
          uk: 'Податкова підготовка',
          zh: '税务准备',
          ar: 'إعداد الضرائب',
          pl: 'Przygotowanie podatkowe',
          it: 'Preparazione fiscale',
        }),
        description: t({
          ru: 'Сводка транзакций для налоговой отчётности за 90 дней',
          en: 'Transaction summary for tax reporting over 90 days',
          kk: '90 күнге салық есептілігі үшін транзакция жиынтығы',
          de: 'Transaktionsübersicht für die Steuererklärung über 90 Tage',
          fr: 'Résumé des transactions pour la déclaration fiscale sur 90 jours',
          es: 'Resumen de transacciones para declaración fiscal de 90 días',
          pt: 'Resumo de transações para declaração fiscal de 90 dias',
          tr: '90 günlük vergi raporlaması için işlem özeti',
          uk: 'Зведення транзакцій для податкової звітності за 90 днів',
          zh: '90天税务报告交易汇总',
          ar: 'ملخص المعاملات للإقرار الضريبي لمدة 90 يومًا',
          pl: 'Podsumowanie transakcji do rozliczenia podatkowego za 90 dni',
          it: 'Riepilogo transazioni per la dichiarazione fiscale di 90 giorni',
        }),
      },
      anomalyDetection: {
        title: t({
          ru: 'Поиск аномалий',
          en: 'Anomaly Detection',
          kk: 'Аномалияларды анықтау',
          de: 'Anomalieerkennung',
          fr: 'Détection d\'anomalies',
          es: 'Detección de anomalías',
          pt: 'Detecção de anomalias',
          tr: 'Anomali tespiti',
          uk: 'Пошук аномалій',
          zh: '异常检测',
          ar: 'كشف الشذوذ',
          pl: 'Wykrywanie anomalii',
          it: 'Rilevamento anomalie',
        }),
        description: t({
          ru: 'Поиск необычных транзакций и подозрительных паттернов',
          en: 'Find unusual transactions and suspicious patterns',
          kk: 'Әдеттен тыс транзакциялар мен күдікті үлгілерді табу',
          de: 'Ungewöhnliche Transaktionen und verdächtige Muster finden',
          fr: 'Recherche de transactions inhabituelles et de modèles suspects',
          es: 'Buscar transacciones inusuales y patrones sospechosos',
          pt: 'Encontrar transações incomuns e padrões suspeitos',
          tr: 'Olağandışı işlemleri ve şüpheli kalıpları bulun',
          uk: 'Пошук незвичайних транзакцій та підозрілих патернів',
          zh: '查找异常交易和可疑模式',
          ar: 'البحث عن معاملات غير عادية وأنماط مشبوهة',
          pl: 'Znajdź nietypowe transakcje i podejrzane wzorce',
          it: 'Trova transazioni insolite e modelli sospetti',
        }),
      },
      budgetRecommendations: {
        title: t({
          ru: 'Рекомендации по бюджету',
          en: 'Budget Recommendations',
          kk: 'Бюджет ұсыныстары',
          de: 'Budgetempfehlungen',
          fr: 'Recommandations budgétaires',
          es: 'Recomendaciones de presupuesto',
          pt: 'Recomendações de orçamento',
          tr: 'Bütçe önerileri',
          uk: 'Рекомендації щодо бюджету',
          zh: '预算建议',
          ar: 'توصيات الميزانية',
          pl: 'Rekomendacje budżetowe',
          it: 'Raccomandazioni di budget',
        }),
        description: t({
          ru: 'Персональный бюджетный план на основе ваших расходов',
          en: 'Personalized budget plan based on your spending',
          kk: 'Шығыстарыңыз негізінде жеке бюджет жоспары',
          de: 'Personalisierter Budgetplan basierend auf Ihren Ausgaben',
          fr: 'Plan budgétaire personnalisé basé sur vos dépenses',
          es: 'Plan de presupuesto personalizado basado en tus gastos',
          pt: 'Plano de orçamento personalizado com base em seus gastos',
          tr: 'Harcamalarınıza dayalı kişiselleştirilmiş bütçe planı',
          uk: 'Персональний бюджетний план на основі ваших витрат',
          zh: '根据您的支出定制的预算计划',
          ar: 'خطة ميزانية مخصصة بناءً على إنفاقك',
          pl: 'Spersonalizowany plan budżetowy na podstawie Twoich wydatków',
          it: 'Piano di budget personalizzato basato sulle tue spese',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
