import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'adminUsersPage',
  content: {
    title: t({
      ru: 'Управление пользователями',
      en: 'User management',
      kk: 'Пайдаланушыларды басқару',
      de: 'Benutzerverwaltung',
      fr: 'Gestion des utilisateurs',
      es: 'Gestión de usuarios',
      pt: 'Gerenciamento de usuários',
      tr: 'Kullanıcı yönetimi',
      uk: 'Управління користувачами',
      zh: '用户管理',
      ar: 'إدارة المستخدمين',
      pl: 'Zarządzanie użytkownikami',
      it: 'Gestione utenti',
    }),
    search: t({
      ru: 'Поиск',
      en: 'Search',
      kk: 'Іздеу',
      de: 'Suche',
      fr: 'Recherche',
      es: 'Buscar',
      pt: 'Pesquisar',
      tr: 'Ara',
      uk: 'Пошук',
      zh: '搜索',
      ar: 'بحث',
      pl: 'Szukaj',
      it: 'Cerca',
    }),
    refresh: t({
      ru: 'Обновить',
      en: 'Refresh',
      kk: 'Жаңарту',
      de: 'Aktualisieren',
      fr: 'Actualiser',
      es: 'Actualizar',
      pt: 'Atualizar',
      tr: 'Yenile',
      uk: 'Оновити',
      zh: '刷新',
      ar: 'تحديث',
      pl: 'Odśwież',
      it: 'Aggiorna',
    }),
    table: {
      email: t({ ru: 'Email', en: 'Email', kk: 'Email', de: 'E-Mail', fr: 'E-mail', es: 'Correo electrónico', pt: 'E-mail', tr: 'E-posta', uk: 'Email', zh: '邮箱', ar: 'البريد الإلكتروني', pl: 'E-mail', it: 'Email' }),
      name: t({
        ru: 'Имя',
        en: 'Name',
        kk: 'Аты',
        de: 'Name',
        fr: 'Nom',
        es: 'Nombre',
        pt: 'Nome',
        tr: 'Ad',
        uk: 'Ім\'я',
        zh: '姓名',
        ar: 'الاسم',
        pl: 'Imię',
        it: 'Nome',
      }),
      role: t({
        ru: 'Роль',
        en: 'Role',
        kk: 'Рөлі',
        de: 'Rolle',
        fr: 'Rôle',
        es: 'Rol',
        pt: 'Função',
        tr: 'Rol',
        uk: 'Роль',
        zh: '角色',
        ar: 'الدور',
        pl: 'Rola',
        it: 'Ruolo',
      }),
      status: t({
        ru: 'Статус',
        en: 'Status',
        kk: 'Күйі',
        de: 'Status',
        fr: 'Statut',
        es: 'Estado',
        pt: 'Status',
        tr: 'Durum',
        uk: 'Статус',
        zh: '状态',
        ar: 'الحالة',
        pl: 'Status',
        it: 'Stato',
      }),
      permissions: t({
        ru: 'Права',
        en: 'Permissions',
        kk: 'Құқықтар',
        de: 'Berechtigungen',
        fr: 'Autorisations',
        es: 'Permisos',
        pt: 'Permissões',
        tr: 'İzinler',
        uk: 'Права',
        zh: '权限',
        ar: 'الأذونات',
        pl: 'Uprawnienia',
        it: 'Autorizzazioni',
      }),
      createdAt: t({
        ru: 'Дата регистрации',
        en: 'Registered at',
        kk: 'Тіркелген күні',
        de: 'Registrierungsdatum',
        fr: 'Date d\'inscription',
        es: 'Fecha de registro',
        pt: 'Data de registro',
        tr: 'Kayıt tarihi',
        uk: 'Дата реєстрації',
        zh: '注册日期',
        ar: 'تاريخ التسجيل',
        pl: 'Data rejestracji',
        it: 'Data di registrazione',
      }),
      actions: t({
        ru: 'Действия',
        en: 'Actions',
        kk: 'Әрекеттер',
        de: 'Aktionen',
        fr: 'Actions',
        es: 'Acciones',
        pt: 'Ações',
        tr: 'İşlemler',
        uk: 'Дії',
        zh: '操作',
        ar: 'الإجراءات',
        pl: 'Akcje',
        it: 'Azioni',
      }),
    },
    roles: {
      admin: t({
        ru: 'Администратор',
        en: 'Administrator',
        kk: 'Әкімші',
        de: 'Administrator',
        fr: 'Administrateur',
        es: 'Administrador',
        pt: 'Administrador',
        tr: 'Yönetici',
        uk: 'Адміністратор',
        zh: '管理员',
        ar: 'المشرف',
        pl: 'Administrator',
        it: 'Amministratore',
      }),
      user: t({
        ru: 'Пользователь',
        en: 'User',
        kk: 'Пайдаланушы',
        de: 'Benutzer',
        fr: 'Utilisateur',
        es: 'Usuario',
        pt: 'Usuário',
        tr: 'Kullanıcı',
        uk: 'Користувач',
        zh: '用户',
        ar: 'مستخدم',
        pl: 'Użytkownik',
        it: 'Utente',
      }),
      viewer: t({
        ru: 'Наблюдатель',
        en: 'Viewer',
        kk: 'Бақылаушы',
        de: 'Betrachter',
        fr: 'Observateur',
        es: 'Observador',
        pt: 'Visualizador',
        tr: 'İzleyici',
        uk: 'Спостерігач',
        zh: '查看者',
        ar: 'مشاهد',
        pl: 'Obserwator',
        it: 'Visualizzatore',
      }),
    },
    status: {
      active: t({
        ru: 'Активен',
        en: 'Active',
        kk: 'Белсенді',
        de: 'Aktiv',
        fr: 'Actif',
        es: 'Activo',
        pt: 'Ativo',
        tr: 'Aktif',
        uk: 'Активний',
        zh: '活跃',
        ar: 'نشط',
        pl: 'Aktywny',
        it: 'Attivo',
      }),
      inactive: t({
        ru: 'Неактивен',
        en: 'Inactive',
        kk: 'Белсенді емес',
        de: 'Inaktiv',
        fr: 'Inactif',
        es: 'Inactivo',
        pt: 'Inativo',
        tr: 'Pasif',
        uk: 'Неактивний',
        zh: '非活跃',
        ar: 'غير نشط',
        pl: 'Nieaktywny',
        it: 'Inattivo',
      }),
    },
    permissionsChip: {
      default: t({
        ru: 'По умолчанию',
        en: 'Default',
        kk: 'Әдепкі',
        de: 'Standard',
        fr: 'Par défaut',
        es: 'Por defecto',
        pt: 'Padrão',
        tr: 'Varsayılan',
        uk: 'За замовчуванням',
        zh: '默认',
        ar: 'افتراضي',
        pl: 'Domyślne',
        it: 'Predefinito',
      }),
    },
    tooltips: {
      managePermissions: t({
        ru: 'Управление правами',
        en: 'Manage permissions',
        kk: 'Құқықтарды басқару',
        de: 'Berechtigungen verwalten',
        fr: 'Gérer les autorisations',
        es: 'Gestionar permisos',
        pt: 'Gerenciar permissões',
        tr: 'İzinleri yönet',
        uk: 'Управління правами',
        zh: '管理权限',
        ar: 'إدارة الأذونات',
        pl: 'Zarządzaj uprawnieniami',
        it: 'Gestisci autorizzazioni',
      }),
    },
    dialog: {
      titlePrefix: t({
        ru: 'Управление правами',
        en: 'Manage permissions',
        kk: 'Құқықтарды басқару',
        de: 'Berechtigungen verwalten',
        fr: 'Gérer les autorisations',
        es: 'Gestionar permisos',
        pt: 'Gerenciar permissões',
        tr: 'İzinleri yönet',
        uk: 'Управління правами',
        zh: '管理权限',
        ar: 'إدارة الأذونات',
        pl: 'Zarządzaj uprawnieniami',
        it: 'Gestisci autorizzazioni',
      }),
      rolePrefix: t({
        ru: 'Роль',
        en: 'Role',
        kk: 'Рөл',
        de: 'Rolle',
        fr: 'Rôle',
        es: 'Rol',
        pt: 'Função',
        tr: 'Rol',
        uk: 'Роль',
        zh: '角色',
        ar: 'الدور',
        pl: 'Rola',
        it: 'Ruolo',
      }),
      subtitleSuffix: t({
        ru: 'Выберите дополнительные права доступа:',
        en: 'Select additional permissions:',
        kk: 'Қосымша құқықтарды таңдаңыз:',
        de: 'Zusätzliche Berechtigungen auswählen:',
        fr: 'Sélectionnez des autorisations supplémentaires :',
        es: 'Selecciona permisos adicionales:',
        pt: 'Selecione permissões adicionais:',
        tr: 'Ek izinleri seçin:',
        uk: 'Виберіть додаткові права доступу:',
        zh: '选择附加权限：',
        ar: 'اختر أذونات إضافية:',
        pl: 'Wybierz dodatkowe uprawnienia:',
        it: 'Seleziona autorizzazioni aggiuntive:',
      }),
      resetDefaults: t({
        ru: 'Сбросить к умолчаниям',
        en: 'Reset to defaults',
        kk: 'Әдепкіге қайтару',
        de: 'Auf Standard zurücksetzen',
        fr: 'Réinitialiser aux valeurs par défaut',
        es: 'Restablecer valores predeterminados',
        pt: 'Redefinir para padrões',
        tr: 'Varsayılanlara sıfırla',
        uk: 'Скинути до значень за замовчуванням',
        zh: '重置为默认值',
        ar: 'إعادة الضبط إلى الافتراضي',
        pl: 'Zresetuj do domyślnych',
        it: 'Ripristina predefiniti',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
      }),
      save: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Speichern',
        fr: 'Enregistrer',
        es: 'Guardar',
        pt: 'Salvar',
        tr: 'Kaydet',
        uk: 'Зберегти',
        zh: '保存',
        ar: 'حفظ',
        pl: 'Zapisz',
        it: 'Salva',
      }),
    },
    errors: {
      loadUsers: t({
        ru: 'Ошибка загрузки пользователей',
        en: 'Failed to load users',
        kk: 'Пайдаланушыларды жүктеу қатесі',
        de: 'Fehler beim Laden der Benutzer',
        fr: 'Erreur lors du chargement des utilisateurs',
        es: 'Error al cargar usuarios',
        pt: 'Erro ao carregar usuários',
        tr: 'Kullanıcılar yüklenemedi',
        uk: 'Помилка завантаження користувачів',
        zh: '加载用户失败',
        ar: 'فشل تحميل المستخدمين',
        pl: 'Błąd ładowania użytkowników',
        it: 'Errore nel caricamento degli utenti',
      }),
      loadPermissions: t({
        ru: 'Ошибка загрузки прав',
        en: 'Failed to load permissions',
        kk: 'Құқықтарды жүктеу қатесі',
        de: 'Fehler beim Laden der Berechtigungen',
        fr: 'Erreur lors du chargement des autorisations',
        es: 'Error al cargar permisos',
        pt: 'Erro ao carregar permissões',
        tr: 'İzinler yüklenemedi',
        uk: 'Помилка завантаження прав',
        zh: '加载权限失败',
        ar: 'فشل تحميل الأذونات',
        pl: 'Błąd ładowania uprawnień',
        it: 'Errore nel caricamento delle autorizzazioni',
      }),
      savePermissions: t({
        ru: 'Ошибка сохранения прав',
        en: 'Failed to save permissions',
        kk: 'Құқықтарды сақтау қатесі',
        de: 'Fehler beim Speichern der Berechtigungen',
        fr: 'Erreur lors de l\'enregistrement des autorisations',
        es: 'Error al guardar permisos',
        pt: 'Erro ao salvar permissões',
        tr: 'İzinler kaydedilemedi',
        uk: 'Помилка збереження прав',
        zh: '保存权限失败',
        ar: 'فشل حفظ الأذونات',
        pl: 'Błąd zapisywania uprawnień',
        it: 'Errore nel salvataggio delle autorizzazioni',
      }),
      resetPermissions: t({
        ru: 'Ошибка сброса прав',
        en: 'Failed to reset permissions',
        kk: 'Құқықтарды қалпына келтіру қатесі',
        de: 'Fehler beim Zurücksetzen der Berechtigungen',
        fr: 'Erreur lors de la réinitialisation des autorisations',
        es: 'Error al restablecer permisos',
        pt: 'Erro ao redefinir permissões',
        tr: 'İzinler sıfırlanamadı',
        uk: 'Помилка скидання прав',
        zh: '重置权限失败',
        ar: 'فشل إعادة تعيين الأذونات',
        pl: 'Błąd resetowania uprawnień',
        it: 'Errore nel ripristino delle autorizzazioni',
      }),
      updateRole: t({
        ru: 'Ошибка обновления роли',
        en: 'Failed to update role',
        kk: 'Рөлді жаңарту қатесі',
        de: 'Fehler beim Aktualisieren der Rolle',
        fr: 'Erreur lors de la mise à jour du rôle',
        es: 'Error al actualizar el rol',
        pt: 'Erro ao atualizar a função',
        tr: 'Rol güncellenemedi',
        uk: 'Помилка оновлення ролі',
        zh: '更新角色失败',
        ar: 'فشل تحديث الدور',
        pl: 'Błąd aktualizacji roli',
        it: 'Errore nell\'aggiornamento del ruolo',
      }),
      updateStatus: t({
        ru: 'Ошибка обновления статуса',
        en: 'Failed to update status',
        kk: 'Күйді жаңарту қатесі',
        de: 'Fehler beim Aktualisieren des Status',
        fr: 'Erreur lors de la mise à jour du statut',
        es: 'Error al actualizar el estado',
        pt: 'Erro ao atualizar o status',
        tr: 'Durum güncellenemedi',
        uk: 'Помилка оновлення статусу',
        zh: '更新状态失败',
        ar: 'فشل تحديث الحالة',
        pl: 'Błąd aktualizacji statusu',
        it: 'Errore nell\'aggiornamento dello stato',
      }),
    },
    permissions: {
      statementView: t({
        ru: 'Просмотр выписок',
        en: 'View statements',
        kk: 'Үзінділерді қарау',
        de: 'Kontoauszüge anzeigen',
        fr: 'Afficher les relevés',
        es: 'Ver extractos',
        pt: 'Visualizar extratos',
        tr: 'Ekstreleri görüntüle',
        uk: 'Перегляд виписок',
        zh: '查看账单',
        ar: 'عرض الكشوفات',
        pl: 'Przeglądaj wyciągi',
        it: 'Visualizza estratti',
      }),
      statementUpload: t({
        ru: 'Загрузка выписок',
        en: 'Upload statements',
        kk: 'Үзінділерді жүктеу',
        de: 'Kontoauszüge hochladen',
        fr: 'Télécharger des relevés',
        es: 'Subir extractos',
        pt: 'Fazer upload de extratos',
        tr: 'Ekstre yükle',
        uk: 'Завантаження виписок',
        zh: '上传账单',
        ar: 'رفع الكشوفات',
        pl: 'Przesyłaj wyciągi',
        it: 'Carica estratti',
      }),
      statementDelete: t({
        ru: 'Удаление выписок',
        en: 'Delete statements',
        kk: 'Үзінділерді жою',
        de: 'Kontoauszüge löschen',
        fr: 'Supprimer les relevés',
        es: 'Eliminar extractos',
        pt: 'Excluir extratos',
        tr: 'Ekstreleri sil',
        uk: 'Видалення виписок',
        zh: '删除账单',
        ar: 'حذف الكشوفات',
        pl: 'Usuń wyciągi',
        it: 'Elimina estratti',
      }),
      statementEdit: t({
        ru: 'Редактирование выписок',
        en: 'Edit statements',
        kk: 'Үзінділерді өңдеу',
        de: 'Kontoauszüge bearbeiten',
        fr: 'Modifier les relevés',
        es: 'Editar extractos',
        pt: 'Editar extratos',
        tr: 'Ekstreleri düzenle',
        uk: 'Редагування виписок',
        zh: '编辑账单',
        ar: 'تعديل الكشوفات',
        pl: 'Edytuj wyciągi',
        it: 'Modifica estratti',
      }),
      transactionView: t({
        ru: 'Просмотр транзакций',
        en: 'View transactions',
        kk: 'Транзакцияларды қарау',
        de: 'Transaktionen anzeigen',
        fr: 'Afficher les transactions',
        es: 'Ver transacciones',
        pt: 'Visualizar transações',
        tr: 'İşlemleri görüntüle',
        uk: 'Перегляд транзакцій',
        zh: '查看交易',
        ar: 'عرض المعاملات',
        pl: 'Przeglądaj transakcje',
        it: 'Visualizza transazioni',
      }),
      transactionEdit: t({
        ru: 'Редактирование транзакций',
        en: 'Edit transactions',
        kk: 'Транзакцияларды өңдеу',
        de: 'Transaktionen bearbeiten',
        fr: 'Modifier les transactions',
        es: 'Editar transacciones',
        pt: 'Editar transações',
        tr: 'İşlemleri düzenle',
        uk: 'Редагування транзакцій',
        zh: '编辑交易',
        ar: 'تعديل المعاملات',
        pl: 'Edytuj transakcje',
        it: 'Modifica transazioni',
      }),
      transactionDelete: t({
        ru: 'Удаление транзакций',
        en: 'Delete transactions',
        kk: 'Транзакцияларды жою',
        de: 'Transaktionen löschen',
        fr: 'Supprimer les transactions',
        es: 'Eliminar transacciones',
        pt: 'Excluir transações',
        tr: 'İşlemleri sil',
        uk: 'Видалення транзакцій',
        zh: '删除交易',
        ar: 'حذف المعاملات',
        pl: 'Usuń transakcje',
        it: 'Elimina transazioni',
      }),
      transactionBulkUpdate: t({
        ru: 'Массовое обновление транзакций',
        en: 'Bulk update transactions',
        kk: 'Транзакцияларды жаппай жаңарту',
        de: 'Transaktionen massenweise aktualisieren',
        fr: 'Mise à jour groupée des transactions',
        es: 'Actualización masiva de transacciones',
        pt: 'Atualização em massa de transações',
        tr: 'İşlemleri toplu güncelle',
        uk: 'Масове оновлення транзакцій',
        zh: '批量更新交易',
        ar: 'تحديث جماعي للمعاملات',
        pl: 'Zbiorcza aktualizacja transakcji',
        it: 'Aggiornamento in blocco transazioni',
      }),
      categoryView: t({
        ru: 'Просмотр категорий',
        en: 'View categories',
        kk: 'Санаттарды қарау',
        de: 'Kategorien anzeigen',
        fr: 'Afficher les catégories',
        es: 'Ver categorías',
        pt: 'Visualizar categorias',
        tr: 'Kategorileri görüntüle',
        uk: 'Перегляд категорій',
        zh: '查看类别',
        ar: 'عرض الفئات',
        pl: 'Przeglądaj kategorie',
        it: 'Visualizza categorie',
      }),
      categoryCreate: t({
        ru: 'Создание категорий',
        en: 'Create categories',
        kk: 'Санат құру',
        de: 'Kategorien erstellen',
        fr: 'Créer des catégories',
        es: 'Crear categorías',
        pt: 'Criar categorias',
        tr: 'Kategori oluştur',
        uk: 'Створення категорій',
        zh: '创建类别',
        ar: 'إنشاء الفئات',
        pl: 'Twórz kategorie',
        it: 'Crea categorie',
      }),
      categoryEdit: t({
        ru: 'Редактирование категорий',
        en: 'Edit categories',
        kk: 'Санаттарды өңдеу',
        de: 'Kategorien bearbeiten',
        fr: 'Modifier les catégories',
        es: 'Editar categorías',
        pt: 'Editar categorias',
        tr: 'Kategorileri düzenle',
        uk: 'Редагування категорій',
        zh: '编辑类别',
        ar: 'تعديل الفئات',
        pl: 'Edytuj kategorie',
        it: 'Modifica categorie',
      }),
      categoryDelete: t({
        ru: 'Удаление категорий',
        en: 'Delete categories',
        kk: 'Санаттарды жою',
        de: 'Kategorien löschen',
        fr: 'Supprimer les catégories',
        es: 'Eliminar categorías',
        pt: 'Excluir categorias',
        tr: 'Kategorileri sil',
        uk: 'Видалення категорій',
        zh: '删除类别',
        ar: 'حذف الفئات',
        pl: 'Usuń kategorie',
        it: 'Elimina categorie',
      }),
      branchView: t({
        ru: 'Просмотр филиалов',
        en: 'View branches',
        kk: 'Филиалдарды қарау',
        de: 'Filialen anzeigen',
        fr: 'Afficher les succursales',
        es: 'Ver sucursales',
        pt: 'Visualizar filiais',
        tr: 'Şubeleri görüntüle',
        uk: 'Перегляд філіалів',
        zh: '查看分支机构',
        ar: 'عرض الفروع',
        pl: 'Przeglądaj oddziały',
        it: 'Visualizza filiali',
      }),
      branchCreate: t({
        ru: 'Создание филиалов',
        en: 'Create branches',
        kk: 'Филиал құру',
        de: 'Filialen erstellen',
        fr: 'Créer des succursales',
        es: 'Crear sucursales',
        pt: 'Criar filiais',
        tr: 'Şube oluştur',
        uk: 'Створення філіалів',
        zh: '创建分支机构',
        ar: 'إنشاء الفروع',
        pl: 'Twórz oddziały',
        it: 'Crea filiali',
      }),
      branchEdit: t({
        ru: 'Редактирование филиалов',
        en: 'Edit branches',
        kk: 'Филиалдарды өңдеу',
        de: 'Filialen bearbeiten',
        fr: 'Modifier les succursales',
        es: 'Editar sucursales',
        pt: 'Editar filiais',
        tr: 'Şubeleri düzenle',
        uk: 'Редагування філіалів',
        zh: '编辑分支机构',
        ar: 'تعديل الفروع',
        pl: 'Edytuj oddziały',
        it: 'Modifica filiali',
      }),
      branchDelete: t({
        ru: 'Удаление филиалов',
        en: 'Delete branches',
        kk: 'Филиалдарды жою',
        de: 'Filialen löschen',
        fr: 'Supprimer les succursales',
        es: 'Eliminar sucursales',
        pt: 'Excluir filiais',
        tr: 'Şubeleri sil',
        uk: 'Видалення філіалів',
        zh: '删除分支机构',
        ar: 'حذف الفروع',
        pl: 'Usuń oddziały',
        it: 'Elimina filiali',
      }),
      walletView: t({
        ru: 'Просмотр кошельков',
        en: 'View wallets',
        kk: 'Әмияндарды қарау',
        de: 'Wallets anzeigen',
        fr: 'Afficher les portefeuilles',
        es: 'Ver billeteras',
        pt: 'Visualizar carteiras',
        tr: 'Cüzdanları görüntüle',
        uk: 'Перегляд гаманців',
        zh: '查看钱包',
        ar: 'عرض المحافظ',
        pl: 'Przeglądaj portfele',
        it: 'Visualizza portafogli',
      }),
      walletCreate: t({
        ru: 'Создание кошельков',
        en: 'Create wallets',
        kk: 'Әмиян құру',
        de: 'Wallets erstellen',
        fr: 'Créer des portefeuilles',
        es: 'Crear billeteras',
        pt: 'Criar carteiras',
        tr: 'Cüzdan oluştur',
        uk: 'Створення гаманців',
        zh: '创建钱包',
        ar: 'إنشاء المحافظ',
        pl: 'Twórz portfele',
        it: 'Crea portafogli',
      }),
      walletEdit: t({
        ru: 'Редактирование кошельков',
        en: 'Edit wallets',
        kk: 'Әмияндарды өңдеу',
        de: 'Wallets bearbeiten',
        fr: 'Modifier les portefeuilles',
        es: 'Editar billeteras',
        pt: 'Editar carteiras',
        tr: 'Cüzdanları düzenle',
        uk: 'Редагування гаманців',
        zh: '编辑钱包',
        ar: 'تعديل المحافظ',
        pl: 'Edytuj portfele',
        it: 'Modifica portafogli',
      }),
      walletDelete: t({
        ru: 'Удаление кошельков',
        en: 'Delete wallets',
        kk: 'Әмияндарды жою',
        de: 'Wallets löschen',
        fr: 'Supprimer les portefeuilles',
        es: 'Eliminar billeteras',
        pt: 'Excluir carteiras',
        tr: 'Cüzdanları sil',
        uk: 'Видалення гаманців',
        zh: '删除钱包',
        ar: 'حذف المحافظ',
        pl: 'Usuń portfele',
        it: 'Elimina portafogli',
      }),
      reportView: t({
        ru: 'Просмотр отчётов',
        en: 'View reports',
        kk: 'Есептерді қарау',
        de: 'Berichte anzeigen',
        fr: 'Afficher les rapports',
        es: 'Ver informes',
        pt: 'Visualizar relatórios',
        tr: 'Raporları görüntüle',
        uk: 'Перегляд звітів',
        zh: '查看报告',
        ar: 'عرض التقارير',
        pl: 'Przeglądaj raporty',
        it: 'Visualizza report',
      }),
      reportExport: t({
        ru: 'Экспорт отчётов',
        en: 'Export reports',
        kk: 'Есептерді экспорттау',
        de: 'Berichte exportieren',
        fr: 'Exporter les rapports',
        es: 'Exportar informes',
        pt: 'Exportar relatórios',
        tr: 'Raporları dışa aktar',
        uk: 'Експорт звітів',
        zh: '导出报告',
        ar: 'تصدير التقارير',
        pl: 'Eksportuj raporty',
        it: 'Esporta report',
      }),
      googleSheetView: t({
        ru: 'Просмотр Google Sheets',
        en: 'View Google Sheets',
        kk: 'Google Sheets қарау',
        de: 'Google Sheets anzeigen',
        fr: 'Afficher Google Sheets',
        es: 'Ver Google Sheets',
        pt: 'Visualizar Google Sheets',
        tr: 'Google Sheets görüntüle',
        uk: 'Перегляд Google Sheets',
        zh: '查看 Google Sheets',
        ar: 'عرض Google Sheets',
        pl: 'Przeglądaj Google Sheets',
        it: 'Visualizza Google Sheets',
      }),
      googleSheetConnect: t({
        ru: 'Подключение Google Sheets',
        en: 'Connect Google Sheets',
        kk: 'Google Sheets қосу',
        de: 'Google Sheets verbinden',
        fr: 'Connecter Google Sheets',
        es: 'Conectar Google Sheets',
        pt: 'Conectar Google Sheets',
        tr: 'Google Sheets bağla',
        uk: 'Підключення Google Sheets',
        zh: '连接 Google Sheets',
        ar: 'توصيل Google Sheets',
        pl: 'Połącz Google Sheets',
        it: 'Connetti Google Sheets',
      }),
      googleSheetSync: t({
        ru: 'Синхронизация Google Sheets',
        en: 'Sync Google Sheets',
        kk: 'Google Sheets синхрондау',
        de: 'Google Sheets synchronisieren',
        fr: 'Synchroniser Google Sheets',
        es: 'Sincronizar Google Sheets',
        pt: 'Sincronizar Google Sheets',
        tr: 'Google Sheets senkronize et',
        uk: 'Синхронізація Google Sheets',
        zh: '同步 Google Sheets',
        ar: 'مزامنة Google Sheets',
        pl: 'Synchronizuj Google Sheets',
        it: 'Sincronizza Google Sheets',
      }),
    },
  },
} satisfies Dictionary;

export default content;
