import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementViewPage',
  content: {
    errors: {
      loadFailed: t({
        ru: 'Не удалось загрузить данные выписки',
        en: 'Failed to load statement data',
        kk: 'Үзінді деректерін жүктеу мүмкін болмады',
        de: 'Kontoauszugsdaten konnten nicht geladen werden',
        fr: 'Impossible de charger les données du relevé',
        es: 'Error al cargar los datos del extracto',
        pt: 'Falha ao carregar dados do extrato',
        tr: 'Ekstre verileri yüklenemedi',
        uk: 'Не вдалося завантажити дані виписки',
        zh: '无法加载对账单数据',
        ar: 'فشل تحميل بيانات الكشف',
        pl: 'Nie udało się załadować danych wyciągu',
        it: 'Impossibile caricare i dati dell\'estratto conto',
        sk: 'Nie udało się załadować danych wyciągu',
      }),
    },
    loading: t({
      ru: 'Загрузка файла...',
      en: 'Loading file...',
      kk: 'Файл жүктелуде...',
      de: 'Datei wird geladen...',
      fr: 'Chargement du fichier...',
      es: 'Cargando archivo...',
      pt: 'Carregando arquivo...',
      tr: 'Dosya yükleniyor...',
      uk: 'Завантаження файлу...',
      zh: '正在加载文件...',
      ar: 'جارٍ تحميل الملف...',
      pl: 'Ładowanie pliku...',
      it: 'Caricamento file...',
      sk: 'Ładowanie pliku...',
    }),
    fileLoaded: t({
      ru: 'Файл загружен',
      en: 'File loaded',
      kk: 'Файл жүктелді',
      de: 'Datei geladen',
      fr: 'Fichier chargé',
      es: 'Archivo cargado',
      pt: 'Arquivo carregado',
      tr: 'Dosya yüklendi',
      uk: 'Файл завантажено',
      zh: '文件已加载',
      ar: 'تم تحميل الملف',
      pl: 'Plik załadowany',
      it: 'File caricato',
      sk: 'Plik załadowany',
    }),
    fileLoadFailed: t({
      ru: 'Не удалось загрузить файл',
      en: 'Failed to load file',
      kk: 'Файлды жүктеу мүмкін болмады',
      de: 'Datei konnte nicht geladen werden',
      fr: 'Impossible de charger le fichier',
      es: 'Error al cargar el archivo',
      pt: 'Falha ao carregar o arquivo',
      tr: 'Dosya yüklenemedi',
      uk: 'Не вдалося завантажити файл',
      zh: '无法加载文件',
      ar: 'فشل تحميل الملف',
      pl: 'Nie udało się załadować pliku',
      it: 'Impossibile caricare il file',
      sk: 'Nie udało się załadować pliku',
    }),
    statementNotFound: t({
      ru: 'Выписка не найдена',
      en: 'Statement not found',
      kk: 'Үзінді табылмады',
      de: 'Kontoauszug nicht gefunden',
      fr: 'Relevé introuvable',
      es: 'Extracto no encontrado',
      pt: 'Extrato não encontrado',
      tr: 'Ekstre bulunamadı',
      uk: 'Виписку не знайдено',
      zh: '未找到对账单',
      ar: 'الكشف غير موجود',
      pl: 'Wyciąg nie znaleziony',
      it: 'Estratto conto non trovato',
      sk: 'Wyciąg nie znaleziony',
    }),
    back: t({
      ru: 'Назад',
      en: 'Back',
      kk: 'Артқа',
      de: 'Zurück',
      fr: 'Retour',
      es: 'Atrás',
      pt: 'Voltar',
      tr: 'Geri',
      uk: 'Назад',
      zh: '返回',
      ar: 'رجوع',
      pl: 'Wstecz',
      it: 'Indietro',
      sk: 'Wstecz',
    }),
    backToStatements: t({
      ru: 'Назад к списку выписок',
      en: 'Back to statements',
      kk: 'Үзінділер тізіміне оралу',
      de: 'Zurück zu den Kontoauszügen',
      fr: 'Retour aux relevés',
      es: 'Volver a extractos',
      pt: 'Voltar aos extratos',
      tr: 'Ekstreler listesine dön',
      uk: 'Назад до списку виписок',
      zh: '返回对账单列表',
      ar: 'العودة إلى الكشوفات',
      pl: 'Wróć do wyciągów',
      it: 'Torna agli estratti conto',
      sk: 'Wróć do wyciągów',
    }),
  },
} satisfies Dictionary;

export default content;
