import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'breadcrumbs',
  content: {
    labels: {
      '': t({
        ru: 'Главная',
        en: 'Home',
        kk: 'Басты бет',
        de: 'Startseite',
        fr: 'Accueil',
        es: 'Inicio',
        pt: 'Início',
        tr: 'Ana Sayfa',
        uk: 'Головна',
        zh: '首页',
        ar: 'الرئيسية',
        pl: 'Strona główna',
        it: 'Home',
      }),
      statements: t({
        ru: 'Выписки',
        en: 'Statements',
        kk: 'Үзінділер',
        de: 'Auszüge',
        fr: 'Relevés',
        es: 'Extractos',
        pt: 'Extratos',
        tr: 'Ekstreler',
        uk: 'Виписки',
        zh: '账单',
        ar: 'كشوف الحساب',
        pl: 'Wyciągi',
        it: 'Estratti conto',
      }),
      'statements/top-spenders': t({
        ru: 'Главные расходы',
        en: 'Top spenders',
        kk: 'Ең үлкен шығындар',
        de: 'Größte Ausgaben',
        fr: 'Principales dépenses',
        es: 'Principales gastos',
        pt: 'Maiores gastos',
        tr: 'En fazla harcayanlar',
        uk: 'Найбільші витрати',
        zh: '最大支出',
        ar: 'أكبر المنفقين',
        pl: 'Największe wydatki',
        it: 'Principali spese',
      }),
      receipts: t({
        ru: 'Чеки',
        en: 'Receipts',
        kk: 'Чектер',
        de: 'Belege',
        fr: 'Reçus',
        es: 'Recibos',
        pt: 'Recibos',
        tr: 'Makbuzlar',
        uk: 'Чеки',
        zh: '收据',
        ar: 'الإيصالات',
        pl: 'Paragony',
        it: 'Ricevute',
      }),
      upload: t({
        ru: 'Загрузка',
        en: 'Upload',
        kk: 'Жүктеу',
        de: 'Hochladen',
        fr: 'Téléverser',
        es: 'Subir',
        pt: 'Enviar',
        tr: 'Yükle',
        uk: 'Завантаження',
        zh: '上传',
        ar: 'رفع',
        pl: 'Prześlij',
        it: 'Carica',
      }),
      'data-entry': t({
        ru: 'Ввод данных',
        en: 'Data entry',
        kk: 'Деректерді енгізу',
        de: 'Dateneingabe',
        fr: 'Saisie de données',
        es: 'Entrada de datos',
        pt: 'Entrada de dados',
        tr: 'Veri girişi',
        uk: 'Введення даних',
        zh: '数据录入',
        ar: 'إدخال البيانات',
        pl: 'Wprowadzanie danych',
        it: 'Inserimento dati',
      }),
      storage: t({
        ru: 'Хранилище',
        en: 'Storage',
        kk: 'Қойма',
        de: 'Speicher',
        fr: 'Stockage',
        es: 'Almacenamiento',
        pt: 'Armazenamento',
        tr: 'Depolama',
        uk: 'Сховище',
        zh: '存储',
        ar: 'التخزين',
        pl: 'Magazyn',
        it: 'Archivio',
      }),
      reports: t({
        ru: 'Отчёты',
        en: 'Reports',
        kk: 'Есептер',
        de: 'Berichte',
        fr: 'Rapports',
        es: 'Informes',
        pt: 'Relatórios',
        tr: 'Raporlar',
        uk: 'Звіти',
        zh: '报告',
        ar: 'التقارير',
        pl: 'Raporty',
        it: 'Rapporti',
      }),
      categories: t({
        ru: 'Категории',
        en: 'Categories',
        kk: 'Санаттар',
        de: 'Kategorien',
        fr: 'Catégories',
        es: 'Categorías',
        pt: 'Categorias',
        tr: 'Kategoriler',
        uk: 'Категорії',
        zh: '分类',
        ar: 'الفئات',
        pl: 'Kategorie',
        it: 'Categorie',
      }),
      integrations: t({
        ru: 'Интеграции',
        en: 'Integrations',
        kk: 'Интеграциялар',
        de: 'Integrationen',
        fr: 'Intégrations',
        es: 'Integraciones',
        pt: 'Integrações',
        tr: 'Entegrasyonlar',
        uk: 'Інтеграції',
        zh: '集成',
        ar: 'التكاملات',
        pl: 'Integracje',
        it: 'Integrazioni',
      }),
      'supported-banks': t({
        ru: 'Поддерживаемые банки',
        en: 'Supported banks',
        kk: 'Қолдау көрсетілетін банктер',
        de: 'Unterstützte Banken',
        fr: 'Banques prises en charge',
        es: 'Bancos compatibles',
        pt: 'Bancos suportados',
        tr: 'Desteklenen bankalar',
        uk: 'Підтримувані банки',
        zh: '支持的银行',
        ar: 'البنوك المدعومة',
        pl: 'Obsługiwane banki',
        it: 'Banche supportate',
      }),
      'integrations/google-sheets': t({
        ru: 'Google Sheets',
        en: 'Google Sheets',
        kk: 'Google Sheets',
        de: 'Google Sheets',
        fr: 'Google Sheets',
        es: 'Google Sheets',
        pt: 'Google Sheets',
        tr: 'Google Sheets',
        uk: 'Google Sheets',
        zh: 'Google Sheets',
        ar: 'Google Sheets',
        pl: 'Google Sheets',
        it: 'Google Sheets',
      }),
      'custom-tables': t({
        ru: 'Таблицы',
        en: 'Tables',
        kk: 'Кестелер',
        de: 'Tabellen',
        fr: 'Tableaux',
        es: 'Tablas',
        pt: 'Tabelas',
        tr: 'Tablolar',
        uk: 'Таблиці',
        zh: '表格',
        ar: 'الجداول',
        pl: 'Tabele',
        it: 'Tabelle',
      }),
      'custom-tables/import': t({
        ru: 'Импорт',
        en: 'Import',
        kk: 'Импорт',
        de: 'Import',
        fr: 'Importer',
        es: 'Importar',
        pt: 'Importar',
        tr: 'İçe aktar',
        uk: 'Імпорт',
        zh: '导入',
        ar: 'استيراد',
        pl: 'Import',
        it: 'Importa',
      }),
      'custom-tables/import/google-sheets': t({
        ru: 'Google Sheets',
        en: 'Google Sheets',
        kk: 'Google Sheets',
        de: 'Google Sheets',
        fr: 'Google Sheets',
        es: 'Google Sheets',
        pt: 'Google Sheets',
        tr: 'Google Sheets',
        uk: 'Google Sheets',
        zh: 'Google Sheets',
        ar: 'Google Sheets',
        pl: 'Google Sheets',
        it: 'Google Sheets',
      }),
      settings: t({
        ru: 'Настройки',
        en: 'Settings',
        kk: 'Баптаулар',
        de: 'Einstellungen',
        fr: 'Paramètres',
        es: 'Configuración',
        pt: 'Configurações',
        tr: 'Ayarlar',
        uk: 'Налаштування',
        zh: '设置',
        ar: 'الإعدادات',
        pl: 'Ustawienia',
        it: 'Impostazioni',
      }),
      'settings/profile': t({
        ru: 'Профиль',
        en: 'Profile',
        kk: 'Профиль',
        de: 'Profil',
        fr: 'Profil',
        es: 'Perfil',
        pt: 'Perfil',
        tr: 'Profil',
        uk: 'Профіль',
        zh: '个人资料',
        ar: 'الملف الشخصي',
        pl: 'Profil',
        it: 'Profilo',
      }),
      'settings/workspace': t({
        ru: 'Рабочее пространство',
        en: 'Workspace',
        kk: 'Жұмыс кеңістігі',
        de: 'Arbeitsbereich',
        fr: 'Espace de travail',
        es: 'Espacio de trabajo',
        pt: 'Espaço de trabalho',
        tr: 'Çalışma alanı',
        uk: 'Робочий простір',
        zh: '工作区',
        ar: 'مساحة العمل',
        pl: 'Przestrzeń robocza',
        it: 'Area di lavoro',
      }),
      'settings/telegram': t({
        ru: 'Telegram',
        en: 'Telegram',
        kk: 'Telegram',
        de: 'Telegram',
        fr: 'Telegram',
        es: 'Telegram',
        pt: 'Telegram',
        tr: 'Telegram',
        uk: 'Telegram',
        zh: 'Telegram',
        ar: 'Telegram',
        pl: 'Telegram',
        it: 'Telegram',
      }),
      'google-sheets': t({
        ru: 'Google Sheets',
        en: 'Google Sheets',
        kk: 'Google Sheets',
        de: 'Google Sheets',
        fr: 'Google Sheets',
        es: 'Google Sheets',
        pt: 'Google Sheets',
        tr: 'Google Sheets',
        uk: 'Google Sheets',
        zh: 'Google Sheets',
        ar: 'Google Sheets',
        pl: 'Google Sheets',
        it: 'Google Sheets',
      }),
      'google-sheets/callback': t({
        ru: 'Callback',
        en: 'Callback',
        kk: 'Callback',
        de: 'Callback',
        fr: 'Callback',
        es: 'Callback',
        pt: 'Callback',
        tr: 'Callback',
        uk: 'Callback',
        zh: 'Callback',
        ar: 'Callback',
        pl: 'Callback',
        it: 'Callback',
      }),
      admin: t({
        ru: 'Админка',
        en: 'Admin',
        kk: 'Админка',
        de: 'Admin',
        fr: 'Admin',
        es: 'Admin',
        pt: 'Admin',
        tr: 'Yönetici',
        uk: 'Адмінка',
        zh: '管理员',
        ar: 'المشرف',
        pl: 'Admin',
        it: 'Admin',
      }),
    },
  },
} satisfies Dictionary;

export default content;
