import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'navigation',
  content: {
    nav: {
      dashboard: t({
        ru: 'Дашборд',
        en: 'Dashboard',
        kk: 'Дашборд',
        de: 'Dashboard',
        fr: 'Tableau de bord',
        es: 'Panel',
        pt: 'Painel',
        tr: 'Gösterge paneli',
        uk: 'Дашборд',
        zh: '仪表板',
        ar: 'لوحة التحكم',
        pl: 'Panel',
        it: 'Dashboard',
        sk: 'Panel',
      }),
      statements: t({
        ru: 'Выписки',
        en: 'Statements',
        kk: 'Үзінділер',
        de: 'Kontoauszüge',
        fr: 'Relevés',
        es: 'Extractos',
        pt: 'Extratos',
        tr: 'Hesap özetleri',
        uk: 'Виписки',
        zh: '对账单',
        ar: 'كشوف الحساب',
        pl: 'Wyciągi',
        it: 'Estratti conto',
        sk: 'Wyciągi',
      }),
      receipts: t({
        ru: 'Чеки',
        en: 'Receipts',
        kk: 'Чектер',
        de: 'Quittungen',
        fr: 'Reçus',
        es: 'Recibos',
        pt: 'Recibos',
        tr: 'Makbuzlar',
        uk: 'Чеки',
        zh: '收据',
        ar: 'الإيصالات',
        pl: 'Paragony',
        it: 'Ricevute',
        sk: 'Paragony',
      }),
      workspaces: t({
        ru: 'Рабочие пространства',
        en: 'Workspaces',
        kk: 'Жұмыс кеңістіктері',
        de: 'Arbeitsbereiche',
        fr: 'Espaces de travail',
        es: 'Espacios de trabajo',
        pt: 'Workspaces',
        tr: 'Çalışma alanları',
        uk: 'Робочі простори',
        zh: '工作区',
        ar: 'مساحات العمل',
        pl: 'Przestrzenie robocze',
        it: 'Aree di lavoro',
        sk: 'Przestrzenie robocze',
      }),
      storage: t({
        ru: 'Хранилище',
        en: 'Storage',
        kk: 'Қойма',
        de: 'Speicher',
        fr: 'Stockage',
        es: 'Almacenamiento',
        pt: 'Armazenamento',
        tr: 'Depolama',
        uk: 'Сховище',
        zh: '存储',
        ar: 'التخزين',
        pl: 'Magazyn',
        it: 'Archiviazione',
        sk: 'Magazyn',
      }),
      dataEntry: t({
        ru: 'Ввод данных',
        en: 'Data entry',
        kk: 'Деректерді енгізу',
        de: 'Dateneingabe',
        fr: 'Saisie de données',
        es: 'Entrada de datos',
        pt: 'Entrada de dados',
        tr: 'Veri girişi',
        uk: 'Введення даних',
        zh: '数据输入',
        ar: 'إدخال البيانات',
        pl: 'Wprowadzanie danych',
        it: 'Inserimento dati',
        sk: 'Wprowadzanie danych',
      }),
      tables: t({
        ru: 'Таблицы',
        en: 'Tables',
        kk: 'Кестелер',
        de: 'Tabellen',
        fr: 'Tableaux',
        es: 'Tablas',
        pt: 'Tabelas',
        tr: 'Tablolar',
        uk: 'Таблиці',
        zh: '表格',
        ar: 'الجداول',
        pl: 'Tabele',
        it: 'Tabelle',
        sk: 'Tabele',
      }),
      reports: t({
        ru: 'Отчёты',
        en: 'Reports',
        kk: 'Есептер',
        de: 'Berichte',
        fr: 'Rapports',
        es: 'Informes',
        pt: 'Relatórios',
        tr: 'Raporlar',
        uk: 'Звіти',
        zh: '报告',
        ar: 'التقارير',
        pl: 'Raporty',
        it: 'Report',
        sk: 'Raporty',
      }),
      activityLog: t({
        ru: 'Журнал активности',
        en: 'Activity log',
        kk: 'Белсенділік журналы',
        de: 'Aktivitätsprotokoll',
        fr: 'Journal d\'activité',
        es: 'Registro de actividad',
        pt: 'Registro de atividades',
        tr: 'Aktivite günlüğü',
        uk: 'Журнал активності',
        zh: '活动日志',
        ar: 'سجل النشاط',
        pl: 'Dziennik aktywności',
        it: 'Registro attività',
        sk: 'Dziennik aktywności',
      }),
      categories: t({
        ru: 'Категории',
        en: 'Categories',
        kk: 'Санаттар',
        de: 'Kategorien',
        fr: 'Catégories',
        es: 'Categorías',
        pt: 'Categorias',
        tr: 'Kategoriler',
        uk: 'Категорії',
        zh: '分类',
        ar: 'الفئات',
        pl: 'Kategorie',
        it: 'Categorie',
        sk: 'Kategorie',
      }),
      integrations: t({
        ru: 'Интеграции',
        en: 'Integrations',
        kk: 'Интеграциялар',
        de: 'Integrationen',
        fr: 'Intégrations',
        es: 'Integraciones',
        pt: 'Integrações',
        tr: 'Entegrasyonlar',
        uk: 'Інтеграції',
        zh: '集成',
        ar: 'التكاملات',
        pl: 'Integracje',
        it: 'Integrazioni',
        sk: 'Integracje',
      }),
      plugins: t({
        ru: 'Плагины',
        en: 'Plugins',
        kk: 'Плагиндер',
        de: 'Plugins',
        fr: 'Plugins',
        es: 'Complementos',
        pt: 'Plugins',
        tr: 'Eklentiler',
        uk: 'Плагіни',
        zh: '插件',
        ar: 'الإضافات',
        pl: 'Wtyczki',
        it: 'Plugin',
        sk: 'Wtyczki',
      }),
    },
    userMenu: {
      profile: t({
        ru: 'Профиль',
        en: 'Profile',
        kk: 'Профиль',
        de: 'Profil',
        fr: 'Profil',
        es: 'Perfil',
        pt: 'Perfil',
        tr: 'Profil',
        uk: 'Профіль',
        zh: '个人资料',
        ar: 'الملف الشخصي',
        pl: 'Profil',
        it: 'Profilo',
        sk: 'Profil',
      }),
      settings: t({
        ru: 'Настройки',
        en: 'Settings',
        kk: 'Баптаулар',
        de: 'Einstellungen',
        fr: 'Paramètres',
        es: 'Configuración',
        pt: 'Configurações',
        tr: 'Ayarlar',
        uk: 'Налаштування',
        zh: '设置',
        ar: 'الإعدادات',
        pl: 'Ustawienia',
        it: 'Impostazioni',
        sk: 'Ustawienia',
      }),
      workspace: t({
        ru: 'Рабочее пространство',
        en: 'Workspace',
        kk: 'Жұмыс кеңістігі',
        de: 'Arbeitsbereich',
        fr: 'Espace de travail',
        es: 'Espacio de trabajo',
        pt: 'Workspace',
        tr: 'Çalışma alanı',
        uk: 'Робочий простір',
        zh: '工作区',
        ar: 'مساحة العمل',
        pl: 'Przestrzeń robocza',
        it: 'Area di lavoro',
        sk: 'Przestrzeń robocza',
      }),
      integrations: t({
        ru: 'Интеграции',
        en: 'Integrations',
        kk: 'Интеграциялар',
        de: 'Integrationen',
        fr: 'Intégrations',
        es: 'Integraciones',
        pt: 'Integrações',
        tr: 'Entegrasyonlar',
        uk: 'Інтеграції',
        zh: '集成',
        ar: 'التكاملات',
        pl: 'Integracje',
        it: 'Integrazioni',
        sk: 'Integracje',
      }),
      supportedBanks: t({
        ru: 'Поддерживаемые банки',
        en: 'Supported banks',
        kk: 'Қолдау көрсетілетін банктер',
        de: 'Unterstützte Banken',
        fr: 'Banques prises en charge',
        es: 'Bancos compatibles',
        pt: 'Bancos suportados',
        tr: 'Desteklenen bankalar',
        uk: 'Підтримувані банки',
        zh: '支持的银行',
        ar: 'البنوك المدعومة',
        pl: 'Obsługiwane banki',
        it: 'Banche supportate',
        sk: 'Obsługiwane banki',
      }),
      trash: t({
        ru: 'Корзина',
        en: 'Trash',
        kk: 'Себет',
        de: 'Papierkorb',
        fr: 'Corbeille',
        es: 'Papelera',
        pt: 'Lixeira',
        tr: 'Çöp kutusu',
        uk: 'Кошик',
        zh: '回收站',
        ar: 'سلة المحذوفات',
        pl: 'Kosz',
        it: 'Cestino',
        sk: 'Kosz',
      }),
      categories: t({
        ru: 'Категории',
        en: 'Categories',
        kk: 'Санаттар',
        de: 'Kategorien',
        fr: 'Catégories',
        es: 'Categorías',
        pt: 'Categorias',
        tr: 'Kategoriler',
        uk: 'Категорії',
        zh: '分类',
        ar: 'الفئات',
        pl: 'Kategorie',
        it: 'Categorie',
        sk: 'Kategorie',
      }),
      admin: t({
        ru: 'Админка',
        en: 'Activity',
        kk: 'Админка',
        de: 'Admin',
        fr: 'Administration',
        es: 'Administración',
        pt: 'Administração',
        tr: 'Yönetim',
        uk: 'Адмінка',
        zh: '管理',
        ar: 'الإدارة',
        pl: 'Administracja',
        it: 'Amministrazione',
        sk: 'Administracja',
      }),
      knowledgeBase: t({
        ru: 'База знаний',
        en: 'Knowledge base',
        kk: 'Білім қоры',
        de: 'Wissensdatenbank',
        fr: 'Base de connaissances',
        es: 'Base de conocimiento',
        pt: 'Base de conhecimento',
        tr: 'Bilgi tabanı',
        uk: 'База знань',
        zh: '知识库',
        ar: 'قاعدة المعرفة',
        pl: 'Baza wiedzy',
        it: 'Base di conoscenza',
        sk: 'Baza wiedzy',
      }),
      logout: t({
        ru: 'Выйти',
        en: 'Log out',
        kk: 'Шығу',
        de: 'Abmelden',
        fr: 'Se déconnecter',
        es: 'Cerrar sesión',
        pt: 'Sair',
        tr: 'Çıkış yap',
        uk: 'Вийти',
        zh: '退出登录',
        ar: 'تسجيل الخروج',
        pl: 'Wyloguj się',
        it: 'Esci',
        sk: 'Wyloguj się',
      }),
      logoutSuccess: t({
        ru: 'Вы успешно вышли из системы',
        en: 'You have successfully logged out',
        kk: 'Сіз жүйеден сәтті шықтыңыз',
        de: 'Sie haben sich erfolgreich abgemeldet',
        fr: 'Vous vous êtes déconnecté avec succès',
        es: 'Has cerrado sesión exitosamente',
        pt: 'Você saiu com sucesso',
        tr: 'Başarıyla çıkış yaptınız',
        uk: 'Ви успішно вийшли з системи',
        zh: '您已成功退出登录',
        ar: 'لقد سجّلت الخروج بنجاح',
        pl: 'Pomyślnie wylogowano',
        it: 'Hai effettuato il logout con successo',
        sk: 'Pomyślnie wylogowano',
      }),
      language: t({
        ru: 'Язык',
        en: 'Language',
        kk: 'Тіл',
        de: 'Sprache',
        fr: 'Langue',
        es: 'Idioma',
        pt: 'Idioma',
        tr: 'Dil',
        uk: 'Мова',
        zh: '语言',
        ar: 'اللغة',
        pl: 'Język',
        it: 'Lingua',
        sk: 'Język',
      }),
      moreActions: t({
        ru: 'Меню',
        en: 'Menu',
        kk: 'Мәзір',
        de: 'Menü',
        fr: 'Menu',
        es: 'Menú',
        pt: 'Menu',
        tr: 'Menü',
        uk: 'Меню',
        zh: '菜单',
        ar: 'القائمة',
        pl: 'Menu',
        it: 'Menu',
        sk: 'Menu',
      }),
    },
    languageModal: {
      sectionLabel: t({
        ru: 'Интерфейс',
        en: 'Interface',
        kk: 'Интерфейс',
        de: 'Oberfläche',
        fr: 'Interface',
        es: 'Interfaz',
        pt: 'Interface',
        tr: 'Arayüz',
        uk: 'Інтерфейс',
        zh: '界面',
        ar: 'الواجهة',
        pl: 'Interfejs',
        it: 'Interfaccia',
        sk: 'Interfejs',
      }),
      title: t({
        ru: 'Выбор языка',
        en: 'Choose language',
        kk: 'Тілді таңдау',
        de: 'Sprache wählen',
        fr: 'Choisir la langue',
        es: 'Elegir idioma',
        pt: 'Escolher idioma',
        tr: 'Dil seçin',
        uk: 'Вибір мови',
        zh: '选择语言',
        ar: 'اختر اللغة',
        pl: 'Wybierz język',
        it: 'Scegli lingua',
        sk: 'Wybierz język',
      }),
      back: t({
        ru: 'Назад',
        en: 'Back',
        kk: 'Артқа',
        de: 'Zurück',
        fr: 'Retour',
        es: 'Atrás',
        pt: 'Voltar',
        tr: 'Geri',
        uk: 'Назад',
        zh: '返回',
        ar: 'رجوع',
        pl: 'Wstecz',
        it: 'Indietro',
        sk: 'Wstecz',
      }),
      currentLanguageLabel: t({
        ru: 'Текущий язык',
        en: 'Current language',
        kk: 'Ағымдағы тіл',
        de: 'Aktuelle Sprache',
        fr: 'Langue actuelle',
        es: 'Idioma actual',
        pt: 'Idioma atual',
        tr: 'Mevcut dil',
        uk: 'Поточна мова',
        zh: '当前语言',
        ar: 'اللغة الحالية',
        pl: 'Bieżący język',
        it: 'Lingua corrente',
        sk: 'Bieżący język',
      }),
      defaultLanguageNote: t({
        ru: 'По умолчанию',
        en: 'Default',
        kk: 'Әдепкі',
        de: 'Standard',
        fr: 'Par défaut',
        es: 'Predeterminado',
        pt: 'Padrão',
        tr: 'Varsayılan',
        uk: 'За замовчуванням',
        zh: '默认',
        ar: 'الافتراضي',
        pl: 'Domyślny',
        it: 'Predefinito',
        sk: 'Domyślny',
      }),
      changeLanguage: t({
        ru: 'Сменить язык',
        en: 'Change language',
        kk: 'Тілді өзгерту',
        de: 'Sprache ändern',
        fr: 'Changer de langue',
        es: 'Cambiar idioma',
        pt: 'Mudar idioma',
        tr: 'Dili değiştir',
        uk: 'Змінити мову',
        zh: '更改语言',
        ar: 'تغيير اللغة',
        pl: 'Zmień język',
        it: 'Cambia lingua',
        sk: 'Zmień język',
      }),
      availableLanguagesLabel: t({
        ru: 'Доступные языки',
        en: 'Available languages',
        kk: 'Қолжетімді тілдер',
        de: 'Verfügbare Sprachen',
        fr: 'Langues disponibles',
        es: 'Idiomas disponibles',
        pt: 'Idiomas disponíveis',
        tr: 'Mevcut diller',
        uk: 'Доступні мови',
        zh: '可用语言',
        ar: 'اللغات المتاحة',
        pl: 'Dostępne języki',
        it: 'Lingue disponibili',
        sk: 'Dostępne języki',
      }),
      chooseAction: t({
        ru: 'Выбрать',
        en: 'Select',
        kk: 'Таңдау',
        de: 'Auswählen',
        fr: 'Sélectionner',
        es: 'Seleccionar',
        pt: 'Selecionar',
        tr: 'Seç',
        uk: 'Вибрати',
        zh: '选择',
        ar: 'اختر',
        pl: 'Wybierz',
        it: 'Seleziona',
        sk: 'Wybierz',
      }),
      scrollHint: t({
        ru: 'Прокрутите список и выберите язык.',
        en: 'Scroll the list and choose a language.',
        kk: 'Тізімді жылжытып, тілді таңдаңыз.',
        de: 'Scrollen Sie die Liste und wählen Sie eine Sprache.',
        fr: 'Faites défiler la liste et choisissez une langue.',
        es: 'Desplázate por la lista y elige un idioma.',
        pt: 'Role a lista e escolha um idioma.',
        tr: 'Listeyi kaydırın ve bir dil seçin.',
        uk: 'Прокрутіть список і виберіть мову.',
        zh: '滚动列表并选择一种语言。',
        ar: 'قم بالتمرير في القائمة واختر لغة.',
        pl: 'Przewiń listę i wybierz język.',
        it: 'Scorri l\'elenco e scegli una lingua.',
        sk: 'Przewiń listę i wybierz język.',
      }),
      footerHint: t({
        ru: 'Переводы будут добавлены на следующем этапе.',
        en: 'Translations will be added in the next step.',
        kk: 'Аудармалар келесі кезеңде қосылады.',
        de: 'Übersetzungen werden im nächsten Schritt hinzugefügt.',
        fr: 'Les traductions seront ajoutées à l\'étape suivante.',
        es: 'Las traducciones se agregarán en el siguiente paso.',
        pt: 'As traduções serão adicionadas no próximo passo.',
        tr: 'Çeviriler bir sonraki adımda eklenecek.',
        uk: 'Переклади будуть додані на наступному етапі.',
        zh: '翻译将在下一步中添加。',
        ar: 'ستُضاف الترجمات في الخطوة التالية.',
        pl: 'Tłumaczenia zostaną dodane w następnym kroku.',
        it: 'Le traduzioni verranno aggiunte nel passaggio successivo.',
        sk: 'Tłumaczenia zostaną dodane w następnym kroku.',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Anuluj',
      }),
      save: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Speichern',
        fr: 'Enregistrer',
        es: 'Guardar',
        pt: 'Salvar',
        tr: 'Kaydet',
        uk: 'Зберегти',
        zh: '保存',
        ar: 'حفظ',
        pl: 'Zapisz',
        it: 'Salva',
        sk: 'Zapisz',
      }),
      savedToastPrefix: t({
        ru: 'Язык выбран',
        en: 'Language selected',
        kk: 'Тіл таңдалды',
        de: 'Sprache ausgewählt',
        fr: 'Langue sélectionnée',
        es: 'Idioma seleccionado',
        pt: 'Idioma selecionado',
        tr: 'Dil seçildi',
        uk: 'Мову вибрано',
        zh: '已选择语言',
        ar: 'تم اختيار اللغة',
        pl: 'Język wybrany',
        it: 'Lingua selezionata',
        sk: 'Język wybrany',
      }),
    },
    tour: {
      start: t({
        ru: 'Показать тур',
        en: 'Start tour',
        kk: 'Турды бастау',
        de: 'Tour starten',
        fr: 'Démarrer la visite',
        es: 'Iniciar tour',
        pt: 'Iniciar tour',
        tr: 'Turu başlat',
        uk: 'Показати тур',
        zh: '开始导览',
        ar: 'بدء الجولة',
        pl: 'Rozpocznij tour',
        it: 'Avvia tour',
        sk: 'Rozpocznij tour',
      }),
      menuLabel: t({
        ru: 'Туры',
        en: 'Tours',
        kk: 'Турлар',
        de: 'Touren',
        fr: 'Visites',
        es: 'Tours',
        pt: 'Tours',
        tr: 'Turlar',
        uk: 'Тури',
        zh: '导览',
        ar: 'الجولات',
        pl: 'Toury',
        it: 'Tour',
        sk: 'Toury',
      }),
      progressText: t({
        ru: '{{current}} из {{total}}',
        en: '{{current}} of {{total}}',
        kk: '{{current}} / {{total}}',
        de: '{{current}} von {{total}}',
        fr: '{{current}} sur {{total}}',
        es: '{{current}} de {{total}}',
        pt: '{{current}} de {{total}}',
        tr: '{{total}} üzerinden {{current}}',
        uk: '{{current}} з {{total}}',
        zh: '{{current}} / {{total}}',
        ar: '{{current}} من {{total}}',
        pl: '{{current}} z {{total}}',
        it: '{{current}} di {{total}}',
        sk: '{{current}} z {{total}}',
      }),
      buttons: {
        next: t({ ru: 'Далее', en: 'Next', kk: 'Келесі', de: 'Weiter', fr: 'Suivant', es: 'Siguiente', pt: 'Próximo', tr: 'İleri', uk: 'Далі', zh: '下一步', ar: 'التالي', pl: 'Dalej', it: 'Avanti', sk: 'Dalej'}),
        prev: t({ ru: 'Назад', en: 'Back', kk: 'Артқа', de: 'Zurück', fr: 'Retour', es: 'Atrás', pt: 'Voltar', tr: 'Geri', uk: 'Назад', zh: '上一步', ar: 'رجوع', pl: 'Wstecz', it: 'Indietro', sk: 'Wstecz'}),
        done: t({ ru: 'Готово', en: 'Done', kk: 'Дайын', de: 'Fertig', fr: 'Terminé', es: 'Listo', pt: 'Concluído', tr: 'Tamamlandı', uk: 'Готово', zh: '完成', ar: 'تم', pl: 'Gotowe', it: 'Fatto', sk: 'Gotowe'}),
        close: t({ ru: 'Закрыть', en: 'Close', kk: 'Жабу', de: 'Schließen', fr: 'Fermer', es: 'Cerrar', pt: 'Fechar', tr: 'Kapat', uk: 'Закрити', zh: '关闭', ar: 'إغلاق', pl: 'Zamknij', it: 'Chiudi', sk: 'Zamknij'}),
      },
      fallback: {
        noTargets: t({
          ru: 'Не удалось запустить тур: элементы недоступны на этой странице.',
          en: 'Could not start the tour: targets are not available on this page.',
          kk: 'Турды бастау мүмкін болмады: элементтер бұл бетте қолжетімсіз.',
          de: 'Tour konnte nicht gestartet werden: Ziele sind auf dieser Seite nicht verfügbar.',
          fr: 'Impossible de démarrer la visite : les cibles ne sont pas disponibles sur cette page.',
          es: 'No se pudo iniciar el tour: los elementos no están disponibles en esta página.',
          pt: 'Não foi possível iniciar o tour: os alvos não estão disponíveis nesta página.',
          tr: 'Tur başlatılamadı: hedefler bu sayfada mevcut değil.',
          uk: 'Не вдалося запустити тур: елементи недоступні на цій сторінці.',
          zh: '无法启动导览：此页面上的目标不可用。',
          ar: 'تعذر بدء الجولة: العناصر المستهدفة غير متاحة في هذه الصفحة.',
          pl: 'Nie można uruchomić touru: elementy docelowe nie są dostępne na tej stronie.',
          it: 'Impossibile avviare il tour: i target non sono disponibili in questa pagina.',
          sk: 'Nie można uruchomić touru: elementy docelowe nie są dostępne na tej stronie.',
        }),
      },
      steps: {
        brand: {
          title: t({
            ru: 'Ваше рабочее пространство',
            en: 'Your workspace',
            kk: 'Сіздің жұмыс кеңістігі',
            de: 'Ihr Arbeitsbereich',
            fr: 'Votre espace de travail',
            es: 'Tu espacio de trabajo',
            pt: 'Seu workspace',
            tr: 'Çalışma alanınız',
            uk: 'Ваш робочий простір',
            zh: '您的工作区',
            ar: 'مساحة عملك',
            pl: 'Twoja przestrzeń robocza',
            it: 'La tua area di lavoro',
            sk: 'Twoja przestrzeń robocza',
          }),
          description: t({
            ru: 'Логотип Lumio ведет на главную страницу.',
            en: 'Lumio logo brings you back to the home dashboard.',
            kk: 'Lumio логотипі басты бетке қайтарады.',
            de: 'Das Lumio-Logo führt Sie zur Startseite.',
            fr: 'Le logo Lumio vous ramène au tableau de bord principal.',
            es: 'El logo de Lumio te lleva de vuelta al panel principal.',
            pt: 'O logo do Lumio leva você de volta ao painel principal.',
            tr: 'Lumio logosu sizi ana panoya geri götürür.',
            uk: 'Логотип Lumio веде на головну сторінку.',
            zh: 'Lumio 徽标将您带回主仪表板。',
            ar: 'شعار Lumio يعيدك إلى لوحة التحكم الرئيسية.',
            pl: 'Logo Lumio prowadzi do strony głównej.',
            it: 'Il logo Lumio ti riporta alla dashboard principale.',
            sk: 'Logo Lumio prowadzi do strony głównej.',
          }),
        },
        navigation: {
          title: t({
            ru: 'Основные разделы',
            en: 'Main sections',
            kk: 'Негізгі бөлімдер',
            de: 'Hauptbereiche',
            fr: 'Sections principales',
            es: 'Secciones principales',
            pt: 'Seções principais',
            tr: 'Ana bölümler',
            uk: 'Основні розділи',
            zh: '主要章节',
            ar: 'الأقسام الرئيسية',
            pl: 'Główne sekcje',
            it: 'Sezioni principali',
            sk: 'Główne sekcje',
          }),
          description: t({
            ru: 'Здесь доступ к выпискам, хранилищу, вводу данных, таблицам и отчетам.',
            en: 'Access statements, storage, data entry, custom tables, and reports here.',
            kk: 'Мұнда үзінділер, қойма, деректер енгізу, кестелер және есептерге қолжетімділік.',
            de: 'Hier Zugang zu Kontoauszügen, Speicher, Dateneingabe, Tabellen und Berichten.',
            fr: 'Accédez ici aux relevés, au stockage, à la saisie de données, aux tableaux et aux rapports.',
            es: 'Aquí accedes a extractos, almacenamiento, entrada de datos, tablas e informes.',
            pt: 'Acesse extratos, armazenamento, entrada de dados, tabelas e relatórios aqui.',
            tr: 'Buradan hesap özetlerine, depolamaya, veri girişine, tablolara ve raporlara erişin.',
            uk: 'Тут доступ до виписок, сховища, введення даних, таблиць і звітів.',
            zh: '在此访问对账单、存储、数据输入、自定义表格和报告。',
            ar: 'يمكنك الوصول هنا إلى كشوف الحساب والتخزين وإدخال البيانات والجداول والتقارير.',
            pl: 'Tutaj dostęp do wyciągów, magazynu, wprowadzania danych, tabel i raportów.',
            it: 'Accedi qui a estratti conto, archiviazione, inserimento dati, tabelle e report.',
            sk: 'Tutaj dostęp do wyciągów, magazynu, wprowadzania danych, tabel i raportów.',
          }),
        },
        theme: {
          title: t({
            ru: 'Светлая, темная и авто тема',
            en: 'Light, dark, and auto themes',
            kk: 'Жарық, қараңғы және авто тақырыптар',
            de: 'Helles, dunkles und automatisches Design',
            fr: 'Thèmes clair, sombre et automatique',
            es: 'Temas claro, oscuro y automático',
            pt: 'Temas claro, escuro e automático',
            tr: 'Açık, koyu ve otomatik temalar',
            uk: 'Світла, темна та авто тема',
            zh: '浅色、深色和自动主题',
            ar: 'السمات الفاتحة والداكنة والتلقائية',
            pl: 'Jasny, ciemny i automatyczny motyw',
            it: 'Temi chiaro, scuro e automatico',
            sk: 'Jasny, ciemny i automatyczny motyw',
          }),
          description: t({
            ru: 'Переключайте тему интерфейса вручную или по расписанию 07:00/19:00.',
            en: 'Switch the interface theme manually or on the 07:00/19:00 schedule.',
            kk: 'Интерфейс тақырыбын қолмен немесе 07:00/19:00 кестесімен ауыстырыңыз.',
            de: 'Wechseln Sie das Interface-Design manuell oder nach dem 07:00/19:00-Plan.',
            fr: 'Changez le thème de l\'interface manuellement ou selon le planning 07:00/19:00.',
            es: 'Cambia el tema de la interfaz manualmente o según el horario 07:00/19:00.',
            pt: 'Mude o tema da interface manualmente ou no horário 07:00/19:00.',
            tr: 'Arayüz temasını manuel olarak veya 07:00/19:00 planına göre değiştirin.',
            uk: 'Перемикайте тему інтерфейсу вручну або за розкладом 07:00/19:00.',
            zh: '手动切换界面主题，或按 07:00/19:00 时间表切换。',
            ar: 'قم بتبديل سمة الواجهة يدويًا أو وفق جدول 07:00/19:00.',
            pl: 'Przełączaj motyw interfejsu ręcznie lub według harmonogramu 07:00/19:00.',
            it: 'Cambia il tema dell\'interfaccia manualmente o secondo il programma 07:00/19:00.',
            sk: 'Przełączaj motyw interfejsu ręcznie lub według harmonogramu 07:00/19:00.',
          }),
        },
        userMenu: {
          title: t({
            ru: 'Профиль и настройки',
            en: 'Profile and settings',
            kk: 'Профиль және баптаулар',
            de: 'Profil und Einstellungen',
            fr: 'Profil et paramètres',
            es: 'Perfil y configuración',
            pt: 'Perfil e configurações',
            tr: 'Profil ve ayarlar',
            uk: 'Профіль та налаштування',
            zh: '个人资料和设置',
            ar: 'الملف الشخصي والإعدادات',
            pl: 'Profil i ustawienia',
            it: 'Profilo e impostazioni',
            sk: 'Profil i ustawienia',
          }),
          description: t({
            ru: 'Откройте меню, чтобы перейти в настройки, управление рабочим пространством, интеграции или выйти.',
            en: 'Open the menu to manage settings, workspace, integrations, or log out.',
            kk: 'Мәзірді ашып, баптауларды, жұмыс кеңістігін, интеграцияларды басқару немесе шығу.',
            de: 'Öffnen Sie das Menü, um Einstellungen, Arbeitsbereich, Integrationen zu verwalten oder sich abzumelden.',
            fr: 'Ouvrez le menu pour gérer les paramètres, l\'espace de travail, les intégrations ou vous déconnecter.',
            es: 'Abre el menú para gestionar configuración, espacio de trabajo, integraciones o cerrar sesión.',
            pt: 'Abra o menu para gerenciar configurações, workspace, integrações ou sair.',
            tr: 'Ayarları, çalışma alanını, entegrasyonları yönetmek veya çıkış yapmak için menüyü açın.',
            uk: 'Відкрийте меню, щоб перейти до налаштувань, управління робочим простором, інтеграцій або вийти.',
            zh: '打开菜单以管理设置、工作区、集成或退出登录。',
            ar: 'افتح القائمة لإدارة الإعدادات ومساحة العمل والتكاملات أو تسجيل الخروج.',
            pl: 'Otwórz menu, aby zarządzać ustawieniami, przestrzenią roboczą, integracjami lub wylogować się.',
            it: 'Apri il menu per gestire impostazioni, area di lavoro, integrazioni o effettuare il logout.',
            sk: 'Otwórz menu, aby zarządzać ustawieniami, przestrzenią roboczą, integracjami lub wylogować się.',
          }),
        },
        mobileMenu: {
          title: t({
            ru: 'Меню на мобильных',
            en: 'Mobile menu',
            kk: 'Мобильді мәзір',
            de: 'Mobiles Menü',
            fr: 'Menu mobile',
            es: 'Menú móvil',
            pt: 'Menu mobile',
            tr: 'Mobil menü',
            uk: 'Меню на мобільних',
            zh: '移动菜单',
            ar: 'قائمة الجوال',
            pl: 'Menu mobilne',
            it: 'Menu mobile',
            sk: 'Menu mobilne',
          }),
          description: t({
            ru: 'Используйте бургер, чтобы открыть навигацию на небольших экранах.',
            en: 'Use the burger to open navigation on small screens.',
            kk: 'Кіші экрандарда навигацияны ашу үшін бургерді пайдаланыңыз.',
            de: 'Verwenden Sie das Burger-Menü, um die Navigation auf kleinen Bildschirmen zu öffnen.',
            fr: 'Utilisez le hamburger pour ouvrir la navigation sur les petits écrans.',
            es: 'Usa el ícono de hamburguesa para abrir la navegación en pantallas pequeñas.',
            pt: 'Use o menu hambúrguer para abrir a navegação em telas pequenas.',
            tr: 'Küçük ekranlarda navigasyonu açmak için burger menüyü kullanın.',
            uk: 'Використовуйте бургер, щоб відкрити навігацію на маленьких екранах.',
            zh: '使用汉堡菜单在小屏幕上打开导航。',
            ar: 'استخدم أيقونة القائمة لفتح التنقل على الشاشات الصغيرة.',
            pl: 'Użyj przycisku hamburger, aby otworzyć nawigację na małych ekranach.',
            it: 'Usa il menu hamburger per aprire la navigazione su schermi piccoli.',
            sk: 'Użyj przycisku hamburger, aby otworzyć nawigację na małych ekranach.',
          }),
        },
      },
    },
    supportProject: t({
      ru: 'Поддержать проект',
      en: 'Support the project',
      kk: 'Жобаны қолдау',
      de: 'Das Projekt unterstützen',
      fr: 'Soutenir le projet',
      es: 'Apoyar el proyecto',
      pt: 'Apoiar o projeto',
      tr: 'Projeyi destekle',
      uk: 'Підтримати проект',
      zh: '支持项目',
      ar: 'دعم المشروع',
      pl: 'Wspomóż projekt',
      it: 'Supporta il progetto',
      sk: 'Wspomóż projekt',
    }),
    languages: {
      ru: t({ ru: 'Русский', en: 'Русский', kk: 'Русский', de: 'Русский', fr: 'Русский', es: 'Русский', pt: 'Русский', tr: 'Русский', uk: 'Русский', zh: 'Русский', ar: 'Русский', pl: 'Русский', it: 'Русский', sk: 'Русский' }),
      en: t({ ru: 'English', en: 'English', kk: 'English', de: 'English', fr: 'English', es: 'English', pt: 'English', tr: 'English', uk: 'English', zh: 'English', ar: 'English', pl: 'English', it: 'English', sk: 'English' }),
      kk: t({ ru: 'Қазақша', en: 'Қазақша', kk: 'Қазақша', de: 'Қазақша', fr: 'Қазақша', es: 'Қазақша', pt: 'Қазақша', tr: 'Қазақша', uk: 'Қазақша', zh: 'Қазақша', ar: 'Қазақша', pl: 'Қазақша', it: 'Қазақша', sk: 'Қазақша' }),
      de: t({ ru: 'Deutsch', en: 'Deutsch', kk: 'Deutsch', de: 'Deutsch', fr: 'Deutsch', es: 'Deutsch', pt: 'Deutsch', tr: 'Deutsch', uk: 'Deutsch', zh: 'Deutsch', ar: 'Deutsch', pl: 'Deutsch', it: 'Deutsch', sk: 'Deutsch' }),
      fr: t({ ru: 'Français', en: 'Français', kk: 'Français', de: 'Français', fr: 'Français', es: 'Français', pt: 'Français', tr: 'Français', uk: 'Français', zh: 'Français', ar: 'Français', pl: 'Français', it: 'Français', sk: 'Français' }),
      es: t({ ru: 'Español', en: 'Español', kk: 'Español', de: 'Español', fr: 'Español', es: 'Español', pt: 'Español', tr: 'Español', uk: 'Español', zh: 'Español', ar: 'Español', pl: 'Español', it: 'Español', sk: 'Español' }),
      pt: t({ ru: 'Português', en: 'Português', kk: 'Português', de: 'Português', fr: 'Português', es: 'Português', pt: 'Português', tr: 'Português', uk: 'Português', zh: 'Português', ar: 'Português', pl: 'Português', it: 'Português', sk: 'Português' }),
      tr: t({ ru: 'Türkçe', en: 'Türkçe', kk: 'Türkçe', de: 'Türkçe', fr: 'Türkçe', es: 'Türkçe', pt: 'Türkçe', tr: 'Türkçe', uk: 'Türkçe', zh: 'Türkçe', ar: 'Türkçe', pl: 'Türkçe', it: 'Türkçe', sk: 'Türkçe' }),
      uk: t({ ru: 'Українська', en: 'Українська', kk: 'Українська', de: 'Українська', fr: 'Українська', es: 'Українська', pt: 'Українська', tr: 'Українська', uk: 'Українська', zh: 'Українська', ar: 'Українська', pl: 'Українська', it: 'Українська', sk: 'Українська' }),
      zh: t({ ru: '中文', en: '中文', kk: '中文', de: '中文', fr: '中文', es: '中文', pt: '中文', tr: '中文', uk: '中文', zh: '中文', ar: '中文', pl: '中文', it: '中文', sk: '中文' }),
      ar: t({ ru: 'العربية', en: 'العربية', kk: 'العربية', de: 'العربية', fr: 'العربية', es: 'العربية', pt: 'العربية', tr: 'العربية', uk: 'العربية', zh: 'العربية', ar: 'العربية', pl: 'العربية', it: 'العربية', sk: 'العربية' }),
      pl: t({ ru: 'Polski', en: 'Polski', kk: 'Polski', de: 'Polski', fr: 'Polski', es: 'Polski', pt: 'Polski', tr: 'Polski', uk: 'Polski', zh: 'Polski', ar: 'Polski', pl: 'Polski', it: 'Polski', sk: 'Polski' }),
      it: t({ ru: 'Italiano', en: 'Italiano', kk: 'Italiano', de: 'Italiano', fr: 'Italiano', es: 'Italiano', pt: 'Italiano', tr: 'Italiano', uk: 'Italiano', zh: 'Italiano', ar: 'Italiano', pl: 'Italiano', it: 'Italiano', sk: 'Italiano' }),
      sk: t({ ru: 'Slovenčina', en: 'Slovenčina', kk: 'Slovenčina', de: 'Slovenčina', fr: 'Slovenčina', es: 'Slovenčina', pt: 'Slovenčina', tr: 'Slovenčina', uk: 'Slovenčina', zh: 'Slovenčina', ar: 'Slovenčina', pl: 'Slovenčina', it: 'Slovenčina', sk: 'Slovenčina' }),
    },
  },
} satisfies Dictionary;

export default content;
