import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'notificationDropdown',
  content: {
    title: t({
      ru: 'Уведомления',
      en: 'Notifications',
      kk: 'Хабарландырулар',
      de: 'Benachrichtigungen',
      fr: 'Notifications',
      es: 'Notificaciones',
      pt: 'Notificações',
      tr: 'Bildirimler',
      uk: 'Сповіщення',
      zh: '通知',
      ar: 'الإشعارات',
      pl: 'Powiadomienia',
      it: 'Notifiche',
      sk: 'Powiadomienia',
      ja: '通知',
      ko: '알림',
      hi: 'सूचनाएं',
      nl: 'Meldingen',
      sv: 'Aviseringar',
      vi: 'Thông báo',
      id: 'Notifikasi',
    }),
    markAllRead: t({
      ru: 'Прочитать все',
      en: 'Mark all as read',
      kk: 'Барлығын оқылған ету',
      de: 'Alle als gelesen markieren',
      fr: 'Tout marquer comme lu',
      es: 'Marcar todo como leído',
      pt: 'Marcar tudo como lido',
      tr: 'Tümünü okundu işaretle',
      uk: 'Позначити все як прочитане',
      zh: '全部标为已读',
      ar: 'تحديد الكل كمقروء',
      pl: 'Oznacz wszystkie jako przeczytane',
      it: 'Segna tutto come letto',
      sk: 'Oznacz wszystkie jako przeczytane',
      ja: 'すべて既読にする',
      ko: '모두 읽음으로 표시',
      hi: 'सभी को पढ़ा हुआ चिह्नित करें',
      nl: 'Alles als gelezen markeren',
      sv: 'Markera allt som läst',
      vi: 'Đánh dấu tất cả là đã đọc',
      id: 'Tandai semua sebagai dibaca',
    }),
    loading: t({
      ru: 'Загрузка...',
      en: 'Loading...',
      kk: 'Жүктелуде...',
      de: 'Laden...',
      fr: 'Chargement...',
      es: 'Cargando...',
      pt: 'Carregando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '加载中...',
      ar: 'جارٍ التحميل...',
      pl: 'Ładowanie...',
      it: 'Caricamento...',
      sk: 'Ładowanie...',
      ja: '読み込み中...',
      ko: '로딩 중...',
      hi: 'लोड हो रहा है...',
      nl: 'Laden...',
      sv: 'Laddar...',
      vi: 'Đang tải...',
      id: 'Memuat...',
    }),
    empty: t({
      ru: 'Нет новых уведомлений',
      en: 'No new notifications',
      kk: 'Жаңа хабарландыру жоқ',
      de: 'Keine neuen Benachrichtigungen',
      fr: 'Aucune nouvelle notification',
      es: 'No hay nuevas notificaciones',
      pt: 'Sem novas notificações',
      tr: 'Yeni bildirim yok',
      uk: 'Немає нових сповіщень',
      zh: '没有新通知',
      ar: 'لا توجد إشعارات جديدة',
      pl: 'Brak nowych powiadomień',
      it: 'Nessuna nuova notifica',
      sk: 'Brak nowych powiadomień',
      ja: '新しい通知はありません',
      ko: '새 알림이 없습니다',
      hi: 'कोई नई सूचना नहीं',
      nl: 'Geen nieuwe meldingen',
      sv: 'Inga nya aviseringar',
      vi: 'Không có thông báo mới',
      id: 'Tidak ada notifikasi baru',
    }),
    settingsLink: t({
      ru: 'Настройки уведомлений',
      en: 'Notification settings',
      kk: 'Хабарландыру баптаулары',
      de: 'Benachrichtigungseinstellungen',
      fr: 'Paramètres de notification',
      es: 'Configuración de notificaciones',
      pt: 'Configurações de notificações',
      tr: 'Bildirim ayarları',
      uk: 'Налаштування сповіщень',
      zh: '通知设置',
      ar: 'إعدادات الإشعارات',
      pl: 'Ustawienia powiadomień',
      it: 'Impostazioni notifiche',
      sk: 'Ustawienia powiadomień',
      ja: '通知設定',
      ko: '알림 설정',
      hi: 'सूचना सेटिंग',
      nl: 'Meldingsinstellingen',
      sv: 'Aviseringsinställningar',
      vi: 'Cài đặt thông báo',
      id: 'Pengaturan notifikasi',
    }),
    justNow: t({
      ru: 'только что',
      en: 'just now',
      kk: 'дәл қазір',
      de: 'gerade eben',
      fr: "à l'instant",
      es: 'justo ahora',
      pt: 'agora mesmo',
      tr: 'şu an',
      uk: 'щойно',
      zh: '刚刚',
      ar: 'الآن',
      pl: 'przed chwilą',
      it: 'proprio ora',
      sk: 'pred chwilą',
      ja: 'たった今',
      ko: '방금',
      hi: 'अभी',
      nl: 'zojuist',
      sv: 'nyss',
      vi: 'vừa xong',
      id: 'baru saja',
    }),
    aria: {
      notifications: t({
        ru: 'Уведомления',
        en: 'Notifications',
        kk: 'Хабарландырулар',
        de: 'Benachrichtigungen',
        fr: 'Notifications',
        es: 'Notificaciones',
        pt: 'Notificações',
        tr: 'Bildirimler',
        uk: 'Сповіщення',
        zh: '通知',
        ar: 'الإشعارات',
        pl: 'Powiadomienia',
        it: 'Notifiche',
        sk: 'Powiadomienia',
        ja: '通知',
        ko: '알림',
        hi: 'सूचनाएं',
        nl: 'Meldingen',
        sv: 'Aviseringar',
        vi: 'Thông báo',
        id: 'Notifikasi',
      }),
    },
  },
} satisfies Dictionary;

export default content;
