import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'notificationDropdown',
  content: {
    title: t({
      ru: 'Уведомления',
      en: 'Notifications',
      kk: 'Хабарландырулар',
      de: 'Benachrichtigungen',
      fr: 'Notifications',
      es: 'Notificaciones',
      pt: 'Notificações',
      tr: 'Bildirimler',
      uk: 'Сповіщення',
      zh: '通知',
      ar: 'الإشعارات',
      pl: 'Powiadomienia',
      it: 'Notifiche',
      sk: 'Powiadomienia',
    }),
    markAllRead: t({
      ru: 'Прочитать все',
      en: 'Mark all as read',
      kk: 'Барлығын оқылған ету',
      de: 'Alle als gelesen markieren',
      fr: 'Tout marquer comme lu',
      es: 'Marcar todo como leído',
      pt: 'Marcar tudo como lido',
      tr: 'Tümünü okundu işaretle',
      uk: 'Позначити все як прочитане',
      zh: '全部标为已读',
      ar: 'تحديد الكل كمقروء',
      pl: 'Oznacz wszystkie jako przeczytane',
      it: 'Segna tutto come letto',
      sk: 'Oznacz wszystkie jako przeczytane',
    }),
    loading: t({
      ru: 'Загрузка...',
      en: 'Loading...',
      kk: 'Жүктелуде...',
      de: 'Laden...',
      fr: 'Chargement...',
      es: 'Cargando...',
      pt: 'Carregando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '加载中...',
      ar: 'جارٍ التحميل...',
      pl: 'Ładowanie...',
      it: 'Caricamento...',
      sk: 'Ładowanie...',
    }),
    empty: t({
      ru: 'Нет новых уведомлений',
      en: 'No new notifications',
      kk: 'Жаңа хабарландыру жоқ',
      de: 'Keine neuen Benachrichtigungen',
      fr: 'Aucune nouvelle notification',
      es: 'No hay nuevas notificaciones',
      pt: 'Sem novas notificações',
      tr: 'Yeni bildirim yok',
      uk: 'Немає нових сповіщень',
      zh: '没有新通知',
      ar: 'لا توجد إشعارات جديدة',
      pl: 'Brak nowych powiadomień',
      it: 'Nessuna nuova notifica',
      sk: 'Brak nowych powiadomień',
    }),
    settingsLink: t({
      ru: 'Настройки уведомлений',
      en: 'Notification settings',
      kk: 'Хабарландыру баптаулары',
      de: 'Benachrichtigungseinstellungen',
      fr: 'Paramètres de notification',
      es: 'Configuración de notificaciones',
      pt: 'Configurações de notificações',
      tr: 'Bildirim ayarları',
      uk: 'Налаштування сповіщень',
      zh: '通知设置',
      ar: 'إعدادات الإشعارات',
      pl: 'Ustawienia powiadomień',
      it: 'Impostazioni notifiche',
      sk: 'Ustawienia powiadomień',
    }),
    justNow: t({
      ru: 'только что',
      en: 'just now',
      kk: 'дәл қазір',
      de: 'gerade eben',
      fr: "à l'instant",
      es: 'justo ahora',
      pt: 'agora mesmo',
      tr: 'şu an',
      uk: 'щойно',
      zh: '刚刚',
      ar: 'الآن',
      pl: 'przed chwilą',
      it: 'proprio ora',
      sk: 'przed chwilą',
    }),
    aria: {
      notifications: t({
        ru: 'Уведомления',
        en: 'Notifications',
        kk: 'Хабарландырулар',
        de: 'Benachrichtigungen',
        fr: 'Notifications',
        es: 'Notificaciones',
        pt: 'Notificações',
        tr: 'Bildirimler',
        uk: 'Сповіщення',
        zh: '通知',
        ar: 'الإشعارات',
        pl: 'Powiadomienia',
        it: 'Notifiche',
        sk: 'Powiadomienia',
      }),
    },
  },
} satisfies Dictionary;

export default content;
