import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'pdfPreviewModal',
  content: {
    errors: {
      authRequired: t({
        ru: 'Необходима авторизация',
        en: 'Authorization required',
        kk: 'Авторизация қажет',
        de: 'Autorisierung erforderlich',
        fr: 'Autorisation requise',
        es: 'Autorización requerida',
        pt: 'Autorização necessária',
        tr: 'Yetkilendirme gerekli',
        uk: 'Необхідна авторизація',
        zh: '需要授权',
        ar: 'التفويض مطلوب',
        pl: 'Wymagana autoryzacja',
        it: 'Autorizzazione richiesta',
        sk: 'Wymagana autoryzacja',
      }),
      fileLoadFailed: t({
        ru: 'Не удалось загрузить файл',
        en: 'Failed to load file',
        kk: 'Файлды жүктеу мүмкін болмады',
        de: 'Datei konnte nicht geladen werden',
        fr: 'Impossible de charger le fichier',
        es: 'No se pudo cargar el archivo',
        pt: 'Falha ao carregar o arquivo',
        tr: 'Dosya yüklenemedi',
        uk: 'Не вдалося завантажити файл',
        zh: '加载文件失败',
        ar: 'فشل تحميل الملف',
        pl: 'Nie udało się załadować pliku',
        it: 'Impossibile caricare il file',
        sk: 'Nie udało się załadować pliku',
      }),
      fileLoadError: t({
        ru: 'Ошибка загрузки файла',
        en: 'File loading error',
        kk: 'Файлды жүктеу қатесі',
        de: 'Fehler beim Laden der Datei',
        fr: 'Erreur de chargement du fichier',
        es: 'Error al cargar el archivo',
        pt: 'Erro ao carregar o arquivo',
        tr: 'Dosya yükleme hatası',
        uk: 'Помилка завантаження файлу',
        zh: '文件加载错误',
        ar: 'خطأ في تحميل الملف',
        pl: 'Błąd ładowania pliku',
        it: 'Errore nel caricamento del file',
        sk: 'Błąd ładowania pliku',
      }),
      pdfRendererFailed: t({
        ru: 'Не удалось загрузить просмотрщик PDF',
        en: 'Failed to load PDF viewer',
        kk: 'PDF көрсеткішті жүктеу мүмкін болмады',
        de: 'PDF-Viewer konnte nicht geladen werden',
        fr: 'Impossible de charger la visionneuse PDF',
        es: 'No se pudo cargar el visor de PDF',
        pt: 'Falha ao carregar o visualizador de PDF',
        tr: 'PDF görüntüleyici yüklenemedi',
        uk: 'Не вдалося завантажити переглядач PDF',
        zh: '加载PDF查看器失败',
        ar: 'فشل تحميل عارض PDF',
        pl: 'Nie udało się załadować przeglądarki PDF',
        it: 'Impossibile caricare il visualizzatore PDF',
        sk: 'Nie udało się załadować przeglądarki PDF',
      }),
      downloadFailed: t({
        ru: 'Ошибка скачивания файла',
        en: 'File download error',
        kk: 'Файлды жүктеп алу қатесі',
        de: 'Fehler beim Herunterladen der Datei',
        fr: 'Erreur de téléchargement du fichier',
        es: 'Error al descargar el archivo',
        pt: 'Erro ao baixar o arquivo',
        tr: 'Dosya indirme hatası',
        uk: 'Помилка завантаження файлу',
        zh: '文件下载错误',
        ar: 'خطأ في تنزيل الملف',
        pl: 'Błąd pobierania pliku',
        it: 'Errore nel download del file',
        sk: 'Błąd pobierania pliku',
      }),
      downloadAlertFailed: t({
        ru: 'Не удалось скачать файл',
        en: 'Failed to download file',
        kk: 'Файлды жүктеп алу мүмкін болмады',
        de: 'Datei konnte nicht heruntergeladen werden',
        fr: 'Impossible de télécharger le fichier',
        es: 'No se pudo descargar el archivo',
        pt: 'Falha ao baixar o arquivo',
        tr: 'Dosya indirilemedi',
        uk: 'Не вдалося завантажити файл',
        zh: '下载文件失败',
        ar: 'فشل تنزيل الملف',
        pl: 'Nie udało się pobrać pliku',
        it: 'Impossibile scaricare il file',
        sk: 'Nie udało się pobrać pliku',
      }),
      uploadFailed: t({
        ru: 'Не удалось загрузить файл',
        en: 'Failed to upload file',
        kk: 'Файлды жүктеу мүмкін болмады',
        de: 'Datei konnte nicht hochgeladen werden',
        fr: 'Impossible de téléverser le fichier',
        es: 'No se pudo subir el archivo',
        pt: 'Falha ao enviar o arquivo',
        tr: 'Dosya yüklenemedi',
        uk: 'Не вдалося завантажити файл',
        zh: '上传文件失败',
        ar: 'فشل رفع الملف',
        pl: 'Nie udało się przesłać pliku',
        it: 'Impossibile caricare il file',
        sk: 'Nie udało się przesłać pliku',
      }),
      parsingFailed: t({
        ru: 'Не удалось запустить парсинг',
        en: 'Failed to start parsing',
        kk: 'Парсингті бастау мүмкін болмады',
        de: 'Parsing konnte nicht gestartet werden',
        fr: "Impossible de démarrer l'analyse",
        es: 'No se pudo iniciar el análisis',
        pt: 'Falha ao iniciar o parsing',
        tr: 'Ayrıştırma başlatılamadı',
        uk: 'Не вдалося запустити парсинг',
        zh: '启动解析失败',
        ar: 'فشل بدء التحليل',
        pl: 'Nie udało się uruchomić parsowania',
        it: 'Impossibile avviare il parsing',
        sk: 'Nie udało się uruchomić parsowania',
      }),
      displayFailed: t({
        ru: 'Не удалось отобразить документ',
        en: 'Failed to display document',
        kk: 'Құжатты көрсету мүмкін болмады',
        de: 'Dokument konnte nicht angezeigt werden',
        fr: "Impossible d'afficher le document",
        es: 'No se pudo mostrar el documento',
        pt: 'Falha ao exibir o documento',
        tr: 'Belge görüntülenemedi',
        uk: 'Не вдалося відобразити документ',
        zh: '显示文档失败',
        ar: 'فشل عرض المستند',
        pl: 'Nie udało się wyświetlić dokumentu',
        it: 'Impossibile visualizzare il documento',
        sk: 'Nie udało się wyświetlić dokumentu',
      }),
    },
    loading: t({
      ru: 'Загрузка документа...',
      en: 'Loading document...',
      kk: 'Құжат жүктелуде...',
      de: 'Dokument wird geladen...',
      fr: 'Chargement du document...',
      es: 'Cargando documento...',
      pt: 'Carregando documento...',
      tr: 'Belge yükleniyor...',
      uk: 'Завантаження документа...',
      zh: '正在加载文档...',
      ar: 'جارٍ تحميل المستند...',
      pl: 'Ładowanie dokumentu...',
      it: 'Caricamento documento...',
      sk: 'Ładowanie dokumentu...',
    }),
    fileNotAttached: t({
      ru: 'Файл не прикреплен',
      en: 'File not attached',
      kk: 'Файл тіркелмеген',
      de: 'Datei nicht angehängt',
      fr: 'Fichier non attaché',
      es: 'Archivo no adjunto',
      pt: 'Arquivo não anexado',
      tr: 'Dosya eklenmedi',
      uk: 'Файл не прикріплено',
      zh: '文件未附加',
      ar: 'الملف غير مرفق',
      pl: 'Plik nie jest dołączony',
      it: 'File non allegato',
      sk: 'Plik nie jest dołączony',
    }),
    loadError: t({
      ru: 'Ошибка загрузки',
      en: 'Loading error',
      kk: 'Жүктеу қатесі',
      de: 'Ladefehler',
      fr: 'Erreur de chargement',
      es: 'Error de carga',
      pt: 'Erro de carregamento',
      tr: 'Yükleme hatası',
      uk: 'Помилка завантаження',
      zh: '加载错误',
      ar: 'خطأ في التحميل',
      pl: 'Błąd ładowania',
      it: 'Errore di caricamento',
      sk: 'Błąd ładowania',
    }),
    uploadFileHint: t({
      ru: 'Загрузите файл, чтобы открыть превью документа',
      en: 'Upload a file to open document preview',
      kk: 'Құжатты алдын ала қарау үшін файлды жүктеңіз',
      de: 'Laden Sie eine Datei hoch, um die Dokumentvorschau zu öffnen',
      fr: 'Téléversez un fichier pour ouvrir la prévisualisation du document',
      es: 'Suba un archivo para abrir la vista previa del documento',
      pt: 'Envie um arquivo para abrir a visualização do documento',
      tr: 'Belge önizlemesini açmak için bir dosya yükleyin',
      uk: 'Завантажте файл, щоб відкрити попередній перегляд документа',
      zh: '上传文件以打开文档预览',
      ar: 'قم برفع ملف لفتح معاينة المستند',
      pl: 'Prześlij plik, aby otworzyć podgląd dokumentu',
      it: 'Carica un file per aprire la anteprima del documento',
      sk: 'Prześlij plik, aby otworzyć podgląd dokumentu',
    }),
    uploading: t({
      ru: 'Загрузка...',
      en: 'Uploading...',
      kk: 'Жүктелуде...',
      de: 'Hochladen...',
      fr: 'Téléversement...',
      es: 'Subiendo...',
      pt: 'Enviando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '上传中...',
      ar: 'جارٍ الرفع...',
      pl: 'Przesyłanie...',
      it: 'Caricamento...',
      sk: 'Przesyłanie...',
    }),
    uploadFile: t({
      ru: 'Загрузить файл',
      en: 'Upload file',
      kk: 'Файлды жүктеу',
      de: 'Datei hochladen',
      fr: 'Téléverser le fichier',
      es: 'Subir archivo',
      pt: 'Enviar arquivo',
      tr: 'Dosya yükle',
      uk: 'Завантажити файл',
      zh: '上传文件',
      ar: 'رفع ملف',
      pl: 'Prześlij plik',
      it: 'Carica file',
      sk: 'Prześlij plik',
    }),
    close: t({
      ru: 'Закрыть',
      en: 'Close',
      kk: 'Жабу',
      de: 'Schließen',
      fr: 'Fermer',
      es: 'Cerrar',
      pt: 'Fechar',
      tr: 'Kapat',
      uk: 'Закрити',
      zh: '关闭',
      ar: 'إغلاق',
      pl: 'Zamknij',
      it: 'Chiudi',
      sk: 'Zamknij',
    }),
    startParsing: t({
      ru: 'Запустить парсинг?',
      en: 'Start parsing?',
      kk: 'Парсингті бастау керек пе?',
      de: 'Parsing starten?',
      fr: "Démarrer l'analyse ?",
      es: '¿Iniciar análisis?',
      pt: 'Iniciar parsing?',
      tr: 'Ayrıştırma başlatılsın mı?',
      uk: 'Запустити парсинг?',
      zh: '开始解析？',
      ar: 'هل تريد بدء التحليل؟',
      pl: 'Uruchomić parsowanie?',
      it: 'Avviare il parsing?',
      sk: 'Uruchomić parsowanie?',
    }),
    startParsingDescription: t({
      ru: 'Хотите извлечь данные из загруженной выписки и заменить текущие ручные значения?',
      en: 'Would you like to extract data from the uploaded statement and replace the current manual values?',
      kk: 'Жүктелген үзіндіден деректерді шығарып, ағымдағы қолмен енгізілген мәндерді ауыстырғыңыз келе ме?',
      de: 'Möchten Sie Daten aus dem hochgeladenen Auszug extrahieren und die aktuellen manuellen Werte ersetzen?',
      fr: "Voulez-vous extraire les données du relevé téléversé et remplacer les valeurs manuelles actuelles ?",
      es: '¿Desea extraer datos del extracto subido y reemplazar los valores manuales actuales?',
      pt: 'Deseja extrair dados do extrato enviado e substituir os valores manuais atuais?',
      tr: 'Yüklenen ekstreden veri çıkarmak ve mevcut manuel değerleri değiştirmek ister misiniz?',
      uk: 'Бажаєте витягти дані із завантаженої виписки та замінити поточні ручні значення?',
      zh: '是否要从上传的账单中提取数据并替换当前的手动值？',
      ar: 'هل تريد استخراج البيانات من الكشف المرفوع واستبدال القيم اليدوية الحالية؟',
      pl: 'Czy chcesz wyodrębnić dane z przesłanego wyciągu i zastąpić bieżące wartości ręczne?',
      it: 'Vuoi estrarre i dati dall\'estratto caricato e sostituire i valori manuali attuali?',
      sk: 'Czy chcesz wyodrębnić dane z przesłanego wyciągu i zastąpić bieżące wartości ręczne?',
    }),
    decline: t({
      ru: 'Отказаться',
      en: 'Decline',
      kk: 'Бас тарту',
      de: 'Ablehnen',
      fr: 'Refuser',
      es: 'Rechazar',
      pt: 'Recusar',
      tr: 'Reddet',
      uk: 'Відмовитися',
      zh: '拒绝',
      ar: 'رفض',
      pl: 'Odrzuć',
      it: 'Rifiuta',
      sk: 'Odrzuć',
    }),
    startingParsing: t({
      ru: 'Запуск...',
      en: 'Starting...',
      kk: 'Іске қосылуда...',
      de: 'Starte...',
      fr: 'Démarrage...',
      es: 'Iniciando...',
      pt: 'Iniciando...',
      tr: 'Başlatılıyor...',
      uk: 'Запуск...',
      zh: '启动中...',
      ar: 'جارٍ البدء...',
      pl: 'Uruchamianie...',
      it: 'Avvio...',
      sk: 'Uruchamianie...',
    }),
    startParsingButton: t({
      ru: 'Запустить парсинг',
      en: 'Start parsing',
      kk: 'Парсингті бастау',
      de: 'Parsing starten',
      fr: "Démarrer l'analyse",
      es: 'Iniciar análisis',
      pt: 'Iniciar parsing',
      tr: 'Ayrıştırmayı başlat',
      uk: 'Запустити парсинг',
      zh: '开始解析',
      ar: 'بدء التحليل',
      pl: 'Uruchom parsowanie',
      it: 'Avvia parsing',
      sk: 'Uruchom parsowanie',
    }),
  },
} satisfies Dictionary;

export default content;
