import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'permissionsPanel',
  content: {
    title: t({
      ru: 'Права доступа',
      en: 'Permissions',
      kk: 'Қолжетімділік құқықтары',
      de: 'Berechtigungen',
      fr: 'Autorisations',
      es: 'Permisos',
      pt: 'Permissões',
      tr: 'İzinler',
      uk: 'Права доступу',
      zh: '权限',
      ar: 'الأذونات',
      pl: 'Uprawnienia',
      it: 'Autorizzazioni',
      sk: 'Uprawnienia',
    }),
    grantAccess: t({
      ru: 'Предоставить доступ',
      en: 'Grant access',
      kk: 'Қолжетімділік беру',
      de: 'Zugriff gewähren',
      fr: "Accorder l'accès",
      es: 'Conceder acceso',
      pt: 'Conceder acesso',
      tr: 'Erişim ver',
      uk: 'Надати доступ',
      zh: '授予访问权限',
      ar: 'منح الوصول',
      pl: 'Przyznaj dostęp',
      it: 'Concedi accesso',
      sk: 'Przyznaj dostęp',
    }),
    empty: t({
      ru: 'Пока никому не предоставлен доступ к этому файлу',
      en: 'No one has been granted access to this file yet',
      kk: 'Бұл файлға әзірге ешкімге қолжетімділік берілген жоқ',
      de: 'Noch niemandem wurde Zugriff auf diese Datei gewährt',
      fr: "Personne n'a encore eu accès à ce fichier",
      es: 'Nadie ha recibido acceso a este archivo aún',
      pt: 'Ninguém recebeu acesso a este arquivo ainda',
      tr: 'Bu dosyaya henüz kimseye erişim verilmedi',
      uk: 'Нікому ще не надано доступ до цього файлу',
      zh: '尚未授予任何人访问此文件的权限',
      ar: 'لم يتم منح أي شخص حق الوصول إلى هذا الملف بعد',
      pl: 'Nikt nie otrzymał jeszcze dostępu do tego pliku',
      it: 'Nessuno ha ancora ricevuto accesso a questo file',
      sk: 'Nikt nie otrzymał jeszcze dostępu do tego pliku',
    }),
    confirmRevoke: t({
      ru: 'Вы уверены, что хотите отозвать права доступа?',
      en: 'Are you sure you want to revoke access?',
      kk: 'Қолжетімділікті қайтарып алғыңыз келетініне сенімдісіз бе?',
      de: 'Sind Sie sicher, dass Sie den Zugriff widerrufen möchten?',
      fr: "Êtes-vous sûr de vouloir révoquer l'accès ?",
      es: '¿Está seguro de que desea revocar el acceso?',
      pt: 'Tem certeza de que deseja revogar o acesso?',
      tr: 'Erişimi iptal etmek istediğinizden emin misiniz?',
      uk: 'Ви впевнені, що хочете відкликати права доступу?',
      zh: '您确定要撤销访问权限吗？',
      ar: 'هل أنت متأكد أنك تريد إلغاء الوصول؟',
      pl: 'Czy na pewno chcesz odwołać dostęp?',
      it: 'Sei sicuro di voler revocare l\'accesso?',
      sk: 'Czy na pewno chcesz odwołać dostęp?',
    }),
    errors: {
      grantFailed: t({
        ru: 'Не удалось предоставить доступ',
        en: 'Failed to grant access',
        kk: 'Қолжетімділік беру мүмкін болмады',
        de: 'Zugriff konnte nicht gewährt werden',
        fr: "Impossible d'accorder l'accès",
        es: 'No se pudo conceder el acceso',
        pt: 'Falha ao conceder acesso',
        tr: 'Erişim verilemedi',
        uk: 'Не вдалося надати доступ',
        zh: '授予访问权限失败',
        ar: 'فشل منح الوصول',
        pl: 'Nie udało się przyznać dostępu',
        it: 'Impossibile concedere l\'accesso',
        sk: 'Nie udało się przyznać dostępu',
      }),
      updateFailed: t({
        ru: 'Не удалось обновить права',
        en: 'Failed to update permissions',
        kk: 'Құқықтарды жаңарту мүмкін болмады',
        de: 'Berechtigungen konnten nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour les autorisations',
        es: 'No se pudieron actualizar los permisos',
        pt: 'Falha ao atualizar permissões',
        tr: 'İzinler güncellenemedi',
        uk: 'Не вдалося оновити права',
        zh: '更新权限失败',
        ar: 'فشل تحديث الأذونات',
        pl: 'Nie udało się zaktualizować uprawnień',
        it: 'Impossibile aggiornare le autorizzazioni',
        sk: 'Nie udało się zaktualizować uprawnień',
      }),
    },
    table: {
      user: t({
        ru: 'Пользователь',
        en: 'User',
        kk: 'Пайдаланушы',
        de: 'Benutzer',
        fr: 'Utilisateur',
        es: 'Usuario',
        pt: 'Usuário',
        tr: 'Kullanıcı',
        uk: 'Користувач',
        zh: '用户',
        ar: 'المستخدم',
        pl: 'Użytkownik',
        it: 'Utente',
        sk: 'Użytkownik',
      }),
      rights: t({
        ru: 'Права',
        en: 'Rights',
        kk: 'Құқықтар',
        de: 'Rechte',
        fr: 'Droits',
        es: 'Derechos',
        pt: 'Direitos',
        tr: 'Haklar',
        uk: 'Права',
        zh: '权限',
        ar: 'الحقوق',
        pl: 'Prawa',
        it: 'Diritti',
        sk: 'Prawa',
      }),
      canReshare: t({
        ru: 'Может поделиться',
        en: 'Can reshare',
        kk: 'Бөлісе алады',
        de: 'Kann teilen',
        fr: 'Peut repartager',
        es: 'Puede compartir',
        pt: 'Pode compartilhar',
        tr: 'Yeniden paylaşabilir',
        uk: 'Може поділитися',
        zh: '可以重新分享',
        ar: 'يمكنه إعادة المشاركة',
        pl: 'Może udostępnić',
        it: 'Può ricondividere',
        sk: 'Może udostępnić',
      }),
      expires: t({
        ru: 'Срок действия',
        en: 'Expires',
        kk: 'Мерзімі',
        de: 'Läuft ab',
        fr: 'Expire',
        es: 'Vence',
        pt: 'Expira',
        tr: 'Sona erer',
        uk: 'Термін дії',
        zh: '到期',
        ar: 'ينتهي',
        pl: 'Wygasa',
        it: 'Scade',
        sk: 'Wygasa',
      }),
      grantedBy: t({
        ru: 'Предоставил',
        en: 'Granted by',
        kk: 'Берген',
        de: 'Gewährt von',
        fr: 'Accordé par',
        es: 'Concedido por',
        pt: 'Concedido por',
        tr: 'Veren',
        uk: 'Надано',
        zh: '授权人',
        ar: 'منح بواسطة',
        pl: 'Przyznane przez',
        it: 'Concesso da',
        sk: 'Przyznane przez',
      }),
      createdAt: t({
        ru: 'Создано',
        en: 'Created',
        kk: 'Құрылған',
        de: 'Erstellt',
        fr: 'Créé',
        es: 'Creado',
        pt: 'Criado',
        tr: 'Oluşturuldu',
        uk: 'Створено',
        zh: '创建时间',
        ar: 'تاريخ الإنشاء',
        pl: 'Utworzono',
        it: 'Creato',
        sk: 'Utworzono',
      }),
      actions: t({
        ru: 'Действия',
        en: 'Actions',
        kk: 'Әрекеттер',
        de: 'Aktionen',
        fr: 'Actions',
        es: 'Acciones',
        pt: 'Ações',
        tr: 'İşlemler',
        uk: 'Дії',
        zh: '操作',
        ar: 'الإجراءات',
        pl: 'Akcje',
        it: 'Azioni',
        sk: 'Akcje',
      }),
    },
    values: {
      yes: t({
        ru: 'Да',
        en: 'Yes',
        kk: 'Иә',
        de: 'Ja',
        fr: 'Oui',
        es: 'Sí',
        pt: 'Sim',
        tr: 'Evet',
        uk: 'Так',
        zh: '是',
        ar: 'نعم',
        pl: 'Tak',
        it: 'Sì',
        sk: 'Tak',
      }),
      no: t({
        ru: 'Нет',
        en: 'No',
        kk: 'Жоқ',
        de: 'Nein',
        fr: 'Non',
        es: 'No',
        pt: 'Não',
        tr: 'Hayır',
        uk: 'Ні',
        zh: '否',
        ar: 'لا',
        pl: 'Nie',
        it: 'No',
        sk: 'Nie',
      }),
      forever: t({
        ru: 'Бессрочно',
        en: 'Forever',
        kk: 'Мерзімсіз',
        de: 'Unbegrenzt',
        fr: 'Pour toujours',
        es: 'Sin límite',
        pt: 'Sem prazo',
        tr: 'Süresiz',
        uk: 'Безстроково',
        zh: '永久',
        ar: 'للأبد',
        pl: 'Na zawsze',
        it: 'Per sempre',
        sk: 'Na zawsze',
      }),
    },
    tooltips: {
      edit: t({
        ru: 'Редактировать',
        en: 'Edit',
        kk: 'Өзгерту',
        de: 'Bearbeiten',
        fr: 'Modifier',
        es: 'Editar',
        pt: 'Editar',
        tr: 'Düzenle',
        uk: 'Редагувати',
        zh: '编辑',
        ar: 'تعديل',
        pl: 'Edytuj',
        it: 'Modifica',
        sk: 'Edytuj',
      }),
      revoke: t({
        ru: 'Отозвать',
        en: 'Revoke',
        kk: 'Қайтарып алу',
        de: 'Widerrufen',
        fr: 'Révoquer',
        es: 'Revocar',
        pt: 'Revogar',
        tr: 'İptal et',
        uk: 'Відкликати',
        zh: '撤销',
        ar: 'إلغاء',
        pl: 'Odwołaj',
        it: 'Revoca',
        sk: 'Odwołaj',
      }),
    },
    permission: {
      owner: t({
        ru: 'Владелец',
        en: 'Owner',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
        sk: 'Właściciel',
      }),
      editor: t({
        ru: 'Редактор',
        en: 'Editor',
        kk: 'Өңдеуші',
        de: 'Bearbeiter',
        fr: 'Éditeur',
        es: 'Editor',
        pt: 'Editor',
        tr: 'Düzenleyici',
        uk: 'Редактор',
        zh: '编辑者',
        ar: 'المحرر',
        pl: 'Edytor',
        it: 'Editor',
        sk: 'Edytor',
      }),
      viewer: t({
        ru: 'Просмотр',
        en: 'Viewer',
        kk: 'Қараушы',
        de: 'Betrachter',
        fr: 'Lecteur',
        es: 'Lector',
        pt: 'Visualizador',
        tr: 'Görüntüleyici',
        uk: 'Перегляд',
        zh: '查看者',
        ar: 'عارض',
        pl: 'Przeglądający',
        it: 'Visualizzatore',
        sk: 'Przeglądający',
      }),
      downloader: t({
        ru: 'Скачивание',
        en: 'Download',
        kk: 'Жүктеу',
        de: 'Herunterladen',
        fr: 'Téléchargement',
        es: 'Descarga',
        pt: 'Download',
        tr: 'İndirme',
        uk: 'Завантаження',
        zh: '下载',
        ar: 'تنزيل',
        pl: 'Pobieranie',
        it: 'Download',
        sk: 'Pobieranie',
      }),
      editorLong: t({
        ru: 'Редактирование',
        en: 'Editing',
        kk: 'Өңдеу',
        de: 'Bearbeitung',
        fr: 'Édition',
        es: 'Edición',
        pt: 'Edição',
        tr: 'Düzenleme',
        uk: 'Редагування',
        zh: '编辑',
        ar: 'التحرير',
        pl: 'Edycja',
        it: 'Modifica',
        sk: 'Edycja',
      }),
      viewDownloadLong: t({
        ru: 'Просмотр и скачивание',
        en: 'View and download',
        kk: 'Қарау және жүктеу',
        de: 'Ansehen und herunterladen',
        fr: 'Voir et télécharger',
        es: 'Ver y descargar',
        pt: 'Visualizar e baixar',
        tr: 'Görüntüle ve indir',
        uk: 'Перегляд і завантаження',
        zh: '查看和下载',
        ar: 'عرض وتنزيل',
        pl: 'Przeglądaj i pobieraj',
        it: 'Visualizza e scarica',
        sk: 'Przeglądaj i pobieraj',
      }),
      default: t({
        ru: 'Права',
        en: 'Permissions',
        kk: 'Құқықтар',
        de: 'Berechtigungen',
        fr: 'Autorisations',
        es: 'Permisos',
        pt: 'Permissões',
        tr: 'İzinler',
        uk: 'Права',
        zh: '权限',
        ar: 'الأذونات',
        pl: 'Uprawnienia',
        it: 'Autorizzazioni',
        sk: 'Uprawnienia',
      }),
    },
    dialogs: {
      grantTitle: t({
        ru: 'Предоставить доступ',
        en: 'Grant access',
        kk: 'Қолжетімділік беру',
        de: 'Zugriff gewähren',
        fr: "Accorder l'accès",
        es: 'Conceder acceso',
        pt: 'Conceder acesso',
        tr: 'Erişim ver',
        uk: 'Надати доступ',
        zh: '授予访问权限',
        ar: 'منح الوصول',
        pl: 'Przyznaj dostęp',
        it: 'Concedi accesso',
        sk: 'Przyznaj dostęp',
      }),
      editTitle: t({
        ru: 'Редактировать права доступа',
        en: 'Edit permissions',
        kk: 'Қолжетімділік құқықтарын өзгерту',
        de: 'Berechtigungen bearbeiten',
        fr: 'Modifier les autorisations',
        es: 'Editar permisos',
        pt: 'Editar permissões',
        tr: 'İzinleri düzenle',
        uk: 'Редагувати права доступу',
        zh: '编辑权限',
        ar: 'تعديل الأذونات',
        pl: 'Edytuj uprawnienia',
        it: 'Modifica autorizzazioni',
        sk: 'Edytuj uprawnienia',
      }),
      userIdOrEmail: t({
        ru: 'Email или ID пользователя',
        en: 'User email or ID',
        kk: 'Пайдаланушы email немесе ID',
        de: 'Benutzer-E-Mail oder ID',
        fr: "E-mail ou ID de l'utilisateur",
        es: 'Email o ID del usuario',
        pt: 'E-mail ou ID do usuário',
        tr: 'Kullanıcı e-postası veya ID',
        uk: 'Email або ID користувача',
        zh: '用户邮箱或ID',
        ar: 'البريد الإلكتروني أو معرف المستخدم',
        pl: 'E-mail lub ID użytkownika',
        it: 'Email o ID utente',
        sk: 'E-mail lub ID użytkownika',
      }),
      userIdOrEmailHelp: t({
        ru: 'Введите email пользователя, которому хотите предоставить доступ',
        en: 'Enter the email of the user you want to grant access to',
        kk: 'Қолжетімділік бергіңіз келетін пайдаланушының email енгізіңіз',
        de: 'Geben Sie die E-Mail des Benutzers ein, dem Sie Zugriff gewähren möchten',
        fr: "Entrez l'e-mail de l'utilisateur auquel vous souhaitez accorder l'accès",
        es: 'Ingrese el email del usuario al que desea conceder acceso',
        pt: 'Digite o e-mail do usuário ao qual deseja conceder acesso',
        tr: 'Erişim vermek istediğiniz kullanıcının e-postasını girin',
        uk: 'Введіть email користувача, якому хочете надати доступ',
        zh: '输入您要授予访问权限的用户的邮箱',
        ar: 'أدخل البريد الإلكتروني للمستخدم الذي تريد منحه الوصول',
        pl: 'Wprowadź e-mail użytkownika, któremu chcesz przyznać dostęp',
        it: "Inserisci l'email dell'utente a cui vuoi concedere l'accesso",
        sk: 'Wprowadź e-mail użytkownika, któremu chcesz przyznać dostęp',
      }),
      accessLevel: t({
        ru: 'Уровень доступа',
        en: 'Access level',
        kk: 'Қолжетімділік деңгейі',
        de: 'Zugriffsstufe',
        fr: "Niveau d'accès",
        es: 'Nivel de acceso',
        pt: 'Nível de acesso',
        tr: 'Erişim seviyesi',
        uk: 'Рівень доступу',
        zh: '访问级别',
        ar: 'مستوى الوصول',
        pl: 'Poziom dostępu',
        it: 'Livello di accesso',
        sk: 'Poziom dostępu',
      }),
      expiresAt: t({
        ru: 'Срок действия (опционально)',
        en: 'Expiration (optional)',
        kk: 'Жарамдылық мерзімі (міндетті емес)',
        de: 'Ablaufdatum (optional)',
        fr: "Expiration (facultatif)",
        es: 'Vencimiento (opcional)',
        pt: 'Expiração (opcional)',
        tr: 'Son kullanma tarihi (isteğe bağlı)',
        uk: 'Термін дії (необов\'язково)',
        zh: '到期时间（可选）',
        ar: 'تاريخ الانتهاء (اختياري)',
        pl: 'Data wygaśnięcia (opcjonalnie)',
        it: 'Scadenza (opzionale)',
        sk: 'Data wygaśnięcia (opcjonalnie)',
      }),
      expiresAtHelp: t({
        ru: 'Оставьте пустым для бессрочного доступа',
        en: 'Leave empty for no expiration',
        kk: 'Мерзімсіз қолжетімділік үшін бос қалдырыңыз',
        de: 'Leer lassen für unbegrenzte Gültigkeit',
        fr: 'Laisser vide pour une durée illimitée',
        es: 'Dejar en blanco para acceso sin límite',
        pt: 'Deixe em branco para acesso sem prazo',
        tr: 'Süresiz erişim için boş bırakın',
        uk: 'Залиште порожнім для безстрокового доступу',
        zh: '留空则永不过期',
        ar: 'اتركه فارغاً للوصول غير المحدود',
        pl: 'Pozostaw puste dla nieograniczonego dostępu',
        it: 'Lascia vuoto per accesso senza scadenza',
        sk: 'Pozostaw puste dla nieograniczonego dostępu',
      }),
      reshare: t({
        ru: 'Разрешить делиться с другими',
        en: 'Allow sharing with others',
        kk: 'Басқалармен бөлісуге рұқсат беру',
        de: 'Teilen mit anderen erlauben',
        fr: 'Autoriser le partage avec d\'autres',
        es: 'Permitir compartir con otros',
        pt: 'Permitir compartilhamento com outros',
        tr: 'Diğerleriyle paylaşmaya izin ver',
        uk: 'Дозволити ділитися з іншими',
        zh: '允许与他人共享',
        ar: 'السماح بالمشاركة مع الآخرين',
        pl: 'Zezwól na udostępnianie innym',
        it: 'Consenti la condivisione con altri',
        sk: 'Zezwól na udostępnianie innym',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Anuluj',
      }),
      save: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Speichern',
        fr: 'Enregistrer',
        es: 'Guardar',
        pt: 'Salvar',
        tr: 'Kaydet',
        uk: 'Зберегти',
        zh: '保存',
        ar: 'حفظ',
        pl: 'Zapisz',
        it: 'Salva',
        sk: 'Zapisz',
      }),
      grant: t({
        ru: 'Предоставить доступ',
        en: 'Grant access',
        kk: 'Қолжетімділік беру',
        de: 'Zugriff gewähren',
        fr: "Accorder l'accès",
        es: 'Conceder acceso',
        pt: 'Conceder acesso',
        tr: 'Erişim ver',
        uk: 'Надати доступ',
        zh: '授予访问权限',
        ar: 'منح الوصول',
        pl: 'Przyznaj dostęp',
        it: 'Concedi accesso',
        sk: 'Przyznaj dostęp',
      }),
    },
  },
} satisfies Dictionary;

export default content;
