import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'shareDialog',
  content: {
    createTitle: t({
      ru: 'Создать новую ссылку',
      en: 'Create a new link',
      kk: 'Жаңа сілтеме жасау',
      de: 'Neuen Link erstellen',
      fr: 'Créer un nouveau lien',
      es: 'Crear un nuevo enlace',
      pt: 'Criar um novo link',
      tr: 'Yeni bağlantı oluştur',
      uk: 'Створити нове посилання',
      zh: '创建新链接',
      ar: 'إنشاء رابط جديد',
      pl: 'Utwórz nowy link',
      it: 'Crea un nuovo link',
    }),
    accessLevel: {
      label: t({
        ru: 'Уровень доступа',
        en: 'Access level',
        kk: 'Қолжетімділік деңгейі',
        de: 'Zugriffsstufe',
        fr: "Niveau d'accès",
        es: 'Nivel de acceso',
        pt: 'Nível de acesso',
        tr: 'Erişim seviyesi',
        uk: 'Рівень доступу',
        zh: '访问级别',
        ar: 'مستوى الوصول',
        pl: 'Poziom dostępu',
        it: 'Livello di accesso',
      }),
      view: t({
        ru: 'Только просмотр',
        en: 'View only',
        kk: 'Тек қарау',
        de: 'Nur ansehen',
        fr: 'Lecture seule',
        es: 'Solo ver',
        pt: 'Somente visualização',
        tr: 'Yalnızca görüntüle',
        uk: 'Тільки перегляд',
        zh: '仅查看',
        ar: 'عرض فقط',
        pl: 'Tylko podgląd',
        it: 'Solo visualizzazione',
      }),
      download: t({
        ru: 'Просмотр и скачивание',
        en: 'View and download',
        kk: 'Қарау және жүктеу',
        de: 'Ansehen und herunterladen',
        fr: 'Voir et télécharger',
        es: 'Ver y descargar',
        pt: 'Visualizar e baixar',
        tr: 'Görüntüle ve indir',
        uk: 'Перегляд і завантаження',
        zh: '查看和下载',
        ar: 'عرض وتنزيل',
        pl: 'Przeglądaj i pobieraj',
        it: 'Visualizza e scarica',
      }),
      edit: t({
        ru: 'Полный доступ',
        en: 'Full access',
        kk: 'Толық қолжетімділік',
        de: 'Vollzugriff',
        fr: 'Accès complet',
        es: 'Acceso completo',
        pt: 'Acesso completo',
        tr: 'Tam erişim',
        uk: 'Повний доступ',
        zh: '完全访问',
        ar: 'وصول كامل',
        pl: 'Pełny dostęp',
        it: 'Accesso completo',
      }),
    },
    expiresAt: t({
      ru: 'Срок действия (опционально)',
      en: 'Expiration (optional)',
      kk: 'Жарамдылық мерзімі (міндетті емес)',
      de: 'Ablaufdatum (optional)',
      fr: 'Expiration (facultatif)',
      es: 'Vencimiento (opcional)',
      pt: 'Expiração (opcional)',
      tr: 'Son kullanma tarihi (isteğe bağlı)',
      uk: 'Термін дії (необов\'язково)',
      zh: '到期时间（可选）',
      ar: 'تاريخ الانتهاء (اختياري)',
      pl: 'Data wygaśnięcia (opcjonalnie)',
      it: 'Scadenza (opzionale)',
    }),
    password: {
      label: t({
        ru: 'Пароль (опционально)',
        en: 'Password (optional)',
        kk: 'Құпиясөз (міндетті емес)',
        de: 'Passwort (optional)',
        fr: 'Mot de passe (facultatif)',
        es: 'Contraseña (opcional)',
        pt: 'Senha (opcional)',
        tr: 'Şifre (isteğe bağlı)',
        uk: 'Пароль (необов\'язково)',
        zh: '密码（可选）',
        ar: 'كلمة المرور (اختياري)',
        pl: 'Hasło (opcjonalnie)',
        it: 'Password (opzionale)',
      }),
      help: t({
        ru: 'Добавьте пароль для дополнительной защиты',
        en: 'Add a password for extra protection',
        kk: 'Қосымша қорғаныс үшін құпиясөз қосыңыз',
        de: 'Fügen Sie ein Passwort für zusätzlichen Schutz hinzu',
        fr: 'Ajoutez un mot de passe pour une protection supplémentaire',
        es: 'Agregue una contraseña para mayor protección',
        pt: 'Adicione uma senha para proteção extra',
        tr: 'Ekstra koruma için bir şifre ekleyin',
        uk: 'Додайте пароль для додаткового захисту',
        zh: '添加密码以提供额外保护',
        ar: 'أضف كلمة مرور لحماية إضافية',
        pl: 'Dodaj hasło dla dodatkowej ochrony',
        it: 'Aggiungi una password per una protezione extra',
      }),
    },
    description: {
      label: t({
        ru: 'Описание (опционально)',
        en: 'Description (optional)',
        kk: 'Сипаттама (міндетті емес)',
        de: 'Beschreibung (optional)',
        fr: 'Description (facultatif)',
        es: 'Descripción (opcional)',
        pt: 'Descrição (opcional)',
        tr: 'Açıklama (isteğe bağlı)',
        uk: 'Опис (необов\'язково)',
        zh: '描述（可选）',
        ar: 'الوصف (اختياري)',
        pl: 'Opis (opcjonalnie)',
        it: 'Descrizione (opzionale)',
      }),
      help: t({
        ru: 'Добавьте заметку о том, для кого эта ссылка',
        en: 'Add a note about who this link is for',
        kk: 'Бұл сілтеме кімге арналғанын көрсететін жазба қосыңыз',
        de: 'Fügen Sie eine Notiz hinzu, für wen dieser Link ist',
        fr: 'Ajoutez une note sur la destination de ce lien',
        es: 'Agregue una nota sobre para quién es este enlace',
        pt: 'Adicione uma nota sobre para quem este link é',
        tr: 'Bu bağlantının kime ait olduğuna dair bir not ekleyin',
        uk: 'Додайте нотатку про те, для кого це посилання',
        zh: '添加关于此链接用途的备注',
        ar: 'أضف ملاحظة حول من هذا الرابط له',
        pl: 'Dodaj notatkę o tym, dla kogo jest ten link',
        it: 'Aggiungi una nota su chi è destinato questo link',
      }),
    },
    allowAnonymous: t({
      ru: 'Разрешить доступ по ссылке без авторизации',
      en: 'Allow access via link without login',
      kk: 'Кірусіз сілтеме арқылы қол жеткізуге рұқсат беру',
      de: 'Zugriff über Link ohne Anmeldung erlauben',
      fr: "Autoriser l'accès via le lien sans connexion",
      es: 'Permitir acceso a través del enlace sin inicio de sesión',
      pt: 'Permitir acesso via link sem login',
      tr: 'Giriş yapmadan bağlantı üzerinden erişime izin ver',
      uk: 'Дозволити доступ за посиланням без авторизації',
      zh: '允许通过链接无需登录访问',
      ar: 'السماح بالوصول عبر الرابط بدون تسجيل دخول',
      pl: 'Zezwól na dostęp przez link bez logowania',
      it: 'Consenti accesso tramite link senza login',
    }),
    createButton: t({
      ru: 'Создать ссылку',
      en: 'Create link',
      kk: 'Сілтеме жасау',
      de: 'Link erstellen',
      fr: 'Créer le lien',
      es: 'Crear enlace',
      pt: 'Criar link',
      tr: 'Bağlantı oluştur',
      uk: 'Створити посилання',
      zh: '创建链接',
      ar: 'إنشاء رابط',
      pl: 'Utwórz link',
      it: 'Crea link',
    }),
    createdCopied: t({
      ru: 'Ссылка создана и скопирована в буфер обмена!',
      en: 'Link created and copied to clipboard!',
      kk: 'Сілтеме жасалып, алмасу буферіне көшірілді!',
      de: 'Link erstellt und in die Zwischenablage kopiert!',
      fr: 'Lien créé et copié dans le presse-papiers !',
      es: '¡Enlace creado y copiado al portapapeles!',
      pt: 'Link criado e copiado para a área de transferência!',
      tr: 'Bağlantı oluşturuldu ve panoya kopyalandı!',
      uk: 'Посилання створено і скопійовано в буфер обміну!',
      zh: '链接已创建并复制到剪贴板！',
      ar: 'تم إنشاء الرابط ونسخه إلى الحافظة!',
      pl: 'Link utworzony i skopiowany do schowka!',
      it: 'Link creato e copiato negli appunti!',
    }),
    activeLinks: t({
      ru: 'Активные ссылки',
      en: 'Active links',
      kk: 'Белсенді сілтемелер',
      de: 'Aktive Links',
      fr: 'Liens actifs',
      es: 'Enlaces activos',
      pt: 'Links ativos',
      tr: 'Aktif bağlantılar',
      uk: 'Активні посилання',
      zh: '活跃链接',
      ar: 'الروابط النشطة',
      pl: 'Aktywne linki',
      it: 'Link attivi',
    }),
    noLinks: t({
      ru: 'Пока нет активных ссылок для этого файла',
      en: 'There are no active links for this file yet',
      kk: 'Бұл файл үшін белсенді сілтемелер әзірге жоқ',
      de: 'Es gibt noch keine aktiven Links für diese Datei',
      fr: "Il n'y a pas encore de liens actifs pour ce fichier",
      es: 'Aún no hay enlaces activos para este archivo',
      pt: 'Ainda não há links ativos para este arquivo',
      tr: 'Bu dosya için henüz aktif bağlantı yok',
      uk: 'Ще немає активних посилань для цього файлу',
      zh: '此文件尚无活跃链接',
      ar: 'لا توجد روابط نشطة لهذا الملف بعد',
      pl: 'Nie ma jeszcze aktywnych linków do tego pliku',
      it: 'Non ci sono ancora link attivi per questo file',
    }),
    untilPrefix: t({
      ru: 'До',
      en: 'Until',
      kk: 'Дейін',
      de: 'Bis',
      fr: "Jusqu'au",
      es: 'Hasta',
      pt: 'Até',
      tr: 'Kadar',
      uk: 'До',
      zh: '至',
      ar: 'حتى',
      pl: 'Do',
      it: 'Fino al',
    }),
    createdPrefix: t({
      ru: 'Создана',
      en: 'Created',
      kk: 'Құрылды',
      de: 'Erstellt',
      fr: 'Créé',
      es: 'Creado',
      pt: 'Criado',
      tr: 'Oluşturuldu',
      uk: 'Створено',
      zh: '创建于',
      ar: 'تم الإنشاء',
      pl: 'Utworzono',
      it: 'Creato',
    }),
    visitsPrefix: t({
      ru: 'Переходов',
      en: 'Visits',
      kk: 'Өтулер',
      de: 'Besuche',
      fr: 'Visites',
      es: 'Visitas',
      pt: 'Visitas',
      tr: 'Ziyaret',
      uk: 'Переходів',
      zh: '访问次数',
      ar: 'الزيارات',
      pl: 'Odwiedziny',
      it: 'Visite',
    }),
    tooltips: {
      copy: t({
        ru: 'Копировать ссылку',
        en: 'Copy link',
        kk: 'Сілтемені көшіру',
        de: 'Link kopieren',
        fr: 'Copier le lien',
        es: 'Copiar enlace',
        pt: 'Copiar link',
        tr: 'Bağlantıyı kopyala',
        uk: 'Копіювати посилання',
        zh: '复制链接',
        ar: 'نسخ الرابط',
        pl: 'Kopiuj link',
        it: 'Copia link',
      }),
      delete: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Löschen',
        fr: 'Supprimer',
        es: 'Eliminar',
        pt: 'Excluir',
        tr: 'Sil',
        uk: 'Видалити',
        zh: '删除',
        ar: 'حذف',
        pl: 'Usuń',
        it: 'Elimina',
      }),
    },
    permissionLabel: {
      view: t({
        ru: 'Просмотр',
        en: 'View',
        kk: 'Қарау',
        de: 'Ansehen',
        fr: 'Voir',
        es: 'Ver',
        pt: 'Visualizar',
        tr: 'Görüntüle',
        uk: 'Перегляд',
        zh: '查看',
        ar: 'عرض',
        pl: 'Podgląd',
        it: 'Visualizza',
      }),
      download: t({
        ru: 'Просмотр и скачивание',
        en: 'View & download',
        kk: 'Қарау және жүктеу',
        de: 'Ansehen & herunterladen',
        fr: 'Voir & télécharger',
        es: 'Ver y descargar',
        pt: 'Visualizar e baixar',
        tr: 'Görüntüle ve indir',
        uk: 'Перегляд і завантаження',
        zh: '查看和下载',
        ar: 'عرض وتنزيل',
        pl: 'Przeglądaj i pobieraj',
        it: 'Visualizza e scarica',
      }),
      edit: t({
        ru: 'Полный доступ',
        en: 'Full access',
        kk: 'Толық қолжетімділік',
        de: 'Vollzugriff',
        fr: 'Accès complet',
        es: 'Acceso completo',
        pt: 'Acesso completo',
        tr: 'Tam erişim',
        uk: 'Повний доступ',
        zh: '完全访问',
        ar: 'وصول كامل',
        pl: 'Pełny dostęp',
        it: 'Accesso completo',
      }),
    },
    statusLabel: {
      active: t({
        ru: 'Активна',
        en: 'Active',
        kk: 'Белсенді',
        de: 'Aktiv',
        fr: 'Actif',
        es: 'Activo',
        pt: 'Ativo',
        tr: 'Aktif',
        uk: 'Активне',
        zh: '活跃',
        ar: 'نشط',
        pl: 'Aktywny',
        it: 'Attivo',
      }),
      expired: t({
        ru: 'Истекла',
        en: 'Expired',
        kk: 'Мерзімі өтті',
        de: 'Abgelaufen',
        fr: 'Expiré',
        es: 'Vencido',
        pt: 'Expirado',
        tr: 'Süresi doldu',
        uk: 'Термін закінчився',
        zh: '已过期',
        ar: 'منتهي الصلاحية',
        pl: 'Wygasły',
        it: 'Scaduto',
      }),
    },
  },
} satisfies Dictionary;

export default content;
