import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionDocumentViewer',
  content: {
    bankNotDetected: t({
      ru: 'Банк не определен',
      en: 'Bank not detected',
      kk: 'Банк анықталмаған',
      de: 'Bank nicht erkannt',
      fr: 'Banque non détectée',
      es: 'Banco no detectado',
      pt: 'Banco não detectado',
      tr: 'Banka tespit edilemedi',
      uk: 'Банк не визначено',
      zh: '未检测到银行',
      ar: 'لم يتم اكتشاف البنك',
      pl: 'Nie wykryto banku',
      it: 'Banca non rilevata',
    }),
    bankStatement: t({
      ru: 'Банковская выписка',
      en: 'Bank statement',
      kk: 'Банк үзіндісі',
      de: 'Kontoauszug',
      fr: 'Relevé bancaire',
      es: 'Extracto bancario',
      pt: 'Extrato bancário',
      tr: 'Banka ekstresi',
      uk: 'Банківська виписка',
      zh: '银行对账单',
      ar: 'كشف الحساب البنكي',
      pl: 'Wyciąg bankowy',
      it: 'Estratto conto bancario',
    }),
    accountNumber: t({
      ru: 'Номер счета',
      en: 'Account number',
      kk: 'Есепшот нөмірі',
      de: 'Kontonummer',
      fr: 'Numéro de compte',
      es: 'Número de cuenta',
      pt: 'Número da conta',
      tr: 'Hesap numarası',
      uk: 'Номер рахунку',
      zh: '账号',
      ar: 'رقم الحساب',
      pl: 'Numer konta',
      it: 'Numero di conto',
    }),
    statementPeriod: t({
      ru: 'Период выписки',
      en: 'Statement period',
      kk: 'Үзінді кезеңі',
      de: 'Auszugszeitraum',
      fr: 'Période du relevé',
      es: 'Período del extracto',
      pt: 'Período do extrato',
      tr: 'Ekstre dönemi',
      uk: 'Період виписки',
      zh: '账单周期',
      ar: 'فترة الكشف',
      pl: 'Okres wyciągu',
      it: 'Periodo del estratto',
    }),
    statementFile: t({
      ru: 'Файл выписки',
      en: 'Statement file',
      kk: 'Үзінді файлы',
      de: 'Auszugsdatei',
      fr: 'Fichier de relevé',
      es: 'Archivo de extracto',
      pt: 'Arquivo de extrato',
      tr: 'Ekstre dosyası',
      uk: 'Файл виписки',
      zh: '账单文件',
      ar: 'ملف الكشف',
      pl: 'Plik wyciągu',
      it: 'File estratto',
    }),
    openingBalance: t({
      ru: 'Начальный баланс',
      en: 'Opening balance',
      kk: 'Бастапқы қалдық',
      de: 'Anfangssaldo',
      fr: 'Solde d\'ouverture',
      es: 'Saldo inicial',
      pt: 'Saldo inicial',
      tr: 'Açılış bakiyesi',
      uk: 'Початковий баланс',
      zh: '期初余额',
      ar: 'الرصيد الافتتاحي',
      pl: 'Saldo otwarcia',
      it: 'Saldo iniziale',
    }),
    income: t({
      ru: 'Поступления',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Einnahmen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Receitas',
      tr: 'Gelir',
      uk: 'Надходження',
      zh: '收入',
      ar: 'الدخل',
      pl: 'Przychody',
      it: 'Entrate',
    }),
    expenses: t({
      ru: 'Списания',
      en: 'Expenses',
      kk: 'Шығыс',
      de: 'Ausgaben',
      fr: 'Dépenses',
      es: 'Gastos',
      pt: 'Despesas',
      tr: 'Giderler',
      uk: 'Списання',
      zh: '支出',
      ar: 'المصروفات',
      pl: 'Wydatki',
      it: 'Spese',
    }),
    closingBalance: t({
      ru: 'Конечный баланс',
      en: 'Closing balance',
      kk: 'Соңғы қалдық',
      de: 'Schlusssaldo',
      fr: 'Solde de clôture',
      es: 'Saldo final',
      pt: 'Saldo final',
      tr: 'Kapanış bakiyesi',
      uk: 'Кінцевий баланс',
      zh: '期末余额',
      ar: 'الرصيد الختامي',
      pl: 'Saldo zamknięcia',
      it: 'Saldo finale',
    }),
    balanceChange: t({
      ru: 'Изменение баланса за период',
      en: 'Balance change for the period',
      kk: 'Кезең ішіндегі қалдық өзгерісі',
      de: 'Saldoänderung für den Zeitraum',
      fr: 'Variation du solde sur la période',
      es: 'Cambio de saldo para el período',
      pt: 'Variação de saldo no período',
      tr: 'Dönem bakiye değişimi',
      uk: 'Зміна балансу за період',
      zh: '期间余额变动',
      ar: 'تغيير الرصيد للفترة',
      pl: 'Zmiana salda za okres',
      it: 'Variazione del saldo nel periodo',
    }),
    totalTransactions: t({
      ru: 'Всего транзакций',
      en: 'Total transactions',
      kk: 'Барлық транзакциялар',
      de: 'Transaktionen gesamt',
      fr: 'Total des transactions',
      es: 'Total de transacciones',
      pt: 'Total de transações',
      tr: 'Toplam işlem',
      uk: 'Всього транзакцій',
      zh: '交易总数',
      ar: 'إجمالي المعاملات',
      pl: 'Łączna liczba transakcji',
      it: 'Transazioni totali',
    }),
    transactionList: t({
      ru: 'Список транзакций',
      en: 'Transaction list',
      kk: 'Транзакциялар тізімі',
      de: 'Transaktionsliste',
      fr: 'Liste des transactions',
      es: 'Lista de transacciones',
      pt: 'Lista de transações',
      tr: 'İşlem listesi',
      uk: 'Список транзакцій',
      zh: '交易列表',
      ar: 'قائمة المعاملات',
      pl: 'Lista transakcji',
      it: 'Elenco transazioni',
    }),
    transactionListDescription: t({
      ru: 'Детальная информация по всем операциям',
      en: 'Detailed information on all transactions',
      kk: 'Барлық операциялар бойынша толық ақпарат',
      de: 'Detaillierte Informationen zu allen Transaktionen',
      fr: 'Informations détaillées sur toutes les transactions',
      es: 'Información detallada sobre todas las transacciones',
      pt: 'Informações detalhadas sobre todas as transações',
      tr: 'Tüm işlemler hakkında ayrıntılı bilgi',
      uk: 'Детальна інформація по всіх операціях',
      zh: '所有交易的详细信息',
      ar: 'معلومات تفصيلية حول جميع المعاملات',
      pl: 'Szczegółowe informacje o wszystkich operacjach',
      it: 'Informazioni dettagliate su tutte le transazioni',
    }),
    columns: {
      date: t({
        ru: 'Дата',
        en: 'Date',
        kk: 'Күні',
        de: 'Datum',
        fr: 'Date',
        es: 'Fecha',
        pt: 'Data',
        tr: 'Tarih',
        uk: 'Дата',
        zh: '日期',
        ar: 'التاريخ',
        pl: 'Data',
        it: 'Data',
      }),
      documentNumber: t({
        ru: 'Номер документа',
        en: 'Document number',
        kk: 'Құжат нөмірі',
        de: 'Dokumentnummer',
        fr: 'Numéro de document',
        es: 'Número de documento',
        pt: 'Número do documento',
        tr: 'Belge numarası',
        uk: 'Номер документа',
        zh: '单据号',
        ar: 'رقم المستند',
        pl: 'Numer dokumentu',
        it: 'Numero documento',
      }),
      counterparty: t({
        ru: 'Контрагент',
        en: 'Counterparty',
        kk: 'Контрагент',
        de: 'Gegenpartei',
        fr: 'Contrepartie',
        es: 'Contraparte',
        pt: 'Contraparte',
        tr: 'Karşı taraf',
        uk: 'Контрагент',
        zh: '对方',
        ar: 'الطرف المقابل',
        pl: 'Kontrahent',
        it: 'Controparte',
      }),
      bin: t({
        ru: 'БИН',
        en: 'BIN',
        kk: 'БСН',
        de: 'BIN',
        fr: 'BIN',
        es: 'BIN',
        pt: 'BIN',
        tr: 'BIN',
        uk: 'БІН',
        zh: 'BIN',
        ar: 'BIN',
        pl: 'BIN',
        it: 'BIN',
      }),
      paymentPurpose: t({
        ru: 'Назначение платежа',
        en: 'Payment purpose',
        kk: 'Төлем мақсаты',
        de: 'Verwendungszweck',
        fr: 'Objet du paiement',
        es: 'Concepto de pago',
        pt: 'Finalidade do pagamento',
        tr: 'Ödeme amacı',
        uk: 'Призначення платежу',
        zh: '付款用途',
        ar: 'غرض الدفع',
        pl: 'Tytuł płatności',
        it: 'Causale del pagamento',
      }),
      debit: t({
        ru: 'Дебет',
        en: 'Debit',
        kk: 'Дебет',
        de: 'Soll',
        fr: 'Débit',
        es: 'Débito',
        pt: 'Débito',
        tr: 'Borç',
        uk: 'Дебет',
        zh: '借方',
        ar: 'المدين',
        pl: 'Debet',
        it: 'Debito',
      }),
      credit: t({
        ru: 'Кредит',
        en: 'Credit',
        kk: 'Кредит',
        de: 'Haben',
        fr: 'Crédit',
        es: 'Crédito',
        pt: 'Crédito',
        tr: 'Alacak',
        uk: 'Кредит',
        zh: '贷方',
        ar: 'الدائن',
        pl: 'Kredyt',
        it: 'Credito',
      }),
      currency: t({
        ru: 'Валюта',
        en: 'Currency',
        kk: 'Валюта',
        de: 'Währung',
        fr: 'Devise',
        es: 'Moneda',
        pt: 'Moeda',
        tr: 'Para birimi',
        uk: 'Валюта',
        zh: '货币',
        ar: 'العملة',
        pl: 'Waluta',
        it: 'Valuta',
      }),
    },
    total: t({
      ru: 'ИТОГО:',
      en: 'TOTAL:',
      kk: 'БАРЛЫҒЫ:',
      de: 'GESAMT:',
      fr: 'TOTAL :',
      es: 'TOTAL:',
      pt: 'TOTAL:',
      tr: 'TOPLAM:',
      uk: 'РАЗОМ:',
      zh: '合计：',
      ar: 'الإجمالي:',
      pl: 'ŁĄCZNIE:',
      it: 'TOTALE:',
    }),
    totalExpenses: t({
      ru: 'Всего списаний',
      en: 'Total expenses',
      kk: 'Барлық шығыстар',
      de: 'Ausgaben gesamt',
      fr: 'Total des dépenses',
      es: 'Total de gastos',
      pt: 'Total de despesas',
      tr: 'Toplam giderler',
      uk: 'Всього списань',
      zh: '支出合计',
      ar: 'إجمالي المصروفات',
      pl: 'Łączne wydatki',
      it: 'Totale spese',
    }),
    totalIncome: t({
      ru: 'Всего поступлений',
      en: 'Total income',
      kk: 'Барлық кірістер',
      de: 'Einnahmen gesamt',
      fr: 'Total des revenus',
      es: 'Total de ingresos',
      pt: 'Total de receitas',
      tr: 'Toplam gelir',
      uk: 'Всього надходжень',
      zh: '收入合计',
      ar: 'إجمالي الدخل',
      pl: 'Łączne przychody',
      it: 'Totale entrate',
    }),
    footer: t({
      ru: 'Документ сформирован автоматически • Lumio Parse Ledger',
      en: 'Document generated automatically • Lumio Parse Ledger',
      kk: 'Құжат автоматты түрде қалыптастырылды • Lumio Parse Ledger',
      de: 'Dokument automatisch erstellt • Lumio Parse Ledger',
      fr: 'Document généré automatiquement • Lumio Parse Ledger',
      es: 'Documento generado automáticamente • Lumio Parse Ledger',
      pt: 'Documento gerado automaticamente • Lumio Parse Ledger',
      tr: 'Belge otomatik olarak oluşturuldu • Lumio Parse Ledger',
      uk: 'Документ сформований автоматично • Lumio Parse Ledger',
      zh: '文档自动生成 • Lumio Parse Ledger',
      ar: 'تم إنشاء المستند تلقائيًا • Lumio Parse Ledger',
      pl: 'Dokument wygenerowany automatycznie • Lumio Parse Ledger',
      it: 'Documento generato automaticamente • Lumio Parse Ledger',
    }),
  },
} satisfies Dictionary;

export default content;
