import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsView',
  content: {
    searchPlaceholder: t({
      ru: 'Поиск по контрагенту, назначению или категории...',
      en: 'Search by counterparty, purpose, or category...',
      kk: 'Контрагент, мақсат немесе санат бойынша іздеу...',
      de: 'Nach Gegenpartei, Zweck oder Kategorie suchen...',
      fr: 'Rechercher par contrepartie, objet ou catégorie...',
      es: 'Buscar por contraparte, propósito o categoría...',
      pt: 'Buscar por contraparte, finalidade ou categoria...',
      tr: 'Karşı taraf, amaç veya kategoriye göre ara...',
      uk: 'Пошук за контрагентом, призначенням або категорією...',
      zh: '按对方、用途或分类搜索...',
      ar: 'البحث بالطرف المقابل أو الغرض أو الفئة...',
      pl: 'Szukaj po kontrahencie, tytule lub kategorii...',
      it: 'Cerca per controparte, scopo o categoria...',
      sk: 'Szukaj po kontrahencie, tytule lub kategorii...',
    }),
    empty: t({
      ru: 'Транзакции не найдены',
      en: 'No transactions found',
      kk: 'Транзакциялар табылмады',
      de: 'Keine Transaktionen gefunden',
      fr: 'Aucune transaction trouvée',
      es: 'No se encontraron transacciones',
      pt: 'Nenhuma transação encontrada',
      tr: 'İşlem bulunamadı',
      uk: 'Транзакції не знайдено',
      zh: '未找到交易',
      ar: 'لم يتم العثور على معاملات',
      pl: 'Nie znaleziono transakcji',
      it: 'Nessuna transazione trovata',
      sk: 'Nie znaleziono transakcji',
    }),
    pagination: {
      rowsPerPage: t({
        ru: 'Строк на странице:',
        en: 'Rows per page:',
        kk: 'Беттегі жолдар:',
        de: 'Zeilen pro Seite:',
        fr: 'Lignes par page :',
        es: 'Filas por página:',
        pt: 'Linhas por página:',
        tr: 'Sayfa başına satır:',
        uk: 'Рядків на сторінці:',
        zh: '每页行数：',
        ar: 'صفوف في الصفحة:',
        pl: 'Wierszy na stronę:',
        it: 'Righe per pagina:',
        sk: 'Wierszy na stronę:',
      }),
      of: t({
        ru: 'из',
        en: 'of',
        kk: '/',
        de: 'von',
        fr: 'sur',
        es: 'de',
        pt: 'de',
        tr: '/',
        uk: 'з',
        zh: '/',
        ar: 'من',
        pl: 'z',
        it: 'di',
        sk: 'z',
      }),
    },
    dash: t({
      ru: '—',
      en: '—',
      kk: '—',
      de: '—',
      fr: '—',
      es: '—',
      pt: '—',
      tr: '—',
      uk: '—',
      zh: '—',
      ar: '—',
      pl: '—',
      it: '—',
      sk: '—',
    }),
    type: {
      income: t({
        ru: 'Приход',
        en: 'Income',
        kk: 'Кіріс',
        de: 'Einnahme',
        fr: 'Revenu',
        es: 'Ingreso',
        pt: 'Receita',
        tr: 'Gelir',
        uk: 'Прихід',
        zh: '收入',
        ar: 'دخل',
        pl: 'Przychód',
        it: 'Entrata',
        sk: 'Przychód',
      }),
      expense: t({
        ru: 'Расход',
        en: 'Expense',
        kk: 'Шығыс',
        de: 'Ausgabe',
        fr: 'Dépense',
        es: 'Gasto',
        pt: 'Despesa',
        tr: 'Gider',
        uk: 'Витрата',
        zh: '支出',
        ar: 'مصروف',
        pl: 'Wydatek',
        it: 'Spesa',
        sk: 'Wydatek',
      }),
      transfer: t({
        ru: 'Перевод',
        en: 'Transfer',
        kk: 'Аударым',
        de: 'Überweisung',
        fr: 'Virement',
        es: 'Transferencia',
        pt: 'Transferência',
        tr: 'Transfer',
        uk: 'Переказ',
        zh: '转账',
        ar: 'تحويل',
        pl: 'Przelew',
        it: 'Trasferimento',
        sk: 'Przelew',
      }),
    },
    columns: {
      transactionDate: t({
        ru: 'Дата',
        en: 'Date',
        kk: 'Күні',
        de: 'Datum',
        fr: 'Date',
        es: 'Fecha',
        pt: 'Data',
        tr: 'Tarih',
        uk: 'Дата',
        zh: '日期',
        ar: 'التاريخ',
        pl: 'Data',
        it: 'Data',
        sk: 'Data',
      }),
      documentNumber: t({
        ru: 'Номер документа',
        en: 'Document number',
        kk: 'Құжат нөмірі',
        de: 'Dokumentnummer',
        fr: 'Numéro de document',
        es: 'Número de documento',
        pt: 'Número do documento',
        tr: 'Belge numarası',
        uk: 'Номер документа',
        zh: '单据号',
        ar: 'رقم المستند',
        pl: 'Numer dokumentu',
        it: 'Numero documento',
        sk: 'Numer dokumentu',
      }),
      counterpartyName: t({
        ru: 'Контрагент',
        en: 'Counterparty',
        kk: 'Контрагент',
        de: 'Gegenpartei',
        fr: 'Contrepartie',
        es: 'Contraparte',
        pt: 'Contraparte',
        tr: 'Karşı taraf',
        uk: 'Контрагент',
        zh: '对方',
        ar: 'الطرف المقابل',
        pl: 'Kontrahent',
        it: 'Controparte',
        sk: 'Kontrahent',
      }),
      counterpartyBin: t({
        ru: 'БИН',
        en: 'BIN',
        kk: 'БСН',
        de: 'BIN',
        fr: 'BIN',
        es: 'BIN',
        pt: 'BIN',
        tr: 'BIN',
        uk: 'БІН',
        zh: 'BIN',
        ar: 'BIN',
        pl: 'BIN',
        it: 'BIN',
        sk: 'BIN',
      }),
      paymentPurpose: t({
        ru: 'Назначение платежа',
        en: 'Payment purpose',
        kk: 'Төлем мақсаты',
        de: 'Verwendungszweck',
        fr: 'Objet du paiement',
        es: 'Concepto de pago',
        pt: 'Finalidade do pagamento',
        tr: 'Ödeme amacı',
        uk: 'Призначення платежу',
        zh: '付款用途',
        ar: 'غرض الدفع',
        pl: 'Tytuł płatności',
        it: 'Causale del pagamento',
        sk: 'Tytuł płatności',
      }),
      debit: t({
        ru: 'Дебет',
        en: 'Debit',
        kk: 'Дебет',
        de: 'Soll',
        fr: 'Débit',
        es: 'Débito',
        pt: 'Débito',
        tr: 'Borç',
        uk: 'Дебет',
        zh: '借方',
        ar: 'المدين',
        pl: 'Debet',
        it: 'Debito',
        sk: 'Debet',
      }),
      credit: t({
        ru: 'Кредит',
        en: 'Credit',
        kk: 'Кредит',
        de: 'Haben',
        fr: 'Crédit',
        es: 'Crédito',
        pt: 'Crédito',
        tr: 'Alacak',
        uk: 'Кредит',
        zh: '贷方',
        ar: 'الدائن',
        pl: 'Kredyt',
        it: 'Credito',
        sk: 'Kredyt',
      }),
      currency: t({
        ru: 'Валюта',
        en: 'Currency',
        kk: 'Валюта',
        de: 'Währung',
        fr: 'Devise',
        es: 'Moneda',
        pt: 'Moeda',
        tr: 'Para birimi',
        uk: 'Валюта',
        zh: '货币',
        ar: 'العملة',
        pl: 'Waluta',
        it: 'Valuta',
        sk: 'Waluta',
      }),
      exchangeRate: t({
        ru: 'Курс',
        en: 'Rate',
        kk: 'Курс',
        de: 'Kurs',
        fr: 'Taux',
        es: 'Tasa',
        pt: 'Taxa',
        tr: 'Kur',
        uk: 'Курс',
        zh: '汇率',
        ar: 'سعر الصرف',
        pl: 'Kurs',
        it: 'Tasso',
        sk: 'Kurs',
      }),
      transactionType: t({
        ru: 'Тип',
        en: 'Type',
        kk: 'Түрі',
        de: 'Typ',
        fr: 'Type',
        es: 'Tipo',
        pt: 'Tipo',
        tr: 'Tür',
        uk: 'Тип',
        zh: '类型',
        ar: 'النوع',
        pl: 'Typ',
        it: 'Tipo',
        sk: 'Typ',
      }),
      category: t({
        ru: 'Категория',
        en: 'Category',
        kk: 'Санат',
        de: 'Kategorie',
        fr: 'Catégorie',
        es: 'Categoría',
        pt: 'Categoria',
        tr: 'Kategori',
        uk: 'Категорія',
        zh: '分类',
        ar: 'الفئة',
        pl: 'Kategoria',
        it: 'Categoria',
        sk: 'Kategoria',
      }),
      article: t({
        ru: 'Статья',
        en: 'Article',
        kk: 'Бап',
        de: 'Artikel',
        fr: 'Article',
        es: 'Artículo',
        pt: 'Artigo',
        tr: 'Madde',
        uk: 'Стаття',
        zh: '科目',
        ar: 'المادة',
        pl: 'Pozycja',
        it: 'Articolo',
        sk: 'Pozycja',
      }),
      amountForeign: t({
        ru: 'Сумма в валюте',
        en: 'Amount in currency',
        kk: 'Валютадағы сома',
        de: 'Betrag in Währung',
        fr: 'Montant en devise',
        es: 'Monto en moneda',
        pt: 'Valor em moeda',
        tr: 'Döviz cinsinden tutar',
        uk: 'Сума у валюті',
        zh: '外币金额',
        ar: 'المبلغ بالعملة',
        pl: 'Kwota w walucie',
        it: 'Importo in valuta',
        sk: 'Kwota w walucie',
      }),
      branch: t({
        ru: 'Филиал',
        en: 'Branch',
        kk: 'Филиал',
        de: 'Filiale',
        fr: 'Agence',
        es: 'Sucursal',
        pt: 'Filial',
        tr: 'Şube',
        uk: 'Філіал',
        zh: '分支机构',
        ar: 'الفرع',
        pl: 'Oddział',
        it: 'Filiale',
        sk: 'Oddział',
      }),
      wallet: t({
        ru: 'Кошелёк',
        en: 'Wallet',
        kk: 'Әмиян',
        de: 'Wallet',
        fr: 'Portefeuille',
        es: 'Billetera',
        pt: 'Carteira',
        tr: 'Cüzdan',
        uk: 'Гаманець',
        zh: '钱包',
        ar: 'المحفظة',
        pl: 'Portfel',
        it: 'Portafoglio',
        sk: 'Portfel',
      }),
    },
  },
} satisfies Dictionary;

export default content;
