import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'googleSheetsCallbackPage',
  content: {
    errors: {
      missingCode: t({
        ru: 'Не удалось получить код авторизации Google.',
        en: 'Failed to get Google authorization code.',
        kk: 'Google авторизация коды алынбады.',
        de: 'Google-Autorisierungscode konnte nicht abgerufen werden.',
        fr: "Impossible d'obtenir le code d'autorisation Google.",
        es: 'No se pudo obtener el código de autorización de Google.',
        pt: 'Falha ao obter o código de autorização do Google.',
        tr: 'Google yetkilendirme kodu alınamadı.',
        uk: 'Не вдалося отримати код авторизації Google.',
        zh: '无法获取 Google 授权码。',
        ar: 'فشل الحصول على رمز تفويض Google.',
        pl: 'Nie udało się uzyskać kodu autoryzacji Google.',
        it: 'Impossibile ottenere il codice di autorizzazione Google.',
        sk: 'Nie udało się uzyskać kodu autoryzacji Google.',
        ja: 'Google認証コードの取得に失敗しました。',
        ko: 'Google 인증 코드를 가져오지 못했습니다.',
        hi: 'Google प्राधिकरण कोड प्राप्त करने में विफल।',
        nl: 'Google-autorisatiecode ophalen mislukt.',
        sv: 'Det gick inte att hämta Google-auktoriseringskod.',
        vi: 'Không thể lấy mã xác thực Google.',
        id: 'Gagal mendapatkan kode otorisasi Google.',
      }),
      oauthErrorPrefix: t({
        ru: 'Google OAuth ошибка',
        en: 'Google OAuth error',
        kk: 'Google OAuth қатесі',
        de: 'Google OAuth-Fehler',
        fr: 'Erreur Google OAuth',
        es: 'Error de Google OAuth',
        pt: 'Erro do Google OAuth',
        tr: 'Google OAuth hatası',
        uk: 'Помилка Google OAuth',
        zh: 'Google OAuth 错误',
        ar: 'خطأ Google OAuth',
        pl: 'Błąd Google OAuth',
        it: 'Errore Google OAuth',
        sk: 'Błąd Google OAuth',
        ja: 'Google OAuthエラー',
        ko: 'Google OAuth 오류',
        hi: 'Google OAuth त्रुटि',
        nl: 'Google OAuth-fout',
        sv: 'Google OAuth-fel',
        vi: 'Lỗi Google OAuth',
        id: 'Kesalahan Google OAuth',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить Google Sheet',
        en: 'Failed to connect Google Sheet',
        kk: 'Google Sheet қосу мүмкін болмады',
        de: 'Google Sheet konnte nicht verbunden werden',
        fr: 'Impossible de connecter Google Sheet',
        es: 'No se pudo conectar Google Sheet',
        pt: 'Falha ao conectar Google Sheet',
        tr: 'Google Sheet bağlanamadı',
        uk: 'Не вдалося підключити Google Sheet',
        zh: '无法连接 Google Sheet',
        ar: 'فشل ربط Google Sheet',
        pl: 'Nie udało się połączyć Google Sheet',
        it: 'Impossibile connettere Google Sheet',
        sk: 'Nie udało się połączyć Google Sheet',
        ja: 'Google Sheetの接続に失敗しました',
        ko: 'Google Sheet 연결에 실패했습니다',
        hi: 'Google Sheet कनेक्ट करने में विफल',
        nl: 'Google Sheet verbinden mislukt',
        sv: 'Det gick inte att ansluta Google Sheet',
        vi: 'Không thể kết nối Google Sheet',
        id: 'Gagal menghubungkan Google Sheet',
      }),
    },
    title: t({
      ru: 'Подключение Google Sheets',
      en: 'Google Sheets connection',
      kk: 'Google Sheets қосу',
      de: 'Google Sheets-Verbindung',
      fr: 'Connexion à Google Sheets',
      es: 'Conexión de Google Sheets',
      pt: 'Conexão com Google Sheets',
      tr: 'Google Sheets bağlantısı',
      uk: 'Підключення Google Sheets',
      zh: 'Google Sheets 连接',
      ar: 'اتصال Google Sheets',
      pl: 'Połączenie z Google Sheets',
      it: 'Connessione a Google Sheets',
      sk: 'Połączenie z Google Sheets',
      ja: 'Google Sheets接続',
      ko: 'Google Sheets 연결',
      hi: 'Google Sheets कनेक्शन',
      nl: 'Google Sheets-verbinding',
      sv: 'Google Sheets-anslutning',
      vi: 'Kết nối Google Sheets',
      id: 'Koneksi Google Sheets',
    }),
    subtitle: t({
      ru: 'Завершаем подключение Google аккаунта и возвращаем вас к выбору таблицы.',
      en: 'Finishing Google account connection and returning you to spreadsheet selection.',
      kk: 'Google аккаунтын қосуды аяқтап, кесте таңдау бетіне қайтарамыз.',
      de: 'Google-Konto-Verbindung wird abgeschlossen und Sie zur Tabellenauswahl zurückgeleitet.',
      fr: 'Finalisation de la connexion du compte Google et retour à la sélection de la feuille de calcul.',
      es: 'Finalizando la conexión de la cuenta de Google y regresando a la selección de hoja de cálculo.',
      pt: 'Finalizando a conexão da conta Google e retornando à seleção de planilha.',
      tr: 'Google hesabı bağlantısı tamamlanıyor ve elektronik tablo seçimine geri dönülüyor.',
      uk: 'Завершуємо підключення Google акаунту та повертаємо вас до вибору таблиці.',
      zh: '正在完成 Google 账户连接并返回到电子表格选择。',
      ar: 'جارٍ إنهاء ربط حساب Google والعودة إلى تحديد جدول البيانات.',
      pl: 'Kończenie połączenia z kontem Google i powrót do wyboru arkusza.',
      it: "Completamento della connessione dell'account Google e ritorno alla selezione del foglio di calcolo.",
      sk: 'Kończenie połączenia z kontem Google i powrót do wyboru arkusza.',
      ja: 'Googleアカウントの接続を完了し、スプレッドシート選択に戻します。',
      ko: 'Google 계정 연결을 완료하고 스프레드시트 선택으로 돌아갑니다.',
      hi: 'Google खाता कनेक्शन समाप्त कर रहे हैं और आपको स्प्रेडशीट चयन पर वापस ला रहे हैं।',
      nl: 'Google-accountverbinding voltooien en u terugbrengen naar spreadsheetkeuze.',
      sv: 'Avslutar Google-kontoanslutning och tar dig tillbaka till kalkylbladsval.',
      vi: 'Đang hoàn tất kết nối tài khoản Google và đưa bạn trở lại chọn bảng tính.',
      id: 'Menyelesaikan koneksi akun Google dan mengembalikan Anda ke pemilihan spreadsheet.',
    }),
    success: t({
      ru: 'Google аккаунт подключен. Перенаправляем…',
      en: 'Google account connected. Redirecting…',
      kk: 'Google аккаунты қосылды. Бағытталуда…',
      de: 'Google-Konto verbunden. Weiterleitung…',
      fr: 'Compte Google connecté. Redirection…',
      es: 'Cuenta de Google conectada. Redirigiendo…',
      pt: 'Conta Google conectada. Redirecionando…',
      tr: 'Google hesabı bağlandı. Yönlendiriliyor…',
      uk: 'Google акаунт підключено. Перенаправляємо…',
      zh: 'Google 账户已连接。正在重定向…',
      ar: 'تم ربط حساب Google. جارٍ التوجيه…',
      pl: 'Konto Google połączone. Przekierowywanie…',
      it: 'Account Google connesso. Reindirizzamento…',
      sk: 'Konto Google połączone. Przekierowywanie…',
      ja: 'Googleアカウントが接続されました。リダイレクトしています…',
      ko: 'Google 계정이 연결되었습니다. 리디렉션 중…',
      hi: 'Google खाता कनेक्ट हो गया। पुनर्निर्देशित हो रहे हैं…',
      nl: 'Google-account verbonden. Doorsturen…',
      sv: 'Google-konto anslutet. Omdirigerar…',
      vi: 'Tài khoản Google đã kết nối. Đang chuyển hướng…',
      id: 'Akun Google terhubung. Mengalihkan…',
    }),
  },
} satisfies Dictionary;

export default content;
