import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'categoriesPage',
  content: {
    title: t({ ru: 'Категории', en: 'Categories', kk: 'Санаттар', de: 'Kategorien', fr: 'Catégories', es: 'Categorías', pt: 'Categorias', tr: 'Kategoriler', uk: 'Категорії', zh: '类别', ar: 'الفئات', pl: 'Kategorie', it: 'Categorie', sk: 'Kategorie'}),
    subtitle: t({
      ru: 'Следите за расходами и доходами с помощью категорий по умолчанию или добавляйте свои',
      en: 'Get a better overview of where money is spent. Use default categories or add your own.',
      kk: 'Шығындар мен кірістерді әдепкі санаттармен бақылаңыз немесе өзіңіздікін қосыңыз',
      de: 'Behalten Sie den Überblick über Ausgaben und Einnahmen mit Standardkategorien oder fügen Sie eigene hinzu.',
      fr: 'Suivez vos dépenses et revenus avec les catégories par défaut ou ajoutez les vôtres.',
      es: 'Obtenga una mejor visión de dónde se gasta el dinero. Use categorías predeterminadas o agregue las suyas.',
      pt: 'Obtenha uma melhor visão geral de onde o dinheiro é gasto. Use categorias padrão ou adicione as suas.',
      tr: 'Paranın nereye harcandığına daha iyi genel bir bakış elde edin. Varsayılan kategorileri kullanın veya kendinizinkini ekleyin.',
      uk: 'Стежте за витратами та доходами за допомогою стандартних категорій або додайте власні.',
      zh: '更好地了解资金的去向。使用默认类别或添加您自己的类别。',
      ar: 'احصل على نظرة عامة أفضل على أين يُنفق المال. استخدم الفئات الافتراضية أو أضف فئاتك الخاصة.',
      pl: 'Śledź wydatki i przychody za pomocą domyślnych kategorii lub dodaj własne.',
      it: 'Ottieni una migliore panoramica di dove vengono spesi i soldi. Usa le categorie predefinite o aggiungi le tue.',
      sk: 'Śledź wydatki i przychody za pomocą domyślnych kategorii lub dodaj własne.',
    }),
    add: t({ ru: 'Добавить', en: 'Add', kk: 'Қосу', de: 'Hinzufügen', fr: 'Ajouter', es: 'Agregar', pt: 'Adicionar', tr: 'Ekle', uk: 'Додати', zh: '添加', ar: 'إضافة', pl: 'Dodaj', it: 'Aggiungi', sk: 'Dodaj'}),
    enabled: t({ ru: 'Активно', en: 'Enabled', kk: 'Белсенді', de: 'Aktiv', fr: 'Activé', es: 'Habilitado', pt: 'Habilitado', tr: 'Etkin', uk: 'Активно', zh: '已启用', ar: 'مفعّل', pl: 'Włączone', it: 'Abilitato', sk: 'Włączone'}),
    more: t({ ru: 'Еще', en: 'More', kk: 'Көбірек', de: 'Mehr', fr: 'Plus', es: 'Más', pt: 'Mais', tr: 'Daha fazla', uk: 'Ще', zh: '更多', ar: 'المزيد', pl: 'Więcej', it: 'Altro', sk: 'Więcej'}),
    searchPlaceholder: t({ ru: 'Найти категорию', en: 'Find category', kk: 'Санатты табу', de: 'Kategorie suchen', fr: 'Trouver une catégorie', es: 'Buscar categoría', pt: 'Encontrar categoria', tr: 'Kategori bul', uk: 'Знайти категорію', zh: '查找类别', ar: 'البحث عن فئة', pl: 'Znajdź kategorię', it: 'Trova categoria', sk: 'Znajdź kategorię'}),
    columns: {
      name: t({ ru: 'Название', en: 'Name', kk: 'Атауы', de: 'Name', fr: 'Nom', es: 'Nombre', pt: 'Nome', tr: 'Ad', uk: 'Назва', zh: '名称', ar: 'الاسم', pl: 'Nazwa', it: 'Nome', sk: 'Nazwa'}),
    },
    noData: t({ ru: 'Нет категорий', en: 'No categories', kk: 'Санаттар жоқ', de: 'Keine Kategorien', fr: 'Aucune catégorie', es: 'Sin categorías', pt: 'Sem categorias', tr: 'Kategori yok', uk: 'Немає категорій', zh: '暂无类别', ar: 'لا توجد فئات', pl: 'Brak kategorii', it: 'Nessuna categoria', sk: 'Brak kategorii'}),
    sourceBadges: {
      system: t({ ru: 'System', en: 'System', kk: 'System', de: 'System', fr: 'Système', es: 'Sistema', pt: 'Sistema', tr: 'Sistem', uk: 'System', zh: '系统', ar: 'النظام', pl: 'System', it: 'Sistema', sk: 'System'}),
      parsing: t({ ru: 'Данные из парсинга', en: 'Parsing data', kk: 'Parsing data', de: 'Parsing-Daten', fr: 'Données analysées', es: 'Datos de análisis', pt: 'Dados de análise', tr: 'Ayrıştırma verisi', uk: 'Дані парсингу', zh: '解析数据', ar: 'بيانات التحليل', pl: 'Dane z parsowania', it: 'Dati di parsing', sk: 'Dane z parsowania'}),
      user: t({ ru: 'Пользовательская', en: 'Custom', kk: 'Custom', de: 'Benutzerdefiniert', fr: 'Personnalisé', es: 'Personalizado', pt: 'Personalizado', tr: 'Özel', uk: 'Користувацька', zh: '自定义', ar: 'مخصص', pl: 'Niestandardowe', it: 'Personalizzato', sk: 'Niestandardowe'}),
    },
    loading: t({ ru: 'Загрузка...', en: 'Loading...', kk: 'Жүктелуде...', de: 'Laden...', fr: 'Chargement...', es: 'Cargando...', pt: 'Carregando...', tr: 'Yükleniyor...', uk: 'Завантаження...', zh: '加载中...', ar: 'جارٍ التحميل...', pl: 'Ładowanie...', it: 'Caricamento...', sk: 'Ładowanie...'}),
    type: {
      income: t({ ru: 'Доход', en: 'Income', kk: 'Кіріс', de: 'Einnahmen', fr: 'Revenu', es: 'Ingreso', pt: 'Receita', tr: 'Gelir', uk: 'Дохід', zh: '收入', ar: 'دخل', pl: 'Przychód', it: 'Entrata', sk: 'Przychód'}),
      expense: t({ ru: 'Расход', en: 'Expense', kk: 'Шығыс', de: 'Ausgabe', fr: 'Dépense', es: 'Gasto', pt: 'Despesa', tr: 'Gider', uk: 'Витрата', zh: '支出', ar: 'مصروف', pl: 'Wydatek', it: 'Uscita', sk: 'Wydatek'}),
      label: t({ ru: 'Тип', en: 'Type', kk: 'Түрі', de: 'Typ', fr: 'Type', es: 'Tipo', pt: 'Tipo', tr: 'Tür', uk: 'Тип', zh: '类型', ar: 'النوع', pl: 'Typ', it: 'Tipo', sk: 'Typ'}),
    },
    actions: {
      edit: t({ ru: 'Редактировать', en: 'Edit', kk: 'Өзгерту', de: 'Bearbeiten', fr: 'Modifier', es: 'Editar', pt: 'Editar', tr: 'Düzenle', uk: 'Редагувати', zh: '编辑', ar: 'تعديل', pl: 'Edytuj', it: 'Modifica', sk: 'Edytuj'}),
      delete: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina', sk: 'Usuń'}),
    },
    toasts: {
      loadFailed: t({
        ru: 'Не удалось загрузить категории',
        en: 'Failed to load categories',
        kk: 'Санаттарды жүктеу мүмкін болмады',
        de: 'Kategorien konnten nicht geladen werden',
        fr: 'Impossible de charger les catégories',
        es: 'No se pudieron cargar las categorías',
        pt: 'Falha ao carregar categorias',
        tr: 'Kategoriler yüklenemedi',
        uk: 'Не вдалося завантажити категорії',
        zh: '加载类别失败',
        ar: 'فشل تحميل الفئات',
        pl: 'Nie udało się załadować kategorii',
        it: 'Impossibile caricare le categorie',
        sk: 'Nie udało się załadować kategorii',
      }),
      updated: t({ ru: 'Категория обновлена', en: 'Category updated', kk: 'Санат жаңартылды', de: 'Kategorie aktualisiert', fr: 'Catégorie mise à jour', es: 'Categoría actualizada', pt: 'Categoria atualizada', tr: 'Kategori güncellendi', uk: 'Категорію оновлено', zh: '类别已更新', ar: 'تم تحديث الفئة', pl: 'Kategoria zaktualizowana', it: 'Categoria aggiornata', sk: 'Kategoria zaktualizowana'}),
      created: t({ ru: 'Категория создана', en: 'Category created', kk: 'Санат құрылды', de: 'Kategorie erstellt', fr: 'Catégorie créée', es: 'Categoría creada', pt: 'Categoria criada', tr: 'Kategori oluşturuldu', uk: 'Категорію створено', zh: '类别已创建', ar: 'تم إنشاء الفئة', pl: 'Kategoria utworzona', it: 'Categoria creata', sk: 'Kategoria utworzona'}),
      saveFailed: t({
        ru: 'Не удалось сохранить категорию',
        en: 'Failed to save category',
        kk: 'Санатты сақтау мүмкін болмады',
        de: 'Kategorie konnte nicht gespeichert werden',
        fr: 'Impossible d\'enregistrer la catégorie',
        es: 'No se pudo guardar la categoría',
        pt: 'Falha ao salvar a categoria',
        tr: 'Kategori kaydedilemedi',
        uk: 'Не вдалося зберегти категорію',
        zh: '保存类别失败',
        ar: 'فشل حفظ الفئة',
        pl: 'Nie udało się zapisać kategorii',
        it: 'Impossibile salvare la categoria',
        sk: 'Nie udało się zapisać kategorii',
      }),
      deleted: t({ ru: 'Категория удалена', en: 'Category deleted', kk: 'Санат жойылды', de: 'Kategorie gelöscht', fr: 'Catégorie supprimée', es: 'Categoría eliminada', pt: 'Categoria excluída', tr: 'Kategori silindi', uk: 'Категорію видалено', zh: '类别已删除', ar: 'تم حذف الفئة', pl: 'Kategoria usunięta', it: 'Categoria eliminata', sk: 'Kategoria usunięta'}),
      deleteFailed: t({
        ru: 'Не удалось удалить категорию',
        en: 'Failed to delete category',
        kk: 'Санатты жою мүмкін болмады',
        de: 'Kategorie konnte nicht gelöscht werden',
        fr: 'Impossible de supprimer la catégorie',
        es: 'No se pudo eliminar la categoría',
        pt: 'Falha ao excluir a categoria',
        tr: 'Kategori silinemedi',
        uk: 'Не вдалося видалити категорію',
        zh: '删除类别失败',
        ar: 'فشل حذف الفئة',
        pl: 'Nie udało się usunąć kategorii',
        it: 'Impossibile eliminare la categoria',
        sk: 'Nie udało się usunąć kategorii',
      }),
      iconUploaded: t({ ru: 'Иконка загружена', en: 'Icon uploaded', kk: 'Иконка жүктелді', de: 'Symbol hochgeladen', fr: 'Icône téléchargée', es: 'Icono subido', pt: 'Ícone enviado', tr: 'Simge yüklendi', uk: 'Іконку завантажено', zh: '图标已上传', ar: 'تم رفع الأيقونة', pl: 'Ikona przesłana', it: 'Icona caricata', sk: 'Ikona przesłana'}),
      iconUploadFailed: t({
        ru: 'Не удалось загрузить иконку. Попробуйте ещё раз.',
        en: 'Failed to upload icon. Please try again.',
        kk: 'Иконканы жүктеу мүмкін болмады. Қайтадан көріңіз.',
        de: 'Symbol konnte nicht hochgeladen werden. Bitte versuchen Sie es erneut.',
        fr: 'Impossible de télécharger l\'icône. Veuillez réessayer.',
        es: 'No se pudo subir el icono. Por favor, inténtelo de nuevo.',
        pt: 'Falha ao enviar o ícone. Por favor, tente novamente.',
        tr: 'Simge yüklenemedi. Lütfen tekrar deneyin.',
        uk: 'Не вдалося завантажити іконку. Спробуйте ще раз.',
        zh: '上传图标失败。请重试。',
        ar: 'فشل رفع الأيقونة. يرجى المحاولة مرة أخرى.',
        pl: 'Nie udało się przesłać ikony. Spróbuj ponownie.',
        it: 'Impossibile caricare l\'icona. Riprova.',
        sk: 'Nie udało się przesłać ikony. Spróbuj ponownie.',
      }),
    },
    confirmDelete: t({
      ru: 'Вы уверены, что хотите удалить эту категорию?',
      en: 'Are you sure you want to delete this category?',
      kk: 'Осы санатты жойғыңыз келетініне сенімдісіз бе?',
      de: 'Sind Sie sicher, dass Sie diese Kategorie löschen möchten?',
      fr: 'Êtes-vous sûr de vouloir supprimer cette catégorie ?',
      es: '¿Está seguro de que desea eliminar esta categoría?',
      pt: 'Tem certeza de que deseja excluir esta categoria?',
      tr: 'Bu kategoriyi silmek istediğinizden emin misiniz?',
      uk: 'Ви впевнені, що хочете видалити цю категорію?',
      zh: '您确定要删除此类别吗？',
      ar: 'هل أنت متأكد أنك تريد حذف هذه الفئة؟',
      pl: 'Czy na pewno chcesz usunąć tę kategorię?',
      it: 'Sei sicuro di voler eliminare questa categoria?',
      sk: 'Czy na pewno chcesz usunąć tę kategorię?',
    }),
    dialog: {
      editTitle: t({ ru: 'Редактировать категорию', en: 'Edit category', kk: 'Санатты өзгерту', de: 'Kategorie bearbeiten', fr: 'Modifier la catégorie', es: 'Editar categoría', pt: 'Editar categoria', tr: 'Kategoriyi düzenle', uk: 'Редагувати категорію', zh: '编辑类别', ar: 'تعديل الفئة', pl: 'Edytuj kategorię', it: 'Modifica categoria', sk: 'Edytuj kategorię'}),
      createTitle: t({ ru: 'Создать категорию', en: 'Create category', kk: 'Санат құру', de: 'Kategorie erstellen', fr: 'Créer une catégorie', es: 'Crear categoría', pt: 'Criar categoria', tr: 'Kategori oluştur', uk: 'Створити категорію', zh: '创建类别', ar: 'إنشاء فئة', pl: 'Utwórz kategorię', it: 'Crea categoria', sk: 'Utwórz kategorię'}),
      nameLabel: t({ ru: 'Название', en: 'Name', kk: 'Атауы', de: 'Name', fr: 'Nom', es: 'Nombre', pt: 'Nome', tr: 'Ad', uk: 'Назва', zh: '名称', ar: 'الاسم', pl: 'Nazwa', it: 'Nome', sk: 'Nazwa'}),
      chooseIcon: t({ ru: 'Выберите иконку', en: 'Choose an icon', kk: 'Иконканы таңдаңыз', de: 'Symbol auswählen', fr: 'Choisir une icône', es: 'Elegir un icono', pt: 'Escolha um ícone', tr: 'Simge seçin', uk: 'Оберіть іконку', zh: '选择图标', ar: 'اختر أيقونة', pl: 'Wybierz ikonę', it: 'Scegli un\'icona', sk: 'Wybierz ikonę'}),
      uploadedIcon: t({ ru: 'Загруженная иконка:', en: 'Uploaded icon:', kk: 'Жүктелген иконка:', de: 'Hochgeladenes Symbol:', fr: 'Icône téléchargée :', es: 'Icono subido:', pt: 'Ícone enviado:', tr: 'Yüklenen simge:', uk: 'Завантажена іконка:', zh: '已上传图标：', ar: 'الأيقونة المرفوعة:', pl: 'Przesłana ikona:', it: 'Icona caricata:', sk: 'Przesłana ikona:'}),
      uploadIcon: t({ ru: 'Загрузить иконку', en: 'Upload icon', kk: 'Иконканы жүктеу', de: 'Symbol hochladen', fr: 'Télécharger une icône', es: 'Subir icono', pt: 'Enviar ícone', tr: 'Simge yükle', uk: 'Завантажити іконку', zh: '上传图标', ar: 'رفع أيقونة', pl: 'Prześlij ikonę', it: 'Carica icona', sk: 'Prześlij ikonę'}),
      chooseColor: t({ ru: 'Выберите цвет', en: 'Choose a color', kk: 'Түсті таңдаңыз', de: 'Farbe auswählen', fr: 'Choisir une couleur', es: 'Elegir un color', pt: 'Escolha uma cor', tr: 'Renk seçin', uk: 'Оберіть колір', zh: '选择颜色', ar: 'اختر لوناً', pl: 'Wybierz kolor', it: 'Scegli un colore', sk: 'Wybierz kolor'}),
      preview: t({ ru: 'Предпросмотр:', en: 'Preview:', kk: 'Алдын ала қарау:', de: 'Vorschau:', fr: 'Aperçu :', es: 'Vista previa:', pt: 'Pré-visualização:', tr: 'Önizleme:', uk: 'Попередній перегляд:', zh: '预览：', ar: 'معاينة:', pl: 'Podgląd:', it: 'Anteprima:', sk: 'Podgląd:'}),
      placeholderName: t({ ru: 'Название категории', en: 'Category name', kk: 'Санат атауы', de: 'Kategoriename', fr: 'Nom de la catégorie', es: 'Nombre de la categoría', pt: 'Nome da categoria', tr: 'Kategori adı', uk: 'Назва категорії', zh: '类别名称', ar: 'اسم الفئة', pl: 'Nazwa kategorii', it: 'Nome categoria', sk: 'Nazwa kategorii'}),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
      save: t({ ru: 'Сохранить', en: 'Save', kk: 'Сақтау', de: 'Speichern', fr: 'Enregistrer', es: 'Guardar', pt: 'Salvar', tr: 'Kaydet', uk: 'Зберегти', zh: '保存', ar: 'حفظ', pl: 'Zapisz', it: 'Salva', sk: 'Zapisz'}),
      uploading: t({ ru: 'Загрузка...', en: 'Uploading...', kk: 'Жүктелуде...', de: 'Hochladen...', fr: 'Téléchargement...', es: 'Subiendo...', pt: 'Enviando...', tr: 'Yükleniyor...', uk: 'Завантаження...', zh: '上传中...', ar: 'جارٍ الرفع...', pl: 'Przesyłanie...', it: 'Caricamento...', sk: 'Przesyłanie...'}),
    },
  },
} satisfies Dictionary;

export default content;
