import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsDrawer',
  content: {
    title: t({
      ru: 'Детали транзакции',
      en: 'Transaction Details',
      kk: 'Транзакция мәліметтері',
      de: 'Transaktionsdetails',
      fr: 'Détails de la transaction',
      es: 'Detalles de la transacción',
      pt: 'Detalhes da transação',
      tr: 'İşlem Detayları',
      uk: 'Деталі транзакції',
      zh: '交易详情',
      ar: 'تفاصيل المعاملة',
      pl: 'Szczegóły transakcji',
      it: 'Dettagli della transazione',
      sk: 'Szczegóły transakcji',
    }),
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Data',
    }),
    documentNumber: t({
      ru: 'Номер документа',
      en: 'Document Number',
      kk: 'Құжат нөмірі',
      de: 'Dokumentnummer',
      fr: 'Numéro de document',
      es: 'Número de documento',
      pt: 'Número do documento',
      tr: 'Belge Numarası',
      uk: 'Номер документа',
      zh: '文件编号',
      ar: 'رقم الوثيقة',
      pl: 'Numer dokumentu',
      it: 'Numero documento',
      sk: 'Numer dokumentu',
    }),
    counterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı Taraf',
      uk: 'Контрагент',
      zh: '交易对手',
      ar: 'الطرف المقابل',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Kontrahent',
    }),
    bin: t({
      ru: 'БИН',
      en: 'BIN',
      kk: 'БСН',
      de: 'BIN',
      fr: 'BIN',
      es: 'BIN',
      pt: 'BIN',
      tr: 'BIN',
      uk: 'БІН',
      zh: 'BIN',
      ar: 'رقم BIN',
      pl: 'BIN',
      it: 'BIN',
      sk: 'BIN',
    }),
    purpose: t({
      ru: 'Назначение платежа',
      en: 'Payment Purpose',
      kk: 'Төлем мақсаты',
      de: 'Zahlungszweck',
      fr: 'Objet du paiement',
      es: 'Propósito del pago',
      pt: 'Finalidade do pagamento',
      tr: 'Ödeme Amacı',
      uk: 'Призначення платежу',
      zh: '付款用途',
      ar: 'غرض الدفع',
      pl: 'Cel płatności',
      it: 'Scopo del pagamento',
      sk: 'Cel płatności',
    }),
    debit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      ar: 'مدين',
      pl: 'Debet',
      it: 'Addebito',
      sk: 'Debet',
    }),
    credit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      ar: 'دائن',
      pl: 'Kredyt',
      it: 'Credito',
      sk: 'Kredyt',
    }),
    additionalDetails: t({
      ru: 'Дополнительные данные',
      en: 'Additional Details',
      kk: 'Қосымша мәліметтер',
      de: 'Zusätzliche Details',
      fr: 'Détails supplémentaires',
      es: 'Detalles adicionales',
      pt: 'Detalhes adicionais',
      tr: 'Ek Detaylar',
      uk: 'Додаткові дані',
      zh: '附加详情',
      ar: 'تفاصيل إضافية',
      pl: 'Dodatkowe szczegóły',
      it: 'Dettagli aggiuntivi',
      sk: 'Dodatkowe szczegóły',
    }),
    currency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      de: 'Währung',
      fr: 'Devise',
      es: 'Moneda',
      pt: 'Moeda',
      tr: 'Para Birimi',
      uk: 'Валюта',
      zh: '货币',
      ar: 'العملة',
      pl: 'Waluta',
      it: 'Valuta',
      sk: 'Waluta',
    }),
    exchangeRate: t({
      ru: 'Курс обмена',
      en: 'Exchange Rate',
      kk: 'Айырбас курсы',
      de: 'Wechselkurs',
      fr: 'Taux de change',
      es: 'Tipo de cambio',
      pt: 'Taxa de câmbio',
      tr: 'Döviz Kuru',
      uk: 'Курс обміну',
      zh: '汇率',
      ar: 'سعر الصرف',
      pl: 'Kurs wymiany',
      it: 'Tasso di cambio',
      sk: 'Kurs wymiany',
    }),
    article: t({
      ru: 'Статья',
      en: 'Article',
      kk: 'Бап',
      de: 'Artikel',
      fr: 'Article',
      es: 'Artículo',
      pt: 'Artigo',
      tr: 'Madde',
      uk: 'Стаття',
      zh: '条目',
      ar: 'بند',
      pl: 'Artykuł',
      it: 'Articolo',
      sk: 'Artykuł',
    }),
    branch: t({
      ru: 'Филиал',
      en: 'Branch',
      kk: 'Филиал',
      de: 'Filiale',
      fr: 'Succursale',
      es: 'Sucursal',
      pt: 'Filial',
      tr: 'Şube',
      uk: 'Філіал',
      zh: '分支机构',
      ar: 'الفرع',
      pl: 'Oddział',
      it: 'Filiale',
      sk: 'Oddział',
    }),
    wallet: t({
      ru: 'Кошелёк',
      en: 'Wallet',
      kk: 'Әмиян',
      de: 'Geldbörse',
      fr: 'Portefeuille',
      es: 'Cartera',
      pt: 'Carteira',
      tr: 'Cüzdan',
      uk: 'Гаманець',
      zh: '钱包',
      ar: 'المحفظة',
      pl: 'Portfel',
      it: 'Portafoglio',
      sk: 'Portfel',
    }),
    parsingMetadata: t({
      ru: 'Метаданные распознавания',
      en: 'Parsing Metadata',
      kk: 'Тану метадеректері',
      de: 'Parsing-Metadaten',
      fr: 'Métadonnées d\'analyse',
      es: 'Metadatos de análisis',
      pt: 'Metadados de análise',
      tr: 'Ayrıştırma Meta Verileri',
      uk: 'Метадані розпізнавання',
      zh: '解析元数据',
      ar: 'بيانات التحليل الوصفية',
      pl: 'Metadane parsowania',
      it: 'Metadati di analisi',
      sk: 'Metadane parsowania',
    }),
    confidence: t({
      ru: 'Уверенность',
      en: 'Confidence',
      kk: 'Сенімділік',
      de: 'Konfidenz',
      fr: 'Confiance',
      es: 'Confianza',
      pt: 'Confiança',
      tr: 'Güven',
      uk: 'Впевненість',
      zh: '置信度',
      ar: 'الثقة',
      pl: 'Pewność',
      it: 'Affidabilità',
      sk: 'Pewność',
    }),
    rawExtract: t({
      ru: 'Исходные данные',
      en: 'Raw Extract',
      kk: 'Бастапқы деректер',
      de: 'Rohdaten',
      fr: 'Données brutes',
      es: 'Datos sin procesar',
      pt: 'Dados brutos',
      tr: 'Ham Veri',
      uk: 'Вихідні дані',
      zh: '原始提取',
      ar: 'البيانات الخام',
      pl: 'Surowe dane',
      it: 'Dati grezzi',
      sk: 'Surowe dane',
    }),
    currentCategory: t({
      ru: 'Текущая категория',
      en: 'Current Category',
      kk: 'Ағымдағы санат',
      de: 'Aktuelle Kategorie',
      fr: 'Catégorie actuelle',
      es: 'Categoría actual',
      pt: 'Categoria atual',
      tr: 'Mevcut Kategori',
      uk: 'Поточна категорія',
      zh: '当前分类',
      ar: 'الفئة الحالية',
      pl: 'Bieżąca kategoria',
      it: 'Categoria attuale',
      sk: 'Bieżąca kategoria',
    }),
    noCategory: t({
      ru: 'Категория не назначена',
      en: 'No category assigned',
      kk: 'Санат тағайындалмаған',
      de: 'Keine Kategorie zugewiesen',
      fr: 'Aucune catégorie attribuée',
      es: 'Sin categoría asignada',
      pt: 'Sem categoria atribuída',
      tr: 'Kategori atanmadı',
      uk: 'Категорія не призначена',
      zh: '未分配分类',
      ar: 'لم يتم تعيين فئة',
      pl: 'Brak przypisanej kategorii',
      it: 'Nessuna categoria assegnata',
      sk: 'Brak przypisanej kategorii',
    }),
    actions: t({
      ru: 'Действия',
      en: 'Actions',
      kk: 'Әрекеттер',
      de: 'Aktionen',
      fr: 'Actions',
      es: 'Acciones',
      pt: 'Ações',
      tr: 'İşlemler',
      uk: 'Дії',
      zh: '操作',
      ar: 'الإجراءات',
      pl: 'Akcje',
      it: 'Azioni',
      sk: 'Akcje',
    }),
    setCategory: t({
      ru: 'Установить категорию',
      en: 'Set Category',
      kk: 'Санат белгілеу',
      de: 'Kategorie festlegen',
      fr: 'Définir la catégorie',
      es: 'Establecer categoría',
      pt: 'Definir categoria',
      tr: 'Kategori Belirle',
      uk: 'Встановити категорію',
      zh: '设置分类',
      ar: 'تعيين الفئة',
      pl: 'Ustaw kategorię',
      it: 'Imposta categoria',
      sk: 'Ustaw kategorię',
    }),
    selectCategory: t({
      ru: 'Выберите категорию...',
      en: 'Select category...',
      kk: 'Санат таңдаңыз...',
      de: 'Kategorie auswählen...',
      fr: 'Sélectionner une catégorie...',
      es: 'Seleccionar categoría...',
      pt: 'Selecionar categoria...',
      tr: 'Kategori seçin...',
      uk: 'Оберіть категорію...',
      zh: '选择分类...',
      ar: 'اختر الفئة...',
      pl: 'Wybierz kategorię...',
      it: 'Seleziona categoria...',
      sk: 'Wybierz kategorię...',
    }),
    updating: t({
      ru: 'Обновление...',
      en: 'Updating...',
      kk: 'Жаңартылуда...',
      de: 'Wird aktualisiert...',
      fr: 'Mise à jour...',
      es: 'Actualizando...',
      pt: 'Atualizando...',
      tr: 'Güncelleniyor...',
      uk: 'Оновлення...',
      zh: '更新中...',
      ar: 'جارٍ التحديث...',
      pl: 'Aktualizowanie...',
      it: 'Aggiornamento...',
      sk: 'Aktualizowanie...',
    }),
    apply: t({
      ru: 'Применить',
      en: 'Apply',
      kk: 'Қолдану',
      de: 'Anwenden',
      fr: 'Appliquer',
      es: 'Aplicar',
      pt: 'Aplicar',
      tr: 'Uygula',
      uk: 'Застосувати',
      zh: '应用',
      ar: 'تطبيق',
      pl: 'Zastosuj',
      it: 'Applica',
      sk: 'Zastosuj',
    }),
    markIgnored: t({
      ru: 'Отметить как игнорируемое',
      en: 'Mark as Ignored',
      kk: 'Елемеу ретінде белгілеу',
      de: 'Als ignoriert markieren',
      fr: 'Marquer comme ignoré',
      es: 'Marcar como ignorado',
      pt: 'Marcar como ignorado',
      tr: 'Yoksayıldı olarak işaretle',
      uk: 'Позначити як ігнороване',
      zh: '标记为已忽略',
      ar: 'وضع علامة متجاهَل',
      pl: 'Oznacz jako zignorowane',
      it: 'Segna come ignorato',
      sk: 'Oznacz jako zignorowane',
    }),
  },
} satisfies Dictionary;

export default content;
