import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'exportModal',
  content: {
    title: t({
      ru: 'Экспорт транзакций',
      en: 'Export transactions',
      kk: 'Транзакцияларды экспорттау',
      de: 'Transaktionen exportieren',
      fr: 'Exporter les transactions',
      es: 'Exportar transacciones',
      pt: 'Exportar transações',
      tr: 'İşlemleri dışa aktar',
      uk: 'Експорт транзакцій',
      zh: '导出交易',
      ar: 'تصدير المعاملات',
      pl: 'Eksportuj transakcje',
      it: 'Esporta transazioni',
    }),
    exportButton: t({
      ru: 'Экспортировать',
      en: 'Export',
      kk: 'Экспорттау',
      de: 'Exportieren',
      fr: 'Exporter',
      es: 'Exportar',
      pt: 'Exportar',
      tr: 'Dışa Aktar',
      uk: 'Експортувати',
      zh: '导出',
      ar: 'تصدير',
      pl: 'Eksportuj',
      it: 'Esporta',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Бас тарту',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
    }),
    description: t({
      ru: 'Выберите формат экспорта для текущей выборки транзакций:',
      en: 'Choose an export format for the current transaction selection:',
      kk: 'Ағымдағы транзакциялар таңдауы үшін экспорт форматын таңдаңыз:',
      de: 'Wählen Sie ein Exportformat für die aktuelle Transaktionsauswahl:',
      fr: 'Choisissez un format d\'export pour la sélection de transactions actuelle :',
      es: 'Elija un formato de exportación para la selección de transacciones actual:',
      pt: 'Escolha um formato de exportação para a seleção de transações atual:',
      tr: 'Mevcut işlem seçimi için bir dışa aktarma formatı seçin:',
      uk: 'Виберіть формат експорту для поточного вибору транзакцій:',
      zh: '为当前选择的交易选择导出格式：',
      ar: 'اختر تنسيق التصدير لتحديد المعاملات الحالي:',
      pl: 'Wybierz format eksportu dla bieżącego wyboru transakcji:',
      it: 'Scegli un formato di esportazione per la selezione di transazioni corrente:',
    }),
    exportToTable: t({
      ru: 'Экспорт в таблицу',
      en: 'Export to table',
      kk: 'Кестеге экспорттау',
      de: 'In Tabelle exportieren',
      fr: 'Exporter en tableau',
      es: 'Exportar a tabla',
      pt: 'Exportar para tabela',
      tr: 'Tabloya aktar',
      uk: 'Експорт у таблицю',
      zh: '导出到表格',
      ar: 'التصدير إلى جدول',
      pl: 'Eksportuj do tabeli',
      it: 'Esporta in tabella',
    }),
    exportToTableDescription: t({
      ru: 'Создать новую таблицу или добавить в существующую',
      en: 'Create a new table or add to an existing one',
      kk: 'Жаңа кесте құру немесе бар кестеге қосу',
      de: 'Eine neue Tabelle erstellen oder zu einer vorhandenen hinzufügen',
      fr: 'Créer un nouveau tableau ou ajouter à un tableau existant',
      es: 'Crear una nueva tabla o agregar a una existente',
      pt: 'Criar uma nova tabela ou adicionar a uma existente',
      tr: 'Yeni bir tablo oluşturun veya mevcut birine ekleyin',
      uk: 'Створити нову таблицю або додати до існуючої',
      zh: '创建新表格或添加到现有表格',
      ar: 'إنشاء جدول جديد أو إضافة إلى جدول موجود',
      pl: 'Utwórz nową tabelę lub dodaj do istniejącej',
      it: 'Crea una nuova tabella o aggiungila a una esistente',
    }),
    downloadFile: t({
      ru: 'Скачать файл в формате .xlsx или .csv',
      en: 'Download file in .xlsx or .csv format',
      kk: '.xlsx немесе .csv форматында файлды жүктеп алу',
      de: 'Datei im .xlsx- oder .csv-Format herunterladen',
      fr: 'Télécharger le fichier au format .xlsx ou .csv',
      es: 'Descargar archivo en formato .xlsx o .csv',
      pt: 'Baixar arquivo no formato .xlsx ou .csv',
      tr: '.xlsx veya .csv formatında dosya indir',
      uk: 'Завантажити файл у форматі .xlsx або .csv',
      zh: '下载 .xlsx 或 .csv 格式的文件',
      ar: 'تنزيل الملف بتنسيق .xlsx أو .csv',
      pl: 'Pobierz plik w formacie .xlsx lub .csv',
      it: 'Scarica il file in formato .xlsx o .csv',
    }),
  },
} satisfies Dictionary;

export default content;
