import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsSummaryBar',
  content: {
    uploadedAt: t({
      ru: 'Загружено',
      en: 'Uploaded',
      kk: 'Жүктелген',
      de: 'Hochgeladen',
      fr: 'Téléchargé',
      es: 'Subido',
      pt: 'Enviado',
      tr: 'Yüklendi',
      uk: 'Завантажено',
      zh: '已上传',
      ar: 'تم الرفع',
      pl: 'Przesłano',
      it: 'Caricato',
      sk: 'Przesłano',
    }),
    parsed: t({
      ru: 'Распознано',
      en: 'Parsed',
      kk: 'Танылды',
      de: 'Verarbeitet',
      fr: 'Analysé',
      es: 'Procesado',
      pt: 'Processado',
      tr: 'İşlendi',
      uk: 'Розпізнано',
      zh: '已解析',
      ar: 'تم التحليل',
      pl: 'Przetworzone',
      it: 'Analizzato',
      sk: 'Przetworzone',
    }),
    warnings: t({
      ru: 'Предупреждения',
      en: 'Warnings',
      kk: 'Ескертулер',
      de: 'Warnungen',
      fr: 'Avertissements',
      es: 'Advertencias',
      pt: 'Avisos',
      tr: 'Uyarılar',
      uk: 'Попередження',
      zh: '警告',
      ar: 'تحذيرات',
      pl: 'Ostrzeżenia',
      it: 'Avvisi',
      sk: 'Ostrzeżenia',
    }),
    errors: t({
      ru: 'Ошибки',
      en: 'Errors',
      kk: 'Қателер',
      de: 'Fehler',
      fr: 'Erreurs',
      es: 'Errores',
      pt: 'Erros',
      tr: 'Hatalar',
      uk: 'Помилки',
      zh: '错误',
      ar: 'أخطاء',
      pl: 'Błędy',
      it: 'Errori',
      sk: 'Błędy',
    }),
    uncategorized: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Unkategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categorizar',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      ar: 'غير مصنف',
      pl: 'Bez kategorii',
      it: 'Non categorizzato',
      sk: 'Bez kategorii',
    }),
    debitTotal: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      ar: 'مدين',
      pl: 'Debet',
      it: 'Addebito',
      sk: 'Debet',
    }),
    creditTotal: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      ar: 'دائن',
      pl: 'Kredyt',
      it: 'Credito',
      sk: 'Kredyt',
    }),
    fixIssues: t({
      ru: 'Исправить проблемы',
      en: 'Fix Issues',
      kk: 'Мәселелерді шешу',
      de: 'Probleme beheben',
      fr: 'Corriger les problèmes',
      es: 'Corregir problemas',
      pt: 'Corrigir problemas',
      tr: 'Sorunları Düzelt',
      uk: 'Виправити проблеми',
      zh: '修复问题',
      ar: 'إصلاح المشكلات',
      pl: 'Napraw problemy',
      it: 'Risolvi i problemi',
      sk: 'Napraw problemy',
    }),
    showErrors: t({
      ru: 'Показать ошибки',
      en: 'Show Errors',
      kk: 'Қателерді көрсету',
      de: 'Fehler anzeigen',
      fr: 'Afficher les erreurs',
      es: 'Mostrar errores',
      pt: 'Mostrar erros',
      tr: 'Hataları Göster',
      uk: 'Показати помилки',
      zh: '显示错误',
      ar: 'عرض الأخطاء',
      pl: 'Pokaż błędy',
      it: 'Mostra errori',
      sk: 'Pokaż błędy',
    }),
    export: t({
      ru: 'Экспорт',
      en: 'Export',
      kk: 'Экспорт',
      de: 'Exportieren',
      fr: 'Exporter',
      es: 'Exportar',
      pt: 'Exportar',
      tr: 'Dışa Aktar',
      uk: 'Експорт',
      zh: '导出',
      ar: 'تصدير',
      pl: 'Eksportuj',
      it: 'Esporta',
      sk: 'Eksportuj',
    }),
    download: t({
      ru: 'Скачать',
      en: 'Download',
      kk: 'Жүктеу',
      de: 'Herunterladen',
      fr: 'Télécharger',
      es: 'Descargar',
      pt: 'Baixar',
      tr: 'İndir',
      uk: 'Завантажити',
      zh: '下载',
      ar: 'تنزيل',
      pl: 'Pobierz',
      it: 'Scarica',
      sk: 'Pobierz',
    }),
    share: t({
      ru: 'Поделиться',
      en: 'Share',
      kk: 'Бөлісу',
      de: 'Teilen',
      fr: 'Partager',
      es: 'Compartir',
      pt: 'Compartilhar',
      tr: 'Paylaş',
      uk: 'Поділитися',
      zh: '分享',
      ar: 'مشاركة',
      pl: 'Udostępnij',
      it: 'Condividi',
      sk: 'Udostępnij',
    }),
  },
} satisfies Dictionary;

export default content;
