import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsPageView',
  content: {
    notImplemented: t({
      ru: 'Еще не реализовано',
      en: 'Not implemented yet',
      kk: 'Әлі іске асырылмаған',
      de: 'Noch nicht implementiert',
      fr: 'Pas encore implémenté',
      es: 'Aún no implementado',
      pt: 'Ainda não implementado',
      tr: 'Henüz uygulanmadı',
      uk: 'Ще не реалізовано',
      zh: '尚未实现',
      ar: 'لم يتم التنفيذ بعد',
      pl: 'Jeszcze nie zaimplementowano',
      it: 'Non ancora implementato',
      sk: 'Jeszcze nie zaimplementowano',
    }),
    categoryUpdated: t({
      ru: 'Категория обновлена успешно',
      en: 'Category updated successfully',
      kk: 'Санат сәтті жаңартылды',
      de: 'Kategorie erfolgreich aktualisiert',
      fr: 'Catégorie mise à jour avec succès',
      es: 'Categoría actualizada correctamente',
      pt: 'Categoria atualizada com sucesso',
      tr: 'Kategori başarıyla güncellendi',
      uk: 'Категорію успішно оновлено',
      zh: '分类更新成功',
      ar: 'تم تحديث الفئة بنجاح',
      pl: 'Kategoria zaktualizowana pomyślnie',
      it: 'Categoria aggiornata con successo',
      sk: 'Kategoria zaktualizowana pomyślnie',
    }),
    categoryUpdateFailed: t({
      ru: 'Не удалось обновить категорию',
      en: 'Failed to update category',
      kk: 'Санатты жаңарту сәтсіз аяқталды',
      de: 'Kategorie konnte nicht aktualisiert werden',
      fr: 'Échec de la mise à jour de la catégorie',
      es: 'Error al actualizar la categoría',
      pt: 'Falha ao atualizar a categoria',
      tr: 'Kategori güncellenemedi',
      uk: 'Не вдалося оновити категорію',
      zh: '更新分类失败',
      ar: 'فشل تحديث الفئة',
      pl: 'Nie udało się zaktualizować kategorii',
      it: 'Impossibile aggiornare la categoria',
      sk: 'Nie udało się zaktualizować kategorii',
    }),
    categoriesUpdated: t({
      ru: 'Категория назначена транзакциям',
      en: 'Category assigned to transactions',
      kk: 'Санат транзакцияларға тағайындалды',
      de: 'Kategorie den Transaktionen zugewiesen',
      fr: 'Catégorie attribuée aux transactions',
      es: 'Categoría asignada a las transacciones',
      pt: 'Categoria atribuída às transações',
      tr: 'Kategori işlemlere atandı',
      uk: 'Категорію призначено транзакціям',
      zh: '分类已分配给交易',
      ar: 'تم تعيين الفئة للمعاملات',
      pl: 'Kategoria przypisana do transakcji',
      it: 'Categoria assegnata alle transazioni',
      sk: 'Kategoria przypisana do transakcji',
    }),
    bulkUpdateFailed: t({
      ru: 'Не удалось обновить категории',
      en: 'Failed to update categories',
      kk: 'Санаттарды жаңарту сәтсіз аяқталды',
      de: 'Kategorien konnten nicht aktualisiert werden',
      fr: 'Échec de la mise à jour des catégories',
      es: 'Error al actualizar las categorías',
      pt: 'Falha ao atualizar as categorias',
      tr: 'Kategoriler güncellenemedi',
      uk: 'Не вдалося оновити категорії',
      zh: '批量更新分类失败',
      ar: 'فشل تحديث الفئات',
      pl: 'Nie udało się zaktualizować kategorii',
      it: 'Impossibile aggiornare le categorie',
      sk: 'Nie udało się zaktualizować kategorii',
    }),
    exportComingSoon: t({
      ru: 'Экспорт скоро будет доступен',
      en: 'Export feature coming soon',
      kk: 'Экспорт мүмкіндігі жақын арада',
      de: 'Exportfunktion demnächst verfügbar',
      fr: 'Fonctionnalité d\'export bientôt disponible',
      es: 'Función de exportación próximamente',
      pt: 'Função de exportação em breve',
      tr: 'Dışa aktarma özelliği yakında',
      uk: 'Функція експорту незабаром буде доступна',
      zh: '导出功能即将推出',
      ar: 'ميزة التصدير قادمة قريباً',
      pl: 'Funkcja eksportu wkrótce',
      it: 'Funzione di esportazione in arrivo',
      sk: 'Funkcja eksportu wkrótce',
    }),
    shareComingSoon: t({
      ru: 'Функция поделиться скоро будет доступна',
      en: 'Share feature coming soon',
      kk: 'Бөлісу мүмкіндігі жақын арада',
      de: 'Teilfunktion demnächst verfügbar',
      fr: 'Fonctionnalité de partage bientôt disponible',
      es: 'Función de compartir próximamente',
      pt: 'Função de compartilhamento em breve',
      tr: 'Paylaşma özelliği yakında',
      uk: 'Функція поділитися незабаром буде доступна',
      zh: '分享功能即将推出',
      ar: 'ميزة المشاركة قادمة قريباً',
      pl: 'Funkcja udostępniania wkrótce',
      it: 'Funzione di condivisione in arrivo',
      sk: 'Funkcja udostępniania wkrótce',
    }),
    fixIssuesHint: t({
      ru: 'Используйте фильтры для поиска и исправления проблем',
      en: 'Use filters to find and fix issues',
      kk: 'Мәселелерді табу және шешу үшін сүзгілерді пайдаланыңыз',
      de: 'Verwenden Sie Filter, um Probleme zu finden und zu beheben',
      fr: 'Utilisez les filtres pour trouver et corriger les problèmes',
      es: 'Use filtros para encontrar y corregir problemas',
      pt: 'Use filtros para encontrar e corrigir problemas',
      tr: 'Sorunları bulmak ve düzeltmek için filtreleri kullanın',
      uk: 'Використовуйте фільтри для пошуку та виправлення проблем',
      zh: '使用筛选器查找并修复问题',
      ar: 'استخدم المرشحات للعثور على المشكلات وإصلاحها',
      pl: 'Użyj filtrów, aby znaleźć i naprawić problemy',
      it: 'Usa i filtri per trovare e risolvere i problemi',
      sk: 'Użyj filtrów, aby znaleźć i naprawić problemy',
    }),
    selected: t({
      ru: 'выбрано',
      en: 'selected',
      kk: 'таңдалды',
      de: 'ausgewählt',
      fr: 'sélectionné',
      es: 'seleccionado',
      pt: 'selecionado',
      tr: 'seçildi',
      uk: 'вибрано',
      zh: '已选择',
      ar: 'محدد',
      pl: 'zaznaczono',
      it: 'selezionato',
      sk: 'zaznaczono',
    }),
    selectCategory: t({
      ru: 'Выберите категорию...',
      en: 'Select category...',
      kk: 'Санат таңдаңыз...',
      de: 'Kategorie auswählen...',
      fr: 'Sélectionner une catégorie...',
      es: 'Seleccionar categoría...',
      pt: 'Selecionar categoria...',
      tr: 'Kategori seçin...',
      uk: 'Оберіть категорію...',
      zh: '选择分类...',
      ar: 'اختر الفئة...',
      pl: 'Wybierz kategorię...',
      it: 'Seleziona categoria...',
      sk: 'Wybierz kategorię...',
    }),
    apply: t({
      ru: 'Применить',
      en: 'Apply',
      kk: 'Қолдану',
      de: 'Anwenden',
      fr: 'Appliquer',
      es: 'Aplicar',
      pt: 'Aplicar',
      tr: 'Uygula',
      uk: 'Застосувати',
      zh: '应用',
      ar: 'تطبيق',
      pl: 'Zastosuj',
      it: 'Applica',
      sk: 'Zastosuj',
    }),
    clearSelection: t({
      ru: 'Очистить',
      en: 'Clear',
      kk: 'Тазалау',
      de: 'Löschen',
      fr: 'Effacer',
      es: 'Limpiar',
      pt: 'Limpar',
      tr: 'Temizle',
      uk: 'Очистити',
      zh: '清除',
      ar: 'مسح',
      pl: 'Wyczyść',
      it: 'Cancella',
      sk: 'Wyczyść',
    }),
    allCategorized: t({
      ru: 'Все транзакции уже категоризированы',
      en: 'All transactions are already categorized',
      kk: 'Барлық транзакциялар санатталған',
      de: 'Alle Transaktionen sind bereits kategorisiert',
      fr: 'Toutes les transactions sont déjà catégorisées',
      es: 'Todas las transacciones ya están categorizadas',
      pt: 'Todas as transações já estão categorizadas',
      tr: 'Tüm işlemler zaten kategorize edildi',
      uk: 'Всі транзакції вже категоризовані',
      zh: '所有交易已分类',
      ar: 'جميع المعاملات مصنفة بالفعل',
      pl: 'Wszystkie transakcje są już skategoryzowane',
      it: 'Tutte le transazioni sono già categorizzate',
      sk: 'Wszystkie transakcje są już skategoryzowane',
    }),
    categorizingProgress: t({
      ru: 'Категоризация {{count}} транзакций...',
      en: 'Categorizing {{count}} transactions...',
      kk: '{{count}} транзакция санатталуда...',
      de: '{{count}} Transaktionen werden kategorisiert...',
      fr: 'Catégorisation de {{count}} transactions...',
      es: 'Categorizando {{count}} transacciones...',
      pt: 'Categorizando {{count}} transações...',
      tr: '{{count}} işlem kategorize ediliyor...',
      uk: 'Категоризація {{count}} транзакцій...',
      zh: '正在分类 {{count}} 笔交易...',
      ar: 'جارٍ تصنيف {{count}} معاملة...',
      pl: 'Kategoryzowanie {{count}} transakcji...',
      it: 'Categorizzazione di {{count}} transazioni...',
      sk: 'Kategoryzowanie {{count}} transakcji...',
    }),
    categorizeSuccess: t({
      ru: 'Успешно категоризировано {{count}} транзакций',
      en: 'Successfully categorized {{count}} transactions',
      kk: '{{count}} транзакция сәтті санатталды',
      de: '{{count}} Transaktionen erfolgreich kategorisiert',
      fr: '{{count}} transactions catégorisées avec succès',
      es: '{{count}} transacciones categorizadas correctamente',
      pt: '{{count}} transações categorizadas com sucesso',
      tr: '{{count}} işlem başarıyla kategorize edildi',
      uk: 'Успішно категоризовано {{count}} транзакцій',
      zh: '已成功分类 {{count}} 笔交易',
      ar: 'تم تصنيف {{count}} معاملة بنجاح',
      pl: 'Pomyślnie skategoryzowano {{count}} transakcji',
      it: '{{count}} transazioni categorizzate con successo',
      sk: 'Pomyślnie skategoryzowano {{count}} transakcji',
    }),
    categorizePartial: t({
      ru: 'Категоризировано {{successful}} из {{total}}. Ошибок: {{failed}}',
      en: 'Categorized {{successful}} of {{total}}. Errors: {{failed}}',
      kk: '{{total}} ішінен {{successful}} санатталды. Қателер: {{failed}}',
      de: '{{successful}} von {{total}} kategorisiert. Fehler: {{failed}}',
      fr: '{{successful}} sur {{total}} catégorisés. Erreurs : {{failed}}',
      es: '{{successful}} de {{total}} categorizados. Errores: {{failed}}',
      pt: '{{successful}} de {{total}} categorizados. Erros: {{failed}}',
      tr: '{{total}} içinden {{successful}} kategorize edildi. Hatalar: {{failed}}',
      uk: 'Категоризовано {{successful}} з {{total}}. Помилок: {{failed}}',
      zh: '已分类 {{total}} 中的 {{successful}} 笔。错误：{{failed}}',
      ar: 'تم تصنيف {{successful}} من {{total}}. أخطاء: {{failed}}',
      pl: 'Skategoryzowano {{successful}} z {{total}}. Błędy: {{failed}}',
      it: '{{successful}} di {{total}} categorizzati. Errori: {{failed}}',
      sk: 'Skategoryzowano {{successful}} z {{total}}. Błędy: {{failed}}',
    }),
    categorizeFailed: t({
      ru: 'Не удалось категоризировать (ошибок: {{count}})',
      en: 'Failed to categorize (errors: {{count}})',
      kk: 'Санаттау мүмкін болмады (қателер: {{count}})',
      de: 'Kategorisierung fehlgeschlagen (Fehler: {{count}})',
      fr: 'Échec de la catégorisation (erreurs : {{count}})',
      es: 'Error al categorizar (errores: {{count}})',
      pt: 'Falha ao categorizar (erros: {{count}})',
      tr: 'Kategorize edilemedi (hatalar: {{count}})',
      uk: 'Не вдалося категоризувати (помилок: {{count}})',
      zh: '分类失败（错误：{{count}}）',
      ar: 'فشل التصنيف (أخطاء: {{count}})',
      pl: 'Nie udało się skategoryzować (błędy: {{count}})',
      it: 'Impossibile categorizzare (errori: {{count}})',
      sk: 'Nie udało się skategoryzować (błędy: {{count}})',
    }),
    autoFixFailed: t({
      ru: 'Не удалось автоматически исправить проблемы',
      en: 'Failed to automatically fix issues',
      kk: 'Мәселелерді автоматты түрде түзету мүмкін болмады',
      de: 'Probleme konnten nicht automatisch behoben werden',
      fr: 'Échec de la correction automatique des problèmes',
      es: 'Error al corregir problemas automáticamente',
      pt: 'Falha ao corrigir problemas automaticamente',
      tr: 'Sorunlar otomatik olarak düzeltilemedi',
      uk: 'Не вдалося автоматично виправити проблеми',
      zh: '自动修复问题失败',
      ar: 'فشل إصلاح المشكلات تلقائياً',
      pl: 'Nie udało się automatycznie naprawić problemów',
      it: 'Impossibile correggere automaticamente i problemi',
      sk: 'Nie udało się automatycznie naprawić problemów',
    }),
    exportToTable: t({
      ru: 'Экспорт в таблицу: функционал в разработке',
      en: 'Export to table: feature in development',
      kk: 'Кестеге экспорт: функционал әзірленуде',
      de: 'Export in Tabelle: Funktion in Entwicklung',
      fr: 'Export en tableau : fonctionnalité en développement',
      es: 'Exportar a tabla: función en desarrollo',
      pt: 'Exportar para tabela: recurso em desenvolvimento',
      tr: 'Tabloya aktar: özellik geliştiriliyor',
      uk: 'Експорт у таблицю: функціонал у розробці',
      zh: '导出到表格：功能开发中',
      ar: 'التصدير إلى جدول: الميزة قيد التطوير',
      pl: 'Eksport do tabeli: funkcja w trakcie tworzenia',
      it: 'Esporta in tabella: funzionalità in sviluppo',
      sk: 'Eksport do tabeli: funkcja w trakcie tworzenia',
    }),
    exportFormat: t({
      ru: 'Экспорт в {{type}}: функционал в разработке',
      en: 'Export to {{type}}: feature in development',
      kk: '{{type}} экспорты: функционал әзірленуде',
      de: 'Export nach {{type}}: Funktion in Entwicklung',
      fr: 'Export en {{type}} : fonctionnalité en développement',
      es: 'Exportar a {{type}}: función en desarrollo',
      pt: 'Exportar para {{type}}: recurso em desenvolvimento',
      tr: '{{type}} formatına aktar: özellik geliştiriliyor',
      uk: 'Експорт у {{type}}: функціонал у розробці',
      zh: '导出为 {{type}}：功能开发中',
      ar: 'التصدير إلى {{type}}: الميزة قيد التطوير',
      pl: 'Eksport do {{type}}: funkcja w trakcie tworzenia',
      it: 'Esporta in {{type}}: funzionalità in sviluppo',
      sk: 'Eksport do {{type}}: funkcja w trakcie tworzenia',
    }),
  },
} satisfies Dictionary;

export default content;
