import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsTable',
  content: {
    searchPlaceholder: t({
      ru: 'Поиск по контрагенту, назначению, БИН или номеру  документа...',
      en: 'Search by counterparty, purpose, BIN or document number...',
      kk: 'Контрагент, мақсат, БСН немесе құжат нөмірі бойынша іздеу...',
      de: 'Nach Gegenpartei, Zweck, BIN oder Dokumentnummer suchen...',
      fr: 'Rechercher par contrepartie, objet, BIN ou numéro de document...',
      es: 'Buscar por contraparte, propósito, BIN o número de documento...',
      pt: 'Pesquisar por contraparte, finalidade, BIN ou número do documento...',
      tr: 'Karşı taraf, amaç, BIN veya belge numarasına göre ara...',
      uk: 'Пошук за контрагентом, призначенням, БІН або номером документа...',
      zh: '按交易对手、用途、BIN或文件编号搜索...',
      ar: 'البحث بالطرف المقابل أو الغرض أو BIN أو رقم الوثيقة...',
      pl: 'Szukaj po kontrahencie, celu, BIN lub numerze dokumentu...',
      it: 'Cerca per controparte, scopo, BIN o numero documento...',
    }),
    filters: t({
      ru: 'Фильтры',
      en: 'Filters',
      kk: 'Сүзгілер',
      de: 'Filter',
      fr: 'Filtres',
      es: 'Filtros',
      pt: 'Filtros',
      tr: 'Filtreler',
      uk: 'Фільтри',
      zh: '筛选',
      ar: 'المرشحات',
      pl: 'Filtry',
      it: 'Filtri',
    }),
    statusFilter: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Status',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
    }),
    statusAll: t({
      ru: 'Все',
      en: 'All',
      kk: 'Барлығы',
      de: 'Alle',
      fr: 'Tous',
      es: 'Todos',
      pt: 'Todos',
      tr: 'Tümü',
      uk: 'Всі',
      zh: '全部',
      ar: 'الكل',
      pl: 'Wszystkie',
      it: 'Tutti',
    }),
    statusWarnings: t({
      ru: 'С предупреждениями',
      en: 'With Warnings',
      kk: 'Ескертулермен',
      de: 'Mit Warnungen',
      fr: 'Avec avertissements',
      es: 'Con advertencias',
      pt: 'Com avisos',
      tr: 'Uyarılı',
      uk: 'З попередженнями',
      zh: '有警告',
      ar: 'بتحذيرات',
      pl: 'Z ostrzeżeniami',
      it: 'Con avvisi',
    }),
    statusErrors: t({
      ru: 'С ошибками',
      en: 'With Errors',
      kk: 'Қателермен',
      de: 'Mit Fehlern',
      fr: 'Avec erreurs',
      es: 'Con errores',
      pt: 'Com erros',
      tr: 'Hatalı',
      uk: 'З помилками',
      zh: '有错误',
      ar: 'بأخطاء',
      pl: 'Z błędami',
      it: 'Con errori',
    }),
    statusUncategorized: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Unkategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categorizar',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      ar: 'غير مصنف',
      pl: 'Bez kategorii',
      it: 'Non categorizzato',
    }),
    categoryFilter: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '分类',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
    }),
    categoryAll: t({
      ru: 'Все категории',
      en: 'All Categories',
      kk: 'Барлық санаттар',
      de: 'Alle Kategorien',
      fr: 'Toutes les catégories',
      es: 'Todas las categorías',
      pt: 'Todas as categorias',
      tr: 'Tüm Kategoriler',
      uk: 'Всі категорії',
      zh: '所有分类',
      ar: 'جميع الفئات',
      pl: 'Wszystkie kategorie',
      it: 'Tutte le categorie',
    }),
    clearFilters: t({
      ru: 'Очистить',
      en: 'Clear',
      kk: 'Тазалау',
      de: 'Löschen',
      fr: 'Effacer',
      es: 'Limpiar',
      pt: 'Limpar',
      tr: 'Temizle',
      uk: 'Очистити',
      zh: '清除',
      ar: 'مسح',
      pl: 'Wyczyść',
      it: 'Cancella',
    }),
    columnDate: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
    }),
    columnCounterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı Taraf',
      uk: 'Контрагент',
      zh: '交易对手',
      ar: 'الطرف المقابل',
      pl: 'Kontrahent',
      it: 'Controparte',
    }),
    columnBin: t({
      ru: 'БИН',
      en: 'BIN',
      kk: 'БСН',
      de: 'BIN',
      fr: 'BIN',
      es: 'BIN',
      pt: 'BIN',
      tr: 'BIN',
      uk: 'БІН',
      zh: 'BIN',
      ar: 'رقم BIN',
      pl: 'BIN',
      it: 'BIN',
    }),
    columnPurpose: t({
      ru: 'Назначение',
      en: 'Purpose',
      kk: 'Мақсаты',
      de: 'Zweck',
      fr: 'Objet',
      es: 'Propósito',
      pt: 'Finalidade',
      tr: 'Amaç',
      uk: 'Призначення',
      zh: '用途',
      ar: 'الغرض',
      pl: 'Cel',
      it: 'Scopo',
    }),
    columnDebit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      ar: 'مدين',
      pl: 'Debet',
      it: 'Addebito',
    }),
    columnCredit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      ar: 'دائن',
      pl: 'Kredyt',
      it: 'Credito',
    }),
    columnCategory: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '分类',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
    }),
    noResults: t({
      ru: 'Транзакции не найдены',
      en: 'No transactions found',
      kk: 'Транзакциялар табылмады',
      de: 'Keine Transaktionen gefunden',
      fr: 'Aucune transaction trouvée',
      es: 'No se encontraron transacciones',
      pt: 'Nenhuma transação encontrada',
      tr: 'İşlem bulunamadı',
      uk: 'Транзакції не знайдені',
      zh: '未找到交易',
      ar: 'لم يتم العثور على معاملات',
      pl: 'Nie znaleziono transakcji',
      it: 'Nessuna transazione trovata',
    }),
    rowsPerPage: t({
      ru: 'Строк на странице:',
      en: 'Rows per page:',
      kk: 'Беттегі жолдар:',
      de: 'Zeilen pro Seite:',
      fr: 'Lignes par page :',
      es: 'Filas por página:',
      pt: 'Linhas por página:',
      tr: 'Sayfa başına satır:',
      uk: 'Рядків на сторінці:',
      zh: '每页行数：',
      ar: 'صفوف في الصفحة:',
      pl: 'Wierszy na stronę:',
      it: 'Righe per pagina:',
    }),
    of: t({
      ru: 'из',
      en: 'of',
      kk: '/',
      de: 'von',
      fr: 'sur',
      es: 'de',
      pt: 'de',
      tr: '/',
      uk: 'з',
      zh: '/',
      ar: 'من',
      pl: 'z',
      it: 'di',
    }),
    previous: t({
      ru: 'Назад',
      en: 'Previous',
      kk: 'Артқа',
      de: 'Zurück',
      fr: 'Précédent',
      es: 'Anterior',
      pt: 'Anterior',
      tr: 'Önceki',
      uk: 'Назад',
      zh: '上一页',
      ar: 'السابق',
      pl: 'Poprzednia',
      it: 'Precedente',
    }),
    next: t({
      ru: 'Вперед',
      en: 'Next',
      kk: 'Алға',
      de: 'Weiter',
      fr: 'Suivant',
      es: 'Siguiente',
      pt: 'Próximo',
      tr: 'Sonraki',
      uk: 'Вперед',
      zh: '下一页',
      ar: 'التالي',
      pl: 'Następna',
      it: 'Successivo',
    }),
  },
} satisfies Dictionary;

export default content;
