/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'dashboardPage',
  content: {
    title: t({
      ru: 'Дашборд',
      en: 'Dashboard',
      kk: 'Дашборд',
      de: 'Dashboard',
      fr: 'Tableau de bord',
      es: 'Panel',
      pt: 'Painel',
      tr: 'Gösterge paneli',
      uk: 'Дашборд',
      zh: '仪表板',
      ar: 'لوحة التحكم',
      pl: 'Pulpit',
      it: 'Dashboard',
      sk: 'Pulpit',
    }),
    subtitle: t({
      ru: 'Последние 30 дней',
      en: 'Last 30 days',
      kk: 'Соңғы 30 күн',
      de: 'Letzte 30 Tage',
      fr: '30 derniers jours',
      es: 'Últimos 30 días',
      pt: 'Últimos 30 dias',
      tr: 'Son 30 gün',
      uk: 'Останні 30 днів',
      zh: '最近 30 天',
      ar: 'آخر 30 يومًا',
      pl: 'Ostatnie 30 dni',
      it: 'Ultimi 30 giorni',
      sk: 'Ostatnie 30 dni',
    }),
    workspaceFallback: t({
      ru: 'Рабочее пространство',
      en: 'Workspace',
      kk: 'Жұмыс кеңістігі',
      de: 'Arbeitsbereich',
      fr: 'Espace de travail',
      es: 'Espacio de trabajo',
      pt: 'Espaço de trabalho',
      tr: 'Çalışma alanı',
      uk: 'Робочий простір',
      zh: '工作区',
      ar: 'مساحة العمل',
      pl: 'Obszar roboczy',
      it: 'Area di lavoro',
      sk: 'Obszar roboczy',
    }),
    snapshot: {
      totalBalance: t({
        ru: 'Баланс',
        en: 'Total balance',
        kk: 'Баланс',
        de: 'Gesamtguthaben',
        fr: 'Solde total',
        es: 'Balance total',
        pt: 'Saldo total',
        tr: 'Toplam bakiye',
        uk: 'Баланс',
        zh: '总余额',
        ar: 'الرصيد الإجمالي',
        pl: 'Łączne saldo',
        it: 'Saldo totale',
        sk: 'Łączne saldo',
      }),
      income: t({
        ru: 'Доход (30д)',
        en: 'Income (30d)',
        kk: 'Түсім (30к)',
        de: 'Einnahmen (30T)',
        fr: 'Revenus (30j)',
        es: 'Ingresos (30d)',
        pt: 'Receitas (30d)',
        tr: 'Gelir (30g)',
        uk: 'Дохід (30д)',
        zh: '收入 (30天)',
        ar: 'الدخل (30 يومًا)',
        pl: 'Przychód (30d)',
        it: 'Entrate (30g)',
        sk: 'Przychód (30d)',
      }),
      expense: t({
        ru: 'Расход (30д)',
        en: 'Expense (30d)',
        kk: 'Шығыс (30к)',
        de: 'Ausgaben (30T)',
        fr: 'Dépenses (30j)',
        es: 'Gastos (30d)',
        pt: 'Despesas (30d)',
        tr: 'Gider (30g)',
        uk: 'Витрати (30д)',
        zh: '支出 (30天)',
        ar: 'المصروفات (30 يومًا)',
        pl: 'Wydatki (30d)',
        it: 'Spese (30g)',
        sk: 'Wydatki (30d)',
      }),
      netFlow: t({
        ru: 'Net flow',
        en: 'Net flow',
        kk: 'Net flow',
        de: 'Netto-Cashflow',
        fr: 'Flux net',
        es: 'Flujo neto',
        pt: 'Fluxo líquido',
        tr: 'Net akış',
        uk: 'Чистий потік',
        zh: '净现金流',
        ar: 'صافي التدفق',
        pl: 'Przepływ netto',
        it: 'Flusso netto',
        sk: 'Przepływ netto',
      }),
      toPay: t({
        ru: 'К оплате',
        en: 'To pay',
        kk: 'Төлеу керек',
        de: 'Zu zahlen',
        fr: 'À payer',
        es: 'Por pagar',
        pt: 'A pagar',
        tr: 'Ödenecek',
        uk: 'До оплати',
        zh: '待付款',
        ar: 'للدفع',
        pl: 'Do zapłaty',
        it: 'Da pagare',
        sk: 'Do zapłaty',
      }),
      overdue: t({
        ru: 'Просрочено',
        en: 'Overdue',
        kk: 'Мерзімі өтті',
        de: 'Überfällig',
        fr: 'En retard',
        es: 'Vencido',
        pt: 'Vencido',
        tr: 'Vadesi geçmiş',
        uk: 'Прострочено',
        zh: '已逾期',
        ar: 'متأخر',
        pl: 'Zaległe',
        it: 'Scaduto',
        sk: 'Zaległe',
      }),
    },
    actions: {
      title: t({
        ru: 'Требуют действия',
        en: 'Action required',
        kk: 'Әрекет қажет',
        de: 'Aktion erforderlich',
        fr: 'Action requise',
        es: 'Acción requerida',
        pt: 'Ação necessária',
        tr: 'İşlem gerekiyor',
        uk: 'Потрібна дія',
        zh: '需要操作',
        ar: 'يلزم اتخاذ إجراء',
        pl: 'Wymagane działanie',
        it: 'Azione richiesta',
        sk: 'Wymagane działanie',
      }),
      empty: t({
        ru: 'Нет срочных действий',
        en: 'All clear — no actions required',
        kk: 'Шұғыл әрекеттер жоқ',
        de: 'Alles in Ordnung — keine Aktionen erforderlich',
        fr: 'Tout est en ordre — aucune action requise',
        es: 'Todo en orden — no se requieren acciones',
        pt: 'Tudo certo — nenhuma ação necessária',
        tr: 'Her şey yolunda — işlem gerekmiyor',
        uk: 'Все гаразд — дій не потрібно',
        zh: '一切正常，无需操作',
        ar: 'كل شيء على ما يرام — لا إجراءات مطلوبة',
        pl: 'Wszystko w porządku — brak wymaganych działań',
        it: 'Tutto a posto — nessuna azione richiesta',
        sk: 'Wszystko w porządku — brak wymaganych działań',
      }),
    },
    cashFlow: {
      title: t({
        ru: 'Cash flow',
        en: 'Cash flow',
        kk: 'Cash flow',
        de: 'Cashflow',
        fr: 'Flux de trésorerie',
        es: 'Flujo de caja',
        pt: 'Fluxo de caixa',
        tr: 'Nakit akışı',
        uk: 'Грошовий потік',
        zh: '现金流',
        ar: 'التدفق النقدي',
        pl: 'Przepływy pieniężne',
        it: 'Flusso di cassa',
        sk: 'Przepływy pieniężne',
      }),
      empty: t({
        ru: 'Нет данных по cash flow за 30 дней',
        en: 'No cash flow data for the last 30 days',
        kk: 'Соңғы 30 күнде cash flow деректері жоқ',
        de: 'Keine Cashflow-Daten für die letzten 30 Tage',
        fr: 'Aucune donnée de flux de trésorerie pour les 30 derniers jours',
        es: 'Sin datos de flujo de caja para los últimos 30 días',
        pt: 'Sem dados de fluxo de caixa para os últimos 30 dias',
        tr: 'Son 30 gün için nakit akışı verisi yok',
        uk: 'Немає даних по грошовому потоку за 30 днів',
        zh: '最近 30 天没有现金流数据',
        ar: 'لا توجد بيانات تدفق نقدي للـ 30 يومًا الماضية',
        pl: 'Brak danych przepływów pieniężnych za ostatnie 30 dni',
        it: 'Nessun dato di flusso di cassa per gli ultimi 30 giorni',
        sk: 'Brak danych przepływów pieniężnych za ostatnie 30 dni',
      }),
    },
    categories: {
      title: t({
        ru: 'Статьи расходов',
        en: 'Expense categories',
        kk: 'Шығыс санаттары',
        de: 'Ausgabenkategorien',
        fr: 'Catégories de dépenses',
        es: 'Categorías de gastos',
        pt: 'Categorias de despesas',
        tr: 'Harcama kategorileri',
        uk: 'Статті витрат',
        zh: '支出类别',
        ar: 'فئات المصروفات',
        pl: 'Kategorie wydatków',
        it: 'Categorie di spesa',
        sk: 'Kategorie wydatków',
      }),
      empty: t({
        ru: 'Нет данных по категориям расходов',
        en: 'No expense category data',
        kk: 'Шығыс санаттары бойынша дерек жоқ',
        de: 'Keine Daten zu Ausgabenkategorien',
        fr: 'Aucune donnée de catégorie de dépenses',
        es: 'Sin datos de categorías de gastos',
        pt: 'Sem dados de categorias de despesas',
        tr: 'Harcama kategorisi verisi yok',
        uk: 'Немає даних по категоріях витрат',
        zh: '没有支出类别数据',
        ar: 'لا توجد بيانات لفئات المصروفات',
        pl: 'Brak danych kategorii wydatków',
        it: 'Nessun dato sulle categorie di spesa',
        sk: 'Brak danych kategorii wydatków',
      }),
    },
    activity: {
      title: t({
        ru: 'Последние действия',
        en: 'Recent activity',
        kk: 'Соңғы әрекеттер',
        de: 'Letzte Aktivitäten',
        fr: 'Activité récente',
        es: 'Actividad reciente',
        pt: 'Atividade recente',
        tr: 'Son etkinlik',
        uk: 'Остання активність',
        zh: '最近活动',
        ar: 'النشاط الأخير',
        pl: 'Ostatnia aktywność',
        it: 'Attività recente',
        sk: 'Ostatnia aktywność',
      }),
      empty: t({
        ru: 'Нет активности',
        en: 'No recent activity',
        kk: 'Белсенділік жоқ',
        de: 'Keine Aktivitäten',
        fr: 'Aucune activité récente',
        es: 'Sin actividad reciente',
        pt: 'Sem atividade recente',
        tr: 'Son etkinlik yok',
        uk: 'Немає активності',
        zh: '没有最近活动',
        ar: 'لا يوجد نشاط حديث',
        pl: 'Brak ostatniej aktywności',
        it: 'Nessuna attività recente',
        sk: 'Brak ostatniej aktywności',
      }),
    },
    notifications: {
      title: t({
        ru: 'Важные уведомления',
        en: 'Important notifications',
        kk: 'Маңызды хабарламалар',
        de: 'Wichtige Benachrichtigungen',
        fr: 'Notifications importantes',
        es: 'Notificaciones importantes',
        pt: 'Notificações importantes',
        tr: 'Önemli bildirimler',
        uk: 'Важливі сповіщення',
        zh: '重要通知',
        ar: 'إشعارات مهمة',
        pl: 'Ważne powiadomienia',
        it: 'Notifiche importanti',
        sk: 'Ważne powiadomienia',
      }),
      empty: t({
        ru: 'Нет новых уведомлений',
        en: 'No new notifications',
        kk: 'Жаңа хабарламалар жоқ',
        de: 'Keine neuen Benachrichtigungen',
        fr: 'Aucune nouvelle notification',
        es: 'Sin nuevas notificaciones',
        pt: 'Sem novas notificações',
        tr: 'Yeni bildirim yok',
        uk: 'Немає нових сповіщень',
        zh: '没有新通知',
        ar: 'لا توجد إشعارات جديدة',
        pl: 'Brak nowych powiadomień',
        it: 'Nessuna nuova notifica',
        sk: 'Brak nowych powiadomień',
      }),
      settings: t({
        ru: 'Настройки уведомлений',
        en: 'Notification settings',
        kk: 'Хабарлама баптаулары',
        de: 'Benachrichtigungseinstellungen',
        fr: 'Paramètres de notification',
        es: 'Configuración de notificaciones',
        pt: 'Configurações de notificação',
        tr: 'Bildirim ayarları',
        uk: 'Налаштування сповіщень',
        zh: '通知设置',
        ar: 'إعدادات الإشعارات',
        pl: 'Ustawienia powiadomień',
        it: 'Impostazioni notifiche',
        sk: 'Ustawienia powiadomień',
      }),
    },
    latestStatements: {
      title: t({
        ru: 'Последние выписки',
        en: 'Latest statements',
        kk: 'Соңғы үзінділер',
        de: 'Neueste Kontoauszüge',
        fr: 'Derniers relevés',
        es: 'Últimos extractos',
        pt: 'Últimos extratos',
        tr: 'Son hesap özetleri',
        uk: 'Останні виписки',
        zh: '最新对账单',
        ar: 'أحدث الكشوف',
        pl: 'Najnowsze wyciągi',
        it: 'Ultimi estratti conto',
        sk: 'Najnowsze wyciągi',
      }),
      empty: t({
        ru: 'Выписок пока нет',
        en: 'No statements yet',
        kk: 'Үзінділер әлі жоқ',
        de: 'Noch keine Kontoauszüge',
        fr: 'Pas encore de relevés',
        es: 'Aún no hay extractos',
        pt: 'Ainda sem extratos',
        tr: 'Henüz hesap özeti yok',
        uk: 'Виписок поки немає',
        zh: '暂无对账单',
        ar: 'لا توجد كشوف بعد',
        pl: 'Brak wyciągów',
        it: 'Nessun estratto conto ancora',
        sk: 'Brak wyciągów',
      }),
    },
    latestReceipts: {
      title: t({
        ru: 'Последние чеки',
        en: 'Latest receipts',
        kk: 'Соңғы чектер',
        de: 'Neueste Belege',
        fr: 'Derniers reçus',
        es: 'Últimos recibos',
        pt: 'Últimos recibos',
        tr: 'Son makbuzlar',
        uk: 'Останні чеки',
        zh: '最新收据',
        ar: 'أحدث الإيصالات',
        pl: 'Najnowsze paragony',
        it: 'Ultimi ricevuti',
        sk: 'Najnowsze paragony',
      }),
      empty: t({
        ru: 'Чеков пока нет',
        en: 'No receipts yet',
        kk: 'Чектер әлі жоқ',
        de: 'Noch keine Belege',
        fr: 'Pas encore de reçus',
        es: 'Aún no hay recibos',
        pt: 'Ainda sem recibos',
        tr: 'Henüz makbuz yok',
        uk: 'Чеків поки немає',
        zh: '暂无收据',
        ar: 'لا توجد إيصالات بعد',
        pl: 'Brak paragonów',
        it: 'Nessun ricevuto ancora',
        sk: 'Brak paragonów',
      }),
    },
    refresh: {
      idle: t({
        ru: 'Потяните, чтобы обновить',
        en: 'Pull to refresh',
        kk: 'Жаңарту үшін тартыңыз',
        de: 'Zum Aktualisieren ziehen',
        fr: 'Tirer pour actualiser',
        es: 'Desliza para actualizar',
        pt: 'Puxe para atualizar',
        tr: 'Yenilemek için çekin',
        uk: 'Потягніть, щоб оновити',
        zh: '下拉刷新',
        ar: 'اسحب للتحديث',
        pl: 'Pociągnij, aby odświeżyć',
        it: 'Trascina per aggiornare',
        sk: 'Pociągnij, aby odświeżyć',
      }),
      ready: t({
        ru: 'Отпустите для обновления',
        en: 'Release to refresh',
        kk: 'Жаңарту үшін жіберіңіз',
        de: 'Loslassen zum Aktualisieren',
        fr: 'Relâcher pour actualiser',
        es: 'Suelta para actualizar',
        pt: 'Solte para atualizar',
        tr: 'Yenilemek için bırakın',
        uk: 'Відпустіть для оновлення',
        zh: '释放以刷新',
        ar: 'أفلت للتحديث',
        pl: 'Puść, aby odświeżyć',
        it: 'Rilascia per aggiornare',
        sk: 'Puść, aby odświeżyć',
      }),
      loading: t({
        ru: 'Обновляем...',
        en: 'Refreshing...',
        kk: 'Жаңартылуда...',
        de: 'Wird aktualisiert...',
        fr: 'Actualisation...',
        es: 'Actualizando...',
        pt: 'Atualizando...',
        tr: 'Yenileniyor...',
        uk: 'Оновлення...',
        zh: '刷新中...',
        ar: 'جارٍ التحديث...',
        pl: 'Odświeżanie...',
        it: 'Aggiornamento...',
        sk: 'Odświeżanie...',
      }),
    },
    error: {
      load: t({
        ru: 'Не удалось загрузить дашборд',
        en: 'Failed to load dashboard',
        kk: 'Дашборд жүктелмеді',
        de: 'Dashboard konnte nicht geladen werden',
        fr: 'Impossible de charger le tableau de bord',
        es: 'Error al cargar el panel',
        pt: 'Falha ao carregar o painel',
        tr: 'Gösterge paneli yüklenemedi',
        uk: 'Не вдалося завантажити дашборд',
        zh: '仪表板加载失败',
        ar: 'فشل تحميل لوحة التحكم',
        pl: 'Nie udało się załadować pulpitu',
        it: 'Impossibile caricare la dashboard',
        sk: 'Nie udało się załadować pulpitu',
      }),
    },
    range: {
      '7d': t({
        ru: '7 дней',
        en: '7d',
        kk: '7 күн',
        de: '7T',
        fr: '7j',
        es: '7d',
        pt: '7d',
        tr: '7g',
        uk: '7 днів',
        zh: '7天',
        ar: '7 أيام',
        pl: '7d',
        it: '7g',
        sk: '7d',
      }),
      '30d': t({
        ru: '30 дней',
        en: '30d',
        kk: '30 күн',
        de: '30T',
        fr: '30j',
        es: '30d',
        pt: '30d',
        tr: '30g',
        uk: '30 днів',
        zh: '30天',
        ar: '30 يومًا',
        pl: '30d',
        it: '30g',
        sk: '30d',
      }),
      '90d': t({
        ru: '90 дней',
        en: '90d',
        kk: '90 күн',
        de: '90T',
        fr: '90j',
        es: '90d',
        pt: '90d',
        tr: '90g',
        uk: '90 днів',
        zh: '90天',
        ar: '90 يومًا',
        pl: '90d',
        it: '90g',
        sk: '90d',
      }),
    },
    tabs: {
      overview: t({
        ru: 'Обзор',
        en: 'Overview',
        kk: 'Шолу',
        de: 'Übersicht',
        fr: 'Aperçu',
        es: 'Resumen',
        pt: 'Visão geral',
        tr: 'Genel bakış',
        uk: 'Огляд',
        zh: '概览',
        ar: 'نظرة عامة',
        pl: 'Przegląd',
        it: 'Panoramica',
        sk: 'Przegląd',
      }),
      trends: t({
        ru: 'Тренды',
        en: 'Trends',
        kk: 'Трендтер',
        de: 'Trends',
        fr: 'Tendances',
        es: 'Tendencias',
        pt: 'Tendências',
        tr: 'Eğilimler',
        uk: 'Тренди',
        zh: '趋势',
        ar: 'الاتجاهات',
        pl: 'Trendy',
        it: 'Tendenze',
        sk: 'Trendy',
      }),
      dataHealth: t({
        ru: 'Качество данных',
        en: 'Data Health',
        kk: 'Деректер сапасы',
        de: 'Datenqualität',
        fr: 'Qualité des données',
        es: 'Calidad de datos',
        pt: 'Saúde dos dados',
        tr: 'Veri sağlığı',
        uk: 'Якість даних',
        zh: '数据健康',
        ar: 'جودة البيانات',
        pl: 'Jakość danych',
        it: 'Salute dei dati',
        sk: 'Jakość danych',
      }),
    },
    quickActions: {
      upload: t({
        ru: 'Загрузить / Распарсить',
        en: 'Upload / Parse',
        kk: 'Жүктеу / Талдау',
        de: 'Hochladen / Verarbeiten',
        fr: 'Télécharger / Analyser',
        es: 'Subir / Analizar',
        pt: 'Carregar / Analisar',
        tr: 'Yükle / Ayrıştır',
        uk: 'Завантажити / Розібрати',
        zh: '上传 / 解析',
        ar: 'رفع / تحليل',
        pl: 'Prześlij / Parsuj',
        it: 'Carica / Analizza',
        sk: 'Prześlij / Parsuj',
      }),
      review: t({
        ru: 'Очередь на проверку',
        en: 'Review queue',
        kk: 'Тексеру кезегі',
        de: 'Prüfwarteschlange',
        fr: 'File de révision',
        es: 'Cola de revisión',
        pt: 'Fila de revisão',
        tr: 'İnceleme kuyruğu',
        uk: 'Черга на перевірку',
        zh: '审核队列',
        ar: 'طابور المراجعة',
        pl: 'Kolejka do przeglądu',
        it: 'Coda di revisione',
        sk: 'Kolejka do przeglądu',
      }),
      export: t({
        ru: 'Экспорт',
        en: 'Export',
        kk: 'Экспорт',
        de: 'Exportieren',
        fr: 'Exporter',
        es: 'Exportar',
        pt: 'Exportar',
        tr: 'Dışa aktar',
        uk: 'Експорт',
        zh: '导出',
        ar: 'تصدير',
        pl: 'Eksportuj',
        it: 'Esporta',
        sk: 'Eksportuj',
      }),
    },
    exportMenu: {
      button: t({
        ru: 'Экспорт',
        en: 'Export',
        kk: 'Экспорт',
        de: 'Exportieren',
        fr: 'Exporter',
        es: 'Exportar',
        pt: 'Exportar',
        tr: 'Dışa aktar',
        uk: 'Експорт',
        zh: '导出',
        ar: 'تصدير',
        pl: 'Eksportuj',
        it: 'Esporta',
        sk: 'Eksportuj',
      }),
      title: t({
        ru: 'Экспорт данных',
        en: 'Export data',
        kk: 'Деректерді экспорттау',
        de: 'Daten exportieren',
        fr: 'Exporter les données',
        es: 'Exportar datos',
        pt: 'Exportar dados',
        tr: 'Verileri dışa aktar',
        uk: 'Експорт даних',
        zh: '导出数据',
        ar: 'تصدير البيانات',
        pl: 'Eksportuj dane',
        it: 'Esporta dati',
        sk: 'Eksportuj dane',
      }),
      excel: t({
        ru: 'Excel (.xlsx)',
        en: 'Excel (.xlsx)',
        kk: 'Excel (.xlsx)',
        de: 'Excel (.xlsx)',
        fr: 'Excel (.xlsx)',
        es: 'Excel (.xlsx)',
        pt: 'Excel (.xlsx)',
        tr: 'Excel (.xlsx)',
        uk: 'Excel (.xlsx)',
        zh: 'Excel (.xlsx)',
        ar: 'Excel (.xlsx)',
        pl: 'Excel (.xlsx)',
        it: 'Excel (.xlsx)',
        sk: 'Excel (.xlsx)',
      }),
      pdf: t({
        ru: 'PDF',
        en: 'PDF',
        kk: 'PDF',
        de: 'PDF',
        fr: 'PDF',
        es: 'PDF',
        pt: 'PDF',
        tr: 'PDF',
        uk: 'PDF',
        zh: 'PDF',
        ar: 'PDF',
        pl: 'PDF',
        it: 'PDF',
        sk: 'PDF',
      }),
      csv: t({
        ru: 'CSV',
        en: 'CSV',
        kk: 'CSV',
        de: 'CSV',
        fr: 'CSV',
        es: 'CSV',
        pt: 'CSV',
        tr: 'CSV',
        uk: 'CSV',
        zh: 'CSV',
        ar: 'CSV',
        pl: 'CSV',
        it: 'CSV',
        sk: 'CSV',
      }),
      docx: t({
        ru: 'Word (.docx)',
        en: 'Word (.docx)',
        kk: 'Word (.docx)',
        de: 'Word (.docx)',
        fr: 'Word (.docx)',
        es: 'Word (.docx)',
        pt: 'Word (.docx)',
        tr: 'Word (.docx)',
        uk: 'Word (.docx)',
        zh: 'Word (.docx)',
        ar: 'Word (.docx)',
        pl: 'Word (.docx)',
        it: 'Word (.docx)',
        sk: 'Word (.docx)',
      }),
      downloading: t({
        ru: 'Скачивание...',
        en: 'Downloading...',
        kk: 'Жүктелуде...',
        de: 'Herunterladen...',
        fr: 'Téléchargement...',
        es: 'Descargando...',
        pt: 'Baixando...',
        tr: 'İndiriliyor...',
        uk: 'Завантаження...',
        zh: '下载中...',
        ar: 'جارٍ التنزيل...',
        pl: 'Pobieranie...',
        it: 'Download in corso...',
        sk: 'Pobieranie...',
      }),
      success: t({
        ru: 'Файл успешно скачан',
        en: 'File downloaded successfully',
        kk: 'Файл сәтті жүктелді',
        de: 'Datei erfolgreich heruntergeladen',
        fr: 'Fichier téléchargé avec succès',
        es: 'Archivo descargado correctamente',
        pt: 'Arquivo baixado com sucesso',
        tr: 'Dosya başarıyla indirildi',
        uk: 'Файл успішно завантажено',
        zh: '文件下载成功',
        ar: 'تم تنزيل الملف بنجاح',
        pl: 'Plik pobrany pomyślnie',
        it: 'File scaricato con successo',
        sk: 'Plik pobrany pomyślnie',
      }),
      error: t({
        ru: 'Ошибка при скачивании',
        en: 'Download failed',
        kk: 'Жүктеу қатесі',
        de: 'Download fehlgeschlagen',
        fr: 'Échec du téléchargement',
        es: 'Error al descargar',
        pt: 'Falha no download',
        tr: 'İndirme başarısız',
        uk: 'Помилка при завантаженні',
        zh: '下载失败',
        ar: 'فشل التنزيل',
        pl: 'Pobieranie nie powiodło się',
        it: 'Download non riuscito',
        sk: 'Pobieranie nie powiodło się',
      }),
    },
    greeting: {
      fallbackName: t({
        ru: 'Пользователь',
        en: 'User',
        kk: 'Қолданушы',
        de: 'Benutzer',
        fr: 'Utilisateur',
        es: 'Usuario',
        pt: 'Usuário',
        tr: 'Kullanıcı',
        uk: 'Користувач',
        zh: '用户',
        ar: 'المستخدم',
        pl: 'Użytkownik',
        it: 'Utente',
        sk: 'Użytkownik',
      }),
      empty: {
        title: t({
          ru: 'Добро пожаловать, {name}',
          en: 'Welcome, {name}',
          kk: 'Қош келдіңіз, {name}',
          de: 'Willkommen, {name}',
          fr: 'Bienvenue, {name}',
          es: 'Bienvenido, {name}',
          pt: 'Bem-vindo, {name}',
          tr: 'Hoş geldiniz, {name}',
          uk: 'Ласкаво просимо, {name}',
          zh: '欢迎，{name}',
          ar: 'مرحباً، {name}',
          pl: 'Witaj, {name}',
          it: 'Benvenuto, {name}',
          sk: 'Witaj, {name}',
        }),
        subtitle: t({
          ru: 'Загрузите первую выписку, чтобы начать финансовый обзор',
          en: 'Upload your first statement to start building your financial overview',
          kk: 'Қаржылық шолуды бастау үшін алғашқы үзіндіні жүктеңіз',
          de: 'Laden Sie Ihren ersten Kontoauszug hoch, um mit dem Finanzüberblick zu beginnen',
          fr: 'Téléchargez votre premier relevé pour commencer votre aperçu financier',
          es: 'Sube tu primer extracto para comenzar tu resumen financiero',
          pt: 'Carregue seu primeiro extrato para começar seu panorama financeiro',
          tr: 'Finansal genel bakışınızı oluşturmaya başlamak için ilk hesap özetinizi yükleyin',
          uk: 'Завантажте першу виписку, щоб розпочати фінансовий огляд',
          zh: '上传您的第一份对账单，开始构建您的财务概览',
          ar: 'ارفع أول كشف حساب لك لبدء بناء نظرتك المالية',
          pl: 'Prześlij pierwszy wyciąg, aby rozpocząć budowanie przeglądu finansowego',
          it: 'Carica il tuo primo estratto conto per iniziare a costruire la tua panoramica finanziaria',
          sk: 'Prześlij pierwszy wyciąg, aby rozpocząć budowanie przeglądu finansowego',
        }),
      },
      pendingReview: {
        title: t({
          ru: 'С возвращением, {name}',
          en: 'Welcome back, {name}',
          kk: 'Қайта оралдыңыз, {name}',
          de: 'Willkommen zurück, {name}',
          fr: 'Bon retour, {name}',
          es: 'Bienvenido de nuevo, {name}',
          pt: 'Bem-vindo de volta, {name}',
          tr: 'Tekrar hoş geldiniz, {name}',
          uk: 'З поверненням, {name}',
          zh: '欢迎回来，{name}',
          ar: 'مرحباً بعودتك، {name}',
          pl: 'Witaj ponownie, {name}',
          it: 'Bentornato, {name}',
          sk: 'Witaj ponownie, {name}',
        }),
        subtitle: t({
          ru: 'У вас {count} транзакций ждут проверки',
          en: 'You have {count} transactions waiting for review',
          kk: '{count} транзакция тексеруді күтеді',
          de: 'Sie haben {count} Transaktionen, die auf Prüfung warten',
          fr: 'Vous avez {count} transactions en attente de révision',
          es: 'Tienes {count} transacciones esperando revisión',
          pt: 'Você tem {count} transações aguardando revisão',
          tr: '{count} işleminiz inceleme bekliyor',
          uk: 'У вас {count} транзакцій очікують перевірки',
          zh: '您有 {count} 笔交易等待审核',
          ar: 'لديك {count} معاملة في انتظار المراجعة',
          pl: 'Masz {count} transakcji oczekujących na przegląd',
          it: 'Hai {count} transazioni in attesa di revisione',
          sk: 'Masz {count} transakcji oczekujących na przegląd',
        }),
      },
      stale: {
        title: t({
          ru: 'Добрый вечер, {name}',
          en: 'Good evening, {name}',
          kk: 'Қайырлы кеш, {name}',
          de: 'Guten Abend, {name}',
          fr: 'Bonsoir, {name}',
          es: 'Buenas noches, {name}',
          pt: 'Boa noite, {name}',
          tr: 'İyi akşamlar, {name}',
          uk: 'Добрий вечір, {name}',
          zh: '晚上好，{name}',
          ar: 'مساء الخير، {name}',
          pl: 'Dobry wieczór, {name}',
          it: 'Buona sera, {name}',
          sk: 'Dobry wieczór, {name}',
        }),
        subtitle: t({
          ru: 'За последние {days} дней не было новых импортов',
          en: 'No new statements have been imported in the last {days} days',
          kk: 'Соңғы {days} күнде жаңа импорт болмады',
          de: 'In den letzten {days} Tagen wurden keine neuen Kontoauszüge importiert',
          fr: "Aucun nouveau relevé n'a été importé au cours des {days} derniers jours",
          es: 'No se han importado nuevos extractos en los últimos {days} días',
          pt: 'Nenhum novo extrato foi importado nos últimos {days} dias',
          tr: 'Son {days} günde yeni hesap özeti içe aktarılmadı',
          uk: 'За останні {days} днів не було нових імпортів',
          zh: '最近 {days} 天没有导入新的对账单',
          ar: 'لم يتم استيراد أي كشوف جديدة خلال الـ {days} يومًا الماضية',
          pl: 'W ciągu ostatnich {days} dni nie zaimportowano nowych wyciągów',
          it: 'Nessun nuovo estratto conto è stato importato negli ultimi {days} giorni',
          sk: 'W ciągu ostatnich {days} dni nie zaimportowano nowych wyciągów',
        }),
      },
      upToDate: {
        title: t({
          ru: 'С возвращением, {name}',
          en: 'Welcome back, {name}',
          kk: 'Қайта оралдыңыз, {name}',
          de: 'Willkommen zurück, {name}',
          fr: 'Bon retour, {name}',
          es: 'Bienvenido de nuevo, {name}',
          pt: 'Bem-vindo de volta, {name}',
          tr: 'Tekrar hoş geldiniz, {name}',
          uk: 'З поверненням, {name}',
          zh: '欢迎回来，{name}',
          ar: 'مرحباً بعودتك، {name}',
          pl: 'Witaj ponownie, {name}',
          it: 'Bentornato, {name}',
          sk: 'Witaj ponownie, {name}',
        }),
        subtitle: t({
          ru: 'Последние импорты обработаны и актуальны',
          en: 'Your latest imports are processed and up to date',
          kk: 'Соңғы импорттар өңделіп, актуалды',
          de: 'Ihre neuesten Importe sind verarbeitet und aktuell',
          fr: 'Vos dernières importations sont traitées et à jour',
          es: 'Tus últimas importaciones están procesadas y actualizadas',
          pt: 'Suas últimas importações estão processadas e atualizadas',
          tr: 'En son içe aktarmalarınız işlenmiş ve güncel',
          uk: 'Останні імпорти оброблено та актуалізовано',
          zh: '您最新的导入已处理完毕且是最新的',
          ar: 'عمليات الاستيراد الأخيرة تمت معالجتها وهي محدّثة',
          pl: 'Twoje ostatnie importy są przetworzone i aktualne',
          it: 'Le tue ultime importazioni sono elaborate e aggiornate',
          sk: 'Twoje ostatnie importy są przetworzone i aktualne',
        }),
      },
    },
    statusHeading: {
      error: t({
        ru: 'Данные недоступны',
        en: 'Data unavailable',
        kk: 'Деректер қолжетімсіз',
        de: 'Daten nicht verfügbar',
        fr: 'Données indisponibles',
        es: 'Datos no disponibles',
        pt: 'Dados indisponíveis',
        tr: 'Veriler mevcut değil',
        uk: 'Дані недоступні',
        zh: '数据不可用',
        ar: 'البيانات غير متاحة',
        pl: 'Dane niedostępne',
        it: 'Dati non disponibili',
        sk: 'Dane niedostępne',
      }),
      loading: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Wird geladen...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
        sk: 'Ładowanie...',
      }),
      empty: t({
        ru: 'Данных пока нет',
        en: 'No data yet',
        kk: 'Деректер әлі жоқ',
        de: 'Noch keine Daten',
        fr: 'Pas encore de données',
        es: 'Sin datos aún',
        pt: 'Ainda sem dados',
        tr: 'Henüz veri yok',
        uk: 'Даних поки немає',
        zh: '暂无数据',
        ar: 'لا توجد بيانات بعد',
        pl: 'Brak danych',
        it: 'Nessun dato ancora',
        sk: 'Brak danych',
      }),
      overdue: t({
        ru: 'Просрочки',
        en: 'Overdue payments',
        kk: 'Мерзімі өткен',
        de: 'Überfällige Zahlungen',
        fr: 'Paiements en retard',
        es: 'Pagos vencidos',
        pt: 'Pagamentos vencidos',
        tr: 'Vadesi geçmiş ödemeler',
        uk: 'Прострочені платежі',
        zh: '逾期付款',
        ar: 'مدفوعات متأخرة',
        pl: 'Zaległe płatności',
        it: 'Pagamenti scaduti',
        sk: 'Zaległe płatności',
      }),
      needsReview: t({
        ru: 'Ждёт проверки',
        en: 'Needs review',
        kk: 'Тексеру керек',
        de: 'Prüfung erforderlich',
        fr: 'Révision nécessaire',
        es: 'Necesita revisión',
        pt: 'Precisa de revisão',
        tr: 'İnceleme gerekiyor',
        uk: 'Потребує перевірки',
        zh: '需要审核',
        ar: 'يحتاج مراجعة',
        pl: 'Wymaga przeglądu',
        it: 'Necessita revisione',
        sk: 'Wymaga przeglądu',
      }),
      pendingSubmit: t({
        ru: 'Ожидает отправки',
        en: 'Pending submit',
        kk: 'Жіберуді күтуде',
        de: 'Warten auf Übermittlung',
        fr: 'En attente de soumission',
        es: 'Pendiente de envío',
        pt: 'Aguardando envio',
        tr: 'Gönderim bekliyor',
        uk: 'Очікує відправки',
        zh: '等待提交',
        ar: 'في انتظار الإرسال',
        pl: 'Oczekuje na wysłanie',
        it: 'In attesa di invio',
        sk: 'Oczekuje na wysłanie',
      }),
      receiptsNeedReview: t({
        ru: 'Чеки на проверке',
        en: 'Receipts need review',
        kk: 'Чектерді тексеру керек',
        de: 'Belege müssen geprüft werden',
        fr: 'Les reçus nécessitent une révision',
        es: 'Los recibos necesitan revisión',
        pt: 'Recibos precisam de revisão',
        tr: 'Makbuzlar inceleme gerektiriyor',
        uk: 'Чеки потребують перевірки',
        zh: '收据需要审核',
        ar: 'الإيصالات تحتاج مراجعة',
        pl: 'Paragony wymagają przeglądu',
        it: 'I ricevuti necessitano revisione',
        sk: 'Paragony wymagają przeglądu',
      }),
      parsingIssues: t({
        ru: 'Ошибки парсинга',
        en: 'Parsing issues',
        kk: 'Талдау қателері',
        de: 'Analysefehler',
        fr: "Problèmes d'analyse",
        es: 'Problemas de análisis',
        pt: 'Problemas de análise',
        tr: 'Ayrıştırma sorunları',
        uk: 'Помилки парсингу',
        zh: '解析问题',
        ar: 'مشاكل التحليل',
        pl: 'Błędy parsowania',
        it: 'Problemi di analisi',
        sk: 'Błędy parsowania',
      }),
      uncategorized: t({
        ru: 'Без категорий',
        en: 'Uncategorized items',
        kk: 'Санатталмаған',
        de: 'Unkategorisierte Einträge',
        fr: 'Éléments non catégorisés',
        es: 'Elementos sin categorizar',
        pt: 'Itens sem categoria',
        tr: 'Kategorisiz öğeler',
        uk: 'Без категорій',
        zh: '未分类项目',
        ar: 'عناصر غير مصنّفة',
        pl: 'Elementy bez kategorii',
        it: 'Elementi non categorizzati',
        sk: 'Elementy bez kategorii',
      }),
      stale: t({
        ru: 'Данные устарели',
        en: 'Data is stale',
        kk: 'Деректер ескірді',
        de: 'Daten sind veraltet',
        fr: 'Données obsolètes',
        es: 'Datos desactualizados',
        pt: 'Dados desatualizados',
        tr: 'Veriler güncel değil',
        uk: 'Дані застаріли',
        zh: '数据已过期',
        ar: 'البيانات قديمة',
        pl: 'Dane są przestarzałe',
        it: 'I dati non sono aggiornati',
        sk: 'Dane są przestarzałe',
      }),
      negativeFlow: t({
        ru: 'Отрицательный поток',
        en: 'Negative cash flow',
        kk: 'Теріс ағын',
        de: 'Negativer Cashflow',
        fr: 'Flux de trésorerie négatif',
        es: 'Flujo de caja negativo',
        pt: 'Fluxo de caixa negativo',
        tr: 'Negatif nakit akışı',
        uk: "Від'ємний грошовий потік",
        zh: '负现金流',
        ar: 'تدفق نقدي سالب',
        pl: 'Ujemny przepływ pieniężny',
        it: 'Flusso di cassa negativo',
        sk: 'Ujemny przepływ pieniężny',
      }),
      positiveFlow: t({
        ru: 'Положительный поток',
        en: 'Positive cash flow',
        kk: 'Оң ақша ағыны',
        de: 'Positiver Cashflow',
        fr: 'Flux de trésorerie positif',
        es: 'Flujo de caja positivo',
        pt: 'Fluxo de caixa positivo',
        tr: 'Pozitif nakit akışı',
        uk: 'Позитивний грошовий потік',
        zh: '正现金流',
        ar: 'تدفق نقدي إيجابي',
        pl: 'Dodatni przepływ pieniężny',
        it: 'Flusso di cassa positivo',
        sk: 'Dodatni przepływ pieniężny',
      }),
      breakEven: t({
        ru: 'Период баланса',
        en: 'Break-even period',
        kk: 'Тепе-теңдік кезеңі',
        de: 'Kostendeckungsperiode',
        fr: "Période d'équilibre",
        es: 'Período de equilibrio',
        pt: 'Período de equilíbrio',
        tr: 'Başabaş dönemi',
        uk: 'Період беззбитковості',
        zh: '盈亏平衡期',
        ar: 'فترة التعادل',
        pl: 'Okres progu rentowności',
        it: 'Periodo di pareggio',
        sk: 'Okres progu rentowności',
      }),
      allClear: t({
        ru: 'Всё хорошо',
        en: 'All good',
        kk: 'Бәрі жақсы',
        de: 'Alles in Ordnung',
        fr: 'Tout va bien',
        es: 'Todo bien',
        pt: 'Tudo bem',
        tr: 'Her şey yolunda',
        uk: 'Все добре',
        zh: '一切正常',
        ar: 'كل شيء على ما يرام',
        pl: 'Wszystko w porządku',
        it: 'Tutto bene',
        sk: 'Wszystko w porządku',
      }),
    },
    dataHealth: {
      uncategorized: t({
        ru: 'Без категории',
        en: 'Uncategorized',
        kk: 'Санатсыз',
        de: 'Unkategorisiert',
        fr: 'Non catégorisé',
        es: 'Sin categoría',
        pt: 'Sem categoria',
        tr: 'Kategorisiz',
        uk: 'Без категорії',
        zh: '未分类',
        ar: 'غير مصنّف',
        pl: 'Bez kategorii',
        it: 'Non categorizzato',
        sk: 'Bez kategorii',
      }),
      errors: t({
        ru: 'Ошибки',
        en: 'Errors',
        kk: 'Қателер',
        de: 'Fehler',
        fr: 'Erreurs',
        es: 'Errores',
        pt: 'Erros',
        tr: 'Hatalar',
        uk: 'Помилки',
        zh: '错误',
        ar: 'أخطاء',
        pl: 'Błędy',
        it: 'Errori',
        sk: 'Błędy',
      }),
      pendingReview: t({
        ru: 'На проверке',
        en: 'Pending review',
        kk: 'Тексеруде',
        de: 'Prüfung ausstehend',
        fr: 'En attente de révision',
        es: 'Revisión pendiente',
        pt: 'Revisão pendente',
        tr: 'İnceleme bekliyor',
        uk: 'На перевірці',
        zh: '待审核',
        ar: 'في انتظار المراجعة',
        pl: 'Oczekuje na przegląd',
        it: 'In attesa di revisione',
        sk: 'Oczekuje na przegląd',
      }),
      parsingWarnings: t({
        ru: 'Предупреждения',
        en: 'Parsing warnings',
        kk: 'Ескертулер',
        de: 'Analysewarnungen',
        fr: "Avertissements d'analyse",
        es: 'Advertencias de análisis',
        pt: 'Avisos de análise',
        tr: 'Ayrıştırma uyarıları',
        uk: 'Попередження',
        zh: '解析警告',
        ar: 'تحذيرات التحليل',
        pl: 'Ostrzeżenia parsowania',
        it: 'Avvisi di analisi',
        sk: 'Ostrzeżenia parsowania',
      }),
      balanceOk: t({
        ru: 'Баланс сведён',
        en: 'Balance is balanced',
        kk: 'Баланс теңестірілген',
        de: 'Bilanz ausgeglichen',
        fr: 'Solde équilibré',
        es: 'Saldo equilibrado',
        pt: 'Saldo equilibrado',
        tr: 'Bakiye dengeli',
        uk: 'Баланс зведено',
        zh: '余额平衡',
        ar: 'الرصيد متوازن',
        pl: 'Saldo zbilansowane',
        it: 'Saldo bilanciato',
        sk: 'Saldo zbilansowane',
      }),
      balanceWarning: t({
        ru: 'Баланс не сведён',
        en: 'Balance mismatch',
        kk: 'Баланс сәйкес емес',
        de: 'Bilanzabweichung',
        fr: 'Décalage de solde',
        es: 'Discrepancia de saldo',
        pt: 'Divergência de saldo',
        tr: 'Bakiye uyuşmazlığı',
        uk: 'Баланс не зведено',
        zh: '余额不符',
        ar: 'عدم تطابق الرصيد',
        pl: 'Niezgodność salda',
        it: 'Discrepanza saldo',
        sk: 'Niezgodność salda',
      }),
      noBalance: t({
        ru: 'Баланс не настроен',
        en: 'No balance sheet',
        kk: 'Баланс жоқ',
        de: 'Keine Bilanz',
        fr: 'Pas de bilan',
        es: 'Sin balance',
        pt: 'Sem balanço',
        tr: 'Bilanço yok',
        uk: 'Баланс не налаштовано',
        zh: '无资产负债表',
        ar: 'لا يوجد ميزانية',
        pl: 'Brak bilansu',
        it: 'Nessun bilancio',
        sk: 'Brak bilansu',
      }),
      lastUpload: t({
        ru: 'Последняя загрузка',
        en: 'Last upload',
        kk: 'Соңғы жүктеу',
        de: 'Letzter Upload',
        fr: 'Dernier téléchargement',
        es: 'Última subida',
        pt: 'Último upload',
        tr: 'Son yükleme',
        uk: 'Останнє завантаження',
        zh: '最后上传',
        ar: 'آخر رفع',
        pl: 'Ostatnie przesłanie',
        it: 'Ultimo caricamento',
        sk: 'Ostatnie przesłanie',
      }),
      unapprovedCash: t({
        ru: 'Неподтверждённые',
        en: 'Unapproved cash',
        kk: 'Расталмаған',
        de: 'Nicht genehmigte Einträge',
        fr: 'Espèces non approuvées',
        es: 'Efectivo no aprobado',
        pt: 'Dinheiro não aprovado',
        tr: 'Onaylanmamış nakit',
        uk: 'Непідтверджені',
        zh: '未审批现金',
        ar: 'نقد غير معتمد',
        pl: 'Niezatwierdzone',
        it: 'Contanti non approvati',
        sk: 'Niezatwierdzone',
      }),
    },
    trends: {
      dailyTrend: t({
        ru: 'Ежедневный тренд',
        en: 'Daily trend',
        kk: 'Күнделікті тренд',
        de: 'Täglicher Trend',
        fr: 'Tendance quotidienne',
        es: 'Tendencia diaria',
        pt: 'Tendência diária',
        tr: 'Günlük eğilim',
        uk: 'Щоденний тренд',
        zh: '每日趋势',
        ar: 'الاتجاه اليومي',
        pl: 'Dzienny trend',
        it: 'Tendenza giornaliera',
        sk: 'Dzienny trend',
      }),
      categories: t({
        ru: 'Категории расходов',
        en: 'Expense categories',
        kk: 'Шығыс санаттары',
        de: 'Ausgabenkategorien',
        fr: 'Catégories de dépenses',
        es: 'Categorías de gastos',
        pt: 'Categorias de despesas',
        tr: 'Harcama kategorileri',
        uk: 'Категорії витрат',
        zh: '支出类别',
        ar: 'فئات المصروفات',
        pl: 'Kategorie wydatków',
        it: 'Categorie di spesa',
        sk: 'Kategorie wydatków',
      }),
      counterparties: t({
        ru: 'Доход по контрагентам',
        en: 'Income by counterparty',
        kk: 'Контрагент бойынша түсім',
        de: 'Einnahmen nach Gegenpartei',
        fr: 'Revenus par contrepartie',
        es: 'Ingresos por contraparte',
        pt: 'Receitas por contraparte',
        tr: 'Karşı tarafa göre gelir',
        uk: 'Дохід за контрагентами',
        zh: '按对手方分类收入',
        ar: 'الدخل حسب الطرف المقابل',
        pl: 'Przychód według kontrahentów',
        it: 'Entrate per controparte',
        sk: 'Przychód według kontrahentów',
      }),
      sources: t({
        ru: 'Источники данных',
        en: 'Data sources',
        kk: 'Деректер көздері',
        de: 'Datenquellen',
        fr: 'Sources de données',
        es: 'Fuentes de datos',
        pt: 'Fontes de dados',
        tr: 'Veri kaynakları',
        uk: 'Джерела даних',
        zh: '数据来源',
        ar: 'مصادر البيانات',
        pl: 'Źródła danych',
        it: 'Fonti dei dati',
        sk: 'Źródła danych',
      }),
    },
    topMerchants: {
      title: t({
        ru: 'Топ поставщиков',
        en: 'Top merchants',
        kk: 'Топ жеткізушілер',
        de: 'Top-Händler',
        fr: 'Principaux marchands',
        es: 'Principales comerciantes',
        pt: 'Principais fornecedores',
        tr: 'En iyi satıcılar',
        uk: 'Топ постачальників',
        zh: '顶级商户',
        ar: 'أبرز التجار',
        pl: 'Najlepsi dostawcy',
        it: 'Principali fornitori',
        sk: 'Najlepsi dostawcy',
      }),
      empty: t({
        ru: 'Нет данных по поставщикам',
        en: 'No merchant data',
        kk: 'Жеткізушілер деректері жоқ',
        de: 'Keine Händlerdaten',
        fr: 'Aucune donnée de marchand',
        es: 'Sin datos de comerciantes',
        pt: 'Sem dados de fornecedores',
        tr: 'Satıcı verisi yok',
        uk: 'Немає даних по постачальниках',
        zh: '没有商户数据',
        ar: 'لا توجد بيانات تجار',
        pl: 'Brak danych dostawców',
        it: 'Nessun dato sui fornitori',
        sk: 'Brak danych dostawców',
      }),
    },
    topCategories: {
      title: t({
        ru: 'Топ категорий',
        en: 'Top categories',
        kk: 'Топ санаттар',
        de: 'Top-Kategorien',
        fr: 'Principales catégories',
        es: 'Principales categorías',
        pt: 'Principais categorias',
        tr: 'En iyi kategoriler',
        uk: 'Топ категорій',
        zh: '顶级类别',
        ar: 'أبرز الفئات',
        pl: 'Najlepsze kategorie',
        it: 'Categorie principali',
        sk: 'Najlepsze kategorie',
      }),
      empty: t({
        ru: 'Нет данных по категориям',
        en: 'No category data',
        kk: 'Санаттар деректері жоқ',
        de: 'Keine Kategoriedaten',
        fr: 'Aucune donnée de catégorie',
        es: 'Sin datos de categorías',
        pt: 'Sem dados de categorias',
        tr: 'Kategori verisi yok',
        uk: 'Немає даних по категоріях',
        zh: '没有类别数据',
        ar: 'لا توجد بيانات فئات',
        pl: 'Brak danych kategorii',
        it: 'Nessun dato sulle categorie',
        sk: 'Brak danych kategorii',
      }),
    },
    emptyState: {
      title: t({
        ru: 'Добро пожаловать в ваш дашборд',
        en: 'Welcome to your dashboard',
        kk: 'Дашбордыңызға қош келдіңіз',
        de: 'Willkommen in Ihrem Dashboard',
        fr: 'Bienvenue sur votre tableau de bord',
        es: 'Bienvenido a tu panel',
        pt: 'Bem-vindo ao seu painel',
        tr: 'Gösterge panelinize hoş geldiniz',
        uk: 'Ласкаво просимо до вашого дашборду',
        zh: '欢迎来到您的仪表板',
        ar: 'مرحباً بك في لوحة التحكم الخاصة بك',
        pl: 'Witaj na swoim pulpicie',
        it: 'Benvenuto nella tua dashboard',
        sk: 'Witaj na swoim pulpicie',
      }),
      description: t({
        ru: 'Начните с первых документов или расходов, чтобы увидеть живую картину финансов.',
        en: 'Add your first documents or expenses to see real financial activity here.',
        kk: 'Қаржылық белсенділікті көру үшін алғашқы құжаттарды немесе шығындарды қосыңыз.',
        de: 'Fügen Sie Ihre ersten Dokumente oder Ausgaben hinzu, um echte Finanzaktivitäten zu sehen.',
        fr: "Ajoutez vos premiers documents ou dépenses pour voir l'activité financière réelle ici.",
        es: 'Agrega tus primeros documentos o gastos para ver la actividad financiera real aquí.',
        pt: 'Adicione seus primeiros documentos ou despesas para ver a atividade financeira real aqui.',
        tr: 'Gerçek finansal aktiviteyi görmek için ilk belgelerinizi veya harcamalarınızı ekleyin.',
        uk: 'Додайте перші документи або витрати, щоб побачити реальну картину фінансів.',
        zh: '添加您的第一批文件或费用，在此查看真实的财务活动。',
        ar: 'أضف أول مستنداتك أو مصروفاتك لرؤية النشاط المالي الفعلي هنا.',
        pl: 'Dodaj pierwsze dokumenty lub wydatki, aby zobaczyć tu rzeczywistą aktywność finansową.',
        it: "Aggiungi i tuoi primi documenti o spese per vedere l'attività finanziaria reale qui.",
        sk: 'Dodaj pierwsze dokumenty lub wydatki, aby zobaczyć tu rzeczywistą aktywność finansową.',
      }),
      upload: t({
        ru: 'Загрузить первую выписку',
        en: 'Upload your first statement',
        kk: 'Алғашқы үзіндіні жүктеу',
        de: 'Ersten Kontoauszug hochladen',
        fr: 'Télécharger votre premier relevé',
        es: 'Subir tu primer extracto',
        pt: 'Carregar seu primeiro extrato',
        tr: 'İlk hesap özetini yükle',
        uk: 'Завантажити першу виписку',
        zh: '上传您的第一份对账单',
        ar: 'رفع أول كشف حساب',
        pl: 'Prześlij pierwszy wyciąg',
        it: 'Carica il tuo primo estratto conto',
        sk: 'Prześlij pierwszy wyciąg',
      }),
      gmail: t({
        ru: 'Подключить Gmail',
        en: 'Connect Gmail',
        kk: 'Gmail қосу',
        de: 'Gmail verbinden',
        fr: 'Connecter Gmail',
        es: 'Conectar Gmail',
        pt: 'Conectar Gmail',
        tr: "Gmail'i bağla",
        uk: 'Підключити Gmail',
        zh: '连接 Gmail',
        ar: 'ربط Gmail',
        pl: 'Połącz Gmail',
        it: 'Collega Gmail',
        sk: 'Połącz Gmail',
      }),
      manual: t({
        ru: 'Добавить расход вручную',
        en: 'Add manual expense',
        kk: 'Қолмен шығын қосу',
        de: 'Ausgabe manuell hinzufügen',
        fr: 'Ajouter une dépense manuellement',
        es: 'Agregar gasto manual',
        pt: 'Adicionar despesa manual',
        tr: 'Manuel harcama ekle',
        uk: 'Додати витрату вручну',
        zh: '手动添加费用',
        ar: 'إضافة مصروف يدوياً',
        pl: 'Dodaj wydatek ręcznie',
        it: 'Aggiungi spesa manuale',
        sk: 'Dodaj wydatek ręcznie',
      }),
      step1Label: t({
        ru: 'Загрузите выписку или добавьте расход',
        en: 'Upload a statement or add an expense',
        kk: 'Үзінді жүктеп немесе шығын қосыңыз',
        de: 'Laden Sie einen Kontoauszug hoch oder fügen Sie eine Ausgabe hinzu',
        fr: 'Téléchargez un relevé ou ajoutez une dépense',
        es: 'Sube un extracto o agrega un gasto',
        pt: 'Carregue um extrato ou adicione uma despesa',
        tr: 'Bir hesap özeti yükleyin veya harcama ekleyin',
        uk: 'Завантажте виписку або додайте витрату',
        zh: '上传对账单或添加费用',
        ar: 'ارفع كشف حساب أو أضف مصروفاً',
        pl: 'Prześlij wyciąg lub dodaj wydatek',
        it: 'Carica un estratto conto o aggiungi una spesa',
        sk: 'Prześlij wyciąg lub dodaj wydatek',
      }),
      step2Label: t({
        ru: 'Мы автоматически распарсим и категоризируем',
        en: 'We auto-parse and categorize your data',
        kk: 'Деректеріңізді автоматты талдаймыз',
        de: 'Wir analysieren und kategorisieren Ihre Daten automatisch',
        fr: 'Nous analysons et catégorisons automatiquement vos données',
        es: 'Analizamos y categorizamos tus datos automáticamente',
        pt: 'Analisamos e categorizamos seus dados automaticamente',
        tr: 'Verilerinizi otomatik olarak ayrıştırıp kategorize ediyoruz',
        uk: 'Ми автоматично розберемо та категоризуємо дані',
        zh: '我们自动解析并分类您的数据',
        ar: 'نقوم تلقائياً بتحليل بياناتك وتصنيفها',
        pl: 'Automatycznie parsujemy i kategoryzujemy Twoje dane',
        it: 'Analizziamo e categorizziamo automaticamente i tuoi dati',
        sk: 'Automatycznie parsujemy i kategoryzujemy Twoje dane',
      }),
      step3Label: t({
        ru: 'Анализируйте финансы в реальном времени',
        en: 'Analyze your finances in real time',
        kk: 'Қаржыны нақты уақытта талдаңыз',
        de: 'Analysieren Sie Ihre Finanzen in Echtzeit',
        fr: 'Analysez vos finances en temps réel',
        es: 'Analiza tus finanzas en tiempo real',
        pt: 'Analise suas finanças em tempo real',
        tr: 'Finanslarınızı gerçek zamanlı analiz edin',
        uk: 'Аналізуйте фінанси в реальному часі',
        zh: '实时分析您的财务状况',
        ar: 'حلّل أموالك في الوقت الفعلي',
        pl: 'Analizuj swoje finanse w czasie rzeczywistym',
        it: 'Analizza le tue finanze in tempo reale',
        sk: 'Analizuj swoje finanse w czasie rzeczywistym',
      }),
    },
  },
} satisfies Dictionary;

export default content;
