import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTablesImportGoogleSheetsPage',
  content: {
    toasts: {
      loadConnectionsFailed: t({
        ru: 'Не удалось загрузить Google Sheets подключения',
        en: 'Failed to load Google Sheets connections',
        kk: 'Google Sheets қосылымдарын жүктеу мүмкін болмады',
        de: 'Google Sheets-Verbindungen konnten nicht geladen werden',
        fr: 'Impossible de charger les connexions Google Sheets',
        es: 'No se pudieron cargar las conexiones de Google Sheets',
        pt: 'Falha ao carregar conexões do Google Sheets',
        tr: 'Google Sheets bağlantıları yüklenemedi',
        uk: 'Не вдалося завантажити підключення Google Sheets',
        zh: '加载 Google 表格连接失败',
        ar: 'فشل تحميل اتصالات Google Sheets',
        pl: 'Nie udało się załadować połączeń Google Sheets',
        it: 'Impossibile caricare le connessioni di Google Sheets',
      }),
      oauthRequired: t({
        ru: 'Подключение Google Sheets требует OAuth. Переподключите таблицу в разделе «Интеграции».',
        en: 'Google Sheets connection requires OAuth. Reconnect it in the "Integrations" section.',
        kk: 'Google Sheets қосылымы OAuth талап етеді. «Интеграциялар» бөлімінде қайта қосыңыз.',
        de: 'Die Google Sheets-Verbindung erfordert OAuth. Stellen Sie sie im Abschnitt „Integrationen" erneut her.',
        fr: 'La connexion Google Sheets nécessite OAuth. Reconnectez-la dans la section « Intégrations ».',
        es: 'La conexión de Google Sheets requiere OAuth. Reconéctela en la sección "Integraciones".',
        pt: 'A conexão do Google Sheets requer OAuth. Reconecte-a na seção "Integrações".',
        tr: 'Google Sheets bağlantısı OAuth gerektirir. "Entegrasyonlar" bölümünde yeniden bağlayın.',
        uk: 'Підключення Google Sheets вимагає OAuth. Перепідключіть у розділі «Інтеграції».',
        zh: 'Google 表格连接需要 OAuth。请在"集成"部分重新连接。',
        ar: 'يتطلب اتصال Google Sheets OAuth. أعد الاتصال في قسم "التكاملات".',
        pl: 'Połączenie Google Sheets wymaga OAuth. Połącz ponownie w sekcji "Integracje".',
        it: 'La connessione Google Sheets richiede OAuth. Ricollegala nella sezione "Integrazioni".',
      }),
      previewReady: t({ ru: 'Превью готово', en: 'Preview is ready', kk: 'Превью дайын', de: 'Vorschau ist bereit', fr: 'L\'aperçu est prêt', es: 'La vista previa está lista', pt: 'A pré-visualização está pronta', tr: 'Önizleme hazır', uk: 'Попередній перегляд готовий', zh: '预览已就绪', ar: 'المعاينة جاهزة', pl: 'Podgląd jest gotowy', it: 'L\'anteprima è pronta' }),
      previewFailed: t({
        ru: 'Не удалось получить превью',
        en: 'Failed to get preview',
        kk: 'Превью алу мүмкін болмады',
        de: 'Vorschau konnte nicht abgerufen werden',
        fr: 'Impossible d\'obtenir l\'aperçu',
        es: 'No se pudo obtener la vista previa',
        pt: 'Falha ao obter pré-visualização',
        tr: 'Önizleme alınamadı',
        uk: 'Не вдалося отримати попередній перегляд',
        zh: '获取预览失败',
        ar: 'فشل الحصول على المعاينة',
        pl: 'Nie udało się uzyskać podglądu',
        it: 'Impossibile ottenere l\'anteprima',
      }),
      importStartFailed: t({
        ru: 'Не удалось запустить импорт',
        en: 'Failed to start import',
        kk: 'Импортты бастау мүмкін болмады',
        de: 'Import konnte nicht gestartet werden',
        fr: 'Impossible de démarrer l\'importation',
        es: 'No se pudo iniciar la importación',
        pt: 'Falha ao iniciar a importação',
        tr: 'İçe aktarma başlatılamadı',
        uk: 'Не вдалося запустити імпорт',
        zh: '启动导入失败',
        ar: 'فشل بدء الاستيراد',
        pl: 'Nie udało się uruchomić importu',
        it: 'Impossibile avviare l\'importazione',
      }),
      importStarted: t({ ru: 'Импорт запущен', en: 'Import started', kk: 'Импорт басталды', de: 'Import gestartet', fr: 'Importation démarrée', es: 'Importación iniciada', pt: 'Importação iniciada', tr: 'İçe aktarma başladı', uk: 'Імпорт запущено', zh: '导入已开始', ar: 'بدأ الاستيراد', pl: 'Import uruchomiony', it: 'Importazione avviata' }),
      importFailed: t({
        ru: 'Не удалось выполнить импорт',
        en: 'Import failed',
        kk: 'Импорт орындалмады',
        de: 'Import fehlgeschlagen',
        fr: 'L\'importation a échoué',
        es: 'La importación falló',
        pt: 'A importação falhou',
        tr: 'İçe aktarma başarısız oldu',
        uk: 'Імпорт не вдався',
        zh: '导入失败',
        ar: 'فشل الاستيراد',
        pl: 'Import nie powiódł się',
        it: 'Importazione fallita',
      }),
      importDone: t({ ru: 'Импорт завершён', en: 'Import completed', kk: 'Импорт аяқталды', de: 'Import abgeschlossen', fr: 'Importation terminée', es: 'Importación completada', pt: 'Importação concluída', tr: 'İçe aktarma tamamlandı', uk: 'Імпорт завершено', zh: '导入已完成', ar: 'اكتمل الاستيراد', pl: 'Import zakończony', it: 'Importazione completata' }),
      importError: t({
        ru: 'Импорт завершился с ошибкой',
        en: 'Import finished with an error',
        kk: 'Импорт қателікпен аяқталды',
        de: 'Import mit einem Fehler abgeschlossen',
        fr: 'L\'importation s\'est terminée avec une erreur',
        es: 'La importación terminó con un error',
        pt: 'A importação terminou com um erro',
        tr: 'İçe aktarma bir hatayla tamamlandı',
        uk: 'Імпорт завершився з помилкою',
        zh: '导入完成但有错误',
        ar: 'انتهى الاستيراد بخطأ',
        pl: 'Import zakończył się błędem',
        it: 'Importazione terminata con un errore',
      }),
    },
    defaults: {
      tableName: t({
        ru: 'Импорт из Google Sheets',
        en: 'Import from Google Sheets',
        kk: 'Google Sheets-тен импорт',
        de: 'Import aus Google Sheets',
        fr: 'Import depuis Google Sheets',
        es: 'Importación desde Google Sheets',
        pt: 'Importação do Google Sheets',
        tr: 'Google Sheets\'ten içe aktarma',
        uk: 'Імпорт з Google Sheets',
        zh: '从 Google 表格导入',
        ar: 'استيراد من Google Sheets',
        pl: 'Import z Google Sheets',
        it: 'Importazione da Google Sheets',
      }),
    },
    auth: {
      loginRequired: t({
        ru: 'Войдите в систему, чтобы импортировать таблицу.',
        en: 'Log in to import a table.',
        kk: 'Кестені импорттау үшін жүйеге кіріңіз.',
        de: 'Melden Sie sich an, um eine Tabelle zu importieren.',
        fr: 'Connectez-vous pour importer un tableau.',
        es: 'Inicie sesión para importar una tabla.',
        pt: 'Faça login para importar uma tabela.',
        tr: 'Tablo içe aktarmak için giriş yapın.',
        uk: 'Увійдіть, щоб імпортувати таблицю.',
        zh: '登录以导入表格。',
        ar: 'قم بتسجيل الدخول لاستيراد جدول.',
        pl: 'Zaloguj się, aby zaimportować tabelę.',
        it: 'Accedi per importare una tabella.',
      }),
    },
    header: {
      title: t({
        ru: 'Импорт из Google Sheets',
        en: 'Import from Google Sheets',
        kk: 'Google Sheets-тен импорт',
        de: 'Import aus Google Sheets',
        fr: 'Import depuis Google Sheets',
        es: 'Importación desde Google Sheets',
        pt: 'Importação do Google Sheets',
        tr: 'Google Sheets\'ten içe aktarma',
        uk: 'Імпорт з Google Sheets',
        zh: '从 Google 表格导入',
        ar: 'استيراد من Google Sheets',
        pl: 'Import z Google Sheets',
        it: 'Importazione da Google Sheets',
      }),
      subtitle: t({
        ru: 'Превью → настройка колонок → импорт в автономную таблицу Lumio.',
        en: 'Preview → configure columns → import into a standalone Lumio table.',
        kk: 'Превью → бағандарды баптау → Lumio автономды кестесіне импорттау.',
        de: 'Vorschau → Spalten konfigurieren → in eigenständige Lumio-Tabelle importieren.',
        fr: 'Aperçu → configurer les colonnes → importer dans un tableau Lumio autonome.',
        es: 'Vista previa → configurar columnas → importar en una tabla Lumio independiente.',
        pt: 'Pré-visualização → configurar colunas → importar para uma tabela Lumio independente.',
        tr: 'Önizleme → sütunları yapılandır → bağımsız bir Lumio tablosuna aktar.',
        uk: 'Перегляд → налаштування стовпців → імпорт у автономну таблицю Lumio.',
        zh: '预览 → 配置列 → 导入到独立的 Lumio 表格。',
        ar: 'معاينة → تكوين الأعمدة → استيراد إلى جدول Lumio مستقل.',
        pl: 'Podgląd → konfiguracja kolumn → import do autonomicznej tabeli Lumio.',
        it: 'Anteprima → configura colonne → importa in una tabella Lumio autonoma.',
      }),
      back: t({ ru: 'Назад', en: 'Back', kk: 'Артқа', de: 'Zurück', fr: 'Retour', es: 'Atrás', pt: 'Voltar', tr: 'Geri', uk: 'Назад', zh: '返回', ar: 'رجوع', pl: 'Wstecz', it: 'Indietro' }),
    },
    source: {
      title: t({ ru: 'Источник', en: 'Source', kk: 'Дереккөз', de: 'Quelle', fr: 'Source', es: 'Fuente', pt: 'Fonte', tr: 'Kaynak', uk: 'Джерело', zh: '来源', ar: 'المصدر', pl: 'Źródło', it: 'Fonte' }),
      connectionLabel: t({
        ru: 'Подключение Google Sheet',
        en: 'Google Sheet connection',
        kk: 'Google Sheet қосылымы',
        de: 'Google Sheet-Verbindung',
        fr: 'Connexion Google Sheet',
        es: 'Conexión de Google Sheet',
        pt: 'Conexão do Google Sheet',
        tr: 'Google Sheet bağlantısı',
        uk: 'Підключення Google Sheet',
        zh: 'Google 表格连接',
        ar: 'اتصال Google Sheet',
        pl: 'Połączenie Google Sheet',
        it: 'Connessione Google Sheet',
      }),
      selectPlaceholder: t({ ru: '— выберите —', en: '— select —', kk: '— таңдаңыз —', de: '— auswählen —', fr: '— sélectionner —', es: '— seleccionar —', pt: '— selecionar —', tr: '— seçin —', uk: '— оберіть —', zh: '— 请选择 —', ar: '— اختر —', pl: '— wybierz —', it: '— seleziona —' }),
      emptyHint: t({
        ru: 'Сначала подключите Google аккаунт и выберите таблицу в интеграции Google Sheets.',
        en: 'First connect your Google account and choose a spreadsheet in Google Sheets integration.',
        kk: 'Алдымен Google аккаунтын қосып, Google Sheets интеграциясында кестені таңдаңыз.',
        de: 'Verbinden Sie zuerst Ihr Google-Konto und wählen Sie eine Tabelle in der Google Sheets-Integration.',
        fr: 'Connectez d\'abord votre compte Google et choisissez une feuille de calcul dans l\'intégration Google Sheets.',
        es: 'Primero conecte su cuenta de Google y elija una hoja de cálculo en la integración de Google Sheets.',
        pt: 'Primeiro conecte sua conta Google e escolha uma planilha na integração do Google Sheets.',
        tr: 'Önce Google hesabınızı bağlayın ve Google Sheets entegrasyonunda bir elektronik tablo seçin.',
        uk: 'Спочатку підключіть обліковий запис Google і виберіть таблицю в інтеграції Google Sheets.',
        zh: '首先连接您的 Google 账户并在 Google 表格集成中选择电子表格。',
        ar: 'أولاً قم بتوصيل حساب Google الخاص بك واختر جدول بيانات في تكامل Google Sheets.',
        pl: 'Najpierw podłącz konto Google i wybierz arkusz kalkulacyjny w integracji Google Sheets.',
        it: 'Prima connetti il tuo account Google e scegli un foglio di calcolo nell\'integrazione Google Sheets.',
      }),
      emptyAction: t({
        ru: 'Открыть интеграцию',
        en: 'Open integration',
        kk: 'Интеграцияны ашу',
        de: 'Integration öffnen',
        fr: 'Ouvrir l\'intégration',
        es: 'Abrir integración',
        pt: 'Abrir integração',
        tr: 'Entegrasyonu aç',
        uk: 'Відкрити інтеграцію',
        zh: '打开集成',
        ar: 'فتح التكامل',
        pl: 'Otwórz integrację',
        it: 'Apri integrazione',
      }),
      oauthNeededSuffix: t({ ru: ' (нужна OAuth)', en: ' (OAuth required)', kk: ' (OAuth қажет)', de: ' (OAuth erforderlich)', fr: ' (OAuth requis)', es: ' (OAuth requerido)', pt: ' (OAuth necessário)', tr: ' (OAuth gerekli)', uk: ' (потрібен OAuth)', zh: '（需要 OAuth）', ar: ' (مطلوب OAuth)', pl: ' (wymagany OAuth)', it: ' (OAuth richiesto)' }),
      worksheetLabel: t({ ru: 'Лист (worksheet)', en: 'Worksheet', kk: 'Парақ (worksheet)', de: 'Arbeitsblatt', fr: 'Feuille de calcul', es: 'Hoja de cálculo', pt: 'Planilha', tr: 'Çalışma sayfası', uk: 'Аркуш (worksheet)', zh: '工作表', ar: 'ورقة العمل', pl: 'Arkusz roboczy', it: 'Foglio di lavoro' }),
      worksheetPlaceholder: t({
        ru: 'Выберите лист',
        en: 'Choose worksheet',
        kk: 'Парақты таңдаңыз',
        de: 'Arbeitsblatt auswählen',
        fr: 'Choisir une feuille',
        es: 'Elegir hoja de cálculo',
        pt: 'Escolher planilha',
        tr: 'Çalışma sayfası seçin',
        uk: 'Виберіть аркуш',
        zh: '选择工作表',
        ar: 'اختر ورقة العمل',
        pl: 'Wybierz arkusz',
        it: 'Scegli foglio di lavoro',
      }),
      worksheetLoading: t({
        ru: 'Загружаем листы…',
        en: 'Loading worksheets…',
        kk: 'Парақтар жүктелуде…',
        de: 'Arbeitsblätter werden geladen…',
        fr: 'Chargement des feuilles…',
        es: 'Cargando hojas…',
        pt: 'Carregando planilhas…',
        tr: 'Çalışma sayfaları yükleniyor…',
        uk: 'Завантаження аркушів…',
        zh: '正在加载工作表…',
        ar: 'جارٍ تحميل أوراق العمل…',
        pl: 'Ładowanie arkuszy…',
        it: 'Caricamento fogli di lavoro…',
      }),
      worksheetHelp: t({
        ru: 'Если список пустой, будет использован лист из подключения или первый лист таблицы.',
        en: 'If the list is empty, Lumio uses the worksheet from the connection or the first sheet.',
        kk: 'Тізім бос болса, Lumio қосылымдағы парақты немесе кестенің бірінші парағын қолданады.',
        de: 'Wenn die Liste leer ist, verwendet Lumio das Arbeitsblatt aus der Verbindung oder das erste Blatt.',
        fr: 'Si la liste est vide, Lumio utilise la feuille de la connexion ou la première feuille.',
        es: 'Si la lista está vacía, Lumio usa la hoja de la conexión o la primera hoja.',
        pt: 'Se a lista estiver vazia, o Lumio usa a planilha da conexão ou a primeira planilha.',
        tr: 'Liste boşsa Lumio, bağlantıdaki çalışma sayfasını veya ilk sayfayı kullanır.',
        uk: 'Якщо список порожній, Lumio використовує аркуш із підключення або перший аркуш таблиці.',
        zh: '如果列表为空，Lumio 将使用连接中的工作表或第一个工作表。',
        ar: 'إذا كانت القائمة فارغة، يستخدم Lumio ورقة العمل من الاتصال أو الورقة الأولى.',
        pl: 'Jeśli lista jest pusta, Lumio używa arkusza z połączenia lub pierwszego arkusza.',
        it: 'Se la lista è vuota, Lumio usa il foglio di lavoro dalla connessione o il primo foglio.',
      }),
      rangeLabel: t({
        ru: 'Range (опционально)',
        en: 'Range (optional)',
        kk: 'Range (міндетті емес)',
        de: 'Bereich (optional)',
        fr: 'Plage (facultatif)',
        es: 'Rango (opcional)',
        pt: 'Intervalo (opcional)',
        tr: 'Aralık (isteğe bağlı)',
        uk: 'Діапазон (необов\'язково)',
        zh: '范围（可选）',
        ar: 'النطاق (اختياري)',
        pl: 'Zakres (opcjonalnie)',
        it: 'Intervallo (facoltativo)',
      }),
      rangePlaceholder: t({ ru: 'Например: A1:Z200', en: 'e.g. A1:Z200', kk: 'Мысалы: A1:Z200', de: 'z.B. A1:Z200', fr: 'ex. A1:Z200', es: 'ej. A1:Z200', pt: 'ex. A1:Z200', tr: 'örn. A1:Z200', uk: 'Наприклад: A1:Z200', zh: '例如：A1:Z200', ar: 'مثال: A1:Z200', pl: 'np. A1:Z200', it: 'es. A1:Z200' }),
      headerOffsetLabel: t({
        ru: 'Header row offset',
        en: 'Header row offset',
        kk: 'Header row offset',
        de: 'Header-Zeilen-Offset',
        fr: 'Décalage de la ligne d\'en-tête',
        es: 'Desplazamiento de fila de encabezado',
        pt: 'Deslocamento da linha de cabeçalho',
        tr: 'Başlık satırı ofseti',
        uk: 'Зміщення рядка заголовка',
        zh: '标题行偏移',
        ar: 'إزاحة صف الرأس',
        pl: 'Przesunięcie wiersza nagłówka',
        it: 'Offset riga intestazione',
      }),
      headerOffsetHelp: t({
        ru: '0 = первая строка used range',
        en: '0 = first row of used range',
        kk: '0 = used range бірінші жолы',
        de: '0 = erste Zeile des verwendeten Bereichs',
        fr: '0 = première ligne de la plage utilisée',
        es: '0 = primera fila del rango usado',
        pt: '0 = primeira linha do intervalo utilizado',
        tr: '0 = kullanılan aralığın ilk satırı',
        uk: '0 = перший рядок використовуваного діапазону',
        zh: '0 = 已使用范围的第一行',
        ar: '0 = الصف الأول من النطاق المستخدم',
        pl: '0 = pierwszy wiersz używanego zakresu',
        it: '0 = prima riga dell\'intervallo utilizzato',
      }),
      layoutLabel: t({ ru: 'Layout', en: 'Layout', kk: 'Layout', de: 'Layout', fr: 'Disposition', es: 'Diseño', pt: 'Layout', tr: 'Düzen', uk: 'Макет', zh: '布局', ar: 'التخطيط', pl: 'Układ', it: 'Layout' }),
      layoutAuto: t({ ru: 'Авто', en: 'Auto', kk: 'Авто', de: 'Auto', fr: 'Auto', es: 'Auto', pt: 'Auto', tr: 'Otomatik', uk: 'Авто', zh: '自动', ar: 'تلقائي', pl: 'Auto', it: 'Auto' }),
      layoutFlat: t({ ru: 'Плоский', en: 'Flat', kk: 'Жай', de: 'Flach', fr: 'Plat', es: 'Plano', pt: 'Plano', tr: 'Düz', uk: 'Плаский', zh: '平面', ar: 'مسطح', pl: 'Płaski', it: 'Piatto' }),
      layoutMatrix: t({ ru: 'Матрица', en: 'Matrix', kk: 'Матрица', de: 'Matrix', fr: 'Matrice', es: 'Matriz', pt: 'Matriz', tr: 'Matris', uk: 'Матриця', zh: '矩阵', ar: 'مصفوفة', pl: 'Macierz', it: 'Matrice' }),
      previewButton: t({ ru: 'Сделать превью', en: 'Make preview', kk: 'Превью жасау', de: 'Vorschau erstellen', fr: 'Créer un aperçu', es: 'Crear vista previa', pt: 'Criar pré-visualização', tr: 'Önizleme oluştur', uk: 'Зробити попередній перегляд', zh: '生成预览', ar: 'إنشاء معاينة', pl: 'Utwórz podgląd', it: 'Crea anteprima' }),
      loadingConnections: t({
        ru: 'Загружаем подключения…',
        en: 'Loading connections…',
        kk: 'Қосылымдар жүктелуде…',
        de: 'Verbindungen werden geladen…',
        fr: 'Chargement des connexions…',
        es: 'Cargando conexiones…',
        pt: 'Carregando conexões…',
        tr: 'Bağlantılar yükleniyor…',
        uk: 'Завантаження підключень…',
        zh: '正在加载连接…',
        ar: 'جارٍ تحميل الاتصالات…',
        pl: 'Ładowanie połączeń…',
        it: 'Caricamento connessioni…',
      }),
      previewButtonLoading: t({ ru: 'Загрузка...', en: 'Loading...', kk: 'Жүктелуде...', de: 'Laden...', fr: 'Chargement...', es: 'Cargando...', pt: 'Carregando...', tr: 'Yükleniyor...', uk: 'Завантаження...', zh: '加载中...', ar: 'جارٍ التحميل...', pl: 'Ładowanie...', it: 'Caricamento...' }),
    },
    result: {
      title: t({ ru: 'Результат', en: 'Result', kk: 'Нәтиже', de: 'Ergebnis', fr: 'Résultat', es: 'Resultado', pt: 'Resultado', tr: 'Sonuç', uk: 'Результат', zh: '结果', ar: 'النتيجة', pl: 'Wynik', it: 'Risultato' }),
      tableNameLabel: t({ ru: 'Название таблицы', en: 'Table name', kk: 'Кесте атауы', de: 'Tabellenname', fr: 'Nom du tableau', es: 'Nombre de la tabla', pt: 'Nome da tabela', tr: 'Tablo adı', uk: 'Назва таблиці', zh: '表格名称', ar: 'اسم الجدول', pl: 'Nazwa tabeli', it: 'Nome della tabella' }),
      tableNamePlaceholder: t({
        ru: 'Например: Реестр платежей',
        en: 'e.g. Payments registry',
        kk: 'Мысалы: Төлемдер тізілімі',
        de: 'z.B. Zahlungsregister',
        fr: 'ex. Registre des paiements',
        es: 'ej. Registro de pagos',
        pt: 'ex. Registro de pagamentos',
        tr: 'örn. Ödeme kaydı',
        uk: 'Наприклад: Реєстр платежів',
        zh: '例如：付款记录',
        ar: 'مثال: سجل المدفوعات',
        pl: 'np. Rejestr płatności',
        it: 'es. Registro dei pagamenti',
      }),
      descriptionLabel: t({
        ru: 'Описание (опционально)',
        en: 'Description (optional)',
        kk: 'Сипаттама (міндетті емес)',
        de: 'Beschreibung (optional)',
        fr: 'Description (facultatif)',
        es: 'Descripción (opcional)',
        pt: 'Descrição (opcional)',
        tr: 'Açıklama (isteğe bağlı)',
        uk: 'Опис (необов\'язково)',
        zh: '描述（可选）',
        ar: 'الوصف (اختياري)',
        pl: 'Opis (opcjonalnie)',
        it: 'Descrizione (facoltativo)',
      }),
      categoryLabel: t({
        ru: 'Категория (иконка/цвет)',
        en: 'Category (icon/color)',
        kk: 'Санат (иконка/түс)',
        de: 'Kategorie (Symbol/Farbe)',
        fr: 'Catégorie (icône/couleur)',
        es: 'Categoría (icono/color)',
        pt: 'Categoria (ícone/cor)',
        tr: 'Kategori (ikon/renk)',
        uk: 'Категорія (іконка/колір)',
        zh: '类别（图标/颜色）',
        ar: 'الفئة (أيقونة/لون)',
        pl: 'Kategoria (ikona/kolor)',
        it: 'Categoria (icona/colore)',
      }),
      noCategory: t({ ru: 'Без категории', en: 'No category', kk: 'Санатсыз', de: 'Keine Kategorie', fr: 'Sans catégorie', es: 'Sin categoría', pt: 'Sem categoria', tr: 'Kategori yok', uk: 'Без категорії', zh: '无类别', ar: 'بدون فئة', pl: 'Bez kategorii', it: 'Nessuna categoria' }),
      categoryHint: t({
        ru: 'Иконка/цвет будут взяты из категории',
        en: 'Icon/color will be taken from category',
        kk: 'Иконка/түс санаттан алынады',
        de: 'Symbol/Farbe wird aus der Kategorie übernommen',
        fr: 'L\'icône/couleur sera prise depuis la catégorie',
        es: 'El icono/color se tomará de la categoría',
        pt: 'O ícone/cor será retirado da categoria',
        tr: 'İkon/renk kategoriden alınacak',
        uk: 'Іконка/колір буде взята з категорії',
        zh: '图标/颜色将从类别中获取',
        ar: 'سيتم أخذ الأيقونة/اللون من الفئة',
        pl: 'Ikona/kolor zostanie pobrana z kategorii',
        it: 'L\'icona/colore verrà presa dalla categoria',
      }),
      importDataCheckbox: t({
        ru: 'Импортировать данные (кроме заголовка)',
        en: 'Import data (except header)',
        kk: 'Деректерді импорттау (тақырыптан басқа)',
        de: 'Daten importieren (außer Kopfzeile)',
        fr: 'Importer les données (sauf l\'en-tête)',
        es: 'Importar datos (excepto encabezado)',
        pt: 'Importar dados (exceto cabeçalho)',
        tr: 'Verileri içe aktar (başlık hariç)',
        uk: 'Імпортувати дані (крім заголовка)',
        zh: '导入数据（不含标题）',
        ar: 'استيراد البيانات (باستثناء الرأس)',
        pl: 'Importuj dane (z wyjątkiem nagłówka)',
        it: 'Importa dati (esclusa l\'intestazione)',
      }),
      importButton: t({ ru: 'Импортировать', en: 'Import', kk: 'Импорттау', de: 'Importieren', fr: 'Importer', es: 'Importar', pt: 'Importar', tr: 'İçe aktar', uk: 'Імпортувати', zh: '导入', ar: 'استيراد', pl: 'Importuj', it: 'Importa' }),
      importRunning: t({
        ru: 'Импорт выполняется…',
        en: 'Import is running…',
        kk: 'Импорт орындалуда…',
        de: 'Import wird ausgeführt…',
        fr: 'L\'importation est en cours…',
        es: 'La importación está en curso…',
        pt: 'A importação está em andamento…',
        tr: 'İçe aktarma çalışıyor…',
        uk: 'Імпорт виконується…',
        zh: '导入正在进行中…',
        ar: 'جارٍ تشغيل الاستيراد…',
        pl: 'Import jest w toku…',
        it: 'L\'importazione è in corso…',
      }),
      progressTitle: t({ ru: 'Прогресс', en: 'Progress', kk: 'Үдеріс', de: 'Fortschritt', fr: 'Progression', es: 'Progreso', pt: 'Progresso', tr: 'İlerleme', uk: 'Прогрес', zh: '进度', ar: 'التقدم', pl: 'Postęp', it: 'Progresso' }),
      statusLabel: t({ ru: 'Статус', en: 'Status', kk: 'Күйі', de: 'Status', fr: 'Statut', es: 'Estado', pt: 'Status', tr: 'Durum', uk: 'Статус', zh: '状态', ar: 'الحالة', pl: 'Status', it: 'Stato' }),
      needPreviewHint: t({
        ru: 'Сначала сделайте превью.',
        en: 'Make a preview first.',
        kk: 'Алдымен превью жасаңыз.',
        de: 'Erstellen Sie zuerst eine Vorschau.',
        fr: 'Créez d\'abord un aperçu.',
        es: 'Primero cree una vista previa.',
        pt: 'Primeiro crie uma pré-visualização.',
        tr: 'Önce önizleme oluşturun.',
        uk: 'Спочатку зробіть попередній перегляд.',
        zh: '请先生成预览。',
        ar: 'قم بإنشاء معاينة أولاً.',
        pl: 'Najpierw utwórz podgląd.',
        it: 'Prima crea un\'anteprima.',
      }),
      dash: t({ ru: '—', en: '—', kk: '—', de: '—', fr: '—', es: '—', pt: '—', tr: '—', uk: '—', zh: '—', ar: '—', pl: '—', it: '—' }),
    },
    preview: {
      title: t({ ru: 'Превью', en: 'Preview', kk: 'Превью', de: 'Vorschau', fr: 'Aperçu', es: 'Vista previa', pt: 'Pré-visualização', tr: 'Önizleme', uk: 'Попередній перегляд', zh: '预览', ar: 'معاينة', pl: 'Podgląd', it: 'Anteprima' }),
      subtitle: t({
        ru: 'Used range, sample и стили. В commit будут считаны все данные.',
        en: 'Used range, sample, and styles. On commit, all data will be read.',
        kk: 'Used range, sample және стильдер. Commit кезінде барлық деректер оқылады.',
        de: 'Verwendeter Bereich, Stichprobe und Stile. Beim Commit werden alle Daten gelesen.',
        fr: 'Plage utilisée, échantillon et styles. Lors du commit, toutes les données seront lues.',
        es: 'Rango usado, muestra y estilos. Al confirmar, se leerán todos los datos.',
        pt: 'Intervalo utilizado, amostra e estilos. No commit, todos os dados serão lidos.',
        tr: 'Kullanılan aralık, örnek ve stiller. Commit sırasında tüm veriler okunacak.',
        uk: 'Використаний діапазон, зразок і стилі. Під час commit будуть зчитані всі дані.',
        zh: '已使用范围、示例和样式。提交时将读取所有数据。',
        ar: 'النطاق المستخدم والعينة والأنماط. عند الإلزام، ستُقرأ جميع البيانات.',
        pl: 'Używany zakres, przykład i style. Przy commit wszystkie dane zostaną odczytane.',
        it: 'Intervallo utilizzato, campione e stili. Al commit, tutti i dati verranno letti.',
      }),
      hint: t({
        ru: 'Выберите подключение и нажмите "Сделать превью".',
        en: 'Select a connection and click "Make preview".',
        kk: 'Қосылымды таңдап, "Превью жасау" басыңыз.',
        de: 'Wählen Sie eine Verbindung aus und klicken Sie auf "Vorschau erstellen".',
        fr: 'Sélectionnez une connexion et cliquez sur "Créer un aperçu".',
        es: 'Seleccione una conexión y haga clic en "Crear vista previa".',
        pt: 'Selecione uma conexão e clique em "Criar pré-visualização".',
        tr: 'Bir bağlantı seçin ve "Önizleme oluştur"a tıklayın.',
        uk: 'Виберіть підключення та натисніть «Зробити попередній перегляд».',
        zh: '选择连接并点击"生成预览"。',
        ar: 'حدد اتصالاً وانقر على "إنشاء معاينة".',
        pl: 'Wybierz połączenie i kliknij "Utwórz podgląd".',
        it: 'Seleziona una connessione e clicca su "Crea anteprima".',
      }),
      rowHeader: t({ ru: 'Строка', en: 'Row', kk: 'Жол', de: 'Zeile', fr: 'Ligne', es: 'Fila', pt: 'Linha', tr: 'Satır', uk: 'Рядок', zh: '行', ar: 'صف', pl: 'Wiersz', it: 'Riga' }),
      layoutPrefix: t({ ru: 'layout', en: 'layout', kk: 'layout', de: 'Layout', fr: 'disposition', es: 'diseño', pt: 'layout', tr: 'düzen', uk: 'макет', zh: '布局', ar: 'التخطيط', pl: 'układ', it: 'layout' }),
    },
    columns: {
      title: t({ ru: 'Колонки', en: 'Columns', kk: 'Бағандар', de: 'Spalten', fr: 'Colonnes', es: 'Columnas', pt: 'Colunas', tr: 'Sütunlar', uk: 'Стовпці', zh: '列', ar: 'الأعمدة', pl: 'Kolumny', it: 'Colonne' }),
      subtitle: t({
        ru: 'Можно отключать/переименовывать и менять тип. Тип используется для UI и валидаций.',
        en: 'You can disable/rename and change type. Type is used for UI and validations.',
        kk: 'Өшіруге/атын өзгертуге және түрін ауыстыруға болады. Түр UI және валидация үшін қолданылады.',
        de: 'Sie können deaktivieren/umbenennen und den Typ ändern. Der Typ wird für UI und Validierungen verwendet.',
        fr: 'Vous pouvez désactiver/renommer et changer le type. Le type est utilisé pour l\'interface et les validations.',
        es: 'Puede desactivar/renombrar y cambiar el tipo. El tipo se usa para la UI y las validaciones.',
        pt: 'Você pode desativar/renomear e alterar o tipo. O tipo é usado para UI e validações.',
        tr: 'Devre dışı bırakabilir/yeniden adlandırabilir ve türü değiştirebilirsiniz. Tür, UI ve doğrulamalar için kullanılır.',
        uk: 'Можна вимикати/перейменовувати та змінювати тип. Тип використовується для UI та валідацій.',
        zh: '您可以禁用/重命名并更改类型。类型用于 UI 和验证。',
        ar: 'يمكنك تعطيل/إعادة التسمية وتغيير النوع. يُستخدم النوع للواجهة والتحقق من الصحة.',
        pl: 'Możesz wyłączać/zmieniać nazwy i zmieniać typ. Typ jest używany dla UI i walidacji.',
        it: 'Puoi disabilitare/rinominare e cambiare il tipo. Il tipo è usato per l\'interfaccia e le validazioni.',
      }),
      enableAll: t({ ru: 'Включить все', en: 'Enable all', kk: 'Барлығын қосу', de: 'Alle aktivieren', fr: 'Tout activer', es: 'Habilitar todo', pt: 'Habilitar todos', tr: 'Tümünü etkinleştir', uk: 'Увімкнути всі', zh: '全部启用', ar: 'تمكين الكل', pl: 'Włącz wszystkie', it: 'Abilita tutto' }),
      appearAfterPreview: t({
        ru: 'Колонки появятся после превью.',
        en: 'Columns will appear after preview.',
        kk: 'Бағандар превьюдан кейін пайда болады.',
        de: 'Spalten erscheinen nach der Vorschau.',
        fr: 'Les colonnes apparaîtront après l\'aperçu.',
        es: 'Las columnas aparecerán después de la vista previa.',
        pt: 'As colunas aparecerão após a pré-visualização.',
        tr: 'Sütunlar önizlemeden sonra görünecek.',
        uk: 'Стовпці з\'являться після попереднього перегляду.',
        zh: '预览后将显示列。',
        ar: 'ستظهر الأعمدة بعد المعاينة.',
        pl: 'Kolumny pojawią się po podglądzie.',
        it: 'Le colonne appariranno dopo l\'anteprima.',
      }),
      tableHeaders: {
        enabled: t({ ru: 'Вкл', en: 'On', kk: 'Қос', de: 'Ein', fr: 'Act.', es: 'Act.', pt: 'Ativ.', tr: 'Açık', uk: 'Вкл', zh: '开', ar: 'تشغيل', pl: 'Wł.', it: 'On' }),
        name: t({ ru: 'Название', en: 'Name', kk: 'Атауы', de: 'Name', fr: 'Nom', es: 'Nombre', pt: 'Nome', tr: 'Ad', uk: 'Назва', zh: '名称', ar: 'الاسم', pl: 'Nazwa', it: 'Nome' }),
        type: t({ ru: 'Тип', en: 'Type', kk: 'Түрі', de: 'Typ', fr: 'Type', es: 'Tipo', pt: 'Tipo', tr: 'Tür', uk: 'Тип', zh: '类型', ar: 'النوع', pl: 'Typ', it: 'Tipo' }),
      },
      types: {
        text: t({ ru: 'Текст', en: 'Text', kk: 'Мәтін', de: 'Text', fr: 'Texte', es: 'Texto', pt: 'Texto', tr: 'Metin', uk: 'Текст', zh: '文本', ar: 'نص', pl: 'Tekst', it: 'Testo' }),
        number: t({ ru: 'Число', en: 'Number', kk: 'Сан', de: 'Zahl', fr: 'Nombre', es: 'Número', pt: 'Número', tr: 'Sayı', uk: 'Число', zh: '数字', ar: 'رقم', pl: 'Liczba', it: 'Numero' }),
        date: t({ ru: 'Дата', en: 'Date', kk: 'Күні', de: 'Datum', fr: 'Date', es: 'Fecha', pt: 'Data', tr: 'Tarih', uk: 'Дата', zh: '日期', ar: 'تاريخ', pl: 'Data', it: 'Data' }),
        boolean: t({ ru: 'Да/Нет', en: 'Yes/No', kk: 'Иә/Жоқ', de: 'Ja/Nein', fr: 'Oui/Non', es: 'Sí/No', pt: 'Sim/Não', tr: 'Evet/Hayır', uk: 'Так/Ні', zh: '是/否', ar: 'نعم/لا', pl: 'Tak/Nie', it: 'Sì/No' }),
        select: t({ ru: 'Выбор', en: 'Select', kk: 'Таңдау', de: 'Auswahl', fr: 'Sélection', es: 'Selección', pt: 'Seleção', tr: 'Seçim', uk: 'Вибір', zh: '选择', ar: 'اختيار', pl: 'Wybór', it: 'Selezione' }),
        multiSelect: t({ ru: 'Мультивыбор', en: 'Multi-select', kk: 'Көп таңдау', de: 'Mehrfachauswahl', fr: 'Sélection multiple', es: 'Selección múltiple', pt: 'Seleção múltipla', tr: 'Çoklu seçim', uk: 'Мультивибір', zh: '多选', ar: 'اختيار متعدد', pl: 'Wielokrotny wybór', it: 'Selezione multipla' }),
      },
    },
  },
} satisfies Dictionary;

export default content;
