import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'settingsWorkspacePage',
  content: {
    authRequired: t({
      ru: 'Войдите, чтобы управлять рабочим пространством.',
      en: 'Log in to manage your workspace.',
      kk: 'Жұмыс кеңістігін басқару үшін кіріңіз.',
      de: 'Melden Sie sich an, um Ihren Workspace zu verwalten.',
      fr: 'Connectez-vous pour gérer votre espace de travail.',
      es: 'Inicia sesión para gestionar tu workspace.',
      pt: 'Faça login para gerenciar seu workspace.',
      tr: 'Çalışma alanınızı yönetmek için giriş yapın.',
      uk: 'Увійдіть, щоб керувати робочим простором.',
      zh: '登录以管理您的工作空间。',
      ar: 'سجّل الدخول لإدارة مساحة عملك.',
      pl: 'Zaloguj się, aby zarządzać obszarem roboczym.',
      it: 'Accedi per gestire il tuo workspace.',
    }),
    title: t({
      ru: 'Рабочее пространство',
      en: 'Workspace',
      kk: 'Жұмыс кеңістігі',
      de: 'Arbeitsbereich',
      fr: 'Espace de travail',
      es: 'Espacio de trabajo',
      pt: 'Espaço de trabalho',
      tr: 'Çalışma alanı',
      uk: 'Робочий простір',
      zh: '工作空间',
      ar: 'مساحة العمل',
      pl: 'Obszar roboczy',
      it: 'Workspace',
    }),
    subtitle: t({
      ru: 'Приглашайте коллег по email и управляйте доступом.',
      en: 'Invite teammates by email and manage access.',
      kk: 'Әріптестерді email арқылы шақырып, қолжетімділікті басқарыңыз.',
      de: 'Laden Sie Kollegen per E-Mail ein und verwalten Sie den Zugriff.',
      fr: 'Invitez des collègues par e-mail et gérez les accès.',
      es: 'Invita a compañeros por email y gestiona el acceso.',
      pt: 'Convide colegas por e-mail e gerencie o acesso.',
      tr: 'E-posta ile ekip arkadaşlarını davet edin ve erişimi yönetin.',
      uk: 'Запрошуйте колег по email та керуйте доступом.',
      zh: '通过邮箱邀请同事并管理访问权限。',
      ar: 'ادعُ الزملاء بالبريد الإلكتروني وأدر الوصول.',
      pl: 'Zapraszaj współpracowników e-mailem i zarządzaj dostępem.',
      it: 'Invita i colleghi via email e gestisci l\'accesso.',
    }),
    errors: {
      loadOverview: t({
        ru: 'Не удалось загрузить рабочее пространство',
        en: 'Failed to load workspace',
        kk: 'Жұмыс кеңістігін жүктеу мүмкін болмады',
        de: 'Arbeitsbereich konnte nicht geladen werden',
        fr: 'Impossible de charger l\'espace de travail',
        es: 'No se pudo cargar el workspace',
        pt: 'Falha ao carregar o workspace',
        tr: 'Çalışma alanı yüklenemedi',
        uk: 'Не вдалося завантажити робочий простір',
        zh: '无法加载工作空间',
        ar: 'فشل تحميل مساحة العمل',
        pl: 'Nie udało się załadować obszaru roboczego',
        it: 'Impossibile caricare il workspace',
      }),
      inviteFailed: t({
        ru: 'Не удалось отправить приглашение',
        en: 'Failed to send invitation',
        kk: 'Шақыруды жіберу мүмкін болмады',
        de: 'Einladung konnte nicht gesendet werden',
        fr: 'Impossible d\'envoyer l\'invitation',
        es: 'No se pudo enviar la invitación',
        pt: 'Falha ao enviar convite',
        tr: 'Davet gönderilemedi',
        uk: 'Не вдалося надіслати запрошення',
        zh: '无法发送邀请',
        ar: 'فشل إرسال الدعوة',
        pl: 'Nie udało się wysłać zaproszenia',
        it: 'Impossibile inviare l\'invito',
      }),
      copyFailed: t({
        ru: 'Не удалось скопировать ссылку',
        en: 'Failed to copy link',
        kk: 'Сілтемені көшіру мүмкін болмады',
        de: 'Link konnte nicht kopiert werden',
        fr: 'Impossible de copier le lien',
        es: 'No se pudo copiar el enlace',
        pt: 'Falha ao copiar link',
        tr: 'Bağlantı kopyalanamadı',
        uk: 'Не вдалося скопіювати посилання',
        zh: '无法复制链接',
        ar: 'فشل نسخ الرابط',
        pl: 'Nie udało się skopiować linku',
        it: 'Impossibile copiare il link',
      }),
    },
    toasts: {
      inviteSent: t({
        ru: 'Приглашение отправлено',
        en: 'Invitation sent',
        kk: 'Шақыру жіберілді',
        de: 'Einladung gesendet',
        fr: 'Invitation envoyée',
        es: 'Invitación enviada',
        pt: 'Convite enviado',
        tr: 'Davet gönderildi',
        uk: 'Запрошення надіслано',
        zh: '邀请已发送',
        ar: 'تم إرسال الدعوة',
        pl: 'Zaproszenie wysłane',
        it: 'Invito inviato',
      }),
      linkCopied: t({
        ru: 'Ссылка скопирована',
        en: 'Link copied',
        kk: 'Сілтеме көшірілді',
        de: 'Link kopiert',
        fr: 'Lien copié',
        es: 'Enlace copiado',
        pt: 'Link copiado',
        tr: 'Bağlantı kopyalandı',
        uk: 'Посилання скопійовано',
        zh: '链接已复制',
        ar: 'تم نسخ الرابط',
        pl: 'Link skopiowany',
        it: 'Link copiato',
      }),
    },
    roles: {
      owner: t({
        ru: 'Владелец',
        en: 'Owner',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
      }),
      admin: t({
        ru: 'Администратор',
        en: 'Admin',
        kk: 'Әкімші',
        de: 'Administrator',
        fr: 'Administrateur',
        es: 'Administrador',
        pt: 'Administrador',
        tr: 'Yönetici',
        uk: 'Адміністратор',
        zh: '管理员',
        ar: 'المشرف',
        pl: 'Administrator',
        it: 'Amministratore',
      }),
      member: t({
        ru: 'Участник',
        en: 'Member',
        kk: 'Мүше',
        de: 'Mitglied',
        fr: 'Membre',
        es: 'Miembro',
        pt: 'Membro',
        tr: 'Üye',
        uk: 'Учасник',
        zh: '成员',
        ar: 'عضو',
        pl: 'Członek',
        it: 'Membro',
      }),
      roleLabel: t({
        ru: 'Роль',
        en: 'Role',
        kk: 'Рөл',
        de: 'Rolle',
        fr: 'Rôle',
        es: 'Rol',
        pt: 'Função',
        tr: 'Rol',
        uk: 'Роль',
        zh: '角色',
        ar: 'الدور',
        pl: 'Rola',
        it: 'Ruolo',
      }),
      memberDescription: t({
        ru: 'Может работать с данными, но не управляет участниками и доступом.',
        en: 'Can work with data, but can\'t manage members or access.',
        kk: 'Деректермен жұмыс істей алады, бірақ қатысушылар мен қолжетімділікті басқара алмайды.',
        de: 'Kann mit Daten arbeiten, aber keine Mitglieder oder den Zugriff verwalten.',
        fr: 'Peut travailler avec les données, mais ne peut pas gérer les membres ou les accès.',
        es: 'Puede trabajar con datos, pero no gestiona miembros ni acceso.',
        pt: 'Pode trabalhar com dados, mas não gerencia membros ou acesso.',
        tr: 'Verilerle çalışabilir, ancak üyeleri veya erişimi yönetemez.',
        uk: 'Може працювати з даними, але не керує учасниками та доступом.',
        zh: '可以处理数据，但不能管理成员或访问权限。',
        ar: 'يمكنه العمل مع البيانات لكن لا يمكنه إدارة الأعضاء أو الوصول.',
        pl: 'Może pracować z danymi, ale nie zarządza członkami ani dostępem.',
        it: 'Può lavorare con i dati, ma non gestisce i membri o l\'accesso.',
      }),
      adminDescription: t({
        ru: 'Может управлять участниками и доступом, отправлять приглашения.',
        en: 'Can manage members and access, and send invitations.',
        kk: 'Қатысушылар мен қолжетімділікті басқарып, шақыру жібере алады.',
        de: 'Kann Mitglieder und Zugriff verwalten sowie Einladungen senden.',
        fr: 'Peut gérer les membres et les accès, et envoyer des invitations.',
        es: 'Puede gestionar miembros y acceso, y enviar invitaciones.',
        pt: 'Pode gerenciar membros e acesso, e enviar convites.',
        tr: 'Üyeleri ve erişimi yönetebilir, davet gönderebilir.',
        uk: 'Може керувати учасниками та доступом, надсилати запрошення.',
        zh: '可以管理成员和访问权限，并发送邀请。',
        ar: 'يمكنه إدارة الأعضاء والوصول وإرسال الدعوات.',
        pl: 'Może zarządzać członkami i dostępem oraz wysyłać zaproszenia.',
        it: 'Può gestire i membri e l\'accesso, e inviare inviti.',
      }),
    },
    members: {
      title: t({
        ru: 'Участники',
        en: 'Members',
        kk: 'Қатысушылар',
        de: 'Mitglieder',
        fr: 'Membres',
        es: 'Miembros',
        pt: 'Membros',
        tr: 'Üyeler',
        uk: 'Учасники',
        zh: '成员',
        ar: 'الأعضاء',
        pl: 'Członkowie',
        it: 'Membri',
      }),
    },
    invite: {
      title: t({
        ru: 'Пригласить по email',
        en: 'Invite by email',
        kk: 'Email арқылы шақыру',
        de: 'Per E-Mail einladen',
        fr: 'Inviter par e-mail',
        es: 'Invitar por email',
        pt: 'Convidar por e-mail',
        tr: 'E-posta ile davet et',
        uk: 'Запросити по email',
        zh: '通过邮箱邀请',
        ar: 'دعوة عبر البريد الإلكتروني',
        pl: 'Zaproś przez e-mail',
        it: 'Invita via email',
      }),
      onlyAdminHint: t({
        ru: 'Только владелец или администратор может отправлять приглашения.',
        en: 'Only the owner or an admin can send invitations.',
        kk: 'Шақыруларды тек иесі немесе әкімші жібере алады.',
        de: 'Nur der Eigentümer oder ein Administrator kann Einladungen senden.',
        fr: 'Seul le propriétaire ou un administrateur peut envoyer des invitations.',
        es: 'Solo el propietario o un administrador puede enviar invitaciones.',
        pt: 'Somente o proprietário ou um administrador pode enviar convites.',
        tr: 'Yalnızca sahip veya yönetici davet gönderebilir.',
        uk: 'Тільки власник або адміністратор може надсилати запрошення.',
        zh: '只有所有者或管理员才能发送邀请。',
        ar: 'يمكن للمالك أو المشرف فقط إرسال الدعوات.',
        pl: 'Tylko właściciel lub administrator może wysyłać zaproszenia.',
        it: 'Solo il proprietario o un amministratore può inviare inviti.',
      }),
      permissionsTitle: t({
        ru: 'Права доступа',
        en: 'Access permissions',
        kk: 'Қолжетімділік құқықтары',
        de: 'Zugriffsberechtigungen',
        fr: 'Autorisations d\'accès',
        es: 'Permisos de acceso',
        pt: 'Permissões de acesso',
        tr: 'Erişim izinleri',
        uk: 'Права доступу',
        zh: '访问权限',
        ar: 'أذونات الوصول',
        pl: 'Uprawnienia dostępu',
        it: 'Autorizzazioni di accesso',
      }),
      permissionsHint: t({
        ru: 'Отметьте, что может редактировать участник. Если не отмечено — только просмотр.',
        en: 'Select what the member can edit. If unchecked, they can only view.',
        kk: 'Қатысушы нені өңдей алатынын белгілеңіз. Белгіленбесе — тек көру.',
        de: 'Wählen Sie, was das Mitglied bearbeiten kann. Ohne Häkchen nur Ansicht.',
        fr: 'Sélectionnez ce que le membre peut modifier. Sans coche, il ne peut que consulter.',
        es: 'Selecciona qué puede editar el miembro. Si no está marcado, solo puede ver.',
        pt: 'Selecione o que o membro pode editar. Se desmarcado, apenas visualização.',
        tr: 'Üyenin düzenleyebileceği şeyleri seçin. İşaretlenmezse yalnızca görüntüleyebilir.',
        uk: 'Позначте, що може редагувати учасник. Якщо не позначено — лише перегляд.',
        zh: '选择成员可以编辑的内容。如未勾选，只能查看。',
        ar: 'حدد ما يمكن للعضو تعديله. إذا لم يُحدَّد، فهو للعرض فقط.',
        pl: 'Zaznacz, co może edytować członek. Jeśli niezaznaczone — tylko podgląd.',
        it: 'Seleziona cosa può modificare il membro. Se non selezionato, solo visualizzazione.',
      }),
      permissions: {
        canEditStatements: t({
          ru: 'Выписки',
          en: 'Statements',
          kk: 'Үзінділер',
          de: 'Kontoauszüge',
          fr: 'Relevés',
          es: 'Extractos',
          pt: 'Extratos',
          tr: 'Ekstreler',
          uk: 'Виписки',
          zh: '账单',
          ar: 'الكشوفات',
          pl: 'Wyciągi',
          it: 'Estratti',
        }),
        canEditCustomTables: t({
          ru: 'Таблицы',
          en: 'Tables',
          kk: 'Кестелер',
          de: 'Tabellen',
          fr: 'Tableaux',
          es: 'Tablas',
          pt: 'Tabelas',
          tr: 'Tablolar',
          uk: 'Таблиці',
          zh: '表格',
          ar: 'الجداول',
          pl: 'Tabele',
          it: 'Tabelle',
        }),
        canEditCategories: t({
          ru: 'Категории',
          en: 'Categories',
          kk: 'Санаттар',
          de: 'Kategorien',
          fr: 'Catégories',
          es: 'Categorías',
          pt: 'Categorias',
          tr: 'Kategoriler',
          uk: 'Категорії',
          zh: '类别',
          ar: 'الفئات',
          pl: 'Kategorie',
          it: 'Categorie',
        }),
        canEditDataEntry: t({
          ru: 'Ввод данных',
          en: 'Data entry',
          kk: 'Деректерді енгізу',
          de: 'Dateneingabe',
          fr: 'Saisie de données',
          es: 'Entrada de datos',
          pt: 'Entrada de dados',
          tr: 'Veri girişi',
          uk: 'Введення даних',
          zh: '数据录入',
          ar: 'إدخال البيانات',
          pl: 'Wprowadzanie danych',
          it: 'Inserimento dati',
        }),
        canShareFiles: t({
          ru: 'Ссылки и доступ к файлам',
          en: 'File sharing & access',
          kk: 'Файлдарға сілтеме және қолжетімділік',
          de: 'Dateifreigabe und -zugriff',
          fr: 'Partage de fichiers et accès',
          es: 'Compartir archivos y acceso',
          pt: 'Compartilhamento de arquivos e acesso',
          tr: 'Dosya paylaşımı ve erişimi',
          uk: 'Посилання та доступ до файлів',
          zh: '文件共享与访问',
          ar: 'مشاركة الملفات والوصول',
          pl: 'Udostępnianie plików i dostęp',
          it: 'Condivisione file e accesso',
        }),
      },
      send: t({
        ru: 'Отправить приглашение',
        en: 'Send invitation',
        kk: 'Шақыру жіберу',
        de: 'Einladung senden',
        fr: 'Envoyer l\'invitation',
        es: 'Enviar invitación',
        pt: 'Enviar convite',
        tr: 'Davet gönder',
        uk: 'Надіслати запрошення',
        zh: '发送邀请',
        ar: 'إرسال الدعوة',
        pl: 'Wyślij zaproszenie',
        it: 'Invia invito',
      }),
      inviteLinkLabel: t({
        ru: 'Ссылка на приглашение',
        en: 'Invitation link',
        kk: 'Шақыру сілтемесі',
        de: 'Einladungslink',
        fr: 'Lien d\'invitation',
        es: 'Enlace de invitación',
        pt: 'Link de convite',
        tr: 'Davet bağlantısı',
        uk: 'Посилання на запрошення',
        zh: '邀请链接',
        ar: 'رابط الدعوة',
        pl: 'Link zaproszenia',
        it: 'Link di invito',
      }),
    },
    pending: {
      title: t({
        ru: 'Ожидающие приглашения',
        en: 'Pending invitations',
        kk: 'Күтілетін шақырулар',
        de: 'Ausstehende Einladungen',
        fr: 'Invitations en attente',
        es: 'Invitaciones pendientes',
        pt: 'Convites pendentes',
        tr: 'Bekleyen davetler',
        uk: 'Очікуючі запрошення',
        zh: '待处理邀请',
        ar: 'الدعوات المعلقة',
        pl: 'Oczekujące zaproszenia',
        it: 'Inviti in attesa',
      }),
      empty: t({
        ru: 'Пока нет активных приглашений.',
        en: 'No active invitations yet.',
        kk: 'Әзірше белсенді шақырулар жоқ.',
        de: 'Noch keine aktiven Einladungen.',
        fr: 'Aucune invitation active pour l\'instant.',
        es: 'Aún no hay invitaciones activas.',
        pt: 'Nenhum convite ativo ainda.',
        tr: 'Henüz aktif davet yok.',
        uk: 'Поки немає активних запрошень.',
        zh: '暂无活跃邀请。',
        ar: 'لا توجد دعوات نشطة حتى الآن.',
        pl: 'Brak aktywnych zaproszeń.',
        it: 'Nessun invito attivo ancora.',
      }),
      validUntil: t({
        ru: 'Действительно до',
        en: 'Valid until',
        kk: 'Мерзімі',
        de: 'Gültig bis',
        fr: 'Valide jusqu\'au',
        es: 'Válido hasta',
        pt: 'Válido até',
        tr: 'Geçerlilik tarihi',
        uk: 'Дійсно до',
        zh: '有效期至',
        ar: 'صالح حتى',
        pl: 'Ważny do',
        it: 'Valido fino al',
      }),
      copyLink: t({
        ru: 'Копировать ссылку',
        en: 'Copy link',
        kk: 'Сілтемені көшіру',
        de: 'Link kopieren',
        fr: 'Copier le lien',
        es: 'Copiar enlace',
        pt: 'Copiar link',
        tr: 'Bağlantıyı kopyala',
        uk: 'Копіювати посилання',
        zh: '复制链接',
        ar: 'نسخ الرابط',
        pl: 'Kopiuj link',
        it: 'Copia link',
      }),
    },
    backgrounds: {
      showMore: t({
        ru: 'Показать еще',
        en: 'Show more',
        kk: 'Көбірек көрсету',
        de: 'Mehr anzeigen',
        fr: 'Afficher plus',
        es: 'Mostrar más',
        pt: 'Mostrar mais',
        tr: 'Daha fazla göster',
        uk: 'Показати більше',
        zh: '显示更多',
        ar: 'عرض المزيد',
        pl: 'Pokaż więcej',
        it: 'Mostra di più',
      }),
      showLess: t({
        ru: 'Скрыть',
        en: 'Show less',
        kk: 'Азырақ көрсету',
        de: 'Weniger anzeigen',
        fr: 'Afficher moins',
        es: 'Mostrar menos',
        pt: 'Mostrar menos',
        tr: 'Daha az göster',
        uk: 'Згорнути',
        zh: '显示更少',
        ar: 'عرض أقل',
        pl: 'Pokaż mniej',
        it: 'Mostra meno',
      }),
    },
  },
} satisfies Dictionary;

export default content;
