import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'storageDetailsPage',
  content: {
    loading: t({
      ru: 'Загрузка...',
      en: 'Loading...',
      kk: 'Жүктелуде...',
      de: 'Laden...',
      fr: 'Chargement...',
      es: 'Cargando...',
      pt: 'Carregando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '加载中...',
      ar: 'جارٍ التحميل...',
      pl: 'Ładowanie...',
      it: 'Caricamento...',
      sk: 'Ładowanie...',
    }),
    notFound: t({
      ru: 'Файл не найден',
      en: 'File not found',
      kk: 'Файл табылмады',
      de: 'Datei nicht gefunden',
      fr: 'Fichier introuvable',
      es: 'Archivo no encontrado',
      pt: 'Arquivo não encontrado',
      tr: 'Dosya bulunamadı',
      uk: 'Файл не знайдено',
      zh: '文件未找到',
      ar: 'الملف غير موجود',
      pl: 'Plik nie znaleziony',
      it: 'File non trovato',
      sk: 'Plik nie znaleziony',
    }),
    toasts: {
      previewFailed: t({
        ru: 'Не удалось загрузить превью файла',
        en: 'Failed to load file preview',
        kk: 'Файл превьюін жүктеу мүмкін болмады',
        de: 'Dateivorschau konnte nicht geladen werden',
        fr: "Impossible de charger l'aperçu du fichier",
        es: 'No se pudo cargar la vista previa del archivo',
        pt: 'Falha ao carregar prévia do arquivo',
        tr: 'Dosya önizlemesi yüklenemedi',
        uk: 'Не вдалося завантажити попередній перегляд файлу',
        zh: '无法加载文件预览',
        ar: 'فشل تحميل معاينة الملف',
        pl: 'Nie udało się załadować podglądu pliku',
        it: "Impossibile caricare l'anteprima del file",
        sk: 'Nie udało się załadować podglądu pliku',
      }),
      restoreSuccess: t({
        ru: 'Файл восстановлен',
        en: 'File restored',
        kk: 'Файл қалпына келтірілді',
        de: 'Datei wiederhergestellt',
        fr: 'Fichier restauré',
        es: 'Archivo restaurado',
        pt: 'Arquivo restaurado',
        tr: 'Dosya geri yüklendi',
        uk: 'Файл відновлено',
        zh: '文件已恢复',
        ar: 'تم استعادة الملف',
        pl: 'Plik przywrócony',
        it: 'File ripristinato',
        sk: 'Plik przywrócony',
      }),
      restoreFailed: t({
        ru: 'Не удалось восстановить файл',
        en: 'Failed to restore file',
        kk: 'Файлды қалпына келтіру мүмкін болмады',
        de: 'Datei konnte nicht wiederhergestellt werden',
        fr: 'Impossible de restaurer le fichier',
        es: 'No se pudo restaurar el archivo',
        pt: 'Falha ao restaurar arquivo',
        tr: 'Dosya geri yüklenemedi',
        uk: 'Не вдалося відновити файл',
        zh: '无法恢复文件',
        ar: 'فشل استعادة الملف',
        pl: 'Nie udało się przywrócić pliku',
        it: 'Impossibile ripristinare il file',
        sk: 'Nie udało się przywrócić pliku',
      }),
      loadCategoriesFailed: t({
        ru: 'Не удалось загрузить категории',
        en: 'Failed to load categories',
        kk: 'Санаттарды жүктеу мүмкін болмады',
        de: 'Kategorien konnten nicht geladen werden',
        fr: 'Impossible de charger les catégories',
        es: 'No se pudieron cargar las categorías',
        pt: 'Falha ao carregar categorias',
        tr: 'Kategoriler yüklenemedi',
        uk: 'Не вдалося завантажити категорії',
        zh: '无法加载分类',
        ar: 'فشل تحميل الفئات',
        pl: 'Nie udało się załadować kategorii',
        it: 'Impossibile caricare le categorie',
        sk: 'Nie udało się załadować kategorii',
      }),
    },
    availability: {
      labels: {
        both: t({
          ru: 'OK',
          en: 'OK',
          kk: 'OK',
          de: 'OK',
          fr: 'OK',
          es: 'OK',
          pt: 'OK',
          tr: 'OK',
          uk: 'OK',
          zh: 'OK',
          ar: 'OK',
          pl: 'OK',
          it: 'OK',
          sk: 'OK',
        }),
        disk: t({
          ru: 'Диск',
          en: 'Disk',
          kk: 'Disk',
          de: 'Disk',
          fr: 'Disque',
          es: 'Disco',
          pt: 'Disco',
          tr: 'Disk',
          uk: 'Диск',
          zh: '磁盘',
          ar: 'القرص',
          pl: 'Dysk',
          it: 'Disco',
        }),
        db: t({
          ru: 'БД',
          en: 'DB',
          kk: 'DB',
          de: 'DB',
          fr: 'BD',
          es: 'BD',
          pt: 'BD',
          tr: 'DB',
          uk: 'БД',
          zh: '数据库',
          ar: 'قاعدة البيانات',
          pl: 'DB',
          it: 'DB',
          sk: 'DB',
        }),
        missing: t({
          ru: 'Нет файла',
          en: 'Missing',
          kk: 'Қолжетімсіз',
          de: 'Fehlt',
          fr: 'Manquant',
          es: 'Faltante',
          pt: 'Ausente',
          tr: 'Eksik',
          uk: 'Відсутній',
          zh: '缺失',
          ar: 'مفقود',
          pl: 'Brakuje',
          it: 'Mancante',
          sk: 'Brakuje',
        }),
      },
      tooltips: {
        both: t({
          ru: 'Файл доступен на диске и в базе данных',
          en: 'File is available on disk and in DB',
          kk: 'Файл дискте және дерекқорда қолжетімді',
          de: 'Datei ist auf dem Datenträger und in der DB verfügbar',
          fr: 'Le fichier est disponible sur le disque et dans la BD',
          es: 'El archivo está disponible en disco y en BD',
          pt: 'Arquivo disponível no disco e no BD',
          tr: 'Dosya diskte ve veritabanında mevcut',
          uk: 'Файл доступний на диску і в базі даних',
          zh: '文件在磁盘和数据库中均可用',
          ar: 'الملف متاح على القرص وفي قاعدة البيانات',
          pl: 'Plik jest dostępny na dysku i w bazie danych',
          it: 'Il file è disponibile su disco e nel DB',
          sk: 'Plik jest dostępny na dysku i w bazie danych',
        }),
        disk: t({
          ru: 'Файл доступен на диске',
          en: 'File is available on disk',
          kk: 'Файл дискте қолжетімді',
          de: 'Datei ist auf dem Datenträger verfügbar',
          fr: 'Le fichier est disponible sur le disque',
          es: 'El archivo está disponible en disco',
          pt: 'Arquivo disponível no disco',
          tr: 'Dosya diskte mevcut',
          uk: 'Файл доступний на диску',
          zh: '文件在磁盘上可用',
          ar: 'الملف متاح على القرص',
          pl: 'Plik jest dostępny na dysku',
          it: 'Il file è disponibile su disco',
          sk: 'Plik jest dostępny na dysku',
        }),
        db: t({
          ru: 'Файл доступен в базе данных',
          en: 'File is available in DB',
          kk: 'Файл дерекқорда қолжетімді',
          de: 'Datei ist in der Datenbank verfügbar',
          fr: 'Le fichier est disponible dans la BD',
          es: 'El archivo está disponible en BD',
          pt: 'Arquivo disponível no BD',
          tr: 'Dosya veritabanında mevcut',
          uk: 'Файл доступний в базі даних',
          zh: '文件在数据库中可用',
          ar: 'الملف متاح في قاعدة البيانات',
          pl: 'Plik jest dostępny w bazie danych',
          it: 'Il file è disponibile nel DB',
          sk: 'Plik jest dostępny w bazie danych',
        }),
        missing: t({
          ru: 'Файл недоступен (нет на диске и в базе данных)',
          en: 'File is unavailable (missing on disk and in DB)',
          kk: 'Файл қолжетімсіз (дискте де, дерекқорда да жоқ)',
          de: 'Datei nicht verfügbar (nicht auf Datenträger und nicht in DB)',
          fr: 'Fichier indisponible (absent du disque et de la BD)',
          es: 'Archivo no disponible (faltante en disco y en BD)',
          pt: 'Arquivo indisponível (ausente no disco e no BD)',
          tr: 'Dosya mevcut değil (diskte ve veritabanında yok)',
          uk: 'Файл недоступний (відсутній на диску і в базі даних)',
          zh: '文件不可用（磁盘和数据库中均缺失）',
          ar: 'الملف غير متاح (مفقود من القرص وقاعدة البيانات)',
          pl: 'Plik niedostępny (brak na dysku i w bazie danych)',
          it: 'File non disponibile (mancante su disco e nel DB)',
          sk: 'Plik niedostępny (brak na dysku i w bazie danych)',
        }),
      },
    },
    permission: {
      owner: t({
        ru: 'Владелец',
        en: 'Owner',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
        sk: 'Właściciel',
      }),
      editor: t({
        ru: 'Редактор',
        en: 'Editor',
        kk: 'Өңдеуші',
        de: 'Bearbeiter',
        fr: 'Éditeur',
        es: 'Editor',
        pt: 'Editor',
        tr: 'Düzenleyici',
        uk: 'Редактор',
        zh: '编辑者',
        ar: 'محرر',
        pl: 'Edytor',
        it: 'Editore',
        sk: 'Edytor',
      }),
      viewer: t({
        ru: 'Просмотр',
        en: 'Viewer',
        kk: 'Қарау',
        de: 'Betrachter',
        fr: 'Lecteur',
        es: 'Lector',
        pt: 'Visualizador',
        tr: 'Görüntüleyici',
        uk: 'Переглядач',
        zh: '查看者',
        ar: 'مشاهد',
        pl: 'Przeglądający',
        it: 'Visualizzatore',
        sk: 'Przeglądający',
      }),
      downloader: t({
        ru: 'Скачивание',
        en: 'Download',
        kk: 'Жүктеу',
        de: 'Herunterladen',
        fr: 'Téléchargement',
        es: 'Descarga',
        pt: 'Download',
        tr: 'İndirme',
        uk: 'Завантаження',
        zh: '下载',
        ar: 'تنزيل',
        pl: 'Pobieranie',
        it: 'Download',
        sk: 'Pobieranie',
      }),
      access: t({
        ru: 'Доступ',
        en: 'Access',
        kk: 'Қолжетімділік',
        de: 'Zugriff',
        fr: 'Accès',
        es: 'Acceso',
        pt: 'Acesso',
        tr: 'Erişim',
        uk: 'Доступ',
        zh: '访问',
        ar: 'الوصول',
        pl: 'Dostęp',
        it: 'Accesso',
        sk: 'Dostęp',
      }),
    },
    status: {
      completed: t({
        ru: 'Завершено',
        en: 'Completed',
        kk: 'Аяқталды',
        de: 'Abgeschlossen',
        fr: 'Terminé',
        es: 'Completado',
        pt: 'Concluído',
        tr: 'Tamamlandı',
        uk: 'Завершено',
        zh: '已完成',
        ar: 'مكتمل',
        pl: 'Ukończono',
        it: 'Completato',
        sk: 'Ukończono',
      }),
      processing: t({
        ru: 'Обрабатывается',
        en: 'Processing',
        kk: 'Өңделуде',
        de: 'Wird verarbeitet',
        fr: 'En cours de traitement',
        es: 'Procesando',
        pt: 'Processando',
        tr: 'İşleniyor',
        uk: 'Обробляється',
        zh: '处理中',
        ar: 'قيد المعالجة',
        pl: 'Przetwarzanie',
        it: 'In elaborazione',
        sk: 'Przetwarzanie',
      }),
      error: t({
        ru: 'Ошибка',
        en: 'Error',
        kk: 'Қате',
        de: 'Fehler',
        fr: 'Erreur',
        es: 'Error',
        pt: 'Erro',
        tr: 'Hata',
        uk: 'Помилка',
        zh: '错误',
        ar: 'خطأ',
        pl: 'Błąd',
        it: 'Errore',
        sk: 'Błąd',
      }),
      uploaded: t({
        ru: 'Загружено',
        en: 'Uploaded',
        kk: 'Жүктелді',
        de: 'Hochgeladen',
        fr: 'Téléchargé',
        es: 'Subido',
        pt: 'Enviado',
        tr: 'Yüklendi',
        uk: 'Завантажено',
        zh: '已上传',
        ar: 'تم الرفع',
        pl: 'Przesłano',
        it: 'Caricato',
        sk: 'Przesłano',
      }),
    },
    actions: {
      downloadTooltip: t({
        ru: 'Скачать файл',
        en: 'Download file',
        kk: 'Файлды жүктеу',
        de: 'Datei herunterladen',
        fr: 'Télécharger le fichier',
        es: 'Descargar archivo',
        pt: 'Baixar arquivo',
        tr: 'Dosyayı indir',
        uk: 'Завантажити файл',
        zh: '下载文件',
        ar: 'تنزيل الملف',
        pl: 'Pobierz plik',
        it: 'Scarica file',
        sk: 'Pobierz plik',
      }),
      download: t({
        ru: 'Скачать',
        en: 'Download',
        kk: 'Жүктеу',
        de: 'Herunterladen',
        fr: 'Télécharger',
        es: 'Descargar',
        pt: 'Baixar',
        tr: 'İndir',
        uk: 'Завантажити',
        zh: '下载',
        ar: 'تنزيل',
        pl: 'Pobierz',
        it: 'Scarica',
        sk: 'Pobierz',
      }),
      restoreTooltip: t({
        ru: 'Восстановить файл на диск из базы данных',
        en: 'Restore file to disk from DB',
        kk: 'Файлды дерекқордан дискіге қалпына келтіру',
        de: 'Datei aus der Datenbank auf den Datenträger wiederherstellen',
        fr: 'Restaurer le fichier sur le disque depuis la BD',
        es: 'Restaurar archivo al disco desde BD',
        pt: 'Restaurar arquivo no disco a partir do BD',
        tr: 'Dosyayı veritabanından diske geri yükle',
        uk: 'Відновити файл на диск з бази даних',
        zh: '从数据库恢复文件到磁盘',
        ar: 'استعادة الملف إلى القرص من قاعدة البيانات',
        pl: 'Przywróć plik na dysk z bazy danych',
        it: 'Ripristina file su disco dal DB',
        sk: 'Przywróć plik na dysk z bazy danych',
      }),
      restore: t({
        ru: 'Восстановить',
        en: 'Restore',
        kk: 'Қалпына келтіру',
        de: 'Wiederherstellen',
        fr: 'Restaurer',
        es: 'Restaurar',
        pt: 'Restaurar',
        tr: 'Geri yükle',
        uk: 'Відновити',
        zh: '恢复',
        ar: 'استعادة',
        pl: 'Przywróć',
        it: 'Ripristina',
        sk: 'Przywróć',
      }),
      shareTooltip: t({
        ru: 'Поделиться файлом',
        en: 'Share file',
        kk: 'Файлмен бөлісу',
        de: 'Datei teilen',
        fr: 'Partager le fichier',
        es: 'Compartir archivo',
        pt: 'Compartilhar arquivo',
        tr: 'Dosyayı paylaş',
        uk: 'Поділитися файлом',
        zh: '分享文件',
        ar: 'مشاركة الملف',
        pl: 'Udostępnij plik',
        it: 'Condividi file',
        sk: 'Udostępnij plik',
      }),
      share: t({
        ru: 'Поделиться',
        en: 'Share',
        kk: 'Бөлісу',
        de: 'Teilen',
        fr: 'Partager',
        es: 'Compartir',
        pt: 'Compartilhar',
        tr: 'Paylaş',
        uk: 'Поділитися',
        zh: '分享',
        ar: 'مشاركة',
        pl: 'Udostępnij',
        it: 'Condividi',
        sk: 'Udostępnij',
      }),
      back: t({
        ru: 'Назад',
        en: 'Back',
        kk: 'Артқа',
        de: 'Zurück',
        fr: 'Retour',
        es: 'Volver',
        pt: 'Voltar',
        tr: 'Geri',
        uk: 'Назад',
        zh: '返回',
        ar: 'رجوع',
        pl: 'Wstecz',
        it: 'Indietro',
        sk: 'Wstecz',
      }),
    },
    cards: {
      size: t({
        ru: 'Размер файла',
        en: 'File size',
        kk: 'Файл өлшемі',
        de: 'Dateigröße',
        fr: 'Taille du fichier',
        es: 'Tamaño del archivo',
        pt: 'Tamanho do arquivo',
        tr: 'Dosya boyutu',
        uk: 'Розмір файлу',
        zh: '文件大小',
        ar: 'حجم الملف',
        pl: 'Rozmiar pliku',
        it: 'Dimensione file',
        sk: 'Rozmiar pliku',
      }),
      transactions: t({
        ru: 'Транзакций',
        en: 'Transactions',
        kk: 'Транзакциялар',
        de: 'Transaktionen',
        fr: 'Transactions',
        es: 'Transacciones',
        pt: 'Transações',
        tr: 'İşlemler',
        uk: 'Транзакцій',
        zh: '交易',
        ar: 'المعاملات',
        pl: 'Transakcje',
        it: 'Transazioni',
        sk: 'Transakcje',
      }),
      uploadedAt: t({
        ru: 'Загружено',
        en: 'Uploaded',
        kk: 'Жүктелді',
        de: 'Hochgeladen',
        fr: 'Téléchargé',
        es: 'Subido',
        pt: 'Enviado',
        tr: 'Yüklendi',
        uk: 'Завантажено',
        zh: '已上传',
        ar: 'تم الرفع',
        pl: 'Przesłano',
        it: 'Caricato',
        sk: 'Przesłano',
      }),
      account: t({
        ru: 'Счет',
        en: 'Account',
        kk: 'Шот',
        de: 'Konto',
        fr: 'Compte',
        es: 'Cuenta',
        pt: 'Conta',
        tr: 'Hesap',
        uk: 'Рахунок',
        zh: '账户',
        ar: 'الحساب',
        pl: 'Konto',
        it: 'Conto',
        sk: 'Konto',
      }),
      dash: t({
        ru: '—',
        en: '—',
        kk: '—',
        de: '—',
        fr: '—',
        es: '—',
        pt: '—',
        tr: '—',
        uk: '—',
        zh: '—',
        ar: '—',
        pl: '—',
        it: '—',
        sk: '—',
      }),
    },
    preview: {
      title: t({
        ru: 'Предпросмотр файла',
        en: 'File preview',
        kk: 'Файл превьюі',
        de: 'Dateivorschau',
        fr: 'Aperçu du fichier',
        es: 'Vista previa del archivo',
        pt: 'Prévia do arquivo',
        tr: 'Dosya önizlemesi',
        uk: 'Попередній перегляд файлу',
        zh: '文件预览',
        ar: 'معاينة الملف',
        pl: 'Podgląd pliku',
        it: 'Anteprima file',
        sk: 'Podgląd pliku',
      }),
      refresh: t({
        ru: 'Обновить',
        en: 'Refresh',
        kk: 'Жаңарту',
        de: 'Aktualisieren',
        fr: 'Actualiser',
        es: 'Actualizar',
        pt: 'Atualizar',
        tr: 'Yenile',
        uk: 'Оновити',
        zh: '刷新',
        ar: 'تحديث',
        pl: 'Odśwież',
        it: 'Aggiorna',
        sk: 'Odśwież',
      }),
      openNewTab: t({
        ru: 'Открыть в новой вкладке',
        en: 'Open in new tab',
        kk: 'Жаңа қойындыда ашу',
        de: 'In neuem Tab öffnen',
        fr: 'Ouvrir dans un nouvel onglet',
        es: 'Abrir en nueva pestaña',
        pt: 'Abrir em nova aba',
        tr: 'Yeni sekmede aç',
        uk: 'Відкрити у новій вкладці',
        zh: '在新标签页中打开',
        ar: 'فتح في علامة تبويب جديدة',
        pl: 'Otwórz w nowej karcie',
        it: 'Apri in una nuova scheda',
        sk: 'Otwórz w nowej karcie',
      }),
      iframeTitle: t({
        ru: 'Предпросмотр файла',
        en: 'File preview',
        kk: 'Файл превьюі',
        de: 'Dateivorschau',
        fr: 'Aperçu du fichier',
        es: 'Vista previa del archivo',
        pt: 'Prévia do arquivo',
        tr: 'Dosya önizlemesi',
        uk: 'Попередній перегляд файлу',
        zh: '文件预览',
        ar: 'معاينة الملف',
        pl: 'Podgląd pliku',
        it: 'Anteprima file',
        sk: 'Podgląd pliku',
      }),
      retry: t({
        ru: 'Попробовать снова',
        en: 'Try again',
        kk: 'Қайтадан көру',
        de: 'Erneut versuchen',
        fr: 'Réessayer',
        es: 'Intentar de nuevo',
        pt: 'Tentar novamente',
        tr: 'Tekrar dene',
        uk: 'Спробувати знову',
        zh: '重试',
        ar: 'حاول مجدداً',
        pl: 'Spróbuj ponownie',
        it: 'Riprova',
        sk: 'Spróbuj ponownie',
      }),
      unavailable: t({
        ru: 'Файл недоступен. Похоже, он был удалён с сервера. Попросите владельца загрузить файл заново.',
        en: 'File is unavailable. It may have been removed from the server. Ask the owner to upload it again.',
        kk: 'Файл қолжетімсіз. Ол серверден өшірілген болуы мүмкін. Иесінен файлды қайта жүктеуді сұраңыз.',
        de: 'Datei nicht verfügbar. Sie wurde möglicherweise vom Server entfernt. Bitten Sie den Eigentümer, die Datei erneut hochzuladen.',
        fr: 'Fichier indisponible. Il a peut-être été supprimé du serveur. Demandez au propriétaire de le télécharger à nouveau.',
        es: 'Archivo no disponible. Es posible que haya sido eliminado del servidor. Pida al propietario que lo suba de nuevo.',
        pt: 'Arquivo indisponível. Pode ter sido removido do servidor. Peça ao proprietário que faça o upload novamente.',
        tr: 'Dosya mevcut değil. Sunucudan kaldırılmış olabilir. Sahibinden dosyayı tekrar yüklemesini isteyin.',
        uk: 'Файл недоступний. Можливо, він був видалений із сервера. Попросіть власника завантажити файл знову.',
        zh: '文件不可用。可能已从服务器删除。请让所有者重新上传该文件。',
        ar: 'الملف غير متاح. ربما تم حذفه من الخادم. اطلب من المالك رفعه مرة أخرى.',
        pl: 'Plik niedostępny. Mógł zostać usunięty z serwera. Poproś właściciela o ponowne przesłanie pliku.',
        it: 'File non disponibile. Potrebbe essere stato rimosso dal server. Chiedi al proprietario di caricarlo di nuovo.',
        sk: 'Plik niedostępny. Mógł zostać usunięty z serwera. Poproś właściciela o ponowne przesłanie pliku.',
      }),
      empty: t({
        ru: 'Превью появится после загрузки файла. Если формат не поддерживает онлайн-просмотр, скачайте файл.',
        en: 'Preview will appear after file upload. If the format is not supported online, download the file.',
        kk: 'Превью файл жүктелгеннен кейін пайда болады. Егер формат онлайн қарауды қолдамаса, файлды жүктеңіз.',
        de: 'Vorschau erscheint nach dem Hochladen der Datei. Wenn das Format die Online-Ansicht nicht unterstützt, laden Sie die Datei herunter.',
        fr: "L'aperçu apparaîtra après le téléchargement du fichier. Si le format ne prend pas en charge la visualisation en ligne, téléchargez le fichier.",
        es: 'La vista previa aparecerá después de subir el archivo. Si el formato no admite visualización en línea, descargue el archivo.',
        pt: 'A prévia aparecerá após o upload do arquivo. Se o formato não suportar visualização online, baixe o arquivo.',
        tr: 'Önizleme dosya yüklendikten sonra görünecek. Format çevrimiçi görüntülemeyi desteklemiyorsa dosyayı indirin.',
        uk: "Попередній перегляд з'явиться після завантаження файлу. Якщо формат не підтримує онлайн-перегляд, завантажте файл.",
        zh: '预览将在文件上传后显示。如果格式不支持在线查看，请下载文件。',
        ar: 'ستظهر المعاينة بعد رفع الملف. إذا كان التنسيق لا يدعم العرض عبر الإنترنت، قم بتنزيل الملف.',
        pl: 'Podgląd pojawi się po przesłaniu pliku. Jeśli format nie obsługuje przeglądania online, pobierz plik.',
        it: "L'anteprima apparirà dopo il caricamento del file. Se il formato non supporta la visualizzazione online, scarica il file.",
        sk: 'Podgląd pojawi się po przesłaniu pliku. Jeśli format nie obsługuje przeglądania online, pobierz plik.',
      }),
    },
    tabs: {
      transactions: t({
        ru: 'Транзакции',
        en: 'Transactions',
        kk: 'Транзакциялар',
        de: 'Transaktionen',
        fr: 'Transactions',
        es: 'Transacciones',
        pt: 'Transações',
        tr: 'İşlemler',
        uk: 'Транзакції',
        zh: '交易',
        ar: 'المعاملات',
        pl: 'Transakcje',
        it: 'Transazioni',
        sk: 'Transakcje',
      }),
      links: t({
        ru: 'Ссылки',
        en: 'Links',
        kk: 'Сілтемелер',
        de: 'Links',
        fr: 'Liens',
        es: 'Enlaces',
        pt: 'Links',
        tr: 'Bağlantılar',
        uk: 'Посилання',
        zh: '链接',
        ar: 'الروابط',
        pl: 'Linki',
        it: 'Link',
        sk: 'Linki',
      }),
      permissions: t({
        ru: 'Права доступа',
        en: 'Permissions',
        kk: 'Құқықтар',
        de: 'Berechtigungen',
        fr: 'Autorisations',
        es: 'Permisos',
        pt: 'Permissões',
        tr: 'İzinler',
        uk: 'Права доступу',
        zh: '权限',
        ar: 'الصلاحيات',
        pl: 'Uprawnienia',
        it: 'Permessi',
        sk: 'Uprawnienia',
      }),
    },
  },
} satisfies Dictionary;

export default content;
