import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'loginPage',
  content: {
    title: t({
      ru: 'С возвращением',
      en: 'Welcome back',
      kk: 'Қайта келдіңіз',
      de: 'Willkommen zurück',
      fr: 'Bon retour',
      es: 'Bienvenido de nuevo',
      pt: 'Bem-vindo de volta',
      tr: 'Tekrar hoş geldiniz',
      uk: 'З поверненням',
      zh: '欢迎回来',
      ar: 'مرحباً بعودتك',
      pl: 'Witaj ponownie',
      it: 'Bentornato',
    }),
    subtitle: t({
      ru: 'Войдите, чтобы продолжить работу в Lumio',
      en: 'Log in to continue using Lumio',
      kk: 'Lumio қолдануды жалғастыру үшін кіріңіз',
      de: 'Melden Sie sich an, um Lumio weiter zu nutzen',
      fr: 'Connectez-vous pour continuer à utiliser Lumio',
      es: 'Inicia sesión para continuar usando Lumio',
      pt: 'Faça login para continuar usando o Lumio',
      tr: 'Lumio\'yu kullanmaya devam etmek için giriş yapın',
      uk: 'Увійдіть, щоб продовжити роботу в Lumio',
      zh: '登录以继续使用 Lumio',
      ar: 'سجّل دخولك لمواصلة استخدام Lumio',
      pl: 'Zaloguj się, aby kontynuować korzystanie z Lumio',
      it: 'Accedi per continuare a usare Lumio',
    }),
    passwordLabel: t({
      ru: 'Пароль',
      en: 'Password',
      kk: 'Құпиясөз',
      de: 'Passwort',
      fr: 'Mot de passe',
      es: 'Contraseña',
      pt: 'Senha',
      tr: 'Şifre',
      uk: 'Пароль',
      zh: '密码',
      ar: 'كلمة المرور',
      pl: 'Hasło',
      it: 'Password',
    }),
    submit: t({
      ru: 'Войти',
      en: 'Log in',
      kk: 'Кіру',
      de: 'Anmelden',
      fr: 'Se connecter',
      es: 'Iniciar sesión',
      pt: 'Entrar',
      tr: 'Giriş yap',
      uk: 'Увійти',
      zh: '登录',
      ar: 'تسجيل الدخول',
      pl: 'Zaloguj się',
      it: 'Accedi',
    }),
    noAccount: t({
      ru: 'Нет аккаунта? Зарегистрируйтесь',
      en: "Don't have an account? Sign up",
      kk: 'Аккаунт жоқ па? Тіркеліңіз',
      de: 'Noch kein Konto? Registrieren',
      fr: "Pas de compte ? S'inscrire",
      es: '¿No tienes cuenta? Regístrate',
      pt: 'Não tem uma conta? Cadastre-se',
      tr: 'Hesabınız yok mu? Kaydolun',
      uk: 'Немає акаунту? Зареєструйтесь',
      zh: '没有账号？立即注册',
      ar: 'ليس لديك حساب؟ سجّل الآن',
      pl: 'Nie masz konta? Zarejestruj się',
      it: 'Non hai un account? Registrati',
    }),
    rightTagline: t({
      ru: 'Платформа для обработки банковских выписок',
      en: 'A platform for bank statement processing',
      kk: 'Банк үзінділерін өңдеуге арналған платформа',
      de: 'Eine Plattform zur Verarbeitung von Kontoauszügen',
      fr: 'Une plateforme de traitement des relevés bancaires',
      es: 'Una plataforma para el procesamiento de extractos bancarios',
      pt: 'Uma plataforma para processamento de extratos bancários',
      tr: 'Banka ekstresi işleme platformu',
      uk: 'Платформа для обробки банківських виписок',
      zh: '银行对账单处理平台',
      ar: 'منصة لمعالجة كشوف الحسابات البنكية',
      pl: 'Platforma do przetwarzania wyciągów bankowych',
      it: 'Una piattaforma per l\'elaborazione degli estratti conto bancari',
    }),
    loginFailed: t({
      ru: 'Не удалось выполнить вход. Попробуйте ещё раз.',
      en: 'Failed to log in. Please try again.',
      kk: 'Кіру мүмкін болмады. Қайтадан көріңіз.',
      de: 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
      fr: 'Échec de la connexion. Veuillez réessayer.',
      es: 'Error al iniciar sesión. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao fazer login. Por favor, tente novamente.',
      tr: 'Giriş başarısız. Lütfen tekrar deneyin.',
      uk: 'Не вдалося увійти. Спробуйте ще раз.',
      zh: '登录失败，请重试。',
      ar: 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
      pl: 'Logowanie nie powiodło się. Spróbuj ponownie.',
      it: 'Accesso non riuscito. Per favore riprova.',
    }),
    googleLoginFailed: t({
      ru: 'Не удалось войти через Google. Попробуйте ещё раз.',
      en: 'Failed to sign in with Google. Please try again.',
      kk: 'Google арқылы кіру мүмкін болмады. Қайтадан көріңіз.',
      de: 'Anmeldung mit Google fehlgeschlagen. Bitte versuchen Sie es erneut.',
      fr: 'Échec de la connexion avec Google. Veuillez réessayer.',
      es: 'Error al iniciar sesión con Google. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao fazer login com o Google. Por favor, tente novamente.',
      tr: 'Google ile giriş başarısız. Lütfen tekrar deneyin.',
      uk: 'Не вдалося увійти через Google. Спробуйте ще раз.',
      zh: '通过 Google 登录失败，请重试。',
      ar: 'فشل تسجيل الدخول عبر Google. يرجى المحاولة مرة أخرى.',
      pl: 'Logowanie przez Google nie powiodło się. Spróbuj ponownie.',
      it: 'Accesso con Google non riuscito. Per favore riprova.',
    }),
    orLabel: t({
      ru: 'или',
      en: 'or',
      kk: 'немесе',
      de: 'oder',
      fr: 'ou',
      es: 'o',
      pt: 'ou',
      tr: 'veya',
      uk: 'або',
      zh: '或',
      ar: 'أو',
      pl: 'lub',
      it: 'o',
    }),
  },
} satisfies Dictionary;

export default content;
