import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'registerPage',
  content: {
    title: t({
      ru: 'Создайте аккаунт',
      en: 'Create an account',
      kk: 'Аккаунт жасаңыз',
      de: 'Konto erstellen',
      fr: 'Créer un compte',
      es: 'Crear una cuenta',
      pt: 'Criar uma conta',
      tr: 'Hesap oluştur',
      uk: 'Створіть акаунт',
      zh: '创建账号',
      ar: 'إنشاء حساب',
      pl: 'Utwórz konto',
      it: 'Crea un account',
    }),
    subtitle: t({
      ru: 'Присоединяйтесь к Lumio',
      en: 'Join Lumio',
      kk: 'Lumio-қа қосылыңыз',
      de: 'Lumio beitreten',
      fr: 'Rejoignez Lumio',
      es: 'Únete a Lumio',
      pt: 'Junte-se ao Lumio',
      tr: 'Lumio\'ya katılın',
      uk: 'Приєднайтесь до Lumio',
      zh: '加入 Lumio',
      ar: 'انضم إلى Lumio',
      pl: 'Dołącz do Lumio',
      it: 'Unisciti a Lumio',
    }),
    fullNameLabel: t({
      ru: 'Полное имя',
      en: 'Full name',
      kk: 'Толық аты-жөні',
      de: 'Vollständiger Name',
      fr: 'Nom complet',
      es: 'Nombre completo',
      pt: 'Nome completo',
      tr: 'Tam ad',
      uk: 'Повне ім\'я',
      zh: '全名',
      ar: 'الاسم الكامل',
      pl: 'Pełne imię i nazwisko',
      it: 'Nome completo',
    }),
    passwordLabel: t({
      ru: 'Пароль',
      en: 'Password',
      kk: 'Құпиясөз',
      de: 'Passwort',
      fr: 'Mot de passe',
      es: 'Contraseña',
      pt: 'Senha',
      tr: 'Şifre',
      uk: 'Пароль',
      zh: '密码',
      ar: 'كلمة المرور',
      pl: 'Hasło',
      it: 'Password',
    }),
    passwordHelper: t({
      ru: 'Минимум 8 символов',
      en: 'At least 8 characters',
      kk: 'Кемінде 8 таңба',
      de: 'Mindestens 8 Zeichen',
      fr: 'Au moins 8 caractères',
      es: 'Al menos 8 caracteres',
      pt: 'Pelo menos 8 caracteres',
      tr: 'En az 8 karakter',
      uk: 'Мінімум 8 символів',
      zh: '至少 8 个字符',
      ar: '8 أحرف على الأقل',
      pl: 'Co najmniej 8 znaków',
      it: 'Almeno 8 caratteri',
    }),
    companyLabel: t({
      ru: 'Компания (опционально)',
      en: 'Company (optional)',
      kk: 'Компания (міндетті емес)',
      de: 'Unternehmen (optional)',
      fr: 'Entreprise (facultatif)',
      es: 'Empresa (opcional)',
      pt: 'Empresa (opcional)',
      tr: 'Şirket (isteğe bağlı)',
      uk: 'Компанія (необов\'язково)',
      zh: '公司（可选）',
      ar: 'الشركة (اختياري)',
      pl: 'Firma (opcjonalnie)',
      it: 'Azienda (facoltativo)',
    }),
    submit: t({
      ru: 'Зарегистрироваться',
      en: 'Sign up',
      kk: 'Тіркелу',
      de: 'Registrieren',
      fr: "S'inscrire",
      es: 'Registrarse',
      pt: 'Cadastrar-se',
      tr: 'Kaydol',
      uk: 'Зареєструватися',
      zh: '注册',
      ar: 'إنشاء حساب',
      pl: 'Zarejestruj się',
      it: 'Registrati',
    }),
    haveAccount: t({
      ru: 'Уже есть аккаунт? Войти',
      en: 'Already have an account? Log in',
      kk: 'Аккаунтыңыз бар ма? Кіру',
      de: 'Bereits ein Konto? Anmelden',
      fr: 'Déjà un compte ? Se connecter',
      es: '¿Ya tienes cuenta? Iniciar sesión',
      pt: 'Já tem uma conta? Entrar',
      tr: 'Zaten hesabınız var mı? Giriş yapın',
      uk: 'Вже є акаунт? Увійти',
      zh: '已有账号？登录',
      ar: 'لديك حساب بالفعل؟ تسجيل الدخول',
      pl: 'Masz już konto? Zaloguj się',
      it: 'Hai già un account? Accedi',
    }),
    rightTitle: t({
      ru: 'Присоединяйтесь к Lumio',
      en: 'Join Lumio',
      kk: 'Lumio-қа қосылыңыз',
      de: 'Lumio beitreten',
      fr: 'Rejoignez Lumio',
      es: 'Únete a Lumio',
      pt: 'Junte-se ao Lumio',
      tr: 'Lumio\'ya katılın',
      uk: 'Приєднайтесь до Lumio',
      zh: '加入 Lumio',
      ar: 'انضم إلى Lumio',
      pl: 'Dołącz do Lumio',
      it: 'Unisciti a Lumio',
    }),
    rightTagline: t({
      ru: 'Автоматизируйте финансы уже сегодня',
      en: 'Automate your finances today',
      kk: 'Қаржыңызды бүгін автоматтандырыңыз',
      de: 'Automatisieren Sie Ihre Finanzen noch heute',
      fr: 'Automatisez vos finances dès aujourd\'hui',
      es: 'Automatiza tus finanzas hoy',
      pt: 'Automatize suas finanças hoje',
      tr: 'Finanslarınızı bugün otomatikleştirin',
      uk: 'Автоматизуйте фінанси вже сьогодні',
      zh: '今天就自动化您的财务',
      ar: 'أتمتة أموالك اليوم',
      pl: 'Zautomatyzuj swoje finanse już dziś',
      it: 'Automatizza le tue finanze oggi',
    }),
    registerFailed: t({
      ru: 'Не удалось зарегистрироваться. Попробуйте ещё раз.',
      en: 'Failed to sign up. Please try again.',
      kk: 'Тіркелу мүмкін болмады. Қайтадан көріңіз.',
      de: 'Registrierung fehlgeschlagen. Bitte versuchen Sie es erneut.',
      fr: 'Échec de l\'inscription. Veuillez réessayer.',
      es: 'Error al registrarse. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao se cadastrar. Por favor, tente novamente.',
      tr: 'Kayıt başarısız. Lütfen tekrar deneyin.',
      uk: 'Не вдалося зареєструватися. Спробуйте ще раз.',
      zh: '注册失败，请重试。',
      ar: 'فشل إنشاء الحساب. يرجى المحاولة مرة أخرى.',
      pl: 'Rejestracja nie powiodła się. Spróbuj ponownie.',
      it: 'Registrazione non riuscita. Per favore riprova.',
    }),
    googleRegisterFailed: t({
      ru: 'Не удалось зарегистрироваться через Google. Попробуйте ещё раз.',
      en: 'Failed to sign up with Google. Please try again.',
      kk: 'Google арқылы тіркелу мүмкін болмады. Қайтадан көріңіз.',
      de: 'Registrierung mit Google fehlgeschlagen. Bitte versuchen Sie es erneut.',
      fr: 'Échec de l\'inscription avec Google. Veuillez réessayer.',
      es: 'Error al registrarse con Google. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao se cadastrar com o Google. Por favor, tente novamente.',
      tr: 'Google ile kayıt başarısız. Lütfen tekrar deneyin.',
      uk: 'Не вдалося зареєструватися через Google. Спробуйте ще раз.',
      zh: '通过 Google 注册失败，请重试。',
      ar: 'فشل إنشاء الحساب عبر Google. يرجى المحاولة مرة أخرى.',
      pl: 'Rejestracja przez Google nie powiodła się. Spróbuj ponownie.',
      it: 'Registrazione con Google non riuscita. Per favore riprova.',
    }),
    orLabel: t({
      ru: 'или',
      en: 'or',
      kk: 'немесе',
      de: 'oder',
      fr: 'ou',
      es: 'o',
      pt: 'ou',
      tr: 'veya',
      uk: 'або',
      zh: '或',
      ar: 'أو',
      pl: 'lub',
      it: 'o',
    }),
    inviteLoadFailed: t({
      ru: 'Не удалось загрузить данные приглашения. Попробуйте ещё раз.',
      en: 'Failed to load invitation details. Please try again.',
      kk: 'Шақыру деректерін жүктеу мүмкін болмады. Қайтадан көріңіз.',
      de: 'Einladungsdetails konnten nicht geladen werden. Bitte versuchen Sie es erneut.',
      fr: 'Impossible de charger les détails de l\'invitation. Veuillez réessayer.',
      es: 'Error al cargar los detalles de la invitación. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao carregar detalhes do convite. Por favor, tente novamente.',
      tr: 'Davet ayrıntıları yüklenemedi. Lütfen tekrar deneyin.',
      uk: 'Не вдалося завантажити дані запрошення. Спробуйте ще раз.',
      zh: '无法加载邀请详情，请重试。',
      ar: 'فشل تحميل تفاصيل الدعوة. يرجى المحاولة مرة أخرى.',
      pl: 'Nie udało się załadować szczegółów zaproszenia. Spróbuj ponownie.',
      it: 'Impossibile caricare i dettagli dell\'invito. Per favore riprova.',
    }),
  },
} satisfies Dictionary;

export default content;
