/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'googleSheetsIntegrationPage',
  content: {
    errors: {
      loadConnections: t({
        ru: 'Не удалось загрузить подключённые таблицы',
        en: 'Failed to load connected sheets',
        kk: 'Қосылған кестелерді жүктеу мүмкін болмады',
        de: 'Verbundene Tabellen konnten nicht geladen werden',
        fr: 'Impossible de charger les feuilles connectées',
        es: 'No se pudieron cargar las hojas conectadas',
        pt: 'Falha ao carregar planilhas conectadas',
        tr: 'Bağlı tablolar yüklenemedi',
        uk: 'Не вдалося завантажити підключені таблиці',
        zh: '无法加载已连接的表格',
        ar: 'فشل تحميل الجداول المتصلة',
        pl: 'Nie udało się załadować połączonych arkuszy',
        it: 'Impossibile caricare i fogli connessi',
      }),
      missingAuthUrl: t({
        ru: 'Не удалось получить ссылку для авторизации Google',
        en: 'Failed to get Google authorization URL',
        kk: 'Google авторизация сілтемесін алу мүмкін болмады',
        de: 'Google-Autorisierungs-URL konnte nicht abgerufen werden',
        fr: 'Impossible d\'obtenir l\'URL d\'autorisation Google',
        es: 'No se pudo obtener la URL de autorización de Google',
        pt: 'Falha ao obter URL de autorização do Google',
        tr: 'Google yetkilendirme URL\'si alınamadı',
        uk: 'Не вдалося отримати посилання для авторизації Google',
        zh: '无法获取 Google 授权 URL',
        ar: 'فشل الحصول على رابط تفويض Google',
        pl: 'Nie udało się uzyskać URL autoryzacji Google',
        it: 'Impossibile ottenere l\'URL di autorizzazione Google',
      }),
      sheetIdMissing: t({
        ru: 'Укажите ID или ссылку на таблицу',
        en: 'Provide a spreadsheet ID or URL',
        kk: 'Кестенің ID немесе сілтемесін көрсетіңіз',
        de: 'Geben Sie eine Tabellen-ID oder URL an',
        fr: 'Fournissez un ID ou une URL de feuille de calcul',
        es: 'Proporciona un ID o URL de hoja de cálculo',
        pt: 'Forneça um ID ou URL de planilha',
        tr: 'Bir elektronik tablo ID\'si veya URL\'si girin',
        uk: 'Вкажіть ID або посилання на таблицю',
        zh: '请提供电子表格 ID 或 URL',
        ar: 'أدخل معرّف جدول البيانات أو عنوان URL',
        pl: 'Podaj ID lub URL arkusza',
        it: 'Fornisci un ID o URL del foglio di calcolo',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить таблицу',
        en: 'Failed to connect spreadsheet',
        kk: 'Кестені қосу мүмкін болмады',
        de: 'Tabelle konnte nicht verbunden werden',
        fr: 'Impossible de connecter la feuille de calcul',
        es: 'No se pudo conectar la hoja de cálculo',
        pt: 'Falha ao conectar planilha',
        tr: 'Elektronik tablo bağlanamadı',
        uk: 'Не вдалося підключити таблицю',
        zh: '无法连接电子表格',
        ar: 'فشل توصيل جدول البيانات',
        pl: 'Nie udało się połączyć arkusza',
        it: 'Impossibile connettere il foglio di calcolo',
      }),
      loadWorksheets: t({
        ru: 'Не удалось загрузить листы таблицы',
        en: 'Failed to load spreadsheet worksheets',
        kk: 'Кесте парақтарын жүктеу мүмкін болмады',
        de: 'Tabellenblätter konnten nicht geladen werden',
        fr: 'Impossible de charger les feuilles de calcul',
        es: 'No se pudieron cargar las hojas de la hoja de cálculo',
        pt: 'Falha ao carregar planilhas da tabela',
        tr: 'Elektronik tablo sayfaları yüklenemedi',
        uk: 'Не вдалося завантажити аркуші таблиці',
        zh: '无法加载电子表格工作表',
        ar: 'فشل تحميل أوراق جدول البيانات',
        pl: 'Nie udało się załadować arkuszy tabeli',
        it: 'Impossibile caricare i fogli di lavoro',
      }),
      spreadsheetRequired: t({
        ru: 'Сначала выберите таблицу в Google Picker',
        en: 'Choose a spreadsheet in Google Picker first',
        kk: 'Алдымен Google Picker арқылы кестені таңдаңыз',
        de: 'Wählen Sie zuerst eine Tabelle in Google Picker aus',
        fr: 'Choisissez d\'abord une feuille de calcul dans Google Picker',
        es: 'Elige primero una hoja de cálculo en Google Picker',
        pt: 'Escolha primeiro uma planilha no Google Picker',
        tr: 'Önce Google Picker\'da bir elektronik tablo seçin',
        uk: 'Спочатку виберіть таблицю в Google Picker',
        zh: '请先在 Google Picker 中选择电子表格',
        ar: 'اختر جدول بيانات في Google Picker أولاً',
        pl: 'Najpierw wybierz arkusz w Google Picker',
        it: 'Scegli prima un foglio di calcolo in Google Picker',
      }),
      syncFailed: t({
        ru: 'Не удалось синхронизировать',
        en: 'Failed to sync',
        kk: 'Синхрондау мүмкін болмады',
        de: 'Synchronisierung fehlgeschlagen',
        fr: 'Échec de la synchronisation',
        es: 'No se pudo sincronizar',
        pt: 'Falha ao sincronizar',
        tr: 'Senkronizasyon başarısız',
        uk: 'Не вдалося синхронізувати',
        zh: '同步失败',
        ar: 'فشلت المزامنة',
        pl: 'Nie udało się zsynchronizować',
        it: 'Sincronizzazione fallita',
      }),
      removeFailed: t({
        ru: 'Не удалось отключить таблицу',
        en: 'Failed to disconnect sheet',
        kk: 'Кестені ажырату мүмкін болмады',
        de: 'Tabelle konnte nicht getrennt werden',
        fr: 'Impossible de déconnecter la feuille',
        es: 'No se pudo desconectar la hoja',
        pt: 'Falha ao desconectar planilha',
        tr: 'Tablo bağlantısı kesilemedi',
        uk: 'Не вдалося відключити таблицю',
        zh: '无法断开表格连接',
        ar: 'فشل قطع اتصال الجدول',
        pl: 'Nie udało się rozłączyć arkusza',
        it: 'Impossibile disconnettere il foglio',
      }),
    },
    toasts: {
      openingAuth: t({
        ru: 'Открываем Google авторизацию…',
        en: 'Opening Google authorization…',
        kk: 'Google авторизациясы ашылуда…',
        de: 'Google-Autorisierung wird geöffnet…',
        fr: 'Ouverture de l\'autorisation Google…',
        es: 'Abriendo autorización de Google…',
        pt: 'Abrindo autorização do Google…',
        tr: 'Google yetkilendirmesi açılıyor…',
        uk: 'Відкриваємо авторизацію Google…',
        zh: '正在打开 Google 授权…',
        ar: 'جارٍ فتح تفويض Google…',
        pl: 'Otwieranie autoryzacji Google…',
        it: 'Apertura autorizzazione Google…',
      }),
      connected: t({
        ru: 'Google Sheets подключен',
        en: 'Google Sheets connected',
        kk: 'Google Sheets қосылды',
        de: 'Google Sheets verbunden',
        fr: 'Google Sheets connecté',
        es: 'Google Sheets conectado',
        pt: 'Google Sheets conectado',
        tr: 'Google Sheets bağlandı',
        uk: 'Google Sheets підключено',
        zh: 'Google Sheets 已连接',
        ar: 'تم توصيل Google Sheets',
        pl: 'Google Sheets połączony',
        it: 'Google Sheets connesso',
      }),
      syncStarted: t({
        ru: 'Синхронизация запущена',
        en: 'Sync started',
        kk: 'Синхрондау басталды',
        de: 'Synchronisierung gestartet',
        fr: 'Synchronisation démarrée',
        es: 'Sincronización iniciada',
        pt: 'Sincronização iniciada',
        tr: 'Senkronizasyon başlatıldı',
        uk: 'Синхронізацію розпочато',
        zh: '同步已开始',
        ar: 'بدأت المزامنة',
        pl: 'Synchronizacja rozpoczęta',
        it: 'Sincronizzazione avviata',
      }),
      removed: t({
        ru: 'Подключение отключено',
        en: 'Connection removed',
        kk: 'Қосылым ажыратылды',
        de: 'Verbindung entfernt',
        fr: 'Connexion supprimée',
        es: 'Conexión eliminada',
        pt: 'Conexão removida',
        tr: 'Bağlantı kaldırıldı',
        uk: 'Підключення видалено',
        zh: '连接已移除',
        ar: 'تمت إزالة الاتصال',
        pl: 'Połączenie usunięte',
        it: 'Connessione rimossa',
      }),
    },
    loginRequired: {
      title: t({
        ru: 'Войдите, чтобы подключить Google Sheets',
        en: 'Log in to connect Google Sheets',
        kk: 'Google Sheets қосу үшін кіріңіз',
        de: 'Melden Sie sich an, um Google Sheets zu verbinden',
        fr: 'Connectez-vous pour relier Google Sheets',
        es: 'Inicia sesión para conectar Google Sheets',
        pt: 'Faça login para conectar o Google Sheets',
        tr: 'Google Sheets\'i bağlamak için giriş yapın',
        uk: 'Увійдіть, щоб підключити Google Sheets',
        zh: '登录以连接 Google Sheets',
        ar: 'سجّل الدخول لتوصيل Google Sheets',
        pl: 'Zaloguj się, aby połączyć Google Sheets',
        it: 'Accedi per connettere Google Sheets',
      }),
      subtitle: t({
        ru: 'Авторизация нужна для создания привязки таблицы к вашему аккаунту.',
        en: 'Authorization is required to link a sheet to your account.',
        kk: 'Кестені аккаунтыңызға байланыстыру үшін авторизация қажет.',
        de: 'Eine Autorisierung ist erforderlich, um eine Tabelle mit Ihrem Konto zu verknüpfen.',
        fr: 'Une autorisation est requise pour lier une feuille à votre compte.',
        es: 'Se requiere autorización para vincular una hoja a tu cuenta.',
        pt: 'Autorização necessária para vincular uma planilha à sua conta.',
        tr: 'Bir sayfayı hesabınıza bağlamak için yetkilendirme gereklidir.',
        uk: 'Авторизація потрібна для прив\'язки таблиці до вашого облікового запису.',
        zh: '需要授权才能将表格链接到您的账户。',
        ar: 'التفويض مطلوب لربط جدول بيانات بحسابك.',
        pl: 'Autoryzacja jest wymagana do powiązania arkusza z kontem.',
        it: 'L\'autorizzazione è necessaria per collegare un foglio al tuo account.',
      }),
    },
    header: {
      title: t({
        ru: 'Подключение Google Sheets',
        en: 'Google Sheets connection',
        kk: 'Google Sheets қосу',
        de: 'Google Sheets-Verbindung',
        fr: 'Connexion Google Sheets',
        es: 'Conexión de Google Sheets',
        pt: 'Conexão do Google Sheets',
        tr: 'Google Sheets bağlantısı',
        uk: 'Підключення Google Sheets',
        zh: 'Google Sheets 连接',
        ar: 'اتصال Google Sheets',
        pl: 'Połączenie Google Sheets',
        it: 'Connessione Google Sheets',
      }),
      subtitle: t({
        ru: 'Укажите таблицу и лист, куда будут отправляться данные. После подключения вставьте Apps Script из документации для отправки вебхуков.',
        en: 'Specify the spreadsheet and sheet tab for sending data. After connecting, paste the Apps Script from the docs to send webhooks.',
        kk: 'Деректер жіберілетін кесте мен парақты көрсетіңіз. Қосылғаннан кейін вебхук жіберу үшін құжаттамадағы Apps Script-ті қойыңыз.',
        de: 'Geben Sie die Tabelle und das Blatt für den Datenversand an. Fügen Sie nach der Verbindung das Apps Script aus den Docs ein, um Webhooks zu senden.',
        fr: 'Spécifiez le tableur et l\'onglet pour envoyer les données. Après connexion, collez le script Apps Script de la documentation pour envoyer des webhooks.',
        es: 'Especifica la hoja de cálculo y la pestaña de hoja para enviar datos. Después de conectar, pega el Apps Script de la documentación para enviar webhooks.',
        pt: 'Especifique a planilha e a aba para envio de dados. Após conectar, cole o Apps Script da documentação para enviar webhooks.',
        tr: 'Veri gönderimi için elektronik tablo ve sayfa sekmesini belirtin. Bağlandıktan sonra, web kancaları göndermek için belgelerdeki Apps Script\'i yapıştırın.',
        uk: 'Вкажіть таблицю та аркуш, куди надсилатимуться дані. Після підключення вставте Apps Script з документації для відправки вебхуків.',
        zh: '指定用于发送数据的电子表格和工作表选项卡。连接后，粘贴文档中的 Apps Script 以发送 Webhook。',
        ar: 'حدد جدول البيانات وعلامة تبويب الورقة لإرسال البيانات. بعد الاتصال، الصق Apps Script من المستندات لإرسال webhooks.',
        pl: 'Określ arkusz kalkulacyjny i kartę arkusza do wysyłania danych. Po połączeniu wklej Apps Script z dokumentacji, aby wysyłać webhooki.',
        it: 'Specifica il foglio di calcolo e la scheda per l\'invio dei dati. Dopo la connessione, incolla Apps Script dalla documentazione per inviare webhook.',
      }),
    },
    step1: {
      label: t({
        ru: 'Шаг 1',
        en: 'Step 1',
        kk: '1-қадам',
        de: 'Schritt 1',
        fr: 'Étape 1',
        es: 'Paso 1',
        pt: 'Etapa 1',
        tr: 'Adım 1',
        uk: 'Крок 1',
        zh: '第 1 步',
        ar: 'الخطوة 1',
        pl: 'Krok 1',
        it: 'Passaggio 1',
      }),
      title: t({
        ru: 'Подключить Google Sheets',
        en: 'Connect Google Sheets',
        kk: 'Google Sheets қосу',
        de: 'Google Sheets verbinden',
        fr: 'Connecter Google Sheets',
        es: 'Conectar Google Sheets',
        pt: 'Conectar Google Sheets',
        tr: 'Google Sheets\'i bağla',
        uk: 'Підключити Google Sheets',
        zh: '连接 Google Sheets',
        ar: 'توصيل Google Sheets',
        pl: 'Połącz Google Sheets',
        it: 'Connetti Google Sheets',
      }),
      accountLabel: t({
        ru: 'Google аккаунт',
        en: 'Google account',
        kk: 'Google аккаунты',
        de: 'Google-Konto',
        fr: 'Compte Google',
        es: 'Cuenta de Google',
        pt: 'Conta Google',
        tr: 'Google hesabı',
        uk: 'Google-акаунт',
        zh: 'Google 账户',
        ar: 'حساب Google',
        pl: 'Konto Google',
        it: 'Account Google',
      }),
      accountHelp: t({
        ru: 'Подключите Google аккаунт, чтобы открыть список ваших таблиц.',
        en: 'Connect your Google account to browse your spreadsheets.',
        kk: 'Кестелер тізімін ашу үшін Google аккаунтыңызды қосыңыз.',
        de: 'Verbinden Sie Ihr Google-Konto, um Ihre Tabellen zu durchsuchen.',
        fr: 'Connectez votre compte Google pour parcourir vos feuilles de calcul.',
        es: 'Conecta tu cuenta de Google para explorar tus hojas de cálculo.',
        pt: 'Conecte sua conta Google para navegar pelas suas planilhas.',
        tr: 'Elektronik tablolarınıza göz atmak için Google hesabınızı bağlayın.',
        uk: 'Підключіть Google-акаунт, щоб переглянути список таблиць.',
        zh: '连接您的 Google 账户以浏览您的电子表格。',
        ar: 'قم بتوصيل حساب Google للتصفح بين جداول البيانات.',
        pl: 'Połącz konto Google, aby przeglądać swoje arkusze.',
        it: 'Connetti il tuo account Google per sfogliare i tuoi fogli di calcolo.',
      }),
      connectedAs: t({
        ru: 'Подключено как {email}',
        en: 'Connected as {email}',
        kk: '{email} ретінде қосылған',
        de: 'Verbunden als {email}',
        fr: 'Connecté en tant que {email}',
        es: 'Conectado como {email}',
        pt: 'Conectado como {email}',
        tr: '{email} olarak bağlandı',
        uk: 'Підключено як {email}',
        zh: '已连接为 {email}',
        ar: 'متصل بوصفك {email}',
        pl: 'Połączono jako {email}',
        it: 'Connesso come {email}',
      }),
      connectAccountButton: t({
        ru: 'Войти в Google',
        en: 'Sign in with Google',
        kk: 'Google арқылы кіру',
        de: 'Mit Google anmelden',
        fr: 'Se connecter avec Google',
        es: 'Iniciar sesión con Google',
        pt: 'Entrar com Google',
        tr: 'Google ile giriş yap',
        uk: 'Увійти через Google',
        zh: '使用 Google 登录',
        ar: 'تسجيل الدخول بواسطة Google',
        pl: 'Zaloguj się przez Google',
        it: 'Accedi con Google',
      }),
      reconnectButton: t({
        ru: 'Сменить Google аккаунт',
        en: 'Switch Google account',
        kk: 'Google аккаунтын ауыстыру',
        de: 'Google-Konto wechseln',
        fr: 'Changer de compte Google',
        es: 'Cambiar cuenta de Google',
        pt: 'Trocar conta Google',
        tr: 'Google hesabını değiştir',
        uk: 'Змінити Google-акаунт',
        zh: '切换 Google 账户',
        ar: 'تبديل حساب Google',
        pl: 'Zmień konto Google',
        it: 'Cambia account Google',
      }),
      spreadsheetLabel: t({
        ru: 'Таблица для импорта',
        en: 'Spreadsheet to import',
        kk: 'Импортталатын кесте',
        de: 'Zu importierende Tabelle',
        fr: 'Feuille de calcul à importer',
        es: 'Hoja de cálculo a importar',
        pt: 'Planilha para importar',
        tr: 'İçe aktarılacak elektronik tablo',
        uk: 'Таблиця для імпорту',
        zh: '要导入的电子表格',
        ar: 'جدول البيانات المراد استيراده',
        pl: 'Arkusz do importu',
        it: 'Foglio di calcolo da importare',
      }),
      spreadsheetHelp: t({
        ru: 'Откройте Google Picker и выберите нужную таблицу.',
        en: 'Open Google Picker and choose the spreadsheet you need.',
        kk: 'Google Picker ашып, қажетті кестені таңдаңыз.',
        de: 'Öffnen Sie Google Picker und wählen Sie die benötigte Tabelle.',
        fr: 'Ouvrez Google Picker et choisissez la feuille de calcul souhaitée.',
        es: 'Abre Google Picker y elige la hoja de cálculo que necesitas.',
        pt: 'Abra o Google Picker e escolha a planilha necessária.',
        tr: 'Google Picker\'ı açın ve ihtiyacınız olan elektronik tabloyu seçin.',
        uk: 'Відкрийте Google Picker та виберіть потрібну таблицю.',
        zh: '打开 Google Picker 并选择所需的电子表格。',
        ar: 'افتح Google Picker واختر جدول البيانات الذي تحتاجه.',
        pl: 'Otwórz Google Picker i wybierz potrzebny arkusz.',
        it: 'Apri Google Picker e scegli il foglio di calcolo di cui hai bisogno.',
      }),
      chooseSpreadsheetButton: t({
        ru: 'Выбрать таблицу',
        en: 'Choose spreadsheet',
        kk: 'Кестені таңдау',
        de: 'Tabelle auswählen',
        fr: 'Choisir la feuille de calcul',
        es: 'Elegir hoja de cálculo',
        pt: 'Escolher planilha',
        tr: 'Elektronik tablo seç',
        uk: 'Вибрати таблицю',
        zh: '选择电子表格',
        ar: 'اختر جدول البيانات',
        pl: 'Wybierz arkusz',
        it: 'Scegli foglio di calcolo',
      }),
      chooseSpreadsheetLoading: t({
        ru: 'Открываем Picker…',
        en: 'Opening Picker…',
        kk: 'Picker ашылуда…',
        de: 'Picker wird geöffnet…',
        fr: 'Ouverture du Picker…',
        es: 'Abriendo Picker…',
        pt: 'Abrindo Picker…',
        tr: 'Picker açılıyor…',
        uk: 'Відкриваємо Picker…',
        zh: '正在打开 Picker…',
        ar: 'جارٍ فتح Picker…',
        pl: 'Otwieranie Picker…',
        it: 'Apertura Picker…',
      }),
      openSpreadsheet: t({
        ru: 'Открыть таблицу',
        en: 'Open spreadsheet',
        kk: 'Кестені ашу',
        de: 'Tabelle öffnen',
        fr: 'Ouvrir la feuille de calcul',
        es: 'Abrir hoja de cálculo',
        pt: 'Abrir planilha',
        tr: 'Elektronik tabloyu aç',
        uk: 'Відкрити таблицю',
        zh: '打开电子表格',
        ar: 'افتح جدول البيانات',
        pl: 'Otwórz arkusz',
        it: 'Apri foglio di calcolo',
      }),
      nameLabel: t({
        ru: 'Название в системе',
        en: 'Name in system',
        kk: 'Жүйедегі атауы',
        de: 'Name im System',
        fr: 'Nom dans le système',
        es: 'Nombre en el sistema',
        pt: 'Nome no sistema',
        tr: 'Sistemdeki ad',
        uk: 'Назва в системі',
        zh: '系统中的名称',
        ar: 'الاسم في النظام',
        pl: 'Nazwa w systemie',
        it: 'Nome nel sistema',
      }),
      namePlaceholder: t({
        ru: 'Например: Выписки Казахстан',
        en: 'e.g. KZ statements',
        kk: 'Мысалы: Қазақстан үзінділері',
        de: 'z. B. KZ-Kontoauszüge',
        fr: 'ex. : Relevés KZ',
        es: 'p. ej. extractos KZ',
        pt: 'ex.: extratos KZ',
        tr: 'örn. KZ ekstreleri',
        uk: 'Наприклад: Виписки Казахстан',
        zh: '例如：KZ 账单',
        ar: 'مثال: كشوفات KZ',
        pl: 'np. wyciągi KZ',
        it: 'es. estratti KZ',
      }),
      nameHelp: t({
        ru: 'Если оставить пустым — используем название из Google Sheets.',
        en: 'If empty, we will use the name from Google Sheets.',
        kk: 'Бос қалдырсаңыз — Google Sheets атауы қолданылады.',
        de: 'Wenn leer, verwenden wir den Namen aus Google Sheets.',
        fr: 'Si vide, nous utiliserons le nom de Google Sheets.',
        es: 'Si está vacío, usaremos el nombre de Google Sheets.',
        pt: 'Se vazio, usaremos o nome do Google Sheets.',
        tr: 'Boş bırakırsanız Google Sheets\'teki adı kullanırız.',
        uk: 'Якщо порожнє — використаємо назву з Google Sheets.',
        zh: '如果为空，我们将使用 Google Sheets 中的名称。',
        ar: 'إذا تُرك فارغًا، سنستخدم الاسم من Google Sheets.',
        pl: 'Jeśli puste, użyjemy nazwy z Google Sheets.',
        it: 'Se vuoto, useremo il nome da Google Sheets.',
      }),
      worksheetLabel: t({
        ru: 'Лист',
        en: 'Worksheet',
        kk: 'Парақ',
        de: 'Blatt',
        fr: 'Feuille',
        es: 'Hoja',
        pt: 'Planilha',
        tr: 'Sayfa',
        uk: 'Аркуш',
        zh: '工作表',
        ar: 'ورقة العمل',
        pl: 'Arkusz',
        it: 'Foglio',
      }),
      selectWorksheet: t({
        ru: 'Выберите лист',
        en: 'Choose worksheet',
        kk: 'Парақты таңдаңыз',
        de: 'Blatt auswählen',
        fr: 'Choisir une feuille',
        es: 'Elegir hoja',
        pt: 'Escolher planilha',
        tr: 'Sayfa seç',
        uk: 'Виберіть аркуш',
        zh: '选择工作表',
        ar: 'اختر ورقة العمل',
        pl: 'Wybierz arkusz',
        it: 'Scegli foglio',
      }),
      loadingWorksheets: t({
        ru: 'Загружаем листы…',
        en: 'Loading worksheets…',
        kk: 'Парақтар жүктелуде…',
        de: 'Blätter werden geladen…',
        fr: 'Chargement des feuilles…',
        es: 'Cargando hojas…',
        pt: 'Carregando planilhas…',
        tr: 'Sayfalar yükleniyor…',
        uk: 'Завантажуємо аркуші…',
        zh: '正在加载工作表…',
        ar: 'جارٍ تحميل الأوراق…',
        pl: 'Ładowanie arkuszy…',
        it: 'Caricamento fogli…',
      }),
      connectButton: t({
        ru: 'Импортировать из таблицы',
        en: 'Import from spreadsheet',
        kk: 'Кестеден импорттау',
        de: 'Aus Tabelle importieren',
        fr: 'Importer depuis la feuille de calcul',
        es: 'Importar desde la hoja de cálculo',
        pt: 'Importar da planilha',
        tr: 'Elektronik tablodan içe aktar',
        uk: 'Імпортувати з таблиці',
        zh: '从电子表格导入',
        ar: 'استيراد من جدول البيانات',
        pl: 'Importuj z arkusza',
        it: 'Importa dal foglio di calcolo',
      }),
      successText: t({
        ru: 'После выбора таблицы Lumio сохранит подключение и сможет использовать лист для импорта и дальнейшей синхронизации.',
        en: 'After selection, Lumio saves the connection and can use the worksheet for import and future sync.',
        kk: 'Таңдаудан кейін Lumio қосылымды сақтап, парақты импорт пен кейінгі синхрон үшін қолдана алады.',
        de: 'Nach der Auswahl speichert Lumio die Verbindung und kann das Blatt für Import und zukünftige Synchronisierung verwenden.',
        fr: 'Après la sélection, Lumio enregistre la connexion et peut utiliser la feuille pour l\'import et la synchronisation future.',
        es: 'Tras la selección, Lumio guarda la conexión y puede usar la hoja para importar y sincronizar en el futuro.',
        pt: 'Após a seleção, o Lumio salva a conexão e pode usar a planilha para importação e sincronização futura.',
        tr: 'Seçimden sonra Lumio bağlantıyı kaydeder ve sayfayı içe aktarma ve gelecekteki senkronizasyon için kullanabilir.',
        uk: 'Після вибору Lumio збереже підключення і зможе використовувати аркуш для імпорту та подальшої синхронізації.',
        zh: '选择后，Lumio 保存连接，可将工作表用于导入和未来的同步。',
        ar: 'بعد الاختيار، يحفظ Lumio الاتصال ويمكنه استخدام ورقة العمل للاستيراد والمزامنة المستقبلية.',
        pl: 'Po wyborze Lumio zapisuje połączenie i może używać arkusza do importu i przyszłej synchronizacji.',
        it: 'Dopo la selezione, Lumio salva la connessione e può usare il foglio per l\'importazione e la sincronizzazione futura.',
      }),
    },
    step2: {
      label: t({
        ru: 'Шаг 2 (Advanced setup)',
        en: 'Step 2 (Advanced setup)',
        kk: '2-қадам (Қосымша баптау)',
        de: 'Schritt 2 (Erweiterte Einrichtung)',
        fr: 'Étape 2 (Configuration avancée)',
        es: 'Paso 2 (Configuración avanzada)',
        pt: 'Etapa 2 (Configuração avançada)',
        tr: 'Adım 2 (Gelişmiş kurulum)',
        uk: 'Крок 2 (Розширені налаштування)',
        zh: '第 2 步（高级设置）',
        ar: 'الخطوة 2 (الإعداد المتقدم)',
        pl: 'Krok 2 (Zaawansowana konfiguracja)',
        it: 'Passaggio 2 (Configurazione avanzata)',
      }),
      title: t({
        ru: 'Автообновление из Google Sheets (опционально)',
        en: 'Enable automatic updates from Google Sheets (optional)',
        kk: 'Google Sheets-тен авто жаңарту (міндетті емес)',
        de: 'Automatische Updates aus Google Sheets aktivieren (optional)',
        fr: 'Activer les mises à jour automatiques depuis Google Sheets (optionnel)',
        es: 'Habilitar actualizaciones automáticas desde Google Sheets (opcional)',
        pt: 'Habilitar atualizações automáticas do Google Sheets (opcional)',
        tr: 'Google Sheets\'ten otomatik güncellemeleri etkinleştir (isteğe bağlı)',
        uk: 'Автооновлення з Google Sheets (необов\'язково)',
        zh: '启用来自 Google Sheets 的自动更新（可选）',
        ar: 'تفعيل التحديثات التلقائية من Google Sheets (اختياري)',
        pl: 'Włącz automatyczne aktualizacje z Google Sheets (opcjonalnie)',
        it: 'Abilita aggiornamenti automatici da Google Sheets (opzionale)',
      }),
      description: t({
        ru: 'Скопируйте скрипт из нашей инструкции и поставьте триггер onEdit, чтобы отправлять изменения по вебхуку.',
        en: 'Copy the script from our guide and set an onEdit trigger to send changes via webhook.',
        kk: 'Нұсқаулықтағы скриптті көшіріп, өзгерістерді вебхук арқылы жіберу үшін onEdit триггерін орнатыңыз.',
        de: 'Kopieren Sie das Skript aus unserem Leitfaden und setzen Sie einen onEdit-Trigger, um Änderungen per Webhook zu senden.',
        fr: 'Copiez le script de notre guide et définissez un déclencheur onEdit pour envoyer les modifications via webhook.',
        es: 'Copia el script de nuestra guía y configura un trigger onEdit para enviar cambios por webhook.',
        pt: 'Copie o script do nosso guia e defina um gatilho onEdit para enviar alterações via webhook.',
        tr: 'Kılavuzumuzdaki komut dosyasını kopyalayın ve webhook aracılığıyla değişiklikleri göndermek için bir onEdit tetikleyicisi ayarlayın.',
        uk: 'Скопіюйте скрипт з нашої інструкції та встановіть тригер onEdit для надсилання змін через вебхук.',
        zh: '从我们的指南中复制脚本，并设置 onEdit 触发器通过 Webhook 发送更改。',
        ar: 'انسخ النص البرمجي من دليلنا واضبط مشغّل onEdit لإرسال التغييرات عبر webhook.',
        pl: 'Skopiuj skrypt z naszego przewodnika i ustaw wyzwalacz onEdit, aby wysyłać zmiany przez webhook.',
        it: 'Copia lo script dalla nostra guida e imposta un trigger onEdit per inviare le modifiche tramite webhook.',
      }),
      appsScriptDoc: t({
        ru: 'Инструкция по Apps Script',
        en: 'Apps Script guide',
        kk: 'Apps Script нұсқаулығы',
        de: 'Apps Script-Anleitung',
        fr: 'Guide Apps Script',
        es: 'Guía de Apps Script',
        pt: 'Guia de Apps Script',
        tr: 'Apps Script kılavuzu',
        uk: 'Інструкція з Apps Script',
        zh: 'Apps Script 指南',
        ar: 'دليل Apps Script',
        pl: 'Przewodnik Apps Script',
        it: 'Guida Apps Script',
      }),
      openSheets: t({
        ru: 'Открыть Google Sheets',
        en: 'Open Google Sheets',
        kk: 'Google Sheets ашу',
        de: 'Google Sheets öffnen',
        fr: 'Ouvrir Google Sheets',
        es: 'Abrir Google Sheets',
        pt: 'Abrir Google Sheets',
        tr: 'Google Sheets\'i aç',
        uk: 'Відкрити Google Sheets',
        zh: '打开 Google Sheets',
        ar: 'فتح Google Sheets',
        pl: 'Otwórz Google Sheets',
        it: 'Apri Google Sheets',
      }),
      webhookEndpointLabel: t({
        ru: 'Эндпоинт вебхука',
        en: 'Webhook endpoint',
        kk: 'Вебхук эндпоинты',
        de: 'Webhook-Endpunkt',
        fr: 'Point de terminaison webhook',
        es: 'Endpoint de webhook',
        pt: 'Endpoint de webhook',
        tr: 'Webhook uç noktası',
        uk: 'Endpoint вебхука',
        zh: 'Webhook 端点',
        ar: 'نقطة نهاية webhook',
        pl: 'Punkt końcowy webhook',
        it: 'Endpoint webhook',
      }),
      webhookHeaderLabel: t({
        ru: 'Заголовок',
        en: 'Header',
        kk: 'Тақырыпша',
        de: 'Header',
        fr: 'En-tête',
        es: 'Encabezado',
        pt: 'Cabeçalho',
        tr: 'Başlık',
        uk: 'Заголовок',
        zh: '请求头',
        ar: 'الترويسة',
        pl: 'Nagłówek',
        it: 'Intestazione',
      }),
      webhookTokenHint: t({
        ru: 'ваш токен',
        en: 'your token',
        kk: 'сіздің токеніңіз',
        de: 'Ihr Token',
        fr: 'votre jeton',
        es: 'tu token',
        pt: 'seu token',
        tr: 'tokenınız',
        uk: 'ваш токен',
        zh: '您的令牌',
        ar: 'رمزك المميز',
        pl: 'twój token',
        it: 'il tuo token',
      }),
      showTechnicalDetails: t({
        ru: 'Показать технические детали',
        en: 'Show technical details',
        kk: 'Техникалық бөлшектерді көрсету',
        de: 'Technische Details anzeigen',
        fr: 'Afficher les détails techniques',
        es: 'Mostrar detalles técnicos',
        pt: 'Mostrar detalhes técnicos',
        tr: 'Teknik detayları göster',
        uk: 'Показати технічні деталі',
        zh: '显示技术详情',
        ar: 'عرض التفاصيل التقنية',
        pl: 'Pokaż szczegóły techniczne',
        it: 'Mostra dettagli tecnici',
      }),
    },
    list: {
      title: t({
        ru: 'Подключённые таблицы',
        en: 'Connected sheets',
        kk: 'Қосылған кестелер',
        de: 'Verbundene Tabellen',
        fr: 'Feuilles connectées',
        es: 'Hojas conectadas',
        pt: 'Planilhas conectadas',
        tr: 'Bağlı tablolar',
        uk: 'Підключені таблиці',
        zh: '已连接的表格',
        ar: 'الجداول المتصلة',
        pl: 'Połączone arkusze',
        it: 'Fogli connessi',
      }),
      subtitle: t({
        ru: 'Автообновление по вебхуку',
        en: 'Auto updates via webhook',
        kk: 'Вебхук арқылы авто жаңарту',
        de: 'Automatische Updates per Webhook',
        fr: 'Mises à jour automatiques via webhook',
        es: 'Actualizaciones automáticas por webhook',
        pt: 'Atualizações automáticas via webhook',
        tr: 'Webhook aracılığıyla otomatik güncellemeler',
        uk: 'Автооновлення через вебхук',
        zh: '通过 Webhook 自动更新',
        ar: 'تحديثات تلقائية عبر webhook',
        pl: 'Automatyczne aktualizacje przez webhook',
        it: 'Aggiornamenti automatici tramite webhook',
      }),
      empty: t({
        ru: 'Пока нет подключений. Добавьте первую таблицу через форму слева.',
        en: 'No connections yet. Add your first sheet using the form on the left.',
        kk: 'Әзірше қосылымдар жоқ. Сол жақтағы форма арқылы бірінші кестені қосыңыз.',
        de: 'Noch keine Verbindungen. Fügen Sie Ihre erste Tabelle über das Formular links hinzu.',
        fr: 'Aucune connexion pour l\'instant. Ajoutez votre première feuille via le formulaire à gauche.',
        es: 'Aún no hay conexiones. Agrega tu primera hoja usando el formulario de la izquierda.',
        pt: 'Nenhuma conexão ainda. Adicione sua primeira planilha usando o formulário à esquerda.',
        tr: 'Henüz bağlantı yok. Sol taraftaki formu kullanarak ilk tablonuzu ekleyin.',
        uk: 'Поки немає підключень. Додайте першу таблицю через форму зліва.',
        zh: '暂无连接。使用左侧的表单添加您的第一个表格。',
        ar: 'لا توجد اتصالات حتى الآن. أضف أول جدول باستخدام النموذج على اليسار.',
        pl: 'Brak połączeń. Dodaj pierwszy arkusz używając formularza po lewej.',
        it: 'Nessuna connessione ancora. Aggiungi il tuo primo foglio usando il modulo a sinistra.',
      }),
      badges: {
        oauthNeeded: t({
          ru: 'Нужен OAuth',
          en: 'OAuth needed',
          kk: 'OAuth қажет',
          de: 'OAuth erforderlich',
          fr: 'OAuth requis',
          es: 'Se necesita OAuth',
          pt: 'OAuth necessário',
          tr: 'OAuth gerekli',
          uk: 'Потрібен OAuth',
          zh: '需要 OAuth',
          ar: 'OAuth مطلوب',
          pl: 'Wymagany OAuth',
          it: 'OAuth richiesto',
        }),
        active: t({
          ru: 'Активно',
          en: 'Active',
          kk: 'Белсенді',
          de: 'Aktiv',
          fr: 'Actif',
          es: 'Activo',
          pt: 'Ativo',
          tr: 'Aktif',
          uk: 'Активно',
          zh: '活跃',
          ar: 'نشط',
          pl: 'Aktywne',
          it: 'Attivo',
        }),
      },
      fields: {
        idPrefix: t({ ru: 'ID', en: 'ID', kk: 'ID', de: 'ID', fr: 'ID', es: 'ID', pt: 'ID', tr: 'ID', uk: 'ID', zh: 'ID', ar: 'المعرّف', pl: 'ID', it: 'ID' }),
        worksheetPrefix: t({
          ru: 'Лист',
          en: 'Sheet',
          kk: 'Парақ',
          de: 'Blatt',
          fr: 'Feuille',
          es: 'Hoja',
          pt: 'Planilha',
          tr: 'Sayfa',
          uk: 'Аркуш',
          zh: '工作表',
          ar: 'الورقة',
          pl: 'Arkusz',
          it: 'Foglio',
        }),
        lastSyncPrefix: t({
          ru: 'Последняя синхронизация',
          en: 'Last sync',
          kk: 'Соңғы синхрондау',
          de: 'Letzte Synchronisierung',
          fr: 'Dernière synchronisation',
          es: 'Última sincronización',
          pt: 'Última sincronização',
          tr: 'Son senkronizasyon',
          uk: 'Остання синхронізація',
          zh: '最后同步',
          ar: 'آخر مزامنة',
          pl: 'Ostatnia synchronizacja',
          it: 'Ultima sincronizzazione',
        }),
      },
      actions: {
        authorize: t({
          ru: 'Авторизовать',
          en: 'Authorize',
          kk: 'Авторизация',
          de: 'Autorisieren',
          fr: 'Autoriser',
          es: 'Autorizar',
          pt: 'Autorizar',
          tr: 'Yetkilendir',
          uk: 'Авторизувати',
          zh: '授权',
          ar: 'تفويض',
          pl: 'Autoryzuj',
          it: 'Autorizza',
        }),
        sync: t({
          ru: 'Синхронизировать',
          en: 'Sync',
          kk: 'Синхрондау',
          de: 'Synchronisieren',
          fr: 'Synchroniser',
          es: 'Sincronizar',
          pt: 'Sincronizar',
          tr: 'Senkronize et',
          uk: 'Синхронізувати',
          zh: '同步',
          ar: 'مزامنة',
          pl: 'Synchronizuj',
          it: 'Sincronizza',
        }),
        disconnect: t({
          ru: 'Отключить',
          en: 'Disconnect',
          kk: 'Ажырату',
          de: 'Trennen',
          fr: 'Déconnecter',
          es: 'Desconectar',
          pt: 'Desconectar',
          tr: 'Bağlantıyı kes',
          uk: 'Відключити',
          zh: '断开连接',
          ar: 'قطع الاتصال',
          pl: 'Rozłącz',
          it: 'Disconnetti',
        }),
      },
      dash: t({ ru: '—', en: '—', kk: '—', de: '—', fr: '—', es: '—', pt: '—', tr: '—', uk: '—', zh: '—', ar: '—', pl: '—', it: '—' }),
    },
  },
} satisfies Dictionary;

export default content;
