import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTablesPage',
  content: {
    header: {
      title: t({ ru: 'Таблицы', en: 'Tables', kk: 'Кестелер', de: 'Tabellen', fr: 'Tableaux', es: 'Tablas', pt: 'Tabelas', tr: 'Tablolar', uk: 'Таблиці', zh: '表格', ar: 'الجداول', pl: 'Tabele', it: 'Tabelle' }),
      subtitle: t({
        ru: 'Создавайте и управляйте структурированными таблицами из выписок и чеков для бухгалтерии и отчетности.',
        en: 'Export and manage structured tables created from statements and receipts for accounting and reporting.',
        kk: 'Бухгалтерия және есеп беру үшін үзінділер мен чектерден жасалған құрылымдалған кестелерді басқарыңыз.',
        de: 'Exportieren und verwalten Sie strukturierte Tabellen aus Kontoauszügen und Belegen für Buchhaltung und Berichte.',
        fr: 'Exportez et gérez des tableaux structurés créés à partir de relevés et de reçus pour la comptabilité et les rapports.',
        es: 'Exporte y administre tablas estructuradas creadas a partir de estados de cuenta y recibos para contabilidad e informes.',
        pt: 'Exporte e gerencie tabelas estruturadas criadas a partir de extratos e recibos para contabilidade e relatórios.',
        tr: 'Muhasebe ve raporlama için hesap özetleri ve makbuzlardan oluşturulan yapılandırılmış tabloları dışa aktarın ve yönetin.',
        uk: 'Експортуйте та керуйте структурованими таблицями, створеними з виписок та чеків для бухгалтерії та звітності.',
        zh: '导出并管理从对账单和收据创建的结构化表格，用于会计和报告。',
        ar: 'قم بتصدير وإدارة الجداول المنظمة المنشأة من كشوف الحسابات والإيصالات للمحاسبة وإعداد التقارير.',
        pl: 'Eksportuj i zarządzaj ustrukturyzowanymi tabelami tworzonymi z wyciągów i paragonów na potrzeby księgowości i raportowania.',
        it: 'Esporta e gestisci tabelle strutturate create da estratti conto e ricevute per la contabilità e la reportistica.',
      }),
    },
    searchPlaceholder: t({
      ru: 'Поиск таблиц...',
      en: 'Search tables...',
      kk: 'Кестелерді іздеу...',
      de: 'Tabellen suchen...',
      fr: 'Rechercher des tableaux...',
      es: 'Buscar tablas...',
      pt: 'Pesquisar tabelas...',
      tr: 'Tabloları ara...',
      uk: 'Пошук таблиць...',
      zh: '搜索表格...',
      ar: 'البحث في الجداول...',
      pl: 'Szukaj tabel...',
      it: 'Cerca tabelle...',
    }),
    auth: {
      loading: t({ ru: 'Загрузка...', en: 'Loading...', kk: 'Жүктелуде...', de: 'Laden...', fr: 'Chargement...', es: 'Cargando...', pt: 'Carregando...', tr: 'Yükleniyor...', uk: 'Завантаження...', zh: '加载中...', ar: 'جارٍ التحميل...', pl: 'Ładowanie...', it: 'Caricamento...' }),
      loginRequired: t({
        ru: 'Войдите в систему, чтобы просматривать таблицы.',
        en: 'Log in to view tables.',
        kk: 'Кестелерді көру үшін жүйеге кіріңіз.',
        de: 'Melden Sie sich an, um Tabellen anzuzeigen.',
        fr: 'Connectez-vous pour afficher les tableaux.',
        es: 'Inicie sesión para ver las tablas.',
        pt: 'Faça login para visualizar as tabelas.',
        tr: 'Tabloları görüntülemek için giriş yapın.',
        uk: 'Увійдіть, щоб переглядати таблиці.',
        zh: '登录以查看表格。',
        ar: 'قم بتسجيل الدخول لعرض الجداول.',
        pl: 'Zaloguj się, aby przeglądać tabele.',
        it: 'Accedi per visualizzare le tabelle.',
      }),
    },
    actions: {
      create: t({ ru: 'Создать', en: 'Create', kk: 'Құру', de: 'Erstellen', fr: 'Créer', es: 'Crear', pt: 'Criar', tr: 'Oluştur', uk: 'Створити', zh: '创建', ar: 'إنشاء', pl: 'Utwórz', it: 'Crea' }),
      createExportTable: t({
        ru: 'Создать экспортную таблицу',
        en: 'Create export table',
        kk: 'Экспорт кестесін құру',
        de: 'Exporttabelle erstellen',
        fr: 'Créer un tableau d\'export',
        es: 'Crear tabla de exportación',
        pt: 'Criar tabela de exportação',
        tr: 'Dışa aktarma tablosu oluştur',
        uk: 'Створити таблицю експорту',
        zh: '创建导出表格',
        ar: 'إنشاء جدول تصدير',
        pl: 'Utwórz tabelę eksportu',
        it: 'Crea tabella di esportazione',
      }),
      createFirstExportTable: t({
        ru: 'Создать первую экспортную таблицу',
        en: 'Create your first export table',
        kk: 'Бірінші экспорт кестесін құру',
        de: 'Erste Exporttabelle erstellen',
        fr: 'Créer votre premier tableau d\'export',
        es: 'Crear su primera tabla de exportación',
        pt: 'Criar sua primeira tabela de exportação',
        tr: 'İlk dışa aktarma tablonuzu oluşturun',
        uk: 'Створити першу таблицю експорту',
        zh: '创建您的第一个导出表格',
        ar: 'أنشئ أول جدول تصدير لك',
        pl: 'Utwórz swoją pierwszą tabelę eksportu',
        it: 'Crea la tua prima tabella di esportazione',
      }),
      open: t({ ru: 'Открыть', en: 'Open', kk: 'Ашу', de: 'Öffnen', fr: 'Ouvrir', es: 'Abrir', pt: 'Abrir', tr: 'Aç', uk: 'Відкрити', zh: '打开', ar: 'فتح', pl: 'Otwórz', it: 'Apri' }),
      export: t({ ru: 'Экспорт', en: 'Export', kk: 'Экспорт', de: 'Exportieren', fr: 'Exporter', es: 'Exportar', pt: 'Exportar', tr: 'Dışa aktar', uk: 'Експорт', zh: '导出', ar: 'تصدير', pl: 'Eksport', it: 'Esporta' }),
      exportCsv: t({ ru: 'CSV', en: 'CSV', kk: 'CSV', de: 'CSV', fr: 'CSV', es: 'CSV', pt: 'CSV', tr: 'CSV', uk: 'CSV', zh: 'CSV', ar: 'CSV', pl: 'CSV', it: 'CSV' }),
      exportXlsx: t({ ru: 'XLSX', en: 'XLSX', kk: 'XLSX', de: 'XLSX', fr: 'XLSX', es: 'XLSX', pt: 'XLSX', tr: 'XLSX', uk: 'XLSX', zh: 'XLSX', ar: 'XLSX', pl: 'XLSX', it: 'XLSX' }),
      updateData: t({ ru: 'Обновить данные', en: 'Update data', kk: 'Деректерді жаңарту', de: 'Daten aktualisieren', fr: 'Mettre à jour les données', es: 'Actualizar datos', pt: 'Atualizar dados', tr: 'Verileri güncelle', uk: 'Оновити дані', zh: '更新数据', ar: 'تحديث البيانات', pl: 'Aktualizuj dane', it: 'Aggiorna dati' }),
      importTable: t({
        ru: 'Импорт таблицы',
        en: 'Import table',
        kk: 'Кестені импорттау',
        de: 'Tabelle importieren',
        fr: 'Importer un tableau',
        es: 'Importar tabla',
        pt: 'Importar tabela',
        tr: 'Tablo içe aktar',
        uk: 'Імпортувати таблицю',
        zh: '导入表格',
        ar: 'استيراد الجدول',
        pl: 'Importuj tabelę',
        it: 'Importa tabella',
      }),
      fromStatement: t({
        ru: 'Из выписки',
        en: 'From statement',
        kk: 'Үзіндіден',
        de: 'Aus Kontoauszug',
        fr: 'Depuis un relevé',
        es: 'Desde estado de cuenta',
        pt: 'Do extrato',
        tr: 'Özetten',
        uk: 'З виписки',
        zh: '从对账单',
        ar: 'من كشف الحساب',
        pl: 'Z wyciągu',
        it: 'Da estratto conto',
      }),
      importGoogleSheets: t({
        ru: 'Импорт из Google Sheets',
        en: 'Import from Google Sheets',
        kk: 'Google Sheets-тен импорт',
        de: 'Von Google Sheets importieren',
        fr: 'Importer depuis Google Sheets',
        es: 'Importar desde Google Sheets',
        pt: 'Importar do Google Sheets',
        tr: 'Google Sheets\'ten içe aktar',
        uk: 'Імпорт з Google Sheets',
        zh: '从 Google 表格导入',
        ar: 'استيراد من Google Sheets',
        pl: 'Importuj z Google Sheets',
        it: 'Importa da Google Sheets',
      }),
      createBlankTable: t({
        ru: 'Создать пустую таблицу',
        en: 'Create blank table',
        kk: 'Бос кесте құру',
        de: 'Leere Tabelle erstellen',
        fr: 'Créer un tableau vide',
        es: 'Crear tabla en blanco',
        pt: 'Criar tabela em branco',
        tr: 'Boş tablo oluştur',
        uk: 'Створити порожню таблицю',
        zh: '创建空白表格',
        ar: 'إنشاء جدول فارغ',
        pl: 'Utwórz pustą tabelę',
        it: 'Crea tabella vuota',
      }),
      close: t({ ru: 'Закрыть', en: 'Close', kk: 'Жабу', de: 'Schließen', fr: 'Fermer', es: 'Cerrar', pt: 'Fechar', tr: 'Kapat', uk: 'Закрити', zh: '关闭', ar: 'إغلاق', pl: 'Zamknij', it: 'Chiudi' }),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla' }),
      delete: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina' }),
      previous: t({ ru: 'Предыдущая', en: 'Previous', kk: 'Алдыңғы', de: 'Zurück', fr: 'Précédent', es: 'Anterior', pt: 'Anterior', tr: 'Önceki', uk: 'Попередня', zh: '上一页', ar: 'السابق', pl: 'Poprzednia', it: 'Precedente' }),
      next: t({ ru: 'Следующая', en: 'Next', kk: 'Келесі', de: 'Weiter', fr: 'Suivant', es: 'Siguiente', pt: 'Próxima', tr: 'Sonraki', uk: 'Наступна', zh: '下一页', ar: 'التالي', pl: 'Następna', it: 'Successivo' }),
    },
    sources: {
      label: t({ ru: 'Источник', en: 'Source', kk: 'Дереккөз', de: 'Quelle', fr: 'Source', es: 'Fuente', pt: 'Fonte', tr: 'Kaynak', uk: 'Джерело', zh: '来源', ar: 'المصدر', pl: 'Źródło', it: 'Fonte' }),
      googleSheets: t({
        ru: 'Google Sheets',
        en: 'Google Sheets',
        kk: 'Google Sheets',
        de: 'Google Sheets',
        fr: 'Google Sheets',
        es: 'Google Sheets',
        pt: 'Google Sheets',
        tr: 'Google Sheets',
        uk: 'Google Sheets',
        zh: 'Google 表格',
        ar: 'Google Sheets',
        pl: 'Google Sheets',
        it: 'Google Sheets',
      }),
      manual: t({ ru: 'Вручную', en: 'Manual', kk: 'Қолмен', de: 'Manuell', fr: 'Manuel', es: 'Manual', pt: 'Manual', tr: 'Manuel', uk: 'Вручну', zh: '手动', ar: 'يدوي', pl: 'Ręcznie', it: 'Manuale' }),
    },
    filters: {
      all: t({ ru: 'Все', en: 'All', kk: 'Барлығы', de: 'Alle', fr: 'Tous', es: 'Todos', pt: 'Todos', tr: 'Tümü', uk: 'Всі', zh: '全部', ar: 'الكل', pl: 'Wszystkie', it: 'Tutti' }),
      fromStatement: t({ ru: 'Из выписки', en: 'From statement', kk: 'Үзіндіден', de: 'Aus Kontoauszug', fr: 'Depuis un relevé', es: 'Desde estado de cuenta', pt: 'Do extrato', tr: 'Özetten', uk: 'З виписки', zh: '从对账单', ar: 'من كشف الحساب', pl: 'Z wyciągu', it: 'Da estratto conto' }),
      sortUpdated: t({ ru: 'Последние изменения', en: 'Recent updates', kk: 'Соңғы өзгерістер', de: 'Zuletzt geändert', fr: 'Mises à jour récentes', es: 'Actualizaciones recientes', pt: 'Atualizações recentes', tr: 'Son güncellemeler', uk: 'Останні зміни', zh: '最近更新', ar: 'التحديثات الأخيرة', pl: 'Ostatnie zmiany', it: 'Aggiornamenti recenti' }),
      sortName: t({ ru: 'По названию', en: 'By name', kk: 'Атауы бойынша', de: 'Nach Name', fr: 'Par nom', es: 'Por nombre', pt: 'Por nome', tr: 'İsme göre', uk: 'За назвою', zh: '按名称', ar: 'حسب الاسم', pl: 'Według nazwy', it: 'Per nome' }),
      sort: t({ ru: 'Сортировка', en: 'Sort', kk: 'Сұрыптау', de: 'Sortieren', fr: 'Trier', es: 'Ordenar', pt: 'Ordenar', tr: 'Sırala', uk: 'Сортування', zh: '排序', ar: 'ترتيب', pl: 'Sortuj', it: 'Ordina' }),
      filters: t({ ru: 'Фильтры', en: 'Filters', kk: 'Сүзгілер', de: 'Filter', fr: 'Filtres', es: 'Filtros', pt: 'Filtros', tr: 'Filtreler', uk: 'Фільтри', zh: '筛选', ar: 'الفلاتر', pl: 'Filtry', it: 'Filtri' }),
      apply: t({ ru: 'Применить', en: 'Apply', kk: 'Қолдану', de: 'Anwenden', fr: 'Appliquer', es: 'Aplicar', pt: 'Aplicar', tr: 'Uygula', uk: 'Застосувати', zh: '应用', ar: 'تطبيق', pl: 'Zastosuj', it: 'Applica' }),
      reset: t({ ru: 'Сбросить', en: 'Reset', kk: 'Қалпына келтіру', de: 'Zurücksetzen', fr: 'Réinitialiser', es: 'Restablecer', pt: 'Redefinir', tr: 'Sıfırla', uk: 'Скинути', zh: '重置', ar: 'إعادة تعيين', pl: 'Resetuj', it: 'Reimposta' }),
      resetFilters: t({
        ru: 'Сбросить фильтры',
        en: 'Reset filters',
        kk: 'Сүзгілерді қалпына келтіру',
        de: 'Filter zurücksetzen',
        fr: 'Réinitialiser les filtres',
        es: 'Restablecer filtros',
        pt: 'Redefinir filtros',
        tr: 'Filtreleri sıfırla',
        uk: 'Скинути фільтри',
        zh: '重置筛选',
        ar: 'إعادة تعيين الفلاتر',
        pl: 'Resetuj filtry',
        it: 'Reimposta filtri',
      }),
      viewResults: t({ ru: 'Показать', en: 'View results', kk: 'Нәтижені көру', de: 'Ergebnisse anzeigen', fr: 'Voir les résultats', es: 'Ver resultados', pt: 'Ver resultados', tr: 'Sonuçları gör', uk: 'Показати результати', zh: '查看结果', ar: 'عرض النتائج', pl: 'Pokaż wyniki', it: 'Visualizza risultati' }),
      saveSearch: t({ ru: 'Сохранить поиск', en: 'Save search', kk: 'Іздеуді сақтау', de: 'Suche speichern', fr: 'Enregistrer la recherche', es: 'Guardar búsqueda', pt: 'Salvar pesquisa', tr: 'Aramayı kaydet', uk: 'Зберегти пошук', zh: '保存搜索', ar: 'حفظ البحث', pl: 'Zapisz wyszukiwanie', it: 'Salva ricerca' }),
      any: t({ ru: 'Любой', en: 'Any', kk: 'Кез келген', de: 'Beliebig', fr: 'N\'importe lequel', es: 'Cualquiera', pt: 'Qualquer', tr: 'Herhangi biri', uk: 'Будь-який', zh: '任意', ar: 'أي', pl: 'Dowolny', it: 'Qualsiasi' }),
      drawerTitle: t({ ru: 'Фильтры', en: 'Filters', kk: 'Сүзгілер', de: 'Filter', fr: 'Filtres', es: 'Filtros', pt: 'Filtros', tr: 'Filtreler', uk: 'Фільтри', zh: '筛选', ar: 'الفلاتر', pl: 'Filtry', it: 'Filtri' }),
      drawerGeneral: t({ ru: 'Основное', en: 'General', kk: 'Негізгі', de: 'Allgemein', fr: 'Général', es: 'General', pt: 'Geral', tr: 'Genel', uk: 'Загальне', zh: '常规', ar: 'عام', pl: 'Ogólne', it: 'Generale' }),
    },
    sidePanel: {
      subtitle: t({ ru: 'Обзор', en: 'Overview', kk: 'Шолу', de: 'Übersicht', fr: 'Aperçu', es: 'Resumen', pt: 'Visão geral', tr: 'Genel bakış', uk: 'Огляд', zh: '概览', ar: 'نظرة عامة', pl: 'Przegląd', it: 'Panoramica' }),
      todoTitle: t({ ru: 'К выполнению', en: 'To-do', kk: 'Аяқтау керек', de: 'Aufgaben', fr: 'À faire', es: 'Por hacer', pt: 'A fazer', tr: 'Yapılacaklar', uk: 'До виконання', zh: '待办事项', ar: 'المهام', pl: 'Do zrobienia', it: 'Da fare' }),
      accountingTitle: t({ ru: 'Бухгалтерия', en: 'Accounting', kk: 'Бухгалтерия', de: 'Buchhaltung', fr: 'Comptabilité', es: 'Contabilidad', pt: 'Contabilidade', tr: 'Muhasebe', uk: 'Бухгалтерія', zh: '会计', ar: 'المحاسبة', pl: 'Księgowość', it: 'Contabilità' }),
      insightsTitle: t({ ru: 'Инсайты', en: 'Insights', kk: 'Инсайттар', de: 'Einblicke', fr: 'Insights', es: 'Perspectivas', pt: 'Insights', tr: 'Öngörüler', uk: 'Інсайти', zh: '洞察', ar: 'الرؤى', pl: 'Spostrzeżenia', it: 'Approfondimenti' }),
      allTables: t({ ru: 'Все таблицы', en: 'All tables', kk: 'Барлық кестелер', de: 'Alle Tabellen', fr: 'Tous les tableaux', es: 'Todas las tablas', pt: 'Todas as tabelas', tr: 'Tüm tablolar', uk: 'Всі таблиці', zh: '所有表格', ar: 'كل الجداول', pl: 'Wszystkie tabele', it: 'Tutte le tabelle' }),
      sourceOverview: t({
        ru: 'Обзор источников',
        en: 'Sources overview',
        kk: 'Дереккөздер шолуы',
        de: 'Quellenübersicht',
        fr: 'Aperçu des sources',
        es: 'Resumen de fuentes',
        pt: 'Visão geral das fontes',
        tr: 'Kaynaklara genel bakış',
        uk: 'Огляд джерел',
        zh: '来源概览',
        ar: 'نظرة عامة على المصادر',
        pl: 'Przegląd źródeł',
        it: 'Panoramica delle fonti',
      }),
      noData: t({ ru: 'Нет данных', en: 'No data', kk: 'Дерек жоқ', de: 'Keine Daten', fr: 'Aucune donnée', es: 'Sin datos', pt: 'Sem dados', tr: 'Veri yok', uk: 'Немає даних', zh: '暂无数据', ar: 'لا توجد بيانات', pl: 'Brak danych', it: 'Nessun dato' }),
      createTable: t({ ru: 'Создать таблицу', en: 'Create table', kk: 'Кесте құру', de: 'Tabelle erstellen', fr: 'Créer un tableau', es: 'Crear tabla', pt: 'Criar tabela', tr: 'Tablo oluştur', uk: 'Створити таблицю', zh: '创建表格', ar: 'إنشاء جدول', pl: 'Utwórz tabelę', it: 'Crea tabella' }),
      openMenu: t({
        ru: 'Открыть действия таблиц',
        en: 'Open table actions',
        kk: 'Кесте әрекеттерін ашу',
        de: 'Tabellenaktionen öffnen',
        fr: 'Ouvrir les actions du tableau',
        es: 'Abrir acciones de tabla',
        pt: 'Abrir ações da tabela',
        tr: 'Tablo eylemlerini aç',
        uk: 'Відкрити дії таблиці',
        zh: '打开表格操作',
        ar: 'فتح إجراءات الجدول',
        pl: 'Otwórz akcje tabeli',
        it: 'Apri azioni tabella',
      }),
    },
    fromLabel: t({ ru: 'Источник', en: 'From', kk: 'Көзі', de: 'Von', fr: 'De', es: 'De', pt: 'De', tr: 'Kaynak', uk: 'Джерело', zh: '来自', ar: 'من', pl: 'Od', it: 'Da' }),
    growthHint: t({
      ru: 'Вы можете создать несколько экспортных таблиц для разных отчетов или периодов.',
      en: 'You can create multiple export tables for different reports or periods.',
      kk: 'Әртүрлі есептер мен кезеңдер үшін бірнеше экспорт кестесін жасай аласыз.',
      de: 'Sie können mehrere Exporttabellen für verschiedene Berichte oder Zeiträume erstellen.',
      fr: 'Vous pouvez créer plusieurs tableaux d\'export pour différents rapports ou périodes.',
      es: 'Puede crear múltiples tablas de exportación para diferentes informes o períodos.',
      pt: 'Você pode criar várias tabelas de exportação para diferentes relatórios ou períodos.',
      tr: 'Farklı raporlar veya dönemler için birden fazla dışa aktarma tablosu oluşturabilirsiniz.',
      uk: 'Ви можете створити кілька таблиць експорту для різних звітів або періодів.',
      zh: '您可以为不同的报告或时段创建多个导出表格。',
      ar: 'يمكنك إنشاء جداول تصدير متعددة لتقارير أو فترات مختلفة.',
      pl: 'Możesz tworzyć wiele tabel eksportu dla różnych raportów lub okresów.',
      it: 'Puoi creare più tabelle di esportazione per diversi report o periodi.',
    }),
    namingHint: t({
      ru: 'Используйте понятные имена: Расходы экспорт - Feb 2026, VAT reconciliation - Q1, Bank statements export.',
      en: 'Try clear names: Expenses export - Feb 2026, VAT reconciliation - Q1, Bank statements export.',
      kk: 'Түсінікті атауларды қолданыңыз: Expenses export - Feb 2026, VAT reconciliation - Q1, Bank statements export.',
      de: 'Verwenden Sie klare Namen: Ausgaben Export - Feb 2026, MwSt.-Abgleich - Q1, Kontoauszüge Export.',
      fr: 'Utilisez des noms clairs : Export dépenses - Feb 2026, Rapprochement TVA - Q1, Export relevés bancaires.',
      es: 'Use nombres claros: Exportación de gastos - Feb 2026, Conciliación IVA - Q1, Exportación de estados de cuenta.',
      pt: 'Use nomes claros: Exportação de despesas - Fev 2026, Reconciliação de IVA - Q1, Exportação de extratos bancários.',
      tr: 'Açık isimler kullanın: Gider ihracatı - Şub 2026, KDV mutabakatı - Q1, Banka özeti ihracatı.',
      uk: 'Використовуйте зрозумілі назви: Витрати експорт - Feb 2026, Звірка ПДВ - Q1, Експорт виписок.',
      zh: '使用清晰的名称：费用导出 - 2026年2月，增值税对账 - Q1，银行对账单导出。',
      ar: 'استخدم أسماء واضحة: تصدير المصروفات - فبراير 2026، تسوية ضريبة القيمة المضافة - Q1، تصدير كشوف البنك.',
      pl: 'Używaj jasnych nazw: Eksport wydatków - Luty 2026, Uzgodnienie VAT - Q1, Eksport wyciągów bankowych.',
      it: 'Usa nomi chiari: Esportazione spese - Feb 2026, Riconciliazione IVA - Q1, Esportazione estratti conto.',
    }),
    columns: {
      name: t({ ru: 'Название', en: 'Name', kk: 'Атауы', de: 'Name', fr: 'Nom', es: 'Nombre', pt: 'Nome', tr: 'Ad', uk: 'Назва', zh: '名称', ar: 'الاسم', pl: 'Nazwa', it: 'Nome' }),
      purpose: t({ ru: 'Назначение / тип', en: 'Purpose / Type', kk: 'Мақсаты / түрі', de: 'Zweck / Typ', fr: 'Objectif / Type', es: 'Propósito / Tipo', pt: 'Finalidade / Tipo', tr: 'Amaç / Tür', uk: 'Призначення / тип', zh: '用途 / 类型', ar: 'الغرض / النوع', pl: 'Przeznaczenie / Typ', it: 'Scopo / Tipo' }),
      source: t({ ru: 'Источник', en: 'Source', kk: 'Дереккөз', de: 'Quelle', fr: 'Source', es: 'Fuente', pt: 'Fonte', tr: 'Kaynak', uk: 'Джерело', zh: '来源', ar: 'المصدر', pl: 'Źródło', it: 'Fonte' }),
      rows: t({ ru: 'Строки', en: 'Rows', kk: 'Жолдар', de: 'Zeilen', fr: 'Lignes', es: 'Filas', pt: 'Linhas', tr: 'Satırlar', uk: 'Рядки', zh: '行', ar: 'الصفوف', pl: 'Wiersze', it: 'Righe' }),
      updatedAt: t({ ru: 'Обновлено', en: 'Last updated', kk: 'Соңғы жаңарту', de: 'Zuletzt aktualisiert', fr: 'Dernière mise à jour', es: 'Última actualización', pt: 'Última atualização', tr: 'Son güncelleme', uk: 'Останнє оновлення', zh: '最后更新', ar: 'آخر تحديث', pl: 'Ostatnia aktualizacja', it: 'Ultimo aggiornamento' }),
      actions: t({ ru: 'Действия', en: 'Actions', kk: 'Әрекеттер', de: 'Aktionen', fr: 'Actions', es: 'Acciones', pt: 'Ações', tr: 'Eylemler', uk: 'Дії', zh: '操作', ar: 'الإجراءات', pl: 'Akcje', it: 'Azioni' }),
    },
    ctaDescription: t({
      ru: 'Создайте таблицу, сопоставив поля из выписок или чеков для экспорта в Excel или бухгалтерские системы.',
      en: 'Create a table by mapping fields from statements or receipts for export to Excel or accounting systems.',
      kk: 'Excel немесе бухгалтерлік жүйелерге экспорттау үшін үзінділер мен чектер өрістерін сәйкестендіріп кесте құрыңыз.',
      de: 'Erstellen Sie eine Tabelle, indem Sie Felder aus Kontoauszügen oder Belegen für den Export nach Excel oder Buchhaltungssystemen zuordnen.',
      fr: 'Créez un tableau en mappant les champs des relevés ou des reçus pour l\'export vers Excel ou les systèmes comptables.',
      es: 'Cree una tabla mapeando campos de estados de cuenta o recibos para exportar a Excel o sistemas contables.',
      pt: 'Crie uma tabela mapeando campos de extratos ou recibos para exportação ao Excel ou sistemas contábeis.',
      tr: 'Excel\'e veya muhasebe sistemlerine aktarmak için ekstre veya makbuzlardaki alanları eşleyerek bir tablo oluşturun.',
      uk: 'Створіть таблицю, зіставивши поля з виписок або чеків для експорту до Excel або бухгалтерських систем.',
      zh: '通过映射对账单或收据中的字段创建表格，以导出到 Excel 或会计系统。',
      ar: 'أنشئ جدولاً عن طريق ربط حقول من كشوف الحسابات أو الإيصالات للتصدير إلى Excel أو أنظمة المحاسبة.',
      pl: 'Utwórz tabelę mapując pola z wyciągów lub paragonów do eksportu do Excela lub systemów księgowych.',
      it: 'Crea una tabella mappando i campi da estratti conto o ricevute per l\'esportazione in Excel o sistemi contabili.',
    }),
    pagination: {
      shown: t({
        ru: 'Показано {from}–{to} из {count}',
        en: 'Showing {from}–{to} of {count}',
        kk: '{from}–{to} / {count} көрсетілді',
        de: 'Zeige {from}–{to} von {count}',
        fr: 'Affichage {from}–{to} sur {count}',
        es: 'Mostrando {from}–{to} de {count}',
        pt: 'Exibindo {from}–{to} de {count}',
        tr: '{count} içinden {from}–{to} gösteriliyor',
        uk: 'Показано {from}–{to} з {count}',
        zh: '显示 {from}–{to}，共 {count}',
        ar: 'عرض {from}–{to} من {count}',
        pl: 'Wyświetlanie {from}–{to} z {count}',
        it: 'Visualizzazione {from}–{to} di {count}',
      }),
      previous: t({ ru: 'Предыдущая', en: 'Previous', kk: 'Алдыңғы', de: 'Zurück', fr: 'Précédent', es: 'Anterior', pt: 'Anterior', tr: 'Önceki', uk: 'Попередня', zh: '上一页', ar: 'السابق', pl: 'Poprzednia', it: 'Precedente' }),
      next: t({ ru: 'Следующая', en: 'Next', kk: 'Келесі', de: 'Weiter', fr: 'Suivant', es: 'Siguiente', pt: 'Próxima', tr: 'Sonraki', uk: 'Наступна', zh: '下一页', ar: 'التالي', pl: 'Następna', it: 'Successivo' }),
      pageOf: t({
        ru: 'Страница {page} из {count}',
        en: 'Page {page} of {count}',
        kk: '{page} / {count} бет',
        de: 'Seite {page} von {count}',
        fr: 'Page {page} sur {count}',
        es: 'Página {page} de {count}',
        pt: 'Página {page} de {count}',
        tr: '{count} sayfadan {page}. sayfa',
        uk: 'Сторінка {page} з {count}',
        zh: '第 {page} 页，共 {count} 页',
        ar: 'الصفحة {page} من {count}',
        pl: 'Strona {page} z {count}',
        it: 'Pagina {page} di {count}',
      }),
    },
    empty: {
      title: t({
        ru: 'Пока нет экспортных таблиц',
        en: 'No export tables yet',
        kk: 'Экспорт кестелері әлі жоқ',
        de: 'Noch keine Exporttabellen',
        fr: 'Pas encore de tableaux d\'export',
        es: 'Aún no hay tablas de exportación',
        pt: 'Ainda não há tabelas de exportação',
        tr: 'Henüz dışa aktarma tablosu yok',
        uk: 'Ще немає таблиць експорту',
        zh: '暂无导出表格',
        ar: 'لا توجد جداول تصدير بعد',
        pl: 'Brak tabel eksportu',
        it: 'Nessuna tabella di esportazione ancora',
      }),
      description: t({
        ru: 'Создайте таблицу для бухгалтерского экспорта из выписок и чеков.',
        en: 'Create a table for accounting exports from statements and receipts.',
        kk: 'Үзінділер мен чектерден бухгалтерлік экспортқа арналған кесте жасаңыз.',
        de: 'Erstellen Sie eine Tabelle für Buchhaltungsexporte aus Kontoauszügen und Belegen.',
        fr: 'Créez un tableau pour les exports comptables depuis les relevés et les reçus.',
        es: 'Cree una tabla para exportaciones contables desde estados de cuenta y recibos.',
        pt: 'Crie uma tabela para exportações contábeis de extratos e recibos.',
        tr: 'Ekstre ve makbuzlardan muhasebe dışa aktarmaları için bir tablo oluşturun.',
        uk: 'Створіть таблицю для бухгалтерського експорту з виписок і чеків.',
        zh: '创建一个表格，用于从对账单和收据进行会计导出。',
        ar: 'أنشئ جدولاً لتصدير المحاسبة من كشوف الحسابات والإيصالات.',
        pl: 'Utwórz tabelę do eksportów księgowych z wyciągów i paragonów.',
        it: 'Crea una tabella per le esportazioni contabili da estratti conto e ricevute.',
      }),
      step1: t({
        ru: '1. Выберите выписки или чеки для включения',
        en: '1. Select statements or receipts to include',
        kk: '1. Қосу үшін үзінділерді немесе чектерді таңдаңыз',
        de: '1. Kontoauszüge oder Belege auswählen',
        fr: '1. Sélectionnez les relevés ou les reçus à inclure',
        es: '1. Seleccione estados de cuenta o recibos para incluir',
        pt: '1. Selecione extratos ou recibos para incluir',
        tr: '1. Dahil edilecek ekstreleri veya makbuzları seçin',
        uk: '1. Виберіть виписки або чеки для включення',
        zh: '1. 选择要包含的对账单或收据',
        ar: '1. حدد كشوف الحسابات أو الإيصالات للتضمين',
        pl: '1. Wybierz wyciągi lub paragony do uwzględnienia',
        it: '1. Seleziona estratti conto o ricevute da includere',
      }),
      step2: t({
        ru: '2. Выберите поля: дата, сумма, контрагент, категория, НДС',
        en: '2. Pick fields: date, amount, merchant, category, VAT',
        kk: '2. Өрістерді таңдаңыз: күні, сома, мерчант, санат, ҚҚС',
        de: '2. Felder auswählen: Datum, Betrag, Händler, Kategorie, MwSt.',
        fr: '2. Choisissez les champs : date, montant, marchand, catégorie, TVA',
        es: '2. Elija campos: fecha, importe, comerciante, categoría, IVA',
        pt: '2. Escolha campos: data, valor, comerciante, categoria, IVA',
        tr: '2. Alanları seçin: tarih, tutar, satıcı, kategori, KDV',
        uk: '2. Виберіть поля: дата, сума, контрагент, категорія, ПДВ',
        zh: '2. 选择字段：日期、金额、商家、类别、增值税',
        ar: '2. اختر الحقول: التاريخ، المبلغ، التاجر، الفئة، ضريبة القيمة المضافة',
        pl: '2. Wybierz pola: data, kwota, sprzedawca, kategoria, VAT',
        it: '2. Scegli i campi: data, importo, commerciante, categoria, IVA',
      }),
      step3: t({
        ru: '3. Сформируйте структуру таблицы',
        en: '3. Create the table structure',
        kk: '3. Кесте құрылымын жасаңыз',
        de: '3. Tabellenstruktur erstellen',
        fr: '3. Créez la structure du tableau',
        es: '3. Cree la estructura de la tabla',
        pt: '3. Crie a estrutura da tabela',
        tr: '3. Tablo yapısını oluşturun',
        uk: '3. Сформуйте структуру таблиці',
        zh: '3. 创建表格结构',
        ar: '3. أنشئ هيكل الجدول',
        pl: '3. Utwórz strukturę tabeli',
        it: '3. Crea la struttura della tabella',
      }),
      step4: t({
        ru: '4. Экспортируйте в Excel и обновляйте данные в любой момент',
        en: '4. Export to Excel or refresh anytime',
        kk: '4. Excel-ге экспорттаңыз немесе кез келген уақытта жаңартыңыз',
        de: '4. Nach Excel exportieren oder jederzeit aktualisieren',
        fr: '4. Exportez vers Excel ou actualisez à tout moment',
        es: '4. Exporte a Excel o actualice en cualquier momento',
        pt: '4. Exporte para Excel ou atualize a qualquer momento',
        tr: '4. Excel\'e aktarın veya istediğiniz zaman yenileyin',
        uk: '4. Експортуйте до Excel або оновлюйте дані в будь-який момент',
        zh: '4. 导出到 Excel 或随时刷新数据',
        ar: '4. قم بالتصدير إلى Excel أو تحديث البيانات في أي وقت',
        pl: '4. Eksportuj do Excela lub odświeżaj dane w dowolnym momencie',
        it: '4. Esporta in Excel o aggiorna i dati in qualsiasi momento',
      }),
    },
    loading: t({ ru: 'Загрузка...', en: 'Loading...', kk: 'Жүктелуде...', de: 'Laden...', fr: 'Chargement...', es: 'Cargando...', pt: 'Carregando...', tr: 'Yükleniyor...', uk: 'Завантаження...', zh: '加载中...', ar: 'جارٍ التحميل...', pl: 'Ładowanie...', it: 'Caricamento...' }),
    toasts: {
      loadTablesFailed: t({
        ru: 'Не удалось загрузить таблицы',
        en: 'Failed to load tables',
        kk: 'Кестелерді жүктеу мүмкін болмады',
        de: 'Tabellen konnten nicht geladen werden',
        fr: 'Impossible de charger les tableaux',
        es: 'No se pudieron cargar las tablas',
        pt: 'Falha ao carregar tabelas',
        tr: 'Tablolar yüklenemedi',
        uk: 'Не вдалося завантажити таблиці',
        zh: '加载表格失败',
        ar: 'فشل تحميل الجداول',
        pl: 'Nie udało się załadować tabel',
        it: 'Impossibile caricare le tabelle',
      }),
      loadStatementsFailed: t({
        ru: 'Не удалось загрузить выписки',
        en: 'Failed to load statements',
        kk: 'Үзінділерді жүктеу мүмкін болмады',
        de: 'Kontoauszüge konnten nicht geladen werden',
        fr: 'Impossible de charger les relevés',
        es: 'No se pudieron cargar los estados de cuenta',
        pt: 'Falha ao carregar extratos',
        tr: 'Ekstreler yüklenemedi',
        uk: 'Не вдалося завантажити виписки',
        zh: '加载对账单失败',
        ar: 'فشل تحميل كشوف الحسابات',
        pl: 'Nie udało się załadować wyciągów',
        it: 'Impossibile caricare gli estratti conto',
      }),
      created: t({
        ru: 'Таблица создана',
        en: 'Table created',
        kk: 'Кесте құрылды',
        de: 'Tabelle erstellt',
        fr: 'Tableau créé',
        es: 'Tabla creada',
        pt: 'Tabela criada',
        tr: 'Tablo oluşturuldu',
        uk: 'Таблицю створено',
        zh: '表格已创建',
        ar: 'تم إنشاء الجدول',
        pl: 'Tabela została utworzona',
        it: 'Tabella creata',
      }),
      createFailed: t({
        ru: 'Не удалось создать таблицу',
        en: 'Failed to create table',
        kk: 'Кесте құру мүмкін болмады',
        de: 'Tabelle konnte nicht erstellt werden',
        fr: 'Impossible de créer le tableau',
        es: 'No se pudo crear la tabla',
        pt: 'Falha ao criar tabela',
        tr: 'Tablo oluşturulamadı',
        uk: 'Не вдалося створити таблицю',
        zh: '创建表格失败',
        ar: 'فشل إنشاء الجدول',
        pl: 'Nie udało się utworzyć tabeli',
        it: 'Impossibile creare la tabella',
      }),
      selectAtLeastOneStatement: t({
        ru: 'Выберите хотя бы одну выписку',
        en: 'Select at least one statement',
        kk: 'Кемінде бір үзіндіні таңдаңыз',
        de: 'Mindestens einen Kontoauszug auswählen',
        fr: 'Sélectionnez au moins un relevé',
        es: 'Seleccione al menos un estado de cuenta',
        pt: 'Selecione pelo menos um extrato',
        tr: 'En az bir ekstre seçin',
        uk: 'Виберіть принаймні одну виписку',
        zh: '请至少选择一份对账单',
        ar: 'حدد كشف حساب واحداً على الأقل',
        pl: 'Wybierz co najmniej jeden wyciąg',
        it: 'Seleziona almeno un estratto conto',
      }),
      createdFromStatement: t({
        ru: 'Таблица создана из выписки',
        en: 'Table created from statements',
        kk: 'Кесте үзіндіден құрылды',
        de: 'Tabelle aus Kontoauszug erstellt',
        fr: 'Tableau créé à partir des relevés',
        es: 'Tabla creada desde estados de cuenta',
        pt: 'Tabela criada a partir de extratos',
        tr: 'Tablo ekstrelerden oluşturuldu',
        uk: 'Таблицю створено з виписки',
        zh: '已从对账单创建表格',
        ar: 'تم إنشاء الجدول من كشوف الحسابات',
        pl: 'Tabela utworzona z wyciągów',
        it: 'Tabella creata dagli estratti conto',
      }),
      createFromStatementFailed: t({
        ru: 'Не удалось создать таблицу из выписки',
        en: 'Failed to create table from statements',
        kk: 'Үзіндіден кесте құру мүмкін болмады',
        de: 'Tabelle konnte nicht aus Kontoauszug erstellt werden',
        fr: 'Impossible de créer le tableau à partir des relevés',
        es: 'No se pudo crear la tabla desde estados de cuenta',
        pt: 'Falha ao criar tabela a partir de extratos',
        tr: 'Ekstrelerden tablo oluşturulamadı',
        uk: 'Не вдалося створити таблицю з виписки',
        zh: '从对账单创建表格失败',
        ar: 'فشل إنشاء الجدول من كشوف الحسابات',
        pl: 'Nie udało się utworzyć tabeli z wyciągów',
        it: 'Impossibile creare la tabella dagli estratti conto',
      }),
      deleting: t({ ru: 'Удаление...', en: 'Deleting...', kk: 'Жойылуда...', de: 'Löschen...', fr: 'Suppression...', es: 'Eliminando...', pt: 'Excluindo...', tr: 'Siliniyor...', uk: 'Видалення...', zh: '删除中...', ar: 'جارٍ الحذف...', pl: 'Usuwanie...', it: 'Eliminazione...' }),
      deleted: t({
        ru: 'Таблица удалена',
        en: 'Table deleted',
        kk: 'Кесте жойылды',
        de: 'Tabelle gelöscht',
        fr: 'Tableau supprimé',
        es: 'Tabla eliminada',
        pt: 'Tabela excluída',
        tr: 'Tablo silindi',
        uk: 'Таблицю видалено',
        zh: '表格已删除',
        ar: 'تم حذف الجدول',
        pl: 'Tabela została usunięta',
        it: 'Tabella eliminata',
      }),
      deleteFailed: t({
        ru: 'Не удалось удалить таблицу',
        en: 'Failed to delete table',
        kk: 'Кестені жою мүмкін болмады',
        de: 'Tabelle konnte nicht gelöscht werden',
        fr: 'Impossible de supprimer le tableau',
        es: 'No se pudo eliminar la tabla',
        pt: 'Falha ao excluir tabela',
        tr: 'Tablo silinemedi',
        uk: 'Не вдалося видалити таблицю',
        zh: '删除表格失败',
        ar: 'فشل حذف الجدول',
        pl: 'Nie udało się usunąć tabeli',
        it: 'Impossibile eliminare la tabella',
      }),
    },
    create: {
      title: t({ ru: 'Новая таблица', en: 'New table', kk: 'Жаңа кесте', de: 'Neue Tabelle', fr: 'Nouveau tableau', es: 'Nueva tabla', pt: 'Nova tabela', tr: 'Yeni tablo', uk: 'Нова таблиця', zh: '新建表格', ar: 'جدول جديد', pl: 'Nowa tabela', it: 'Nuova tabella' }),
      name: t({ ru: 'Название', en: 'Name', kk: 'Атауы', de: 'Name', fr: 'Nom', es: 'Nombre', pt: 'Nome', tr: 'Ad', uk: 'Назва', zh: '名称', ar: 'الاسم', pl: 'Nazwa', it: 'Nome' }),
      namePlaceholder: t({
        ru: 'Например: Реестр платежей',
        en: 'e.g. Payments registry',
        kk: 'Мысалы: Төлемдер тізілімі',
        de: 'z.B. Zahlungsregister',
        fr: 'ex. Registre des paiements',
        es: 'ej. Registro de pagos',
        pt: 'ex. Registro de pagamentos',
        tr: 'örn. Ödeme kaydı',
        uk: 'Наприклад: Реєстр платежів',
        zh: '例如：付款记录',
        ar: 'مثال: سجل المدفوعات',
        pl: 'np. Rejestr płatności',
        it: 'es. Registro dei pagamenti',
      }),
      description: t({ ru: 'Описание', en: 'Description', kk: 'Сипаттама', de: 'Beschreibung', fr: 'Description', es: 'Descripción', pt: 'Descrição', tr: 'Açıklama', uk: 'Опис', zh: '描述', ar: 'الوصف', pl: 'Opis', it: 'Descrizione' }),
      descriptionPlaceholder: t({
        ru: 'Опционально',
        en: 'Optional',
        kk: 'Міндетті емес',
        de: 'Optional',
        fr: 'Facultatif',
        es: 'Opcional',
        pt: 'Opcional',
        tr: 'İsteğe bağlı',
        uk: 'Необов\'язково',
        zh: '可选',
        ar: 'اختياري',
        pl: 'Opcjonalnie',
        it: 'Facoltativo',
      }),
      category: t({
        ru: 'Категория (иконка/цвет)',
        en: 'Category (icon/color)',
        kk: 'Санат (иконка/түс)',
        de: 'Kategorie (Symbol/Farbe)',
        fr: 'Catégorie (icône/couleur)',
        es: 'Categoría (icono/color)',
        pt: 'Categoria (ícone/cor)',
        tr: 'Kategori (ikon/renk)',
        uk: 'Категорія (іконка/колір)',
        zh: '类别（图标/颜色）',
        ar: 'الفئة (أيقونة/لون)',
        pl: 'Kategoria (ikona/kolor)',
        it: 'Categoria (icona/colore)',
      }),
      noCategory: t({ ru: 'Без категории', en: 'No category', kk: 'Санатсыз', de: 'Keine Kategorie', fr: 'Sans catégorie', es: 'Sin categoría', pt: 'Sem categoria', tr: 'Kategori yok', uk: 'Без категорії', zh: '无类别', ar: 'بدون فئة', pl: 'Bez kategorii', it: 'Nessuna categoria' }),
      categoryHint: t({
        ru: 'Иконка/цвет будут взяты из категории',
        en: 'Icon/color will be taken from category',
        kk: 'Иконка/түс санаттан алынады',
        de: 'Symbol/Farbe wird aus der Kategorie übernommen',
        fr: 'L\'icône/couleur sera prise depuis la catégorie',
        es: 'El icono/color se tomará de la categoría',
        pt: 'O ícone/cor será retirado da categoria',
        tr: 'İkon/renk kategoriden alınacak',
        uk: 'Іконка/колір буде взята з категорії',
        zh: '图标/颜色将从类别中获取',
        ar: 'سيتم أخذ الأيقونة/اللون من الفئة',
        pl: 'Ikona/kolor zostanie pobrana z kategorii',
        it: 'L\'icona/colore verrà presa dalla categoria',
      }),
      creating: t({ ru: 'Создание...', en: 'Creating...', kk: 'Құрылуда...', de: 'Erstellen...', fr: 'Création...', es: 'Creando...', pt: 'Criando...', tr: 'Oluşturuluyor...', uk: 'Створення...', zh: '创建中...', ar: 'جارٍ الإنشاء...', pl: 'Tworzenie...', it: 'Creazione...' }),
    },
    createFromStatements: {
      title: t({
        ru: 'Создать таблицу из выписки',
        en: 'Create table from statements',
        kk: 'Үзіндіден кесте құру',
        de: 'Tabelle aus Kontoauszug erstellen',
        fr: 'Créer un tableau depuis les relevés',
        es: 'Crear tabla desde estados de cuenta',
        pt: 'Criar tabela a partir de extratos',
        tr: 'Ekstrelerden tablo oluştur',
        uk: 'Створити таблицю з виписки',
        zh: '从对账单创建表格',
        ar: 'إنشاء جدول من كشوف الحسابات',
        pl: 'Utwórz tabelę z wyciągów',
        it: 'Crea tabella dagli estratti conto',
      }),
      step1: t({
        ru: 'Шаг 1 - Выбор выписок',
        en: 'Step 1 - Select statements',
        kk: '1-қадам - Үзінділерді таңдау',
        de: 'Schritt 1 - Kontoauszüge auswählen',
        fr: 'Étape 1 - Sélectionner les relevés',
        es: 'Paso 1 - Seleccionar estados de cuenta',
        pt: 'Passo 1 - Selecionar extratos',
        tr: 'Adım 1 - Ekstreleri seçin',
        uk: 'Крок 1 - Вибір виписок',
        zh: '第 1 步 - 选择对账单',
        ar: 'الخطوة 1 - اختيار كشوف الحسابات',
        pl: 'Krok 1 - Wybierz wyciągi',
        it: 'Passo 1 - Seleziona estratti conto',
      }),
      step2: t({
        ru: 'Шаг 2 - Параметры таблицы',
        en: 'Step 2 - Table details',
        kk: '2-қадам - Кесте параметрлері',
        de: 'Schritt 2 - Tabellendetails',
        fr: 'Étape 2 - Détails du tableau',
        es: 'Paso 2 - Detalles de la tabla',
        pt: 'Passo 2 - Detalhes da tabela',
        tr: 'Adım 2 - Tablo ayrıntıları',
        uk: 'Крок 2 - Параметри таблиці',
        zh: '第 2 步 - 表格详情',
        ar: 'الخطوة 2 - تفاصيل الجدول',
        pl: 'Krok 2 - Szczegóły tabeli',
        it: 'Passo 2 - Dettagli tabella',
      }),
      stepCounter: t({
        ru: 'Шаг {current} из {total}',
        en: 'Step {current} of {total}',
        kk: '{total} қадамның {current}-қадамы',
        de: 'Schritt {current} von {total}',
        fr: 'Étape {current} sur {total}',
        es: 'Paso {current} de {total}',
        pt: 'Passo {current} de {total}',
        tr: '{total} adımdan {current}. adım',
        uk: 'Крок {current} з {total}',
        zh: '第 {current} 步，共 {total} 步',
        ar: 'الخطوة {current} من {total}',
        pl: 'Krok {current} z {total}',
        it: 'Passo {current} di {total}',
      }),
      step1Description: t({
        ru: 'Выберите выписки для таблицы: используйте поиск, фильтр и группировку.',
        en: 'Choose statements for the table using search, filters, and grouping.',
        kk: 'Кестеге үзінділерді таңдаңыз: іздеу, сүзгі және топтауды қолданыңыз.',
        de: 'Wählen Sie Kontoauszüge für die Tabelle aus: Verwenden Sie Suche, Filter und Gruppierung.',
        fr: 'Choisissez les relevés pour le tableau en utilisant la recherche, les filtres et le regroupement.',
        es: 'Elija estados de cuenta para la tabla usando búsqueda, filtros y agrupación.',
        pt: 'Escolha extratos para a tabela usando pesquisa, filtros e agrupamento.',
        tr: 'Arama, filtreler ve gruplama kullanarak tablo için ekstreleri seçin.',
        uk: 'Виберіть виписки для таблиці: використовуйте пошук, фільтр та групування.',
        zh: '使用搜索、筛选和分组为表格选择对账单。',
        ar: 'اختر كشوف الحسابات للجدول باستخدام البحث والفلاتر والتجميع.',
        pl: 'Wybierz wyciągi do tabeli korzystając z wyszukiwania, filtrów i grupowania.',
        it: 'Scegli gli estratti conto per la tabella usando ricerca, filtri e raggruppamento.',
      }),
      step2Description: t({
        ru: 'Укажите детали таблицы и проверьте предварительный результат перед созданием.',
        en: 'Set table details and review the result before creating the table.',
        kk: 'Кесте деректерін толтырып, құру алдында нәтижені тексеріңіз.',
        de: 'Geben Sie Tabellendetails an und überprüfen Sie das Ergebnis vor der Erstellung.',
        fr: 'Définissez les détails du tableau et vérifiez le résultat avant de créer le tableau.',
        es: 'Establezca los detalles de la tabla y revise el resultado antes de crear la tabla.',
        pt: 'Defina os detalhes da tabela e revise o resultado antes de criar a tabela.',
        tr: 'Tablo ayrıntılarını ayarlayın ve tabloyu oluşturmadan önce sonucu inceleyin.',
        uk: 'Вкажіть деталі таблиці та перевірте попередній результат перед створенням.',
        zh: '设置表格详情并在创建表格前审查结果。',
        ar: 'حدد تفاصيل الجدول وراجع النتيجة قبل الإنشاء.',
        pl: 'Ustaw szczegóły tabeli i sprawdź wynik przed jej utworzeniem.',
        it: 'Imposta i dettagli della tabella e rivedi il risultato prima di creare la tabella.',
      }),
      nameOptional: t({
        ru: 'Название (опционально)',
        en: 'Name (optional)',
        kk: 'Атауы (міндетті емес)',
        de: 'Name (optional)',
        fr: 'Nom (facultatif)',
        es: 'Nombre (opcional)',
        pt: 'Nome (opcional)',
        tr: 'Ad (isteğe bağlı)',
        uk: 'Назва (необов\'язково)',
        zh: '名称（可选）',
        ar: 'الاسم (اختياري)',
        pl: 'Nazwa (opcjonalnie)',
        it: 'Nome (facoltativo)',
      }),
      namePlaceholder: t({
        ru: 'Например: Платежи из выписки',
        en: 'e.g. Payments from statement',
        kk: 'Мысалы: Үзіндідегі төлемдер',
        de: 'z.B. Zahlungen aus Kontoauszug',
        fr: 'ex. Paiements depuis le relevé',
        es: 'ej. Pagos desde estado de cuenta',
        pt: 'ex. Pagamentos do extrato',
        tr: 'örn. Ekstreden ödemeler',
        uk: 'Наприклад: Платежі з виписки',
        zh: '例如：来自对账单的付款',
        ar: 'مثال: مدفوعات من كشف الحساب',
        pl: 'np. Płatności z wyciągu',
        it: 'es. Pagamenti dall\'estratto conto',
      }),
      descriptionOptional: t({
        ru: 'Описание (опционально)',
        en: 'Description (optional)',
        kk: 'Сипаттама (міндетті емес)',
        de: 'Beschreibung (optional)',
        fr: 'Description (facultatif)',
        es: 'Descripción (opcional)',
        pt: 'Descrição (opcional)',
        tr: 'Açıklama (isteğe bağlı)',
        uk: 'Опис (необов\'язково)',
        zh: '描述（可选）',
        ar: 'الوصف (اختياري)',
        pl: 'Opis (opcjonalnie)',
        it: 'Descrizione (facoltativo)',
      }),
      descriptionPlaceholder: t({
        ru: 'Опционально',
        en: 'Optional',
        kk: 'Міндетті емес',
        de: 'Optional',
        fr: 'Facultatif',
        es: 'Opcional',
        pt: 'Opcional',
        tr: 'İsteğe bağlı',
        uk: 'Необов\'язково',
        zh: '可选',
        ar: 'اختياري',
        pl: 'Opcjonalnie',
        it: 'Facoltativo',
      }),
      statements: t({ ru: 'Выписки', en: 'Statements', kk: 'Үзінділер', de: 'Kontoauszüge', fr: 'Relevés', es: 'Estados de cuenta', pt: 'Extratos', tr: 'Ekstreler', uk: 'Виписки', zh: '对账单', ar: 'كشوف الحسابات', pl: 'Wyciągi', it: 'Estratti conto' }),
      statementsLoading: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Laden...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
      }),
      statementsEmpty: t({
        ru: 'Нет выписок',
        en: 'No statements',
        kk: 'Үзінділер жоқ',
        de: 'Keine Kontoauszüge',
        fr: 'Aucun relevé',
        es: 'Sin estados de cuenta',
        pt: 'Sem extratos',
        tr: 'Ekstre yok',
        uk: 'Немає виписок',
        zh: '无对账单',
        ar: 'لا توجد كشوف حسابات',
        pl: 'Brak wyciągów',
        it: 'Nessun estratto conto',
      }),
      hint: t({
        ru: 'Доступны только обработанные выписки с транзакциями',
        en: 'Only processed statements with transactions are available',
        kk: 'Тек транзакциялары бар өңделген үзінділер қолжетімді',
        de: 'Nur verarbeitete Kontoauszüge mit Transaktionen sind verfügbar',
        fr: 'Seuls les relevés traités avec des transactions sont disponibles',
        es: 'Solo están disponibles los estados de cuenta procesados con transacciones',
        pt: 'Apenas extratos processados com transações estão disponíveis',
        tr: 'Yalnızca işlem içeren işlenmiş ekstreler mevcuttur',
        uk: 'Доступні лише оброблені виписки з транзакціями',
        zh: '仅显示已处理且包含交易的对账单',
        ar: 'تتوفر فقط كشوف الحسابات المعالجة التي تحتوي على معاملات',
        pl: 'Dostępne są tylko przetworzone wyciągi z transakcjami',
        it: 'Sono disponibili solo gli estratti conto elaborati con transazioni',
      }),
      searchPlaceholder: t({
        ru: 'Поиск по файлу, источнику или периоду',
        en: 'Search by file, source, or period',
        kk: 'Файл, дереккөз немесе кезең бойынша іздеу',
        de: 'Nach Datei, Quelle oder Zeitraum suchen',
        fr: 'Rechercher par fichier, source ou période',
        es: 'Buscar por archivo, fuente o período',
        pt: 'Pesquisar por arquivo, fonte ou período',
        tr: 'Dosya, kaynak veya döneme göre ara',
        uk: 'Пошук за файлом, джерелом або періодом',
        zh: '按文件、来源或期间搜索',
        ar: 'البحث بالملف أو المصدر أو الفترة',
        pl: 'Szukaj po pliku, źródle lub okresie',
        it: 'Cerca per file, fonte o periodo',
      }),
      sourceFilter: t({
        ru: 'Источник',
        en: 'Source',
        kk: 'Дереккөз',
        de: 'Quelle',
        fr: 'Source',
        es: 'Fuente',
        pt: 'Fonte',
        tr: 'Kaynak',
        uk: 'Джерело',
        zh: '来源',
        ar: 'المصدر',
        pl: 'Źródło',
        it: 'Fonte',
      }),
      sourceAll: t({
        ru: 'Все источники',
        en: 'All sources',
        kk: 'Барлық дереккөздер',
        de: 'Alle Quellen',
        fr: 'Toutes les sources',
        es: 'Todas las fuentes',
        pt: 'Todas as fontes',
        tr: 'Tüm kaynaklar',
        uk: 'Всі джерела',
        zh: '所有来源',
        ar: 'كل المصادر',
        pl: 'Wszystkie źródła',
        it: 'Tutte le fonti',
      }),
      groupBy: t({
        ru: 'Группировать по',
        en: 'Group by',
        kk: 'Топтау',
        de: 'Gruppieren nach',
        fr: 'Regrouper par',
        es: 'Agrupar por',
        pt: 'Agrupar por',
        tr: 'Grupla',
        uk: 'Групувати за',
        zh: '分组依据',
        ar: 'تجميع حسب',
        pl: 'Grupuj według',
        it: 'Raggruppa per',
      }),
      groupBySource: t({
        ru: 'Источнику',
        en: 'Source',
        kk: 'Дереккөз',
        de: 'Quelle',
        fr: 'Source',
        es: 'Fuente',
        pt: 'Fonte',
        tr: 'Kaynak',
        uk: 'Джерелом',
        zh: '来源',
        ar: 'المصدر',
        pl: 'Źródło',
        it: 'Fonte',
      }),
      groupByPeriod: t({
        ru: 'Периоду',
        en: 'Period',
        kk: 'Кезең',
        de: 'Zeitraum',
        fr: 'Période',
        es: 'Período',
        pt: 'Período',
        tr: 'Dönem',
        uk: 'Періодом',
        zh: '期间',
        ar: 'الفترة',
        pl: 'Okres',
        it: 'Periodo',
      }),
      sourceLabel: t({
        ru: 'Источник',
        en: 'Source',
        kk: 'Дереккөз',
        de: 'Quelle',
        fr: 'Source',
        es: 'Fuente',
        pt: 'Fonte',
        tr: 'Kaynak',
        uk: 'Джерело',
        zh: '来源',
        ar: 'المصدر',
        pl: 'Źródło',
        it: 'Fonte',
      }),
      periodLabel: t({
        ru: 'Период',
        en: 'Period',
        kk: 'Кезең',
        de: 'Zeitraum',
        fr: 'Période',
        es: 'Período',
        pt: 'Período',
        tr: 'Dönem',
        uk: 'Період',
        zh: '期间',
        ar: 'الفترة',
        pl: 'Okres',
        it: 'Periodo',
      }),
      fileLabel: t({
        ru: 'Файл',
        en: 'File',
        kk: 'Файл',
        de: 'Datei',
        fr: 'Fichier',
        es: 'Archivo',
        pt: 'Arquivo',
        tr: 'Dosya',
        uk: 'Файл',
        zh: '文件',
        ar: 'ملف',
        pl: 'Plik',
        it: 'File',
      }),
      rowsLabel: t({
        ru: 'Строки',
        en: 'Rows',
        kk: 'Жолдар',
        de: 'Zeilen',
        fr: 'Lignes',
        es: 'Filas',
        pt: 'Linhas',
        tr: 'Satırlar',
        uk: 'Рядки',
        zh: '行',
        ar: 'الصفوف',
        pl: 'Wiersze',
        it: 'Righe',
      }),
      selectedLabel: t({
        ru: 'Выбрано: {count}',
        en: 'Selected: {count}',
        kk: 'Таңдалды: {count}',
        de: 'Ausgewählt: {count}',
        fr: 'Sélectionné : {count}',
        es: 'Seleccionado: {count}',
        pt: 'Selecionado: {count}',
        tr: 'Seçildi: {count}',
        uk: 'Вибрано: {count}',
        zh: '已选择：{count}',
        ar: 'المحدد: {count}',
        pl: 'Wybrano: {count}',
        it: 'Selezionato: {count}',
      }),
      duplicateUploads: t({
        ru: 'Дубли загрузок: {count} (используется последняя)',
        en: 'Duplicate uploads: {count} (latest is used)',
        kk: 'Қайталанған жүктеулер: {count} (соңғысы қолданылады)',
        de: 'Doppelte Uploads: {count} (neueste wird verwendet)',
        fr: 'Téléchargements en double : {count} (le plus récent est utilisé)',
        es: 'Cargas duplicadas: {count} (se usa la más reciente)',
        pt: 'Uploads duplicados: {count} (o mais recente é usado)',
        tr: 'Yinelenen yüklemeler: {count} (en son kullanılır)',
        uk: 'Дублі завантажень: {count} (використовується останнє)',
        zh: '重复上传：{count}（使用最新版本）',
        ar: 'الرفعات المكررة: {count} (يُستخدم الأحدث)',
        pl: 'Zduplikowane przesyłki: {count} (używana jest ostatnia)',
        it: 'Upload duplicati: {count} (viene usato il più recente)',
      }),
      noSearchResults: t({
        ru: 'По текущему фильтру выписки не найдены',
        en: 'No statements match the current filters',
        kk: 'Ағымдағы сүзгі бойынша үзінділер табылмады',
        de: 'Keine Kontoauszüge entsprechen den aktuellen Filtern',
        fr: 'Aucun relevé ne correspond aux filtres actuels',
        es: 'Ningún estado de cuenta coincide con los filtros actuales',
        pt: 'Nenhum extrato corresponde aos filtros atuais',
        tr: 'Mevcut filtrelere uyan ekstre bulunamadı',
        uk: 'За поточним фільтром виписки не знайдено',
        zh: '没有与当前筛选条件匹配的对账单',
        ar: 'لا توجد كشوف حسابات تطابق الفلاتر الحالية',
        pl: 'Brak wyciągów pasujących do bieżących filtrów',
        it: 'Nessun estratto conto corrisponde ai filtri attuali',
      }),
      previewTitle: t({
        ru: 'Предпросмотр',
        en: 'Preview',
        kk: 'Алдын ала қарау',
        de: 'Vorschau',
        fr: 'Aperçu',
        es: 'Vista previa',
        pt: 'Pré-visualização',
        tr: 'Önizleme',
        uk: 'Попередній перегляд',
        zh: '预览',
        ar: 'معاينة',
        pl: 'Podgląd',
        it: 'Anteprima',
      }),
      previewSummary: t({
        ru: 'Вы создаете таблицу из {statements} выписок',
        en: 'You are creating a table from {statements} statements',
        kk: '{statements} үзіндіден кесте құрып жатырсыз',
        de: 'Sie erstellen eine Tabelle aus {statements} Kontoauszügen',
        fr: 'Vous créez un tableau à partir de {statements} relevés',
        es: 'Está creando una tabla a partir de {statements} estados de cuenta',
        pt: 'Você está criando uma tabela a partir de {statements} extratos',
        tr: '{statements} ekstreden bir tablo oluşturuyorsunuz',
        uk: 'Ви створюєте таблицю з {statements} виписок',
        zh: '您正在从 {statements} 份对账单创建表格',
        ar: 'أنت تنشئ جدولاً من {statements} كشف حساب',
        pl: 'Tworzysz tabelę z {statements} wyciągów',
        it: 'Stai creando una tabella da {statements} estratti conto',
      }),
      previewRows: t({
        ru: 'Итого строк: {rows}',
        en: 'Total rows: {rows}',
        kk: 'Жалпы жол саны: {rows}',
        de: 'Gesamtzeilen: {rows}',
        fr: 'Total des lignes : {rows}',
        es: 'Total de filas: {rows}',
        pt: 'Total de linhas: {rows}',
        tr: 'Toplam satır: {rows}',
        uk: 'Всього рядків: {rows}',
        zh: '总行数：{rows}',
        ar: 'إجمالي الصفوف: {rows}',
        pl: 'Łącznie wierszy: {rows}',
        it: 'Totale righe: {rows}',
      }),
      previewEditable: t({
        ru: 'Вы можете изменить выбор выписок на шаге 1.',
        en: 'You can still change statement selection on Step 1.',
        kk: 'Үзінді таңдауын 1-қадамда өзгерте аласыз.',
        de: 'Sie können die Auswahl der Kontoauszüge in Schritt 1 noch ändern.',
        fr: 'Vous pouvez encore modifier la sélection des relevés à l\'étape 1.',
        es: 'Aún puede cambiar la selección de estados de cuenta en el Paso 1.',
        pt: 'Você ainda pode alterar a seleção de extratos no Passo 1.',
        tr: 'Ekstre seçimini Adım 1\'de hâlâ değiştirebilirsiniz.',
        uk: 'Ви можете змінити вибір виписок на кроці 1.',
        zh: '您仍然可以在第 1 步更改对账单选择。',
        ar: 'لا يزال بإمكانك تغيير اختيار كشوف الحسابات في الخطوة 1.',
        pl: 'Nadal możesz zmienić wybór wyciągów w kroku 1.',
        it: 'Puoi ancora modificare la selezione degli estratti conto al Passo 1.',
      }),
      next: t({
        ru: 'Далее',
        en: 'Next',
        kk: 'Келесі',
        de: 'Weiter',
        fr: 'Suivant',
        es: 'Siguiente',
        pt: 'Próximo',
        tr: 'İleri',
        uk: 'Далі',
        zh: '下一步',
        ar: 'التالي',
        pl: 'Dalej',
        it: 'Avanti',
      }),
      back: t({
        ru: 'Назад',
        en: 'Back',
        kk: 'Артқа',
        de: 'Zurück',
        fr: 'Retour',
        es: 'Atrás',
        pt: 'Voltar',
        tr: 'Geri',
        uk: 'Назад',
        zh: '返回',
        ar: 'رجوع',
        pl: 'Wstecz',
        it: 'Indietro',
      }),
      createWithRows: t({
        ru: 'Создать ({rows} строк)',
        en: 'Create ({rows} rows)',
        kk: 'Құру ({rows} жол)',
        de: 'Erstellen ({rows} Zeilen)',
        fr: 'Créer ({rows} lignes)',
        es: 'Crear ({rows} filas)',
        pt: 'Criar ({rows} linhas)',
        tr: 'Oluştur ({rows} satır)',
        uk: 'Створити ({rows} рядків)',
        zh: '创建（{rows} 行）',
        ar: 'إنشاء ({rows} صف)',
        pl: 'Utwórz ({rows} wierszy)',
        it: 'Crea ({rows} righe)',
      }),
      creating: t({ ru: 'Создание...', en: 'Creating...', kk: 'Құрылуда...', de: 'Erstellen...', fr: 'Création...', es: 'Creando...', pt: 'Criando...', tr: 'Oluşturuluyor...', uk: 'Створення...', zh: '创建中...', ar: 'جارٍ الإنشاء...', pl: 'Tworzenie...', it: 'Creazione...' }),
    },
    confirmDelete: {
      title: t({
        ru: 'Удалить таблицу?',
        en: 'Delete table?',
        kk: 'Кестені жою керек пе?',
        de: 'Tabelle löschen?',
        fr: 'Supprimer le tableau ?',
        es: '¿Eliminar tabla?',
        pt: 'Excluir tabela?',
        tr: 'Tablo silinsin mi?',
        uk: 'Видалити таблицю?',
        zh: '删除表格？',
        ar: 'حذف الجدول؟',
        pl: 'Usunąć tabelę?',
        it: 'Eliminare la tabella?',
      }),
      messageWithNamePrefix: t({
        ru: 'Таблица "',
        en: 'Table "',
        kk: 'Кесте "',
        de: 'Tabelle "',
        fr: 'Le tableau "',
        es: 'La tabla "',
        pt: 'A tabela "',
        tr: '"',
        uk: 'Таблиця "',
        zh: '表格"',
        ar: 'الجدول "',
        pl: 'Tabela "',
        it: 'La tabella "',
      }),
      messageWithNameSuffix: t({
        ru: '" будет удалена вместе со всеми строками и колонками.',
        en: '" will be deleted along with all rows and columns.',
        kk: '" барлық жолдармен және бағандармен бірге жойылады.',
        de: '" wird zusammen mit allen Zeilen und Spalten gelöscht.',
        fr: '" sera supprimé avec toutes les lignes et colonnes.',
        es: '" será eliminada junto con todas las filas y columnas.',
        pt: '" será excluída junto com todas as linhas e colunas.',
        tr: '" tüm satırlar ve sütunlarla birlikte silinecek.',
        uk: '" буде видалена разом з усіма рядками та стовпцями.',
        zh: '"将连同所有行和列一起删除。',
        ar: '" سيُحذف مع كل الصفوف والأعمدة.',
        pl: '" zostanie usunięta wraz ze wszystkimi wierszami i kolumnami.',
        it: '" verrà eliminata insieme a tutte le righe e colonne.',
      }),
      messageNoName: t({
        ru: 'Таблица будет удалена вместе со всеми строками и колонками.',
        en: 'The table will be deleted along with all rows and columns.',
        kk: 'Кесте барлық жолдармен және бағандармен бірге жойылады.',
        de: 'Die Tabelle wird zusammen mit allen Zeilen und Spalten gelöscht.',
        fr: 'Le tableau sera supprimé avec toutes les lignes et colonnes.',
        es: 'La tabla será eliminada junto con todas las filas y columnas.',
        pt: 'A tabela será excluída junto com todas as linhas e colunas.',
        tr: 'Tablo tüm satırlar ve sütunlarla birlikte silinecek.',
        uk: 'Таблицю буде видалено разом з усіма рядками та стовпцями.',
        zh: '该表格将连同所有行和列一起删除。',
        ar: 'سيُحذف الجدول مع كل الصفوف والأعمدة.',
        pl: 'Tabela zostanie usunięta wraz ze wszystkimi wierszami i kolumnami.',
        it: 'La tabella verrà eliminata insieme a tutte le righe e colonne.',
      }),
      confirm: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina' }),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla' }),
    },
  },
} satisfies Dictionary;

export default content;
