import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'settingsProfilePage',
  content: {
    authRequired: t({
      ru: 'Войдите в систему, чтобы управлять профилем.',
      en: 'Log in to manage your profile.',
      kk: 'Профильді басқару үшін жүйеге кіріңіз.',
      de: 'Melden Sie sich an, um Ihr Profil zu verwalten.',
      fr: 'Connectez-vous pour gérer votre profil.',
      es: 'Inicia sesión para gestionar tu perfil.',
      pt: 'Faça login para gerenciar seu perfil.',
      tr: 'Profilinizi yönetmek için giriş yapın.',
      uk: 'Увійдіть у систему, щоб керувати профілем.',
      zh: '登录以管理您的个人资料。',
      ar: 'سجّل الدخول لإدارة ملفك الشخصي.',
      pl: 'Zaloguj się, aby zarządzać profilem.',
      it: 'Accedi per gestire il tuo profilo.',
      sk: 'Zaloguj się, aby zarządzać profilem.',
    }),
    title: t({
      ru: 'Настройки профиля',
      en: 'Profile settings',
      kk: 'Профиль баптаулары',
      de: 'Profileinstellungen',
      fr: 'Paramètres du profil',
      es: 'Configuración del perfil',
      pt: 'Configurações do perfil',
      tr: 'Profil ayarları',
      uk: 'Налаштування профілю',
      zh: '个人资料设置',
      ar: 'إعدادات الملف الشخصي',
      pl: 'Ustawienia profilu',
      it: 'Impostazioni profilo',
      sk: 'Ustawienia profilu',
    }),
    subtitle: t({
      ru: 'Обновите контактный email и пароль. Изменения вступают в силу сразу после сохранения.',
      en: 'Update your contact email and password. Changes take effect immediately after saving.',
      kk: 'Байланыс email-ін және құпиясөзді жаңартыңыз. Өзгерістер сақтағаннан кейін бірден күшіне енеді.',
      de: 'Aktualisieren Sie Ihre Kontakt-E-Mail und Ihr Passwort. Änderungen treten sofort nach dem Speichern in Kraft.',
      fr: 'Mettez à jour votre e-mail de contact et votre mot de passe. Les modifications prennent effet immédiatement après l\'enregistrement.',
      es: 'Actualiza tu correo de contacto y contraseña. Los cambios surten efecto inmediatamente al guardar.',
      pt: 'Atualize seu e-mail de contato e senha. As alterações entram em vigor imediatamente após salvar.',
      tr: 'İletişim e-postanızı ve şifrenizi güncelleyin. Değişiklikler kaydedildikten hemen sonra geçerli olur.',
      uk: 'Оновіть контактний email та пароль. Зміни набувають чинності одразу після збереження.',
      zh: '更新您的联系邮箱和密码。更改在保存后立即生效。',
      ar: 'حدّث بريدك الإلكتروني للتواصل وكلمة المرور. تسري التغييرات فور الحفظ.',
      pl: 'Zaktualizuj kontaktowy e-mail i hasło. Zmiany wchodzą w życie natychmiast po zapisaniu.',
      it: 'Aggiorna la tua email di contatto e la password. Le modifiche hanno effetto immediatamente dopo il salvataggio.',
      sk: 'Zaktualizuj kontaktowy e-mail i hasło. Zmiany wchodzą w życie natychmiast po zapisaniu.',
    }),
    navigation: {
      title: t({
        ru: 'Разделы',
        en: 'Sections',
        kk: 'Бөлімдер',
        de: 'Abschnitte',
        fr: 'Sections',
        es: 'Secciones',
        pt: 'Seções',
        tr: 'Bölümler',
        uk: 'Розділи',
        zh: '章节',
        ar: 'الأقسام',
        pl: 'Sekcje',
        it: 'Sezioni',
        sk: 'Sekcje',
      }),
      sectionLabel: t({
        ru: 'Раздел',
        en: 'Section',
        kk: 'Бөлім',
        de: 'Abschnitt',
        fr: 'Section',
        es: 'Sección',
        pt: 'Seção',
        tr: 'Bölüm',
        uk: 'Розділ',
        zh: '部分',
        ar: 'قسم',
        pl: 'Sekcja',
        it: 'Sezione',
        sk: 'Sekcja',
      }),
    },
    changelogCard: {
      title: t({ ru: 'Changelog', en: 'Changelog', kk: 'Changelog', de: 'Changelog', fr: 'Changelog', es: 'Changelog', pt: 'Changelog', tr: 'Changelog', uk: 'Changelog', zh: 'Changelog', ar: 'Changelog', pl: 'Changelog', it: 'Changelog', sk: 'Changelog'}),
      description: t({
        ru: 'Краткая лента обновлений продукта.',
        en: 'A compact stream of product updates.',
        kk: 'Өнім жаңартуларының қысқаша таспасы.',
        de: 'Ein kompakter Strom von Produktupdates.',
        fr: 'Un flux compact des mises à jour du produit.',
        es: 'Un flujo compacto de actualizaciones del producto.',
        pt: 'Um fluxo compacto de atualizações do produto.',
        tr: 'Ürün güncellemelerinin özlü bir akışı.',
        uk: 'Стислий потік оновлень продукту.',
        zh: '产品更新的简洁流。',
        ar: 'تدفق مدمج لتحديثات المنتج.',
        pl: 'Zwarty strumień aktualizacji produktu.',
        it: 'Un flusso compatto di aggiornamenti del prodotto.',
        sk: 'Zwarty strumień aktualizacji produktu.',
      }),
      loading: t({
        ru: 'Загружаем changelog...',
        en: 'Loading changelog...',
        kk: 'Changelog жүктелуде...',
        de: 'Changelog wird geladen...',
        fr: 'Chargement du changelog...',
        es: 'Cargando changelog...',
        pt: 'Carregando changelog...',
        tr: 'Changelog yükleniyor...',
        uk: 'Завантажуємо changelog...',
        zh: '加载 changelog 中...',
        ar: 'جارٍ تحميل changelog...',
        pl: 'Ładowanie changelog...',
        it: 'Caricamento changelog...',
        sk: 'Ładowanie changelog...',
      }),
      empty: t({
        ru: 'Пока нет опубликованных обновлений.',
        en: 'No published updates yet.',
        kk: 'Жарияланған жаңартулар әлі жоқ.',
        de: 'Noch keine veröffentlichten Updates.',
        fr: 'Aucune mise à jour publiée pour l\'instant.',
        es: 'Aún no hay actualizaciones publicadas.',
        pt: 'Nenhuma atualização publicada ainda.',
        tr: 'Henüz yayımlanmış güncelleme yok.',
        uk: 'Поки немає опублікованих оновлень.',
        zh: '暂无已发布的更新。',
        ar: 'لا توجد تحديثات منشورة حتى الآن.',
        pl: 'Brak opublikowanych aktualizacji.',
        it: 'Nessun aggiornamento pubblicato ancora.',
        sk: 'Brak opublikowanych aktualizacji.',
      }),
      openDetails: t({
        ru: 'Открыть детали',
        en: 'Open details',
        kk: 'Толығырақ ашу',
        de: 'Details öffnen',
        fr: 'Ouvrir les détails',
        es: 'Abrir detalles',
        pt: 'Abrir detalhes',
        tr: 'Ayrıntıları aç',
        uk: 'Відкрити деталі',
        zh: '打开详情',
        ar: 'فتح التفاصيل',
        pl: 'Otwórz szczegóły',
        it: 'Apri dettagli',
        sk: 'Otwórz szczegóły',
      }),
      releaseLabel: t({
        ru: 'Релиз',
        en: 'Release',
        kk: 'Релиз',
        de: 'Release',
        fr: 'Version',
        es: 'Versión',
        pt: 'Versão',
        tr: 'Sürüm',
        uk: 'Реліз',
        zh: '版本',
        ar: 'الإصدار',
        pl: 'Wydanie',
        it: 'Release',
        sk: 'Wydanie',
      }),
      closeLabel: t({
        ru: 'Закрыть changelog',
        en: 'Close changelog',
        kk: 'Changelog жабу',
        de: 'Changelog schließen',
        fr: 'Fermer le changelog',
        es: 'Cerrar changelog',
        pt: 'Fechar changelog',
        tr: 'Changelog\'u kapat',
        uk: 'Закрити changelog',
        zh: '关闭 changelog',
        ar: 'إغلاق changelog',
        pl: 'Zamknij changelog',
        it: 'Chiudi changelog',
        sk: 'Zamknij changelog',
      }),
    },
    validation: {
      passwordRequiredForEmail: t({
        ru: 'Введите текущий пароль для подтверждения.',
        en: 'Enter your current password to confirm.',
        kk: 'Растау үшін ағымдағы құпиясөзді енгізіңіз.',
        de: 'Geben Sie Ihr aktuelles Passwort zur Bestätigung ein.',
        fr: 'Entrez votre mot de passe actuel pour confirmer.',
        es: 'Introduce tu contraseña actual para confirmar.',
        pt: 'Digite sua senha atual para confirmar.',
        tr: 'Onaylamak için mevcut şifrenizi girin.',
        uk: 'Введіть поточний пароль для підтвердження.',
        zh: '请输入当前密码以确认。',
        ar: 'أدخل كلمة مرورك الحالية للتأكيد.',
        pl: 'Podaj aktualne hasło, aby potwierdzić.',
        it: 'Inserisci la tua password attuale per confermare.',
        sk: 'Podaj aktualne hasło, aby potwierdzić.',
      }),
      passwordMismatch: t({
        ru: 'Новый пароль и подтверждение не совпадают.',
        en: 'New password and confirmation do not match.',
        kk: 'Жаңа құпиясөз бен растау сәйкес келмейді.',
        de: 'Neues Passwort und Bestätigung stimmen nicht überein.',
        fr: 'Le nouveau mot de passe et la confirmation ne correspondent pas.',
        es: 'La nueva contraseña y la confirmación no coinciden.',
        pt: 'A nova senha e a confirmação não coincidem.',
        tr: 'Yeni şifre ve onay eşleşmiyor.',
        uk: 'Новий пароль та підтвердження не збігаються.',
        zh: '新密码与确认密码不匹配。',
        ar: 'كلمة المرور الجديدة والتأكيد غير متطابقين.',
        pl: 'Nowe hasło i potwierdzenie nie są zgodne.',
        it: 'La nuova password e la conferma non coincidono.',
        sk: 'Nowe hasło i potwierdzenie nie są zgodne.',
      }),
    },
    emailCard: {
      title: t({ ru: 'Email', en: 'Email', kk: 'Email', de: 'E-Mail', fr: 'E-mail', es: 'Correo electrónico', pt: 'E-mail', tr: 'E-posta', uk: 'Email', zh: '邮箱', ar: 'البريد الإلكتروني', pl: 'E-mail', it: 'Email', sk: 'E-mail'}),
      newEmailLabel: t({
        ru: 'Новый email',
        en: 'New email',
        kk: 'Жаңа email',
        de: 'Neue E-Mail',
        fr: 'Nouvel e-mail',
        es: 'Nuevo correo',
        pt: 'Novo e-mail',
        tr: 'Yeni e-posta',
        uk: 'Новий email',
        zh: '新邮箱',
        ar: 'البريد الإلكتروني الجديد',
        pl: 'Nowy e-mail',
        it: 'Nuova email',
        sk: 'Nowy e-mail',
      }),
      currentPasswordLabel: t({
        ru: 'Текущий пароль',
        en: 'Current password',
        kk: 'Ағымдағы құпиясөз',
        de: 'Aktuelles Passwort',
        fr: 'Mot de passe actuel',
        es: 'Contraseña actual',
        pt: 'Senha atual',
        tr: 'Mevcut şifre',
        uk: 'Поточний пароль',
        zh: '当前密码',
        ar: 'كلمة المرور الحالية',
        pl: 'Aktualne hasło',
        it: 'Password attuale',
        sk: 'Aktualne hasło',
      }),
      currentPasswordHelp: t({
        ru: 'Мы запрашиваем пароль, чтобы подтвердить смену email.',
        en: 'We ask for your password to confirm the email change.',
        kk: 'Email өзгерісін растау үшін құпиясөз сұраймыз.',
        de: 'Wir fragen Ihr Passwort ab, um die E-Mail-Änderung zu bestätigen.',
        fr: 'Nous demandons votre mot de passe pour confirmer le changement d\'e-mail.',
        es: 'Solicitamos tu contraseña para confirmar el cambio de correo.',
        pt: 'Solicitamos sua senha para confirmar a alteração de e-mail.',
        tr: 'E-posta değişikliğini onaylamak için şifrenizi istiyoruz.',
        uk: 'Ми запитуємо пароль для підтвердження зміни email.',
        zh: '我们需要您的密码来确认邮箱更改。',
        ar: 'نطلب كلمة مرورك لتأكيد تغيير البريد الإلكتروني.',
        pl: 'Prosimy o hasło, aby potwierdzić zmianę e-maila.',
        it: 'Chiediamo la tua password per confermare la modifica dell\'email.',
        sk: 'Prosimy o hasło, aby potwierdzić zmianę e-maila.',
      }),
      submit: t({
        ru: 'Обновить email',
        en: 'Update email',
        kk: 'Email жаңарту',
        de: 'E-Mail aktualisieren',
        fr: 'Mettre à jour l\'e-mail',
        es: 'Actualizar correo',
        pt: 'Atualizar e-mail',
        tr: 'E-postayı güncelle',
        uk: 'Оновити email',
        zh: '更新邮箱',
        ar: 'تحديث البريد الإلكتروني',
        pl: 'Zaktualizuj e-mail',
        it: 'Aggiorna email',
        sk: 'Zaktualizuj e-mail',
      }),
      successFallback: t({
        ru: 'Email успешно обновлён.',
        en: 'Email updated successfully.',
        kk: 'Email сәтті жаңартылды.',
        de: 'E-Mail erfolgreich aktualisiert.',
        fr: 'E-mail mis à jour avec succès.',
        es: 'Correo actualizado correctamente.',
        pt: 'E-mail atualizado com sucesso.',
        tr: 'E-posta başarıyla güncellendi.',
        uk: 'Email успішно оновлено.',
        zh: '邮箱更新成功。',
        ar: 'تم تحديث البريد الإلكتروني بنجاح.',
        pl: 'E-mail zaktualizowany pomyślnie.',
        it: 'Email aggiornata con successo.',
        sk: 'E-mail zaktualizowany pomyślnie.',
      }),
      errorFallback: t({
        ru: 'Не удалось обновить email.',
        en: 'Failed to update email.',
        kk: 'Email жаңарту мүмкін болмады.',
        de: 'E-Mail konnte nicht aktualisiert werden.',
        fr: 'Impossible de mettre à jour l\'e-mail.',
        es: 'No se pudo actualizar el correo.',
        pt: 'Falha ao atualizar e-mail.',
        tr: 'E-posta güncellenemedi.',
        uk: 'Не вдалося оновити email.',
        zh: '无法更新邮箱。',
        ar: 'فشل تحديث البريد الإلكتروني.',
        pl: 'Nie udało się zaktualizować e-maila.',
        it: 'Impossibile aggiornare l\'email.',
        sk: 'Nie udało się zaktualizować e-maila.',
      }),
    },
    profileCard: {
      title: t({
        ru: 'Профиль',
        en: 'Profile',
        kk: 'Профиль',
        de: 'Profil',
        fr: 'Profil',
        es: 'Perfil',
        pt: 'Perfil',
        tr: 'Profil',
        uk: 'Профіль',
        zh: '个人资料',
        ar: 'الملف الشخصي',
        pl: 'Profil',
        it: 'Profilo',
        sk: 'Profil',
      }),
      nameLabel: t({
        ru: 'Имя',
        en: 'Name',
        kk: 'Аты',
        de: 'Name',
        fr: 'Nom',
        es: 'Nombre',
        pt: 'Nome',
        tr: 'Ad',
        uk: 'Ім\'я',
        zh: '姓名',
        ar: 'الاسم',
        pl: 'Imię',
        it: 'Nome',
        sk: 'Imię',
      }),
      languageLabel: t({
        ru: 'Язык интерфейса',
        en: 'Language',
        kk: 'Тіл',
        de: 'Sprache',
        fr: 'Langue',
        es: 'Idioma',
        pt: 'Idioma',
        tr: 'Dil',
        uk: 'Мова інтерфейсу',
        zh: '界面语言',
        ar: 'لغة الواجهة',
        pl: 'Język',
        it: 'Lingua',
        sk: 'Język',
      }),
      timeZoneLabel: t({
        ru: 'Часовой пояс',
        en: 'Time zone',
        kk: 'Уақыт белдеуі',
        de: 'Zeitzone',
        fr: 'Fuseau horaire',
        es: 'Zona horaria',
        pt: 'Fuso horário',
        tr: 'Saat dilimi',
        uk: 'Часовий пояс',
        zh: '时区',
        ar: 'المنطقة الزمنية',
        pl: 'Strefa czasowa',
        it: 'Fuso orario',
        sk: 'Strefa czasowa',
      }),
      timeZoneHelp: t({
        ru: 'Оставьте «Авто», чтобы использовать часовой пояс устройства.',
        en: 'Keep "Auto" to use your device time zone.',
        kk: 'Құрылғының уақыт белдеуін қолдану үшін «Авто» қалдырыңыз.',
        de: 'Behalten Sie „Auto", um die Gerätezeitzone zu verwenden.',
        fr: 'Laissez « Auto » pour utiliser le fuseau horaire de votre appareil.',
        es: 'Mantén «Auto» para usar la zona horaria del dispositivo.',
        pt: 'Mantenha "Auto" para usar o fuso horário do dispositivo.',
        tr: 'Cihaz saat dilimini kullanmak için "Otomatik" bırakın.',
        uk: 'Залиште «Авто», щоб використовувати часовий пояс пристрою.',
        zh: '保持"自动"以使用设备时区。',
        ar: 'احتفظ بـ «تلقائي» لاستخدام المنطقة الزمنية للجهاز.',
        pl: 'Zostaw «Auto», aby używać strefy czasowej urządzenia.',
        it: 'Mantieni "Auto" per usare il fuso orario del dispositivo.',
        sk: 'Zostaw «Auto», aby używać strefy czasowej urządzenia.',
      }),
      submit: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Speichern',
        fr: 'Enregistrer',
        es: 'Guardar',
        pt: 'Salvar',
        tr: 'Kaydet',
        uk: 'Зберегти',
        zh: '保存',
        ar: 'حفظ',
        pl: 'Zapisz',
        it: 'Salva',
        sk: 'Zapisz',
      }),
      unsavedChanges: t({
        ru: 'Есть несохранённые изменения.',
        en: 'Unsaved changes.',
        kk: 'Сақталмаған өзгерістер бар.',
        de: 'Nicht gespeicherte Änderungen.',
        fr: 'Modifications non enregistrées.',
        es: 'Cambios sin guardar.',
        pt: 'Alterações não salvas.',
        tr: 'Kaydedilmemiş değişiklikler.',
        uk: 'Є незбережені зміни.',
        zh: '有未保存的更改。',
        ar: 'توجد تغييرات غير محفوظة.',
        pl: 'Niezapisane zmiany.',
        it: 'Modifiche non salvate.',
        sk: 'Niezapisane zmiany.',
      }),
      successFallback: t({
        ru: 'Профиль обновлён.',
        en: 'Profile updated.',
        kk: 'Профиль жаңартылды.',
        de: 'Profil aktualisiert.',
        fr: 'Profil mis à jour.',
        es: 'Perfil actualizado.',
        pt: 'Perfil atualizado.',
        tr: 'Profil güncellendi.',
        uk: 'Профіль оновлено.',
        zh: '个人资料已更新。',
        ar: 'تم تحديث الملف الشخصي.',
        pl: 'Profil zaktualizowany.',
        it: 'Profilo aggiornato.',
        sk: 'Profil zaktualizowany.',
      }),
      errorFallback: t({
        ru: 'Не удалось обновить профиль.',
        en: 'Failed to update profile.',
        kk: 'Профильді жаңарту мүмкін болмады.',
        de: 'Profil konnte nicht aktualisiert werden.',
        fr: 'Impossible de mettre à jour le profil.',
        es: 'No se pudo actualizar el perfil.',
        pt: 'Falha ao atualizar o perfil.',
        tr: 'Profil güncellenemedi.',
        uk: 'Не вдалося оновити профіль.',
        zh: '无法更新个人资料。',
        ar: 'فشل تحديث الملف الشخصي.',
        pl: 'Nie udało się zaktualizować profilu.',
        it: 'Impossibile aggiornare il profilo.',
        sk: 'Nie udało się zaktualizować profilu.',
      }),
      languages: {
        ru: t({ ru: 'Русский', en: 'Русский', kk: 'Русский', de: 'Русский', fr: 'Русский', es: 'Русский', pt: 'Русский', tr: 'Русский', uk: 'Русский', zh: 'Русский', ar: 'Русский', pl: 'Русский', it: 'Русский', sk: 'Русский'}),
        en: t({ ru: 'English', en: 'English', kk: 'English', de: 'English', fr: 'English', es: 'English', pt: 'English', tr: 'English', uk: 'English', zh: 'English', ar: 'English', pl: 'English', it: 'English', sk: 'English'}),
        kk: t({ ru: 'Қазақша', en: 'Қазақша', kk: 'Қазақша', de: 'Қазақша', fr: 'Қазақша', es: 'Қазақша', pt: 'Қазақша', tr: 'Қазақша', uk: 'Қазақша', zh: 'Қазақша', ar: 'Қазақша', pl: 'Қазақша', it: 'Қазақша', sk: 'Қазақша'}),
        auto: t({ ru: 'Авто', en: 'Auto', kk: 'Авто', de: 'Auto', fr: 'Auto', es: 'Auto', pt: 'Auto', tr: 'Otomatik', uk: 'Авто', zh: '自动', ar: 'تلقائي', pl: 'Auto', it: 'Auto', sk: 'Auto'}),
      },
      timeZones: {
        auto: t({ ru: 'Авто', en: 'Auto', kk: 'Авто', de: 'Auto', fr: 'Auto', es: 'Auto', pt: 'Auto', tr: 'Otomatik', uk: 'Авто', zh: '自动', ar: 'تلقائي', pl: 'Auto', it: 'Auto', sk: 'Auto'}),
        utc: t({ ru: 'UTC', en: 'UTC', kk: 'UTC', de: 'UTC', fr: 'UTC', es: 'UTC', pt: 'UTC', tr: 'UTC', uk: 'UTC', zh: 'UTC', ar: 'UTC', pl: 'UTC', it: 'UTC', sk: 'UTC'}),
        europeMoscow: t({
          ru: 'Europe/Moscow',
          en: 'Europe/Moscow',
          kk: 'Europe/Moscow',
          de: 'Europe/Moscow',
          fr: 'Europe/Moscow',
          es: 'Europe/Moscow',
          pt: 'Europe/Moscow',
          tr: 'Europe/Moscow',
          uk: 'Europe/Moscow',
          zh: 'Europe/Moscow',
          ar: 'Europe/Moscow',
          pl: 'Europe/Moscow',
          it: 'Europe/Moscow',
          sk: 'Europe/Moscow',
        }),
        asiaAlmaty: t({
          ru: 'Asia/Almaty',
          en: 'Asia/Almaty',
          kk: 'Asia/Almaty',
          de: 'Asia/Almaty',
          fr: 'Asia/Almaty',
          es: 'Asia/Almaty',
          pt: 'Asia/Almaty',
          tr: 'Asia/Almaty',
          uk: 'Asia/Almaty',
          zh: 'Asia/Almaty',
          ar: 'Asia/Almaty',
          pl: 'Asia/Almaty',
          it: 'Asia/Almaty',
          sk: 'Asia/Almaty',
        }),
      },
      editPhotoLabel: t({
        ru: 'Изменить фото',
        en: 'Edit photo',
        kk: 'Фотоны өзгерту',
        de: 'Foto bearbeiten',
        fr: 'Modifier la photo',
        es: 'Editar foto',
        pt: 'Editar foto',
        tr: 'Fotoğrafı düzenle',
        uk: 'Змінити фото',
        zh: '编辑照片',
        ar: 'تعديل الصورة',
        pl: 'Edytuj zdjęcie',
        it: 'Modifica foto',
        sk: 'Edytuj zdjęcie',
      }),
      avatarUpdated: t({
        ru: 'Аватар обновлен.',
        en: 'Avatar updated.',
        kk: 'Аватар жаңартылды.',
        de: 'Avatar aktualisiert.',
        fr: 'Avatar mis à jour.',
        es: 'Avatar actualizado.',
        pt: 'Avatar atualizado.',
        tr: 'Avatar güncellendi.',
        uk: 'Аватар оновлено.',
        zh: '头像已更新。',
        ar: 'تم تحديث الصورة الرمزية.',
        pl: 'Awatar zaktualizowany.',
        it: 'Avatar aggiornato.',
        sk: 'Awatar zaktualizowany.',
      }),
      avatarError: t({
        ru: 'Не удалось обновить аватар.',
        en: 'Failed to update avatar.',
        kk: 'Аватарды жаңарту мүмкін болмады.',
        de: 'Avatar konnte nicht aktualisiert werden.',
        fr: 'Impossible de mettre à jour l\'avatar.',
        es: 'No se pudo actualizar el avatar.',
        pt: 'Falha ao atualizar o avatar.',
        tr: 'Avatar güncellenemedi.',
        uk: 'Не вдалося оновити аватар.',
        zh: '无法更新头像。',
        ar: 'فشل تحديث الصورة الرمزية.',
        pl: 'Nie udało się zaktualizować awatara.',
        it: 'Impossibile aggiornare l\'avatar.',
        sk: 'Nie udało się zaktualizować awatara.',
      }),
      avatarSizeError: t({
        ru: 'Слишком большой файл. Максимум 2 МБ.',
        en: 'File is too large. Max 2 MB.',
        kk: 'Файл тым үлкен. Ең көбі 2 МБ.',
        de: 'Datei ist zu groß. Maximal 2 MB.',
        fr: 'Fichier trop volumineux. Maximum 2 Mo.',
        es: 'El archivo es demasiado grande. Máximo 2 MB.',
        pt: 'Arquivo muito grande. Máximo 2 MB.',
        tr: 'Dosya çok büyük. Maks. 2 MB.',
        uk: 'Файл завеликий. Максимум 2 МБ.',
        zh: '文件太大。最大 2 MB。',
        ar: 'الملف كبير جدًا. الحد الأقصى 2 ميغابايت.',
        pl: 'Plik jest za duży. Maks. 2 MB.',
        it: 'File troppo grande. Massimo 2 MB.',
        sk: 'Plik jest za duży. Maks. 2 MB.',
      }),
    },
    sessionsCard: {
      title: t({
        ru: 'Сеансы',
        en: 'Sessions',
        kk: 'Сеанстар',
        de: 'Sitzungen',
        fr: 'Sessions',
        es: 'Sesiones',
        pt: 'Sessões',
        tr: 'Oturumlar',
        uk: 'Сеанси',
        zh: '会话',
        ar: 'الجلسات',
        pl: 'Sesje',
        it: 'Sessioni',
        sk: 'Sesje',
      }),
      lastLoginLabel: t({
        ru: 'Последний вход',
        en: 'Last login',
        kk: 'Соңғы кіру',
        de: 'Letzte Anmeldung',
        fr: 'Dernière connexion',
        es: 'Último acceso',
        pt: 'Último login',
        tr: 'Son giriş',
        uk: 'Останній вхід',
        zh: '最后登录',
        ar: 'آخر تسجيل دخول',
        pl: 'Ostatnie logowanie',
        it: 'Ultimo accesso',
        sk: 'Ostatnie logowanie',
      }),
      activeSessionsLabel: t({
        ru: 'Активные устройства',
        en: 'Active devices',
        kk: 'Белсенді құрылғылар',
        de: 'Aktive Geräte',
        fr: 'Appareils actifs',
        es: 'Dispositivos activos',
        pt: 'Dispositivos ativos',
        tr: 'Aktif cihazlar',
        uk: 'Активні пристрої',
        zh: '活跃设备',
        ar: 'الأجهزة النشطة',
        pl: 'Aktywne urządzenia',
        it: 'Dispositivi attivi',
        sk: 'Aktywne urządzenia',
      }),
      currentSessionBadge: t({
        ru: 'Это устройство',
        en: 'This device',
        kk: 'Бұл құрылғы',
        de: 'Dieses Gerät',
        fr: 'Cet appareil',
        es: 'Este dispositivo',
        pt: 'Este dispositivo',
        tr: 'Bu cihaz',
        uk: 'Цей пристрій',
        zh: '此设备',
        ar: 'هذا الجهاز',
        pl: 'To urządzenie',
        it: 'Questo dispositivo',
        sk: 'To urządzenie',
      }),
      loadingLabel: t({
        ru: 'Загрузка сеансов...',
        en: 'Loading sessions...',
        kk: 'Сеанстар жүктелуде...',
        de: 'Sitzungen werden geladen...',
        fr: 'Chargement des sessions...',
        es: 'Cargando sesiones...',
        pt: 'Carregando sessões...',
        tr: 'Oturumlar yükleniyor...',
        uk: 'Завантаження сеансів...',
        zh: '加载会话中...',
        ar: 'جارٍ تحميل الجلسات...',
        pl: 'Ładowanie sesji...',
        it: 'Caricamento sessioni...',
        sk: 'Ładowanie sesji...',
      }),
      emptySessionsLabel: t({
        ru: 'Активные сеансы не найдены.',
        en: 'No active sessions found.',
        kk: 'Белсенді сеанстар табылмады.',
        de: 'Keine aktiven Sitzungen gefunden.',
        fr: 'Aucune session active trouvée.',
        es: 'No se encontraron sesiones activas.',
        pt: 'Nenhuma sessão ativa encontrada.',
        tr: 'Aktif oturum bulunamadı.',
        uk: 'Активні сеанси не знайдено.',
        zh: '未找到活跃会话。',
        ar: 'لم يتم العثور على جلسات نشطة.',
        pl: 'Nie znaleziono aktywnych sesji.',
        it: 'Nessuna sessione attiva trovata.',
        sk: 'Nie znaleziono aktywnych sesji.',
      }),
      ipLabel: t({ ru: 'IP', en: 'IP', kk: 'IP', de: 'IP', fr: 'IP', es: 'IP', pt: 'IP', tr: 'IP', uk: 'IP', zh: 'IP', ar: 'IP', pl: 'IP', it: 'IP', sk: 'IP'}),
      lastActiveLabel: t({
        ru: 'Последняя активность',
        en: 'Last active',
        kk: 'Соңғы белсенділік',
        de: 'Zuletzt aktiv',
        fr: 'Dernière activité',
        es: 'Última actividad',
        pt: 'Última atividade',
        tr: 'Son aktif',
        uk: 'Остання активність',
        zh: '最后活跃',
        ar: 'آخر نشاط',
        pl: 'Ostatnia aktywność',
        it: 'Ultima attività',
        sk: 'Ostatnia aktywność',
      }),
      logoutSessionButton: t({
        ru: 'Выйти',
        en: 'Log out',
        kk: 'Шығу',
        de: 'Abmelden',
        fr: 'Se déconnecter',
        es: 'Cerrar sesión',
        pt: 'Sair',
        tr: 'Çıkış yap',
        uk: 'Вийти',
        zh: '退出',
        ar: 'تسجيل الخروج',
        pl: 'Wyloguj',
        it: 'Esci',
        sk: 'Wyloguj',
      }),
      sessionLogoutSuccess: t({
        ru: 'Сеанс завершен.',
        en: 'Session logged out.',
        kk: 'Сеанс аяқталды.',
        de: 'Sitzung beendet.',
        fr: 'Session déconnectée.',
        es: 'Sesión cerrada.',
        pt: 'Sessão encerrada.',
        tr: 'Oturumdan çıkıldı.',
        uk: 'Сеанс завершено.',
        zh: '会话已退出。',
        ar: 'تم إنهاء الجلسة.',
        pl: 'Sesja wylogowana.',
        it: 'Sessione disconnessa.',
        sk: 'Sesja wylogowana.',
      }),
      sessionLogoutError: t({
        ru: 'Не удалось завершить сеанс.',
        en: 'Failed to log out session.',
        kk: 'Сеансты аяқтау мүмкін болмады.',
        de: 'Sitzung konnte nicht beendet werden.',
        fr: 'Impossible de déconnecter la session.',
        es: 'No se pudo cerrar la sesión.',
        pt: 'Falha ao encerrar sessão.',
        tr: 'Oturumdan çıkılamadı.',
        uk: 'Не вдалося завершити сеанс.',
        zh: '无法退出会话。',
        ar: 'فشل إنهاء الجلسة.',
        pl: 'Nie udało się wylogować sesji.',
        it: 'Impossibile disconnettere la sessione.',
        sk: 'Nie udało się wylogować sesji.',
      }),
      sessionsLoadError: t({
        ru: 'Не удалось загрузить список сеансов.',
        en: 'Failed to load sessions list.',
        kk: 'Сеанстар тізімін жүктеу мүмкін болмады.',
        de: 'Sitzungsliste konnte nicht geladen werden.',
        fr: 'Impossible de charger la liste des sessions.',
        es: 'No se pudo cargar la lista de sesiones.',
        pt: 'Falha ao carregar lista de sessões.',
        tr: 'Oturum listesi yüklenemedi.',
        uk: 'Не вдалося завантажити список сеансів.',
        zh: '无法加载会话列表。',
        ar: 'فشل تحميل قائمة الجلسات.',
        pl: 'Nie udało się załadować listy sesji.',
        it: 'Impossibile caricare l\'elenco delle sessioni.',
        sk: 'Nie udało się załadować listy sesji.',
      }),
      logoutAllHelp: t({
        ru: 'Завершает все активные сессии на других устройствах и в других браузерах.',
        en: 'Ends all active sessions on other devices and browsers.',
        kk: 'Басқа құрылғылар мен браузерлердегі барлық белсенді сеанстарды аяқтайды.',
        de: 'Beendet alle aktiven Sitzungen auf anderen Geräten und Browsern.',
        fr: 'Met fin à toutes les sessions actives sur d\'autres appareils et navigateurs.',
        es: 'Cierra todas las sesiones activas en otros dispositivos y navegadores.',
        pt: 'Encerra todas as sessões ativas em outros dispositivos e navegadores.',
        tr: 'Diğer cihazlar ve tarayıcılardaki tüm aktif oturumları sonlandırır.',
        uk: 'Завершує всі активні сеанси на інших пристроях і браузерах.',
        zh: '结束其他设备和浏览器上的所有活跃会话。',
        ar: 'ينهي جميع الجلسات النشطة على الأجهزة والمتصفحات الأخرى.',
        pl: 'Kończy wszystkie aktywne sesje na innych urządzeniach i przeglądarkach.',
        it: 'Termina tutte le sessioni attive su altri dispositivi e browser.',
        sk: 'Kończy wszystkie aktywne sesje na innych urządzeniach i przeglądarkach.',
      }),
      securityHint: t({
        ru: 'Завершайте только знакомые сеансы. Выход с текущего устройства завершит текущую авторизацию.',
        en: 'Sign out only sessions you recognize. Logging out on this device ends your current sign-in.',
        kk: 'Тек өзіңіз танитын сеанстардан шығыңыз. Осы құрылғыдан шығу ағымдағы кіруді тоқтатады.',
        de: 'Beenden Sie nur Sitzungen, die Sie kennen. Das Abmelden auf diesem Gerät beendet Ihre aktuelle Anmeldung.',
        fr: 'Déconnectez uniquement les sessions que vous reconnaissez. La déconnexion sur cet appareil met fin à votre connexion actuelle.',
        es: 'Cierra solo las sesiones que reconoces. Cerrar sesión en este dispositivo termina tu acceso actual.',
        pt: 'Encerre apenas sessões que você reconhece. Sair neste dispositivo encerra seu login atual.',
        tr: 'Yalnızca tanıdığınız oturumları kapatın. Bu cihazda çıkış yapmak mevcut girişinizi sonlandırır.',
        uk: 'Завершуйте лише знайомі сеанси. Вихід з поточного пристрою завершить поточну авторизацію.',
        zh: '只退出您认识的会话。在此设备上退出将结束您的当前登录。',
        ar: 'أنهِ فقط الجلسات التي تعرفها. تسجيل الخروج من هذا الجهاز ينهي تسجيل دخولك الحالي.',
        pl: 'Kończ tylko znane sesje. Wylogowanie na tym urządzeniu kończy bieżące logowanie.',
        it: 'Disconnettiti solo dalle sessioni che riconosci. Il logout su questo dispositivo termina il tuo accesso corrente.',
        sk: 'Kończ tylko znane sesje. Wylogowanie na tym urządzeniu kończy bieżące logowanie.',
      }),
      logoutSessionConfirm: t({
        ru: 'Завершить этот сеанс?',
        en: 'Log out this session?',
        kk: 'Осы сеансты аяқтайсыз ба?',
        de: 'Diese Sitzung beenden?',
        fr: 'Déconnecter cette session ?',
        es: '¿Cerrar esta sesión?',
        pt: 'Encerrar esta sessão?',
        tr: 'Bu oturumu kapatılsın mı?',
        uk: 'Завершити цей сеанс?',
        zh: '退出此会话？',
        ar: 'هل تريد إنهاء هذه الجلسة؟',
        pl: 'Zakończyć tę sesję?',
        it: 'Disconnettere questa sessione?',
        sk: 'Zakończyć tę sesję?',
      }),
      logoutCurrentConfirm: t({
        ru: 'Выйти на этом устройстве? Потребуется повторный вход.',
        en: 'Log out on this device? You will need to sign in again.',
        kk: 'Осы құрылғыдан шығасыз ба? Қайта кіру қажет болады.',
        de: 'Auf diesem Gerät abmelden? Sie müssen sich erneut anmelden.',
        fr: 'Se déconnecter sur cet appareil ? Vous devrez vous reconnecter.',
        es: '¿Cerrar sesión en este dispositivo? Tendrás que iniciar sesión de nuevo.',
        pt: 'Sair neste dispositivo? Você precisará fazer login novamente.',
        tr: 'Bu cihazda çıkış yapılsın mı? Yeniden giriş yapmanız gerekecek.',
        uk: 'Вийти на цьому пристрої? Потрібно буде повторно увійти.',
        zh: '在此设备上退出？您需要重新登录。',
        ar: 'تسجيل الخروج من هذا الجهاز؟ ستحتاج إلى تسجيل الدخول مجددًا.',
        pl: 'Wylogować się na tym urządzeniu? Będziesz musiał zalogować się ponownie.',
        it: 'Disconnettersi su questo dispositivo? Dovrai accedere di nuovo.',
        sk: 'Wylogować się na tym urządzeniu? Będziesz musiał zalogować się ponownie.',
      }),
      logoutAllConfirm: t({
        ru: 'Выйти со всех устройств? На каждом устройстве потребуется вход заново.',
        en: 'Log out of all devices? You will need to sign in again on each device.',
        kk: 'Барлық құрылғылардан шығасыз ба? Әр құрылғыда қайта кіру қажет болады.',
        de: 'Von allen Geräten abmelden? Sie müssen sich auf jedem Gerät erneut anmelden.',
        fr: 'Se déconnecter de tous les appareils ? Vous devrez vous reconnecter sur chaque appareil.',
        es: '¿Cerrar sesión en todos los dispositivos? Tendrás que iniciar sesión de nuevo en cada uno.',
        pt: 'Sair de todos os dispositivos? Você precisará fazer login novamente em cada dispositivo.',
        tr: 'Tüm cihazlardan çıkış yapılsın mı? Her cihazda yeniden giriş yapmanız gerekecek.',
        uk: 'Вийти з усіх пристроїв? На кожному пристрої потрібно буде повторно увійти.',
        zh: '退出所有设备？您需要在每台设备上重新登录。',
        ar: 'تسجيل الخروج من جميع الأجهزة؟ ستحتاج إلى تسجيل الدخول مجددًا على كل جهاز.',
        pl: 'Wylogować się ze wszystkich urządzeń? Na każdym urządzeniu będzie wymagane ponowne logowanie.',
        it: 'Disconnettersi da tutti i dispositivi? Dovrai accedere di nuovo su ogni dispositivo.',
        sk: 'Wylogować się ze wszystkich urządzeń? Na każdym urządzeniu będzie wymagane ponowne logowanie.',
      }),
      logoutAllButton: t({
        ru: 'Выйти со всех устройств',
        en: 'Log out of all devices',
        kk: 'Барлық құрылғылардан шығу',
        de: 'Von allen Geräten abmelden',
        fr: 'Se déconnecter de tous les appareils',
        es: 'Cerrar sesión en todos los dispositivos',
        pt: 'Sair de todos os dispositivos',
        tr: 'Tüm cihazlardan çıkış yap',
        uk: 'Вийти з усіх пристроїв',
        zh: '退出所有设备',
        ar: 'تسجيل الخروج من جميع الأجهزة',
        pl: 'Wyloguj ze wszystkich urządzeń',
        it: 'Disconnetti da tutti i dispositivi',
        sk: 'Wyloguj ze wszystkich urządzeń',
      }),
    },
    passwordCard: {
      title: t({
        ru: 'Пароль',
        en: 'Password',
        kk: 'Құпиясөз',
        de: 'Passwort',
        fr: 'Mot de passe',
        es: 'Contraseña',
        pt: 'Senha',
        tr: 'Şifre',
        uk: 'Пароль',
        zh: '密码',
        ar: 'كلمة المرور',
        pl: 'Hasło',
        it: 'Password',
        sk: 'Hasło',
      }),
      currentPasswordLabel: t({
        ru: 'Текущий пароль',
        en: 'Current password',
        kk: 'Ағымдағы құпиясөз',
        de: 'Aktuelles Passwort',
        fr: 'Mot de passe actuel',
        es: 'Contraseña actual',
        pt: 'Senha atual',
        tr: 'Mevcut şifre',
        uk: 'Поточний пароль',
        zh: '当前密码',
        ar: 'كلمة المرور الحالية',
        pl: 'Aktualne hasło',
        it: 'Password attuale',
        sk: 'Aktualne hasło',
      }),
      newPasswordLabel: t({
        ru: 'Новый пароль',
        en: 'New password',
        kk: 'Жаңа құпиясөз',
        de: 'Neues Passwort',
        fr: 'Nouveau mot de passe',
        es: 'Nueva contraseña',
        pt: 'Nova senha',
        tr: 'Yeni şifre',
        uk: 'Новий пароль',
        zh: '新密码',
        ar: 'كلمة المرور الجديدة',
        pl: 'Nowe hasło',
        it: 'Nuova password',
        sk: 'Nowe hasło',
      }),
      newPasswordHelp: t({
        ru: 'Минимум 8 символов.',
        en: 'At least 8 characters.',
        kk: 'Кемінде 8 таңба.',
        de: 'Mindestens 8 Zeichen.',
        fr: 'Au moins 8 caractères.',
        es: 'Al menos 8 caracteres.',
        pt: 'Pelo menos 8 caracteres.',
        tr: 'En az 8 karakter.',
        uk: 'Мінімум 8 символів.',
        zh: '至少 8 个字符。',
        ar: '8 أحرف على الأقل.',
        pl: 'Co najmniej 8 znaków.',
        it: 'Almeno 8 caratteri.',
        sk: 'Co najmniej 8 znaków.',
      }),
      confirmPasswordLabel: t({
        ru: 'Подтвердите новый пароль',
        en: 'Confirm new password',
        kk: 'Жаңа құпиясөзді растаңыз',
        de: 'Neues Passwort bestätigen',
        fr: 'Confirmer le nouveau mot de passe',
        es: 'Confirmar nueva contraseña',
        pt: 'Confirmar nova senha',
        tr: 'Yeni şifreyi onaylayın',
        uk: 'Підтвердіть новий пароль',
        zh: '确认新密码',
        ar: 'تأكيد كلمة المرور الجديدة',
        pl: 'Potwierdź nowe hasło',
        it: 'Conferma nuova password',
        sk: 'Potwierdź nowe hasło',
      }),
      submit: t({
        ru: 'Обновить пароль',
        en: 'Update password',
        kk: 'Құпиясөз жаңарту',
        de: 'Passwort aktualisieren',
        fr: 'Mettre à jour le mot de passe',
        es: 'Actualizar contraseña',
        pt: 'Atualizar senha',
        tr: 'Şifreyi güncelle',
        uk: 'Оновити пароль',
        zh: '更新密码',
        ar: 'تحديث كلمة المرور',
        pl: 'Zaktualizuj hasło',
        it: 'Aggiorna password',
        sk: 'Zaktualizuj hasło',
      }),
      securityHint: t({
        ru: 'Используйте уникальный пароль и подтверждайте действие перед сохранением.',
        en: 'Use a unique password and confirm the action before saving.',
        kk: 'Бірегей құпиясөз қолданып, сақтар алдында әрекетті растаңыз.',
        de: 'Verwenden Sie ein eindeutiges Passwort und bestätigen Sie die Aktion vor dem Speichern.',
        fr: 'Utilisez un mot de passe unique et confirmez l\'action avant d\'enregistrer.',
        es: 'Usa una contraseña única y confirma la acción antes de guardar.',
        pt: 'Use uma senha única e confirme a ação antes de salvar.',
        tr: 'Benzersiz bir şifre kullanın ve kaydetmeden önce işlemi onaylayın.',
        uk: 'Використовуйте унікальний пароль та підтверджуйте дію перед збереженням.',
        zh: '使用唯一密码并在保存前确认操作。',
        ar: 'استخدم كلمة مرور فريدة وأكّد الإجراء قبل الحفظ.',
        pl: 'Używaj unikalnego hasła i potwierdź działanie przed zapisaniem.',
        it: 'Usa una password univoca e conferma l\'azione prima di salvare.',
        sk: 'Używaj unikalnego hasła i potwierdź działanie przed zapisaniem.',
      }),
      confirmSubmit: t({
        ru: 'Обновить пароль сейчас? Возможно, потребуется заново войти на других устройствах.',
        en: 'Update password now? You may need to sign in again on other devices.',
        kk: 'Құпиясөзді қазір жаңартасыз ба? Басқа құрылғыларда қайта кіру қажет болуы мүмкін.',
        de: 'Passwort jetzt aktualisieren? Möglicherweise müssen Sie sich auf anderen Geräten erneut anmelden.',
        fr: 'Mettre à jour le mot de passe maintenant ? Vous devrez peut-être vous reconnecter sur d\'autres appareils.',
        es: '¿Actualizar contraseña ahora? Es posible que tengas que iniciar sesión de nuevo en otros dispositivos.',
        pt: 'Atualizar senha agora? Pode ser necessário fazer login novamente em outros dispositivos.',
        tr: 'Şifre şimdi güncellensin mi? Diğer cihazlarda yeniden giriş yapmanız gerekebilir.',
        uk: 'Оновити пароль зараз? Можливо, знадобиться повторно увійти на інших пристроях.',
        zh: '立即更新密码？您可能需要在其他设备上重新登录。',
        ar: 'تحديث كلمة المرور الآن؟ قد تحتاج إلى تسجيل الدخول مجددًا على الأجهزة الأخرى.',
        pl: 'Zaktualizować hasło teraz? Może być konieczne ponowne logowanie na innych urządzeniach.',
        it: 'Aggiornare la password ora? Potrebbe essere necessario accedere di nuovo su altri dispositivi.',
        sk: 'Zaktualizować hasło teraz? Może być konieczne ponowne logowanie na innych urządzeniach.',
      }),
      successFallback: t({
        ru: 'Пароль успешно обновлён.',
        en: 'Password updated successfully.',
        kk: 'Құпиясөз сәтті жаңартылды.',
        de: 'Passwort erfolgreich aktualisiert.',
        fr: 'Mot de passe mis à jour avec succès.',
        es: 'Contraseña actualizada correctamente.',
        pt: 'Senha atualizada com sucesso.',
        tr: 'Şifre başarıyla güncellendi.',
        uk: 'Пароль успішно оновлено.',
        zh: '密码更新成功。',
        ar: 'تم تحديث كلمة المرور بنجاح.',
        pl: 'Hasło zaktualizowane pomyślnie.',
        it: 'Password aggiornata con successo.',
        sk: 'Hasło zaktualizowane pomyślnie.',
      }),
      errorFallback: t({
        ru: 'Не удалось обновить пароль.',
        en: 'Failed to update password.',
        kk: 'Құпиясөзді жаңарту мүмкін болмады.',
        de: 'Passwort konnte nicht aktualisiert werden.',
        fr: 'Impossible de mettre à jour le mot de passe.',
        es: 'No se pudo actualizar la contraseña.',
        pt: 'Falha ao atualizar a senha.',
        tr: 'Şifre güncellenemedi.',
        uk: 'Не вдалося оновити пароль.',
        zh: '无法更新密码。',
        ar: 'فشل تحديث كلمة المرور.',
        pl: 'Nie udało się zaktualizować hasła.',
        it: 'Impossibile aggiornare la password.',
        sk: 'Nie udało się zaktualizować hasła.',
      }),
    },
    notificationsCard: {
      title: t({
        ru: 'Уведомления',
        en: 'Notifications',
        kk: 'Хабарландырулар',
        de: 'Benachrichtigungen',
        fr: 'Notifications',
        es: 'Notificaciones',
        pt: 'Notificações',
        tr: 'Bildirimler',
        uk: 'Сповіщення',
        zh: '通知',
        ar: 'الإشعارات',
        pl: 'Powiadomienia',
        it: 'Notifiche',
        sk: 'Powiadomienia',
      }),
      description: t({
        ru: 'Выберите, какие уведомления хотите получать в колокольчике.',
        en: 'Choose which notifications you want to receive in the bell.',
        kk: 'Қоңырауда қандай хабарландырулар алғыңыз келетінін таңдаңыз.',
        de: 'Wählen Sie, welche Benachrichtigungen Sie in der Glocke erhalten möchten.',
        fr: 'Choisissez quelles notifications vous souhaitez recevoir dans la cloche.',
        es: 'Elige qué notificaciones quieres recibir en la campana.',
        pt: 'Escolha quais notificações deseja receber no sino.',
        tr: 'Zilde hangi bildirimleri almak istediğinizi seçin.',
        uk: 'Виберіть, які сповіщення хочете отримувати в дзвіночку.',
        zh: '选择您希望在铃铛中收到的通知。',
        ar: 'اختر الإشعارات التي تريد تلقيها في الجرس.',
        pl: 'Wybierz, jakie powiadomienia chcesz otrzymywać w dzwonku.',
        it: 'Scegli quali notifiche vuoi ricevere nella campanella.',
        sk: 'Wybierz, jakie powiadomienia chcesz otrzymywać w dzwonku.',
      }),
      loading: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Laden...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
        sk: 'Ładowanie...',
      }),
      workspace: {
        title: t({
          ru: 'Активность workspace',
          en: 'Workspace activity',
          kk: 'Workspace белсенділігі',
          de: 'Workspace-Aktivität',
          fr: 'Activité de l\'espace de travail',
          es: 'Actividad del workspace',
          pt: 'Atividade do workspace',
          tr: 'Workspace etkinliği',
          uk: 'Активність workspace',
          zh: 'Workspace 活动',
          ar: 'نشاط مساحة العمل',
          pl: 'Aktywność workspace',
          it: 'Attività workspace',
          sk: 'Aktywność workspace',
        }),
        description: t({
          ru: 'Уведомления о действиях других участников',
          en: 'Notifications about actions of other members',
          kk: 'Басқа қатысушылар әрекеттері туралы хабарландырулар',
          de: 'Benachrichtigungen über Aktionen anderer Mitglieder',
          fr: 'Notifications sur les actions des autres membres',
          es: 'Notificaciones sobre acciones de otros miembros',
          pt: 'Notificações sobre ações de outros membros',
          tr: 'Diğer üyelerin eylemleri hakkında bildirimler',
          uk: 'Сповіщення про дії інших учасників',
          zh: '关于其他成员操作的通知',
          ar: 'إشعارات بشأن إجراءات الأعضاء الآخرين',
          pl: 'Powiadomienia o działaniach innych członków',
          it: 'Notifiche sulle azioni degli altri membri',
          sk: 'Powiadomienia o działaniach innych członków',
        }),
      },
      system: {
        title: t({
          ru: 'Системные уведомления',
          en: 'System notifications',
          kk: 'Жүйелік хабарландырулар',
          de: 'Systembenachrichtigungen',
          fr: 'Notifications système',
          es: 'Notificaciones del sistema',
          pt: 'Notificações do sistema',
          tr: 'Sistem bildirimleri',
          uk: 'Системні сповіщення',
          zh: '系统通知',
          ar: 'إشعارات النظام',
          pl: 'Powiadomienia systemowe',
          it: 'Notifiche di sistema',
          sk: 'Powiadomienia systemowe',
        }),
        description: t({
          ru: 'Критичные события и ошибки обработки данных',
          en: 'Critical events and data processing errors',
          kk: 'Маңызды оқиғалар мен деректерді өңдеу қателері',
          de: 'Kritische Ereignisse und Datenverarbeitungsfehler',
          fr: 'Événements critiques et erreurs de traitement des données',
          es: 'Eventos críticos y errores de procesamiento de datos',
          pt: 'Eventos críticos e erros de processamento de dados',
          tr: 'Kritik olaylar ve veri işleme hataları',
          uk: 'Критичні події та помилки обробки даних',
          zh: '关键事件和数据处理错误',
          ar: 'الأحداث الحرجة وأخطاء معالجة البيانات',
          pl: 'Krytyczne zdarzenia i błędy przetwarzania danych',
          it: 'Eventi critici ed errori di elaborazione dati',
          sk: 'Krytyczne zdarzenia i błędy przetwarzania danych',
        }),
      },
      items: {
        statementUploaded: {
          label: t({
            ru: 'Загрузка выписок',
            en: 'Statement uploads',
            kk: 'Үзінді жүктеу',
            de: 'Kontoauszüge hochladen',
            fr: 'Téléchargements de relevés',
            es: 'Carga de extractos',
            pt: 'Upload de extratos',
            tr: 'Ekstre yüklemeleri',
            uk: 'Завантаження виписок',
            zh: '账单上传',
            ar: 'تحميل الكشوفات',
            pl: 'Przesyłanie wyciągów',
            it: 'Caricamento estratti',
            sk: 'Przesyłanie wyciągów',
          }),
          description: t({
            ru: 'Когда участники загружают новые выписки',
            en: 'When members upload new statements',
            kk: 'Қатысушылар жаңа үзінді жүктеген кезде',
            de: 'Wenn Mitglieder neue Kontoauszüge hochladen',
            fr: 'Lorsque des membres téléchargent de nouveaux relevés',
            es: 'Cuando los miembros cargan nuevos extractos',
            pt: 'Quando membros fazem upload de novos extratos',
            tr: 'Üyeler yeni ekstre yüklediğinde',
            uk: 'Коли учасники завантажують нові виписки',
            zh: '当成员上传新账单时',
            ar: 'عندما يرفع الأعضاء كشوفات جديدة',
            pl: 'Gdy członkowie przesyłają nowe wyciągi',
            it: 'Quando i membri caricano nuovi estratti',
            sk: 'Gdy członkowie przesyłają nowe wyciągi',
          }),
        },
        importCommitted: {
          label: t({
            ru: 'Импорт транзакций',
            en: 'Transaction import',
            kk: 'Транзакция импорты',
            de: 'Transaktionsimport',
            fr: 'Import de transactions',
            es: 'Importación de transacciones',
            pt: 'Importação de transações',
            tr: 'İşlem içe aktarma',
            uk: 'Імпорт транзакцій',
            zh: '交易导入',
            ar: 'استيراد المعاملات',
            pl: 'Import transakcji',
            it: 'Importazione transazioni',
            sk: 'Import transakcji',
          }),
          description: t({
            ru: 'Когда участники подтверждают импорт транзакций',
            en: 'When members confirm transaction import',
            kk: 'Қатысушылар транзакция импортын растаған кезде',
            de: 'Wenn Mitglieder den Transaktionsimport bestätigen',
            fr: 'Lorsque des membres confirment l\'import de transactions',
            es: 'Cuando los miembros confirman la importación de transacciones',
            pt: 'Quando membros confirmam a importação de transações',
            tr: 'Üyeler işlem içe aktarmayı onayladığında',
            uk: 'Коли учасники підтверджують імпорт транзакцій',
            zh: '当成员确认交易导入时',
            ar: 'عندما يؤكد الأعضاء استيراد المعاملات',
            pl: 'Gdy członkowie potwierdzają import transakcji',
            it: 'Quando i membri confermano l\'importazione delle transazioni',
            sk: 'Gdy członkowie potwierdzają import transakcji',
          }),
        },
        categoryChanges: {
          label: t({
            ru: 'Изменение категорий',
            en: 'Category changes',
            kk: 'Санат өзгерістері',
            de: 'Kategorieänderungen',
            fr: 'Modifications de catégories',
            es: 'Cambios de categorías',
            pt: 'Alterações de categorias',
            tr: 'Kategori değişiklikleri',
            uk: 'Зміна категорій',
            zh: '类别更改',
            ar: 'تغييرات الفئات',
            pl: 'Zmiany kategorii',
            it: 'Modifiche categorie',
            sk: 'Zmiany kategorii',
          }),
          description: t({
            ru: 'Создание, изменение и удаление категорий',
            en: 'Category creation, updates, and deletion',
            kk: 'Санатты құру, өзгерту және жою',
            de: 'Erstellen, Aktualisieren und Löschen von Kategorien',
            fr: 'Création, mise à jour et suppression de catégories',
            es: 'Creación, actualización y eliminación de categorías',
            pt: 'Criação, atualização e exclusão de categorias',
            tr: 'Kategori oluşturma, güncelleme ve silme',
            uk: 'Створення, зміна та видалення категорій',
            zh: '创建、更新和删除类别',
            ar: 'إنشاء الفئات وتحديثها وحذفها',
            pl: 'Tworzenie, aktualizacja i usuwanie kategorii',
            it: 'Creazione, aggiornamento ed eliminazione di categorie',
            sk: 'Tworzenie, aktualizacja i usuwanie kategorii',
          }),
        },
        memberActivity: {
          label: t({
            ru: 'Активность участников',
            en: 'Member activity',
            kk: 'Қатысушылар белсенділігі',
            de: 'Mitgliederaktivität',
            fr: 'Activité des membres',
            es: 'Actividad de miembros',
            pt: 'Atividade de membros',
            tr: 'Üye etkinliği',
            uk: 'Активність учасників',
            zh: '成员活动',
            ar: 'نشاط الأعضاء',
            pl: 'Aktywność członków',
            it: 'Attività dei membri',
            sk: 'Aktywność członków',
          }),
          description: t({
            ru: 'Приглашения и вступление новых участников',
            en: 'Invites and new member joins',
            kk: 'Жаңа қатысушыларды шақыру және қосылу',
            de: 'Einladungen und neue Mitglieder',
            fr: 'Invitations et nouveaux membres',
            es: 'Invitaciones y nuevos miembros',
            pt: 'Convites e novos membros',
            tr: 'Davetler ve yeni üye katılımları',
            uk: 'Запрошення та вступ нових учасників',
            zh: '邀请和新成员加入',
            ar: 'الدعوات وانضمام أعضاء جدد',
            pl: 'Zaproszenia i dołączanie nowych członków',
            it: 'Inviti e nuovi membri',
            sk: 'Zaproszenia i dołączanie nowych członków',
          }),
        },
        dataDeleted: {
          label: t({
            ru: 'Удаление данных',
            en: 'Data deletion',
            kk: 'Деректерді жою',
            de: 'Datenlöschung',
            fr: 'Suppression de données',
            es: 'Eliminación de datos',
            pt: 'Exclusão de dados',
            tr: 'Veri silme',
            uk: 'Видалення даних',
            zh: '数据删除',
            ar: 'حذف البيانات',
            pl: 'Usuwanie danych',
            it: 'Eliminazione dati',
            sk: 'Usuwanie danych',
          }),
          description: t({
            ru: 'Удаление транзакций, выписок и других данных',
            en: 'Deletion of transactions, statements, and other data',
            kk: 'Транзакция, үзінді және басқа деректерді жою',
            de: 'Löschen von Transaktionen, Kontoauszügen und anderen Daten',
            fr: 'Suppression de transactions, relevés et autres données',
            es: 'Eliminación de transacciones, extractos y otros datos',
            pt: 'Exclusão de transações, extratos e outros dados',
            tr: 'İşlemlerin, ekstrelerin ve diğer verilerin silinmesi',
            uk: 'Видалення транзакцій, виписок та інших даних',
            zh: '删除交易、账单和其他数据',
            ar: 'حذف المعاملات والكشوفات والبيانات الأخرى',
            pl: 'Usuwanie transakcji, wyciągów i innych danych',
            it: 'Eliminazione di transazioni, estratti e altri dati',
            sk: 'Usuwanie transakcji, wyciągów i innych danych',
          }),
        },
        workspaceUpdated: {
          label: t({
            ru: 'Настройки workspace',
            en: 'Workspace settings',
            kk: 'Workspace баптаулары',
            de: 'Workspace-Einstellungen',
            fr: 'Paramètres du workspace',
            es: 'Configuración del workspace',
            pt: 'Configurações do workspace',
            tr: 'Workspace ayarları',
            uk: 'Налаштування workspace',
            zh: 'Workspace 设置',
            ar: 'إعدادات مساحة العمل',
            pl: 'Ustawienia workspace',
            it: 'Impostazioni workspace',
            sk: 'Ustawienia workspace',
          }),
          description: t({
            ru: 'Изменение названия, валюты и других параметров',
            en: 'Changes in name, currency, and other settings',
            kk: 'Атау, валюта және басқа параметрлер өзгерісі',
            de: 'Änderungen bei Name, Währung und anderen Einstellungen',
            fr: 'Modifications du nom, de la devise et d\'autres paramètres',
            es: 'Cambios en nombre, moneda y otros parámetros',
            pt: 'Alterações em nome, moeda e outros parâmetros',
            tr: 'Ad, para birimi ve diğer ayarlardaki değişiklikler',
            uk: 'Зміна назви, валюти та інших параметрів',
            zh: '名称、货币和其他设置的更改',
            ar: 'التغييرات في الاسم والعملة والإعدادات الأخرى',
            pl: 'Zmiany nazwy, waluty i innych parametrów',
            it: 'Modifiche a nome, valuta e altre impostazioni',
            sk: 'Zmiany nazwy, waluty i innych parametrów',
          }),
        },
        parsingErrors: {
          label: t({
            ru: 'Ошибки парсинга',
            en: 'Parsing errors',
            kk: 'Талдау қателері',
            de: 'Parsing-Fehler',
            fr: 'Erreurs d\'analyse',
            es: 'Errores de análisis',
            pt: 'Erros de análise',
            tr: 'Ayrıştırma hataları',
            uk: 'Помилки парсингу',
            zh: '解析错误',
            ar: 'أخطاء التحليل',
            pl: 'Błędy parsowania',
            it: 'Errori di parsing',
            sk: 'Błędy parsowania',
          }),
          description: t({
            ru: 'Проблемы при обработке выписок',
            en: 'Issues while processing statements',
            kk: 'Үзіндіні өңдеу кезіндегі мәселелер',
            de: 'Probleme bei der Verarbeitung von Kontoauszügen',
            fr: 'Problèmes lors du traitement des relevés',
            es: 'Problemas al procesar extractos',
            pt: 'Problemas ao processar extratos',
            tr: 'Ekstre işleme sırasındaki sorunlar',
            uk: 'Проблеми при обробці виписок',
            zh: '处理账单时出现的问题',
            ar: 'مشكلات أثناء معالجة الكشوفات',
            pl: 'Problemy podczas przetwarzania wyciągów',
            it: 'Problemi durante l\'elaborazione degli estratti',
            sk: 'Problemy podczas przetwarzania wyciągów',
          }),
        },
        importFailures: {
          label: t({
            ru: 'Ошибки импорта',
            en: 'Import failures',
            kk: 'Импорт қателері',
            de: 'Importfehler',
            fr: 'Échecs d\'import',
            es: 'Errores de importación',
            pt: 'Falhas de importação',
            tr: 'İçe aktarma hataları',
            uk: 'Помилки імпорту',
            zh: '导入失败',
            ar: 'فشل الاستيراد',
            pl: 'Błędy importu',
            it: 'Errori di importazione',
            sk: 'Błędy importu',
          }),
          description: t({
            ru: 'Импорт завершился с ошибкой',
            en: 'Import finished with an error',
            kk: 'Импорт қателікпен аяқталды',
            de: 'Import mit Fehler abgeschlossen',
            fr: 'Import terminé avec une erreur',
            es: 'La importación terminó con un error',
            pt: 'Importação concluída com erro',
            tr: 'İçe aktarma hatayla tamamlandı',
            uk: 'Імпорт завершився з помилкою',
            zh: '导入以错误结束',
            ar: 'اكتمل الاستيراد بخطأ',
            pl: 'Import zakończony błędem',
            it: 'Importazione terminata con un errore',
            sk: 'Import zakończony błędem',
          }),
        },
        uncategorizedItems: {
          label: t({
            ru: 'Операции без категории',
            en: 'Uncategorized items',
            kk: 'Санатсыз операциялар',
            de: 'Nicht kategorisierte Einträge',
            fr: 'Éléments non catégorisés',
            es: 'Elementos sin categoría',
            pt: 'Itens não categorizados',
            tr: 'Kategorisiz öğeler',
            uk: 'Операції без категорії',
            zh: '未分类项目',
            ar: 'العناصر غير المصنّفة',
            pl: 'Elementy bez kategorii',
            it: 'Elementi senza categoria',
            sk: 'Elementy bez kategorii',
          }),
          description: t({
            ru: 'Транзакции и чеки, требующие категоризации',
            en: 'Transactions and receipts that require categorization',
            kk: 'Санаттауды қажет ететін транзакциялар мен чектер',
            de: 'Transaktionen und Belege, die kategorisiert werden müssen',
            fr: 'Transactions et reçus nécessitant une catégorisation',
            es: 'Transacciones y recibos que requieren categorización',
            pt: 'Transações e recibos que requerem categorização',
            tr: 'Kategorizasyon gerektiren işlemler ve makbuzlar',
            uk: 'Транзакції та чеки, що потребують категоризації',
            zh: '需要分类的交易和收据',
            ar: 'المعاملات والإيصالات التي تحتاج إلى تصنيف',
            pl: 'Transakcje i paragony wymagające kategoryzacji',
            it: 'Transazioni e ricevute che richiedono categorizzazione',
            sk: 'Transakcje i paragony wymagające kategoryzacji',
          }),
        },
      },
      messages: {
        saved: t({
          ru: 'Настройки сохранены',
          en: 'Settings saved',
          kk: 'Баптаулар сақталды',
          de: 'Einstellungen gespeichert',
          fr: 'Paramètres enregistrés',
          es: 'Configuración guardada',
          pt: 'Configurações salvas',
          tr: 'Ayarlar kaydedildi',
          uk: 'Налаштування збережено',
          zh: '设置已保存',
          ar: 'تم حفظ الإعدادات',
          pl: 'Ustawienia zapisane',
          it: 'Impostazioni salvate',
          sk: 'Ustawienia zapisane',
        }),
      },
      errors: {
        load: t({
          ru: 'Не удалось загрузить настройки уведомлений',
          en: 'Failed to load notification settings',
          kk: 'Хабарландыру баптауларын жүктеу мүмкін болмады',
          de: 'Benachrichtigungseinstellungen konnten nicht geladen werden',
          fr: 'Impossible de charger les paramètres de notification',
          es: 'No se pudieron cargar los ajustes de notificaciones',
          pt: 'Falha ao carregar configurações de notificação',
          tr: 'Bildirim ayarları yüklenemedi',
          uk: 'Не вдалося завантажити налаштування сповіщень',
          zh: '无法加载通知设置',
          ar: 'فشل تحميل إعدادات الإشعارات',
          pl: 'Nie udało się załadować ustawień powiadomień',
          it: 'Impossibile caricare le impostazioni delle notifiche',
          sk: 'Nie udało się załadować ustawień powiadomień',
        }),
        save: t({
          ru: 'Не удалось сохранить настройки уведомлений',
          en: 'Failed to save notification settings',
          kk: 'Хабарландыру баптауларын сақтау мүмкін болмады',
          de: 'Benachrichtigungseinstellungen konnten nicht gespeichert werden',
          fr: 'Impossible d\'enregistrer les paramètres de notification',
          es: 'No se pudieron guardar los ajustes de notificaciones',
          pt: 'Falha ao salvar configurações de notificação',
          tr: 'Bildirim ayarları kaydedilemedi',
          uk: 'Не вдалося зберегти налаштування сповіщень',
          zh: '无法保存通知设置',
          ar: 'فشل حفظ إعدادات الإشعارات',
          pl: 'Nie udało się zapisać ustawień powiadomień',
          it: 'Impossibile salvare le impostazioni delle notifiche',
          sk: 'Nie udało się zapisać ustawień powiadomień',
        }),
      },
    },
    appearanceCard: {
      title: t({
        ru: 'Внешний вид',
        en: 'Appearance',
        kk: 'Көрініс',
        de: 'Erscheinungsbild',
        fr: 'Apparence',
        es: 'Apariencia',
        pt: 'Aparência',
        tr: 'Görünüm',
        uk: 'Зовнішній вигляд',
        zh: '外观',
        ar: 'المظهر',
        pl: 'Wygląd',
        it: 'Aspetto',
        sk: 'Wygląd',
      }),
      description: t({
        ru: 'Настройте тему приложения',
        en: 'Configure application theme',
        kk: 'Қолданба тақырыбын баптаңыз',
        de: 'Anwendungsdesign konfigurieren',
        fr: 'Configurer le thème de l\'application',
        es: 'Configura el tema de la aplicación',
        pt: 'Configure o tema do aplicativo',
        tr: 'Uygulama temasını yapılandırın',
        uk: 'Налаштуйте тему застосунку',
        zh: '配置应用程序主题',
        ar: 'تكوين مظهر التطبيق',
        pl: 'Skonfiguruj motyw aplikacji',
        it: 'Configura il tema dell\'applicazione',
        sk: 'Skonfiguruj motyw aplikacji',
      }),
      themeLabel: t({
        ru: 'Тема',
        en: 'Theme',
        kk: 'Тақырып',
        de: 'Design',
        fr: 'Thème',
        es: 'Tema',
        pt: 'Tema',
        tr: 'Tema',
        uk: 'Тема',
        zh: '主题',
        ar: 'السمة',
        pl: 'Motyw',
        it: 'Tema',
        sk: 'Motyw',
      }),
      themeHelp: t({
        ru: 'Выберите светлую, тёмную или автоматическую тему по расписанию.',
        en: 'Choose a light, dark, or scheduled automatic theme.',
        kk: 'Жарық, қараңғы немесе кесте бойынша автоматты тақырыпты таңдаңыз.',
        de: 'Wählen Sie ein helles, dunkles oder zeitgesteuertes automatisches Design.',
        fr: 'Choisissez un thème clair, sombre ou automatique planifié.',
        es: 'Elige un tema claro, oscuro o automático programado.',
        pt: 'Escolha um tema claro, escuro ou automático agendado.',
        tr: 'Açık, koyu veya zamanlanmış otomatik tema seçin.',
        uk: 'Оберіть світлу, темну або автоматичну тему за розкладом.',
        zh: '选择浅色、深色或按计划自动切换的主题。',
        ar: 'اختر سمة فاتحة أو داكنة أو تلقائية مجدولة.',
        pl: 'Wybierz jasny, ciemny lub automatyczny motyw według harmonogramu.',
        it: 'Scegli un tema chiaro, scuro o automatico programmato.',
        sk: 'Wybierz jasny, ciemny lub automatyczny motyw według harmonogramu.',
      }),
      light: t({
        ru: 'Светлая',
        en: 'Light',
        kk: 'Жарық',
        de: 'Hell',
        fr: 'Clair',
        es: 'Claro',
        pt: 'Claro',
        tr: 'Açık',
        uk: 'Світла',
        zh: '浅色',
        ar: 'فاتح',
        pl: 'Jasny',
        it: 'Chiaro',
        sk: 'Jasny',
      }),
      dark: t({
        ru: 'Тёмная',
        en: 'Dark',
        kk: 'Қараңғы',
        de: 'Dunkel',
        fr: 'Sombre',
        es: 'Oscuro',
        pt: 'Escuro',
        tr: 'Koyu',
        uk: 'Темна',
        zh: '深色',
        ar: 'داكن',
        pl: 'Ciemny',
        it: 'Scuro',
        sk: 'Ciemny',
      }),
      auto: t({
        ru: 'Авто',
        en: 'Auto',
        kk: 'Авто',
        de: 'Auto',
        fr: 'Auto',
        es: 'Auto',
        pt: 'Auto',
        tr: 'Otomatik',
        uk: 'Авто',
        zh: '自动',
        ar: 'تلقائي',
        pl: 'Auto',
        it: 'Auto',
        sk: 'Auto',
      }),
      active: t({
        ru: 'Активная тема',
        en: 'Active theme',
        kk: 'Белсенді тақырып',
        de: 'Aktives Design',
        fr: 'Thème actif',
        es: 'Tema activo',
        pt: 'Tema ativo',
        tr: 'Aktif tema',
        uk: 'Активна тема',
        zh: '当前主题',
        ar: 'السمة النشطة',
        pl: 'Aktywny motyw',
        it: 'Tema attivo',
        sk: 'Aktywny motyw',
      }),
      followsSystem: t({
        ru: 'Светлая тема включается в 07:00, тёмная — в 19:00.',
        en: 'Light theme turns on at 07:00, dark theme at 19:00.',
        kk: 'Жарық тақырып 07:00-де, қараңғы тақырып 19:00-де қосылады.',
        de: 'Helles Design schaltet sich um 07:00 Uhr ein, dunkles um 19:00 Uhr.',
        fr: 'Le thème clair s\'active à 07h00, le thème sombre à 19h00.',
        es: 'El tema claro se activa a las 07:00, el oscuro a las 19:00.',
        pt: 'O tema claro liga às 07:00, o escuro às 19:00.',
        tr: 'Açık tema 07:00\'de, koyu tema 19:00\'da etkinleşir.',
        uk: 'Світла тема вмикається о 07:00, темна — о 19:00.',
        zh: '浅色主题在 07:00 启用，深色主题在 19:00 启用。',
        ar: 'تُفعَّل السمة الفاتحة في 07:00 والداكنة في 19:00.',
        pl: 'Jasny motyw włącza się o 07:00, ciemny o 19:00.',
        it: 'Il tema chiaro si attiva alle 07:00, quello scuro alle 19:00.',
        sk: 'Jasny motyw włącza się o 07:00, ciemny o 19:00.',
      }),
    },
  },
} satisfies Dictionary;

export default content;
