import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'supportedBanksPage',
  content: {
    title: t({
      ru: 'Поддерживаемые банки',
      en: 'Supported banks',
      kk: 'Қолдау көрсетілетін банктер',
      de: 'Unterstützte Banken',
      fr: 'Banques prises en charge',
      es: 'Bancos compatibles',
      pt: 'Bancos suportados',
      tr: 'Desteklenen bankalar',
      uk: 'Підтримувані банки',
      zh: '支持的银行',
      ar: 'البنوك المدعومة',
      pl: 'Obsługiwane banki',
      it: 'Banche supportate',
      sk: 'Obsługiwane banki',
    }),
    subtitle: t({
      ru: 'Список банков, для которых доступен автоматический парсинг выписок.',
      en: 'List of banks currently available for automatic statement parsing.',
      kk: 'Үзінділерді автоматты түрде талдау қолжетімді банктер тізімі.',
      de: 'Liste der Banken, für die automatisches Kontoauszugs-Parsing verfügbar ist.',
      fr: 'Liste des banques disponibles pour l\'analyse automatique des relevés.',
      es: 'Lista de bancos disponibles para el análisis automático de extractos.',
      pt: 'Lista de bancos disponíveis para análise automática de extratos.',
      tr: 'Otomatik hesap özeti ayrıştırması için mevcut bankaların listesi.',
      uk: 'Список банків, для яких доступний автоматичний парсинг виписок.',
      zh: '支持自动对账单解析的银行列表。',
      ar: 'قائمة البنوك المتاحة لتحليل كشوف الحساب تلقائيًا.',
      pl: 'Lista banków dostępnych do automatycznego przetwarzania wyciągów.',
      it: 'Elenco delle banche disponibili per l\'analisi automatica degli estratti conto.',
      sk: 'Lista banków dostępnych do automatycznego przetwarzania wyciągów.',
    }),
    parserStatus: t({
      ru: 'Парсер активен',
      en: 'Parser is active',
      kk: 'Талдау модулі белсенді',
      de: 'Parser ist aktiv',
      fr: 'L\'analyseur est actif',
      es: 'El analizador está activo',
      pt: 'Analisador ativo',
      tr: 'Ayrıştırıcı aktif',
      uk: 'Парсер активний',
      zh: '解析器已激活',
      ar: 'المحلل نشط',
      pl: 'Parser jest aktywny',
      it: 'Il parser è attivo',
      sk: 'Parser jest aktywny',
    }),
    comingSoon: t({
      ru: 'Скоро добавим новые банки',
      en: 'More banks are coming soon',
      kk: 'Жақында жаңа банктер қосылады',
      de: 'Weitere Banken kommen bald',
      fr: 'D\'autres banques arrivent bientôt',
      es: 'Más bancos próximamente',
      pt: 'Mais bancos em breve',
      tr: 'Daha fazla banka yakında eklenecek',
      uk: 'Незабаром додамо нові банки',
      zh: '更多银行即将推出',
      ar: 'المزيد من البنوك قريبًا',
      pl: 'Więcej banków wkrótce',
      it: 'Altre banche in arrivo',
      sk: 'Więcej banków wkrótce',
    }),
    statusLabel: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Status',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Status',
    }),
    formatsLabel: t({
      ru: 'Поддерживаемый формат',
      en: 'Supported format',
      kk: 'Қолдау көрсетілетін формат',
      de: 'Unterstütztes Format',
      fr: 'Format pris en charge',
      es: 'Formato compatible',
      pt: 'Formato suportado',
      tr: 'Desteklenen format',
      uk: 'Підтримуваний формат',
      zh: '支持的格式',
      ar: 'الصيغة المدعومة',
      pl: 'Obsługiwany format',
      it: 'Formato supportato',
      sk: 'Obsługiwany format',
    }),
    supported: t({
      ru: 'Поддерживается',
      en: 'Supported',
      kk: 'Қолдау көрсетіледі',
      de: 'Unterstützt',
      fr: 'Pris en charge',
      es: 'Compatible',
      pt: 'Suportado',
      tr: 'Destekleniyor',
      uk: 'Підтримується',
      zh: '已支持',
      ar: 'مدعوم',
      pl: 'Obsługiwany',
      it: 'Supportato',
      sk: 'Obsługiwany',
    }),
    pdfStatements: t({
      ru: 'PDF-выписки',
      en: 'PDF statements',
      kk: 'PDF үзінділері',
      de: 'PDF-Kontoauszüge',
      fr: 'Relevés PDF',
      es: 'Extractos PDF',
      pt: 'Extratos PDF',
      tr: 'PDF hesap özetleri',
      uk: 'PDF-виписки',
      zh: 'PDF 对账单',
      ar: 'كشوف الحساب PDF',
      pl: 'Wyciągi PDF',
      it: 'Estratti conto PDF',
      sk: 'Wyciągi PDF',
    }),
    banks: {
      kaspi: {
        name: t({ ru: 'Kaspi', en: 'Kaspi', kk: 'Kaspi', de: 'Kaspi', fr: 'Kaspi', es: 'Kaspi', pt: 'Kaspi', tr: 'Kaspi', uk: 'Kaspi', zh: 'Kaspi', ar: 'Kaspi', pl: 'Kaspi', it: 'Kaspi', sk: 'Kaspi'}),
        notes: t({
          ru: 'Загружайте выписки Kaspi в PDF для автоматического распознавания операций.',
          en: 'Upload Kaspi PDF statements for automatic transaction extraction.',
          kk: 'Операцияларды автоматты тану үшін Kaspi PDF үзінділерін жүктеңіз.',
          de: 'Laden Sie Kaspi PDF-Kontoauszüge für automatische Transaktionserkennung hoch.',
          fr: 'Téléchargez les relevés PDF Kaspi pour l\'extraction automatique des transactions.',
          es: 'Sube extractos PDF de Kaspi para la extracción automática de transacciones.',
          pt: 'Envie extratos PDF da Kaspi para extração automática de transações.',
          tr: 'Otomatik işlem çıkarma için Kaspi PDF hesap özetlerini yükleyin.',
          uk: 'Завантажуйте виписки Kaspi у PDF для автоматичного розпізнавання операцій.',
          zh: '上传 Kaspi PDF 对账单以自动提取交易。',
          ar: 'ارفع كشوف حساب Kaspi بتنسيق PDF للاستخراج التلقائي للمعاملات.',
          pl: 'Prześlij wyciągi PDF Kaspi do automatycznego wyodrębniania transakcji.',
          it: 'Carica estratti conto PDF di Kaspi per l\'estrazione automatica delle transazioni.',
          sk: 'Prześlij wyciągi PDF Kaspi do automatycznego wyodrębniania transakcji.',
        }),
      },
      bereke: {
        name: t({ ru: 'Bereke', en: 'Bereke', kk: 'Bereke', de: 'Bereke', fr: 'Bereke', es: 'Bereke', pt: 'Bereke', tr: 'Bereke', uk: 'Bereke', zh: 'Bereke', ar: 'Bereke', pl: 'Bereke', it: 'Bereke', sk: 'Bereke'}),
        notes: t({
          ru: 'Загружайте выписки Bereke в PDF для автоматического распознавания операций.',
          en: 'Upload Bereke PDF statements for automatic transaction extraction.',
          kk: 'Операцияларды автоматты тану үшін Bereke PDF үзінділерін жүктеңіз.',
          de: 'Laden Sie Bereke PDF-Kontoauszüge für automatische Transaktionserkennung hoch.',
          fr: 'Téléchargez les relevés PDF Bereke pour l\'extraction automatique des transactions.',
          es: 'Sube extractos PDF de Bereke para la extracción automática de transacciones.',
          pt: 'Envie extratos PDF da Bereke para extração automática de transações.',
          tr: 'Otomatik işlem çıkarma için Bereke PDF hesap özetlerini yükleyin.',
          uk: 'Завантажуйте виписки Bereke у PDF для автоматичного розпізнавання операцій.',
          zh: '上传 Bereke PDF 对账单以自动提取交易。',
          ar: 'ارفع كشوف حساب Bereke بتنسيق PDF للاستخراج التلقائي للمعاملات.',
          pl: 'Prześlij wyciągi PDF Bereke do automatycznego wyodrębniania transakcji.',
          it: 'Carica estratti conto PDF di Bereke per l\'estrazione automatica delle transazioni.',
          sk: 'Prześlij wyciągi PDF Bereke do automatycznego wyodrębniania transakcji.',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
