import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'pluginsPage',
  content: {
    title: t({
      ru: 'Плагины',
      en: 'Plugins',
      kk: 'Плагиндер',
      de: 'Plugins',
      fr: 'Plugins',
      es: 'Complementos',
      pt: 'Plugins',
      tr: 'Eklentiler',
      uk: 'Плагіни',
      zh: '插件',
      ar: 'الإضافات',
      pl: 'Wtyczki',
      it: 'Plugin',
    }),
    subtitle: t({
      ru: 'Расширяйте возможности Lumio с помощью плагинов.',
      en: 'Extend Lumio with powerful plugins.',
      kk: 'Lumio мүмкіндіктерін плагиндермен кеңейтіңіз.',
      de: 'Erweitern Sie Lumio mit leistungsstarken Plugins.',
      fr: 'Étendez Lumio avec des plugins puissants.',
      es: 'Amplía Lumio con complementos potentes.',
      pt: 'Estenda o Lumio com plugins poderosos.',
      tr: 'Lumio\'yu güçlü eklentilerle genişletin.',
      uk: 'Розширюйте можливості Lumio за допомогою плагінів.',
      zh: '使用强大的插件扩展 Lumio。',
      ar: 'وسّع Lumio بإضافات قوية.',
      pl: 'Rozszerzaj Lumio za pomocą wtyczek.',
      it: 'Estendi Lumio con potenti plugin.',
    }),
    sections: {
      enabled: t({
        ru: 'Включено',
        en: 'Enabled',
        kk: 'Қосылған',
        de: 'Aktiviert',
        fr: 'Activé',
        es: 'Activado',
        pt: 'Ativado',
        tr: 'Etkin',
        uk: 'Увімкнено',
        zh: '已启用',
        ar: 'مفعّل',
        pl: 'Włączone',
        it: 'Attivato',
      }),
      available: t({
        ru: 'Доступно',
        en: 'Available',
        kk: 'Қолжетімді',
        de: 'Verfügbar',
        fr: 'Disponible',
        es: 'Disponible',
        pt: 'Disponível',
        tr: 'Mevcut',
        uk: 'Доступно',
        zh: '可用',
        ar: 'متاح',
        pl: 'Dostępne',
        it: 'Disponibile',
      }),
    },
    enable: t({
      ru: 'Включить',
      en: 'Enable',
      kk: 'Қосу',
      de: 'Aktivieren',
      fr: 'Activer',
      es: 'Activar',
      pt: 'Ativar',
      tr: 'Etkinleştir',
      uk: 'Увімкнути',
      zh: '启用',
      ar: 'تفعيل',
      pl: 'Włącz',
      it: 'Attiva',
    }),
    disable: t({
      ru: 'Отключить',
      en: 'Disable',
      kk: 'Өшіру',
      de: 'Deaktivieren',
      fr: 'Désactiver',
      es: 'Desactivar',
      pt: 'Desativar',
      tr: 'Devre dışı bırak',
      uk: 'Вимкнути',
      zh: '禁用',
      ar: 'تعطيل',
      pl: 'Wyłącz',
      it: 'Disattiva',
    }),
    cards: {
      aiAssistant: {
        name: t({
          ru: 'AI Ассистент',
          en: 'AI Assistant',
          kk: 'AI Көмекші',
          de: 'KI-Assistent',
          fr: 'Assistant IA',
          es: 'Asistente IA',
          pt: 'Assistente IA',
          tr: 'Yapay Zeka Asistanı',
          uk: 'AI Асистент',
          zh: 'AI 助手',
          ar: 'مساعد الذكاء الاصطناعي',
          pl: 'Asystent AI',
          it: 'Assistente IA',
        }),
        description: t({
          ru: 'Анализируйте финансовые данные с помощью ИИ. Подготавливает промпты с вашими данными и передаёт их в ChatGPT.',
          en: 'Analyze financial data with AI. Prepares prompts with your data and hands off to ChatGPT.',
          kk: 'Қаржылық деректерді AI көмегімен талдаңыз. Деректеріңізбен промпттар дайындап, ChatGPT-ге жібереді.',
          de: 'Analysieren Sie Finanzdaten mit KI. Erstellt Prompts mit Ihren Daten und übergibt sie an ChatGPT.',
          fr: 'Analysez vos données financières avec l\'IA. Prépare des prompts avec vos données et les transmet à ChatGPT.',
          es: 'Analiza datos financieros con IA. Prepara prompts con tus datos y los envía a ChatGPT.',
          pt: 'Analise dados financeiros com IA. Prepara prompts com seus dados e envia ao ChatGPT.',
          tr: 'Finansal verileri yapay zeka ile analiz edin. Verilerinizle promptlar hazırlar ve ChatGPT\'ye aktarır.',
          uk: 'Аналізуйте фінансові дані за допомогою ШІ. Готує промпти з вашими даними та передає їх у ChatGPT.',
          zh: '使用 AI 分析财务数据。准备包含您数据的提示并移交给 ChatGPT。',
          ar: 'حلّل البيانات المالية بالذكاء الاصطناعي. يُعدّ المطالبات ببياناتك ويرسلها إلى ChatGPT.',
          pl: 'Analizuj dane finansowe z pomocą AI. Przygotowuje prompty z Twoimi danymi i przekazuje do ChatGPT.',
          it: 'Analizza i dati finanziari con l\'IA. Prepara prompt con i tuoi dati e li invia a ChatGPT.',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
