import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'uploadPage',
  content: {
    title: t({
      ru: 'Загрузка банковских выписок',
      en: 'Upload bank statements',
      kk: 'Банк үзінділерін жүктеу',
      de: 'Kontoauszüge hochladen',
      fr: 'Télécharger des relevés bancaires',
      es: 'Subir extractos bancarios',
      pt: 'Enviar extratos bancários',
      tr: 'Banka hesap özetlerini yükle',
      uk: 'Завантаження банківських виписок',
      zh: '上传银行对账单',
      ar: 'رفع كشوف الحساب البنكية',
      pl: 'Prześlij wyciągi bankowe',
      it: 'Carica estratti conto bancari',
      sk: 'Prześlij wyciągi bankowe',
    }),
    description: t({
      ru: 'После загрузки файлы будут автоматически обработаны: извлечены транзакции, классифицированы и синхронизированы с Google Sheets (если подключен). Результаты обработки можно посмотреть на странице Выписки.',
      en: 'After upload, files will be processed automatically: transactions will be extracted, categorized, and synced to Google Sheets (if connected). You can view results on the Statements page.',
      kk: 'Жүктелгеннен кейін файлдар автоматты түрде өңделеді: транзакциялар алынады, санаттарға бөлінеді және (қосылған болса) Google Sheets-пен синхрондалады. Нәтижелерді Үзінділер бетінде көре аласыз.',
      de: 'Nach dem Hochladen werden Dateien automatisch verarbeitet: Transaktionen werden extrahiert, kategorisiert und mit Google Sheets synchronisiert (wenn verbunden). Die Ergebnisse können auf der Seite Kontoauszüge angesehen werden.',
      fr: 'Après le téléchargement, les fichiers seront traités automatiquement : les transactions seront extraites, catégorisées et synchronisées avec Google Sheets (si connecté). Vous pouvez consulter les résultats sur la page Relevés.',
      es: 'Después de subir, los archivos se procesarán automáticamente: se extraerán las transacciones, se categorizarán y se sincronizarán con Google Sheets (si está conectado). Puedes ver los resultados en la página de Extractos.',
      pt: 'Após o envio, os arquivos serão processados automaticamente: as transações serão extraídas, categorizadas e sincronizadas com o Google Sheets (se conectado). Você pode ver os resultados na página de Extratos.',
      tr: 'Yüklemeden sonra dosyalar otomatik olarak işlenecektir: işlemler çıkarılacak, kategorize edilecek ve Google Sheets ile senkronize edilecektir (bağlıysa). Sonuçları Hesap Özetleri sayfasında görebilirsiniz.',
      uk: 'Після завантаження файли будуть автоматично оброблені: витягнуті транзакції, класифіковані та синхронізовані з Google Sheets (якщо підключено). Результати обробки можна переглянути на сторінці Виписки.',
      zh: '上传后，文件将自动处理：提取交易、分类，并同步到 Google Sheets（如果已连接）。您可以在对账单页面查看结果。',
      ar: 'بعد الرفع، ستتم معالجة الملفات تلقائيًا: استخراج المعاملات وتصنيفها ومزامنتها مع Google Sheets (إذا كان متصلاً). يمكنك عرض النتائج في صفحة كشوف الحساب.',
      pl: 'Po przesłaniu pliki zostaną automatycznie przetworzone: transakcje zostaną wyodrębnione, skategoryzowane i zsynchronizowane z Google Sheets (jeśli jest połączony). Wyniki można zobaczyć na stronie Wyciągi.',
      it: 'Dopo il caricamento, i file verranno elaborati automaticamente: le transazioni verranno estratte, categorizzate e sincronizzate con Google Sheets (se connesso). Puoi visualizzare i risultati nella pagina Estratti conto.',
      sk: 'Po przesłaniu pliki zostaną automatycznie przetworzone: transakcje zostaną wyodrębnione, skategoryzowane i zsynchronizowane z Google Sheets (jeśli jest połączony). Wyniki można zobaczyć na stronie Wyciągi.',
    }),
    success: t({
      ru: 'Файлы успешно загружены! Идёт обработка... Вы будете перенаправлены на страницу выписок.',
      en: 'Files uploaded successfully! Processing is in progress... You will be redirected to the statements page.',
      kk: 'Файлдар сәтті жүктелді! Өңдеу жүріп жатыр... Сіз үзінділер бетіне бағытталасыз.',
      de: 'Dateien erfolgreich hochgeladen! Verarbeitung läuft... Sie werden zur Seite der Kontoauszüge weitergeleitet.',
      fr: 'Fichiers téléchargés avec succès ! Traitement en cours... Vous serez redirigé vers la page des relevés.',
      es: '¡Archivos subidos exitosamente! El procesamiento está en curso... Serás redirigido a la página de extractos.',
      pt: 'Arquivos enviados com sucesso! O processamento está em andamento... Você será redirecionado para a página de extratos.',
      tr: 'Dosyalar başarıyla yüklendi! İşlem devam ediyor... Hesap özetleri sayfasına yönlendirileceksiniz.',
      uk: 'Файли успішно завантажено! Іде обробка... Вас буде перенаправлено на сторінку виписок.',
      zh: '文件上传成功！正在处理中...您将被重定向到对账单页面。',
      ar: 'تم رفع الملفات بنجاح! جارٍ المعالجة... سيتم توجيهك إلى صفحة كشوف الحساب.',
      pl: 'Pliki przesłane pomyślnie! Trwa przetwarzanie... Zostaniesz przekierowany na stronę wyciągów.',
      it: 'File caricati con successo! L\'elaborazione è in corso... Sarai reindirizzato alla pagina degli estratti conto.',
      sk: 'Pliki przesłane pomyślnie! Trwa przetwarzanie... Zostaniesz przekierowany na stronę wyciągów.',
    }),
    oauthLinkMissing: t({
      ru: 'Не удалось получить ссылку для авторизации Google',
      en: 'Failed to get Google authorization link',
      kk: 'Google авторизация сілтемесін алу мүмкін болмады',
      de: 'Google-Autorisierungslink konnte nicht abgerufen werden',
      fr: 'Impossible d\'obtenir le lien d\'autorisation Google',
      es: 'No se pudo obtener el enlace de autorización de Google',
      pt: 'Falha ao obter link de autorização do Google',
      tr: 'Google yetkilendirme bağlantısı alınamadı',
      uk: 'Не вдалося отримати посилання для авторизації Google',
      zh: '无法获取 Google 授权链接',
      ar: 'فشل الحصول على رابط تفويض Google',
      pl: 'Nie udało się uzyskać linku autoryzacji Google',
      it: 'Impossibile ottenere il link di autorizzazione Google',
      sk: 'Nie udało się uzyskać linku autoryzacji Google',
    }),
    oauthStartFailed: t({
      ru: 'Не удалось начать авторизацию Google',
      en: 'Failed to start Google authorization',
      kk: 'Google авторизациясын бастау мүмкін болмады',
      de: 'Google-Autorisierung konnte nicht gestartet werden',
      fr: 'Impossible de démarrer l\'autorisation Google',
      es: 'No se pudo iniciar la autorización de Google',
      pt: 'Falha ao iniciar a autorização do Google',
      tr: 'Google yetkilendirmesi başlatılamadı',
      uk: 'Не вдалося розпочати авторизацію Google',
      zh: '无法启动 Google 授权',
      ar: 'فشل بدء تفويض Google',
      pl: 'Nie udało się uruchomić autoryzacji Google',
      it: 'Impossibile avviare l\'autorizzazione Google',
      sk: 'Nie udało się uruchomić autoryzacji Google',
    }),
    maxTwoFiles: t({
      ru: 'Максимум 2 файла можно загрузить за раз',
      en: 'You can upload up to 2 files at a time',
      kk: 'Бір ретте ең көбі 2 файл жүктеуге болады',
      de: 'Sie können bis zu 2 Dateien gleichzeitig hochladen',
      fr: 'Vous pouvez télécharger jusqu\'à 2 fichiers à la fois',
      es: 'Puedes subir hasta 2 archivos a la vez',
      pt: 'Você pode enviar até 2 arquivos por vez',
      tr: 'Aynı anda en fazla 2 dosya yükleyebilirsiniz',
      uk: 'Максимум 2 файли можна завантажити за раз',
      zh: '您一次最多可以上传 2 个文件',
      ar: 'يمكنك رفع ما يصل إلى ملفين في المرة الواحدة',
      pl: 'Możesz przesłać maksymalnie 2 pliki na raz',
      it: 'Puoi caricare fino a 2 file alla volta',
      sk: 'Możesz przesłać maksymalnie 2 pliki na raz',
    }),
    allowDuplicates: t({
      ru: 'Разрешить загрузку дубликатов',
      en: 'Allow uploading duplicates',
      kk: 'Дубликаттарды жүктеуге рұқсат беру',
      de: 'Hochladen von Duplikaten erlauben',
      fr: 'Autoriser le téléchargement de doublons',
      es: 'Permitir subir duplicados',
      pt: 'Permitir envio de duplicatas',
      tr: 'Tekrar yüklemeye izin ver',
      uk: 'Дозволити завантаження дублікатів',
      zh: '允许上传重复文件',
      ar: 'السماح برفع الملفات المكررة',
      pl: 'Zezwól na przesyłanie duplikatów',
      it: 'Consenti caricamento di duplicati',
      sk: 'Zezwól na przesyłanie duplikatów',
    }),
    uploadFailed: t({
      ru: 'Не удалось загрузить файлы. Попробуйте снова.',
      en: 'Failed to upload files. Please try again.',
      kk: 'Файлдарды жүктеу мүмкін болмады. Қайтадан көріңіз.',
      de: 'Dateien konnten nicht hochgeladen werden. Bitte versuchen Sie es erneut.',
      fr: 'Impossible de télécharger les fichiers. Veuillez réessayer.',
      es: 'No se pudieron subir los archivos. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao enviar arquivos. Por favor, tente novamente.',
      tr: 'Dosyalar yüklenemedi. Lütfen tekrar deneyin.',
      uk: 'Не вдалося завантажити файли. Спробуйте знову.',
      zh: '无法上传文件。请重试。',
      ar: 'فشل رفع الملفات. يرجى المحاولة مرة أخرى.',
      pl: 'Nie udało się przesłać plików. Spróbuj ponownie.',
      it: 'Impossibile caricare i file. Riprova.',
      sk: 'Nie udało się przesłać plików. Spróbuj ponownie.',
    }),
    pickAtLeastOne: t({
      ru: 'Пожалуйста, выберите хотя бы один файл',
      en: 'Please select at least one file',
      kk: 'Кемінде бір файл таңдаңыз',
      de: 'Bitte wählen Sie mindestens eine Datei aus',
      fr: 'Veuillez sélectionner au moins un fichier',
      es: 'Por favor, selecciona al menos un archivo',
      pt: 'Por favor, selecione pelo menos um arquivo',
      tr: 'Lütfen en az bir dosya seçin',
      uk: 'Будь ласка, виберіть принаймні один файл',
      zh: '请至少选择一个文件',
      ar: 'يرجى تحديد ملف واحد على الأقل',
      pl: 'Proszę wybrać co najmniej jeden plik',
      it: 'Seleziona almeno un file',
      sk: 'Proszę wybrać co najmniej jeden plik',
    }),
    googleSheetOptional: t({
      ru: 'Google Таблица (опционально)',
      en: 'Google Sheet (optional)',
      kk: 'Google кестесі (міндетті емес)',
      de: 'Google Tabelle (optional)',
      fr: 'Google Sheet (facultatif)',
      es: 'Google Sheet (opcional)',
      pt: 'Google Sheet (opcional)',
      tr: 'Google Sheet (isteğe bağlı)',
      uk: 'Google Таблиця (необов\'язково)',
      zh: 'Google 表格（可选）',
      ar: 'Google Sheet (اختياري)',
      pl: 'Google Sheet (opcjonalnie)',
      it: 'Google Sheet (opzionale)',
      sk: 'Google Sheet (opcjonalnie)',
    }),
    noSync: t({
      ru: 'Без синхронизации с Google Таблицами',
      en: 'No Google Sheets sync',
      kk: 'Google Sheets синхрондаусыз',
      de: 'Keine Google Sheets-Synchronisierung',
      fr: 'Pas de synchronisation Google Sheets',
      es: 'Sin sincronización con Google Sheets',
      pt: 'Sem sincronização com Google Sheets',
      tr: 'Google Sheets senkronizasyonu yok',
      uk: 'Без синхронізації з Google Таблицями',
      zh: '无 Google Sheets 同步',
      ar: 'بدون مزامنة Google Sheets',
      pl: 'Bez synchronizacji z Google Sheets',
      it: 'Nessuna sincronizzazione con Google Sheets',
      sk: 'Bez synchronizacji z Google Sheets',
    }),
    googleSheetHelp: t({
      ru: 'Выберите Google Таблицу для автоматической синхронизации транзакций. Если не выбрана, данные будут сохранены только в системе.',
      en: 'Select a Google Sheet for automatic transaction sync. If not selected, data will be saved only in the system.',
      kk: 'Транзакцияларды автоматты синхрондау үшін Google кестесін таңдаңыз. Таңдалмаса, деректер тек жүйеде сақталады.',
      de: 'Wählen Sie ein Google Sheet für die automatische Transaktionssynchronisierung. Wenn nicht ausgewählt, werden die Daten nur im System gespeichert.',
      fr: 'Sélectionnez un Google Sheet pour la synchronisation automatique des transactions. Si non sélectionné, les données ne seront sauvegardées que dans le système.',
      es: 'Selecciona un Google Sheet para la sincronización automática de transacciones. Si no se selecciona, los datos se guardarán solo en el sistema.',
      pt: 'Selecione um Google Sheet para sincronização automática de transações. Se não selecionado, os dados serão salvos apenas no sistema.',
      tr: 'Otomatik işlem senkronizasyonu için bir Google Sheet seçin. Seçilmezse, veriler yalnızca sistemde kaydedilecektir.',
      uk: 'Виберіть Google Таблицю для автоматичної синхронізації транзакцій. Якщо не вибрано, дані будуть збережені лише в системі.',
      zh: '选择一个 Google 表格用于自动交易同步。如果未选择，数据将仅保存在系统中。',
      ar: 'اختر Google Sheet للمزامنة التلقائية للمعاملات. إذا لم يتم اختياره، ستُحفظ البيانات فقط في النظام.',
      pl: 'Wybierz Google Sheet do automatycznej synchronizacji transakcji. Jeśli nie zostanie wybrany, dane będą zapisywane tylko w systemie.',
      it: 'Seleziona un Google Sheet per la sincronizzazione automatica delle transazioni. Se non selezionato, i dati verranno salvati solo nel sistema.',
      sk: 'Wybierz Google Sheet do automatycznej synchronizacji transakcji. Jeśli nie zostanie wybrany, dane będą zapisywane tylko w systemie.',
    }),
    noConnectedSheets: t({
      ru: 'Нет подключенных таблиц.',
      en: 'No connected sheets.',
      kk: 'Қосылған кестелер жоқ.',
      de: 'Keine verbundenen Tabellen.',
      fr: 'Aucune feuille connectée.',
      es: 'No hay hojas conectadas.',
      pt: 'Nenhuma planilha conectada.',
      tr: 'Bağlı sayfa yok.',
      uk: 'Немає підключених таблиць.',
      zh: '没有已连接的表格。',
      ar: 'لا توجد جداول متصلة.',
      pl: 'Brak połączonych arkuszy.',
      it: 'Nessun foglio connesso.',
      sk: 'Brak połączonych arkuszy.',
    }),
    oauthOpening: t({
      ru: 'Открытие...',
      en: 'Opening...',
      kk: 'Ашылуда...',
      de: 'Öffnen...',
      fr: 'Ouverture...',
      es: 'Abriendo...',
      pt: 'Abrindo...',
      tr: 'Açılıyor...',
      uk: 'Відкриття...',
      zh: '正在打开...',
      ar: 'جارٍ الفتح...',
      pl: 'Otwieranie...',
      it: 'Apertura...',
      sk: 'Otwieranie...',
    }),
    connectGoogleSheets: t({
      ru: 'Подключить Google Таблицы',
      en: 'Connect Google Sheets',
      kk: 'Google Sheets қосу',
      de: 'Google Sheets verbinden',
      fr: 'Connecter Google Sheets',
      es: 'Conectar Google Sheets',
      pt: 'Conectar Google Sheets',
      tr: 'Google Sheets\'i bağla',
      uk: 'Підключити Google Таблиці',
      zh: '连接 Google Sheets',
      ar: 'ربط Google Sheets',
      pl: 'Połącz Google Sheets',
      it: 'Connetti Google Sheets',
      sk: 'Połącz Google Sheets',
    }),
    dropTitle: t({
      ru: 'Перетащите файлы сюда или нажмите, чтобы выбрать',
      en: 'Drag files here or click to select',
      kk: 'Файлдарды осында сүйреп әкеліңіз немесе таңдау үшін басыңыз',
      de: 'Dateien hierher ziehen oder klicken zum Auswählen',
      fr: 'Faites glisser les fichiers ici ou cliquez pour sélectionner',
      es: 'Arrastra archivos aquí o haz clic para seleccionar',
      pt: 'Arraste arquivos aqui ou clique para selecionar',
      tr: 'Dosyaları buraya sürükleyin veya seçmek için tıklayın',
      uk: 'Перетягніть файли сюди або натисніть, щоб вибрати',
      zh: '将文件拖放到此处或单击以选择',
      ar: 'اسحب الملفات هنا أو انقر للاختيار',
      pl: 'Przeciągnij pliki tutaj lub kliknij, aby wybrać',
      it: 'Trascina i file qui o clicca per selezionare',
      sk: 'Przeciągnij pliki tutaj lub kliknij, aby wybrać',
    }),
    dropSubtitle: t({
      ru: 'Поддерживаемые форматы: PDF, XLSX, XLS, CSV, JPG, PNG (до 2 файлов, каждый до 10 МБ)',
      en: 'Supported formats: PDF, XLSX, XLS, CSV, JPG, PNG (up to 2 files, up to 10 MB each)',
      kk: 'Қолдау көрсетілетін форматтар: PDF, XLSX, XLS, CSV, JPG, PNG (ең көбі 2 файл, әрқайсысы 10 МБ дейін)',
      de: 'Unterstützte Formate: PDF, XLSX, XLS, CSV, JPG, PNG (bis zu 2 Dateien, jeweils bis zu 10 MB)',
      fr: 'Formats pris en charge : PDF, XLSX, XLS, CSV, JPG, PNG (jusqu\'à 2 fichiers, jusqu\'à 10 Mo chacun)',
      es: 'Formatos soportados: PDF, XLSX, XLS, CSV, JPG, PNG (hasta 2 archivos, hasta 10 MB cada uno)',
      pt: 'Formatos suportados: PDF, XLSX, XLS, CSV, JPG, PNG (até 2 arquivos, até 10 MB cada)',
      tr: 'Desteklenen formatlar: PDF, XLSX, XLS, CSV, JPG, PNG (en fazla 2 dosya, her biri en fazla 10 MB)',
      uk: 'Підтримувані формати: PDF, XLSX, XLS, CSV, JPG, PNG (до 2 файлів, кожен до 10 МБ)',
      zh: '支持的格式：PDF、XLSX、XLS、CSV、JPG、PNG（最多 2 个文件，每个最多 10 MB）',
      ar: 'الصيغ المدعومة: PDF, XLSX, XLS, CSV, JPG, PNG (حتى ملفين، حتى 10 ميغابايت لكل منهما)',
      pl: 'Obsługiwane formaty: PDF, XLSX, XLS, CSV, JPG, PNG (do 2 plików, każdy do 10 MB)',
      it: 'Formati supportati: PDF, XLSX, XLS, CSV, JPG, PNG (fino a 2 file, fino a 10 MB ciascuno)',
      sk: 'Obsługiwane formaty: PDF, XLSX, XLS, CSV, JPG, PNG (do 2 plików, każdy do 10 MB)',
    }),
    selectedFiles: t({
      ru: 'Выбранные файлы',
      en: 'Selected files',
      kk: 'Таңдалған файлдар',
      de: 'Ausgewählte Dateien',
      fr: 'Fichiers sélectionnés',
      es: 'Archivos seleccionados',
      pt: 'Arquivos selecionados',
      tr: 'Seçilen dosyalar',
      uk: 'Вибрані файли',
      zh: '已选择的文件',
      ar: 'الملفات المحددة',
      pl: 'Wybrane pliki',
      it: 'File selezionati',
      sk: 'Wybrane pliki',
    }),
    megabytesShort: t({
      ru: 'МБ',
      en: 'MB',
      kk: 'МБ',
      de: 'MB',
      fr: 'Mo',
      es: 'MB',
      pt: 'MB',
      tr: 'MB',
      uk: 'МБ',
      zh: 'MB',
      ar: 'ميغابايت',
      pl: 'MB',
      it: 'MB',
      sk: 'MB',
    }),
    uploadButtonIdle: t({
      ru: 'Загрузить файлы',
      en: 'Upload files',
      kk: 'Файлдарды жүктеу',
      de: 'Dateien hochladen',
      fr: 'Télécharger les fichiers',
      es: 'Subir archivos',
      pt: 'Enviar arquivos',
      tr: 'Dosyaları yükle',
      uk: 'Завантажити файли',
      zh: '上传文件',
      ar: 'رفع الملفات',
      pl: 'Prześlij pliki',
      it: 'Carica file',
      sk: 'Prześlij pliki',
    }),
    uploadButtonLoading: t({
      ru: 'Загрузка...',
      en: 'Uploading...',
      kk: 'Жүктелуде...',
      de: 'Hochladen...',
      fr: 'Téléchargement...',
      es: 'Subiendo...',
      pt: 'Enviando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '上传中...',
      ar: 'جارٍ الرفع...',
      pl: 'Przesyłanie...',
      it: 'Caricamento...',
      sk: 'Przesyłanie...',
    }),
    afterUploadTitle: t({
      ru: 'Что происходит после загрузки?',
      en: 'What happens after upload?',
      kk: 'Жүктегеннен кейін не болады?',
      de: 'Was passiert nach dem Hochladen?',
      fr: 'Que se passe-t-il après le téléchargement ?',
      es: '¿Qué pasa después de subir?',
      pt: 'O que acontece após o envio?',
      tr: 'Yüklemeden sonra ne olur?',
      uk: 'Що відбувається після завантаження?',
      zh: '上传后会发生什么？',
      ar: 'ماذا يحدث بعد الرفع؟',
      pl: 'Co się dzieje po przesłaniu?',
      it: 'Cosa succede dopo il caricamento?',
      sk: 'Co się dzieje po przesłaniu?',
    }),
    afterUploadSteps: {
      step1: t({
        ru: 'Файл сохраняется в системе',
        en: 'The file is saved in the system',
        kk: 'Файл жүйеде сақталады',
        de: 'Die Datei wird im System gespeichert',
        fr: 'Le fichier est sauvegardé dans le système',
        es: 'El archivo se guarda en el sistema',
        pt: 'O arquivo é salvo no sistema',
        tr: 'Dosya sistemde kaydedilir',
        uk: 'Файл зберігається в системі',
        zh: '文件保存在系统中',
        ar: 'يتم حفظ الملف في النظام',
        pl: 'Plik jest zapisywany w systemie',
        it: 'Il file viene salvato nel sistema',
        sk: 'Plik jest zapisywany w systemie',
      }),
      step2: t({
        ru: 'Автоматически определяется банк и формат выписки',
        en: 'The bank and statement format are detected automatically',
        kk: 'Банк және үзінді форматы автоматты түрде анықталады',
        de: 'Bank und Kontoauszugsformat werden automatisch erkannt',
        fr: 'La banque et le format du relevé sont détectés automatiquement',
        es: 'El banco y el formato del extracto se detectan automáticamente',
        pt: 'O banco e o formato do extrato são detectados automaticamente',
        tr: 'Banka ve hesap özeti formatı otomatik olarak algılanır',
        uk: 'Автоматично визначається банк і формат виписки',
        zh: '自动检测银行和对账单格式',
        ar: 'يتم اكتشاف البنك وتنسيق كشف الحساب تلقائيًا',
        pl: 'Bank i format wyciągu są wykrywane automatycznie',
        it: 'La banca e il formato dell\'estratto conto vengono rilevati automaticamente',
        sk: 'Bank i format wyciągu są wykrywane automatycznie',
      }),
      step3: t({
        ru: 'Извлекаются все транзакции',
        en: 'All transactions are extracted',
        kk: 'Барлық транзакциялар алынады',
        de: 'Alle Transaktionen werden extrahiert',
        fr: 'Toutes les transactions sont extraites',
        es: 'Se extraen todas las transacciones',
        pt: 'Todas as transações são extraídas',
        tr: 'Tüm işlemler çıkarılır',
        uk: 'Витягуються всі транзакції',
        zh: '提取所有交易',
        ar: 'يتم استخراج جميع المعاملات',
        pl: 'Wszystkie transakcje są wyodrębniane',
        it: 'Tutte le transazioni vengono estratte',
        sk: 'Wszystkie transakcje są wyodrębniane',
      }),
      step4: t({
        ru: 'Транзакции автоматически классифицируются по категориям',
        en: 'Transactions are categorized automatically',
        kk: 'Транзакциялар автоматты түрде санаттарға бөлінеді',
        de: 'Transaktionen werden automatisch kategorisiert',
        fr: 'Les transactions sont automatiquement catégorisées',
        es: 'Las transacciones se categorizan automáticamente',
        pt: 'As transações são categorizadas automaticamente',
        tr: 'İşlemler otomatik olarak kategorilere ayrılır',
        uk: 'Транзакції автоматично класифікуються по категоріях',
        zh: '交易自动分类',
        ar: 'يتم تصنيف المعاملات تلقائيًا',
        pl: 'Transakcje są automatycznie kategoryzowane',
        it: 'Le transazioni vengono categorizzate automaticamente',
        sk: 'Transakcje są automatycznie kategoryzowane',
      }),
      step5: t({
        ru: 'Если выбран Google Sheet, данные синхронизируются',
        en: 'If a Google Sheet is selected, data is synced',
        kk: 'Егер Google кестесі таңдалса, деректер синхрондалады',
        de: 'Wenn ein Google Sheet ausgewählt ist, werden die Daten synchronisiert',
        fr: 'Si un Google Sheet est sélectionné, les données sont synchronisées',
        es: 'Si se selecciona un Google Sheet, los datos se sincronizan',
        pt: 'Se um Google Sheet for selecionado, os dados são sincronizados',
        tr: 'Bir Google Sheet seçiliyse, veriler senkronize edilir',
        uk: 'Якщо вибрано Google Sheet, дані синхронізуються',
        zh: '如果选择了 Google 表格，数据将同步',
        ar: 'إذا تم اختيار Google Sheet، يتم مزامنة البيانات',
        pl: 'Jeśli wybrano Google Sheet, dane są synchronizowane',
        it: 'Se è selezionato un Google Sheet, i dati vengono sincronizzati',
        sk: 'Jeśli wybrano Google Sheet, dane są synchronizowane',
      }),
      step6: t({
        ru: 'Результаты можно посмотреть на странице Выписки',
        en: 'Results are available on the Statements page',
        kk: 'Нәтижелер Үзінділер бетінде қолжетімді',
        de: 'Ergebnisse sind auf der Seite Kontoauszüge verfügbar',
        fr: 'Les résultats sont disponibles sur la page Relevés',
        es: 'Los resultados están disponibles en la página de Extractos',
        pt: 'Os resultados estão disponíveis na página de Extratos',
        tr: 'Sonuçlar Hesap Özetleri sayfasında mevcuttur',
        uk: 'Результати можна переглянути на сторінці Виписки',
        zh: '结果可在对账单页面查看',
        ar: 'النتائج متاحة في صفحة كشوف الحساب',
        pl: 'Wyniki są dostępne na stronie Wyciągi',
        it: 'I risultati sono disponibili nella pagina Estratti conto',
        sk: 'Wyniki są dostępne na stronie Wyciągi',
      }),
    },
  },
} satisfies Dictionary;

export default content;
