import { makeCloudStorageContent } from '../shared/make-cloud-storage-content';

const content = makeCloudStorageContent({
  key: 'dropboxIntegrationPage',
  name: { ru: 'Dropbox', en: 'Dropbox', kk: 'Dropbox', de: 'Dropbox', fr: 'Dropbox', es: 'Dropbox', pt: 'Dropbox', tr: 'Dropbox', uk: 'Dropbox', zh: 'Dropbox', ar: 'Dropbox', pl: 'Dropbox', it: 'Dropbox', sk: 'Dropbox' },
  folderLabel: {
    ru: 'Папка в Dropbox',
    en: 'Dropbox folder',
    kk: 'Dropbox қалтасы',
    de: 'Dropbox-Ordner',
    fr: 'Dossier Dropbox',
    es: 'Carpeta de Dropbox',
    pt: 'Pasta do Dropbox',
    tr: 'Dropbox klasörü',
    uk: 'Папка в Dropbox',
    zh: 'Dropbox 文件夹',
    ar: 'مجلد Dropbox',
    pl: 'Folder Dropbox',
    it: 'Cartella Dropbox',
    sk: 'Folder Dropbox',
  },
  connectingLabel: {
    ru: 'Открываем авторизацию Dropbox…',
    en: 'Opening Dropbox authorization…',
    kk: 'Dropbox авторизациясы ашылуда…',
    de: 'Dropbox-Autorisierung wird geöffnet…',
    fr: 'Ouverture de l\'autorisation Dropbox…',
    es: 'Abriendo autorización de Dropbox…',
    pt: 'Abrindo autorização do Dropbox…',
    tr: 'Dropbox yetkilendirmesi açılıyor…',
    uk: 'Відкриваємо авторизацію Dropbox…',
    zh: '正在打开 Dropbox 授权…',
    ar: 'جارٍ فتح تفويض Dropbox…',
    pl: 'Otwieranie autoryzacji Dropbox…',
    it: 'Apertura autorizzazione Dropbox…',
    sk: 'Otwieranie autoryzacji Dropbox…',
  },
  connectedLabel: {
    ru: 'Dropbox подключен',
    en: 'Dropbox connected',
    kk: 'Dropbox қосылды',
    de: 'Dropbox verbunden',
    fr: 'Dropbox connecté',
    es: 'Dropbox conectado',
    pt: 'Dropbox conectado',
    tr: 'Dropbox bağlandı',
    uk: 'Dropbox підключено',
    zh: 'Dropbox 已连接',
    ar: 'تم توصيل Dropbox',
    pl: 'Dropbox połączony',
    it: 'Dropbox connesso',
    sk: 'Dropbox połączony',
  },
  pickerUnavailableLabel: {
    ru: 'Dropbox Chooser недоступен',
    en: 'Dropbox Chooser is unavailable',
    kk: 'Dropbox Chooser қолжетімсіз',
    de: 'Dropbox Chooser ist nicht verfügbar',
    fr: 'Dropbox Chooser est indisponible',
    es: 'Dropbox Chooser no está disponible',
    pt: 'Dropbox Chooser não está disponível',
    tr: 'Dropbox Chooser kullanılamıyor',
    uk: 'Dropbox Chooser недоступний',
    zh: 'Dropbox Chooser 不可用',
    ar: 'Dropbox Chooser غير متاح',
    pl: 'Dropbox Chooser jest niedostępny',
    it: 'Dropbox Chooser non disponibile',
    sk: 'Dropbox',
  },
});

export default content;
