import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTableDetailPage',
  content: {
    auth: {
      loading: t({ ru: 'Загрузка...', en: 'Loading...', kk: 'Жүктелуде...', de: 'Laden...', fr: 'Chargement...', es: 'Cargando...', pt: 'Carregando...', tr: 'Yükleniyor...', uk: 'Завантаження...', zh: '加载中...', ar: 'جارٍ التحميل...', pl: 'Ładowanie...', it: 'Caricamento...', sk: 'Ładowanie...'}),
      loginRequired: t({
        ru: 'Войдите в систему, чтобы просматривать таблицу.',
        en: 'Log in to view the table.',
        kk: 'Кестені көру үшін жүйеге кіріңіз.',
        de: 'Melden Sie sich an, um die Tabelle anzuzeigen.',
        fr: 'Connectez-vous pour afficher le tableau.',
        es: 'Inicie sesión para ver la tabla.',
        pt: 'Faça login para visualizar a tabela.',
        tr: 'Tabloyu görüntülemek için giriş yapın.',
        uk: 'Увійдіть, щоб переглядати таблицю.',
        zh: '登录以查看表格。',
        ar: 'قم بتسجيل الدخول لعرض الجدول.',
        pl: 'Zaloguj się, aby przeglądać tabelę.',
        it: 'Accedi per visualizzare la tabella.',
        sk: 'Zaloguj się, aby przeglądać tabelę.',
      }),
    },
    errors: {
      notFound: t({
        ru: 'Таблица не найдена.',
        en: 'Table not found.',
        kk: 'Кесте табылмады.',
        de: 'Tabelle nicht gefunden.',
        fr: 'Tableau introuvable.',
        es: 'Tabla no encontrada.',
        pt: 'Tabela não encontrada.',
        tr: 'Tablo bulunamadı.',
        uk: 'Таблицю не знайдено.',
        zh: '未找到表格。',
        ar: 'الجدول غير موجود.',
        pl: 'Tabela nie znaleziona.',
        it: 'Tabella non trovata.',
        sk: 'Tabela nie znaleziona.',
      }),
    },
    tabs: {
      all: t({ ru: 'Все', en: 'All', kk: 'Барлығы', de: 'Alle', fr: 'Tous', es: 'Todos', pt: 'Todos', tr: 'Tümü', uk: 'Всі', zh: '全部', ar: 'الكل', pl: 'Wszystkie', it: 'Tutti', sk: 'Wszystkie'}),
      paid: t({ ru: 'Оплачено', en: 'Paid', kk: 'Төленді', de: 'Bezahlt', fr: 'Payé', es: 'Pagado', pt: 'Pago', tr: 'Ödendi', uk: 'Оплачено', zh: '已付款', ar: 'مدفوع', pl: 'Zapłacono', it: 'Pagato', sk: 'Zapłacono'}),
      unpaid: t({ ru: 'Не оплачено', en: 'Unpaid', kk: 'Төленбеді', de: 'Nicht bezahlt', fr: 'Non payé', es: 'No pagado', pt: 'Não pago', tr: 'Ödenmedi', uk: 'Не оплачено', zh: '未付款', ar: 'غير مدفوع', pl: 'Niezapłacono', it: 'Non pagato', sk: 'Niezapłacono'}),
    },
    actions: {
      markPaid: t({
        ru: 'Отметить как оплачено',
        en: 'Mark as paid',
        kk: 'Төленді деп белгілеу',
        de: 'Als bezahlt markieren',
        fr: 'Marquer comme payé',
        es: 'Marcar como pagado',
        pt: 'Marcar como pago',
        tr: 'Ödendi olarak işaretle',
        uk: 'Позначити як оплачено',
        zh: '标记为已付款',
        ar: 'وضع علامة مدفوع',
        pl: 'Oznacz jako zapłacone',
        it: 'Segna come pagato',
        sk: 'Oznacz jako zapłacone',
      }),
      markUnpaid: t({
        ru: 'Отметить как не оплачено',
        en: 'Mark as unpaid',
        kk: 'Төленбеді деп белгілеу',
        de: 'Als nicht bezahlt markieren',
        fr: 'Marquer comme non payé',
        es: 'Marcar como no pagado',
        pt: 'Marcar como não pago',
        tr: 'Ödenmedi olarak işaretle',
        uk: 'Позначити як не оплачено',
        zh: '标记为未付款',
        ar: 'وضع علامة غير مدفوع',
        pl: 'Oznacz jako niezapłacone',
        it: 'Segna come non pagato',
        sk: 'Oznacz jako niezapłacone',
      }),
      print: t({ ru: 'Печать', en: 'Print', kk: 'Басып шығару', de: 'Drucken', fr: 'Imprimer', es: 'Imprimir', pt: 'Imprimir', tr: 'Yazdır', uk: 'Друк', zh: '打印', ar: 'طباعة', pl: 'Drukuj', it: 'Stampa', sk: 'Drukuj'}),
      delete: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina', sk: 'Usuń'}),
      markingPaid: t({
        ru: 'Отмечаем...',
        en: 'Marking...',
        kk: 'Белгіленуде...',
        de: 'Markieren...',
        fr: 'Marquage...',
        es: 'Marcando...',
        pt: 'Marcando...',
        tr: 'İşaretleniyor...',
        uk: 'Позначення...',
        zh: '标记中...',
        ar: 'جارٍ الوضع...',
        pl: 'Oznaczanie...',
        it: 'Contrassegno...',
        sk: 'Oznaczanie...',
      }),
      markingUnpaid: t({
        ru: 'Отмечаем...',
        en: 'Marking...',
        kk: 'Белгіленуде...',
        de: 'Markieren...',
        fr: 'Marquage...',
        es: 'Marcando...',
        pt: 'Marcando...',
        tr: 'İşaretleniyor...',
        uk: 'Позначення...',
        zh: '标记中...',
        ar: 'جارٍ الوضع...',
        pl: 'Oznaczanie...',
        it: 'Contrassegno...',
        sk: 'Oznaczanie...',
      }),
      searchPlaceholder: t({
        ru: 'Поиск по счету',
        en: 'Search invoice',
        kk: 'Шотты іздеу',
        de: 'Rechnung suchen',
        fr: 'Rechercher une facture',
        es: 'Buscar factura',
        pt: 'Pesquisar fatura',
        tr: 'Fatura ara',
        uk: 'Пошук рахунку',
        zh: '搜索发票',
        ar: 'البحث في الفاتورة',
        pl: 'Szukaj faktury',
        it: 'Cerca fattura',
        sk: 'Szukaj faktury',
      }),
      columns: t({ ru: 'Колонки', en: 'Columns', kk: 'Бағандар', de: 'Spalten', fr: 'Colonnes', es: 'Columnas', pt: 'Colunas', tr: 'Sütunlar', uk: 'Стовпці', zh: '列', ar: 'الأعمدة', pl: 'Kolumny', it: 'Colonne', sk: 'Kolumny'}),
      columnsReset: t({ ru: 'Сбросить', en: 'Reset', kk: 'Қалпына келтіру', de: 'Zurücksetzen', fr: 'Réinitialiser', es: 'Restablecer', pt: 'Redefinir', tr: 'Sıfırla', uk: 'Скинути', zh: '重置', ar: 'إعادة تعيين', pl: 'Resetuj', it: 'Reimposta', sk: 'Resetuj'}),
      columnsHint: t({
        ru: 'Скрыть / порядок',
        en: 'Hide / order',
        kk: 'Жасыру / рет',
        de: 'Ausblenden / Reihenfolge',
        fr: 'Masquer / ordre',
        es: 'Ocultar / orden',
        pt: 'Ocultar / ordem',
        tr: 'Gizle / sırala',
        uk: 'Приховати / порядок',
        zh: '隐藏 / 排序',
        ar: 'إخفاء / ترتيب',
        pl: 'Ukryj / kolejność',
        it: 'Nascondi / ordine',
        sk: 'Ukryj / kolejność',
      }),
      actionsHeader: t({ ru: 'Действия', en: 'Actions', kk: 'Әрекеттер', de: 'Aktionen', fr: 'Actions', es: 'Acciones', pt: 'Ações', tr: 'Eylemler', uk: 'Дії', zh: '操作', ar: 'الإجراءات', pl: 'Akcje', it: 'Azioni', sk: 'Akcje'}),
    },
    nav: {
      back: t({ ru: 'Назад', en: 'Back', kk: 'Артқа', de: 'Zurück', fr: 'Retour', es: 'Atrás', pt: 'Voltar', tr: 'Geri', uk: 'Назад', zh: '返回', ar: 'رجوع', pl: 'Wstecz', it: 'Indietro', sk: 'Wstecz'}),
      tables: t({ ru: 'Таблицы', en: 'Tables', kk: 'Кестелер', de: 'Tabellen', fr: 'Tableaux', es: 'Tablas', pt: 'Tabelas', tr: 'Tablolar', uk: 'Таблиці', zh: '表格', ar: 'الجداول', pl: 'Tabele', it: 'Tabelle', sk: 'Tabele'}),
    },
    paidColumn: t({ ru: 'Оплачено', en: 'Paid', kk: 'Төленген', de: 'Bezahlt', fr: 'Payé', es: 'Pagado', pt: 'Pago', tr: 'Ödendi', uk: 'Оплачено', zh: '已付款', ar: 'مدفوع', pl: 'Zapłacono', it: 'Pagato', sk: 'Zapłacono'}),
    meta: {
      namePlaceholder: t({
        ru: 'Название таблицы',
        en: 'Table name',
        kk: 'Кесте атауы',
        de: 'Tabellenname',
        fr: 'Nom du tableau',
        es: 'Nombre de la tabla',
        pt: 'Nome da tabela',
        tr: 'Tablo adı',
        uk: 'Назва таблиці',
        zh: '表格名称',
        ar: 'اسم الجدول',
        pl: 'Nazwa tabeli',
        it: 'Nome della tabella',
        sk: 'Nazwa tabeli',
      }),
      descriptionPlaceholder: t({
        ru: 'Описание таблицы',
        en: 'Table description',
        kk: 'Кесте сипаттамасы',
        de: 'Tabellenbeschreibung',
        fr: 'Description du tableau',
        es: 'Descripción de la tabla',
        pt: 'Descrição da tabela',
        tr: 'Tablo açıklaması',
        uk: 'Опис таблиці',
        zh: '表格描述',
        ar: 'وصف الجدول',
        pl: 'Opis tabeli',
        it: 'Descrizione della tabella',
        sk: 'Opis tabeli',
      }),
      save: t({ ru: 'Сохранить', en: 'Save', kk: 'Сақтау', de: 'Speichern', fr: 'Enregistrer', es: 'Guardar', pt: 'Salvar', tr: 'Kaydet', uk: 'Зберегти', zh: '保存', ar: 'حفظ', pl: 'Zapisz', it: 'Salva', sk: 'Zapisz'}),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
      editTooltip: t({
        ru: 'Редактировать название и описание',
        en: 'Edit name and description',
        kk: 'Атау мен сипаттаманы өңдеу',
        de: 'Name und Beschreibung bearbeiten',
        fr: 'Modifier le nom et la description',
        es: 'Editar nombre y descripción',
        pt: 'Editar nome e descrição',
        tr: 'Ad ve açıklamayı düzenle',
        uk: 'Редагувати назву та опис',
        zh: '编辑名称和描述',
        ar: 'تعديل الاسم والوصف',
        pl: 'Edytuj nazwę i opis',
        it: 'Modifica nome e descrizione',
        sk: 'Edytuj nazwę i opis',
      }),
      editMenu: {
        name: t({
          ru: 'Изменить название',
          en: 'Edit name',
          kk: 'Атауын өзгерту',
          de: 'Name bearbeiten',
          fr: 'Modifier le nom',
          es: 'Editar nombre',
          pt: 'Editar nome',
          tr: 'Adı düzenle',
          uk: 'Змінити назву',
          zh: '编辑名称',
          ar: 'تعديل الاسم',
          pl: 'Edytuj nazwę',
          it: 'Modifica nome',
          sk: 'Edytuj nazwę',
        }),
        description: t({
          ru: 'Изменить описание',
          en: 'Edit description',
          kk: 'Сипаттаманы өзгерту',
          de: 'Beschreibung bearbeiten',
          fr: 'Modifier la description',
          es: 'Editar descripción',
          pt: 'Editar descrição',
          tr: 'Açıklamayı düzenle',
          uk: 'Змінити опис',
          zh: '编辑描述',
          ar: 'تعديل الوصف',
          pl: 'Edytuj opis',
          it: 'Modifica descrizione',
          sk: 'Edytuj opis',
        }),
        both: t({
          ru: 'Название и описание',
          en: 'Name and description',
          kk: 'Атау және сипаттама',
          de: 'Name und Beschreibung',
          fr: 'Nom et description',
          es: 'Nombre y descripción',
          pt: 'Nome e descrição',
          tr: 'Ad ve açıklama',
          uk: 'Назва та опис',
          zh: '名称和描述',
          ar: 'الاسم والوصف',
          pl: 'Nazwa i opis',
          it: 'Nome e descrizione',
          sk: 'Nazwa i opis',
        }),
      },
      nameRequired: t({
        ru: 'Введите название таблицы',
        en: 'Enter table name',
        kk: 'Кесте атауын енгізіңіз',
        de: 'Tabellennamen eingeben',
        fr: 'Saisissez le nom du tableau',
        es: 'Ingrese el nombre de la tabla',
        pt: 'Insira o nome da tabela',
        tr: 'Tablo adını girin',
        uk: 'Введіть назву таблиці',
        zh: '请输入表格名称',
        ar: 'أدخل اسم الجدول',
        pl: 'Wprowadź nazwę tabeli',
        it: 'Inserisci il nome della tabella',
        sk: 'Wprowadź nazwę tabeli',
      }),
      saved: t({ ru: 'Сохранено', en: 'Saved', kk: 'Сақталды', de: 'Gespeichert', fr: 'Enregistré', es: 'Guardado', pt: 'Salvo', tr: 'Kaydedildi', uk: 'Збережено', zh: '已保存', ar: 'تم الحفظ', pl: 'Zapisano', it: 'Salvato', sk: 'Zapisano'}),
      saveFailed: t({
        ru: 'Не удалось сохранить изменения',
        en: 'Failed to save changes',
        kk: 'Өзгерістерді сақтау мүмкін болмады',
        de: 'Änderungen konnten nicht gespeichert werden',
        fr: 'Impossible d\'enregistrer les modifications',
        es: 'No se pudieron guardar los cambios',
        pt: 'Falha ao salvar as alterações',
        tr: 'Değişiklikler kaydedilemedi',
        uk: 'Не вдалося зберегти зміни',
        zh: '保存更改失败',
        ar: 'فشل حفظ التغييرات',
        pl: 'Nie udało się zapisać zmian',
        it: 'Impossibile salvare le modifiche',
        sk: 'Nie udało się zapisać zmian',
      }),
    },
    category: {
      none: t({ ru: 'Без категории', en: 'No category', kk: 'Санатсыз', de: 'Keine Kategorie', fr: 'Sans catégorie', es: 'Sin categoría', pt: 'Sem categoria', tr: 'Kategori yok', uk: 'Без категорії', zh: '无类别', ar: 'بدون فئة', pl: 'Bez kategorii', it: 'Nessuna categoria', sk: 'Bez kategorii'}),
      updated: t({
        ru: 'Категория обновлена',
        en: 'Category updated',
        kk: 'Санат жаңартылды',
        de: 'Kategorie aktualisiert',
        fr: 'Catégorie mise à jour',
        es: 'Categoría actualizada',
        pt: 'Categoria atualizada',
        tr: 'Kategori güncellendi',
        uk: 'Категорію оновлено',
        zh: '类别已更新',
        ar: 'تم تحديث الفئة',
        pl: 'Kategoria zaktualizowana',
        it: 'Categoria aggiornata',
        sk: 'Kategoria zaktualizowana',
      }),
      updateFailed: t({
        ru: 'Не удалось обновить категорию',
        en: 'Failed to update category',
        kk: 'Санатты жаңарту мүмкін болмады',
        de: 'Kategorie konnte nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour la catégorie',
        es: 'No se pudo actualizar la categoría',
        pt: 'Falha ao atualizar a categoria',
        tr: 'Kategori güncellenemedi',
        uk: 'Не вдалося оновити категорію',
        zh: '更新类别失败',
        ar: 'فشل تحديث الفئة',
        pl: 'Nie udało się zaktualizować kategorii',
        it: 'Impossibile aggiornare la categoria',
        sk: 'Nie udało się zaktualizować kategorii',
      }),
    },
    columnTypes: {
      text: t({ ru: 'Текст', en: 'Text', kk: 'Мәтін', de: 'Text', fr: 'Texte', es: 'Texto', pt: 'Texto', tr: 'Metin', uk: 'Текст', zh: '文本', ar: 'نص', pl: 'Tekst', it: 'Testo', sk: 'Tekst'}),
      number: t({ ru: 'Число', en: 'Number', kk: 'Сан', de: 'Zahl', fr: 'Nombre', es: 'Número', pt: 'Número', tr: 'Sayı', uk: 'Число', zh: '数字', ar: 'رقم', pl: 'Liczba', it: 'Numero', sk: 'Liczba'}),
      date: t({ ru: 'Дата', en: 'Date', kk: 'Күні', de: 'Datum', fr: 'Date', es: 'Fecha', pt: 'Data', tr: 'Tarih', uk: 'Дата', zh: '日期', ar: 'تاريخ', pl: 'Data', it: 'Data', sk: 'Data'}),
      boolean: t({ ru: 'Да/Нет', en: 'Yes/No', kk: 'Иә/Жоқ', de: 'Ja/Nein', fr: 'Oui/Non', es: 'Sí/No', pt: 'Sim/Não', tr: 'Evet/Hayır', uk: 'Так/Ні', zh: '是/否', ar: 'نعم/لا', pl: 'Tak/Nie', it: 'Sì/No', sk: 'Tak/Nie'}),
      select: t({ ru: 'Выбор', en: 'Select', kk: 'Таңдау', de: 'Auswahl', fr: 'Sélection', es: 'Selección', pt: 'Seleção', tr: 'Seçim', uk: 'Вибір', zh: '选择', ar: 'اختيار', pl: 'Wybór', it: 'Selezione', sk: 'Wybór'}),
      multiSelect: t({
        ru: 'Мультивыбор',
        en: 'Multi-select',
        kk: 'Көп таңдау',
        de: 'Mehrfachauswahl',
        fr: 'Sélection multiple',
        es: 'Selección múltiple',
        pt: 'Seleção múltipla',
        tr: 'Çoklu seçim',
        uk: 'Мультивибір',
        zh: '多选',
        ar: 'اختيار متعدد',
        pl: 'Wielokrotny wybór',
        it: 'Selezione multipla',
        sk: 'Wielokrotny wybór',
      }),
    },
    grid: {
      columnWidthSaveFailed: t({
        ru: 'Не удалось сохранить ширину колонки',
        en: 'Failed to save column width',
        kk: 'Баған ені сақталмады',
        de: 'Spaltenbreite konnte nicht gespeichert werden',
        fr: 'Impossible d\'enregistrer la largeur de la colonne',
        es: 'No se pudo guardar el ancho de la columna',
        pt: 'Falha ao salvar a largura da coluna',
        tr: 'Sütun genişliği kaydedilemedi',
        uk: 'Не вдалося зберегти ширину стовпця',
        zh: '保存列宽失败',
        ar: 'فشل حفظ عرض العمود',
        pl: 'Nie udało się zapisać szerokości kolumny',
        it: 'Impossibile salvare la larghezza della colonna',
        sk: 'Nie udało się zapisać szerokości kolumny',
      }),
      emptyTitle: t({
        ru: 'Пока нет данных',
        en: 'No data yet',
        kk: 'Әзірге дерек жоқ',
        de: 'Noch keine Daten',
        fr: 'Pas encore de données',
        es: 'Aún no hay datos',
        pt: 'Ainda não há dados',
        tr: 'Henüz veri yok',
        uk: 'Поки немає даних',
        zh: '暂无数据',
        ar: 'لا توجد بيانات بعد',
        pl: 'Brak danych',
        it: 'Nessun dato ancora',
        sk: 'Brak danych',
      }),
      emptySubtitle: t({
        ru: 'Начните с добавления строк в таблицу',
        en: 'Start by adding rows to your table',
        kk: 'Кестеге жолдар қосудан бастаңыз',
        de: 'Beginnen Sie mit dem Hinzufügen von Zeilen zu Ihrer Tabelle',
        fr: 'Commencez par ajouter des lignes à votre tableau',
        es: 'Empiece añadiendo filas a su tabla',
        pt: 'Comece adicionando linhas à sua tabela',
        tr: 'Tablonuza satır ekleyerek başlayın',
        uk: 'Почніть з додавання рядків до таблиці',
        zh: '从向表格中添加行开始',
        ar: 'ابدأ بإضافة صفوف إلى جدولك',
        pl: 'Zacznij od dodania wierszy do tabeli',
        it: 'Inizia aggiungendo righe alla tua tabella',
        sk: 'Zacznij od dodania wierszy do tabeli',
      }),
      addRowLabel: t({
        ru: 'Добавить строку',
        en: 'Add row',
        kk: 'Жол қосу',
        de: 'Zeile hinzufügen',
        fr: 'Ajouter une ligne',
        es: 'Agregar fila',
        pt: 'Adicionar linha',
        tr: 'Satır ekle',
        uk: 'Додати рядок',
        zh: '添加行',
        ar: 'إضافة صف',
        pl: 'Dodaj wiersz',
        it: 'Aggiungi riga',
        sk: 'Dodaj wiersz',
      }),
      loadTableFailed: t({
        ru: 'Не удалось загрузить таблицу',
        en: 'Failed to load table',
        kk: 'Кестені жүктеу мүмкін болмады',
        de: 'Tabelle konnte nicht geladen werden',
        fr: 'Impossible de charger le tableau',
        es: 'No se pudo cargar la tabla',
        pt: 'Falha ao carregar a tabela',
        tr: 'Tablo yüklenemedi',
        uk: 'Не вдалося завантажити таблицю',
        zh: '加载表格失败',
        ar: 'فشل تحميل الجدول',
        pl: 'Nie udało się załadować tabeli',
        it: 'Impossibile caricare la tabella',
        sk: 'Nie udało się załadować tabeli',
      }),
      loadRowsFailed: t({
        ru: 'Не удалось загрузить строки',
        en: 'Failed to load rows',
        kk: 'Жолдарды жүктеу мүмкін болмады',
        de: 'Zeilen konnten nicht geladen werden',
        fr: 'Impossible de charger les lignes',
        es: 'No se pudieron cargar las filas',
        pt: 'Falha ao carregar as linhas',
        tr: 'Satırlar yüklenemedi',
        uk: 'Не вдалося завантажити рядки',
        zh: '加载行失败',
        ar: 'فشل تحميل الصفوف',
        pl: 'Nie udało się załadować wierszy',
        it: 'Impossibile caricare le righe',
        sk: 'Nie udało się załadować wierszy',
      }),
      saveValueFailed: t({
        ru: 'Не удалось сохранить значение',
        en: 'Failed to save value',
        kk: 'Мәнді сақтау мүмкін болмады',
        de: 'Wert konnte nicht gespeichert werden',
        fr: 'Impossible d\'enregistrer la valeur',
        es: 'No se pudo guardar el valor',
        pt: 'Falha ao salvar o valor',
        tr: 'Değer kaydedilemedi',
        uk: 'Не вдалося зберегти значення',
        zh: '保存值失败',
        ar: 'فشل حفظ القيمة',
        pl: 'Nie udało się zapisać wartości',
        it: 'Impossibile salvare il valore',
        sk: 'Nie udało się zapisać wartości',
      }),
      loadMore: t({ ru: 'Загрузить ещё', en: 'Load more', kk: 'Тағы жүктеу', de: 'Mehr laden', fr: 'Charger plus', es: 'Cargar más', pt: 'Carregar mais', tr: 'Daha fazla yükle', uk: 'Завантажити ще', zh: '加载更多', ar: 'تحميل المزيد', pl: 'Załaduj więcej', it: 'Carica altro', sk: 'Załaduj więcej'}),
      noMore: t({
        ru: 'Больше нет строк',
        en: 'No more rows',
        kk: 'Жолдар жоқ',
        de: 'Keine weiteren Zeilen',
        fr: 'Plus de lignes',
        es: 'No hay más filas',
        pt: 'Não há mais linhas',
        tr: 'Daha fazla satır yok',
        uk: 'Більше немає рядків',
        zh: '没有更多行',
        ar: 'لا مزيد من الصفوف',
        pl: 'Brak kolejnych wierszy',
        it: 'Non ci sono altre righe',
        sk: 'Brak kolejnych wierszy',
      }),
      loadingMore: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Laden...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
        sk: 'Ładowanie...',
      }),
    },
    paste: {
      titlePrefix: t({ ru: 'Вставка ', en: 'Paste ', kk: 'Қою ', de: 'Einfügen ', fr: 'Coller ', es: 'Pegar ', pt: 'Colar ', tr: 'Yapıştır ', uk: 'Вставка ', zh: '粘贴 ', ar: 'لصق ', pl: 'Wklej ', it: 'Incolla ', sk: 'Wklej '}),
      titleSuffix: t({ ru: ' строк', en: ' rows', kk: ' жол', de: ' Zeilen', fr: ' lignes', es: ' filas', pt: ' linhas', tr: ' satır', uk: ' рядків', zh: ' 行', ar: ' صفوف', pl: ' wierszy', it: ' righe', sk: ' wierszy'}),
      titleFallback: t({
        ru: 'Вставка строк',
        en: 'Paste rows',
        kk: 'Жолдарды қою',
        de: 'Zeilen einfügen',
        fr: 'Coller des lignes',
        es: 'Pegar filas',
        pt: 'Colar linhas',
        tr: 'Satırları yapıştır',
        uk: 'Вставка рядків',
        zh: '粘贴行',
        ar: 'لصق الصفوف',
        pl: 'Wklej wiersze',
        it: 'Incolla righe',
        sk: 'Wklej wiersze',
      }),
      headersToggle: t({
        ru: 'Первая строка — заголовки',
        en: 'First row is headers',
        kk: 'Бірінші жол — тақырыптар',
        de: 'Erste Zeile sind Überschriften',
        fr: 'La première ligne est les en-têtes',
        es: 'La primera fila son encabezados',
        pt: 'A primeira linha são cabeçalhos',
        tr: 'İlk satır başlıklardır',
        uk: 'Перший рядок — заголовки',
        zh: '第一行是标题',
        ar: 'الصف الأول هو الرؤوس',
        pl: 'Pierwszy wiersz to nagłówki',
        it: 'La prima riga sono le intestazioni',
        sk: 'Pierwszy wiersz to nagłówki',
      }),
      parsing: t({
        ru: 'Подготовка превью...',
        en: 'Preparing preview...',
        kk: 'Алдын ала көру дайындалуда...',
        de: 'Vorschau wird vorbereitet...',
        fr: 'Préparation de l\'aperçu...',
        es: 'Preparando vista previa...',
        pt: 'Preparando pré-visualização...',
        tr: 'Önizleme hazırlanıyor...',
        uk: 'Підготовка попереднього перегляду...',
        zh: '正在准备预览...',
        ar: 'جارٍ تحضير المعاينة...',
        pl: 'Przygotowywanie podglądu...',
        it: 'Preparazione anteprima...',
        sk: 'Przygotowywanie podglądu...',
      }),
      add: t({ ru: 'Добавить', en: 'Add', kk: 'Қосу', de: 'Hinzufügen', fr: 'Ajouter', es: 'Agregar', pt: 'Adicionar', tr: 'Ekle', uk: 'Додати', zh: '添加', ar: 'إضافة', pl: 'Dodaj', it: 'Aggiungi', sk: 'Dodaj'}),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
      noRows: t({
        ru: 'Нет строк для вставки',
        en: 'No rows to insert',
        kk: 'Қоюға жол жоқ',
        de: 'Keine Zeilen zum Einfügen',
        fr: 'Aucune ligne à insérer',
        es: 'No hay filas para insertar',
        pt: 'Nenhuma linha para inserir',
        tr: 'Eklenecek satır yok',
        uk: 'Немає рядків для вставки',
        zh: '没有要插入的行',
        ar: 'لا توجد صفوف للإدراج',
        pl: 'Brak wierszy do wstawienia',
        it: 'Nessuna riga da inserire',
        sk: 'Brak wierszy do wstawienia',
      }),
      errorsTitle: t({
        ru: 'Есть ошибки',
        en: 'Errors found',
        kk: 'Қателер бар',
        de: 'Fehler gefunden',
        fr: 'Erreurs trouvées',
        es: 'Se encontraron errores',
        pt: 'Erros encontrados',
        tr: 'Hatalar bulundu',
        uk: 'Є помилки',
        zh: '发现错误',
        ar: 'توجد أخطاء',
        pl: 'Znaleziono błędy',
        it: 'Errori trovati',
        sk: 'Znaleziono błędy',
      }),
      errors: {
        date: t({ ru: 'Дата', en: 'Date', kk: 'Күні', de: 'Datum', fr: 'Date', es: 'Fecha', pt: 'Data', tr: 'Tarih', uk: 'Дата', zh: '日期', ar: 'تاريخ', pl: 'Data', it: 'Data', sk: 'Data'}),
        amount: t({ ru: 'Сумма', en: 'Amount', kk: 'Сома', de: 'Betrag', fr: 'Montant', es: 'Importe', pt: 'Valor', tr: 'Tutar', uk: 'Сума', zh: '金额', ar: 'المبلغ', pl: 'Kwota', it: 'Importo', sk: 'Kwota'}),
        currency: t({ ru: 'Валюта', en: 'Currency', kk: 'Валюта', de: 'Währung', fr: 'Devise', es: 'Moneda', pt: 'Moeda', tr: 'Para birimi', uk: 'Валюта', zh: '货币', ar: 'العملة', pl: 'Waluta', it: 'Valuta', sk: 'Waluta'}),
        paid: t({ ru: 'Paid', en: 'Paid', kk: 'Төленді', de: 'Bezahlt', fr: 'Payé', es: 'Pagado', pt: 'Pago', tr: 'Ödendi', uk: 'Оплачено', zh: '已付款', ar: 'مدفوع', pl: 'Zapłacono', it: 'Pagato', sk: 'Zapłacono'}),
      },
      addedPrefix: t({ ru: 'Добавлено ', en: 'Added ', kk: 'Қосылды ', de: 'Hinzugefügt ', fr: 'Ajouté ', es: 'Agregado ', pt: 'Adicionado ', tr: 'Eklendi ', uk: 'Додано ', zh: '已添加 ', ar: 'تمت الإضافة ', pl: 'Dodano ', it: 'Aggiunto ', sk: 'Dodano '}),
      addedSuffix: t({ ru: ' строк', en: ' rows', kk: ' жол', de: ' Zeilen', fr: ' lignes', es: ' filas', pt: ' linhas', tr: ' satır', uk: ' рядків', zh: ' 行', ar: ' صفوف', pl: ' wierszy', it: ' righe', sk: ' wierszy'}),
      undo: t({ ru: 'Отменить', en: 'Undo', kk: 'Болдырмау', de: 'Rückgängig', fr: 'Annuler', es: 'Deshacer', pt: 'Desfazer', tr: 'Geri al', uk: 'Скасувати', zh: '撤销', ar: 'تراجع', pl: 'Cofnij', it: 'Annulla', sk: 'Cofnij'}),
      insertFailed: t({
        ru: 'Не удалось добавить строки',
        en: 'Failed to add rows',
        kk: 'Жолдарды қосу мүмкін болмады',
        de: 'Zeilen konnten nicht hinzugefügt werden',
        fr: 'Impossible d\'ajouter des lignes',
        es: 'No se pudieron agregar filas',
        pt: 'Falha ao adicionar linhas',
        tr: 'Satırlar eklenemedi',
        uk: 'Не вдалося додати рядки',
        zh: '添加行失败',
        ar: 'فشل إضافة الصفوف',
        pl: 'Nie udało się dodać wierszy',
        it: 'Impossibile aggiungere righe',
        sk: 'Nie udało się dodać wierszy',
      }),
      undoFailed: t({
        ru: 'Не удалось отменить вставку',
        en: 'Failed to undo insert',
        kk: 'Қоюды болдырмау мүмкін болмады',
        de: 'Einfügen konnte nicht rückgängig gemacht werden',
        fr: 'Impossible d\'annuler l\'insertion',
        es: 'No se pudo deshacer la inserción',
        pt: 'Falha ao desfazer a inserção',
        tr: 'Ekleme geri alınamadı',
        uk: 'Не вдалося скасувати вставку',
        zh: '撤销插入失败',
        ar: 'فشل التراجع عن الإدراج',
        pl: 'Nie udało się cofnąć wstawiania',
        it: 'Impossibile annullare l\'inserimento',
        sk: 'Nie udało się cofnąć wstawiania',
      }),
      moreRowsPrefix: t({ ru: 'И ещё ', en: 'And ', kk: 'Тағы ', de: 'Und ', fr: 'Et ', es: 'Y ', pt: 'E ', tr: 'Ve ', uk: 'І ще ', zh: '还有 ', ar: 'و ', pl: 'I jeszcze ', it: 'E altri ', sk: 'I jeszcze '}),
      moreRowsSuffix: t({
        ru: ' строк',
        en: ' more rows',
        kk: ' жол',
        de: ' weitere Zeilen',
        fr: ' lignes de plus',
        es: ' filas más',
        pt: ' mais linhas',
        tr: ' satır daha',
        uk: ' рядків',
        zh: ' 行',
        ar: ' صفوف إضافية',
        pl: ' wierszy',
        it: ' righe in più',
        sk: ' wierszy',
      }),
      mappingTitle: t({
        ru: 'Сопоставление колонок',
        en: 'Column mapping',
        kk: 'Бағандарды сәйкестендіру',
        de: 'Spaltenzuordnung',
        fr: 'Correspondance des colonnes',
        es: 'Mapeo de columnas',
        pt: 'Mapeamento de colunas',
        tr: 'Sütun eşleştirmesi',
        uk: 'Зіставлення стовпців',
        zh: '列映射',
        ar: 'تعيين الأعمدة',
        pl: 'Mapowanie kolumn',
        it: 'Mappatura colonne',
        sk: 'Mapowanie kolumn',
      }),
      mappingIgnore: t({
        ru: 'Не импортировать',
        en: 'Ignore',
        kk: 'Импорттамау',
        de: 'Ignorieren',
        fr: 'Ignorer',
        es: 'Ignorar',
        pt: 'Ignorar',
        tr: 'Yoksay',
        uk: 'Не імпортувати',
        zh: '忽略',
        ar: 'تجاهل',
        pl: 'Ignoruj',
        it: 'Ignora',
        sk: 'Ignoruj',
      }),
      mappingNew: t({
        ru: 'Новая колонка',
        en: 'New column',
        kk: 'Жаңа баған',
        de: 'Neue Spalte',
        fr: 'Nouvelle colonne',
        es: 'Nueva columna',
        pt: 'Nova coluna',
        tr: 'Yeni sütun',
        uk: 'Новий стовпець',
        zh: '新列',
        ar: 'عمود جديد',
        pl: 'Nowa kolumna',
        it: 'Nuova colonna',
        sk: 'Nowa kolumna',
      }),
      mappingNewPlaceholder: t({
        ru: 'Название колонки',
        en: 'Column name',
        kk: 'Баған атауы',
        de: 'Spaltenname',
        fr: 'Nom de la colonne',
        es: 'Nombre de la columna',
        pt: 'Nome da coluna',
        tr: 'Sütun adı',
        uk: 'Назва стовпця',
        zh: '列名称',
        ar: 'اسم العمود',
        pl: 'Nazwa kolumny',
        it: 'Nome colonna',
        sk: 'Nazwa kolumny',
      }),
      missingColumnTitle: t({
        ru: 'Укажите название новой колонки',
        en: 'Provide a name for the new column',
        kk: 'Жаңа баған атауын енгізіңіз',
        de: 'Namen für die neue Spalte angeben',
        fr: 'Fournissez un nom pour la nouvelle colonne',
        es: 'Proporcione un nombre para la nueva columna',
        pt: 'Forneça um nome para a nova coluna',
        tr: 'Yeni sütun için bir ad girin',
        uk: 'Вкажіть назву нового стовпця',
        zh: '请为新列提供名称',
        ar: 'أدخل اسماً للعمود الجديد',
        pl: 'Podaj nazwę dla nowej kolumny',
        it: 'Fornisci un nome per la nuova colonna',
        sk: 'Podaj nazwę dla nowej kolumny',
      }),
      mappingTypeLabel: t({
        ru: 'Тип',
        en: 'Type',
        kk: 'Түрі',
        de: 'Typ',
        fr: 'Type',
        es: 'Tipo',
        pt: 'Tipo',
        tr: 'Tür',
        uk: 'Тип',
        zh: '类型',
        ar: 'النوع',
        pl: 'Typ',
        it: 'Tipo',
        sk: 'Typ',
      }),
      defaults: {
        date: t({ ru: 'Дата', en: 'Date', kk: 'Күні', de: 'Datum', fr: 'Date', es: 'Fecha', pt: 'Data', tr: 'Tarih', uk: 'Дата', zh: '日期', ar: 'تاريخ', pl: 'Data', it: 'Data', sk: 'Data'}),
        type: t({ ru: 'Тип', en: 'Type', kk: 'Түрі', de: 'Typ', fr: 'Type', es: 'Tipo', pt: 'Tipo', tr: 'Tür', uk: 'Тип', zh: '类型', ar: 'النوع', pl: 'Typ', it: 'Tipo', sk: 'Typ'}),
        amount: t({ ru: 'Сумма', en: 'Amount', kk: 'Сома', de: 'Betrag', fr: 'Montant', es: 'Importe', pt: 'Valor', tr: 'Tutar', uk: 'Сума', zh: '金额', ar: 'المبلغ', pl: 'Kwota', it: 'Importo', sk: 'Kwota'}),
        currency: t({ ru: 'Валюта', en: 'Currency', kk: 'Валюта', de: 'Währung', fr: 'Devise', es: 'Moneda', pt: 'Moeda', tr: 'Para birimi', uk: 'Валюта', zh: '货币', ar: 'العملة', pl: 'Waluta', it: 'Valuta', sk: 'Waluta'}),
        comment: t({
          ru: 'Комментарий',
          en: 'Comment',
          kk: 'Түсініктеме',
          de: 'Kommentar',
          fr: 'Commentaire',
          es: 'Comentario',
          pt: 'Comentário',
          tr: 'Yorum',
          uk: 'Коментар',
          zh: '备注',
          ar: 'تعليق',
          pl: 'Komentarz',
          it: 'Commento',
          sk: 'Komentarz',
        }),
        paid: t({ ru: 'Оплачено', en: 'Paid', kk: 'Төленді', de: 'Bezahlt', fr: 'Payé', es: 'Pagado', pt: 'Pago', tr: 'Ödendi', uk: 'Оплачено', zh: '已付款', ar: 'مدفوع', pl: 'Zapłacono', it: 'Pagato', sk: 'Zapłacono'}),
        columnPrefix: t({
          ru: 'Колонка',
          en: 'Column',
          kk: 'Баған',
          de: 'Spalte',
          fr: 'Colonne',
          es: 'Columna',
          pt: 'Coluna',
          tr: 'Sütun',
          uk: 'Стовпець',
          zh: '列',
          ar: 'عمود',
          pl: 'Kolumna',
          it: 'Colonna',
          sk: 'Kolumna',
        }),
      },
    },
    toasts: {
      noMoreRows: t({
        ru: 'Больше нет строк',
        en: 'No more rows',
        kk: 'Жолдар жоқ',
        de: 'Keine weiteren Zeilen',
        fr: 'Plus de lignes',
        es: 'No hay más filas',
        pt: 'Não há mais linhas',
        tr: 'Daha fazla satır yok',
        uk: 'Більше немає рядків',
        zh: '没有更多行',
        ar: 'لا مزيد من الصفوف',
        pl: 'Brak kolejnych wierszy',
        it: 'Non ci sono altre righe',
        sk: 'Brak kolejnych wierszy',
      }),
      creatingPaidColumn: t({
        ru: 'Создание колонки оплаты...',
        en: 'Creating Paid column...',
        kk: 'Төлем бағаны жасалуда...',
        de: 'Zahlungsspalte wird erstellt...',
        fr: 'Création de la colonne de paiement...',
        es: 'Creando columna de pago...',
        pt: 'Criando coluna de pagamento...',
        tr: 'Ödeme sütunu oluşturuluyor...',
        uk: 'Створення стовпця оплати...',
        zh: '正在创建付款列...',
        ar: 'جارٍ إنشاء عمود الدفع...',
        pl: 'Tworzenie kolumny płatności...',
        it: 'Creazione colonna pagamento...',
        sk: 'Tworzenie kolumny płatności...',
      }),
      paidColumnCreated: t({
        ru: 'Колонка оплаты создана',
        en: 'Paid column created',
        kk: 'Төлем бағаны жасалды',
        de: 'Zahlungsspalte erstellt',
        fr: 'Colonne de paiement créée',
        es: 'Columna de pago creada',
        pt: 'Coluna de pagamento criada',
        tr: 'Ödeme sütunu oluşturuldu',
        uk: 'Стовпець оплати створено',
        zh: '付款列已创建',
        ar: 'تم إنشاء عمود الدفع',
        pl: 'Kolumna płatności utworzona',
        it: 'Colonna pagamento creata',
        sk: 'Kolumna płatności utworzona',
      }),
      paidColumnCreateFailed: t({
        ru: 'Не удалось создать колонку оплаты',
        en: 'Failed to create Paid column',
        kk: 'Төлем бағанын жасау мүмкін болмады',
        de: 'Zahlungsspalte konnte nicht erstellt werden',
        fr: 'Impossible de créer la colonne de paiement',
        es: 'No se pudo crear la columna de pago',
        pt: 'Falha ao criar coluna de pagamento',
        tr: 'Ödeme sütunu oluşturulamadı',
        uk: 'Не вдалося створити стовпець оплати',
        zh: '创建付款列失败',
        ar: 'فشل إنشاء عمود الدفع',
        pl: 'Nie udało się utworzyć kolumny płatności',
        it: 'Impossibile creare la colonna pagamento',
        sk: 'Nie udało się utworzyć kolumny płatności',
      }),
      updateSomeRowsFailed: t({
        ru: 'Не удалось обновить некоторые строки',
        en: 'Failed to update some rows',
        kk: 'Кейбір жолдарды жаңарту мүмкін болмады',
        de: 'Einige Zeilen konnten nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour certaines lignes',
        es: 'No se pudieron actualizar algunas filas',
        pt: 'Falha ao atualizar algumas linhas',
        tr: 'Bazı satırlar güncellenemedi',
        uk: 'Не вдалося оновити деякі рядки',
        zh: '更新部分行失败',
        ar: 'فشل تحديث بعض الصفوف',
        pl: 'Nie udało się zaktualizować niektórych wierszy',
        it: 'Impossibile aggiornare alcune righe',
        sk: 'Nie udało się zaktualizować niektórych wierszy',
      }),
      markedPaid: t({
        ru: 'Отмечено как оплачено',
        en: 'Marked as paid',
        kk: 'Төленді деп белгіленді',
        de: 'Als bezahlt markiert',
        fr: 'Marqué comme payé',
        es: 'Marcado como pagado',
        pt: 'Marcado como pago',
        tr: 'Ödendi olarak işaretlendi',
        uk: 'Позначено як оплачено',
        zh: '已标记为已付款',
        ar: 'تم وضع علامة مدفوع',
        pl: 'Oznaczono jako zapłacone',
        it: 'Contrassegnato come pagato',
        sk: 'Oznaczono jako zapłacone',
      }),
      markedUnpaid: t({
        ru: 'Отмечено как не оплачено',
        en: 'Marked as unpaid',
        kk: 'Төленбеді деп белгіленді',
        de: 'Als nicht bezahlt markiert',
        fr: 'Marqué comme non payé',
        es: 'Marcado como no pagado',
        pt: 'Marcado como não pago',
        tr: 'Ödenmedi olarak işaretlendi',
        uk: 'Позначено як не оплачено',
        zh: '已标记为未付款',
        ar: 'تم وضع علامة غير مدفوع',
        pl: 'Oznaczono jako niezapłacone',
        it: 'Contrassegnato come non pagato',
        sk: 'Oznaczono jako niezapłacone',
      }),
      updateRowsFailed: t({
        ru: 'Не удалось обновить строки',
        en: 'Failed to update rows',
        kk: 'Жолдарды жаңарту мүмкін болмады',
        de: 'Zeilen konnten nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour les lignes',
        es: 'No se pudieron actualizar las filas',
        pt: 'Falha ao atualizar as linhas',
        tr: 'Satırlar güncellenemedi',
        uk: 'Не вдалося оновити рядки',
        zh: '更新行失败',
        ar: 'فشل تحديث الصفوف',
        pl: 'Nie udało się zaktualizować wierszy',
        it: 'Impossibile aggiornare le righe',
        sk: 'Nie udało się zaktualizować wierszy',
      }),
    },
    zoom: {
      out: t({ ru: 'Уменьшить масштаб', en: 'Zoom out', kk: 'Кішірейту', de: 'Verkleinern', fr: 'Dézoomer', es: 'Alejar', pt: 'Diminuir zoom', tr: 'Uzaklaştır', uk: 'Зменшити масштаб', zh: '缩小', ar: 'تصغير', pl: 'Oddalenie', it: 'Riduci zoom', sk: 'Oddalenie'}),
      in: t({ ru: 'Увеличить масштаб', en: 'Zoom in', kk: 'Үлкейту', de: 'Vergrößern', fr: 'Zoomer', es: 'Acercar', pt: 'Aumentar zoom', tr: 'Yaklaştır', uk: 'Збільшити масштаб', zh: '放大', ar: 'تكبير', pl: 'Przybliżenie', it: 'Aumenta zoom', sk: 'Przybliżenie'}),
    },
    fill: {
      column: t({ ru: 'Колонка', en: 'Column', kk: 'Баған', de: 'Spalte', fr: 'Colonne', es: 'Columna', pt: 'Coluna', tr: 'Sütun', uk: 'Стовпець', zh: '列', ar: 'عمود', pl: 'Kolumna', it: 'Colonna', sk: 'Kolumna'}),
      row: t({ ru: 'Строка', en: 'Row', kk: 'Жол', de: 'Zeile', fr: 'Ligne', es: 'Fila', pt: 'Linha', tr: 'Satır', uk: 'Рядок', zh: '行', ar: 'صف', pl: 'Wiersz', it: 'Riga', sk: 'Wiersz'}),
      selectedRowsPrefix: t({
        ru: 'Выбрано строк',
        en: 'Selected rows',
        kk: 'Таңдалған жолдар',
        de: 'Ausgewählte Zeilen',
        fr: 'Lignes sélectionnées',
        es: 'Filas seleccionadas',
        pt: 'Linhas selecionadas',
        tr: 'Seçili satırlar',
        uk: 'Вибрані рядки',
        zh: '已选行',
        ar: 'الصفوف المحددة',
        pl: 'Wybrane wiersze',
        it: 'Righe selezionate',
        sk: 'Wybrane wiersze',
      }),
      rowsFillTitle: t({
        ru: 'Заливка строк',
        en: 'Row fill',
        kk: 'Жолды бояу',
        de: 'Zeilenfüllung',
        fr: 'Remplissage des lignes',
        es: 'Relleno de filas',
        pt: 'Preenchimento de linhas',
        tr: 'Satır doldurma',
        uk: 'Заливка рядків',
        zh: '行填充',
        ar: 'تعبئة الصفوف',
        pl: 'Wypełnienie wierszy',
        it: 'Riempimento righe',
        sk: 'Wypełnienie wierszy',
      }),
      colorTooltip: t({
        ru: 'Цвет заливки',
        en: 'Fill color',
        kk: 'Бояу түсі',
        de: 'Füllfarbe',
        fr: 'Couleur de remplissage',
        es: 'Color de relleno',
        pt: 'Cor de preenchimento',
        tr: 'Dolgu rengi',
        uk: 'Колір заливки',
        zh: '填充颜色',
        ar: 'لون التعبئة',
        pl: 'Kolor wypełnienia',
        it: 'Colore di riempimento',
        sk: 'Kolor wypełnienia',
      }),
      fillButton: t({ ru: 'Заливка', en: 'Fill', kk: 'Бояу', de: 'Füllen', fr: 'Remplir', es: 'Rellenar', pt: 'Preencher', tr: 'Doldur', uk: 'Заливка', zh: '填充', ar: 'تعبئة', pl: 'Wypełnij', it: 'Riempi', sk: 'Wypełnij'}),
      clear: t({ ru: 'Очистить', en: 'Clear', kk: 'Тазалау', de: 'Löschen', fr: 'Effacer', es: 'Limpiar', pt: 'Limpar', tr: 'Temizle', uk: 'Очистити', zh: '清除', ar: 'مسح', pl: 'Wyczyść', it: 'Cancella', sk: 'Wyczyść'}),
      chooseRowsError: t({
        ru: 'Выберите строки, к которым нужно применить заливку',
        en: 'Select rows to apply fill',
        kk: 'Бояуды қолдану үшін жолдарды таңдаңыз',
        de: 'Wählen Sie die Zeilen aus, auf die die Füllung angewendet werden soll',
        fr: 'Sélectionnez les lignes auxquelles appliquer le remplissage',
        es: 'Seleccione las filas a las que aplicar el relleno',
        pt: 'Selecione as linhas para aplicar o preenchimento',
        tr: 'Dolgu uygulamak için satırları seçin',
        uk: 'Виберіть рядки, до яких потрібно застосувати заливку',
        zh: '选择要应用填充的行',
        ar: 'حدد الصفوف لتطبيق التعبئة',
        pl: 'Wybierz wiersze, do których chcesz zastosować wypełnienie',
        it: 'Seleziona le righe a cui applicare il riempimento',
        sk: 'Wybierz wiersze, do których chcesz zastosować wypełnienie',
      }),
      applied: t({
        ru: 'Заливка применена',
        en: 'Fill applied',
        kk: 'Бояу қолданылды',
        de: 'Füllung angewendet',
        fr: 'Remplissage appliqué',
        es: 'Relleno aplicado',
        pt: 'Preenchimento aplicado',
        tr: 'Dolgu uygulandı',
        uk: 'Заливку застосовано',
        zh: '填充已应用',
        ar: 'تم تطبيق التعبئة',
        pl: 'Wypełnienie zastosowane',
        it: 'Riempimento applicato',
        sk: 'Wypełnienie zastosowane',
      }),
      clearedToast: t({
        ru: 'Заливка сброшена',
        en: 'Fill cleared',
        kk: 'Бояу тазаланды',
        de: 'Füllung geleert',
        fr: 'Remplissage effacé',
        es: 'Relleno eliminado',
        pt: 'Preenchimento removido',
        tr: 'Dolgu temizlendi',
        uk: 'Заливку скинуто',
        zh: '填充已清除',
        ar: 'تم مسح التعبئة',
        pl: 'Wypełnienie wyczyszczone',
        it: 'Riempimento rimosso',
        sk: 'Wypełnienie wyczyszczone',
      }),
      applyFailed: t({
        ru: 'Не удалось применить заливку',
        en: 'Failed to apply fill',
        kk: 'Бояуды қолдану мүмкін болмады',
        de: 'Füllung konnte nicht angewendet werden',
        fr: 'Impossible d\'appliquer le remplissage',
        es: 'No se pudo aplicar el relleno',
        pt: 'Falha ao aplicar o preenchimento',
        tr: 'Dolgu uygulanamadı',
        uk: 'Не вдалося застосувати заливку',
        zh: '应用填充失败',
        ar: 'فشل تطبيق التعبئة',
        pl: 'Nie udało się zastosować wypełnienia',
        it: 'Impossibile applicare il riempimento',
        sk: 'Nie udało się zastosować wypełnienia',
      }),
    },
    addRow: {
      loading: t({
        ru: 'Добавление строки...',
        en: 'Adding row...',
        kk: 'Жол қосылуда...',
        de: 'Zeile wird hinzugefügt...',
        fr: 'Ajout d\'une ligne...',
        es: 'Agregando fila...',
        pt: 'Adicionando linha...',
        tr: 'Satır ekleniyor...',
        uk: 'Додавання рядка...',
        zh: '正在添加行...',
        ar: 'جارٍ إضافة صف...',
        pl: 'Dodawanie wiersza...',
        it: 'Aggiunta riga...',
        sk: 'Dodawanie wiersza...',
      }),
      success: t({
        ru: 'Строка добавлена',
        en: 'Row added',
        kk: 'Жол қосылды',
        de: 'Zeile hinzugefügt',
        fr: 'Ligne ajoutée',
        es: 'Fila agregada',
        pt: 'Linha adicionada',
        tr: 'Satır eklendi',
        uk: 'Рядок додано',
        zh: '行已添加',
        ar: 'تمت إضافة الصف',
        pl: 'Wiersz dodany',
        it: 'Riga aggiunta',
        sk: 'Wiersz dodany',
      }),
      failed: t({
        ru: 'Не удалось добавить строку',
        en: 'Failed to add row',
        kk: 'Жол қосу мүмкін болмады',
        de: 'Zeile konnte nicht hinzugefügt werden',
        fr: 'Impossible d\'ajouter une ligne',
        es: 'No se pudo agregar la fila',
        pt: 'Falha ao adicionar linha',
        tr: 'Satır eklenemedi',
        uk: 'Не вдалося додати рядок',
        zh: '添加行失败',
        ar: 'فشل إضافة الصف',
        pl: 'Nie udało się dodać wiersza',
        it: 'Impossibile aggiungere la riga',
        sk: 'Nie udało się dodać wiersza',
      }),
    },
    renameColumn: {
      success: t({
        ru: 'Название колонки обновлено',
        en: 'Column renamed',
        kk: 'Баған атауы жаңартылды',
        de: 'Spalte umbenannt',
        fr: 'Colonne renommée',
        es: 'Columna renombrada',
        pt: 'Coluna renomeada',
        tr: 'Sütun yeniden adlandırıldı',
        uk: 'Назву стовпця оновлено',
        zh: '列已重命名',
        ar: 'تمت إعادة تسمية العمود',
        pl: 'Kolumna przemianowana',
        it: 'Colonna rinominata',
        sk: 'Kolumna przemianowana',
      }),
      failed: t({
        ru: 'Не удалось переименовать колонку',
        en: 'Failed to rename column',
        kk: 'Баған атын өзгерту мүмкін болмады',
        de: 'Spalte konnte nicht umbenannt werden',
        fr: 'Impossible de renommer la colonne',
        es: 'No se pudo renombrar la columna',
        pt: 'Falha ao renomear a coluna',
        tr: 'Sütun yeniden adlandırılamadı',
        uk: 'Не вдалося перейменувати стовпець',
        zh: '重命名列失败',
        ar: 'فشل إعادة تسمية العمود',
        pl: 'Nie udało się przemianować kolumny',
        it: 'Impossibile rinominare la colonna',
        sk: 'Nie udało się przemianować kolumny',
      }),
    },
    deleteColumn: {
      loading: t({
        ru: 'Удаление колонки...',
        en: 'Deleting column...',
        kk: 'Баған жойылуда...',
        de: 'Spalte wird gelöscht...',
        fr: 'Suppression de la colonne...',
        es: 'Eliminando columna...',
        pt: 'Excluindo coluna...',
        tr: 'Sütun siliniyor...',
        uk: 'Видалення стовпця...',
        zh: '正在删除列...',
        ar: 'جارٍ حذف العمود...',
        pl: 'Usuwanie kolumny...',
        it: 'Eliminazione colonna...',
        sk: 'Usuwanie kolumny...',
      }),
      success: t({
        ru: 'Колонка удалена',
        en: 'Column deleted',
        kk: 'Баған жойылды',
        de: 'Spalte gelöscht',
        fr: 'Colonne supprimée',
        es: 'Columna eliminada',
        pt: 'Coluna excluída',
        tr: 'Sütun silindi',
        uk: 'Стовпець видалено',
        zh: '列已删除',
        ar: 'تم حذف العمود',
        pl: 'Kolumna usunięta',
        it: 'Colonna eliminata',
        sk: 'Kolumna usunięta',
      }),
      failed: t({
        ru: 'Не удалось удалить колонку',
        en: 'Failed to delete column',
        kk: 'Бағанды жою мүмкін болмады',
        de: 'Spalte konnte nicht gelöscht werden',
        fr: 'Impossible de supprimer la colonne',
        es: 'No se pudo eliminar la columna',
        pt: 'Falha ao excluir a coluna',
        tr: 'Sütun silinemedi',
        uk: 'Не вдалося видалити стовпець',
        zh: '删除列失败',
        ar: 'فشل حذف العمود',
        pl: 'Nie udało się usunąć kolumny',
        it: 'Impossibile eliminare la colonna',
        sk: 'Nie udało się usunąć kolumny',
      }),
      confirmTitle: t({
        ru: 'Удалить колонку?',
        en: 'Delete column?',
        kk: 'Бағанды жою керек пе?',
        de: 'Spalte löschen?',
        fr: 'Supprimer la colonne ?',
        es: '¿Eliminar columna?',
        pt: 'Excluir coluna?',
        tr: 'Sütun silinsin mi?',
        uk: 'Видалити стовпець?',
        zh: '删除列？',
        ar: 'حذف العمود؟',
        pl: 'Usunąć kolumnę?',
        it: 'Eliminare la colonna?',
        sk: 'Usunąć kolumnę?',
      }),
      confirmWithNamePrefix: t({
        ru: 'Колонка "',
        en: 'Column "',
        kk: 'Баған "',
        de: 'Spalte "',
        fr: 'La colonne "',
        es: 'La columna "',
        pt: 'A coluna "',
        tr: '"',
        uk: 'Стовпець "',
        zh: '列"',
        ar: 'العمود "',
        pl: 'Kolumna "',
        it: 'La colonna "',
        sk: 'Kolumna "',
      }),
      confirmWithNameSuffix: t({
        ru: '" будет удалена. Значения в строках останутся в данных, но не будут отображаться (пока не добавите колонку снова).',
        en: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        kk: '" жойылады. Мәндер деректе қалады, бірақ көрсетілмейді (бағанды қайта қоспайынша).',
        de: '" wird gelöscht. Werte bleiben in den Daten, werden aber nicht angezeigt (bis Sie die Spalte erneut hinzufügen).',
        fr: '" sera supprimée. Les valeurs resteront dans les données mais ne seront pas affichées (jusqu\'à ce que vous ajoutiez à nouveau la colonne).',
        es: '" será eliminada. Los valores permanecerán en los datos pero no se mostrarán (hasta que agregue la columna nuevamente).',
        pt: '" será excluída. Os valores permanecerão nos dados mas não serão exibidos (até você adicionar a coluna novamente).',
        tr: '" silinecek. Değerler verilerde kalacak ancak görüntülenmeyecek (sütunu tekrar ekleyene kadar).',
        uk: '" буде видалено. Значення залишаться у даних, але не відображатимуться (поки не додасте стовпець знову).',
        zh: '"将被删除。值将保留在数据中但不会显示（直到您再次添加该列）。',
        ar: '" سيُحذف. ستبقى القيم في البيانات لكن لن تُعرض (حتى تضيف العمود مرة أخرى).',
        pl: '" zostanie usunięta. Wartości pozostaną w danych, ale nie będą wyświetlane (dopóki nie dodasz kolumny ponownie).',
        it: '" verrà eliminata. I valori rimarranno nei dati ma non verranno mostrati (finché non aggiungi di nuovo la colonna).',
        sk: '" zostanie usunięta. Wartości pozostaną w danych, ale nie będą wyświetlane (dopóki nie dodasz kolumny ponownie).',
      }),
      confirmNoName: t({
        ru: 'Колонка будет удалена.',
        en: 'Column will be deleted.',
        kk: 'Баған жойылады.',
        de: 'Die Spalte wird gelöscht.',
        fr: 'La colonne sera supprimée.',
        es: 'La columna será eliminada.',
        pt: 'A coluna será excluída.',
        tr: 'Sütun silinecek.',
        uk: 'Стовпець буде видалено.',
        zh: '列将被删除。',
        ar: 'سيُحذف العمود.',
        pl: 'Kolumna zostanie usunięta.',
        it: 'La colonna verrà eliminata.',
        sk: 'Kolumna zostanie usunięta.',
      }),
      confirm: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina', sk: 'Usuń'}),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
    },
    deleteRow: {
      loading: t({
        ru: 'Удаление строки...',
        en: 'Deleting row...',
        kk: 'Жол жойылуда...',
        de: 'Zeile wird gelöscht...',
        fr: 'Suppression de la ligne...',
        es: 'Eliminando fila...',
        pt: 'Excluindo linha...',
        tr: 'Satır siliniyor...',
        uk: 'Видалення рядка...',
        zh: '正在删除行...',
        ar: 'جارٍ حذف الصف...',
        pl: 'Usuwanie wiersza...',
        it: 'Eliminazione riga...',
        sk: 'Usuwanie wiersza...',
      }),
      success: t({
        ru: 'Строка удалена',
        en: 'Row deleted',
        kk: 'Жол жойылды',
        de: 'Zeile gelöscht',
        fr: 'Ligne supprimée',
        es: 'Fila eliminada',
        pt: 'Linha excluída',
        tr: 'Satır silindi',
        uk: 'Рядок видалено',
        zh: '行已删除',
        ar: 'تم حذف الصف',
        pl: 'Wiersz usunięty',
        it: 'Riga eliminata',
        sk: 'Wiersz usunięty',
      }),
      failed: t({
        ru: 'Не удалось удалить строку',
        en: 'Failed to delete row',
        kk: 'Жолды жою мүмкін болмады',
        de: 'Zeile konnte nicht gelöscht werden',
        fr: 'Impossible de supprimer la ligne',
        es: 'No se pudo eliminar la fila',
        pt: 'Falha ao excluir a linha',
        tr: 'Satır silinemedi',
        uk: 'Не вдалося видалити рядок',
        zh: '删除行失败',
        ar: 'فشل حذف الصف',
        pl: 'Nie udało się usunąć wiersza',
        it: 'Impossibile eliminare la riga',
        sk: 'Nie udało się usunąć wiersza',
      }),
      confirmTitle: t({
        ru: 'Удалить строку?',
        en: 'Delete row?',
        kk: 'Жолды жою керек пе?',
        de: 'Zeile löschen?',
        fr: 'Supprimer la ligne ?',
        es: '¿Eliminar fila?',
        pt: 'Excluir linha?',
        tr: 'Satır silinsin mi?',
        uk: 'Видалити рядок?',
        zh: '删除行？',
        ar: 'حذف الصف؟',
        pl: 'Usunąć wiersz?',
        it: 'Eliminare la riga?',
        sk: 'Usunąć wiersz?',
      }),
      confirmWithNumberPrefix: t({ ru: 'Строка #', en: 'Row #', kk: 'Жол #', de: 'Zeile #', fr: 'Ligne n°', es: 'Fila #', pt: 'Linha #', tr: 'Satır #', uk: 'Рядок #', zh: '行 #', ar: 'الصف #', pl: 'Wiersz #', it: 'Riga #', sk: 'Wiersz #'}),
      confirmWithNumberSuffix: t({
        ru: ' будет удалена.',
        en: ' will be deleted.',
        kk: ' жойылады.',
        de: ' wird gelöscht.',
        fr: ' sera supprimée.',
        es: ' será eliminada.',
        pt: ' será excluída.',
        tr: ' silinecek.',
        uk: ' буде видалено.',
        zh: ' 将被删除。',
        ar: ' سيُحذف.',
        pl: ' zostanie usunięty.',
        it: ' verrà eliminata.',
        sk: ' zostanie usunięty.',
      }),
      confirmNoNumber: t({
        ru: 'Строка будет удалена.',
        en: 'Row will be deleted.',
        kk: 'Жол жойылады.',
        de: 'Die Zeile wird gelöscht.',
        fr: 'La ligne sera supprimée.',
        es: 'La fila será eliminada.',
        pt: 'A linha será excluída.',
        tr: 'Satır silinecek.',
        uk: 'Рядок буде видалено.',
        zh: '行将被删除。',
        ar: 'سيُحذف الصف.',
        pl: 'Wiersz zostanie usunięty.',
        it: 'La riga verrà eliminata.',
        sk: 'Wiersz zostanie usunięty.',
      }),
      confirm: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina', sk: 'Usuń'}),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
    },
    bulkDeleteRows: {
      loading: t({
        ru: 'Удаление строк...',
        en: 'Deleting rows...',
        kk: 'Жолдар жойылуда...',
        de: 'Zeilen werden gelöscht...',
        fr: 'Suppression des lignes...',
        es: 'Eliminando filas...',
        pt: 'Excluindo linhas...',
        tr: 'Satırlar siliniyor...',
        uk: 'Видалення рядків...',
        zh: '正在删除行...',
        ar: 'جارٍ حذف الصفوف...',
        pl: 'Usuwanie wierszy...',
        it: 'Eliminazione righe...',
        sk: 'Usuwanie wierszy...',
      }),
      success: t({
        ru: 'Строки удалены',
        en: 'Rows deleted',
        kk: 'Жолдар жойылды',
        de: 'Zeilen gelöscht',
        fr: 'Lignes supprimées',
        es: 'Filas eliminadas',
        pt: 'Linhas excluídas',
        tr: 'Satırlar silindi',
        uk: 'Рядки видалено',
        zh: '行已删除',
        ar: 'تم حذف الصفوف',
        pl: 'Wiersze usunięte',
        it: 'Righe eliminate',
        sk: 'Wiersze usunięte',
      }),
      failed: t({
        ru: 'Не удалось удалить некоторые строки',
        en: 'Failed to delete some rows',
        kk: 'Кейбір жолдарды жою мүмкін болмады',
        de: 'Einige Zeilen konnten nicht gelöscht werden',
        fr: 'Impossible de supprimer certaines lignes',
        es: 'No se pudieron eliminar algunas filas',
        pt: 'Falha ao excluir algumas linhas',
        tr: 'Bazı satırlar silinemedi',
        uk: 'Не вдалося видалити деякі рядки',
        zh: '删除部分行失败',
        ar: 'فشل حذف بعض الصفوف',
        pl: 'Nie udało się usunąć niektórych wierszy',
        it: 'Impossibile eliminare alcune righe',
        sk: 'Nie udało się usunąć niektórych wierszy',
      }),
      confirmTitle: t({
        ru: 'Удалить строки?',
        en: 'Delete rows?',
        kk: 'Жолдарды жою керек пе?',
        de: 'Zeilen löschen?',
        fr: 'Supprimer les lignes ?',
        es: '¿Eliminar filas?',
        pt: 'Excluir linhas?',
        tr: 'Satırlar silinsin mi?',
        uk: 'Видалити рядки?',
        zh: '删除行？',
        ar: 'حذف الصفوف؟',
        pl: 'Usunąć wiersze?',
        it: 'Eliminare le righe?',
        sk: 'Usunąć wiersze?',
      }),
      confirmMessagePrefix: t({
        ru: 'Будут удалены ',
        en: 'Delete ',
        kk: 'Жойылады ',
        de: 'Löschen ',
        fr: 'Supprimer ',
        es: 'Eliminar ',
        pt: 'Excluir ',
        tr: 'Sil ',
        uk: 'Буде видалено ',
        zh: '删除 ',
        ar: 'حذف ',
        pl: 'Usuń ',
        it: 'Elimina ',
        sk: 'Usuń ',
      }),
      confirmMessageSuffix: t({
        ru: ' выбранных строк.',
        en: ' selected rows?',
        kk: ' таңдалған жол.',
        de: ' ausgewählte Zeilen?',
        fr: ' lignes sélectionnées ?',
        es: ' filas seleccionadas?',
        pt: ' linhas selecionadas?',
        tr: ' seçili satır silinsin mi?',
        uk: ' вибраних рядків.',
        zh: ' 选定的行？',
        ar: ' الصفوف المحددة؟',
        pl: ' zaznaczonych wierszy?',
        it: ' righe selezionate?',
        sk: ' zaznaczonych wierszy?',
      }),
      confirm: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina', sk: 'Usuń'}),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
    },
    columnIcon: {
      uploaded: t({
        ru: 'Иконка загружена',
        en: 'Icon uploaded',
        kk: 'Иконка жүктелді',
        de: 'Symbol hochgeladen',
        fr: 'Icône téléchargée',
        es: 'Icono subido',
        pt: 'Ícone enviado',
        tr: 'Simge yüklendi',
        uk: 'Іконку завантажено',
        zh: '图标已上传',
        ar: 'تم رفع الأيقونة',
        pl: 'Ikona przesłana',
        it: 'Icona caricata',
        sk: 'Ikona przesłana',
      }),
      uploadFailed: t({
        ru: 'Не удалось загрузить иконку',
        en: 'Failed to upload icon',
        kk: 'Иконканы жүктеу мүмкін болмады',
        de: 'Symbol konnte nicht hochgeladen werden',
        fr: 'Impossible de télécharger l\'icône',
        es: 'No se pudo subir el icono',
        pt: 'Falha ao enviar o ícone',
        tr: 'Simge yüklenemedi',
        uk: 'Не вдалося завантажити іконку',
        zh: '上传图标失败',
        ar: 'فشل رفع الأيقونة',
        pl: 'Nie udało się przesłać ikony',
        it: 'Impossibile caricare l\'icona',
        sk: 'Nie udało się przesłać ikony',
      }),
    },
    addColumn: {
      modalTitle: t({
        ru: 'Новая колонка',
        en: 'New column',
        kk: 'Жаңа баған',
        de: 'Neue Spalte',
        fr: 'Nouvelle colonne',
        es: 'Nueva columna',
        pt: 'Nova coluna',
        tr: 'Yeni sütun',
        uk: 'Новий стовпець',
        zh: '新列',
        ar: 'عمود جديد',
        pl: 'Nowa kolumna',
        it: 'Nuova colonna',
        sk: 'Nowa kolumna',
      }),
      loading: t({
        ru: 'Добавление колонки...',
        en: 'Adding column...',
        kk: 'Баған қосылуда...',
        de: 'Spalte wird hinzugefügt...',
        fr: 'Ajout d\'une colonne...',
        es: 'Agregando columna...',
        pt: 'Adicionando coluna...',
        tr: 'Sütun ekleniyor...',
        uk: 'Додавання стовпця...',
        zh: '正在添加列...',
        ar: 'جارٍ إضافة عمود...',
        pl: 'Dodawanie kolumny...',
        it: 'Aggiunta colonna...',
        sk: 'Dodawanie kolumny...',
      }),
      success: t({
        ru: 'Колонка добавлена',
        en: 'Column added',
        kk: 'Баған қосылды',
        de: 'Spalte hinzugefügt',
        fr: 'Colonne ajoutée',
        es: 'Columna agregada',
        pt: 'Coluna adicionada',
        tr: 'Sütun eklendi',
        uk: 'Стовпець додано',
        zh: '列已添加',
        ar: 'تمت إضافة العمود',
        pl: 'Kolumna dodana',
        it: 'Colonna aggiunta',
        sk: 'Kolumna dodana',
      }),
      failed: t({
        ru: 'Не удалось добавить колонку',
        en: 'Failed to add column',
        kk: 'Баған қосу мүмкін болмады',
        de: 'Spalte konnte nicht hinzugefügt werden',
        fr: 'Impossible d\'ajouter une colonne',
        es: 'No se pudo agregar la columna',
        pt: 'Falha ao adicionar coluna',
        tr: 'Sütun eklenemedi',
        uk: 'Не вдалося додати стовпець',
        zh: '添加列失败',
        ar: 'فشل إضافة العمود',
        pl: 'Nie udało się dodać kolumny',
        it: 'Impossibile aggiungere la colonna',
        sk: 'Nie udało się dodać kolumny',
      }),
      titleLabel: t({
        ru: 'Название колонки',
        en: 'Column name',
        kk: 'Баған атауы',
        de: 'Spaltenname',
        fr: 'Nom de la colonne',
        es: 'Nombre de la columna',
        pt: 'Nome da coluna',
        tr: 'Sütun adı',
        uk: 'Назва стовпця',
        zh: '列名称',
        ar: 'اسم العمود',
        pl: 'Nazwa kolumny',
        it: 'Nome colonna',
        sk: 'Nazwa kolumny',
      }),
      titlePlaceholder: t({
        ru: 'Например: Сумма, Дата, Контрагент',
        en: 'e.g. Amount, Date, Counterparty',
        kk: 'Мысалы: Сома, Күні, Контрагент',
        de: 'z.B. Betrag, Datum, Gegenpartei',
        fr: 'ex. Montant, Date, Contrepartie',
        es: 'ej. Importe, Fecha, Contraparte',
        pt: 'ex. Valor, Data, Contraparte',
        tr: 'örn. Tutar, Tarih, Karşı taraf',
        uk: 'Наприклад: Сума, Дата, Контрагент',
        zh: '例如：金额、日期、对方',
        ar: 'مثال: المبلغ، التاريخ، الطرف المقابل',
        pl: 'np. Kwota, Data, Kontrahent',
        it: 'es. Importo, Data, Controparte',
        sk: 'np. Kwota, Data, Kontrahent',
      }),
      typeLabel: t({ ru: 'Тип', en: 'Type', kk: 'Түрі', de: 'Typ', fr: 'Type', es: 'Tipo', pt: 'Tipo', tr: 'Tür', uk: 'Тип', zh: '类型', ar: 'النوع', pl: 'Typ', it: 'Tipo', sk: 'Typ'}),
      iconLabel: t({ ru: 'Иконка', en: 'Icon', kk: 'Иконка', de: 'Symbol', fr: 'Icône', es: 'Icono', pt: 'Ícone', tr: 'Simge', uk: 'Іконка', zh: '图标', ar: 'أيقونة', pl: 'Ikona', it: 'Icona', sk: 'Ikona'}),
      choose: t({ ru: 'Выбрать', en: 'Choose', kk: 'Таңдау', de: 'Auswählen', fr: 'Choisir', es: 'Elegir', pt: 'Escolher', tr: 'Seç', uk: 'Вибрати', zh: '选择', ar: 'اختيار', pl: 'Wybierz', it: 'Scegli', sk: 'Wybierz'}),
      uploadIcon: t({
        ru: 'Загрузить иконку',
        en: 'Upload icon',
        kk: 'Иконканы жүктеу',
        de: 'Symbol hochladen',
        fr: 'Télécharger une icône',
        es: 'Subir icono',
        pt: 'Enviar ícone',
        tr: 'Simge yükle',
        uk: 'Завантажити іконку',
        zh: '上传图标',
        ar: 'رفع أيقونة',
        pl: 'Prześlij ikonę',
        it: 'Carica icona',
        sk: 'Prześlij ikonę',
      }),
      uploading: t({
        ru: 'Загрузка...',
        en: 'Uploading...',
        kk: 'Жүктелуде...',
        de: 'Hochladen...',
        fr: 'Téléchargement...',
        es: 'Subiendo...',
        pt: 'Enviando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '上传中...',
        ar: 'جارٍ الرفع...',
        pl: 'Przesyłanie...',
        it: 'Caricamento...',
        sk: 'Przesyłanie...',
      }),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
      save: t({ ru: 'Сохранить', en: 'Save', kk: 'Сақтау', de: 'Speichern', fr: 'Enregistrer', es: 'Guardar', pt: 'Salvar', tr: 'Kaydet', uk: 'Зберегти', zh: '保存', ar: 'حفظ', pl: 'Zapisz', it: 'Salva', sk: 'Zapisz'}),
    },
    dateFilters: {
      from: t({ ru: 'Дата от', en: 'Date from', kk: 'Күні бастап', de: 'Datum von', fr: 'Date de', es: 'Fecha desde', pt: 'Data de', tr: 'Tarihten', uk: 'Дата від', zh: '起始日期', ar: 'من التاريخ', pl: 'Data od', it: 'Data da', sk: 'Data od'}),
      to: t({ ru: 'Дата до', en: 'Date to', kk: 'Күні дейін', de: 'Datum bis', fr: 'Date jusqu\'à', es: 'Fecha hasta', pt: 'Data até', tr: 'Tarihe kadar', uk: 'Дата до', zh: '截止日期', ar: 'إلى التاريخ', pl: 'Data do', it: 'Data a', sk: 'Data do'}),
    },
  },
} satisfies Dictionary;

export default content;
