/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTableDetailPageModals',
  content: {
    renameColumn: {
      success: t({
        ru: 'Название колонки обновлено',
        en: 'Column renamed',
        kk: 'Баған атауы жаңартылды',
        de: 'Column renamed',
        fr: 'Column renamed',
        es: 'Column renamed',
        pt: 'Column renamed',
        tr: 'Column renamed',
        uk: 'Column renamed',
        zh: 'Column renamed',
        ar: 'Column renamed',
        pl: 'Column renamed',
        it: 'Column renamed',
        sk: 'Column renamed',
        ja: 'Column renamed',
        ko: 'Column renamed',
        hi: 'Column renamed',
        nl: 'Column renamed',
        sv: 'Column renamed',
        vi: 'Column renamed',
        id: 'Column renamed',
      }),
      failed: t({
        ru: 'Не удалось переименовать колонку',
        en: 'Failed to rename column',
        kk: 'Баған атын өзгерту мүмкін болмады',
        de: 'Failed to rename column',
        fr: 'Failed to rename column',
        es: 'Failed to rename column',
        pt: 'Failed to rename column',
        tr: 'Failed to rename column',
        uk: 'Failed to rename column',
        zh: 'Failed to rename column',
        ar: 'Failed to rename column',
        pl: 'Failed to rename column',
        it: 'Failed to rename column',
        sk: 'Failed to rename column',
        ja: 'Failed to rename column',
        ko: 'Failed to rename column',
        hi: 'Failed to rename column',
        nl: 'Failed to rename column',
        sv: 'Failed to rename column',
        vi: 'Failed to rename column',
        id: 'Failed to rename column',
      }),
    },
    deleteColumn: {
      loading: t({
        ru: 'Удаление колонки...',
        en: 'Deleting column...',
        kk: 'Баған жойылуда...',
        de: 'Deleting column...',
        fr: 'Deleting column...',
        es: 'Deleting column...',
        pt: 'Deleting column...',
        tr: 'Deleting column...',
        uk: 'Deleting column...',
        zh: 'Deleting column...',
        ar: 'Deleting column...',
        pl: 'Deleting column...',
        it: 'Deleting column...',
        sk: 'Deleting column...',
        ja: 'Deleting column...',
        ko: 'Deleting column...',
        hi: 'Deleting column...',
        nl: 'Deleting column...',
        sv: 'Deleting column...',
        vi: 'Deleting column...',
        id: 'Deleting column...',
      }),
      success: t({
        ru: 'Колонка удалена',
        en: 'Column deleted',
        kk: 'Баған жойылды',
        de: 'Column deleted',
        fr: 'Column deleted',
        es: 'Column deleted',
        pt: 'Column deleted',
        tr: 'Column deleted',
        uk: 'Column deleted',
        zh: 'Column deleted',
        ar: 'Column deleted',
        pl: 'Column deleted',
        it: 'Column deleted',
        sk: 'Column deleted',
        ja: 'Column deleted',
        ko: 'Column deleted',
        hi: 'Column deleted',
        nl: 'Column deleted',
        sv: 'Column deleted',
        vi: 'Column deleted',
        id: 'Column deleted',
      }),
      failed: t({
        ru: 'Не удалось удалить колонку',
        en: 'Failed to delete column',
        kk: 'Бағанды жою мүмкін болмады',
        de: 'Failed to delete column',
        fr: 'Failed to delete column',
        es: 'Failed to delete column',
        pt: 'Failed to delete column',
        tr: 'Failed to delete column',
        uk: 'Failed to delete column',
        zh: 'Failed to delete column',
        ar: 'Failed to delete column',
        pl: 'Failed to delete column',
        it: 'Failed to delete column',
        sk: 'Failed to delete column',
        ja: 'Failed to delete column',
        ko: 'Failed to delete column',
        hi: 'Failed to delete column',
        nl: 'Failed to delete column',
        sv: 'Failed to delete column',
        vi: 'Failed to delete column',
        id: 'Failed to delete column',
      }),
      confirmTitle: t({
        ru: 'Удалить колонку?',
        en: 'Delete column?',
        kk: 'Бағанды жою керек пе?',
        de: 'Delete column?',
        fr: 'Delete column?',
        es: 'Delete column?',
        pt: 'Delete column?',
        tr: 'Delete column?',
        uk: 'Delete column?',
        zh: 'Delete column?',
        ar: 'Delete column?',
        pl: 'Delete column?',
        it: 'Delete column?',
        sk: 'Delete column?',
        ja: 'Delete column?',
        ko: 'Delete column?',
        hi: 'Delete column?',
        nl: 'Delete column?',
        sv: 'Delete column?',
        vi: 'Delete column?',
        id: 'Delete column?',
      }),
      confirmWithNamePrefix: t({
        ru: 'Колонка "',
        en: 'Column "',
        kk: 'Баған "',
        de: 'Column "',
        fr: 'Column "',
        es: 'Column "',
        pt: 'Column "',
        tr: 'Column "',
        uk: 'Column "',
        zh: 'Column "',
        ar: 'Column "',
        pl: 'Column "',
        it: 'Column "',
        sk: 'Column "',
        ja: 'Column "',
        ko: 'Column "',
        hi: 'Column "',
        nl: 'Column "',
        sv: 'Column "',
        vi: 'Column "',
        id: 'Column "',
      }),
      confirmWithNameSuffix: t({
        ru: '" будет удалена. Значения в строках останутся в данных, но не будут отображаться (пока не добавите колонку снова).',
        en: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        kk: '" жойылады. Мәндер деректе қалады, бірақ көрсетілмейді (бағанды қайта қоспайынша).',
        de: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        fr: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        es: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        pt: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        tr: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        uk: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        zh: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        ar: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        pl: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        it: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        sk: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        ja: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        ko: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        hi: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        nl: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        sv: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        vi: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        id: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
      }),
      confirmNoName: t({
        ru: 'Колонка будет удалена.',
        en: 'Column will be deleted.',
        kk: 'Баған жойылады.',
        de: 'Column will be deleted.',
        fr: 'Column will be deleted.',
        es: 'Column will be deleted.',
        pt: 'Column will be deleted.',
        tr: 'Column will be deleted.',
        uk: 'Column will be deleted.',
        zh: 'Column will be deleted.',
        ar: 'Column will be deleted.',
        pl: 'Column will be deleted.',
        it: 'Column will be deleted.',
        sk: 'Column will be deleted.',
        ja: 'Column will be deleted.',
        ko: 'Column will be deleted.',
        hi: 'Column will be deleted.',
        nl: 'Column will be deleted.',
        sv: 'Column will be deleted.',
        vi: 'Column will be deleted.',
        id: 'Column will be deleted.',
      }),
      confirm: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Delete',
        fr: 'Delete',
        es: 'Delete',
        pt: 'Delete',
        tr: 'Delete',
        uk: 'Delete',
        zh: 'Delete',
        ar: 'Delete',
        pl: 'Delete',
        it: 'Delete',
        sk: 'Delete',
        ja: 'Delete',
        ko: 'Delete',
        hi: 'Delete',
        nl: 'Delete',
        sv: 'Delete',
        vi: 'Delete',
        id: 'Delete',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Cancel',
        fr: 'Cancel',
        es: 'Cancel',
        pt: 'Cancel',
        tr: 'Cancel',
        uk: 'Cancel',
        zh: 'Cancel',
        ar: 'Cancel',
        pl: 'Cancel',
        it: 'Cancel',
        sk: 'Cancel',
        ja: 'Cancel',
        ko: 'Cancel',
        hi: 'Cancel',
        nl: 'Cancel',
        sv: 'Cancel',
        vi: 'Cancel',
        id: 'Cancel',
      }),
    },
    deleteRow: {
      loading: t({
        ru: 'Удаление строки...',
        en: 'Deleting row...',
        kk: 'Жол жойылуда...',
        de: 'Deleting row...',
        fr: 'Deleting row...',
        es: 'Deleting row...',
        pt: 'Deleting row...',
        tr: 'Deleting row...',
        uk: 'Deleting row...',
        zh: 'Deleting row...',
        ar: 'Deleting row...',
        pl: 'Deleting row...',
        it: 'Deleting row...',
        sk: 'Deleting row...',
        ja: 'Deleting row...',
        ko: 'Deleting row...',
        hi: 'Deleting row...',
        nl: 'Deleting row...',
        sv: 'Deleting row...',
        vi: 'Deleting row...',
        id: 'Deleting row...',
      }),
      success: t({
        ru: 'Строка удалена',
        en: 'Row deleted',
        kk: 'Жол жойылды',
        de: 'Row deleted',
        fr: 'Row deleted',
        es: 'Row deleted',
        pt: 'Row deleted',
        tr: 'Row deleted',
        uk: 'Row deleted',
        zh: 'Row deleted',
        ar: 'Row deleted',
        pl: 'Row deleted',
        it: 'Row deleted',
        sk: 'Row deleted',
        ja: 'Row deleted',
        ko: 'Row deleted',
        hi: 'Row deleted',
        nl: 'Row deleted',
        sv: 'Row deleted',
        vi: 'Row deleted',
        id: 'Row deleted',
      }),
      failed: t({
        ru: 'Не удалось удалить строку',
        en: 'Failed to delete row',
        kk: 'Жолды жою мүмкін болмады',
        de: 'Failed to delete row',
        fr: 'Failed to delete row',
        es: 'Failed to delete row',
        pt: 'Failed to delete row',
        tr: 'Failed to delete row',
        uk: 'Failed to delete row',
        zh: 'Failed to delete row',
        ar: 'Failed to delete row',
        pl: 'Failed to delete row',
        it: 'Failed to delete row',
        sk: 'Failed to delete row',
        ja: 'Failed to delete row',
        ko: 'Failed to delete row',
        hi: 'Failed to delete row',
        nl: 'Failed to delete row',
        sv: 'Failed to delete row',
        vi: 'Failed to delete row',
        id: 'Failed to delete row',
      }),
      confirmTitle: t({
        ru: 'Удалить строку?',
        en: 'Delete row?',
        kk: 'Жолды жою керек пе?',
        de: 'Delete row?',
        fr: 'Delete row?',
        es: 'Delete row?',
        pt: 'Delete row?',
        tr: 'Delete row?',
        uk: 'Delete row?',
        zh: 'Delete row?',
        ar: 'Delete row?',
        pl: 'Delete row?',
        it: 'Delete row?',
        sk: 'Delete row?',
        ja: 'Delete row?',
        ko: 'Delete row?',
        hi: 'Delete row?',
        nl: 'Delete row?',
        sv: 'Delete row?',
        vi: 'Delete row?',
        id: 'Delete row?',
      }),
      confirmWithNumberPrefix: t({
        ru: 'Строка #',
        en: 'Row #',
        kk: 'Жол #',
        de: 'Row #',
        fr: 'Row #',
        es: 'Row #',
        pt: 'Row #',
        tr: 'Row #',
        uk: 'Row #',
        zh: 'Row #',
        ar: 'Row #',
        pl: 'Row #',
        it: 'Row #',
        sk: 'Row #',
        ja: 'Row #',
        ko: 'Row #',
        hi: 'Row #',
        nl: 'Row #',
        sv: 'Row #',
        vi: 'Row #',
        id: 'Row #',
      }),
      confirmWithNumberSuffix: t({
        ru: ' будет удалена.',
        en: ' will be deleted.',
        kk: ' жойылады.',
        de: ' will be deleted.',
        fr: ' will be deleted.',
        es: ' will be deleted.',
        pt: ' will be deleted.',
        tr: ' will be deleted.',
        uk: ' will be deleted.',
        zh: ' will be deleted.',
        ar: ' will be deleted.',
        pl: ' will be deleted.',
        it: ' will be deleted.',
        sk: ' will be deleted.',
        ja: ' will be deleted.',
        ko: ' will be deleted.',
        hi: ' will be deleted.',
        nl: ' will be deleted.',
        sv: ' will be deleted.',
        vi: ' will be deleted.',
        id: ' will be deleted.',
      }),
      confirmNoNumber: t({
        ru: 'Строка будет удалена.',
        en: 'Row will be deleted.',
        kk: 'Жол жойылады.',
        de: 'Row will be deleted.',
        fr: 'Row will be deleted.',
        es: 'Row will be deleted.',
        pt: 'Row will be deleted.',
        tr: 'Row will be deleted.',
        uk: 'Row will be deleted.',
        zh: 'Row will be deleted.',
        ar: 'Row will be deleted.',
        pl: 'Row will be deleted.',
        it: 'Row will be deleted.',
        sk: 'Row will be deleted.',
        ja: 'Row will be deleted.',
        ko: 'Row will be deleted.',
        hi: 'Row will be deleted.',
        nl: 'Row will be deleted.',
        sv: 'Row will be deleted.',
        vi: 'Row will be deleted.',
        id: 'Row will be deleted.',
      }),
      confirm: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Delete',
        fr: 'Delete',
        es: 'Delete',
        pt: 'Delete',
        tr: 'Delete',
        uk: 'Delete',
        zh: 'Delete',
        ar: 'Delete',
        pl: 'Delete',
        it: 'Delete',
        sk: 'Delete',
        ja: 'Delete',
        ko: 'Delete',
        hi: 'Delete',
        nl: 'Delete',
        sv: 'Delete',
        vi: 'Delete',
        id: 'Delete',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Cancel',
        fr: 'Cancel',
        es: 'Cancel',
        pt: 'Cancel',
        tr: 'Cancel',
        uk: 'Cancel',
        zh: 'Cancel',
        ar: 'Cancel',
        pl: 'Cancel',
        it: 'Cancel',
        sk: 'Cancel',
        ja: 'Cancel',
        ko: 'Cancel',
        hi: 'Cancel',
        nl: 'Cancel',
        sv: 'Cancel',
        vi: 'Cancel',
        id: 'Cancel',
      }),
    },
    bulkDeleteRows: {
      loading: t({
        ru: 'Удаление строк...',
        en: 'Deleting rows...',
        kk: 'Жолдар жойылуда...',
        de: 'Deleting rows...',
        fr: 'Deleting rows...',
        es: 'Deleting rows...',
        pt: 'Deleting rows...',
        tr: 'Deleting rows...',
        uk: 'Deleting rows...',
        zh: 'Deleting rows...',
        ar: 'Deleting rows...',
        pl: 'Deleting rows...',
        it: 'Deleting rows...',
        sk: 'Deleting rows...',
        ja: 'Deleting rows...',
        ko: 'Deleting rows...',
        hi: 'Deleting rows...',
        nl: 'Deleting rows...',
        sv: 'Deleting rows...',
        vi: 'Deleting rows...',
        id: 'Deleting rows...',
      }),
      success: t({
        ru: 'Строки удалены',
        en: 'Rows deleted',
        kk: 'Жолдар жойылды',
        de: 'Rows deleted',
        fr: 'Rows deleted',
        es: 'Rows deleted',
        pt: 'Rows deleted',
        tr: 'Rows deleted',
        uk: 'Rows deleted',
        zh: 'Rows deleted',
        ar: 'Rows deleted',
        pl: 'Rows deleted',
        it: 'Rows deleted',
        sk: 'Rows deleted',
        ja: 'Rows deleted',
        ko: 'Rows deleted',
        hi: 'Rows deleted',
        nl: 'Rows deleted',
        sv: 'Rows deleted',
        vi: 'Rows deleted',
        id: 'Rows deleted',
      }),
      failed: t({
        ru: 'Не удалось удалить некоторые строки',
        en: 'Failed to delete some rows',
        kk: 'Кейбір жолдарды жою мүмкін болмады',
        de: 'Failed to delete some rows',
        fr: 'Failed to delete some rows',
        es: 'Failed to delete some rows',
        pt: 'Failed to delete some rows',
        tr: 'Failed to delete some rows',
        uk: 'Failed to delete some rows',
        zh: 'Failed to delete some rows',
        ar: 'Failed to delete some rows',
        pl: 'Failed to delete some rows',
        it: 'Failed to delete some rows',
        sk: 'Failed to delete some rows',
        ja: 'Failed to delete some rows',
        ko: 'Failed to delete some rows',
        hi: 'Failed to delete some rows',
        nl: 'Failed to delete some rows',
        sv: 'Failed to delete some rows',
        vi: 'Failed to delete some rows',
        id: 'Failed to delete some rows',
      }),
      confirmTitle: t({
        ru: 'Удалить строки?',
        en: 'Delete rows?',
        kk: 'Жолдарды жою керек пе?',
        de: 'Delete rows?',
        fr: 'Delete rows?',
        es: 'Delete rows?',
        pt: 'Delete rows?',
        tr: 'Delete rows?',
        uk: 'Delete rows?',
        zh: 'Delete rows?',
        ar: 'Delete rows?',
        pl: 'Delete rows?',
        it: 'Delete rows?',
        sk: 'Delete rows?',
        ja: 'Delete rows?',
        ko: 'Delete rows?',
        hi: 'Delete rows?',
        nl: 'Delete rows?',
        sv: 'Delete rows?',
        vi: 'Delete rows?',
        id: 'Delete rows?',
      }),
      confirmMessagePrefix: t({
        ru: 'Будут удалены ',
        en: 'Delete ',
        kk: 'Жойылады ',
        de: 'Delete ',
        fr: 'Delete ',
        es: 'Delete ',
        pt: 'Delete ',
        tr: 'Delete ',
        uk: 'Delete ',
        zh: 'Delete ',
        ar: 'Delete ',
        pl: 'Delete ',
        it: 'Delete ',
        sk: 'Delete ',
        ja: 'Delete ',
        ko: 'Delete ',
        hi: 'Delete ',
        nl: 'Delete ',
        sv: 'Delete ',
        vi: 'Delete ',
        id: 'Delete ',
      }),
      confirmMessageSuffix: t({
        ru: ' выбранных строк.',
        en: ' selected rows?',
        kk: ' таңдалған жол.',
        de: ' selected rows?',
        fr: ' selected rows?',
        es: ' selected rows?',
        pt: ' selected rows?',
        tr: ' selected rows?',
        uk: ' selected rows?',
        zh: ' selected rows?',
        ar: ' selected rows?',
        pl: ' selected rows?',
        it: ' selected rows?',
        sk: ' selected rows?',
        ja: ' selected rows?',
        ko: ' selected rows?',
        hi: ' selected rows?',
        nl: ' selected rows?',
        sv: ' selected rows?',
        vi: ' selected rows?',
        id: ' selected rows?',
      }),
      confirm: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Delete',
        fr: 'Delete',
        es: 'Delete',
        pt: 'Delete',
        tr: 'Delete',
        uk: 'Delete',
        zh: 'Delete',
        ar: 'Delete',
        pl: 'Delete',
        it: 'Delete',
        sk: 'Delete',
        ja: 'Delete',
        ko: 'Delete',
        hi: 'Delete',
        nl: 'Delete',
        sv: 'Delete',
        vi: 'Delete',
        id: 'Delete',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Cancel',
        fr: 'Cancel',
        es: 'Cancel',
        pt: 'Cancel',
        tr: 'Cancel',
        uk: 'Cancel',
        zh: 'Cancel',
        ar: 'Cancel',
        pl: 'Cancel',
        it: 'Cancel',
        sk: 'Cancel',
        ja: 'Cancel',
        ko: 'Cancel',
        hi: 'Cancel',
        nl: 'Cancel',
        sv: 'Cancel',
        vi: 'Cancel',
        id: 'Cancel',
      }),
    },
    columnIcon: {
      uploaded: t({
        ru: 'Иконка загружена',
        en: 'Icon uploaded',
        kk: 'Иконка жүктелді',
        de: 'Icon uploaded',
        fr: 'Icon uploaded',
        es: 'Icon uploaded',
        pt: 'Icon uploaded',
        tr: 'Icon uploaded',
        uk: 'Icon uploaded',
        zh: 'Icon uploaded',
        ar: 'Icon uploaded',
        pl: 'Icon uploaded',
        it: 'Icon uploaded',
        sk: 'Icon uploaded',
        ja: 'Icon uploaded',
        ko: 'Icon uploaded',
        hi: 'Icon uploaded',
        nl: 'Icon uploaded',
        sv: 'Icon uploaded',
        vi: 'Icon uploaded',
        id: 'Icon uploaded',
      }),
      uploadFailed: t({
        ru: 'Не удалось загрузить иконку',
        en: 'Failed to upload icon',
        kk: 'Иконканы жүктеу мүмкін болмады',
        de: 'Failed to upload icon',
        fr: 'Failed to upload icon',
        es: 'Failed to upload icon',
        pt: 'Failed to upload icon',
        tr: 'Failed to upload icon',
        uk: 'Failed to upload icon',
        zh: 'Failed to upload icon',
        ar: 'Failed to upload icon',
        pl: 'Failed to upload icon',
        it: 'Failed to upload icon',
        sk: 'Failed to upload icon',
        ja: 'Failed to upload icon',
        ko: 'Failed to upload icon',
        hi: 'Failed to upload icon',
        nl: 'Failed to upload icon',
        sv: 'Failed to upload icon',
        vi: 'Failed to upload icon',
        id: 'Failed to upload icon',
      }),
    },
    addColumn: {
      modalTitle: t({
        ru: 'Новая колонка',
        en: 'New column',
        kk: 'Жаңа баған',
        de: 'New column',
        fr: 'New column',
        es: 'New column',
        pt: 'New column',
        tr: 'New column',
        uk: 'New column',
        zh: 'New column',
        ar: 'New column',
        pl: 'New column',
        it: 'New column',
        sk: 'New column',
        ja: 'New column',
        ko: 'New column',
        hi: 'New column',
        nl: 'New column',
        sv: 'New column',
        vi: 'New column',
        id: 'New column',
      }),
      loading: t({
        ru: 'Добавление колонки...',
        en: 'Adding column...',
        kk: 'Баған қосылуда...',
        de: 'Adding column...',
        fr: 'Adding column...',
        es: 'Adding column...',
        pt: 'Adding column...',
        tr: 'Adding column...',
        uk: 'Adding column...',
        zh: 'Adding column...',
        ar: 'Adding column...',
        pl: 'Adding column...',
        it: 'Adding column...',
        sk: 'Adding column...',
        ja: 'Adding column...',
        ko: 'Adding column...',
        hi: 'Adding column...',
        nl: 'Adding column...',
        sv: 'Adding column...',
        vi: 'Adding column...',
        id: 'Adding column...',
      }),
      success: t({
        ru: 'Колонка добавлена',
        en: 'Column added',
        kk: 'Баған қосылды',
        de: 'Column added',
        fr: 'Column added',
        es: 'Column added',
        pt: 'Column added',
        tr: 'Column added',
        uk: 'Column added',
        zh: 'Column added',
        ar: 'Column added',
        pl: 'Column added',
        it: 'Column added',
        sk: 'Column added',
        ja: 'Column added',
        ko: 'Column added',
        hi: 'Column added',
        nl: 'Column added',
        sv: 'Column added',
        vi: 'Column added',
        id: 'Column added',
      }),
      failed: t({
        ru: 'Не удалось добавить колонку',
        en: 'Failed to add column',
        kk: 'Баған қосу мүмкін болмады',
        de: 'Failed to add column',
        fr: 'Failed to add column',
        es: 'Failed to add column',
        pt: 'Failed to add column',
        tr: 'Failed to add column',
        uk: 'Failed to add column',
        zh: 'Failed to add column',
        ar: 'Failed to add column',
        pl: 'Failed to add column',
        it: 'Failed to add column',
        sk: 'Failed to add column',
        ja: 'Failed to add column',
        ko: 'Failed to add column',
        hi: 'Failed to add column',
        nl: 'Failed to add column',
        sv: 'Failed to add column',
        vi: 'Failed to add column',
        id: 'Failed to add column',
      }),
      titleLabel: t({
        ru: 'Название колонки',
        en: 'Column name',
        kk: 'Баған атауы',
        de: 'Column name',
        fr: 'Column name',
        es: 'Column name',
        pt: 'Column name',
        tr: 'Column name',
        uk: 'Column name',
        zh: 'Column name',
        ar: 'Column name',
        pl: 'Column name',
        it: 'Column name',
        sk: 'Column name',
        ja: 'Column name',
        ko: 'Column name',
        hi: 'Column name',
        nl: 'Column name',
        sv: 'Column name',
        vi: 'Column name',
        id: 'Column name',
      }),
      titlePlaceholder: t({
        ru: 'Например: Сумма, Дата, Контрагент',
        en: 'e.g. Amount, Date, Counterparty',
        kk: 'Мысалы: Сома, Күні, Контрагент',
        de: 'e.g. Amount, Date, Counterparty',
        fr: 'e.g. Amount, Date, Counterparty',
        es: 'e.g. Amount, Date, Counterparty',
        pt: 'e.g. Amount, Date, Counterparty',
        tr: 'e.g. Amount, Date, Counterparty',
        uk: 'e.g. Amount, Date, Counterparty',
        zh: 'e.g. Amount, Date, Counterparty',
        ar: 'e.g. Amount, Date, Counterparty',
        pl: 'e.g. Amount, Date, Counterparty',
        it: 'e.g. Amount, Date, Counterparty',
        sk: 'e.g. Amount, Date, Counterparty',
        ja: 'e.g. Amount, Date, Counterparty',
        ko: 'e.g. Amount, Date, Counterparty',
        hi: 'e.g. Amount, Date, Counterparty',
        nl: 'e.g. Amount, Date, Counterparty',
        sv: 'e.g. Amount, Date, Counterparty',
        vi: 'e.g. Amount, Date, Counterparty',
        id: 'e.g. Amount, Date, Counterparty',
      }),
      typeLabel: t({
        ru: 'Тип',
        en: 'Type',
        kk: 'Түрі',
        de: 'Type',
        fr: 'Type',
        es: 'Type',
        pt: 'Type',
        tr: 'Type',
        uk: 'Type',
        zh: 'Type',
        ar: 'Type',
        pl: 'Type',
        it: 'Type',
        sk: 'Type',
        ja: 'Type',
        ko: 'Type',
        hi: 'Type',
        nl: 'Type',
        sv: 'Type',
        vi: 'Type',
        id: 'Type',
      }),
      iconLabel: t({
        ru: 'Иконка',
        en: 'Icon',
        kk: 'Иконка',
        de: 'Icon',
        fr: 'Icon',
        es: 'Icon',
        pt: 'Icon',
        tr: 'Icon',
        uk: 'Icon',
        zh: 'Icon',
        ar: 'Icon',
        pl: 'Icon',
        it: 'Icon',
        sk: 'Icon',
        ja: 'Icon',
        ko: 'Icon',
        hi: 'Icon',
        nl: 'Icon',
        sv: 'Icon',
        vi: 'Icon',
        id: 'Icon',
      }),
      choose: t({
        ru: 'Выбрать',
        en: 'Choose',
        kk: 'Таңдау',
        de: 'Choose',
        fr: 'Choose',
        es: 'Choose',
        pt: 'Choose',
        tr: 'Choose',
        uk: 'Choose',
        zh: 'Choose',
        ar: 'Choose',
        pl: 'Choose',
        it: 'Choose',
        sk: 'Choose',
        ja: 'Choose',
        ko: 'Choose',
        hi: 'Choose',
        nl: 'Choose',
        sv: 'Choose',
        vi: 'Choose',
        id: 'Choose',
      }),
      uploadIcon: t({
        ru: 'Загрузить иконку',
        en: 'Upload icon',
        kk: 'Иконканы жүктеу',
        de: 'Upload icon',
        fr: 'Upload icon',
        es: 'Upload icon',
        pt: 'Upload icon',
        tr: 'Upload icon',
        uk: 'Upload icon',
        zh: 'Upload icon',
        ar: 'Upload icon',
        pl: 'Upload icon',
        it: 'Upload icon',
        sk: 'Upload icon',
        ja: 'Upload icon',
        ko: 'Upload icon',
        hi: 'Upload icon',
        nl: 'Upload icon',
        sv: 'Upload icon',
        vi: 'Upload icon',
        id: 'Upload icon',
      }),
      uploading: t({
        ru: 'Загрузка...',
        en: 'Uploading...',
        kk: 'Жүктелуде...',
        de: 'Uploading...',
        fr: 'Uploading...',
        es: 'Uploading...',
        pt: 'Uploading...',
        tr: 'Uploading...',
        uk: 'Uploading...',
        zh: 'Uploading...',
        ar: 'Uploading...',
        pl: 'Uploading...',
        it: 'Uploading...',
        sk: 'Uploading...',
        ja: 'Uploading...',
        ko: 'Uploading...',
        hi: 'Uploading...',
        nl: 'Uploading...',
        sv: 'Uploading...',
        vi: 'Uploading...',
        id: 'Uploading...',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Cancel',
        fr: 'Cancel',
        es: 'Cancel',
        pt: 'Cancel',
        tr: 'Cancel',
        uk: 'Cancel',
        zh: 'Cancel',
        ar: 'Cancel',
        pl: 'Cancel',
        it: 'Cancel',
        sk: 'Cancel',
        ja: 'Cancel',
        ko: 'Cancel',
        hi: 'Cancel',
        nl: 'Cancel',
        sv: 'Cancel',
        vi: 'Cancel',
        id: 'Cancel',
      }),
      save: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Save',
        fr: 'Save',
        es: 'Save',
        pt: 'Save',
        tr: 'Save',
        uk: 'Save',
        zh: 'Save',
        ar: 'Save',
        pl: 'Save',
        it: 'Save',
        sk: 'Save',
        ja: 'Save',
        ko: 'Save',
        hi: 'Save',
        nl: 'Save',
        sv: 'Save',
        vi: 'Save',
        id: 'Save',
      }),
    },
  },
} satisfies Dictionary;

export default content;
