import { makeCloudStorageContent } from '../shared/make-cloud-storage-content';

const content = makeCloudStorageContent({
  key: 'googleDriveIntegrationPage',
  name: { ru: 'Google Drive', en: 'Google Drive', kk: 'Google Drive', de: 'Google Drive', fr: 'Google Drive', es: 'Google Drive', pt: 'Google Drive', tr: 'Google Drive', uk: 'Google Drive', zh: 'Google Drive', ar: 'Google Drive', pl: 'Google Drive', it: 'Google Drive' },
  folderLabel: {
    ru: 'Папка в Drive',
    en: 'Drive folder',
    kk: 'Drive қалтасы',
    de: 'Drive-Ordner',
    fr: 'Dossier Drive',
    es: 'Carpeta de Drive',
    pt: 'Pasta do Drive',
    tr: 'Drive klasörü',
    uk: 'Папка в Drive',
    zh: 'Drive 文件夹',
    ar: 'مجلد Drive',
    pl: 'Folder Drive',
    it: 'Cartella Drive',
    sk: 'Folder Drive',
  },
  connectingLabel: {
    ru: 'Открываем авторизацию Google…',
    en: 'Opening Google authorization…',
    kk: 'Google авторизациясы ашылуда…',
    de: 'Google-Autorisierung wird geöffnet…',
    fr: 'Ouverture de l\'autorisation Google…',
    es: 'Abriendo autorización de Google…',
    pt: 'Abrindo autorização do Google…',
    tr: 'Google yetkilendirmesi açılıyor…',
    uk: 'Відкриваємо авторизацію Google…',
    zh: '正在打开 Google 授权…',
    ar: 'جارٍ فتح تفويض Google…',
    pl: 'Otwieranie autoryzacji Google…',
    it: 'Apertura autorizzazione Google…',
    sk: 'Otwieranie autoryzacji Google…',
  },
  connectedLabel: {
    ru: 'Google Drive подключен',
    en: 'Google Drive connected',
    kk: 'Google Drive қосылды',
    de: 'Google Drive verbunden',
    fr: 'Google Drive connecté',
    es: 'Google Drive conectado',
    pt: 'Google Drive conectado',
    tr: 'Google Drive bağlandı',
    uk: 'Google Drive підключено',
    zh: 'Google Drive 已连接',
    ar: 'تم توصيل Google Drive',
    pl: 'Google Drive połączony',
    it: 'Google Drive connesso',
    sk: 'Google Drive połączony',
  },
  pickerUnavailableLabel: {
    ru: 'Google Picker недоступен',
    en: 'Google Picker is unavailable',
    kk: 'Google Picker қолжетімсіз',
    de: 'Google Picker ist nicht verfügbar',
    fr: 'Google Picker est indisponible',
    es: 'Google Picker no está disponible',
    pt: 'Google Picker não está disponível',
    tr: 'Google Picker kullanılamıyor',
    uk: 'Google Picker недоступний',
    zh: 'Google Picker 不可用',
    ar: 'Google Picker غير متاح',
    pl: 'Google Picker jest niedostępny',
    it: 'Google Picker non disponibile',
    sk: 'Google Drive',
  },
});

export default content;
