import { type Dictionary, t } from 'intlayer';

const connectAction = t({
  ru: 'Подключить',
  en: 'Connect',
  kk: 'Қосу',
  de: 'Verbinden',
  fr: 'Connecter',
  es: 'Conectar',
  pt: 'Conectar',
  tr: 'Bağla',
  uk: 'Підключити',
  zh: '连接',
  ar: 'ربط',
  pl: 'Połącz',
  it: 'Connetti',
  sk: 'Połącz',
  ja: '接続',
  ko: '연결',
  hi: 'कनेक्ट करें',
  nl: 'Verbinden',
  sv: 'Anslut',
  vi: 'Kết nối',
  id: 'Hubungkan',
});
const setupAction = t({
  ru: 'Настроить',
  en: 'Set up',
  kk: 'Баптау',
  de: 'Einrichten',
  fr: 'Configurer',
  es: 'Configurar',
  pt: 'Configurar',
  tr: 'Ayarla',
  uk: 'Налаштувати',
  zh: '设置',
  ar: 'إعداد',
  pl: 'Skonfiguruj',
  it: 'Configura',
  sk: 'Skonfiguruj',
  ja: '設定する',
  ko: '설정',
  hi: 'सेट अप करें',
  nl: 'Instellen',
  sv: 'Konfigurera',
  vi: 'Thiết lập',
  id: 'Atur',
});

const content = {
  key: 'onboardingPage',
  content: {
    progressLabel: t({
      ru: 'Шаг {current} из {total}',
      en: 'Step {current} of {total}',
      kk: '{total} қадамның {current}-қадамы',
      de: 'Schritt {current} von {total}',
      fr: 'Étape {current} sur {total}',
      es: 'Paso {current} de {total}',
      pt: 'Passo {current} de {total}',
      tr: '{total} adımdan {current}. adım',
      uk: 'Крок {current} з {total}',
      zh: '第 {current} 步，共 {total} 步',
      ar: 'الخطوة {current} من {total}',
      pl: 'Krok {current} z {total}',
      it: 'Passo {current} di {total}',
      sk: 'Krok {current} z {total}',
      ja: 'ステップ {current} / {total}',
      ko: '{total}단계 중 {current}단계',
      hi: 'चरण {current} / {total}',
      nl: 'Stap {current} van {total}',
      sv: 'Steg {current} av {total}',
      vi: 'Bước {current} / {total}',
      id: 'Langkah {current} dari {total}',
    }),
    steps: {
      welcome: t({
        ru: 'Старт',
        en: 'Start',
        kk: 'Бастау',
        de: 'Start',
        fr: 'Démarrer',
        es: 'Inicio',
        pt: 'Início',
        tr: 'Başlangıç',
        uk: 'Старт',
        zh: '开始',
        ar: 'البداية',
        pl: 'Start',
        it: 'Inizio',
        sk: 'Start',
        ja: 'スタート',
        ko: '시작',
        hi: 'शुरू',
        nl: 'Start',
        sv: 'Start',
        vi: 'Bắt đầu',
        id: 'Mulai',
      }),
      language: t({
        ru: 'Язык',
        en: 'Language',
        kk: 'Тіл',
        de: 'Sprache',
        fr: 'Langue',
        es: 'Idioma',
        pt: 'Idioma',
        tr: 'Dil',
        uk: 'Мова',
        zh: '语言',
        ar: 'اللغة',
        pl: 'Język',
        it: 'Lingua',
        sk: 'Język',
        ja: '言語',
        ko: '언어',
        hi: 'भाषा',
        nl: 'Taal',
        sv: 'Språk',
        vi: 'Ngôn ngữ',
        id: 'Bahasa',
      }),
      workspace: t({
        ru: 'Воркспейс',
        en: 'Workspace',
        kk: 'Жұмыс кеңістігі',
        de: 'Arbeitsbereich',
        fr: 'Espace de travail',
        es: 'Espacio de trabajo',
        pt: 'Workspace',
        tr: 'Çalışma alanı',
        uk: 'Воркспейс',
        zh: '工作区',
        ar: 'مساحة العمل',
        pl: 'Przestrzeń robocza',
        it: 'Area di lavoro',
        sk: 'Przestrzeń robocza',
        ja: 'ワークスペース',
        ko: '워크스페이스',
        hi: 'वर्कस्पेस',
        nl: 'Werkruimte',
        sv: 'Arbetsyta',
        vi: 'Không gian làm việc',
        id: 'Ruang kerja',
      }),
      integrations: t({
        ru: 'Интеграции',
        en: 'Integrations',
        kk: 'Интеграциялар',
        de: 'Integrationen',
        fr: 'Intégrations',
        es: 'Integraciones',
        pt: 'Integrações',
        tr: 'Entegrasyonlar',
        uk: 'Інтеграції',
        zh: '集成',
        ar: 'التكاملات',
        pl: 'Integracje',
        it: 'Integrazioni',
        sk: 'Integracje',
        ja: '連携',
        ko: '통합',
        hi: 'इंटीग्रेशन',
        nl: 'Integraties',
        sv: 'Integrationer',
        vi: 'Tích hợp',
        id: 'Integrasi',
      }),
      completion: t({
        ru: 'Готово',
        en: 'Done',
        kk: 'Дайын',
        de: 'Fertig',
        fr: 'Terminé',
        es: 'Listo',
        pt: 'Concluído',
        tr: 'Tamamlandı',
        uk: 'Готово',
        zh: '完成',
        ar: 'تم',
        pl: 'Gotowe',
        it: 'Completato',
        sk: 'Gotowe',
        ja: '完了',
        ko: '완료',
        hi: 'पूर्ण',
        nl: 'Klaar',
        sv: 'Klar',
        vi: 'Hoàn thành',
        id: 'Selesai',
      }),
    },
    welcome: {
      badge: t({
        ru: 'Добро пожаловать',
        en: 'Welcome',
        kk: 'Қош келдіңіз',
        de: 'Willkommen',
        fr: 'Bienvenue',
        es: 'Bienvenido',
        pt: 'Bem-vindo',
        tr: 'Hoş geldiniz',
        uk: 'Ласкаво просимо',
        zh: '欢迎',
        ar: 'مرحبًا',
        pl: 'Witamy',
        it: 'Benvenuto',
        sk: 'Witamy',
        ja: 'ようこそ',
        ko: '환영합니다',
        hi: 'स्वागत है',
        nl: 'Welkom',
        sv: 'Välkommen',
        vi: 'Chào mừng',
        id: 'Selamat datang',
      }),
      title: t({
        ru: 'Настроим Lumio под вас',
        en: "Let's tailor Lumio for you",
        kk: 'Lumio-ны сізге бейімдейік',
        de: 'Passen wir Lumio für Sie an',
        fr: 'Personnalisons Lumio pour vous',
        es: 'Personalicemos Lumio para ti',
        pt: 'Vamos personalizar o Lumio para você',
        tr: "Lumio'yu sizin için özelleştirelim",
        uk: 'Налаштуємо Lumio для вас',
        zh: '让我们为您定制 Lumio',
        ar: 'لنخصص Lumio لك',
        pl: 'Dostosujmy Lumio dla Ciebie',
        it: 'Personalizziamo Lumio per te',
        sk: 'Dostosujmy Lumio dla Ciebie',
        ja: 'Lumio をあなた向けにカスタマイズしましょう',
        ko: 'Lumio를 맞춤 설정해 드리겠습니다',
        hi: 'Lumio को आपके लिए अनुकूलित करते हैं',
        nl: 'Laten we Lumio voor u aanpassen',
        sv: 'Låt oss anpassa Lumio för dig',
        vi: 'Hãy tùy chỉnh Lumio cho bạn',
        id: 'Mari sesuaikan Lumio untuk Anda',
      }),
      subtitle: t({
        ru: 'Это займет пару минут: выберем язык, базовую валюту и подключим нужные интеграции.',
        en: 'This takes a couple of minutes: choose language, default currency, and integrations.',
        kk: 'Бұл бірнеше минут алады: тілді, негізгі валютаны және интеграцияларды таңдаңыз.',
        de: 'Das dauert ein paar Minuten: Sprache, Standardwährung und Integrationen auswählen.',
        fr: 'Cela prend quelques minutes : choisissez la langue, la devise par défaut et les intégrations.',
        es: 'Esto lleva un par de minutos: elige idioma, moneda predeterminada e integraciones.',
        pt: 'Isso leva alguns minutos: escolha idioma, moeda padrão e integrações.',
        tr: 'Bu birkaç dakika sürer: dil, varsayılan para birimi ve entegrasyonları seçin.',
        uk: 'Це займе кілька хвилин: оберіть мову, базову валюту та підключіть потрібні інтеграції.',
        zh: '这需要几分钟：选择语言、默认货币和集成。',
        ar: 'يستغرق ذلك بضع دقائق: اختر اللغة والعملة الافتراضية والتكاملات.',
        pl: 'To zajmuje kilka minut: wybierz język, domyślną walutę i integracje.',
        it: 'Ci vogliono un paio di minuti: scegli lingua, valuta predefinita e integrazioni.',
        sk: 'To zajmuje kilka minut: wybierz język, domyślną walutę i integracje.',
        ja: '数分かかります：言語、デフォルト通貨、統合を選択してください。',
        ko: '몇 분이면 됩니다: 언어, 기본 통화 및 통합을 선택하세요.',
        hi: 'इसमें कुछ मिनट लगते हैं: भाषा, डिफ़ॉल्ट मुद्रा और इंटीग्रेशन चुनें।',
        nl: 'Dit duurt een paar minuten: kies taal, standaardvaluta en integraties.',
        sv: 'Det tar några minuter: välj språk, standardvaluta och integrationer.',
        vi: 'Chỉ mất vài phút: chọn ngôn ngữ, tiền tệ mặc định và tích hợp.',
        id: 'Ini membutuhkan beberapa menit: pilih bahasa, mata uang default, dan integrasi.',
      }),
      nextTitle: t({
        ru: 'Что будет дальше',
        en: 'What happens next',
        kk: 'Келесі қадамдар',
        de: 'Was als nächstes passiert',
        fr: 'Ce qui se passe ensuite',
        es: 'Qué pasa después',
        pt: 'O que acontece a seguir',
        tr: 'Bundan sonra ne olur',
        uk: 'Що буде далі',
        zh: '接下来发生什么',
        ar: 'ماذا سيحدث بعد ذلك',
        pl: 'Co się dzieje dalej',
        it: 'Cosa succede dopo',
        sk: 'Co się dzieje dalej',
        ja: '次のステップ',
        ko: '다음에 일어나는 일',
        hi: 'आगे क्या होगा',
        nl: 'Wat er daarna gebeurt',
        sv: 'Vad som händer härnäst',
        vi: 'Điều gì xảy ra tiếp theo',
        id: 'Apa yang terjadi selanjutnya',
      }),
      nextSteps: {
        language: t({
          ru: 'Выберите язык интерфейса и часовой пояс',
          en: 'Pick interface language and timezone',
          kk: 'Интерфейс тілі мен уақыт белдеуін таңдаңыз',
          de: 'Schnittstellensprache und Zeitzone wählen',
          fr: "Choisir la langue de l'interface et le fuseau horaire",
          es: 'Elige el idioma de la interfaz y la zona horaria',
          pt: 'Escolha o idioma da interface e o fuso horário',
          tr: 'Arayüz dili ve saat dilimi seçin',
          uk: 'Оберіть мову інтерфейсу та часовий пояс',
          zh: '选择界面语言和时区',
          ar: 'اختر لغة الواجهة والمنطقة الزمنية',
          pl: 'Wybierz język interfejsu i strefę czasową',
          it: "Scegli la lingua dell'interfaccia e il fuso orario",
          sk: 'Wybierz język interfejsu i strefę czasową',
          ja: 'インターフェース言語とタイムゾーンを選択する',
          ko: '인터페이스 언어와 시간대를 선택하세요',
          hi: 'इंटरफ़ेस भाषा और समय क्षेत्र चुनें',
          nl: 'Kies interfacetaal en tijdzone',
          sv: 'Välj gränssnittsspråk och tidszon',
          vi: 'Chọn ngôn ngữ giao diện và múi giờ',
          id: 'Pilih bahasa antarmuka dan zona waktu',
        }),
        workspace: t({
          ru: 'Настройте название, валюту и фон воркспейса',
          en: 'Set workspace name, currency, and background',
          kk: 'Жұмыс кеңістігінің атауын, валютасын және фонын орнатыңыз',
          de: 'Name, Währung und Hintergrund des Arbeitsbereichs festlegen',
          fr: "Définir le nom, la devise et l'arrière-plan de l'espace de travail",
          es: 'Establece el nombre, moneda y fondo del espacio de trabajo',
          pt: 'Defina o nome, moeda e plano de fundo do workspace',
          tr: 'Çalışma alanı adını, para birimini ve arka planı ayarlayın',
          uk: 'Налаштуйте назву, валюту та фон воркспейсу',
          zh: '设置工作区名称、货币和背景',
          ar: 'حدد اسم مساحة العمل والعملة والخلفية',
          pl: 'Ustaw nazwę, walutę i tło przestrzeni roboczej',
          it: "Imposta nome, valuta e sfondo dell'area di lavoro",
          sk: 'Ustaw nazwę, walutę i tło przestrzeni roboczej',
          ja: 'ワークスペース名、通貨、背景を設定する',
          ko: '워크스페이스 이름, 통화, 배경 설정',
          hi: 'वर्कस्पेस का नाम, मुद्रा और पृष्ठभूमि सेट करें',
          nl: 'Stel werkruimtenaam, valuta en achtergrond in',
          sv: 'Ange arbetsytans namn, valuta och bakgrund',
          vi: 'Đặt tên không gian làm việc, tiền tệ và nền',
          id: 'Atur nama ruang kerja, mata uang, dan latar belakang',
        }),
        integrations: t({
          ru: 'Подключите интеграции, которые нужны сейчас',
          en: 'Connect integrations you need right now',
          kk: 'Қазір керек интеграцияларды қосыңыз',
          de: 'Jetzt benötigte Integrationen verbinden',
          fr: 'Connectez les intégrations dont vous avez besoin maintenant',
          es: 'Conecta las integraciones que necesitas ahora',
          pt: 'Conecte as integrações que você precisa agora',
          tr: 'Şu anda ihtiyacınız olan entegrasyonları bağlayın',
          uk: 'Підключіть інтеграції, які потрібні зараз',
          zh: '立即连接您需要的集成',
          ar: 'اربط التكاملات التي تحتاجها الآن',
          pl: 'Połącz integracje, których potrzebujesz teraz',
          it: 'Collega le integrazioni di cui hai bisogno ora',
          sk: 'Połącz integracje, których potrzebujesz teraz',
          ja: '今すぐ必要な統合を接続する',
          ko: '지금 필요한 통합을 연결하세요',
          hi: 'अभी आवश्यक इंटीग्रेशन कनेक्ट करें',
          nl: 'Verbind de integraties die u nu nodig hebt',
          sv: 'Anslut de integrationer du behöver nu',
          vi: 'Kết nối các tích hợp bạn cần ngay bây giờ',
          id: 'Hubungkan integrasi yang Anda butuhkan sekarang',
        }),
      },
      points: {
        fastSetup: t({
          ru: 'Быстрая первоначальная настройка',
          en: 'Quick initial setup',
          kk: 'Жылдам бастапқы баптау',
          de: 'Schnelle Ersteinrichtung',
          fr: 'Configuration initiale rapide',
          es: 'Configuración inicial rápida',
          pt: 'Configuração inicial rápida',
          tr: 'Hızlı ilk kurulum',
          uk: 'Швидке початкове налаштування',
          zh: '快速初始设置',
          ar: 'إعداد أولي سريع',
          pl: 'Szybka konfiguracja początkowa',
          it: 'Configurazione iniziale rapida',
          sk: 'Szybka konfiguracja początkowa',
          ja: 'クイック初期設定',
          ko: '빠른 초기 설정',
          hi: 'त्वरित प्रारंभिक सेटअप',
          nl: 'Snelle initiële installatie',
          sv: 'Snabb initial konfiguration',
          vi: 'Cài đặt ban đầu nhanh chóng',
          id: 'Pengaturan awal yang cepat',
        }),
        integrations: t({
          ru: 'Подключение сервисов в один клик',
          en: 'Connect services in one click',
          kk: 'Сервистерді бір шерту арқылы қосу',
          de: 'Dienste mit einem Klick verbinden',
          fr: 'Connecter des services en un clic',
          es: 'Conectar servicios en un clic',
          pt: 'Conectar serviços com um clique',
          tr: 'Tek tıkla hizmetleri bağlayın',
          uk: 'Підключення сервісів в один клік',
          zh: '一键连接服务',
          ar: 'ربط الخدمات بنقرة واحدة',
          pl: 'Połącz usługi jednym kliknięciem',
          it: 'Connetti servizi in un clic',
          sk: 'Połącz usługi jednym kliknięciem',
          ja: 'ワンクリックでサービスを接続',
          ko: '원클릭으로 서비스 연결',
          hi: 'एक क्लिक में सेवाएं कनेक्ट करें',
          nl: 'Services verbinden met één klik',
          sv: 'Anslut tjänster med ett klick',
          vi: 'Kết nối dịch vụ chỉ với một cú nhấp',
          id: 'Hubungkan layanan dalam satu klik',
        }),
        control: t({
          ru: 'Понятный старт и полный контроль',
          en: 'Clear start and full control',
          kk: 'Түсінікті бастау және толық бақылау',
          de: 'Klarer Start und volle Kontrolle',
          fr: 'Démarrage clair et contrôle total',
          es: 'Inicio claro y control total',
          pt: 'Início claro e controle total',
          tr: 'Net başlangıç ve tam kontrol',
          uk: 'Зрозумілий старт і повний контроль',
          zh: '清晰的开始和完全控制',
          ar: 'بداية واضحة وتحكم كامل',
          pl: 'Jasny start i pełna kontrola',
          it: 'Inizio chiaro e pieno controllo',
          sk: 'Jasny start i pełna kontrola',
          ja: '明確なスタートと完全なコントロール',
          ko: '명확한 시작과 완전한 제어',
          hi: 'स्पष्ट शुरुआत और पूर्ण नियंत्रण',
          nl: 'Duidelijke start en volledige controle',
          sv: 'Tydlig start och full kontroll',
          vi: 'Khởi đầu rõ ràng và kiểm soát đầy đủ',
          id: 'Awal yang jelas dan kontrol penuh',
        }),
      },
    },
    language: {
      title: t({
        ru: 'Язык и часовой пояс',
        en: 'Language and timezone',
        kk: 'Тіл және уақыт белдеуі',
        de: 'Sprache und Zeitzone',
        fr: 'Langue et fuseau horaire',
        es: 'Idioma y zona horaria',
        pt: 'Idioma e fuso horário',
        tr: 'Dil ve saat dilimi',
        uk: 'Мова та часовий пояс',
        zh: '语言和时区',
        ar: 'اللغة والمنطقة الزمنية',
        pl: 'Język i strefa czasowa',
        it: 'Lingua e fuso orario',
        sk: 'Język i strefa czasowa',
        ja: '言語とタイムゾーン',
        ko: '언어 및 시간대',
        hi: 'भाषा और समय क्षेत्र',
        nl: 'Taal en tijdzone',
        sv: 'Språk och tidszon',
        vi: 'Ngôn ngữ và múi giờ',
        id: 'Bahasa dan zona waktu',
      }),
      subtitle: t({
        ru: 'Выберите удобный язык интерфейса и ваш часовой пояс для корректного времени в отчетах.',
        en: 'Choose your preferred interface language and timezone for accurate report timestamps.',
        kk: 'Есептердегі уақыт дұрыс болуы үшін интерфейс тілін және уақыт белдеуін таңдаңыз.',
        de: 'Wählen Sie Ihre bevorzugte Schnittstellensprache und Zeitzone für korrekte Berichtszeitstempel.',
        fr: "Choisissez votre langue d'interface préférée et votre fuseau horaire pour des horodatages précis dans les rapports.",
        es: 'Elige tu idioma de interfaz preferido y zona horaria para marcas de tiempo precisas en los informes.',
        pt: 'Escolha seu idioma de interface preferido e fuso horário para timestamps precisos nos relatórios.',
        tr: 'Raporlarda doğru zaman damgaları için tercih ettiğiniz arayüz dilini ve saat dilimini seçin.',
        uk: 'Оберіть зручну мову інтерфейсу та часовий пояс для коректного часу у звітах.',
        zh: '选择您偏好的界面语言和时区，以确保报告时间戳准确。',
        ar: 'اختر لغة الواجهة المفضلة والمنطقة الزمنية لطوابع زمنية دقيقة في التقارير.',
        pl: 'Wybierz preferowany język interfejsu i strefę czasową dla dokładnych znaczników czasu w raportach.',
        it: "Scegli la tua lingua dell'interfaccia preferita e il fuso orario per timestamp accurati nei report.",
        sk: 'Wybierz preferowany język interfejsu i strefę czasową dla dokładnych znaczników czasu w raportach.',
        ja: 'レポートの正確なタイムスタンプのために、好みのインターフェース言語とタイムゾーンを選択してください。',
        ko: '정확한 보고서 타임스탬프를 위해 선호하는 인터페이스 언어와 시간대를 선택하세요.',
        hi: 'सटीक रिपोर्ट टाइमस्टैम्प के लिए अपनी पसंदीदा इंटरफ़ेस भाषा और समय क्षेत्र चुनें।',
        nl: 'Kies uw gewenste interfacetaal en tijdzone voor nauwkeurige rapporttijdstempels.',
        sv: 'Välj ditt föredragna gränssnittsspråk och tidszon för korrekta rapporttidsstämplar.',
        vi: 'Chọn ngôn ngữ giao diện và múi giờ ưa thích để có dấu thời gian báo cáo chính xác.',
        id: 'Pilih bahasa antarmuka dan zona waktu pilihan Anda untuk cap waktu laporan yang akurat.',
      }),
      localeLabel: t({
        ru: 'Язык',
        en: 'Language',
        kk: 'Тіл',
        de: 'Sprache',
        fr: 'Langue',
        es: 'Idioma',
        pt: 'Idioma',
        tr: 'Dil',
        uk: 'Мова',
        zh: '语言',
        ar: 'اللغة',
        pl: 'Język',
        it: 'Lingua',
        sk: 'Język',
        ja: '言語',
        ko: '언어',
        hi: 'भाषा',
        nl: 'Taal',
        sv: 'Språk',
        vi: 'Ngôn ngữ',
        id: 'Bahasa',
      }),
      localeOptions: {
        ru: t({
          ru: 'Русский',
          en: 'Russian',
          kk: 'Орыс тілі',
          de: 'Russisch',
          fr: 'Russe',
          es: 'Ruso',
          pt: 'Russo',
          tr: 'Rusça',
          uk: 'Російська',
          zh: '俄语',
          ar: 'الروسية',
          pl: 'Rosyjski',
          it: 'Russo',
          sk: 'Rosyjski',
          ja: 'ロシア語',
          ko: '러시아어',
          hi: 'रूसी',
          nl: 'Russisch',
          sv: 'Ryska',
          vi: 'Tiếng Nga',
          id: 'Rusia',
        }),
        en: t({
          ru: 'English',
          en: 'English',
          kk: 'English',
          de: 'Englisch',
          fr: 'Anglais',
          es: 'Inglés',
          pt: 'Inglês',
          tr: 'İngilizce',
          uk: 'Англійська',
          zh: '英语',
          ar: 'الإنجليزية',
          pl: 'Angielski',
          it: 'Inglese',
          sk: 'Angielski',
          ja: '英語',
          ko: '영어',
          hi: 'अंग्रेज़ी',
          nl: 'Engels',
          sv: 'Engelska',
          vi: 'Tiếng Anh',
          id: 'Inggris',
        }),
        kk: t({
          ru: 'Қазақша',
          en: 'Kazakh',
          kk: 'Қазақша',
          de: 'Kasachisch',
          fr: 'Kazakh',
          es: 'Kazajo',
          pt: 'Cazaque',
          tr: 'Kazakça',
          uk: 'Казахська',
          zh: '哈萨克语',
          ar: 'الكازاخية',
          pl: 'Kazachski',
          it: 'Kazaco',
          sk: 'Kazachski',
          ja: 'カザフ語',
          ko: '카자흐어',
          hi: 'कज़ाख',
          nl: 'Kazachs',
          sv: 'Kazakiska',
          vi: 'Tiếng Kazakh',
          id: 'Kazakh',
        }),
        zh: t({
          ru: 'Китайский',
          en: 'Chinese',
          kk: 'Қытай тілі',
          de: 'Chinesisch',
          fr: 'Chinois',
          es: 'Chino',
          pt: 'Chinês',
          tr: 'Çince',
          uk: 'Китайська',
          zh: '中文',
          ar: 'الصينية',
          pl: 'Chiński',
          it: 'Cinese',
          sk: 'Chiński',
          ja: '中国語',
          ko: '중국어',
          hi: 'चीनी',
          nl: 'Chinees',
          sv: 'Kinesiska',
          vi: 'Tiếng Trung',
          id: 'Cina',
        }),
        de: t({
          ru: 'Немецкий',
          en: 'German',
          kk: 'Неміс тілі',
          de: 'Deutsch',
          fr: 'Allemand',
          es: 'Alemán',
          pt: 'Alemão',
          tr: 'Almanca',
          uk: 'Німецька',
          zh: '德语',
          ar: 'الألمانية',
          pl: 'Niemiecki',
          it: 'Tedesco',
          sk: 'Niemiecki',
          ja: 'ドイツ語',
          ko: '독일어',
          hi: 'जर्मन',
          nl: 'Duits',
          sv: 'Tyska',
          vi: 'Tiếng Đức',
          id: 'Jerman',
        }),
        fr: t({
          ru: 'Французский',
          en: 'French',
          kk: 'Француз тілі',
          de: 'Französisch',
          fr: 'Français',
          es: 'Francés',
          pt: 'Francês',
          tr: 'Fransızca',
          uk: 'Французька',
          zh: '法语',
          ar: 'الفرنسية',
          pl: 'Francuski',
          it: 'Francese',
          sk: 'Francuski',
          ja: 'フランス語',
          ko: '프랑스어',
          hi: 'फ्रेंच',
          nl: 'Frans',
          sv: 'Franska',
          vi: 'Tiếng Pháp',
          id: 'Prancis',
        }),
        es: t({
          ru: 'Испанский',
          en: 'Spanish',
          kk: 'Испан тілі',
          de: 'Spanisch',
          fr: 'Espagnol',
          es: 'Español',
          pt: 'Espanhol',
          tr: 'İspanyolca',
          uk: 'Іспанська',
          zh: '西班牙语',
          ar: 'الإسبانية',
          pl: 'Hiszpański',
          it: 'Spagnolo',
          sk: 'Hiszpański',
          ja: 'スペイン語',
          ko: '스페인어',
          hi: 'स्पेनिश',
          nl: 'Spaans',
          sv: 'Spanska',
          vi: 'Tiếng Tây Ban Nha',
          id: 'Spanyol',
        }),
        uk: t({
          ru: 'Украинский',
          en: 'Ukrainian',
          kk: 'Украин тілі',
          de: 'Ukrainisch',
          fr: 'Ukrainien',
          es: 'Ucraniano',
          pt: 'Ucraniano',
          tr: 'Ukraynaca',
          uk: 'Українська',
          zh: '乌克兰语',
          ar: 'الأوكرانية',
          pl: 'Ukraiński',
          it: 'Ucraino',
          sk: 'Ukraiński',
          ja: 'ウクライナ語',
          ko: '우크라이나어',
          hi: 'यूक्रेनी',
          nl: 'Oekraïens',
          sv: 'Ukrainska',
          vi: 'Tiếng Ukraine',
          id: 'Ukraina',
        }),
        pl: t({
          ru: 'Польский',
          en: 'Polish',
          kk: 'Поляк тілі',
          de: 'Polnisch',
          fr: 'Polonais',
          es: 'Polaco',
          pt: 'Polonês',
          tr: 'Lehçe',
          uk: 'Польська',
          zh: '波兰语',
          ar: 'البولندية',
          pl: 'Polski',
          it: 'Polacco',
          sk: 'Polski',
          ja: 'ポーランド語',
          ko: '폴란드어',
          hi: 'पोलिश',
          nl: 'Pools',
          sv: 'Polska',
          vi: 'Tiếng Ba Lan',
          id: 'Polandia',
        }),
        sk: t({
          ru: 'Словацкий',
          en: 'Slovak',
          kk: 'Словак тілі',
          de: 'Slowakisch',
          fr: 'Slovaque',
          es: 'Eslovaco',
          pt: 'Eslovaco',
          tr: 'Slovakça',
          uk: 'Словацька',
          zh: '斯洛伐克语',
          ar: 'السلوفاكية',
          pl: 'Słowacki',
          it: 'Slovacco',
          sk: 'Slovak',
          ja: 'スロバキア語',
          ko: '슬로바키아어',
          hi: 'स्लोवाक',
          nl: 'Slowaaks',
          sv: 'Slovakiska',
          vi: 'Tiếng Slovak',
          id: 'Slovakia',
        }),
      },
      timeZoneLabel: t({
        ru: 'Часовой пояс',
        en: 'Timezone',
        kk: 'Уақыт белдеуі',
        de: 'Zeitzone',
        fr: 'Fuseau horaire',
        es: 'Zona horaria',
        pt: 'Fuso horário',
        tr: 'Saat dilimi',
        uk: 'Часовий пояс',
        zh: '时区',
        ar: 'المنطقة الزمنية',
        pl: 'Strefa czasowa',
        it: 'Fuso orario',
        sk: 'Strefa czasowa',
        ja: 'タイムゾーン',
        ko: '시간대',
        hi: 'समय क्षेत्र',
        nl: 'Tijdzone',
        sv: 'Tidszon',
        vi: 'Múi giờ',
        id: 'Zona waktu',
      }),
      timeZonePlaceholder: t({
        ru: 'Выберите часовой пояс',
        en: 'Select timezone',
        kk: 'Уақыт белдеуін таңдаңыз',
        de: 'Zeitzone auswählen',
        fr: 'Sélectionner le fuseau horaire',
        es: 'Seleccionar zona horaria',
        pt: 'Selecionar fuso horário',
        tr: 'Saat dilimi seçin',
        uk: 'Оберіть часовий пояс',
        zh: '选择时区',
        ar: 'اختر المنطقة الزمنية',
        pl: 'Wybierz strefę czasową',
        it: 'Seleziona fuso orario',
        sk: 'Wybierz strefę czasową',
        ja: 'タイムゾーンを選択',
        ko: '시간대 선택',
        hi: 'समय क्षेत्र चुनें',
        nl: 'Selecteer tijdzone',
        sv: 'Välj tidszon',
        vi: 'Chọn múi giờ',
        id: 'Pilih zona waktu',
      }),
      timeZoneHint: t({
        ru: 'Вы всегда сможете изменить это позже в настройках профиля.',
        en: 'You can always change this later in profile settings.',
        kk: 'Мұны кейін профиль баптауларында өзгерте аласыз.',
        de: 'Sie können dies jederzeit in den Profileinstellungen ändern.',
        fr: 'Vous pouvez toujours modifier cela dans les paramètres du profil.',
        es: 'Siempre puedes cambiar esto más tarde en la configuración del perfil.',
        pt: 'Você sempre pode alterar isso nas configurações do perfil.',
        tr: 'Bunu daha sonra profil ayarlarından değiştirebilirsiniz.',
        uk: 'Ви завжди зможете змінити це пізніше в налаштуваннях профілю.',
        zh: '您可以随时在个人资料设置中更改此项。',
        ar: 'يمكنك دائمًا تغيير هذا لاحقًا في إعدادات الملف الشخصي.',
        pl: 'Zawsze możesz to zmienić później w ustawieniach profilu.',
        it: 'Puoi sempre cambiarlo in seguito nelle impostazioni del profilo.',
        sk: 'Zawsze możesz to zmienić później w ustawieniach profilu.',
        ja: 'プロフィール設定でいつでも変更できます。',
        ko: '나중에 프로필 설정에서 언제든지 변경할 수 있습니다.',
        hi: 'आप इसे बाद में प्रोफ़ाइल सेटिंग में कभी भी बदल सकते हैं।',
        nl: 'U kunt dit altijd later wijzigen in de profielinstellingen.',
        sv: 'Du kan alltid ändra detta senare i profilinställningarna.',
        vi: 'Bạn luôn có thể thay đổi điều này sau trong cài đặt hồ sơ.',
        id: 'Anda selalu bisa mengubah ini nanti di pengaturan profil.',
      }),
      timeZoneNoOptions: t({
        ru: 'Часовые пояса не найдены',
        en: 'No matching timezones found',
        kk: 'Сәйкес уақыт белдеуі табылмады',
        de: 'Keine passenden Zeitzonen gefunden',
        fr: 'Aucun fuseau horaire correspondant trouvé',
        es: 'No se encontraron zonas horarias coincidentes',
        pt: 'Nenhum fuso horário correspondente encontrado',
        tr: 'Eşleşen saat dilimi bulunamadı',
        uk: 'Відповідних часових поясів не знайдено',
        zh: '未找到匹配的时区',
        ar: 'لم يتم العثور على مناطق زمنية مطابقة',
        pl: 'Nie znaleziono pasujących stref czasowych',
        it: 'Nessun fuso orario corrispondente trovato',
        sk: 'Nie znaleziono pasujących stref czasowych',
        ja: '一致するタイムゾーンが見つかりません',
        ko: '일치하는 시간대를 찾을 수 없습니다',
        hi: 'कोई मेल खाने वाला समय क्षेत्र नहीं मिला',
        nl: 'Geen overeenkomende tijdzones gevonden',
        sv: 'Inga matchande tidszoner hittades',
        vi: 'Không tìm thấy múi giờ phù hợp',
        id: 'Tidak ada zona waktu yang cocok ditemukan',
      }),
    },
    workspace: {
      title: t({
        ru: 'Настройка первого воркспейса',
        en: 'Set up your first workspace',
        kk: 'Алғашқы жұмыс кеңістігін баптау',
        de: 'Richten Sie Ihren ersten Arbeitsbereich ein',
        fr: 'Configurez votre premier espace de travail',
        es: 'Configura tu primer espacio de trabajo',
        pt: 'Configure seu primeiro workspace',
        tr: 'İlk çalışma alanınızı kurun',
        uk: 'Налаштування першого воркспейсу',
        zh: '设置您的第一个工作区',
        ar: 'إعداد مساحة العمل الأولى',
        pl: 'Skonfiguruj pierwszą przestrzeń roboczą',
        it: 'Configura la tua prima area di lavoro',
        sk: 'Skonfiguruj pierwszą przestrzeń roboczą',
        ja: '最初のワークスペースを設定する',
        ko: '첫 번째 워크스페이스 설정',
        hi: 'अपना पहला वर्कस्पेस सेट करें',
        nl: 'Stel uw eerste werkruimte in',
        sv: 'Konfigurera din första arbetsyta',
        vi: 'Thiết lập không gian làm việc đầu tiên của bạn',
        id: 'Siapkan ruang kerja pertama Anda',
      }),
      subtitle: t({
        ru: 'Задайте название и валюту по умолчанию для корректного учета данных.',
        en: 'Set workspace name and default currency for accurate data tracking.',
        kk: 'Деректерді дұрыс жүргізу үшін жұмыс кеңістігінің атауын және негізгі валютаны орнатыңыз.',
        de: 'Legen Sie den Namen des Arbeitsbereichs und die Standardwährung für genaue Datenverfolgung fest.',
        fr: "Définissez le nom de l'espace de travail et la devise par défaut pour un suivi précis des données.",
        es: 'Establece el nombre del espacio de trabajo y la moneda predeterminada para un seguimiento preciso de datos.',
        pt: 'Defina o nome do workspace e a moeda padrão para rastreamento preciso de dados.',
        tr: 'Doğru veri takibi için çalışma alanı adını ve varsayılan para birimini ayarlayın.',
        uk: 'Задайте назву та валюту за замовчуванням для коректного обліку даних.',
        zh: '设置工作区名称和默认货币，以便准确跟踪数据。',
        ar: 'حدد اسم مساحة العمل والعملة الافتراضية لتتبع البيانات بدقة.',
        pl: 'Ustaw nazwę przestrzeni roboczej i domyślną walutę dla dokładnego śledzenia danych.',
        it: "Imposta il nome dell'area di lavoro e la valuta predefinita per un monitoraggio preciso dei dati.",
        sk: 'Ustaw nazwę przestrzeni roboczej i domyślną walutę dla dokładnego śledzenia danych.',
        ja: '正確なデータ追跡のためにワークスペース名とデフォルト通貨を設定してください。',
        ko: '정확한 데이터 추적을 위해 워크스페이스 이름과 기본 통화를 설정하세요.',
        hi: 'सटीक डेटा ट्रैकिंग के लिए वर्कस्पेस का नाम और डिफ़ॉल्ट मुद्रा सेट करें।',
        nl: 'Stel de werkruimtenaam en standaardvaluta in voor nauwkeurige gegevensregistratie.',
        sv: 'Ange arbetsytans namn och standardvaluta för korrekt dataspårning.',
        vi: 'Đặt tên không gian làm việc và tiền tệ mặc định để theo dõi dữ liệu chính xác.',
        id: 'Atur nama ruang kerja dan mata uang default untuk pelacakan data yang akurat.',
      }),
      nameLabel: t({
        ru: 'Название воркспейса',
        en: 'Workspace name',
        kk: 'Жұмыс кеңістігінің атауы',
        de: 'Name des Arbeitsbereichs',
        fr: "Nom de l'espace de travail",
        es: 'Nombre del espacio de trabajo',
        pt: 'Nome do workspace',
        tr: 'Çalışma alanı adı',
        uk: 'Назва воркспейсу',
        zh: '工作区名称',
        ar: 'اسم مساحة العمل',
        pl: 'Nazwa przestrzeni roboczej',
        it: "Nome dell'area di lavoro",
        sk: 'Nazwa przestrzeni roboczej',
        ja: 'ワークスペース名',
        ko: '워크스페이스 이름',
        hi: 'वर्कस्पेस का नाम',
        nl: 'Naam van de werkruimte',
        sv: 'Arbetsytans namn',
        vi: 'Tên không gian làm việc',
        id: 'Nama ruang kerja',
      }),
      namePlaceholder: t({
        ru: 'Например: My Company workspace',
        en: 'For example: My Company workspace',
        kk: 'Мысалы: My Company workspace',
        de: 'Zum Beispiel: My Company workspace',
        fr: 'Par exemple : My Company workspace',
        es: 'Por ejemplo: My Company workspace',
        pt: 'Por exemplo: My Company workspace',
        tr: 'Örneğin: My Company workspace',
        uk: 'Наприклад: My Company workspace',
        zh: '例如：My Company workspace',
        ar: 'مثال: My Company workspace',
        pl: 'Na przykład: My Company workspace',
        it: 'Ad esempio: My Company workspace',
        sk: 'Na przykład: My Company workspace',
        ja: '例：My Company workspace',
        ko: '예: My Company workspace',
        hi: 'उदाहरण: My Company workspace',
        nl: 'Bijvoorbeeld: My Company workspace',
        sv: 'Till exempel: My Company workspace',
        vi: 'Ví dụ: My Company workspace',
        id: 'Misalnya: My Company workspace',
      }),
      currencyHint: t({
        ru: 'Эта валюта будет использоваться по умолчанию при создании новых записей.',
        en: 'This currency will be used by default for new records.',
        kk: 'Бұл валюта жаңа жазбалар үшін әдепкі ретінде қолданылады.',
        de: 'Diese Währung wird standardmäßig für neue Datensätze verwendet.',
        fr: 'Cette devise sera utilisée par défaut pour les nouveaux enregistrements.',
        es: 'Esta moneda se usará de forma predeterminada para nuevos registros.',
        pt: 'Esta moeda será usada por padrão para novos registros.',
        tr: 'Bu para birimi yeni kayıtlar için varsayılan olarak kullanılacaktır.',
        uk: 'Ця валюта буде використовуватись за замовчуванням при створенні нових записів.',
        zh: '此货币将作为新记录的默认货币。',
        ar: 'ستُستخدم هذه العملة افتراضيًا للسجلات الجديدة.',
        pl: 'Ta waluta będzie używana domyślnie dla nowych rekordów.',
        it: 'Questa valuta verrà utilizzata per impostazione predefinita per i nuovi record.',
        sk: 'Ta waluta będzie używana domyślnie dla nowych rekordów.',
        ja: 'この通貨は新しいレコードのデフォルトとして使用されます。',
        ko: '이 통화는 새 레코드의 기본값으로 사용됩니다.',
        hi: 'यह मुद्रा नए रिकॉर्ड के लिए डिफ़ॉल्ट रूप से उपयोग की जाएगी।',
        nl: 'Deze valuta wordt standaard gebruikt voor nieuwe records.',
        sv: 'Denna valuta används som standard för nya poster.',
        vi: 'Tiền tệ này sẽ được sử dụng mặc định cho các bản ghi mới.',
        id: 'Mata uang ini akan digunakan secara default untuk catatan baru.',
      }),
      currencyPickerTitle: t({
        ru: 'Выберите валюту',
        en: 'Select a currency',
        kk: 'Валютаны таңдаңыз',
        de: 'Währung auswählen',
        fr: 'Sélectionner une devise',
        es: 'Seleccionar una moneda',
        pt: 'Selecionar uma moeda',
        tr: 'Para birimi seçin',
        uk: 'Оберіть валюту',
        zh: '选择货币',
        ar: 'اختر العملة',
        pl: 'Wybierz walutę',
        it: 'Seleziona una valuta',
        sk: 'Wybierz walutę',
        ja: '通貨を選択',
        ko: '통화 선택',
        hi: 'मुद्रा चुनें',
        nl: 'Selecteer een valuta',
        sv: 'Välj en valuta',
        vi: 'Chọn một loại tiền tệ',
        id: 'Pilih mata uang',
      }),
      currencyPickerSubtitle: t({
        ru: 'Найдите и выберите валюту, которая будет использоваться по умолчанию.',
        en: 'Find and select the currency that will be used by default.',
        kk: 'Әдепкі бойынша қолданылатын валютаны тауып таңдаңыз.',
        de: 'Suchen und wählen Sie die Währung, die standardmäßig verwendet wird.',
        fr: 'Trouvez et sélectionnez la devise qui sera utilisée par défaut.',
        es: 'Busca y selecciona la moneda que se usará de forma predeterminada.',
        pt: 'Encontre e selecione a moeda que será usada por padrão.',
        tr: 'Varsayılan olarak kullanılacak para birimini bulun ve seçin.',
        uk: 'Знайдіть і оберіть валюту, яка буде використовуватись за замовчуванням.',
        zh: '查找并选择将作为默认使用的货币。',
        ar: 'ابحث عن العملة التي ستُستخدم افتراضيًا وحددها.',
        pl: 'Znajdź i wybierz walutę, która będzie używana domyślnie.',
        it: 'Trova e seleziona la valuta che verrà utilizzata per impostazione predefinita.',
        sk: 'Znajdź i wybierz walutę, która będzie używana domyślnie.',
        ja: 'デフォルトで使用される通貨を検索して選択してください。',
        ko: '기본으로 사용될 통화를 찾아서 선택하세요.',
        hi: 'वह मुद्रा खोजें और चुनें जो डिफ़ॉल्ट रूप से उपयोग की जाएगी।',
        nl: 'Zoek en selecteer de valuta die standaard wordt gebruikt.',
        sv: 'Hitta och välj den valuta som ska användas som standard.',
        vi: 'Tìm và chọn loại tiền tệ sẽ được sử dụng mặc định.',
        id: 'Temukan dan pilih mata uang yang akan digunakan secara default.',
      }),
      backgroundLabel: t({
        ru: 'Фон воркспейса',
        en: 'Workspace background',
        kk: 'Жұмыс кеңістігінің фоны',
        de: 'Hintergrund des Arbeitsbereichs',
        fr: "Arrière-plan de l'espace de travail",
        es: 'Fondo del espacio de trabajo',
        pt: 'Plano de fundo do workspace',
        tr: 'Çalışma alanı arka planı',
        uk: 'Фон воркспейсу',
        zh: '工作区背景',
        ar: 'خلفية مساحة العمل',
        pl: 'Tło przestrzeni roboczej',
        it: "Sfondo dell'area di lavoro",
        sk: 'Tło przestrzeni roboczej',
        ja: 'ワークスペースの背景',
        ko: '워크스페이스 배경',
        hi: 'वर्कस्पेस की पृष्ठभूमि',
        nl: 'Werkruimte achtergrond',
        sv: 'Arbetsytans bakgrund',
        vi: 'Nền không gian làm việc',
        id: 'Latar belakang ruang kerja',
      }),
      customBackgroundLabel: t({
        ru: 'Своя картинка (URL)',
        en: 'Custom image (URL)',
        kk: 'Жеке сурет (URL)',
        de: 'Eigenes Bild (URL)',
        fr: 'Image personnalisée (URL)',
        es: 'Imagen personalizada (URL)',
        pt: 'Imagem personalizada (URL)',
        tr: 'Özel görsel (URL)',
        uk: 'Власне зображення (URL)',
        zh: '自定义图片（URL）',
        ar: 'صورة مخصصة (URL)',
        pl: 'Własny obraz (URL)',
        it: 'Immagine personalizzata (URL)',
        sk: 'Własny obraz (URL)',
        ja: 'カスタム画像（URL）',
        ko: '사용자 지정 이미지（URL）',
        hi: 'कस्टम छवि (URL)',
        nl: 'Aangepaste afbeelding (URL)',
        sv: 'Anpassad bild (URL)',
        vi: 'Hình ảnh tùy chỉnh (URL)',
        id: 'Gambar kustom (URL)',
      }),
      customBackgroundPlaceholder: t({
        ru: 'https://example.com/my-image.jpg',
        en: 'https://example.com/my-image.jpg',
        kk: 'https://example.com/my-image.jpg',
        de: 'https://example.com/my-image.jpg',
        fr: 'https://example.com/my-image.jpg',
        es: 'https://example.com/my-image.jpg',
        pt: 'https://example.com/my-image.jpg',
        tr: 'https://example.com/my-image.jpg',
        uk: 'https://example.com/my-image.jpg',
        zh: 'https://example.com/my-image.jpg',
        ar: 'https://example.com/my-image.jpg',
        pl: 'https://example.com/my-image.jpg',
        it: 'https://example.com/my-image.jpg',
        sk: 'https://example.com/my-image.jpg',
        ja: 'https://example.com/my-image.jpg',
        ko: 'https://example.com/my-image.jpg',
        hi: 'https://example.com/my-image.jpg',
        nl: 'https://example.com/my-image.jpg',
        sv: 'https://example.com/my-image.jpg',
        vi: 'https://example.com/my-image.jpg',
        id: 'https://example.com/my-image.jpg',
      }),
      customBackgroundHint: t({
        ru: 'Можно вставить ссылку на свою картинку или выбрать одну из готовых ниже.',
        en: 'Paste your own image URL or choose one of the presets below.',
        kk: 'Өз суретіңіздің URL сілтемесін енгізіңіз немесе дайын нұсқалардың бірін таңдаңыз.',
        de: 'Fügen Sie Ihre eigene Bild-URL ein oder wählen Sie eine der Voreinstellungen unten.',
        fr: "Collez l'URL de votre propre image ou choisissez l'un des préréglages ci-dessous.",
        es: 'Pega la URL de tu propia imagen o elige uno de los ajustes preestablecidos a continuación.',
        pt: 'Cole a URL da sua própria imagem ou escolha uma das predefinições abaixo.',
        tr: "Kendi görsel URL'nizi yapıştırın veya aşağıdaki hazır seçeneklerden birini seçin.",
        uk: 'Можна вставити посилання на власне зображення або вибрати одне із готових нижче.',
        zh: '粘贴您自己的图片 URL，或从下面的预设中选择一个。',
        ar: 'الصق رابط صورتك الخاصة أو اختر أحد الإعدادات المسبقة أدناه.',
        pl: 'Wklej URL własnego obrazu lub wybierz jeden z gotowych poniżej.',
        it: "Incolla l'URL della tua immagine o scegli uno dei preset qui sotto.",
        sk: 'Wklej URL własnego obrazu lub wybierz jeden z gotowych poniżej.',
        ja: '独自の画像URLを貼り付けるか、以下のプリセットから選択してください。',
        ko: '자신의 이미지 URL을 붙여넣거나 아래 프리셋 중 하나를 선택하세요.',
        hi: 'अपनी खुद की छवि URL चिपकाएं या नीचे दिए गए प्रीसेट में से एक चुनें।',
        nl: 'Plak uw eigen afbeelding-URL of kies een van de voorinstellingen hieronder.',
        sv: 'Klistra in din egna bild-URL eller välj ett av förinställningarna nedan.',
        vi: 'Dán URL hình ảnh của bạn hoặc chọn một trong các cài đặt sẵn bên dưới.',
        id: 'Tempel URL gambar Anda sendiri atau pilih salah satu preset di bawah.',
      }),
    },
    integrations: {
      title: t({
        ru: 'Подключите нужные интеграции',
        en: 'Connect your integrations',
        kk: 'Қажетті интеграцияларды қосыңыз',
        de: 'Verbinden Sie Ihre Integrationen',
        fr: 'Connectez vos intégrations',
        es: 'Conecta tus integraciones',
        pt: 'Conecte suas integrações',
        tr: 'Entegrasyonlarınızı bağlayın',
        uk: 'Підключіть потрібні інтеграції',
        zh: '连接您的集成',
        ar: 'اربط تكاملاتك',
        pl: 'Połącz swoje integracje',
        it: 'Collega le tue integrazioni',
        sk: 'Połącz swoje integracje',
        ja: '統合を接続する',
        ko: '통합을 연결하세요',
        hi: 'अपने इंटीग्रेशन कनेक्ट करें',
        nl: 'Verbind uw integraties',
        sv: 'Anslut dina integrationer',
        vi: 'Kết nối các tích hợp của bạn',
        id: 'Hubungkan integrasi Anda',
      }),
      subtitle: t({
        ru: 'Выберите сервисы, которые хотите настроить сейчас. Можно подключить и позже.',
        en: 'Pick services you want to set up now. You can connect them later as well.',
        kk: 'Қазір баптағыңыз келетін сервистерді таңдаңыз. Кейін де қосуға болады.',
        de: 'Wählen Sie Dienste, die Sie jetzt einrichten möchten. Sie können diese auch später verbinden.',
        fr: 'Choisissez les services que vous souhaitez configurer maintenant. Vous pouvez les connecter plus tard également.',
        es: 'Elige los servicios que deseas configurar ahora. También puedes conectarlos más tarde.',
        pt: 'Escolha os serviços que deseja configurar agora. Você também pode conectá-los mais tarde.',
        tr: 'Şimdi kurmak istediğiniz hizmetleri seçin. Bunları daha sonra da bağlayabilirsiniz.',
        uk: 'Оберіть сервіси, які хочете налаштувати зараз. Можна підключити і пізніше.',
        zh: '选择您现在想要设置的服务。您也可以稍后连接它们。',
        ar: 'اختر الخدمات التي تريد إعدادها الآن. يمكنك ربطها لاحقًا أيضًا.',
        pl: 'Wybierz usługi, które chcesz skonfigurować teraz. Możesz je połączyć później.',
        it: 'Scegli i servizi che vuoi configurare ora. Puoi connetterli anche in seguito.',
        sk: 'Wybierz usługi, które chcesz skonfigurować teraz. Możesz je połączyć później.',
        ja: '今設定したいサービスを選択してください。後で接続することもできます。',
        ko: '지금 설정하고 싶은 서비스를 선택하세요. 나중에 연결할 수도 있습니다.',
        hi: 'वे सेवाएं चुनें जिन्हें आप अभी सेट अप करना चाहते हैं। आप उन्हें बाद में भी कनेक्ट कर सकते हैं।',
        nl: 'Kies services die u nu wilt instellen. U kunt ze later ook verbinden.',
        sv: 'Välj tjänster du vill konfigurera nu. Du kan även ansluta dem senare.',
        vi: 'Chọn các dịch vụ bạn muốn thiết lập ngay bây giờ. Bạn cũng có thể kết nối chúng sau.',
        id: 'Pilih layanan yang ingin Anda siapkan sekarang. Anda juga dapat menghubungkannya nanti.',
      }),
      helper: t({
        ru: 'Если пропустить шаг, интеграции можно подключить в разделе Настройки -> Интеграции.',
        en: 'If you skip this step, you can connect integrations later in Settings -> Integrations.',
        kk: 'Бұл қадамды өткізіп жіберсеңіз, интеграцияларды кейін Баптаулар -> Интеграциялар бөлімінен қоса аласыз.',
        de: 'Wenn Sie diesen Schritt überspringen, können Sie Integrationen später unter Einstellungen -> Integrationen verbinden.',
        fr: 'Si vous sautez cette étape, vous pouvez connecter des intégrations plus tard dans Paramètres -> Intégrations.',
        es: 'Si omites este paso, puedes conectar integraciones más tarde en Configuración -> Integraciones.',
        pt: 'Se pular esta etapa, você pode conectar integrações mais tarde em Configurações -> Integrações.',
        tr: 'Bu adımı atlarsanız, entegrasyonları daha sonra Ayarlar -> Entegrasyonlar bölümünde bağlayabilirsiniz.',
        uk: 'Якщо пропустити крок, інтеграції можна підключити в розділі Налаштування -> Інтеграції.',
        zh: '如果跳过此步骤，可以稍后在设置 -> 集成中连接集成。',
        ar: 'إذا تخطيت هذه الخطوة، يمكنك ربط التكاملات لاحقًا في الإعدادات -> التكاملات.',
        pl: 'Jeśli pominiesz ten krok, możesz połączyć integracje później w Ustawieniach -> Integracje.',
        it: 'Se salti questo passaggio, puoi connettere le integrazioni in seguito in Impostazioni -> Integrazioni.',
        sk: 'Jeśli pominiesz ten krok, możesz połączyć integracje później w Ustawieniach -> Integracje.',
        ja: 'このステップをスキップした場合、後で設定 -> 統合で統合を接続できます。',
        ko: '이 단계를 건너뛰면 나중에 설정 -> 통합에서 통합을 연결할 수 있습니다.',
        hi: 'यदि आप इस चरण को छोड़ते हैं, तो आप बाद में सेटिंग्स -> इंटीग्रेशन में इंटीग्रेशन कनेक्ट कर सकते हैं।',
        nl: 'Als u deze stap overslaat, kunt u later integraties verbinden via Instellingen -> Integraties.',
        sv: 'Om du hoppar över det här steget kan du ansluta integrationer senare i Inställningar -> Integrationer.',
        vi: 'Nếu bạn bỏ qua bước này, bạn có thể kết nối tích hợp sau trong Cài đặt -> Tích hợp.',
        id: 'Jika Anda melewati langkah ini, Anda dapat menghubungkan integrasi nanti di Pengaturan -> Integrasi.',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить интеграцию. Попробуйте еще раз.',
        en: 'Failed to connect integration. Please try again.',
        kk: 'Интеграцияны қосу мүмкін болмады. Қайта көріңіз.',
        de: 'Integration konnte nicht verbunden werden. Bitte versuchen Sie es erneut.',
        fr: "Impossible de connecter l'intégration. Veuillez réessayer.",
        es: 'No se pudo conectar la integración. Por favor, inténtalo de nuevo.',
        pt: 'Falha ao conectar integração. Por favor, tente novamente.',
        tr: 'Entegrasyon bağlanamadı. Lütfen tekrar deneyin.',
        uk: 'Не вдалося підключити інтеграцію. Спробуйте ще раз.',
        zh: '无法连接集成。请重试。',
        ar: 'فشل ربط التكامل. يرجى المحاولة مرة أخرى.',
        pl: 'Nie udało się połączyć integracji. Spróbuj ponownie.',
        it: "Impossibile connettere l'integrazione. Riprova.",
        sk: 'Nie udało się połączyć integracji. Spróbuj ponownie.',
        ja: '統合の接続に失敗しました。もう一度お試しください。',
        ko: '통합 연결에 실패했습니다. 다시 시도해 주세요.',
        hi: 'इंटीग्रेशन कनेक्ट करने में विफल। कृपया पुनः प्रयास करें।',
        nl: 'Verbinding met integratie mislukt. Probeer het opnieuw.',
        sv: 'Det gick inte att ansluta integrationen. Försök igen.',
        vi: 'Kết nối tích hợp thất bại. Vui lòng thử lại.',
        id: 'Gagal menghubungkan integrasi. Silakan coba lagi.',
      }),
      cards: {
        s3Compatible: {
          title: t({
            ru: 'S3-compatible storage',
            en: 'S3-compatible storage',
            kk: 'S3-compatible storage',
            de: 'S3-compatible storage',
            fr: 'S3-compatible storage',
            es: 'S3-compatible storage',
            pt: 'S3-compatible storage',
            tr: 'S3-compatible storage',
            uk: 'S3-compatible storage',
            zh: 'S3-compatible storage',
            ar: 'S3-compatible storage',
            pl: 'S3-compatible storage',
            it: 'S3-compatible storage',
            sk: 'S3-compatible storage',
            ja: 'S3-compatible storage',
            ko: 'S3-compatible storage',
            hi: 'S3-compatible storage',
            nl: 'S3-compatible storage',
            sv: 'S3-compatible storage',
            vi: 'S3-compatible storage',
            id: 'S3-compatible storage',
          }),
          description: t({
            ru: 'Подключите MinIO или любой S3-compatible bucket для импорта и синхронизации.',
            en: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            kk: 'Импорт және синхрондау үшін MinIO немесе S3-compatible bucket қосыңыз.',
            de: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            fr: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            es: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            pt: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            tr: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            uk: 'Підключіть MinIO або будь-який S3-compatible bucket для імпорту та синхронізації.',
            zh: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            ar: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            pl: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            it: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            sk: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            ja: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            ko: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            hi: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            nl: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            sv: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            vi: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
            id: 'Connect MinIO or any S3-compatible bucket for imports and sync.',
          }),
          action: setupAction,
        },
        webdav: {
          title: t({
            ru: 'WebDAV storage',
            en: 'WebDAV storage',
            kk: 'WebDAV storage',
            de: 'WebDAV storage',
            fr: 'WebDAV storage',
            es: 'WebDAV storage',
            pt: 'WebDAV storage',
            tr: 'WebDAV storage',
            uk: 'WebDAV storage',
            zh: 'WebDAV storage',
            ar: 'WebDAV storage',
            pl: 'WebDAV storage',
            it: 'WebDAV storage',
            sk: 'WebDAV storage',
            ja: 'WebDAV storage',
            ko: 'WebDAV storage',
            hi: 'WebDAV storage',
            nl: 'WebDAV storage',
            sv: 'WebDAV storage',
            vi: 'WebDAV storage',
            id: 'WebDAV storage',
          }),
          description: t({
            ru: 'Подключите Nextcloud или другое WebDAV-compatible хранилище файлов.',
            en: 'Connect Nextcloud or another WebDAV-compatible file store.',
            kk: 'Nextcloud немесе басқа WebDAV-compatible файл қоймасын қосыңыз.',
            de: 'Connect Nextcloud or another WebDAV-compatible file store.',
            fr: 'Connect Nextcloud or another WebDAV-compatible file store.',
            es: 'Connect Nextcloud or another WebDAV-compatible file store.',
            pt: 'Connect Nextcloud or another WebDAV-compatible file store.',
            tr: 'Connect Nextcloud or another WebDAV-compatible file store.',
            uk: 'Підключіть Nextcloud або інше WebDAV-compatible файлове сховище.',
            zh: 'Connect Nextcloud or another WebDAV-compatible file store.',
            ar: 'Connect Nextcloud or another WebDAV-compatible file store.',
            pl: 'Connect Nextcloud or another WebDAV-compatible file store.',
            it: 'Connect Nextcloud or another WebDAV-compatible file store.',
            sk: 'Connect Nextcloud or another WebDAV-compatible file store.',
            ja: 'Connect Nextcloud or another WebDAV-compatible file store.',
            ko: 'Connect Nextcloud or another WebDAV-compatible file store.',
            hi: 'Connect Nextcloud or another WebDAV-compatible file store.',
            nl: 'Connect Nextcloud or another WebDAV-compatible file store.',
            sv: 'Connect Nextcloud or another WebDAV-compatible file store.',
            vi: 'Connect Nextcloud or another WebDAV-compatible file store.',
            id: 'Connect Nextcloud or another WebDAV-compatible file store.',
          }),
          action: setupAction,
        },
        imap: {
          title: t({
            ru: 'IMAP inbox',
            en: 'IMAP inbox',
            kk: 'IMAP inbox',
            de: 'IMAP inbox',
            fr: 'IMAP inbox',
            es: 'IMAP inbox',
            pt: 'IMAP inbox',
            tr: 'IMAP inbox',
            uk: 'IMAP inbox',
            zh: 'IMAP inbox',
            ar: 'IMAP inbox',
            pl: 'IMAP inbox',
            it: 'IMAP inbox',
            sk: 'IMAP inbox',
            ja: 'IMAP inbox',
            ko: 'IMAP inbox',
            hi: 'IMAP inbox',
            nl: 'IMAP inbox',
            sv: 'IMAP inbox',
            vi: 'IMAP inbox',
            id: 'IMAP inbox',
          }),
          description: t({
            ru: 'Импортируйте чеки из любого IMAP-compatible почтового ящика.',
            en: 'Import receipts from any IMAP-compatible mailbox.',
            kk: 'Кез келген IMAP-compatible пошта жәшігінен чектерді импорттаңыз.',
            de: 'Import receipts from any IMAP-compatible mailbox.',
            fr: 'Import receipts from any IMAP-compatible mailbox.',
            es: 'Import receipts from any IMAP-compatible mailbox.',
            pt: 'Import receipts from any IMAP-compatible mailbox.',
            tr: 'Import receipts from any IMAP-compatible mailbox.',
            uk: 'Імпортуйте чеки з будь-якої IMAP-compatible поштової скриньки.',
            zh: 'Import receipts from any IMAP-compatible mailbox.',
            ar: 'Import receipts from any IMAP-compatible mailbox.',
            pl: 'Import receipts from any IMAP-compatible mailbox.',
            it: 'Import receipts from any IMAP-compatible mailbox.',
            sk: 'Import receipts from any IMAP-compatible mailbox.',
            ja: 'Import receipts from any IMAP-compatible mailbox.',
            ko: 'Import receipts from any IMAP-compatible mailbox.',
            hi: 'Import receipts from any IMAP-compatible mailbox.',
            nl: 'Import receipts from any IMAP-compatible mailbox.',
            sv: 'Import receipts from any IMAP-compatible mailbox.',
            vi: 'Import receipts from any IMAP-compatible mailbox.',
            id: 'Import receipts from any IMAP-compatible mailbox.',
          }),
          action: connectAction,
        },
        smtp: {
          title: t({
            ru: 'SMTP email',
            en: 'SMTP email',
            kk: 'SMTP email',
            de: 'SMTP email',
            fr: 'SMTP email',
            es: 'SMTP email',
            pt: 'SMTP email',
            tr: 'SMTP email',
            uk: 'SMTP email',
            zh: 'SMTP email',
            ar: 'SMTP email',
            pl: 'SMTP email',
            it: 'SMTP email',
            sk: 'SMTP email',
            ja: 'SMTP email',
            ko: 'SMTP email',
            hi: 'SMTP email',
            nl: 'SMTP email',
            sv: 'SMTP email',
            vi: 'SMTP email',
            id: 'SMTP email',
          }),
          description: t({
            ru: 'Отправляйте приглашения через любой SMTP-compatible почтовый сервер.',
            en: 'Send invitations through any SMTP-compatible mail server.',
            kk: 'Шақыруларды кез келген SMTP-compatible пошта сервері арқылы жіберіңіз.',
            de: 'Send invitations through any SMTP-compatible mail server.',
            fr: 'Send invitations through any SMTP-compatible mail server.',
            es: 'Send invitations through any SMTP-compatible mail server.',
            pt: 'Send invitations through any SMTP-compatible mail server.',
            tr: 'Send invitations through any SMTP-compatible mail server.',
            uk: 'Надсилайте запрошення через будь-який SMTP-compatible поштовий сервер.',
            zh: 'Send invitations through any SMTP-compatible mail server.',
            ar: 'Send invitations through any SMTP-compatible mail server.',
            pl: 'Send invitations through any SMTP-compatible mail server.',
            it: 'Send invitations through any SMTP-compatible mail server.',
            sk: 'Send invitations through any SMTP-compatible mail server.',
            ja: 'Send invitations through any SMTP-compatible mail server.',
            ko: 'Send invitations through any SMTP-compatible mail server.',
            hi: 'Send invitations through any SMTP-compatible mail server.',
            nl: 'Send invitations through any SMTP-compatible mail server.',
            sv: 'Send invitations through any SMTP-compatible mail server.',
            vi: 'Send invitations through any SMTP-compatible mail server.',
            id: 'Send invitations through any SMTP-compatible mail server.',
          }),
          action: setupAction,
        },
        aiCompatible: {
          title: t({
            ru: 'AI-compatible endpoint',
            en: 'AI-compatible endpoint',
            kk: 'AI-compatible endpoint',
            de: 'AI-compatible endpoint',
            fr: 'AI-compatible endpoint',
            es: 'AI-compatible endpoint',
            pt: 'AI-compatible endpoint',
            tr: 'AI-compatible endpoint',
            uk: 'AI-compatible endpoint',
            zh: 'AI-compatible endpoint',
            ar: 'AI-compatible endpoint',
            pl: 'AI-compatible endpoint',
            it: 'AI-compatible endpoint',
            sk: 'AI-compatible endpoint',
            ja: 'AI-compatible endpoint',
            ko: 'AI-compatible endpoint',
            hi: 'AI-compatible endpoint',
            nl: 'AI-compatible endpoint',
            sv: 'AI-compatible endpoint',
            vi: 'AI-compatible endpoint',
            id: 'AI-compatible endpoint',
          }),
          description: t({
            ru: 'Используйте Ollama, LocalAI, vLLM или другой OpenAI-compatible backend.',
            en: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            kk: 'Ollama, LocalAI, vLLM немесе басқа OpenAI-compatible backend қолданыңыз.',
            de: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            fr: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            es: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            pt: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            tr: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            uk: 'Використовуйте Ollama, LocalAI, vLLM або інший OpenAI-compatible backend.',
            zh: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            ar: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            pl: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            it: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            sk: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            ja: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            ko: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            hi: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            nl: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            sv: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            vi: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
            id: 'Use Ollama, LocalAI, vLLM, or another OpenAI-compatible backend.',
          }),
          action: setupAction,
        },
        telegram: {
          title: t({
            ru: 'Telegram',
            en: 'Telegram',
            kk: 'Telegram',
            de: 'Telegram',
            fr: 'Telegram',
            es: 'Telegram',
            pt: 'Telegram',
            tr: 'Telegram',
            uk: 'Telegram',
            zh: 'Telegram',
            ar: 'Telegram',
            pl: 'Telegram',
            it: 'Telegram',
            sk: 'Telegram',
            ja: 'Telegram',
            ko: 'Telegram',
            hi: 'Telegram',
            nl: 'Telegram',
            sv: 'Telegram',
            vi: 'Telegram',
            id: 'Telegram',
          }),
          description: t({
            ru: 'Подключите бота для отчетов и доставки уведомлений.',
            en: 'Connect a bot for reports and notification delivery.',
            kk: 'Есептер мен хабарламалар үшін ботты қосыңыз.',
            de: 'Connect a bot for reports and notification delivery.',
            fr: 'Connect a bot for reports and notification delivery.',
            es: 'Connect a bot for reports and notification delivery.',
            pt: 'Connect a bot for reports and notification delivery.',
            tr: 'Connect a bot for reports and notification delivery.',
            uk: 'Підключіть бота для звітів і доставки сповіщень.',
            zh: 'Connect a bot for reports and notification delivery.',
            ar: 'Connect a bot for reports and notification delivery.',
            pl: 'Connect a bot for reports and notification delivery.',
            it: 'Connect a bot for reports and notification delivery.',
            sk: 'Connect a bot for reports and notification delivery.',
            ja: 'Connect a bot for reports and notification delivery.',
            ko: 'Connect a bot for reports and notification delivery.',
            hi: 'Connect a bot for reports and notification delivery.',
            nl: 'Connect a bot for reports and notification delivery.',
            sv: 'Connect a bot for reports and notification delivery.',
            vi: 'Connect a bot for reports and notification delivery.',
            id: 'Connect a bot for reports and notification delivery.',
          }),
          action: setupAction,
        },
        appUrl: {
          title: t({
            ru: 'Application URL',
            en: 'Application URL',
            kk: 'Application URL',
            de: 'Application URL',
            fr: 'Application URL',
            es: 'Application URL',
            pt: 'Application URL',
            tr: 'Application URL',
            uk: 'Application URL',
            zh: 'Application URL',
            ar: 'Application URL',
            pl: 'Application URL',
            it: 'Application URL',
            sk: 'Application URL',
            ja: 'Application URL',
            ko: 'Application URL',
            hi: 'Application URL',
            nl: 'Application URL',
            sv: 'Application URL',
            vi: 'Application URL',
            id: 'Application URL',
          }),
          description: t({
            ru: 'Задайте публичный URL для ссылок приглашений и общего доступа.',
            en: 'Set the public URL used in invitation and sharing links.',
            kk: 'Шақыру және бөлісу сілтемелері үшін public URL орнатыңыз.',
            de: 'Set the public URL used in invitation and sharing links.',
            fr: 'Set the public URL used in invitation and sharing links.',
            es: 'Set the public URL used in invitation and sharing links.',
            pt: 'Set the public URL used in invitation and sharing links.',
            tr: 'Set the public URL used in invitation and sharing links.',
            uk: 'Задайте публічний URL для посилань запрошень і спільного доступу.',
            zh: 'Set the public URL used in invitation and sharing links.',
            ar: 'Set the public URL used in invitation and sharing links.',
            pl: 'Set the public URL used in invitation and sharing links.',
            it: 'Set the public URL used in invitation and sharing links.',
            sk: 'Set the public URL used in invitation and sharing links.',
            ja: 'Set the public URL used in invitation and sharing links.',
            ko: 'Set the public URL used in invitation and sharing links.',
            hi: 'Set the public URL used in invitation and sharing links.',
            nl: 'Set the public URL used in invitation and sharing links.',
            sv: 'Set the public URL used in invitation and sharing links.',
            vi: 'Set the public URL used in invitation and sharing links.',
            id: 'Set the public URL used in invitation and sharing links.',
          }),
          action: setupAction,
        },
      },
      connectedBadge: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылған',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlandı',
        uk: 'Підключено',
        zh: '已连接',
        ar: 'متصل',
        pl: 'Połączono',
        it: 'Connesso',
        sk: 'Połączono',
        ja: '接続済み',
        ko: '연결됨',
        hi: 'कनेक्टेड',
        nl: 'Verbonden',
        sv: 'Ansluten',
        vi: 'Đã kết nối',
        id: 'Terhubung',
      }),
      availableBadge: t({
        ru: 'Доступно',
        en: 'Available',
        kk: 'Қолжетімді',
        de: 'Verfügbar',
        fr: 'Disponible',
        es: 'Disponible',
        pt: 'Disponível',
        tr: 'Mevcut',
        uk: 'Доступно',
        zh: '可用',
        ar: 'متاح',
        pl: 'Dostępne',
        it: 'Disponibile',
        sk: 'Dostępne',
        ja: '利用可能',
        ko: '사용 가능',
        hi: 'उपलब्ध',
        nl: 'Beschikbaar',
        sv: 'Tillgänglig',
        vi: 'Có sẵn',
        id: 'Tersedia',
      }),
    },
    completion: {
      title: t({
        ru: 'Готово! Все настроено',
        en: 'Done! Setup complete',
        kk: 'Дайын! Баптау аяқталды',
        de: 'Fertig! Einrichtung abgeschlossen',
        fr: 'Terminé ! Configuration complète',
        es: '¡Listo! Configuración completa',
        pt: 'Concluído! Configuração completa',
        tr: 'Tamamlandı! Kurulum bitti',
        uk: 'Готово! Все налаштовано',
        zh: '完成！设置已完成',
        ar: 'تم! اكتمل الإعداد',
        pl: 'Gotowe! Konfiguracja zakończona',
        it: 'Fatto! Configurazione completata',
        sk: 'Gotowe! Konfiguracja zakończona',
        ja: '完了！セットアップが完了しました',
        ko: '완료! 설정이 완료되었습니다',
        hi: 'हो गया! सेटअप पूर्ण',
        nl: 'Klaar! Installatie voltooid',
        sv: 'Klar! Installationen är slutförd',
        vi: 'Xong! Cài đặt hoàn tất',
        id: 'Selesai! Pengaturan selesai',
      }),
      subtitle: t({
        ru: 'Нажмите кнопку ниже, и перейдете в рабочее пространство.',
        en: 'Press the button below to continue to your workspace.',
        kk: 'Төмендегі батырманы басып, жұмыс кеңістігіне өтіңіз.',
        de: 'Drücken Sie den Button unten, um zu Ihrem Arbeitsbereich zu gelangen.',
        fr: 'Appuyez sur le bouton ci-dessous pour accéder à votre espace de travail.',
        es: 'Presiona el botón de abajo para continuar a tu espacio de trabajo.',
        pt: 'Pressione o botão abaixo para continuar para o seu workspace.',
        tr: 'Çalışma alanınıza geçmek için aşağıdaki düğmeye basın.',
        uk: 'Натисніть кнопку нижче і перейдіть до робочого простору.',
        zh: '按下下方按钮继续进入您的工作区。',
        ar: 'اضغط على الزر أدناه للانتقال إلى مساحة العمل.',
        pl: 'Naciśnij przycisk poniżej, aby przejść do przestrzeni roboczej.',
        it: 'Premi il pulsante qui sotto per continuare verso la tua area di lavoro.',
        sk: 'Naciśnij przycisk poniżej, aby przejść do przestrzeni roboczej.',
        ja: '以下のボタンを押してワークスペースに進んでください。',
        ko: '아래 버튼을 눌러 워크스페이스로 계속하세요.',
        hi: 'अपने वर्कस्पेस पर जारी रखने के लिए नीचे दिए गए बटन को दबाएं।',
        nl: 'Druk op de knop hieronder om door te gaan naar uw werkruimte.',
        sv: 'Tryck på knappen nedan för att fortsätta till din arbetsyta.',
        vi: 'Nhấn nút bên dưới để tiếp tục đến không gian làm việc của bạn.',
        id: 'Tekan tombol di bawah untuk melanjutkan ke ruang kerja Anda.',
      }),
      summaryTitle: t({
        ru: 'Ваши настройки',
        en: 'Your setup',
        kk: 'Сіздің баптауларыңыз',
        de: 'Ihre Einstellungen',
        fr: 'Votre configuration',
        es: 'Tu configuración',
        pt: 'Sua configuração',
        tr: 'Kurulumunuz',
        uk: 'Ваші налаштування',
        zh: '您的设置',
        ar: 'إعداداتك',
        pl: 'Twoje ustawienia',
        it: 'La tua configurazione',
        sk: 'Twoje ustawienia',
        ja: 'あなたの設定',
        ko: '내 설정',
        hi: 'आपकी सेटिंग',
        nl: 'Uw installatie',
        sv: 'Din konfiguration',
        vi: 'Cài đặt của bạn',
        id: 'Pengaturan Anda',
      }),
      notSet: t({
        ru: 'не задано',
        en: 'not set',
        kk: 'орнатылмаған',
        de: 'nicht festgelegt',
        fr: 'non défini',
        es: 'no definido',
        pt: 'não definido',
        tr: 'ayarlanmadı',
        uk: 'не задано',
        zh: '未设置',
        ar: 'غير محدد',
        pl: 'nie ustawiono',
        it: 'non impostato',
        sk: 'nie ustawiono',
        ja: '未設定',
        ko: '설정되지 않음',
        hi: 'सेट नहीं',
        nl: 'niet ingesteld',
        sv: 'ej inställt',
        vi: 'chưa đặt',
        id: 'belum diatur',
      }),
      summary: {
        language: t({
          ru: 'Язык: {value}',
          en: 'Language: {value}',
          kk: 'Тіл: {value}',
          de: 'Sprache: {value}',
          fr: 'Langue : {value}',
          es: 'Idioma: {value}',
          pt: 'Idioma: {value}',
          tr: 'Dil: {value}',
          uk: 'Мова: {value}',
          zh: '语言：{value}',
          ar: 'اللغة: {value}',
          pl: 'Język: {value}',
          it: 'Lingua: {value}',
          sk: 'Język: {value}',
          ja: '言語：{value}',
          ko: '언어: {value}',
          hi: 'भाषा: {value}',
          nl: 'Taal: {value}',
          sv: 'Språk: {value}',
          vi: 'Ngôn ngữ: {value}',
          id: 'Bahasa: {value}',
        }),
        timeZone: t({
          ru: 'Часовой пояс: {value}',
          en: 'Timezone: {value}',
          kk: 'Уақыт белдеуі: {value}',
          de: 'Zeitzone: {value}',
          fr: 'Fuseau horaire : {value}',
          es: 'Zona horaria: {value}',
          pt: 'Fuso horário: {value}',
          tr: 'Saat dilimi: {value}',
          uk: 'Часовий пояс: {value}',
          zh: '时区：{value}',
          ar: 'المنطقة الزمنية: {value}',
          pl: 'Strefa czasowa: {value}',
          it: 'Fuso orario: {value}',
          sk: 'Strefa czasowa: {value}',
          ja: 'タイムゾーン：{value}',
          ko: '시간대: {value}',
          hi: 'समय क्षेत्र: {value}',
          nl: 'Tijdzone: {value}',
          sv: 'Tidszon: {value}',
          vi: 'Múi giờ: {value}',
          id: 'Zona waktu: {value}',
        }),
        workspace: t({
          ru: 'Воркспейс: {value}',
          en: 'Workspace: {value}',
          kk: 'Жұмыс кеңістігі: {value}',
          de: 'Arbeitsbereich: {value}',
          fr: 'Espace de travail : {value}',
          es: 'Espacio de trabajo: {value}',
          pt: 'Workspace: {value}',
          tr: 'Çalışma alanı: {value}',
          uk: 'Воркспейс: {value}',
          zh: '工作区：{value}',
          ar: 'مساحة العمل: {value}',
          pl: 'Przestrzeń robocza: {value}',
          it: 'Area di lavoro: {value}',
          sk: 'Przestrzeń robocza: {value}',
          ja: 'ワークスペース：{value}',
          ko: '워크스페이스: {value}',
          hi: 'वर्कस्पेस: {value}',
          nl: 'Werkruimte: {value}',
          sv: 'Arbetsyta: {value}',
          vi: 'Không gian làm việc: {value}',
          id: 'Ruang kerja: {value}',
        }),
        currency: t({
          ru: 'Валюта: {value}',
          en: 'Currency: {value}',
          kk: 'Валюта: {value}',
          de: 'Währung: {value}',
          fr: 'Devise : {value}',
          es: 'Moneda: {value}',
          pt: 'Moeda: {value}',
          tr: 'Para birimi: {value}',
          uk: 'Валюта: {value}',
          zh: '货币：{value}',
          ar: 'العملة: {value}',
          pl: 'Waluta: {value}',
          it: 'Valuta: {value}',
          sk: 'Waluta: {value}',
          ja: '通貨：{value}',
          ko: '통화: {value}',
          hi: 'मुद्रा: {value}',
          nl: 'Valuta: {value}',
          sv: 'Valuta: {value}',
          vi: 'Tiền tệ: {value}',
          id: 'Mata uang: {value}',
        }),
        integrations: t({
          ru: 'Подключенные интеграции:',
          en: 'Connected integrations:',
          kk: 'Қосылған интеграциялар:',
          de: 'Verbundene Integrationen:',
          fr: 'Intégrations connectées :',
          es: 'Integraciones conectadas:',
          pt: 'Integrações conectadas:',
          tr: 'Bağlı entegrasyonlar:',
          uk: 'Підключені інтеграції:',
          zh: '已连接的集成：',
          ar: 'التكاملات المتصلة:',
          pl: 'Połączone integracje:',
          it: 'Integrazioni connesse:',
          sk: 'Połączone integracje:',
          ja: '接続済み統合：',
          ko: '연결된 통합:',
          hi: 'कनेक्टेड इंटीग्रेशन:',
          nl: 'Verbonden integraties:',
          sv: 'Anslutna integrationer:',
          vi: 'Tích hợp đã kết nối:',
          id: 'Integrasi yang terhubung:',
        }),
        background: t({
          ru: 'Фон воркспейса: {value}',
          en: 'Workspace background: {value}',
          kk: 'Жұмыс кеңістігінің фоны: {value}',
          de: 'Hintergrund des Arbeitsbereichs: {value}',
          fr: "Arrière-plan de l'espace de travail : {value}",
          es: 'Fondo del espacio de trabajo: {value}',
          pt: 'Plano de fundo do workspace: {value}',
          tr: 'Çalışma alanı arka planı: {value}',
          uk: 'Фон воркспейсу: {value}',
          zh: '工作区背景：{value}',
          ar: 'خلفية مساحة العمل: {value}',
          pl: 'Tło przestrzeni roboczej: {value}',
          it: 'Sfondo area di lavoro: {value}',
          sk: 'Tło przestrzeni roboczej: {value}',
          ja: 'ワークスペースの背景：{value}',
          ko: '워크스페이스 배경: {value}',
          hi: 'वर्कस्पेस की पृष्ठभूमि: {value}',
          nl: 'Werkruimte achtergrond: {value}',
          sv: 'Arbetsytans bakgrund: {value}',
          vi: 'Nền không gian làm việc: {value}',
          id: 'Latar belakang ruang kerja: {value}',
        }),
      },
      backgroundSet: t({
        ru: 'установлен',
        en: 'set',
        kk: 'орнатылған',
        de: 'festgelegt',
        fr: 'défini',
        es: 'definido',
        pt: 'definido',
        tr: 'ayarlandı',
        uk: 'встановлено',
        zh: '已设置',
        ar: 'محدد',
        pl: 'ustawiono',
        it: 'impostato',
        sk: 'ustawiono',
        ja: '設定済み',
        ko: '설정됨',
        hi: 'सेट',
        nl: 'ingesteld',
        sv: 'angiven',
        vi: 'đã đặt',
        id: 'telah diatur',
      }),
      noIntegrations: t({
        ru: 'Интеграции не подключены',
        en: 'No integrations connected',
        kk: 'Интеграциялар қосылмаған',
        de: 'Keine Integrationen verbunden',
        fr: 'Aucune intégration connectée',
        es: 'No hay integraciones conectadas',
        pt: 'Nenhuma integração conectada',
        tr: 'Bağlı entegrasyon yok',
        uk: 'Інтеграції не підключені',
        zh: '没有已连接的集成',
        ar: 'لا توجد تكاملات متصلة',
        pl: 'Brak połączonych integracji',
        it: 'Nessuna integrazione connessa',
        sk: 'Brak połączonych integracji',
        ja: '接続済みの統合はありません',
        ko: '연결된 통합이 없습니다',
        hi: 'कोई इंटीग्रेशन कनेक्टेड नहीं',
        nl: 'Geen integraties verbonden',
        sv: 'Inga integrationer anslutna',
        vi: 'Không có tích hợp nào được kết nối',
        id: 'Tidak ada integrasi yang terhubung',
      }),
    },
    navigation: {
      back: t({
        ru: 'Назад',
        en: 'Back',
        kk: 'Артқа',
        de: 'Zurück',
        fr: 'Retour',
        es: 'Atrás',
        pt: 'Voltar',
        tr: 'Geri',
        uk: 'Назад',
        zh: '返回',
        ar: 'رجوع',
        pl: 'Wstecz',
        it: 'Indietro',
        sk: 'Wstecz',
        ja: '戻る',
        ko: '뒤로',
        hi: 'वापस',
        nl: 'Terug',
        sv: 'Tillbaka',
        vi: 'Quay lại',
        id: 'Kembali',
      }),
      next: t({
        ru: 'Далее',
        en: 'Next',
        kk: 'Келесі',
        de: 'Weiter',
        fr: 'Suivant',
        es: 'Siguiente',
        pt: 'Próximo',
        tr: 'İleri',
        uk: 'Далі',
        zh: '下一步',
        ar: 'التالي',
        pl: 'Dalej',
        it: 'Avanti',
        sk: 'Dalej',
        ja: '次へ',
        ko: '다음',
        hi: 'अगला',
        nl: 'Volgende',
        sv: 'Nästa',
        vi: 'Tiếp theo',
        id: 'Berikutnya',
      }),
      finish: t({
        ru: 'Начать работу',
        en: 'Start using app',
        kk: 'Жұмысты бастау',
        de: 'App starten',
        fr: "Commencer à utiliser l'application",
        es: 'Empezar a usar la app',
        pt: 'Começar a usar o app',
        tr: 'Uygulamayı kullanmaya başla',
        uk: 'Почати роботу',
        zh: '开始使用应用',
        ar: 'ابدأ استخدام التطبيق',
        pl: 'Zacznij korzystać z aplikacji',
        it: "Inizia a usare l'app",
        sk: 'Zacznij korzystać z aplikacji',
        ja: 'アプリの使用を開始する',
        ko: '앱 사용 시작',
        hi: 'ऐप का उपयोग शुरू करें',
        nl: 'Begin met het gebruik van de app',
        sv: 'Börja använda appen',
        vi: 'Bắt đầu sử dụng ứng dụng',
        id: 'Mulai menggunakan aplikasi',
      }),
      skip: t({
        ru: 'Пропустить',
        en: 'Skip',
        kk: 'Өткізу',
        de: 'Überspringen',
        fr: 'Passer',
        es: 'Omitir',
        pt: 'Pular',
        tr: 'Atla',
        uk: 'Пропустити',
        zh: '跳过',
        ar: 'تخطي',
        pl: 'Pomiń',
        it: 'Salta',
        sk: 'Pomiń',
        ja: 'スキップ',
        ko: '건너뛰기',
        hi: 'छोड़ें',
        nl: 'Overslaan',
        sv: 'Hoppa över',
        vi: 'Bỏ qua',
        id: 'Lewati',
      }),
      skipAll: t({
        ru: 'Пропустить все',
        en: 'Skip all',
        kk: 'Барлығын өткізу',
        de: 'Alle überspringen',
        fr: 'Tout passer',
        es: 'Omitir todo',
        pt: 'Pular tudo',
        tr: 'Tümünü atla',
        uk: 'Пропустити все',
        zh: '全部跳过',
        ar: 'تخطي الكل',
        pl: 'Pomiń wszystko',
        it: 'Salta tutto',
        sk: 'Pomiń wszystko',
        ja: 'すべてスキップ',
        ko: '모두 건너뛰기',
        hi: 'सब छोड़ें',
        nl: 'Alles overslaan',
        sv: 'Hoppa över allt',
        vi: 'Bỏ qua tất cả',
        id: 'Lewati semua',
      }),
      saving: t({
        ru: 'Сохраняем...',
        en: 'Saving...',
        kk: 'Сақталуда...',
        de: 'Speichern...',
        fr: 'Enregistrement...',
        es: 'Guardando...',
        pt: 'Salvando...',
        tr: 'Kaydediliyor...',
        uk: 'Зберігаємо...',
        zh: '保存中...',
        ar: 'جارٍ الحفظ...',
        pl: 'Zapisywanie...',
        it: 'Salvataggio...',
        sk: 'Zapisywanie...',
        ja: '保存中...',
        ko: '저장 중...',
        hi: 'सहेजा जा रहा है...',
        nl: 'Opslaan...',
        sv: 'Sparar...',
        vi: 'Đang lưu...',
        id: 'Menyimpan...',
      }),
    },
    errors: {
      workspaceLoadFailed: t({
        ru: 'Не удалось загрузить данные воркспейса. Можно продолжить с настройками по умолчанию.',
        en: 'Failed to load workspace data. You can continue with default settings.',
        kk: 'Жұмыс кеңістігі деректерін жүктеу мүмкін болмады. Әдепкі баптаулармен жалғастыра аласыз.',
        de: 'Arbeitsbereichsdaten konnten nicht geladen werden. Sie können mit den Standardeinstellungen fortfahren.',
        fr: "Impossible de charger les données de l'espace de travail. Vous pouvez continuer avec les paramètres par défaut.",
        es: 'No se pudieron cargar los datos del espacio de trabajo. Puedes continuar con la configuración predeterminada.',
        pt: 'Falha ao carregar dados do workspace. Você pode continuar com as configurações padrão.',
        tr: 'Çalışma alanı verileri yüklenemedi. Varsayılan ayarlarla devam edebilirsiniz.',
        uk: 'Не вдалося завантажити дані воркспейсу. Можна продовжити з налаштуваннями за замовчуванням.',
        zh: '无法加载工作区数据。您可以使用默认设置继续。',
        ar: 'فشل تحميل بيانات مساحة العمل. يمكنك المتابعة بالإعدادات الافتراضية.',
        pl: 'Nie udało się załadować danych przestrzeni roboczej. Możesz kontynuować z ustawieniami domyślnymi.',
        it: "Impossibile caricare i dati dell'area di lavoro. Puoi continuare con le impostazioni predefinite.",
        sk: 'Nie udało się załadować danych przestrzeni roboczej. Możesz kontynuować z ustawieniami domyślnymi.',
        ja: 'ワークスペースデータの読み込みに失敗しました。デフォルト設定で続行できます。',
        ko: '워크스페이스 데이터 로드에 실패했습니다. 기본 설정으로 계속할 수 있습니다.',
        hi: 'वर्कस्पेस डेटा लोड करने में विफल। आप डिफ़ॉल्ट सेटिंग के साथ जारी रख सकते हैं।',
        nl: 'Werkruimtegegevens konden niet worden geladen. U kunt doorgaan met standaardinstellingen.',
        sv: 'Det gick inte att ladda arbetsytedata. Du kan fortsätta med standardinställningar.',
        vi: 'Không thể tải dữ liệu không gian làm việc. Bạn có thể tiếp tục với cài đặt mặc định.',
        id: 'Gagal memuat data ruang kerja. Anda dapat melanjutkan dengan pengaturan default.',
      }),
      completeFailed: t({
        ru: 'Не удалось завершить онбординг. Попробуйте еще раз.',
        en: 'Failed to complete onboarding. Please try again.',
        kk: 'Онбордингті аяқтау мүмкін болмады. Қайта көріңіз.',
        de: 'Onboarding konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
        fr: "Impossible de terminer l'intégration. Veuillez réessayer.",
        es: 'No se pudo completar el proceso de incorporación. Por favor, inténtalo de nuevo.',
        pt: 'Falha ao concluir o onboarding. Por favor, tente novamente.',
        tr: 'Katılım süreci tamamlanamadı. Lütfen tekrar deneyin.',
        uk: 'Не вдалося завершити онбординг. Спробуйте ще раз.',
        zh: '无法完成引导流程。请重试。',
        ar: 'فشل إكمال عملية التهيئة. يرجى المحاولة مرة أخرى.',
        pl: 'Nie udało się ukończyć procesu wdrożenia. Spróbuj ponownie.',
        it: "Impossibile completare l'onboarding. Riprova.",
        sk: 'Nie udało się ukończyć procesu wdrożenia. Spróbuj ponownie.',
        ja: 'オンボーディングの完了に失敗しました。もう一度お試しください。',
        ko: '온보딩 완료에 실패했습니다. 다시 시도해 주세요.',
        hi: 'ऑनबोर्डिंग पूर्ण करने में विफल। कृपया पुनः प्रयास करें।',
        nl: 'Onboarding kon niet worden voltooid. Probeer het opnieuw.',
        sv: 'Det gick inte att slutföra introduktionen. Försök igen.',
        vi: 'Không thể hoàn thành quá trình onboarding. Vui lòng thử lại.',
        id: 'Gagal menyelesaikan onboarding. Silakan coba lagi.',
      }),
    },
  },
} satisfies Dictionary;

export default content;
