import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'onboardingPage',
  content: {
    progressLabel: t({
      ru: 'Шаг {current} из {total}',
      en: 'Step {current} of {total}',
      kk: '{total} қадамның {current}-қадамы',
      de: 'Schritt {current} von {total}',
      fr: 'Étape {current} sur {total}',
      es: 'Paso {current} de {total}',
      pt: 'Passo {current} de {total}',
      tr: '{total} adımdan {current}. adım',
      uk: 'Крок {current} з {total}',
      zh: '第 {current} 步，共 {total} 步',
      ar: 'الخطوة {current} من {total}',
      pl: 'Krok {current} z {total}',
      it: 'Passo {current} di {total}',
    }),
    steps: {
      welcome: t({ ru: 'Старт', en: 'Start', kk: 'Бастау', de: 'Start', fr: 'Démarrer', es: 'Inicio', pt: 'Início', tr: 'Başlangıç', uk: 'Старт', zh: '开始', ar: 'البداية', pl: 'Start', it: 'Inizio' }),
      language: t({ ru: 'Язык', en: 'Language', kk: 'Тіл', de: 'Sprache', fr: 'Langue', es: 'Idioma', pt: 'Idioma', tr: 'Dil', uk: 'Мова', zh: '语言', ar: 'اللغة', pl: 'Język', it: 'Lingua' }),
      workspace: t({ ru: 'Воркспейс', en: 'Workspace', kk: 'Жұмыс кеңістігі', de: 'Arbeitsbereich', fr: 'Espace de travail', es: 'Espacio de trabajo', pt: 'Workspace', tr: 'Çalışma alanı', uk: 'Воркспейс', zh: '工作区', ar: 'مساحة العمل', pl: 'Przestrzeń robocza', it: 'Area di lavoro' }),
      integrations: t({ ru: 'Интеграции', en: 'Integrations', kk: 'Интеграциялар', de: 'Integrationen', fr: 'Intégrations', es: 'Integraciones', pt: 'Integrações', tr: 'Entegrasyonlar', uk: 'Інтеграції', zh: '集成', ar: 'التكاملات', pl: 'Integracje', it: 'Integrazioni' }),
      completion: t({ ru: 'Готово', en: 'Done', kk: 'Дайын', de: 'Fertig', fr: 'Terminé', es: 'Listo', pt: 'Concluído', tr: 'Tamamlandı', uk: 'Готово', zh: '完成', ar: 'تم', pl: 'Gotowe', it: 'Completato' }),
    },
    welcome: {
      badge: t({ ru: 'Добро пожаловать', en: 'Welcome', kk: 'Қош келдіңіз', de: 'Willkommen', fr: 'Bienvenue', es: 'Bienvenido', pt: 'Bem-vindo', tr: 'Hoş geldiniz', uk: 'Ласкаво просимо', zh: '欢迎', ar: 'مرحبًا', pl: 'Witamy', it: 'Benvenuto' }),
      title: t({
        ru: 'Настроим Lumio под вас',
        en: "Let's tailor Lumio for you",
        kk: 'Lumio-ны сізге бейімдейік',
        de: 'Passen wir Lumio für Sie an',
        fr: 'Personnalisons Lumio pour vous',
        es: 'Personalicemos Lumio para ti',
        pt: 'Vamos personalizar o Lumio para você',
        tr: 'Lumio\'yu sizin için özelleştirelim',
        uk: 'Налаштуємо Lumio для вас',
        zh: '让我们为您定制 Lumio',
        ar: 'لنخصص Lumio لك',
        pl: 'Dostosujmy Lumio dla Ciebie',
        it: 'Personalizziamo Lumio per te',
      }),
      subtitle: t({
        ru: 'Это займет пару минут: выберем язык, базовую валюту и подключим нужные интеграции.',
        en: 'This takes a couple of minutes: choose language, default currency, and integrations.',
        kk: 'Бұл бірнеше минут алады: тілді, негізгі валютаны және интеграцияларды таңдаңыз.',
        de: 'Das dauert ein paar Minuten: Sprache, Standardwährung und Integrationen auswählen.',
        fr: 'Cela prend quelques minutes : choisissez la langue, la devise par défaut et les intégrations.',
        es: 'Esto lleva un par de minutos: elige idioma, moneda predeterminada e integraciones.',
        pt: 'Isso leva alguns minutos: escolha idioma, moeda padrão e integrações.',
        tr: 'Bu birkaç dakika sürer: dil, varsayılan para birimi ve entegrasyonları seçin.',
        uk: 'Це займе кілька хвилин: оберіть мову, базову валюту та підключіть потрібні інтеграції.',
        zh: '这需要几分钟：选择语言、默认货币和集成。',
        ar: 'يستغرق ذلك بضع دقائق: اختر اللغة والعملة الافتراضية والتكاملات.',
        pl: 'To zajmuje kilka minut: wybierz język, domyślną walutę i integracje.',
        it: 'Ci vogliono un paio di minuti: scegli lingua, valuta predefinita e integrazioni.',
      }),
      nextTitle: t({
        ru: 'Что будет дальше',
        en: 'What happens next',
        kk: 'Келесі қадамдар',
        de: 'Was als nächstes passiert',
        fr: 'Ce qui se passe ensuite',
        es: 'Qué pasa después',
        pt: 'O que acontece a seguir',
        tr: 'Bundan sonra ne olur',
        uk: 'Що буде далі',
        zh: '接下来发生什么',
        ar: 'ماذا سيحدث بعد ذلك',
        pl: 'Co się dzieje dalej',
        it: 'Cosa succede dopo',
      }),
      nextSteps: {
        language: t({
          ru: 'Выберите язык интерфейса и часовой пояс',
          en: 'Pick interface language and timezone',
          kk: 'Интерфейс тілі мен уақыт белдеуін таңдаңыз',
          de: 'Schnittstellensprache und Zeitzone wählen',
          fr: 'Choisir la langue de l\'interface et le fuseau horaire',
          es: 'Elige el idioma de la interfaz y la zona horaria',
          pt: 'Escolha o idioma da interface e o fuso horário',
          tr: 'Arayüz dili ve saat dilimi seçin',
          uk: 'Оберіть мову інтерфейсу та часовий пояс',
          zh: '选择界面语言和时区',
          ar: 'اختر لغة الواجهة والمنطقة الزمنية',
          pl: 'Wybierz język interfejsu i strefę czasową',
          it: 'Scegli la lingua dell\'interfaccia e il fuso orario',
        }),
        workspace: t({
          ru: 'Настройте название, валюту и фон воркспейса',
          en: 'Set workspace name, currency, and background',
          kk: 'Жұмыс кеңістігінің атауын, валютасын және фонын орнатыңыз',
          de: 'Name, Währung und Hintergrund des Arbeitsbereichs festlegen',
          fr: 'Définir le nom, la devise et l\'arrière-plan de l\'espace de travail',
          es: 'Establece el nombre, moneda y fondo del espacio de trabajo',
          pt: 'Defina o nome, moeda e plano de fundo do workspace',
          tr: 'Çalışma alanı adını, para birimini ve arka planı ayarlayın',
          uk: 'Налаштуйте назву, валюту та фон воркспейсу',
          zh: '设置工作区名称、货币和背景',
          ar: 'حدد اسم مساحة العمل والعملة والخلفية',
          pl: 'Ustaw nazwę, walutę i tło przestrzeni roboczej',
          it: 'Imposta nome, valuta e sfondo dell\'area di lavoro',
        }),
        integrations: t({
          ru: 'Подключите интеграции, которые нужны сейчас',
          en: 'Connect integrations you need right now',
          kk: 'Қазір керек интеграцияларды қосыңыз',
          de: 'Jetzt benötigte Integrationen verbinden',
          fr: 'Connectez les intégrations dont vous avez besoin maintenant',
          es: 'Conecta las integraciones que necesitas ahora',
          pt: 'Conecte as integrações que você precisa agora',
          tr: 'Şu anda ihtiyacınız olan entegrasyonları bağlayın',
          uk: 'Підключіть інтеграції, які потрібні зараз',
          zh: '立即连接您需要的集成',
          ar: 'اربط التكاملات التي تحتاجها الآن',
          pl: 'Połącz integracje, których potrzebujesz teraz',
          it: 'Collega le integrazioni di cui hai bisogno ora',
        }),
      },
      points: {
        fastSetup: t({
          ru: 'Быстрая первоначальная настройка',
          en: 'Quick initial setup',
          kk: 'Жылдам бастапқы баптау',
          de: 'Schnelle Ersteinrichtung',
          fr: 'Configuration initiale rapide',
          es: 'Configuración inicial rápida',
          pt: 'Configuração inicial rápida',
          tr: 'Hızlı ilk kurulum',
          uk: 'Швидке початкове налаштування',
          zh: '快速初始设置',
          ar: 'إعداد أولي سريع',
          pl: 'Szybka konfiguracja początkowa',
          it: 'Configurazione iniziale rapida',
        }),
        integrations: t({
          ru: 'Подключение сервисов в один клик',
          en: 'Connect services in one click',
          kk: 'Сервистерді бір шерту арқылы қосу',
          de: 'Dienste mit einem Klick verbinden',
          fr: 'Connecter des services en un clic',
          es: 'Conectar servicios en un clic',
          pt: 'Conectar serviços com um clique',
          tr: 'Tek tıkla hizmetleri bağlayın',
          uk: 'Підключення сервісів в один клік',
          zh: '一键连接服务',
          ar: 'ربط الخدمات بنقرة واحدة',
          pl: 'Połącz usługi jednym kliknięciem',
          it: 'Connetti servizi in un clic',
        }),
        control: t({
          ru: 'Понятный старт и полный контроль',
          en: 'Clear start and full control',
          kk: 'Түсінікті бастау және толық бақылау',
          de: 'Klarer Start und volle Kontrolle',
          fr: 'Démarrage clair et contrôle total',
          es: 'Inicio claro y control total',
          pt: 'Início claro e controle total',
          tr: 'Net başlangıç ve tam kontrol',
          uk: 'Зрозумілий старт і повний контроль',
          zh: '清晰的开始和完全控制',
          ar: 'بداية واضحة وتحكم كامل',
          pl: 'Jasny start i pełna kontrola',
          it: 'Inizio chiaro e pieno controllo',
        }),
      },
    },
    language: {
      title: t({
        ru: 'Язык и часовой пояс',
        en: 'Language and timezone',
        kk: 'Тіл және уақыт белдеуі',
        de: 'Sprache und Zeitzone',
        fr: 'Langue et fuseau horaire',
        es: 'Idioma y zona horaria',
        pt: 'Idioma e fuso horário',
        tr: 'Dil ve saat dilimi',
        uk: 'Мова та часовий пояс',
        zh: '语言和时区',
        ar: 'اللغة والمنطقة الزمنية',
        pl: 'Język i strefa czasowa',
        it: 'Lingua e fuso orario',
      }),
      subtitle: t({
        ru: 'Выберите удобный язык интерфейса и ваш часовой пояс для корректного времени в отчетах.',
        en: 'Choose your preferred interface language and timezone for accurate report timestamps.',
        kk: 'Есептердегі уақыт дұрыс болуы үшін интерфейс тілін және уақыт белдеуін таңдаңыз.',
        de: 'Wählen Sie Ihre bevorzugte Schnittstellensprache und Zeitzone für korrekte Berichtszeitstempel.',
        fr: 'Choisissez votre langue d\'interface préférée et votre fuseau horaire pour des horodatages précis dans les rapports.',
        es: 'Elige tu idioma de interfaz preferido y zona horaria para marcas de tiempo precisas en los informes.',
        pt: 'Escolha seu idioma de interface preferido e fuso horário para timestamps precisos nos relatórios.',
        tr: 'Raporlarda doğru zaman damgaları için tercih ettiğiniz arayüz dilini ve saat dilimini seçin.',
        uk: 'Оберіть зручну мову інтерфейсу та часовий пояс для коректного часу у звітах.',
        zh: '选择您偏好的界面语言和时区，以确保报告时间戳准确。',
        ar: 'اختر لغة الواجهة المفضلة والمنطقة الزمنية لطوابع زمنية دقيقة في التقارير.',
        pl: 'Wybierz preferowany język interfejsu i strefę czasową dla dokładnych znaczników czasu w raportach.',
        it: 'Scegli la tua lingua dell\'interfaccia preferita e il fuso orario per timestamp accurati nei report.',
      }),
      localeLabel: t({ ru: 'Язык', en: 'Language', kk: 'Тіл', de: 'Sprache', fr: 'Langue', es: 'Idioma', pt: 'Idioma', tr: 'Dil', uk: 'Мова', zh: '语言', ar: 'اللغة', pl: 'Język', it: 'Lingua' }),
      localeOptions: {
        ru: t({ ru: 'Русский', en: 'Russian', kk: 'Орыс тілі', de: 'Russisch', fr: 'Russe', es: 'Ruso', pt: 'Russo', tr: 'Rusça', uk: 'Російська', zh: '俄语', ar: 'الروسية', pl: 'Rosyjski', it: 'Russo' }),
        en: t({ ru: 'English', en: 'English', kk: 'English', de: 'Englisch', fr: 'Anglais', es: 'Inglés', pt: 'Inglês', tr: 'İngilizce', uk: 'Англійська', zh: '英语', ar: 'الإنجليزية', pl: 'Angielski', it: 'Inglese' }),
        kk: t({ ru: 'Қазақша', en: 'Kazakh', kk: 'Қазақша', de: 'Kasachisch', fr: 'Kazakh', es: 'Kazajo', pt: 'Cazaque', tr: 'Kazakça', uk: 'Казахська', zh: '哈萨克语', ar: 'الكازاخية', pl: 'Kazachski', it: 'Kazaco' }),
      },
      timeZoneLabel: t({ ru: 'Часовой пояс', en: 'Timezone', kk: 'Уақыт белдеуі', de: 'Zeitzone', fr: 'Fuseau horaire', es: 'Zona horaria', pt: 'Fuso horário', tr: 'Saat dilimi', uk: 'Часовий пояс', zh: '时区', ar: 'المنطقة الزمنية', pl: 'Strefa czasowa', it: 'Fuso orario' }),
      timeZonePlaceholder: t({
        ru: 'Выберите часовой пояс',
        en: 'Select timezone',
        kk: 'Уақыт белдеуін таңдаңыз',
        de: 'Zeitzone auswählen',
        fr: 'Sélectionner le fuseau horaire',
        es: 'Seleccionar zona horaria',
        pt: 'Selecionar fuso horário',
        tr: 'Saat dilimi seçin',
        uk: 'Оберіть часовий пояс',
        zh: '选择时区',
        ar: 'اختر المنطقة الزمنية',
        pl: 'Wybierz strefę czasową',
        it: 'Seleziona fuso orario',
      }),
      timeZoneHint: t({
        ru: 'Вы всегда сможете изменить это позже в настройках профиля.',
        en: 'You can always change this later in profile settings.',
        kk: 'Мұны кейін профиль баптауларында өзгерте аласыз.',
        de: 'Sie können dies jederzeit in den Profileinstellungen ändern.',
        fr: 'Vous pouvez toujours modifier cela dans les paramètres du profil.',
        es: 'Siempre puedes cambiar esto más tarde en la configuración del perfil.',
        pt: 'Você sempre pode alterar isso nas configurações do perfil.',
        tr: 'Bunu daha sonra profil ayarlarından değiştirebilirsiniz.',
        uk: 'Ви завжди зможете змінити це пізніше в налаштуваннях профілю.',
        zh: '您可以随时在个人资料设置中更改此项。',
        ar: 'يمكنك دائمًا تغيير هذا لاحقًا في إعدادات الملف الشخصي.',
        pl: 'Zawsze możesz to zmienić później w ustawieniach profilu.',
        it: 'Puoi sempre cambiarlo in seguito nelle impostazioni del profilo.',
      }),
      timeZoneNoOptions: t({
        ru: 'Часовые пояса не найдены',
        en: 'No matching timezones found',
        kk: 'Сәйкес уақыт белдеуі табылмады',
        de: 'Keine passenden Zeitzonen gefunden',
        fr: 'Aucun fuseau horaire correspondant trouvé',
        es: 'No se encontraron zonas horarias coincidentes',
        pt: 'Nenhum fuso horário correspondente encontrado',
        tr: 'Eşleşen saat dilimi bulunamadı',
        uk: 'Відповідних часових поясів не знайдено',
        zh: '未找到匹配的时区',
        ar: 'لم يتم العثور على مناطق زمنية مطابقة',
        pl: 'Nie znaleziono pasujących stref czasowych',
        it: 'Nessun fuso orario corrispondente trovato',
      }),
    },
    workspace: {
      title: t({
        ru: 'Настройка первого воркспейса',
        en: 'Set up your first workspace',
        kk: 'Алғашқы жұмыс кеңістігін баптау',
        de: 'Richten Sie Ihren ersten Arbeitsbereich ein',
        fr: 'Configurez votre premier espace de travail',
        es: 'Configura tu primer espacio de trabajo',
        pt: 'Configure seu primeiro workspace',
        tr: 'İlk çalışma alanınızı kurun',
        uk: 'Налаштування першого воркспейсу',
        zh: '设置您的第一个工作区',
        ar: 'إعداد مساحة العمل الأولى',
        pl: 'Skonfiguruj pierwszą przestrzeń roboczą',
        it: 'Configura la tua prima area di lavoro',
      }),
      subtitle: t({
        ru: 'Задайте название и валюту по умолчанию для корректного учета данных.',
        en: 'Set workspace name and default currency for accurate data tracking.',
        kk: 'Деректерді дұрыс жүргізу үшін жұмыс кеңістігінің атауын және негізгі валютаны орнатыңыз.',
        de: 'Legen Sie den Namen des Arbeitsbereichs und die Standardwährung für genaue Datenverfolgung fest.',
        fr: 'Définissez le nom de l\'espace de travail et la devise par défaut pour un suivi précis des données.',
        es: 'Establece el nombre del espacio de trabajo y la moneda predeterminada para un seguimiento preciso de datos.',
        pt: 'Defina o nome do workspace e a moeda padrão para rastreamento preciso de dados.',
        tr: 'Doğru veri takibi için çalışma alanı adını ve varsayılan para birimini ayarlayın.',
        uk: 'Задайте назву та валюту за замовчуванням для коректного обліку даних.',
        zh: '设置工作区名称和默认货币，以便准确跟踪数据。',
        ar: 'حدد اسم مساحة العمل والعملة الافتراضية لتتبع البيانات بدقة.',
        pl: 'Ustaw nazwę przestrzeni roboczej i domyślną walutę dla dokładnego śledzenia danych.',
        it: 'Imposta il nome dell\'area di lavoro e la valuta predefinita per un monitoraggio preciso dei dati.',
      }),
      nameLabel: t({
        ru: 'Название воркспейса',
        en: 'Workspace name',
        kk: 'Жұмыс кеңістігінің атауы',
        de: 'Name des Arbeitsbereichs',
        fr: 'Nom de l\'espace de travail',
        es: 'Nombre del espacio de trabajo',
        pt: 'Nome do workspace',
        tr: 'Çalışma alanı adı',
        uk: 'Назва воркспейсу',
        zh: '工作区名称',
        ar: 'اسم مساحة العمل',
        pl: 'Nazwa przestrzeni roboczej',
        it: 'Nome dell\'area di lavoro',
      }),
      namePlaceholder: t({
        ru: 'Например: My Company workspace',
        en: 'For example: My Company workspace',
        kk: 'Мысалы: My Company workspace',
        de: 'Zum Beispiel: My Company workspace',
        fr: 'Par exemple : My Company workspace',
        es: 'Por ejemplo: My Company workspace',
        pt: 'Por exemplo: My Company workspace',
        tr: 'Örneğin: My Company workspace',
        uk: 'Наприклад: My Company workspace',
        zh: '例如：My Company workspace',
        ar: 'مثال: My Company workspace',
        pl: 'Na przykład: My Company workspace',
        it: 'Ad esempio: My Company workspace',
      }),
      currencyHint: t({
        ru: 'Эта валюта будет использоваться по умолчанию при создании новых записей.',
        en: 'This currency will be used by default for new records.',
        kk: 'Бұл валюта жаңа жазбалар үшін әдепкі ретінде қолданылады.',
        de: 'Diese Währung wird standardmäßig für neue Datensätze verwendet.',
        fr: 'Cette devise sera utilisée par défaut pour les nouveaux enregistrements.',
        es: 'Esta moneda se usará de forma predeterminada para nuevos registros.',
        pt: 'Esta moeda será usada por padrão para novos registros.',
        tr: 'Bu para birimi yeni kayıtlar için varsayılan olarak kullanılacaktır.',
        uk: 'Ця валюта буде використовуватись за замовчуванням при створенні нових записів.',
        zh: '此货币将作为新记录的默认货币。',
        ar: 'ستُستخدم هذه العملة افتراضيًا للسجلات الجديدة.',
        pl: 'Ta waluta będzie używana domyślnie dla nowych rekordów.',
        it: 'Questa valuta verrà utilizzata per impostazione predefinita per i nuovi record.',
      }),
      currencyPickerTitle: t({
        ru: 'Выберите валюту',
        en: 'Select a currency',
        kk: 'Валютаны таңдаңыз',
        de: 'Währung auswählen',
        fr: 'Sélectionner une devise',
        es: 'Seleccionar una moneda',
        pt: 'Selecionar uma moeda',
        tr: 'Para birimi seçin',
        uk: 'Оберіть валюту',
        zh: '选择货币',
        ar: 'اختر العملة',
        pl: 'Wybierz walutę',
        it: 'Seleziona una valuta',
      }),
      currencyPickerSubtitle: t({
        ru: 'Найдите и выберите валюту, которая будет использоваться по умолчанию.',
        en: 'Find and select the currency that will be used by default.',
        kk: 'Әдепкі бойынша қолданылатын валютаны тауып таңдаңыз.',
        de: 'Suchen und wählen Sie die Währung, die standardmäßig verwendet wird.',
        fr: 'Trouvez et sélectionnez la devise qui sera utilisée par défaut.',
        es: 'Busca y selecciona la moneda que se usará de forma predeterminada.',
        pt: 'Encontre e selecione a moeda que será usada por padrão.',
        tr: 'Varsayılan olarak kullanılacak para birimini bulun ve seçin.',
        uk: 'Знайдіть і оберіть валюту, яка буде використовуватись за замовчуванням.',
        zh: '查找并选择将作为默认使用的货币。',
        ar: 'ابحث عن العملة التي ستُستخدم افتراضيًا وحددها.',
        pl: 'Znajdź i wybierz walutę, która będzie używana domyślnie.',
        it: 'Trova e seleziona la valuta che verrà utilizzata per impostazione predefinita.',
      }),
      backgroundLabel: t({
        ru: 'Фон воркспейса',
        en: 'Workspace background',
        kk: 'Жұмыс кеңістігінің фоны',
        de: 'Hintergrund des Arbeitsbereichs',
        fr: 'Arrière-plan de l\'espace de travail',
        es: 'Fondo del espacio de trabajo',
        pt: 'Plano de fundo do workspace',
        tr: 'Çalışma alanı arka planı',
        uk: 'Фон воркспейсу',
        zh: '工作区背景',
        ar: 'خلفية مساحة العمل',
        pl: 'Tło przestrzeni roboczej',
        it: 'Sfondo dell\'area di lavoro',
      }),
      customBackgroundLabel: t({
        ru: 'Своя картинка (URL)',
        en: 'Custom image (URL)',
        kk: 'Жеке сурет (URL)',
        de: 'Eigenes Bild (URL)',
        fr: 'Image personnalisée (URL)',
        es: 'Imagen personalizada (URL)',
        pt: 'Imagem personalizada (URL)',
        tr: 'Özel görsel (URL)',
        uk: 'Власне зображення (URL)',
        zh: '自定义图片（URL）',
        ar: 'صورة مخصصة (URL)',
        pl: 'Własny obraz (URL)',
        it: 'Immagine personalizzata (URL)',
      }),
      customBackgroundPlaceholder: t({
        ru: 'https://example.com/my-image.jpg',
        en: 'https://example.com/my-image.jpg',
        kk: 'https://example.com/my-image.jpg',
        de: 'https://example.com/my-image.jpg',
        fr: 'https://example.com/my-image.jpg',
        es: 'https://example.com/my-image.jpg',
        pt: 'https://example.com/my-image.jpg',
        tr: 'https://example.com/my-image.jpg',
        uk: 'https://example.com/my-image.jpg',
        zh: 'https://example.com/my-image.jpg',
        ar: 'https://example.com/my-image.jpg',
        pl: 'https://example.com/my-image.jpg',
        it: 'https://example.com/my-image.jpg',
      }),
      customBackgroundHint: t({
        ru: 'Можно вставить ссылку на свою картинку или выбрать одну из готовых ниже.',
        en: 'Paste your own image URL or choose one of the presets below.',
        kk: 'Өз суретіңіздің URL сілтемесін енгізіңіз немесе дайын нұсқалардың бірін таңдаңыз.',
        de: 'Fügen Sie Ihre eigene Bild-URL ein oder wählen Sie eine der Voreinstellungen unten.',
        fr: 'Collez l\'URL de votre propre image ou choisissez l\'un des préréglages ci-dessous.',
        es: 'Pega la URL de tu propia imagen o elige uno de los ajustes preestablecidos a continuación.',
        pt: 'Cole a URL da sua própria imagem ou escolha uma das predefinições abaixo.',
        tr: 'Kendi görsel URL\'nizi yapıştırın veya aşağıdaki hazır seçeneklerden birini seçin.',
        uk: 'Можна вставити посилання на власне зображення або вибрати одне із готових нижче.',
        zh: '粘贴您自己的图片 URL，或从下面的预设中选择一个。',
        ar: 'الصق رابط صورتك الخاصة أو اختر أحد الإعدادات المسبقة أدناه.',
        pl: 'Wklej URL własnego obrazu lub wybierz jeden z gotowych poniżej.',
        it: 'Incolla l\'URL della tua immagine o scegli uno dei preset qui sotto.',
      }),
    },
    integrations: {
      title: t({
        ru: 'Подключите нужные интеграции',
        en: 'Connect your integrations',
        kk: 'Қажетті интеграцияларды қосыңыз',
        de: 'Verbinden Sie Ihre Integrationen',
        fr: 'Connectez vos intégrations',
        es: 'Conecta tus integraciones',
        pt: 'Conecte suas integrações',
        tr: 'Entegrasyonlarınızı bağlayın',
        uk: 'Підключіть потрібні інтеграції',
        zh: '连接您的集成',
        ar: 'اربط تكاملاتك',
        pl: 'Połącz swoje integracje',
        it: 'Collega le tue integrazioni',
      }),
      subtitle: t({
        ru: 'Выберите сервисы, которые хотите настроить сейчас. Можно подключить и позже.',
        en: 'Pick services you want to set up now. You can connect them later as well.',
        kk: 'Қазір баптағыңыз келетін сервистерді таңдаңыз. Кейін де қосуға болады.',
        de: 'Wählen Sie Dienste, die Sie jetzt einrichten möchten. Sie können diese auch später verbinden.',
        fr: 'Choisissez les services que vous souhaitez configurer maintenant. Vous pouvez les connecter plus tard également.',
        es: 'Elige los servicios que deseas configurar ahora. También puedes conectarlos más tarde.',
        pt: 'Escolha os serviços que deseja configurar agora. Você também pode conectá-los mais tarde.',
        tr: 'Şimdi kurmak istediğiniz hizmetleri seçin. Bunları daha sonra da bağlayabilirsiniz.',
        uk: 'Оберіть сервіси, які хочете налаштувати зараз. Можна підключити і пізніше.',
        zh: '选择您现在想要设置的服务。您也可以稍后连接它们。',
        ar: 'اختر الخدمات التي تريد إعدادها الآن. يمكنك ربطها لاحقًا أيضًا.',
        pl: 'Wybierz usługi, które chcesz skonfigurować teraz. Możesz je połączyć później.',
        it: 'Scegli i servizi che vuoi configurare ora. Puoi connetterli anche in seguito.',
      }),
      helper: t({
        ru: 'Если пропустить шаг, интеграции можно подключить в разделе Настройки -> Интеграции.',
        en: 'If you skip this step, you can connect integrations later in Settings -> Integrations.',
        kk: 'Бұл қадамды өткізіп жіберсеңіз, интеграцияларды кейін Баптаулар -> Интеграциялар бөлімінен қоса аласыз.',
        de: 'Wenn Sie diesen Schritt überspringen, können Sie Integrationen später unter Einstellungen -> Integrationen verbinden.',
        fr: 'Si vous sautez cette étape, vous pouvez connecter des intégrations plus tard dans Paramètres -> Intégrations.',
        es: 'Si omites este paso, puedes conectar integraciones más tarde en Configuración -> Integraciones.',
        pt: 'Se pular esta etapa, você pode conectar integrações mais tarde em Configurações -> Integrações.',
        tr: 'Bu adımı atlarsanız, entegrasyonları daha sonra Ayarlar -> Entegrasyonlar bölümünde bağlayabilirsiniz.',
        uk: 'Якщо пропустити крок, інтеграції можна підключити в розділі Налаштування -> Інтеграції.',
        zh: '如果跳过此步骤，可以稍后在设置 -> 集成中连接集成。',
        ar: 'إذا تخطيت هذه الخطوة، يمكنك ربط التكاملات لاحقًا في الإعدادات -> التكاملات.',
        pl: 'Jeśli pominiesz ten krok, możesz połączyć integracje później w Ustawieniach -> Integracje.',
        it: 'Se salti questo passaggio, puoi connettere le integrazioni in seguito in Impostazioni -> Integrazioni.',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить интеграцию. Попробуйте еще раз.',
        en: 'Failed to connect integration. Please try again.',
        kk: 'Интеграцияны қосу мүмкін болмады. Қайта көріңіз.',
        de: 'Integration konnte nicht verbunden werden. Bitte versuchen Sie es erneut.',
        fr: 'Impossible de connecter l\'intégration. Veuillez réessayer.',
        es: 'No se pudo conectar la integración. Por favor, inténtalo de nuevo.',
        pt: 'Falha ao conectar integração. Por favor, tente novamente.',
        tr: 'Entegrasyon bağlanamadı. Lütfen tekrar deneyin.',
        uk: 'Не вдалося підключити інтеграцію. Спробуйте ще раз.',
        zh: '无法连接集成。请重试。',
        ar: 'فشل ربط التكامل. يرجى المحاولة مرة أخرى.',
        pl: 'Nie udało się połączyć integracji. Spróbuj ponownie.',
        it: 'Impossibile connettere l\'integrazione. Riprova.',
      }),
      cards: {
        gmail: {
          title: t({ ru: 'Gmail', en: 'Gmail', kk: 'Gmail', de: 'Gmail', fr: 'Gmail', es: 'Gmail', pt: 'Gmail', tr: 'Gmail', uk: 'Gmail', zh: 'Gmail', ar: 'Gmail', pl: 'Gmail', it: 'Gmail' }),
          description: t({
            ru: 'Автоматически импортируйте чеки и инвойсы из Gmail.',
            en: 'Automatically import receipts and invoices from Gmail.',
            kk: 'Gmail-ден чектер мен инвойстарды автоматты түрде импорттаңыз.',
            de: 'Quittungen und Rechnungen automatisch aus Gmail importieren.',
            fr: 'Importez automatiquement les reçus et factures depuis Gmail.',
            es: 'Importa automáticamente recibos y facturas desde Gmail.',
            pt: 'Importe automaticamente recibos e faturas do Gmail.',
            tr: 'Gmail\'den makbuzları ve faturaları otomatik olarak içe aktarın.',
            uk: 'Автоматично імпортуйте чеки та інвойси з Gmail.',
            zh: '自动从 Gmail 导入收据和发票。',
            ar: 'استيراد الإيصالات والفواتير من Gmail تلقائيًا.',
            pl: 'Automatycznie importuj paragony i faktury z Gmaila.',
            it: 'Importa automaticamente ricevute e fatture da Gmail.',
          }),
          action: t({ ru: 'Подключить', en: 'Connect', kk: 'Қосу', de: 'Verbinden', fr: 'Connecter', es: 'Conectar', pt: 'Conectar', tr: 'Bağla', uk: 'Підключити', zh: '连接', ar: 'ربط', pl: 'Połącz', it: 'Connetti' }),
        },
        googleDrive: {
          title: t({ ru: 'Google Drive', en: 'Google Drive', kk: 'Google Drive', de: 'Google Drive', fr: 'Google Drive', es: 'Google Drive', pt: 'Google Drive', tr: 'Google Drive', uk: 'Google Drive', zh: 'Google Drive', ar: 'Google Drive', pl: 'Google Drive', it: 'Google Drive' }),
          description: t({
            ru: 'Синхронизируйте выписки с Google Drive и импортируйте файлы.',
            en: 'Sync statements with Google Drive and import files.',
            kk: 'Үзінділерді Google Drive-пен синхрондап, файлдарды импорттаңыз.',
            de: 'Kontoauszüge mit Google Drive synchronisieren und Dateien importieren.',
            fr: 'Synchronisez les relevés avec Google Drive et importez des fichiers.',
            es: 'Sincroniza extractos con Google Drive e importa archivos.',
            pt: 'Sincronize extratos com o Google Drive e importe arquivos.',
            tr: 'Hesap özetlerini Google Drive ile senkronize edin ve dosyaları içe aktarın.',
            uk: 'Синхронізуйте виписки з Google Drive та імпортуйте файли.',
            zh: '将对账单与 Google Drive 同步并导入文件。',
            ar: 'زامن كشوف الحساب مع Google Drive واستورد الملفات.',
            pl: 'Synchronizuj wyciągi z Google Drive i importuj pliki.',
            it: 'Sincronizza gli estratti conto con Google Drive e importa file.',
          }),
          action: t({ ru: 'Подключить', en: 'Connect', kk: 'Қосу', de: 'Verbinden', fr: 'Connecter', es: 'Conectar', pt: 'Conectar', tr: 'Bağla', uk: 'Підключити', zh: '连接', ar: 'ربط', pl: 'Połącz', it: 'Connetti' }),
        },
        dropbox: {
          title: t({ ru: 'Dropbox', en: 'Dropbox', kk: 'Dropbox', de: 'Dropbox', fr: 'Dropbox', es: 'Dropbox', pt: 'Dropbox', tr: 'Dropbox', uk: 'Dropbox', zh: 'Dropbox', ar: 'Dropbox', pl: 'Dropbox', it: 'Dropbox' }),
          description: t({
            ru: 'Синхронизируйте выписки с Dropbox и импортируйте файлы.',
            en: 'Sync statements with Dropbox and import files.',
            kk: 'Үзінділерді Dropbox-пен синхрондап, файлдарды импорттаңыз.',
            de: 'Kontoauszüge mit Dropbox synchronisieren und Dateien importieren.',
            fr: 'Synchronisez les relevés avec Dropbox et importez des fichiers.',
            es: 'Sincroniza extractos con Dropbox e importa archivos.',
            pt: 'Sincronize extratos com o Dropbox e importe arquivos.',
            tr: 'Hesap özetlerini Dropbox ile senkronize edin ve dosyaları içe aktarın.',
            uk: 'Синхронізуйте виписки з Dropbox та імпортуйте файли.',
            zh: '将对账单与 Dropbox 同步并导入文件。',
            ar: 'زامن كشوف الحساب مع Dropbox واستورد الملفات.',
            pl: 'Synchronizuj wyciągi z Dropbox i importuj pliki.',
            it: 'Sincronizza gli estratti conto con Dropbox e importa file.',
          }),
          action: t({ ru: 'Подключить', en: 'Connect', kk: 'Қосу', de: 'Verbinden', fr: 'Connecter', es: 'Conectar', pt: 'Conectar', tr: 'Bağla', uk: 'Підключити', zh: '连接', ar: 'ربط', pl: 'Połącz', it: 'Connetti' }),
        },
        googleSheets: {
          title: t({ ru: 'Google Sheets', en: 'Google Sheets', kk: 'Google Sheets', de: 'Google Sheets', fr: 'Google Sheets', es: 'Google Sheets', pt: 'Google Sheets', tr: 'Google Sheets', uk: 'Google Sheets', zh: 'Google Sheets', ar: 'Google Sheets', pl: 'Google Sheets', it: 'Google Sheets' }),
          description: t({
            ru: 'Отправляйте распарсенные транзакции в выбранную таблицу.',
            en: 'Send parsed transactions to a selected spreadsheet.',
            kk: 'Өңделген транзакцияларды таңдалған кестеге жіберіңіз.',
            de: 'Geparste Transaktionen an eine ausgewählte Tabelle senden.',
            fr: 'Envoyez les transactions analysées vers une feuille de calcul sélectionnée.',
            es: 'Envía transacciones procesadas a una hoja de cálculo seleccionada.',
            pt: 'Envie transações processadas para uma planilha selecionada.',
            tr: 'İşlenmiş işlemleri seçilen bir elektronik tabloya gönderin.',
            uk: 'Надсилайте оброблені транзакції у вибрану таблицю.',
            zh: '将解析的交易发送到选定的电子表格。',
            ar: 'أرسل المعاملات المحللة إلى جدول بيانات محدد.',
            pl: 'Wysyłaj przetworzone transakcje do wybranego arkusza.',
            it: 'Invia le transazioni elaborate a un foglio di calcolo selezionato.',
          }),
          action: t({ ru: 'Открыть настройку', en: 'Open setup', kk: 'Баптауды ашу', de: 'Einrichtung öffnen', fr: 'Ouvrir la configuration', es: 'Abrir configuración', pt: 'Abrir configuração', tr: 'Kurulumu aç', uk: 'Відкрити налаштування', zh: '打开设置', ar: 'فتح الإعداد', pl: 'Otwórz konfigurację', it: 'Apri configurazione' }),
        },
        telegram: {
          title: t({ ru: 'Telegram', en: 'Telegram', kk: 'Telegram', de: 'Telegram', fr: 'Telegram', es: 'Telegram', pt: 'Telegram', tr: 'Telegram', uk: 'Telegram', zh: 'Telegram', ar: 'Telegram', pl: 'Telegram', it: 'Telegram' }),
          description: t({
            ru: 'Получайте уведомления и отправляйте выписки через бота.',
            en: 'Receive notifications and send statements via bot.',
            kk: 'Хабарламалар алыңыз және үзінділерді бот арқылы жіберіңіз.',
            de: 'Benachrichtigungen empfangen und Kontoauszüge per Bot senden.',
            fr: 'Recevez des notifications et envoyez des relevés via le bot.',
            es: 'Recibe notificaciones y envía extractos a través del bot.',
            pt: 'Receba notificações e envie extratos via bot.',
            tr: 'Bot aracılığıyla bildirim alın ve hesap özetleri gönderin.',
            uk: 'Отримуйте сповіщення та надсилайте виписки через бота.',
            zh: '通过机器人接收通知并发送对账单。',
            ar: 'استقبل الإشعارات وأرسل كشوف الحساب عبر البوت.',
            pl: 'Otrzymuj powiadomienia i wysyłaj wyciągi przez bota.',
            it: 'Ricevi notifiche e invia estratti conto tramite bot.',
          }),
          action: t({ ru: 'Настроить', en: 'Set up', kk: 'Баптау', de: 'Einrichten', fr: 'Configurer', es: 'Configurar', pt: 'Configurar', tr: 'Ayarla', uk: 'Налаштувати', zh: '设置', ar: 'إعداد', pl: 'Skonfiguruj', it: 'Configura' }),
        },
      },
      connectedBadge: t({ ru: 'Подключено', en: 'Connected', kk: 'Қосылған', de: 'Verbunden', fr: 'Connecté', es: 'Conectado', pt: 'Conectado', tr: 'Bağlandı', uk: 'Підключено', zh: '已连接', ar: 'متصل', pl: 'Połączono', it: 'Connesso' }),
      availableBadge: t({ ru: 'Доступно', en: 'Available', kk: 'Қолжетімді', de: 'Verfügbar', fr: 'Disponible', es: 'Disponible', pt: 'Disponível', tr: 'Mevcut', uk: 'Доступно', zh: '可用', ar: 'متاح', pl: 'Dostępne', it: 'Disponibile' }),
    },
    completion: {
      title: t({
        ru: 'Готово! Все настроено',
        en: 'Done! Setup complete',
        kk: 'Дайын! Баптау аяқталды',
        de: 'Fertig! Einrichtung abgeschlossen',
        fr: 'Terminé ! Configuration complète',
        es: '¡Listo! Configuración completa',
        pt: 'Concluído! Configuração completa',
        tr: 'Tamamlandı! Kurulum bitti',
        uk: 'Готово! Все налаштовано',
        zh: '完成！设置已完成',
        ar: 'تم! اكتمل الإعداد',
        pl: 'Gotowe! Konfiguracja zakończona',
        it: 'Fatto! Configurazione completata',
      }),
      subtitle: t({
        ru: 'Нажмите кнопку ниже, и перейдете в рабочее пространство.',
        en: 'Press the button below to continue to your workspace.',
        kk: 'Төмендегі батырманы басып, жұмыс кеңістігіне өтіңіз.',
        de: 'Drücken Sie den Button unten, um zu Ihrem Arbeitsbereich zu gelangen.',
        fr: 'Appuyez sur le bouton ci-dessous pour accéder à votre espace de travail.',
        es: 'Presiona el botón de abajo para continuar a tu espacio de trabajo.',
        pt: 'Pressione o botão abaixo para continuar para o seu workspace.',
        tr: 'Çalışma alanınıza geçmek için aşağıdaki düğmeye basın.',
        uk: 'Натисніть кнопку нижче і перейдіть до робочого простору.',
        zh: '按下下方按钮继续进入您的工作区。',
        ar: 'اضغط على الزر أدناه للانتقال إلى مساحة العمل.',
        pl: 'Naciśnij przycisk poniżej, aby przejść do przestrzeni roboczej.',
        it: 'Premi il pulsante qui sotto per continuare verso la tua area di lavoro.',
      }),
      summaryTitle: t({ ru: 'Ваши настройки', en: 'Your setup', kk: 'Сіздің баптауларыңыз', de: 'Ihre Einstellungen', fr: 'Votre configuration', es: 'Tu configuración', pt: 'Sua configuração', tr: 'Kurulumunuz', uk: 'Ваші налаштування', zh: '您的设置', ar: 'إعداداتك', pl: 'Twoje ustawienia', it: 'La tua configurazione' }),
      notSet: t({ ru: 'не задано', en: 'not set', kk: 'орнатылмаған', de: 'nicht festgelegt', fr: 'non défini', es: 'no definido', pt: 'não definido', tr: 'ayarlanmadı', uk: 'не задано', zh: '未设置', ar: 'غير محدد', pl: 'nie ustawiono', it: 'non impostato' }),
      summary: {
        language: t({ ru: 'Язык: {value}', en: 'Language: {value}', kk: 'Тіл: {value}', de: 'Sprache: {value}', fr: 'Langue : {value}', es: 'Idioma: {value}', pt: 'Idioma: {value}', tr: 'Dil: {value}', uk: 'Мова: {value}', zh: '语言：{value}', ar: 'اللغة: {value}', pl: 'Język: {value}', it: 'Lingua: {value}' }),
        timeZone: t({
          ru: 'Часовой пояс: {value}',
          en: 'Timezone: {value}',
          kk: 'Уақыт белдеуі: {value}',
          de: 'Zeitzone: {value}',
          fr: 'Fuseau horaire : {value}',
          es: 'Zona horaria: {value}',
          pt: 'Fuso horário: {value}',
          tr: 'Saat dilimi: {value}',
          uk: 'Часовий пояс: {value}',
          zh: '时区：{value}',
          ar: 'المنطقة الزمنية: {value}',
          pl: 'Strefa czasowa: {value}',
          it: 'Fuso orario: {value}',
        }),
        workspace: t({
          ru: 'Воркспейс: {value}',
          en: 'Workspace: {value}',
          kk: 'Жұмыс кеңістігі: {value}',
          de: 'Arbeitsbereich: {value}',
          fr: 'Espace de travail : {value}',
          es: 'Espacio de trabajo: {value}',
          pt: 'Workspace: {value}',
          tr: 'Çalışma alanı: {value}',
          uk: 'Воркспейс: {value}',
          zh: '工作区：{value}',
          ar: 'مساحة العمل: {value}',
          pl: 'Przestrzeń robocza: {value}',
          it: 'Area di lavoro: {value}',
        }),
        currency: t({ ru: 'Валюта: {value}', en: 'Currency: {value}', kk: 'Валюта: {value}', de: 'Währung: {value}', fr: 'Devise : {value}', es: 'Moneda: {value}', pt: 'Moeda: {value}', tr: 'Para birimi: {value}', uk: 'Валюта: {value}', zh: '货币：{value}', ar: 'العملة: {value}', pl: 'Waluta: {value}', it: 'Valuta: {value}' }),
        integrations: t({
          ru: 'Подключенные интеграции:',
          en: 'Connected integrations:',
          kk: 'Қосылған интеграциялар:',
          de: 'Verbundene Integrationen:',
          fr: 'Intégrations connectées :',
          es: 'Integraciones conectadas:',
          pt: 'Integrações conectadas:',
          tr: 'Bağlı entegrasyonlar:',
          uk: 'Підключені інтеграції:',
          zh: '已连接的集成：',
          ar: 'التكاملات المتصلة:',
          pl: 'Połączone integracje:',
          it: 'Integrazioni connesse:',
        }),
        background: t({
          ru: 'Фон воркспейса: {value}',
          en: 'Workspace background: {value}',
          kk: 'Жұмыс кеңістігінің фоны: {value}',
          de: 'Hintergrund des Arbeitsbereichs: {value}',
          fr: 'Arrière-plan de l\'espace de travail : {value}',
          es: 'Fondo del espacio de trabajo: {value}',
          pt: 'Plano de fundo do workspace: {value}',
          tr: 'Çalışma alanı arka planı: {value}',
          uk: 'Фон воркспейсу: {value}',
          zh: '工作区背景：{value}',
          ar: 'خلفية مساحة العمل: {value}',
          pl: 'Tło przestrzeni roboczej: {value}',
          it: 'Sfondo area di lavoro: {value}',
        }),
      },
      backgroundSet: t({ ru: 'установлен', en: 'set', kk: 'орнатылған', de: 'festgelegt', fr: 'défini', es: 'definido', pt: 'definido', tr: 'ayarlandı', uk: 'встановлено', zh: '已设置', ar: 'محدد', pl: 'ustawiono', it: 'impostato' }),
      noIntegrations: t({
        ru: 'Интеграции не подключены',
        en: 'No integrations connected',
        kk: 'Интеграциялар қосылмаған',
        de: 'Keine Integrationen verbunden',
        fr: 'Aucune intégration connectée',
        es: 'No hay integraciones conectadas',
        pt: 'Nenhuma integração conectada',
        tr: 'Bağlı entegrasyon yok',
        uk: 'Інтеграції не підключені',
        zh: '没有已连接的集成',
        ar: 'لا توجد تكاملات متصلة',
        pl: 'Brak połączonych integracji',
        it: 'Nessuna integrazione connessa',
      }),
    },
    navigation: {
      back: t({ ru: 'Назад', en: 'Back', kk: 'Артқа', de: 'Zurück', fr: 'Retour', es: 'Atrás', pt: 'Voltar', tr: 'Geri', uk: 'Назад', zh: '返回', ar: 'رجوع', pl: 'Wstecz', it: 'Indietro' }),
      next: t({ ru: 'Далее', en: 'Next', kk: 'Келесі', de: 'Weiter', fr: 'Suivant', es: 'Siguiente', pt: 'Próximo', tr: 'İleri', uk: 'Далі', zh: '下一步', ar: 'التالي', pl: 'Dalej', it: 'Avanti' }),
      finish: t({ ru: 'Начать работу', en: 'Start using app', kk: 'Жұмысты бастау', de: 'App starten', fr: 'Commencer à utiliser l\'application', es: 'Empezar a usar la app', pt: 'Começar a usar o app', tr: 'Uygulamayı kullanmaya başla', uk: 'Почати роботу', zh: '开始使用应用', ar: 'ابدأ استخدام التطبيق', pl: 'Zacznij korzystać z aplikacji', it: 'Inizia a usare l\'app' }),
      skip: t({ ru: 'Пропустить', en: 'Skip', kk: 'Өткізу', de: 'Überspringen', fr: 'Passer', es: 'Omitir', pt: 'Pular', tr: 'Atla', uk: 'Пропустити', zh: '跳过', ar: 'تخطي', pl: 'Pomiń', it: 'Salta' }),
      skipAll: t({ ru: 'Пропустить все', en: 'Skip all', kk: 'Барлығын өткізу', de: 'Alle überspringen', fr: 'Tout passer', es: 'Omitir todo', pt: 'Pular tudo', tr: 'Tümünü atla', uk: 'Пропустити все', zh: '全部跳过', ar: 'تخطي الكل', pl: 'Pomiń wszystko', it: 'Salta tutto' }),
      saving: t({ ru: 'Сохраняем...', en: 'Saving...', kk: 'Сақталуда...', de: 'Speichern...', fr: 'Enregistrement...', es: 'Guardando...', pt: 'Salvando...', tr: 'Kaydediliyor...', uk: 'Зберігаємо...', zh: '保存中...', ar: 'جارٍ الحفظ...', pl: 'Zapisywanie...', it: 'Salvataggio...' }),
    },
    errors: {
      workspaceLoadFailed: t({
        ru: 'Не удалось загрузить данные воркспейса. Можно продолжить с настройками по умолчанию.',
        en: 'Failed to load workspace data. You can continue with default settings.',
        kk: 'Жұмыс кеңістігі деректерін жүктеу мүмкін болмады. Әдепкі баптаулармен жалғастыра аласыз.',
        de: 'Arbeitsbereichsdaten konnten nicht geladen werden. Sie können mit den Standardeinstellungen fortfahren.',
        fr: 'Impossible de charger les données de l\'espace de travail. Vous pouvez continuer avec les paramètres par défaut.',
        es: 'No se pudieron cargar los datos del espacio de trabajo. Puedes continuar con la configuración predeterminada.',
        pt: 'Falha ao carregar dados do workspace. Você pode continuar com as configurações padrão.',
        tr: 'Çalışma alanı verileri yüklenemedi. Varsayılan ayarlarla devam edebilirsiniz.',
        uk: 'Не вдалося завантажити дані воркспейсу. Можна продовжити з налаштуваннями за замовчуванням.',
        zh: '无法加载工作区数据。您可以使用默认设置继续。',
        ar: 'فشل تحميل بيانات مساحة العمل. يمكنك المتابعة بالإعدادات الافتراضية.',
        pl: 'Nie udało się załadować danych przestrzeni roboczej. Możesz kontynuować z ustawieniami domyślnymi.',
        it: 'Impossibile caricare i dati dell\'area di lavoro. Puoi continuare con le impostazioni predefinite.',
      }),
      completeFailed: t({
        ru: 'Не удалось завершить онбординг. Попробуйте еще раз.',
        en: 'Failed to complete onboarding. Please try again.',
        kk: 'Онбордингті аяқтау мүмкін болмады. Қайта көріңіз.',
        de: 'Onboarding konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
        fr: 'Impossible de terminer l\'intégration. Veuillez réessayer.',
        es: 'No se pudo completar el proceso de incorporación. Por favor, inténtalo de nuevo.',
        pt: 'Falha ao concluir o onboarding. Por favor, tente novamente.',
        tr: 'Katılım süreci tamamlanamadı. Lütfen tekrar deneyin.',
        uk: 'Не вдалося завершити онбординг. Спробуйте ще раз.',
        zh: '无法完成引导流程。请重试。',
        ar: 'فشل إكمال عملية التهيئة. يرجى المحاولة مرة أخرى.',
        pl: 'Nie udało się ukończyć procesu wdrożenia. Spróbuj ponownie.',
        it: 'Impossibile completare l\'onboarding. Riprova.',
      }),
    },
  },
} satisfies Dictionary;

export default content;
