import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'gmailIntegrationPage',
  content: {
    header: {
      title: t({ ru: 'Gmail', en: 'Gmail', kk: 'Gmail', de: 'Gmail', fr: 'Gmail', es: 'Gmail', pt: 'Gmail', tr: 'Gmail', uk: 'Gmail', zh: 'Gmail', ar: 'Gmail', pl: 'Gmail', it: 'Gmail', sk: 'Gmail'}),
      subtitle: t({
        ru: 'Подключите Gmail, чтобы автоматически импортировать чеки и счета',
        en: 'Connect Gmail to automatically import receipts and invoices',
        kk: 'Чек пен шоттарды автоматты импорттау үшін Gmail қосыңыз',
        de: 'Verbinden Sie Gmail, um Belege und Rechnungen automatisch zu importieren',
        fr: 'Connectez Gmail pour importer automatiquement les reçus et factures',
        es: 'Conecta Gmail para importar automáticamente recibos y facturas',
        pt: 'Conecte o Gmail para importar automaticamente recibos e faturas',
        tr: 'Makbuz ve faturaları otomatik içe aktarmak için Gmail\'i bağlayın',
        uk: 'Підключіть Gmail для автоматичного імпорту чеків та рахунків',
        zh: '连接 Gmail 以自动导入收据和发票',
        ar: 'قم بتوصيل Gmail لاستيراد الإيصالات والفواتير تلقائيًا',
        pl: 'Połącz Gmail, aby automatycznie importować paragony i faktury',
        it: 'Collega Gmail per importare automaticamente ricevute e fatture',
        sk: 'Połącz Gmail, aby automatycznie importować paragony i faktury',
      }),
    },
    status: {
      connected: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылған',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlı',
        uk: 'Підключено',
        zh: '已连接',
        ar: 'متصل',
        pl: 'Połączone',
        it: 'Connesso',
        sk: 'Połączone',
      }),
      disconnected: t({
        ru: 'Не подключено',
        en: 'Disconnected',
        kk: 'Қосылмаған',
        de: 'Getrennt',
        fr: 'Déconnecté',
        es: 'Desconectado',
        pt: 'Desconectado',
        tr: 'Bağlı değil',
        uk: 'Відключено',
        zh: '未连接',
        ar: 'غير متصل',
        pl: 'Rozłączone',
        it: 'Disconnesso',
        sk: 'Rozłączone',
      }),
      needsReauth: t({
        ru: 'Требуется повторная авторизация',
        en: 'Needs re-authentication',
        kk: 'Қайта авторизация қажет',
        de: 'Erneute Authentifizierung erforderlich',
        fr: 'Réauthentification requise',
        es: 'Requiere reautenticación',
        pt: 'Reautenticação necessária',
        tr: 'Yeniden kimlik doğrulama gerekiyor',
        uk: 'Потрібна повторна авторизація',
        zh: '需要重新认证',
        ar: 'يتطلب إعادة المصادقة',
        pl: 'Wymagane ponowne uwierzytelnienie',
        it: 'Richiesta nuova autenticazione',
        sk: 'Wymagane ponowne uwierzytelnienie',
      }),
      active: t({
        ru: 'Активно',
        en: 'Active',
        kk: 'Белсенді',
        de: 'Aktiv',
        fr: 'Actif',
        es: 'Activo',
        pt: 'Ativo',
        tr: 'Aktif',
        uk: 'Активно',
        zh: '活跃',
        ar: 'نشط',
        pl: 'Aktywne',
        it: 'Attivo',
        sk: 'Aktywne',
      }),
      inactive: t({
        ru: 'Неактивно',
        en: 'Inactive',
        kk: 'Белсенді емес',
        de: 'Inaktiv',
        fr: 'Inactif',
        es: 'Inactivo',
        pt: 'Inativo',
        tr: 'Pasif',
        uk: 'Неактивно',
        zh: '非活跃',
        ar: 'غير نشط',
        pl: 'Nieaktywne',
        it: 'Inattivo',
        sk: 'Nieaktywne',
      }),
      enabled: t({
        ru: 'Включено',
        en: 'Enabled',
        kk: 'Қосулы',
        de: 'Aktiviert',
        fr: 'Activé',
        es: 'Habilitado',
        pt: 'Habilitado',
        tr: 'Etkin',
        uk: 'Увімкнено',
        zh: '已启用',
        ar: 'مفعّل',
        pl: 'Włączone',
        it: 'Abilitato',
        sk: 'Włączone',
      }),
      disabled: t({
        ru: 'Выключено',
        en: 'Disabled',
        kk: 'Өшірулі',
        de: 'Deaktiviert',
        fr: 'Désactivé',
        es: 'Deshabilitado',
        pt: 'Desabilitado',
        tr: 'Devre dışı',
        uk: 'Вимкнено',
        zh: '已禁用',
        ar: 'معطّل',
        pl: 'Wyłączone',
        it: 'Disabilitato',
        sk: 'Wyłączone',
      }),
    },
    actions: {
      connect: t({
        ru: 'Подключить Gmail',
        en: 'Connect Gmail',
        kk: 'Gmail қосу',
        de: 'Gmail verbinden',
        fr: 'Connecter Gmail',
        es: 'Conectar Gmail',
        pt: 'Conectar Gmail',
        tr: 'Gmail\'i bağla',
        uk: 'Підключити Gmail',
        zh: '连接 Gmail',
        ar: 'توصيل Gmail',
        pl: 'Połącz Gmail',
        it: 'Connetti Gmail',
        sk: 'Połącz Gmail',
      }),
      reconnect: t({
        ru: 'Переподключить',
        en: 'Reconnect',
        kk: 'Қайта қосу',
        de: 'Erneut verbinden',
        fr: 'Reconnecter',
        es: 'Reconectar',
        pt: 'Reconectar',
        tr: 'Yeniden bağlan',
        uk: 'Перепідключити',
        zh: '重新连接',
        ar: 'إعادة الاتصال',
        pl: 'Połącz ponownie',
        it: 'Riconnetti',
        sk: 'Połącz ponownie',
      }),
      disconnect: t({
        ru: 'Отключить',
        en: 'Disconnect',
        kk: 'Ажырату',
        de: 'Trennen',
        fr: 'Déconnecter',
        es: 'Desconectar',
        pt: 'Desconectar',
        tr: 'Bağlantıyı kes',
        uk: 'Відключити',
        zh: '断开连接',
        ar: 'قطع الاتصال',
        pl: 'Rozłącz',
        it: 'Disconnetti',
        sk: 'Rozłącz',
      }),
      sync: t({
        ru: 'Синхронизировать Gmail',
        en: 'Sync Gmail',
        kk: 'Gmail синхрондау',
        de: 'Gmail synchronisieren',
        fr: 'Synchroniser Gmail',
        es: 'Sincronizar Gmail',
        pt: 'Sincronizar Gmail',
        tr: 'Gmail\'i senkronize et',
        uk: 'Синхронізувати Gmail',
        zh: '同步 Gmail',
        ar: 'مزامنة Gmail',
        pl: 'Synchronizuj Gmail',
        it: 'Sincronizza Gmail',
        sk: 'Synchronizuj Gmail',
      }),
    },
    settings: {
      title: t({
        ru: 'Настройки',
        en: 'Settings',
        kk: 'Баптаулар',
        de: 'Einstellungen',
        fr: 'Paramètres',
        es: 'Configuración',
        pt: 'Configurações',
        tr: 'Ayarlar',
        uk: 'Налаштування',
        zh: '设置',
        ar: 'الإعدادات',
        pl: 'Ustawienia',
        it: 'Impostazioni',
        sk: 'Ustawienia',
      }),
      labelName: t({
        ru: 'Название ярлыка',
        en: 'Label name',
        kk: 'Белгі атауы',
        de: 'Label-Name',
        fr: 'Nom du libellé',
        es: 'Nombre de etiqueta',
        pt: 'Nome do rótulo',
        tr: 'Etiket adı',
        uk: 'Назва мітки',
        zh: '标签名称',
        ar: 'اسم التسمية',
        pl: 'Nazwa etykiety',
        it: 'Nome etichetta',
        sk: 'Nazwa etykiety',
      }),
      lastSync: t({
        ru: 'Последняя синхронизация',
        en: 'Last sync',
        kk: 'Соңғы синхрондау',
        de: 'Letzte Synchronisierung',
        fr: 'Dernière synchronisation',
        es: 'Última sincronización',
        pt: 'Última sincronização',
        tr: 'Son senkronizasyon',
        uk: 'Остання синхронізація',
        zh: '最后同步',
        ar: 'آخر مزامنة',
        pl: 'Ostatnia synchronizacja',
        it: 'Ultima sincronizzazione',
        sk: 'Ostatnia synchronizacja',
      }),
      filterEnabled: t({
        ru: 'Включить автоматическую фильтрацию',
        en: 'Enable automatic filtering',
        kk: 'Автоматты сүзуді қосу',
        de: 'Automatische Filterung aktivieren',
        fr: 'Activer le filtrage automatique',
        es: 'Habilitar filtrado automático',
        pt: 'Habilitar filtragem automática',
        tr: 'Otomatik filtrelemeyi etkinleştir',
        uk: 'Увімкнути автоматичне фільтрування',
        zh: '启用自动筛选',
        ar: 'تفعيل التصفية التلقائية',
        pl: 'Włącz automatyczne filtrowanie',
        it: 'Abilita filtro automatico',
        sk: 'Włącz automatyczne filtrowanie',
      }),
      watchStatus: t({
        ru: 'Статус отслеживания',
        en: 'Watch status',
        kk: 'Бақылау статусы',
        de: 'Überwachungsstatus',
        fr: 'Statut de surveillance',
        es: 'Estado de seguimiento',
        pt: 'Status de monitoramento',
        tr: 'İzleme durumu',
        uk: 'Статус відстеження',
        zh: '监控状态',
        ar: 'حالة المراقبة',
        pl: 'Status śledzenia',
        it: 'Stato monitoraggio',
        sk: 'Status śledzenia',
      }),
      expires: t({
        ru: 'Истекает',
        en: 'Expires',
        kk: 'Аяқталады',
        de: 'Läuft ab',
        fr: 'Expire',
        es: 'Expira',
        pt: 'Expira',
        tr: 'Sona eriyor',
        uk: 'Закінчується',
        zh: '到期',
        ar: 'تنتهي صلاحيته',
        pl: 'Wygasa',
        it: 'Scade',
        sk: 'Wygasa',
      }),
      keywords: t({
        ru: 'Ключевые слова',
        en: 'Filter keywords',
        kk: 'Сүзгі сөздері',
        de: 'Schlüsselwörter',
        fr: 'Mots-clés de filtre',
        es: 'Palabras clave de filtro',
        pt: 'Palavras-chave de filtro',
        tr: 'Filtre anahtar kelimeleri',
        uk: 'Ключові слова фільтра',
        zh: '筛选关键词',
        ar: 'كلمات مفتاح التصفية',
        pl: 'Słowa kluczowe filtra',
        it: 'Parole chiave filtro',
        sk: 'Słowa kluczowe filtra',
      }),
      keywordsPlaceholder: t({
        ru: 'чек, счет, подтверждение заказа',
        en: 'receipt, invoice, order confirmation',
        kk: 'чек, шот, тапсырыс растауы',
        de: 'Beleg, Rechnung, Bestellbestätigung',
        fr: 'reçu, facture, confirmation de commande',
        es: 'recibo, factura, confirmación de pedido',
        pt: 'recibo, fatura, confirmação de pedido',
        tr: 'makbuz, fatura, sipariş onayı',
        uk: 'чек, рахунок, підтвердження замовлення',
        zh: '收据, 发票, 订单确认',
        ar: 'إيصال، فاتورة، تأكيد الطلب',
        pl: 'paragon, faktura, potwierdzenie zamówienia',
        it: 'ricevuta, fattura, conferma ordine',
        sk: 'paragon, faktura, potwierdzenie zamówienia',
      }),
      keywordsHelp: t({
        ru: 'Ключевые слова через запятую для фильтрации писем',
        en: 'Comma-separated keywords for filtering emails',
        kk: 'Электрондық хаттарды сүзуге арналған үтірмен бөлінген сөздер',
        de: 'Durch Komma getrennte Schlüsselwörter zur E-Mail-Filterung',
        fr: 'Mots-clés séparés par des virgules pour filtrer les e-mails',
        es: 'Palabras clave separadas por comas para filtrar correos',
        pt: 'Palavras-chave separadas por vírgula para filtrar e-mails',
        tr: 'E-postaları filtrelemek için virgülle ayrılmış anahtar kelimeler',
        uk: 'Ключові слова через кому для фільтрації листів',
        zh: '用逗号分隔的关键词用于过滤邮件',
        ar: 'كلمات مفتاحية مفصولة بفواصل لتصفية الرسائل',
        pl: 'Słowa kluczowe oddzielone przecinkami do filtrowania e-maili',
        it: 'Parole chiave separate da virgola per filtrare le email',
        sk: 'Słowa kluczowe oddzielone przecinkami do filtrowania e-maili',
      }),
      hasAttachment: t({
        ru: 'Только письма с вложениями',
        en: 'Only emails with attachments',
        kk: 'Тек тіркемесі бар хаттар',
        de: 'Nur E-Mails mit Anhängen',
        fr: 'Uniquement les e-mails avec pièces jointes',
        es: 'Solo correos con archivos adjuntos',
        pt: 'Apenas e-mails com anexos',
        tr: 'Yalnızca ekli e-postalar',
        uk: 'Тільки листи з вкладеннями',
        zh: '仅含附件的邮件',
        ar: 'رسائل البريد التي تحتوي على مرفقات فقط',
        pl: 'Tylko e-maile z załącznikami',
        it: 'Solo email con allegati',
        sk: 'Tylko e-maile z załącznikami',
      }),
    },
    toasts: {
      connecting: t({
        ru: 'Подключение к Gmail...',
        en: 'Connecting to Gmail...',
        kk: 'Gmail қосылуда...',
        de: 'Verbindung zu Gmail wird hergestellt...',
        fr: 'Connexion à Gmail en cours...',
        es: 'Conectando a Gmail...',
        pt: 'Conectando ao Gmail...',
        tr: 'Gmail\'e bağlanılıyor...',
        uk: 'Підключення до Gmail...',
        zh: '正在连接 Gmail...',
        ar: 'جارٍ الاتصال بـ Gmail...',
        pl: 'Łączenie z Gmail...',
        it: 'Connessione a Gmail in corso...',
        sk: 'Łączenie z Gmail...',
      }),
      connected: t({
        ru: 'Gmail подключен',
        en: 'Gmail connected successfully!',
        kk: 'Gmail сәтті қосылды!',
        de: 'Gmail erfolgreich verbunden!',
        fr: 'Gmail connecté avec succès !',
        es: '¡Gmail conectado correctamente!',
        pt: 'Gmail conectado com sucesso!',
        tr: 'Gmail başarıyla bağlandı!',
        uk: 'Gmail успішно підключено!',
        zh: 'Gmail 连接成功！',
        ar: 'تم توصيل Gmail بنجاح!',
        pl: 'Gmail połączony pomyślnie!',
        it: 'Gmail connesso con successo!',
        sk: 'Gmail połączony pomyślnie!',
      }),
      disconnected: t({
        ru: 'Gmail отключен',
        en: 'Gmail disconnected',
        kk: 'Gmail ажыратылды',
        de: 'Gmail getrennt',
        fr: 'Gmail déconnecté',
        es: 'Gmail desconectado',
        pt: 'Gmail desconectado',
        tr: 'Gmail bağlantısı kesildi',
        uk: 'Gmail відключено',
        zh: 'Gmail 已断开连接',
        ar: 'تم قطع اتصال Gmail',
        pl: 'Gmail rozłączony',
        it: 'Gmail disconnesso',
        sk: 'Gmail rozłączony',
      }),
      settingsSaved: t({
        ru: 'Настройки сохранены',
        en: 'Settings saved',
        kk: 'Баптаулар сақталды',
        de: 'Einstellungen gespeichert',
        fr: 'Paramètres enregistrés',
        es: 'Configuración guardada',
        pt: 'Configurações salvas',
        tr: 'Ayarlar kaydedildi',
        uk: 'Налаштування збережено',
        zh: '设置已保存',
        ar: 'تم حفظ الإعدادات',
        pl: 'Ustawienia zapisane',
        it: 'Impostazioni salvate',
        sk: 'Ustawienia zapisane',
      }),
      syncStarted: t({
        ru: 'Синхронизация запущена',
        en: 'Gmail sync started',
        kk: 'Синхрондау басталды',
        de: 'Gmail-Synchronisierung gestartet',
        fr: 'Synchronisation Gmail démarrée',
        es: 'Sincronización de Gmail iniciada',
        pt: 'Sincronização do Gmail iniciada',
        tr: 'Gmail senkronizasyonu başlatıldı',
        uk: 'Синхронізацію Gmail розпочато',
        zh: 'Gmail 同步已开始',
        ar: 'بدأت مزامنة Gmail',
        pl: 'Synchronizacja Gmail rozpoczęta',
        it: 'Sincronizzazione Gmail avviata',
        sk: 'Synchronizacja Gmail rozpoczęta',
      }),
    },
    errors: {
      loadStatus: t({
        ru: 'Не удалось загрузить статус Gmail',
        en: 'Failed to load Gmail integration status',
        kk: 'Gmail статусын жүктеу мүмкін болмады',
        de: 'Gmail-Integrationsstatus konnte nicht geladen werden',
        fr: 'Impossible de charger le statut d\'intégration Gmail',
        es: 'No se pudo cargar el estado de integración de Gmail',
        pt: 'Falha ao carregar o status de integração do Gmail',
        tr: 'Gmail entegrasyon durumu yüklenemedi',
        uk: 'Не вдалося завантажити статус Gmail',
        zh: '无法加载 Gmail 集成状态',
        ar: 'فشل تحميل حالة تكامل Gmail',
        pl: 'Nie udało się załadować statusu integracji Gmail',
        it: 'Impossibile caricare lo stato di integrazione Gmail',
        sk: 'Nie udało się załadować statusu integracji Gmail',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить Gmail',
        en: 'Failed to connect Gmail',
        kk: 'Gmail қосу мүмкін болмады',
        de: 'Gmail konnte nicht verbunden werden',
        fr: 'Impossible de connecter Gmail',
        es: 'No se pudo conectar Gmail',
        pt: 'Falha ao conectar o Gmail',
        tr: 'Gmail bağlanamadı',
        uk: 'Не вдалося підключити Gmail',
        zh: '无法连接 Gmail',
        ar: 'فشل الاتصال بـ Gmail',
        pl: 'Nie udało się połączyć Gmail',
        it: 'Impossibile connettere Gmail',
        sk: 'Nie udało się połączyć Gmail',
      }),
      missingOauthUrl: t({
        ru: 'Не удалось получить OAuth ссылку Gmail',
        en: 'Failed to get Gmail OAuth URL',
        kk: 'Gmail OAuth сілтемесін алу мүмкін болмады',
        de: 'Gmail OAuth-URL konnte nicht abgerufen werden',
        fr: 'Impossible d\'obtenir l\'URL OAuth Gmail',
        es: 'No se pudo obtener la URL de OAuth de Gmail',
        pt: 'Falha ao obter URL OAuth do Gmail',
        tr: 'Gmail OAuth URL\'si alınamadı',
        uk: 'Не вдалося отримати OAuth-посилання Gmail',
        zh: '无法获取 Gmail OAuth URL',
        ar: 'فشل الحصول على رابط OAuth الخاص بـ Gmail',
        pl: 'Nie udało się uzyskać adresu OAuth Gmail',
        it: 'Impossibile ottenere l\'URL OAuth di Gmail',
        sk: 'Nie udało się uzyskać adresu OAuth Gmail',
      }),
      disconnectFailed: t({
        ru: 'Не удалось отключить Gmail',
        en: 'Failed to disconnect Gmail',
        kk: 'Gmail ажырату мүмкін болмады',
        de: 'Gmail konnte nicht getrennt werden',
        fr: 'Impossible de déconnecter Gmail',
        es: 'No se pudo desconectar Gmail',
        pt: 'Falha ao desconectar o Gmail',
        tr: 'Gmail bağlantısı kesilemedi',
        uk: 'Не вдалося відключити Gmail',
        zh: '无法断开 Gmail 连接',
        ar: 'فشل قطع اتصال Gmail',
        pl: 'Nie udało się rozłączyć Gmail',
        it: 'Impossibile disconnettere Gmail',
        sk: 'Nie udało się rozłączyć Gmail',
      }),
      saveFailed: t({
        ru: 'Не удалось сохранить настройки',
        en: 'Failed to save settings',
        kk: 'Баптауларды сақтау мүмкін болмады',
        de: 'Einstellungen konnten nicht gespeichert werden',
        fr: 'Impossible d\'enregistrer les paramètres',
        es: 'No se pudo guardar la configuración',
        pt: 'Falha ao salvar configurações',
        tr: 'Ayarlar kaydedilemedi',
        uk: 'Не вдалося зберегти налаштування',
        zh: '无法保存设置',
        ar: 'فشل حفظ الإعدادات',
        pl: 'Nie udało się zapisać ustawień',
        it: 'Impossibile salvare le impostazioni',
        sk: 'Nie udało się zapisać ustawień',
      }),
      syncFailed: t({
        ru: 'Не удалось синхронизировать Gmail',
        en: 'Failed to sync Gmail',
        kk: 'Gmail синхрондау мүмкін болмады',
        de: 'Gmail konnte nicht synchronisiert werden',
        fr: 'Impossible de synchroniser Gmail',
        es: 'No se pudo sincronizar Gmail',
        pt: 'Falha ao sincronizar o Gmail',
        tr: 'Gmail senkronize edilemedi',
        uk: 'Не вдалося синхронізувати Gmail',
        zh: '无法同步 Gmail',
        ar: 'فشلت مزامنة Gmail',
        pl: 'Nie udało się zsynchronizować Gmail',
        it: 'Impossibile sincronizzare Gmail',
        sk: 'Nie udało się zsynchronizować Gmail',
      }),
      noMatches: t({
        ru: 'Подходящие письма не найдены',
        en: 'No matching emails found in Gmail',
        kk: 'Сәйкес хаттар табылмады',
        de: 'Keine passenden E-Mails in Gmail gefunden',
        fr: 'Aucun e-mail correspondant trouvé dans Gmail',
        es: 'No se encontraron correos coincidentes en Gmail',
        pt: 'Nenhum e-mail correspondente encontrado no Gmail',
        tr: 'Gmail\'de eşleşen e-posta bulunamadı',
        uk: 'Відповідні листи не знайдено',
        zh: 'Gmail 中未找到匹配的邮件',
        ar: 'لم يتم العثور على رسائل بريد مطابقة في Gmail',
        pl: 'Nie znaleziono pasujących wiadomości w Gmail',
        it: 'Nessuna email corrispondente trovata in Gmail',
        sk: 'Nie znaleziono pasujących wiadomości w Gmail',
      }),
      allSynced: t({
        ru: 'Все доступные чеки уже синхронизированы',
        en: 'All receipts available in Gmail are already synced',
        kk: 'Барлық чек синхрондалған',
        de: 'Alle in Gmail verfügbaren Belege sind bereits synchronisiert',
        fr: 'Tous les reçus disponibles dans Gmail sont déjà synchronisés',
        es: 'Todos los recibos disponibles en Gmail ya están sincronizados',
        pt: 'Todos os recibos disponíveis no Gmail já estão sincronizados',
        tr: 'Gmail\'deki tüm makbuzlar zaten senkronize edildi',
        uk: 'Всі доступні чеки вже синхронізовані',
        zh: 'Gmail 中所有可用的收据已同步',
        ar: 'جميع الإيصالات المتاحة في Gmail متزامنة بالفعل',
        pl: 'Wszystkie paragony dostępne w Gmail są już zsynchronizowane',
        it: 'Tutte le ricevute disponibili in Gmail sono già sincronizzate',
        sk: 'Wszystkie paragony dostępne w Gmail są już zsynchronizowane',
      }),
      syncNoNew: t({
        ru: 'Синхронизация завершена без новых чеков',
        en: 'Gmail sync finished with no new receipts',
        kk: 'Жаңа чек табылмады',
        de: 'Gmail-Synchronisierung ohne neue Belege abgeschlossen',
        fr: 'Synchronisation Gmail terminée sans nouveaux reçus',
        es: 'Sincronización de Gmail finalizada sin nuevos recibos',
        pt: 'Sincronização do Gmail concluída sem novos recibos',
        tr: 'Gmail senkronizasyonu yeni makbuz olmadan tamamlandı',
        uk: 'Синхронізація Gmail завершена без нових чеків',
        zh: 'Gmail 同步完成，无新收据',
        ar: 'اكتملت مزامنة Gmail دون إيصالات جديدة',
        pl: 'Synchronizacja Gmail zakończona bez nowych paragonów',
        it: 'Sincronizzazione Gmail completata senza nuove ricevute',
        sk: 'Synchronizacja Gmail zakończona bez nowych paragonów',
      }),
      loginRequired: t({
        ru: 'Войдите, чтобы подключить Gmail',
        en: 'Please sign in to connect Gmail',
        kk: 'Gmail қосу үшін кіріңіз',
        de: 'Bitte melden Sie sich an, um Gmail zu verbinden',
        fr: 'Veuillez vous connecter pour relier Gmail',
        es: 'Inicia sesión para conectar Gmail',
        pt: 'Faça login para conectar o Gmail',
        tr: 'Gmail\'i bağlamak için giriş yapın',
        uk: 'Увійдіть, щоб підключити Gmail',
        zh: '请登录以连接 Gmail',
        ar: 'يرجى تسجيل الدخول لتوصيل Gmail',
        pl: 'Zaloguj się, aby połączyć Gmail',
        it: 'Accedi per connettere Gmail',
        sk: 'Zaloguj się, aby połączyć Gmail',
      }),
      authFailed: t({
        ru: 'Не удалось подключить Gmail',
        en: 'Failed to connect Gmail',
        kk: 'Gmail қосу мүмкін болмады',
        de: 'Gmail konnte nicht verbunden werden',
        fr: 'Impossible de connecter Gmail',
        es: 'No se pudo conectar Gmail',
        pt: 'Falha ao conectar o Gmail',
        tr: 'Gmail bağlanamadı',
        uk: 'Не вдалося підключити Gmail',
        zh: '无法连接 Gmail',
        ar: 'فشل الاتصال بـ Gmail',
        pl: 'Nie udało się połączyć Gmail',
        it: 'Impossibile connettere Gmail',
        sk: 'Nie udało się połączyć Gmail',
      }),
    },
    info: {
      title: t({
        ru: 'Как это работает',
        en: 'How it works',
        kk: 'Бұл қалай жұмыс істейді',
        de: 'So funktioniert es',
        fr: 'Comment ça marche',
        es: 'Cómo funciona',
        pt: 'Como funciona',
        tr: 'Nasıl çalışır',
        uk: 'Як це працює',
        zh: '工作原理',
        ar: 'كيف يعمل',
        pl: 'Jak to działa',
        it: 'Come funziona',
        sk: 'Jak to działa',
      }),
      step1: t({
        ru: '1. Подключите Gmail с доступом только на чтение',
        en: '1. Connect your Gmail account with read-only access',
        kk: '1. Gmail аккаунтын тек оқу рұқсатымен қосыңыз',
        de: '1. Verbinden Sie Ihr Gmail-Konto mit Lesezugriff',
        fr: '1. Connectez votre compte Gmail en accès lecture seule',
        es: '1. Conecta tu cuenta de Gmail con acceso de solo lectura',
        pt: '1. Conecte sua conta do Gmail com acesso somente leitura',
        tr: '1. Gmail hesabınızı salt okunur erişimle bağlayın',
        uk: '1. Підключіть Gmail з доступом лише для читання',
        zh: '1. 以只读权限连接您的 Gmail 账户',
        ar: '1. قم بتوصيل حساب Gmail بصلاحية القراءة فقط',
        pl: '1. Połącz konto Gmail z dostępem tylko do odczytu',
        it: '1. Connetti il tuo account Gmail con accesso in sola lettura',
        sk: '1. Połącz konto Gmail z dostępem tylko do odczytu',
      }),
      step2: t({
        ru: '2. Мы автоматически создадим ярлык "Lumio/Receipts"',
        en: '2. We automatically create a "Lumio/Receipts" label',
        kk: '2. Біз "Lumio/Receipts" белгісін автоматты жасаймыз',
        de: '2. Wir erstellen automatisch ein Label „Lumio/Receipts"',
        fr: '2. Nous créons automatiquement un libellé « Lumio/Receipts »',
        es: '2. Creamos automáticamente una etiqueta "Lumio/Receipts"',
        pt: '2. Criamos automaticamente um rótulo "Lumio/Receipts"',
        tr: '2. Otomatik olarak "Lumio/Receipts" etiketi oluşturuyoruz',
        uk: '2. Ми автоматично створимо мітку "Lumio/Receipts"',
        zh: '2. 我们自动创建 "Lumio/Receipts" 标签',
        ar: '2. نقوم تلقائيًا بإنشاء تسمية "Lumio/Receipts"',
        pl: '2. Automatycznie tworzymy etykietę "Lumio/Receipts"',
        it: '2. Creiamo automaticamente un\'etichetta "Lumio/Receipts"',
        sk: '2. Automatycznie tworzymy etykietę "Lumio/Receipts"',
      }),
      step3: t({
        ru: '3. Письма по фильтрам будут импортироваться автоматически',
        en: '3. Emails matching your filters are automatically imported',
        kk: '3. Сүзгіге сай хаттар автоматты импортталады',
        de: '3. E-Mails, die Ihren Filtern entsprechen, werden automatisch importiert',
        fr: '3. Les e-mails correspondant à vos filtres sont automatiquement importés',
        es: '3. Los correos que coinciden con tus filtros se importan automáticamente',
        pt: '3. E-mails que correspondem aos seus filtros são importados automaticamente',
        tr: '3. Filtrelerinizle eşleşen e-postalar otomatik olarak içe aktarılır',
        uk: '3. Листи за фільтрами будуть автоматично імпортовані',
        zh: '3. 符合筛选条件的邮件将自动导入',
        ar: '3. يتم استيراد رسائل البريد المطابقة لمرشحاتك تلقائيًا',
        pl: '3. E-maile pasujące do filtrów są automatycznie importowane',
        it: '3. Le email corrispondenti ai tuoi filtri vengono importate automaticamente',
        sk: '3. E-maile pasujące do filtrów są automatycznie importowane',
      }),
      step4: t({
        ru: '4. Проверяйте и подтверждайте чеки на странице Receipts',
        en: '4. Review and approve receipts in the Receipts page',
        kk: '4. Receipts бетінде чектерді тексеріп растаңыз',
        de: '4. Überprüfen und genehmigen Sie Belege auf der Seite „Receipts"',
        fr: '4. Vérifiez et approuvez les reçus sur la page Receipts',
        es: '4. Revisa y aprueba recibos en la página Receipts',
        pt: '4. Revise e aprove recibos na página Receipts',
        tr: '4. Makbuzları Receipts sayfasında inceleyin ve onaylayın',
        uk: '4. Перевіряйте та підтверджуйте чеки на сторінці Receipts',
        zh: '4. 在收据页面查看并确认收据',
        ar: '4. راجع الإيصالات وافتح صفحة Receipts للموافقة عليها',
        pl: '4. Przeglądaj i zatwierdzaj paragony na stronie Receipts',
        it: '4. Revisiona e approva le ricevute nella pagina Receipts',
        sk: '4. Przeglądaj i zatwierdzaj paragony na stronie Receipts',
      }),
    },
    common: {
      loading: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Laden...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
        sk: 'Ładowanie...',
      }),
      notConnected: t({
        ru: 'Не подключено',
        en: 'Not connected',
        kk: 'Қосылмаған',
        de: 'Nicht verbunden',
        fr: 'Non connecté',
        es: 'No conectado',
        pt: 'Não conectado',
        tr: 'Bağlı değil',
        uk: 'Не підключено',
        zh: '未连接',
        ar: 'غير متصل',
        pl: 'Niepołączone',
        it: 'Non connesso',
        sk: 'Niepołączone',
      }),
      unknownDate: t({ ru: '—', en: '—', kk: '—', de: '—', fr: '—', es: '—', pt: '—', tr: '—', uk: '—', zh: '—', ar: '—', pl: '—', it: '—', sk: '—'}),
    },
  },
} satisfies Dictionary;

export default content;
