import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementEditPageAlerts',
  content: {
    alertNeedsFixTitle: t({
      ru: 'Нужно исправить перед отправкой',
      en: 'Fix required before submit',
      kk: 'Жіберу алдында түзету қажет',
      de: 'Korrektur vor dem Einreichen erforderlich',
      fr: 'Correction requise avant soumission',
      es: 'Se requiere corrección antes de enviar',
      pt: 'Correção necessária antes de enviar',
      tr: 'Göndermeden önce düzeltme gerekli',
      uk: 'Потрібне виправлення перед надсиланням',
      zh: '提交前需要修正',
      ar: 'مطلوب تصحيح قبل الإرسال',
      pl: 'Wymagana korekta przed przesłaniem',
      it: 'Correzione richiesta prima dell\'invio',
      sk: 'Wymagana korekta przed przesłaniem',
    }),
    alertReviewTitle: t({
      ru: 'Проверьте выписку перед отправкой',
      en: 'Review statement before submit',
      kk: 'Жіберу алдында үзіндіні тексеріңіз',
      de: 'Kontoauszug vor dem Einreichen prüfen',
      fr: 'Vérifiez le relevé avant soumission',
      es: 'Revise el extracto antes de enviar',
      pt: 'Revise o extrato antes de enviar',
      tr: 'Göndermeden önce ekstreyi inceleyin',
      uk: 'Перевірте виписку перед надсиланням',
      zh: '提交前请审核对账单',
      ar: 'راجع الكشف قبل الإرسال',
      pl: 'Przejrzyj wyciąg przed przesłaniem',
      it: 'Rivedi l\'estratto conto prima dell\'invio',
      sk: 'Przejrzyj wyciąg przed przesłaniem',
    }),
    alertReadyTitle: t({
      ru: 'Выписка готова к отправке',
      en: 'Statement is ready to submit',
      kk: 'Үзінді жіберуге дайын',
      de: 'Kontoauszug ist bereit zur Einreichung',
      fr: 'Le relevé est prêt à être soumis',
      es: 'El extracto está listo para enviar',
      pt: 'O extrato está pronto para enviar',
      tr: 'Ekstre gönderilebilir durumda',
      uk: 'Виписка готова до надсилання',
      zh: '对账单已准备好提交',
      ar: 'الكشف جاهز للإرسال',
      pl: 'Wyciąg jest gotowy do przesłania',
      it: 'L\'estratto conto è pronto per l\'invio',
      sk: 'Wyciąg jest gotowy do przesłania',
    }),
    alertReadyBody: t({
      ru: 'Все обязательные категории назначены. Данные выглядят корректно, можно отправлять.',
      en: 'All required categories are assigned. The data looks good and ready to submit.',
      kk: 'Барлық міндетті санаттар тағайындалды. Деректер дұрыс, жіберуге болады.',
      de: 'Alle erforderlichen Kategorien wurden zugewiesen. Die Daten sehen gut aus und können eingereicht werden.',
      fr: 'Toutes les catégories requises sont assignées. Les données semblent correctes et sont prêtes à être soumises.',
      es: 'Todas las categorías requeridas están asignadas. Los datos se ven bien y están listos para enviar.',
      pt: 'Todas as categorias obrigatórias foram atribuídas. Os dados estão corretos e prontos para enviar.',
      tr: 'Gerekli tüm kategoriler atandı. Veriler iyi görünüyor ve gönderilmeye hazır.',
      uk: 'Усі обов\'язкові категорії призначено. Дані виглядають коректно, можна надсилати.',
      zh: '所有必填类别均已分配。数据看起来正常，可以提交。',
      ar: 'تم تعيين جميع الفئات المطلوبة. تبدو البيانات جيدة وجاهزة للإرسال.',
      pl: 'Wszystkie wymagane kategorie zostały przypisane. Dane wyglądają dobrze i są gotowe do przesłania.',
      it: 'Tutte le categorie obbligatorie sono assegnate. I dati sembrano corretti e sono pronti per l\'invio.',
      sk: 'Wszystkie wymagane kategorie zostały przypisane. Dane wyglądają dobrze i są gotowe do przesłania.',
    }),
    alertStatementCategoryMissing: t({
      ru: 'Не выбрана категория выписки.',
      en: 'Statement category is not selected.',
      kk: 'Үзінді санаты таңдалмаған.',
      de: 'Kontoauszugskategorie ist nicht ausgewählt.',
      fr: 'La catégorie du relevé n\'est pas sélectionnée.',
      es: 'La categoría del extracto no está seleccionada.',
      pt: 'A categoria do extrato não está selecionada.',
      tr: 'Ekstre kategorisi seçilmedi.',
      uk: 'Категорію виписки не вибрано.',
      zh: '未选择对账单类别。',
      ar: 'لم يتم تحديد فئة الكشف.',
      pl: 'Kategoria wyciągu nie jest wybrana.',
      it: 'La categoria dell\'estratto conto non è selezionata.',
      sk: 'Kategoria wyciągu nie jest wybrana.',
    }),
    alertStatementCategoryDisabled: t({
      ru: 'Выбранная категория выписки отключена. Выберите активную.',
      en: 'Selected statement category is disabled. Choose an active category.',
      kk: 'Таңдалған үзінді санаты өшірілген. Белсенді санатты таңдаңыз.',
      de: 'Die ausgewählte Kontoauszugskategorie ist deaktiviert. Wählen Sie eine aktive Kategorie.',
      fr: 'La catégorie de relevé sélectionnée est désactivée. Choisissez une catégorie active.',
      es: 'La categoría de extracto seleccionada está desactivada. Elija una categoría activa.',
      pt: 'A categoria de extrato selecionada está desativada. Escolha uma categoria ativa.',
      tr: 'Seçilen ekstre kategorisi devre dışı. Aktif bir kategori seçin.',
      uk: 'Вибрана категорія виписки вимкнена. Виберіть активну.',
      zh: '所选对账单类别已禁用。请选择一个有效类别。',
      ar: 'فئة الكشف المحددة معطلة. اختر فئة نشطة.',
      pl: 'Wybrana kategoria wyciągu jest wyłączona. Wybierz aktywną kategorię.',
      it: 'La categoria dell\'estratto conto selezionata è disabilitata. Scegli una categoria attiva.',
      sk: 'Wybrana kategoria wyciągu jest wyłączona. Wybierz aktywną kategorię.',
    }),
    alertTransactionsCategoryMissing: t({
      ru: '{count} транзакций требуют категорию. Назначьте категории для всех строк.',
      en: '{count} transactions require a category. Assign categories for all rows.',
      kk: '{count} транзакцияға санат қажет. Барлық жолдарға санат тағайындаңыз.',
      de: '{count} Transaktionen benötigen eine Kategorie. Weisen Sie allen Zeilen Kategorien zu.',
      fr: '{count} transactions nécessitent une catégorie. Assignez des catégories à toutes les lignes.',
      es: '{count} transacciones requieren una categoría. Asigne categorías a todas las filas.',
      pt: '{count} transações requerem uma categoria. Atribua categorias a todas as linhas.',
      tr: '{count} işlem bir kategori gerektiriyor. Tüm satırlara kategori atayın.',
      uk: '{count} транзакцій потребують категорії. Призначте категорії для всіх рядків.',
      zh: '{count} 笔交易需要类别。为所有行分配类别。',
      ar: '{count} معاملة تتطلب فئة. قم بتعيين الفئات لجميع الصفوف.',
      pl: '{count} transakcji wymaga kategorii. Przypisz kategorie do wszystkich wierszy.',
      it: '{count} transazioni richiedono una categoria. Assegna categorie a tutte le righe.',
      sk: '{count} transakcji wymaga kategorii. Przypisz kategorie do wszystkich wierszy.',
    }),
    alertParsingErrors: t({
      ru: 'Обнаружено {count} ошибок парсинга. Проверьте детали и данные выписки.',
      en: '{count} parsing errors found. Review parsing details and statement data.',
      kk: '{count} парсинг қатесі анықталды. Толық мәліметтерді тексеріңіз.',
      de: '{count} Parsing-Fehler gefunden. Überprüfen Sie die Parsing-Details und die Kontoauszugsdaten.',
      fr: '{count} erreurs d\'analyse trouvées. Vérifiez les détails d\'analyse et les données du relevé.',
      es: 'Se encontraron {count} errores de análisis. Revise los detalles de análisis y los datos del extracto.',
      pt: '{count} erros de análise encontrados. Revise os detalhes de análise e os dados do extrato.',
      tr: '{count} ayrıştırma hatası bulundu. Ayrıştırma ayrıntılarını ve ekstre verilerini inceleyin.',
      uk: 'Виявлено {count} помилок парсингу. Перевірте деталі та дані виписки.',
      zh: '发现 {count} 个解析错误。请检查解析详情和对账单数据。',
      ar: 'تم العثور على {count} أخطاء تحليل. راجع تفاصيل التحليل وبيانات الكشف.',
      pl: 'Znaleziono {count} błędów parsowania. Przejrzyj szczegóły parsowania i dane wyciągu.',
      it: 'Trovati {count} errori di analisi. Rivedi i dettagli di analisi e i dati dell\'estratto conto.',
      sk: 'Znaleziono {count} błędów parsowania. Przejrzyj szczegóły parsowania i dane wyciągu.',
    }),
    alertParsingWarnings: t({
      ru: 'Есть {count} предупреждений парсинга. Рекомендуется проверить спорные строки.',
      en: '{count} parsing warnings found. It is recommended to review flagged rows.',
      kk: '{count} парсинг ескертуі бар. Белгіленген жолдарды тексеріңіз.',
      de: '{count} Parsing-Warnungen gefunden. Es wird empfohlen, markierte Zeilen zu überprüfen.',
      fr: '{count} avertissements d\'analyse trouvés. Il est recommandé de vérifier les lignes signalées.',
      es: 'Se encontraron {count} advertencias de análisis. Se recomienda revisar las filas marcadas.',
      pt: '{count} avisos de análise encontrados. Recomenda-se revisar as linhas sinalizadas.',
      tr: '{count} ayrıştırma uyarısı bulundu. İşaretli satırların incelenmesi önerilir.',
      uk: 'Є {count} попереджень парсингу. Рекомендується перевірити позначені рядки.',
      zh: '发现 {count} 个解析警告。建议检查标记的行。',
      ar: 'تم العثور على {count} تحذيرات تحليل. يُنصح بمراجعة الصفوف المُعلَّمة.',
      pl: 'Znaleziono {count} ostrzeżeń parsowania. Zaleca się przegląd oznaczonych wierszy.',
      it: 'Trovati {count} avvisi di analisi. Si consiglia di rivedere le righe contrassegnate.',
      sk: 'Znaleziono {count} ostrzeżeń parsowania. Zaleca się przegląd oznaczonych wierszy.',
    }),
    alertNoTransactions: t({
      ru: 'В выписке нет транзакций. Проверьте файл или параметры импорта.',
      en: 'No transactions found in this statement. Check file or import settings.',
      kk: 'Үзіндіде транзакциялар жоқ. Файлды не импорт баптауларын тексеріңіз.',
      de: 'Keine Transaktionen in diesem Kontoauszug gefunden. Überprüfen Sie die Datei oder die Importeinstellungen.',
      fr: 'Aucune transaction trouvée dans ce relevé. Vérifiez le fichier ou les paramètres d\'importation.',
      es: 'No se encontraron transacciones en este extracto. Verifique el archivo o la configuración de importación.',
      pt: 'Nenhuma transação encontrada neste extrato. Verifique o arquivo ou as configurações de importação.',
      tr: 'Bu ekstrede işlem bulunamadı. Dosyayı veya içe aktarma ayarlarını kontrol edin.',
      uk: 'У виписці немає транзакцій. Перевірте файл або параметри імпорту.',
      zh: '此对账单中未找到交易。请检查文件或导入设置。',
      ar: 'لم يتم العثور على معاملات في هذا الكشف. تحقق من الملف أو إعدادات الاستيراد.',
      pl: 'Nie znaleziono transakcji w tym wyciągu. Sprawdź plik lub ustawienia importu.',
      it: 'Nessuna transazione trovata in questo estratto conto. Controlla il file o le impostazioni di importazione.',
      sk: 'Nie znaleziono transakcji w tym wyciągu. Sprawdź plik lub ustawienia importu.',
    }),
  },
} satisfies Dictionary;

export default content;
