import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementEditPageColumns',
  content: {
    date: t({ ru: 'Дата', en: 'Date', kk: 'Күні', de: 'Datum', fr: 'Date', es: 'Fecha', pt: 'Data', tr: 'Tarih', uk: 'Дата', zh: '日期', ar: 'التاريخ', pl: 'Data', it: 'Data', sk: 'Data'}),
    counterparty: t({ ru: 'Контрагент', en: 'Counterparty', kk: 'Контрагент', de: 'Gegenpartei', fr: 'Contrepartie', es: 'Contraparte', pt: 'Contraparte', tr: 'Karşı Taraf', uk: 'Контрагент', zh: '对手方', ar: 'الطرف المقابل', pl: 'Kontrahent', it: 'Controparte', sk: 'Kontrahent'}),
    paymentPurposeShort: t({ ru: 'Назначение платежа', en: 'Payment purpose', kk: 'Төлем мақсаты', de: 'Zahlungszweck', fr: 'Objet du paiement', es: 'Propósito del pago', pt: 'Finalidade do pagamento', tr: 'Ödeme amacı', uk: 'Призначення платежу', zh: '付款用途', ar: 'الغرض من الدفع', pl: 'Cel płatności', it: 'Scopo del pagamento', sk: 'Cel płatności'}),
    expense: t({ ru: 'Расход', en: 'Expense', kk: 'Шығыс', de: 'Ausgabe', fr: 'Dépense', es: 'Gasto', pt: 'Despesa', tr: 'Gider', uk: 'Витрата', zh: '支出', ar: 'مصروف', pl: 'Wydatek', it: 'Spesa', sk: 'Wydatek'}),
    income: t({ ru: 'Доход', en: 'Income', kk: 'Кіріс', de: 'Einnahme', fr: 'Revenu', es: 'Ingreso', pt: 'Receita', tr: 'Gelir', uk: 'Дохід', zh: '收入', ar: 'دخل', pl: 'Przychód', it: 'Entrata', sk: 'Przychód'}),
    category: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
    actions: t({ ru: 'Действия', en: 'Actions', kk: 'Әрекеттер', de: 'Aktionen', fr: 'Actions', es: 'Acciones', pt: 'Ações', tr: 'Eylemler', uk: 'Дії', zh: '操作', ar: 'الإجراءات', pl: 'Akcje', it: 'Azioni', sk: 'Akcje'}),
    transactionDate: t({ ru: 'Дата операции', en: 'Transaction date', kk: 'Операция күні', de: 'Transaktionsdatum', fr: 'Date de transaction', es: 'Fecha de transacción', pt: 'Data da transação', tr: 'İşlem tarihi', uk: 'Дата операції', zh: '交易日期', ar: 'تاريخ المعاملة', pl: 'Data transakcji', it: 'Data transazione', sk: 'Data transakcji'}),
    documentNumber: t({ ru: 'Номер документа', en: 'Document number', kk: 'Құжат нөмірі', de: 'Dokumentnummer', fr: 'Numéro de document', es: 'Número de documento', pt: 'Número do documento', tr: 'Belge numarası', uk: 'Номер документа', zh: '单据编号', ar: 'رقم المستند', pl: 'Numer dokumentu', it: 'Numero documento', sk: 'Numer dokumentu'}),
    counterpartyName: t({
      ru: 'Наименование контрагента',
      en: 'Counterparty name',
      kk: 'Контрагент атауы',
      de: 'Name der Gegenpartei',
      fr: 'Nom de la contrepartie',
      es: 'Nombre de la contraparte',
      pt: 'Nome da contraparte',
      tr: 'Karşı taraf adı',
      uk: 'Найменування контрагента',
      zh: '对手方名称',
      ar: 'اسم الطرف المقابل',
      pl: 'Nazwa kontrahenta',
      it: 'Nome della controparte',
      sk: 'Nazwa kontrahenta',
    }),
    counterpartyBin: t({
      ru: 'БИН/номер счёта контрагента',
      en: 'Counterparty BIN/account',
      kk: 'Контрагент БСН/есепшот',
      de: 'BIN/Kontonummer der Gegenpartei',
      fr: 'BIN/compte de la contrepartie',
      es: 'BIN/cuenta de la contraparte',
      pt: 'BIN/conta da contraparte',
      tr: 'Karşı taraf BIN/hesap',
      uk: 'БІН/номер рахунку контрагента',
      zh: '对手方BIN/账户',
      ar: 'BIN/حساب الطرف المقابل',
      pl: 'BIN/numer konta kontrahenta',
      it: 'BIN/conto della controparte',
      sk: 'BIN/numer konta kontrahenta',
    }),
    counterpartyBank: t({
      ru: 'Реквизиты банка контрагента',
      en: 'Counterparty bank details',
      kk: 'Контрагент банк реквизиттері',
      de: 'Bankdaten der Gegenpartei',
      fr: 'Coordonnées bancaires de la contrepartie',
      es: 'Datos bancarios de la contraparte',
      pt: 'Dados bancários da contraparte',
      tr: 'Karşı taraf banka bilgileri',
      uk: 'Реквізити банку контрагента',
      zh: '对手方银行信息',
      ar: 'تفاصيل بنك الطرف المقابل',
      pl: 'Dane bankowe kontrahenta',
      it: 'Coordinate bancarie della controparte',
      sk: 'Dane bankowe kontrahenta',
    }),
    debit: t({ ru: 'Дебет', en: 'Debit', kk: 'Дебет', de: 'Soll', fr: 'Débit', es: 'Débito', pt: 'Débito', tr: 'Borç', uk: 'Дебет', zh: '借方', ar: 'مدين', pl: 'Debet', it: 'Dare', sk: 'Debet'}),
    credit: t({ ru: 'Кредит', en: 'Credit', kk: 'Кредит', de: 'Haben', fr: 'Crédit', es: 'Crédito', pt: 'Crédito', tr: 'Alacak', uk: 'Кредит', zh: '贷方', ar: 'دائن', pl: 'Kredyt', it: 'Avere', sk: 'Kredyt'}),
    paymentPurpose: t({ ru: 'Назначение платежа', en: 'Payment purpose', kk: 'Төлем мақсаты', de: 'Zahlungszweck', fr: 'Objet du paiement', es: 'Propósito del pago', pt: 'Finalidade do pagamento', tr: 'Ödeme amacı', uk: 'Призначення платежу', zh: '付款用途', ar: 'الغرض من الدفع', pl: 'Cel płatności', it: 'Scopo del pagamento', sk: 'Cel płatności'}),
    categoryId: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
    branchId: t({ ru: 'Филиал', en: 'Branch', kk: 'Филиал', de: 'Filiale', fr: 'Agence', es: 'Sucursal', pt: 'Filial', tr: 'Şube', uk: 'Філія', zh: '分支机构', ar: 'الفرع', pl: 'Oddział', it: 'Filiale', sk: 'Oddział'}),
    walletId: t({ ru: 'Кошелек', en: 'Wallet', kk: 'Әмиян', de: 'Wallet', fr: 'Portefeuille', es: 'Cartera', pt: 'Carteira', tr: 'Cüzdan', uk: 'Гаманець', zh: '钱包', ar: 'المحفظة', pl: 'Portfel', it: 'Portafoglio', sk: 'Portfel'}),
  },
} satisfies Dictionary;

export default content;
