import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementEditPage',
  content: {
    errors: {
      loadData: t({
        ru: 'Не удалось загрузить данные',
        en: 'Failed to load data',
        kk: 'Деректерді жүктеу мүмкін болмады',
        de: 'Daten konnten nicht geladen werden',
        fr: 'Impossible de charger les données',
        es: 'Error al cargar los datos',
        pt: 'Falha ao carregar dados',
        tr: 'Veriler yüklenemedi',
        uk: 'Не вдалося завантажити дані',
        zh: '无法加载数据',
        ar: 'فشل تحميل البيانات',
        pl: 'Nie udało się załadować danych',
        it: 'Impossibile caricare i dati',
        sk: 'Nie udało się załadować danych',
      }),
      saveTransaction: t({
        ru: 'Не удалось сохранить транзакцию',
        en: 'Failed to save transaction',
        kk: 'Транзакцияны сақтау мүмкін болмады',
        de: 'Transaktion konnte nicht gespeichert werden',
        fr: 'Impossible de sauvegarder la transaction',
        es: 'Error al guardar la transacción',
        pt: 'Falha ao salvar transação',
        tr: 'İşlem kaydedilemedi',
        uk: 'Не вдалося зберегти транзакцію',
        zh: '无法保存交易',
        ar: 'فشل حفظ المعاملة',
        pl: 'Nie udało się zapisać transakcji',
        it: 'Impossibile salvare la transazione',
        sk: 'Nie udało się zapisać transakcji',
      }),
      updateStatement: t({
        ru: 'Не удалось обновить данные выписки',
        en: 'Failed to update statement data',
        kk: 'Үзінді деректерін жаңарту мүмкін болмады',
        de: 'Kontoauszugsdaten konnten nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour les données du relevé',
        es: 'Error al actualizar los datos del extracto',
        pt: 'Falha ao atualizar dados do extrato',
        tr: 'Ekstre verileri güncellenemedi',
        uk: 'Не вдалося оновити дані виписки',
        zh: '无法更新对账单数据',
        ar: 'فشل تحديث بيانات الكشف',
        pl: 'Nie udało się zaktualizować danych wyciągu',
        it: 'Impossibile aggiornare i dati dell\'estratto conto',
        sk: 'Nie udało się zaktualizować danych wyciągu',
      }),
      deleteTransaction: t({
        ru: 'Не удалось удалить транзакцию',
        en: 'Failed to delete transaction',
        kk: 'Транзакцияны жою мүмкін болмады',
        de: 'Transaktion konnte nicht gelöscht werden',
        fr: 'Impossible de supprimer la transaction',
        es: 'Error al eliminar la transacción',
        pt: 'Falha ao excluir transação',
        tr: 'İşlem silinemedi',
        uk: 'Не вдалося видалити транзакцію',
        zh: '无法删除交易',
        ar: 'فشل حذف المعاملة',
        pl: 'Nie udało się usunąć transakcji',
        it: 'Impossibile eliminare la transazione',
        sk: 'Nie udało się usunąć transakcji',
      }),
      updateTransactions: t({
        ru: 'Не удалось обновить транзакции',
        en: 'Failed to update transactions',
        kk: 'Транзакцияларды жаңарту мүмкін болмады',
        de: 'Transaktionen konnten nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour les transactions',
        es: 'Error al actualizar las transacciones',
        pt: 'Falha ao atualizar transações',
        tr: 'İşlemler güncellenemedi',
        uk: 'Не вдалося оновити транзакції',
        zh: '无法更新交易',
        ar: 'فشل تحديث المعاملات',
        pl: 'Nie udało się zaktualizować transakcji',
        it: 'Impossibile aggiornare le transazioni',
        sk: 'Nie udało się zaktualizować transakcji',
      }),
      deleteTransactions: t({
        ru: 'Не удалось удалить транзакции',
        en: 'Failed to delete transactions',
        kk: 'Транзакцияларды жою мүмкін болмады',
        de: 'Transaktionen konnten nicht gelöscht werden',
        fr: 'Impossible de supprimer les transactions',
        es: 'Error al eliminar las transacciones',
        pt: 'Falha ao excluir transações',
        tr: 'İşlemler silinemedi',
        uk: 'Не вдалося видалити транзакції',
        zh: '无法删除交易',
        ar: 'فشل حذف المعاملات',
        pl: 'Nie udało się usunąć transakcji',
        it: 'Impossibile eliminare le transazioni',
        sk: 'Nie udało się usunąć transakcji',
      }),
      assignCategory: t({
        ru: 'Не удалось назначить категорию',
        en: 'Failed to assign category',
        kk: 'Санатты тағайындау мүмкін болмады',
        de: 'Kategorie konnte nicht zugewiesen werden',
        fr: 'Impossible d\'assigner la catégorie',
        es: 'Error al asignar la categoría',
        pt: 'Falha ao atribuir categoria',
        tr: 'Kategori atanamadı',
        uk: 'Не вдалося призначити категорію',
        zh: '无法分配类别',
        ar: 'فشل تعيين الفئة',
        pl: 'Nie udało się przypisać kategorii',
        it: 'Impossibile assegnare la categoria',
        sk: 'Nie udało się przypisać kategorii',
      }),
      selectAtLeastOneTransaction: t({
        ru: 'Выберите хотя бы одну транзакцию',
        en: 'Select at least one transaction',
        kk: 'Кемінде бір транзакцияны таңдаңыз',
        de: 'Wählen Sie mindestens eine Transaktion aus',
        fr: 'Sélectionnez au moins une transaction',
        es: 'Seleccione al menos una transacción',
        pt: 'Selecione pelo menos uma transação',
        tr: 'En az bir işlem seçin',
        uk: 'Виберіть принаймні одну транзакцію',
        zh: '请至少选择一笔交易',
        ar: 'حدد معاملة واحدة على الأقل',
        pl: 'Wybierz co najmniej jedną transakcję',
        it: 'Seleziona almeno una transazione',
        sk: 'Wybierz co najmniej jedną transakcję',
      }),
      selectTransactionsForCategory: t({
        ru: 'Выберите транзакции, чтобы назначить категорию',
        en: 'Select transactions to assign a category',
        kk: 'Санат тағайындау үшін транзакцияларды таңдаңыз',
        de: 'Transaktionen auswählen, um eine Kategorie zuzuweisen',
        fr: 'Sélectionnez des transactions pour assigner une catégorie',
        es: 'Seleccione transacciones para asignar una categoría',
        pt: 'Selecione transações para atribuir uma categoria',
        tr: 'Kategori atamak için işlemleri seçin',
        uk: 'Виберіть транзакції, щоб призначити категорію',
        zh: '选择交易以分配类别',
        ar: 'حدد المعاملات لتعيين فئة',
        pl: 'Wybierz transakcje, aby przypisać kategorię',
        it: 'Seleziona le transazioni per assegnare una categoria',
        sk: 'Wybierz transakcje, aby przypisać kategorię',
      }),
      selectCategoryToApply: t({
        ru: 'Выберите категорию для назначения',
        en: 'Select a category to apply',
        kk: 'Тағайындау үшін санатты таңдаңыз',
        de: 'Wählen Sie eine Kategorie zum Anwenden',
        fr: 'Sélectionnez une catégorie à appliquer',
        es: 'Seleccione una categoría para aplicar',
        pt: 'Selecione uma categoria para aplicar',
        tr: 'Uygulamak için bir kategori seçin',
        uk: 'Виберіть категорію для призначення',
        zh: '选择要应用的类别',
        ar: 'حدد فئة للتطبيق',
        pl: 'Wybierz kategorię do zastosowania',
        it: 'Seleziona una categoria da applicare',
        sk: 'Wybierz kategorię do zastosowania',
      }),
    },
    confirms: {
      deleteOne: t({
        ru: 'Вы уверены, что хотите удалить эту транзакцию?',
        en: 'Are you sure you want to delete this transaction?',
        kk: 'Бұл транзакцияны жойғыңыз келетініне сенімдісіз бе?',
        de: 'Sind Sie sicher, dass Sie diese Transaktion löschen möchten?',
        fr: 'Êtes-vous sûr de vouloir supprimer cette transaction ?',
        es: '¿Está seguro de que desea eliminar esta transacción?',
        pt: 'Tem certeza de que deseja excluir esta transação?',
        tr: 'Bu işlemi silmek istediğinizden emin misiniz?',
        uk: 'Ви впевнені, що хочете видалити цю транзакцію?',
        zh: '您确定要删除此交易吗？',
        ar: 'هل أنت متأكد من رغبتك في حذف هذه المعاملة؟',
        pl: 'Czy na pewno chcesz usunąć tę transakcję?',
        it: 'Sei sicuro di voler eliminare questa transazione?',
        sk: 'Czy na pewno chcesz usunąć tę transakcję?',
      }),
      deleteManyPrefix: t({
        ru: 'Вы уверены, что хотите удалить ',
        en: 'Are you sure you want to delete ',
        kk: 'Жойғыңыз келетініне сенімдісіз бе: ',
        de: 'Sind Sie sicher, dass Sie ',
        fr: 'Êtes-vous sûr de vouloir supprimer ',
        es: '¿Está seguro de que desea eliminar ',
        pt: 'Tem certeza de que deseja excluir ',
        tr: 'Silmek istediğinizden emin misiniz: ',
        uk: 'Ви впевнені, що хочете видалити ',
        zh: '您确定要删除',
        ar: 'هل أنت متأكد من رغبتك في حذف ',
        pl: 'Czy na pewno chcesz usunąć ',
        it: 'Sei sicuro di voler eliminare ',
        sk: 'Czy na pewno chcesz usunąć ',
      }),
      deleteManySuffix: t({ ru: ' транзакций?', en: ' transactions?', kk: ' транзакция?', de: ' Transaktionen löschen möchten?', fr: ' transactions ?', es: ' transacciones?', pt: ' transações?', tr: ' işlemi?', uk: ' транзакцій?', zh: '笔交易吗？', ar: ' معاملات؟', pl: ' transakcji?', it: ' transazioni?', sk: ' transakcji?'}),
    },
    labels: {
      back: t({ ru: 'Назад', en: 'Back', kk: 'Артқа', de: 'Zurück', fr: 'Retour', es: 'Atrás', pt: 'Voltar', tr: 'Geri', uk: 'Назад', zh: '返回', ar: 'رجوع', pl: 'Wstecz', it: 'Indietro', sk: 'Wstecz'}),
      editTitlePrefix: t({
        ru: 'Редактирование выписки: ',
        en: 'Edit statement: ',
        kk: 'Үзіндіні өңдеу: ',
        de: 'Kontoauszug bearbeiten: ',
        fr: 'Modifier le relevé : ',
        es: 'Editar extracto: ',
        pt: 'Editar extrato: ',
        tr: 'Ekstreyi düzenle: ',
        uk: 'Редагування виписки: ',
        zh: '编辑对账单：',
        ar: 'تعديل الكشف: ',
        pl: 'Edytuj wyciąg: ',
        it: 'Modifica estratto conto: ',
        sk: 'Edytuj wyciąg: ',
      }),
      transactionsCount: t({ ru: 'транзакций', en: 'transactions', kk: 'транзакция', de: 'Transaktionen', fr: 'transactions', es: 'transacciones', pt: 'transações', tr: 'işlem', uk: 'транзакцій', zh: '笔交易', ar: 'معاملات', pl: 'transakcji', it: 'transazioni', sk: 'transakcji'}),
      assignCategory: t({
        ru: 'Назначить категорию',
        en: 'Assign category',
        kk: 'Санат тағайындау',
        de: 'Kategorie zuweisen',
        fr: 'Assigner une catégorie',
        es: 'Asignar categoría',
        pt: 'Atribuir categoria',
        tr: 'Kategori ata',
        uk: 'Призначити категорію',
        zh: '分配类别',
        ar: 'تعيين الفئة',
        pl: 'Przypisz kategorię',
        it: 'Assegna categoria',
        sk: 'Przypisz kategorię',
      }),
      saveSelectedPrefix: t({
        ru: 'Сохранить выбранные (',
        en: 'Save selected (',
        kk: 'Таңдалғанды сақтау (',
        de: 'Ausgewählte speichern (',
        fr: 'Sauvegarder la sélection (',
        es: 'Guardar seleccionados (',
        pt: 'Salvar selecionados (',
        tr: 'Seçilenleri kaydet (',
        uk: 'Зберегти вибрані (',
        zh: '保存已选 (',
        ar: 'حفظ المحدد (',
        pl: 'Zapisz wybrane (',
        it: 'Salva selezionati (',
        sk: 'Zapisz wybrane (',
      }),
      saveSelectedSuffix: t({ ru: ')', en: ')', kk: ')', de: ')', fr: ')', es: ')', pt: ')', tr: ')', uk: ')', zh: ')', ar: ')', pl: ')', it: ')', sk: ')'}),
      deleteSelected: t({ ru: 'Удалить выбранные', en: 'Delete selected', kk: 'Таңдалғанды жою', de: 'Ausgewählte löschen', fr: 'Supprimer la sélection', es: 'Eliminar seleccionados', pt: 'Excluir selecionados', tr: 'Seçilenleri sil', uk: 'Видалити вибрані', zh: '删除已选', ar: 'حذف المحدد', pl: 'Usuń wybrane', it: 'Elimina selezionati', sk: 'Usuń wybrane'}),
      changesSaved: t({
        ru: 'Изменения успешно сохранены!',
        en: 'Changes saved successfully!',
        kk: 'Өзгерістер сәтті сақталды!',
        de: 'Änderungen erfolgreich gespeichert!',
        fr: 'Modifications enregistrées avec succès !',
        es: '¡Cambios guardados exitosamente!',
        pt: 'Alterações salvas com sucesso!',
        tr: 'Değişiklikler başarıyla kaydedildi!',
        uk: 'Зміни успішно збережено!',
        zh: '更改已成功保存！',
        ar: 'تم حفظ التغييرات بنجاح!',
        pl: 'Zmiany zostały pomyślnie zapisane!',
        it: 'Modifiche salvate con successo!',
        sk: 'Zmiany zostały pomyślnie zapisane!',
      }),
      infoHint: t({
        ru: 'После загрузки сразу переходите к проверке: строки без категории подсвечены, выберите им категорию вручную или через массовое действие.',
        en: 'After upload, start reviewing right away: rows without a category are highlighted. Assign categories manually or in bulk.',
        kk: 'Жүктегеннен кейін бірден тексеріңіз: санаты жоқ жолдар белгіленген. Санатты қолмен немесе жаппай әрекет арқылы тағайындаңыз.',
        de: 'Nach dem Hochladen sofort mit der Überprüfung beginnen: Zeilen ohne Kategorie sind hervorgehoben. Kategorien manuell oder in Masse zuweisen.',
        fr: 'Après le téléchargement, commencez immédiatement la vérification : les lignes sans catégorie sont surlignées. Assignez les catégories manuellement ou en masse.',
        es: 'Después de cargar, comience a revisar de inmediato: las filas sin categoría están resaltadas. Asigne categorías manualmente o en masa.',
        pt: 'Após o upload, comece a revisar imediatamente: linhas sem categoria estão destacadas. Atribua categorias manualmente ou em massa.',
        tr: 'Yükledikten sonra hemen incelemeye başlayın: kategorisiz satırlar vurgulanmıştır. Kategorileri manuel veya toplu olarak atayın.',
        uk: 'Після завантаження одразу переходьте до перевірки: рядки без категорії підсвічені, призначте їм категорію вручну або через масову дію.',
        zh: '上传后立即开始审核：没有类别的行已高亮显示。手动或批量分配类别。',
        ar: 'بعد الرفع، ابدأ المراجعة فوراً: الصفوف بدون فئة مظللة. قم بتعيين الفئات يدوياً أو بشكل جماعي.',
        pl: 'Po przesłaniu od razu przejdź do weryfikacji: wiersze bez kategorii są podświetlone. Przypisz kategorie ręcznie lub zbiorczo.',
        it: 'Dopo il caricamento, inizia subito la revisione: le righe senza categoria sono evidenziate. Assegna le categorie manualmente o in blocco.',
        sk: 'Po przesłaniu od razu przejdź do weryfikacji: wiersze bez kategorii są podświetlone. Przypisz kategorie ręcznie lub zbiorczo.',
      }),
      statementInfoTitle: t({
        ru: 'Информация о выписке',
        en: 'Statement information',
        kk: 'Үзінді туралы ақпарат',
        de: 'Kontoauszugsinformationen',
        fr: 'Informations sur le relevé',
        es: 'Información del extracto',
        pt: 'Informações do extrato',
        tr: 'Ekstre bilgileri',
        uk: 'Інформація про виписку',
        zh: '对账单信息',
        ar: 'معلومات الكشف',
        pl: 'Informacje o wyciągu',
        it: 'Informazioni sull\'estratto conto',
        sk: 'Informacje o wyciągu',
      }),
      saveStatementData: t({
        ru: 'Сохранить данные выписки',
        en: 'Save statement data',
        kk: 'Үзінді деректерін сақтау',
        de: 'Kontoauszugsdaten speichern',
        fr: 'Enregistrer les données du relevé',
        es: 'Guardar datos del extracto',
        pt: 'Salvar dados do extrato',
        tr: 'Ekstre verilerini kaydet',
        uk: 'Зберегти дані виписки',
        zh: '保存对账单数据',
        ar: 'حفظ بيانات الكشف',
        pl: 'Zapisz dane wyciągu',
        it: 'Salva dati estratto conto',
        sk: 'Zapisz dane wyciągu',
      }),
      periodFrom: t({ ru: 'Период с', en: 'Period from', kk: 'Кезең (бастап)', de: 'Zeitraum von', fr: 'Période du', es: 'Período desde', pt: 'Período de', tr: 'Dönem başlangıcı', uk: 'Період з', zh: '期间从', ar: 'الفترة من', pl: 'Okres od', it: 'Periodo da', sk: 'Okres od'}),
      periodTo: t({ ru: 'Период по', en: 'Period to', kk: 'Кезең (дейін)', de: 'Zeitraum bis', fr: 'Période au', es: 'Período hasta', pt: 'Período até', tr: 'Dönem sonu', uk: 'Період по', zh: '期间至', ar: 'الفترة إلى', pl: 'Okres do', it: 'Periodo fino a', sk: 'Okres do'}),
      balanceStart: t({ ru: 'Остаток на начало', en: 'Opening balance', kk: 'Бастапқы қалдық', de: 'Anfangssaldo', fr: 'Solde d\'ouverture', es: 'Saldo inicial', pt: 'Saldo inicial', tr: 'Açılış bakiyesi', uk: 'Залишок на початок', zh: '期初余额', ar: 'الرصيد الافتتاحي', pl: 'Saldo otwarcia', it: 'Saldo iniziale', sk: 'Saldo otwarcia'}),
      balanceEnd: t({ ru: 'Остаток на конец', en: 'Closing balance', kk: 'Соңғы қалдық', de: 'Abschlusssaldo', fr: 'Solde de clôture', es: 'Saldo final', pt: 'Saldo final', tr: 'Kapanış bakiyesi', uk: 'Залишок на кінець', zh: '期末余额', ar: 'الرصيد الختامي', pl: 'Saldo zamknięcia', it: 'Saldo finale', sk: 'Saldo zamknięcia'}),
      expenses: t({ ru: 'Расходы', en: 'Expenses', kk: 'Шығыстар', de: 'Ausgaben', fr: 'Dépenses', es: 'Gastos', pt: 'Despesas', tr: 'Giderler', uk: 'Витрати', zh: '支出', ar: 'المصروفات', pl: 'Wydatki', it: 'Spese', sk: 'Wydatki'}),
      income: t({ ru: 'Доходы', en: 'Income', kk: 'Кіріс', de: 'Einnahmen', fr: 'Revenus', es: 'Ingresos', pt: 'Receitas', tr: 'Gelirler', uk: 'Доходи', zh: '收入', ar: 'الدخل', pl: 'Przychody', it: 'Entrate', sk: 'Przychody'}),
      startDate: t({ ru: 'Дата начала', en: 'Start date', kk: 'Басталу күні', de: 'Startdatum', fr: 'Date de début', es: 'Fecha de inicio', pt: 'Data de início', tr: 'Başlangıç tarihi', uk: 'Дата початку', zh: '开始日期', ar: 'تاريخ البدء', pl: 'Data rozpoczęcia', it: 'Data inizio', sk: 'Data rozpoczęcia'}),
      endDate: t({ ru: 'Дата окончания', en: 'End date', kk: 'Аяқталу күні', de: 'Enddatum', fr: 'Date de fin', es: 'Fecha de fin', pt: 'Data de fim', tr: 'Bitiş tarihi', uk: 'Дата закінчення', zh: '结束日期', ar: 'تاريخ الانتهاء', pl: 'Data zakończenia', it: 'Data fine', sk: 'Data zakończenia'}),
      notSpecified: t({ ru: 'Не указан', en: 'Not specified', kk: 'Көрсетілмеген', de: 'Nicht angegeben', fr: 'Non spécifié', es: 'No especificado', pt: 'Não especificado', tr: 'Belirtilmedi', uk: 'Не вказано', zh: '未指定', ar: 'غير محدد', pl: 'Nie określono', it: 'Non specificato', sk: 'Nie określono'}),
      openingBalance: t({ ru: 'Начальный баланс', en: 'Opening balance', kk: 'Бастапқы қалдық', de: 'Anfangssaldo', fr: 'Solde d\'ouverture', es: 'Saldo inicial', pt: 'Saldo inicial', tr: 'Açılış bakiyesi', uk: 'Початковий баланс', zh: '期初余额', ar: 'الرصيد الافتتاحي', pl: 'Saldo otwarcia', it: 'Saldo iniziale', sk: 'Saldo otwarcia'}),
      enterOpeningBalance: t({
        ru: 'Введите начальный баланс',
        en: 'Enter opening balance',
        kk: 'Бастапқы қалдықты енгізіңіз',
        de: 'Anfangssaldo eingeben',
        fr: 'Saisir le solde d\'ouverture',
        es: 'Ingresar saldo inicial',
        pt: 'Inserir saldo inicial',
        tr: 'Açılış bakiyesini girin',
        uk: 'Введіть початковий баланс',
        zh: '输入期初余额',
        ar: 'أدخل الرصيد الافتتاحي',
        pl: 'Wprowadź saldo otwarcia',
        it: 'Inserisci saldo iniziale',
        sk: 'Wprowadź saldo otwarcia',
      }),
      selectedTransactions: t({
        ru: 'Выбрано: {count} транзакций',
        en: 'Selected: {count} transactions',
        kk: 'Таңдалғаны: {count} транзакция',
        de: 'Ausgewählt: {count} Transaktionen',
        fr: 'Sélectionné : {count} transactions',
        es: 'Seleccionados: {count} transacciones',
        pt: 'Selecionados: {count} transações',
        tr: 'Seçildi: {count} işlem',
        uk: 'Вибрано: {count} транзакцій',
        zh: '已选: {count} 笔交易',
        ar: 'المحدد: {count} معاملات',
        pl: 'Wybrano: {count} transakcji',
        it: 'Selezionati: {count} transazioni',
        sk: 'Wybrano: {count} transakcji',
      }),
      save: t({ ru: 'Сохранить', en: 'Save', kk: 'Сақтау', de: 'Speichern', fr: 'Enregistrer', es: 'Guardar', pt: 'Salvar', tr: 'Kaydet', uk: 'Зберегти', zh: '保存', ar: 'حفظ', pl: 'Zapisz', it: 'Salva', sk: 'Zapisz'}),
      delete: t({ ru: 'Удалить', en: 'Delete', kk: 'Жою', de: 'Löschen', fr: 'Supprimer', es: 'Eliminar', pt: 'Excluir', tr: 'Sil', uk: 'Видалити', zh: '删除', ar: 'حذف', pl: 'Usuń', it: 'Elimina', sk: 'Usuń'}),
      fromFilePrefix: t({ ru: 'Из файла: ', en: 'From file: ', kk: 'Файлдан: ', de: 'Aus Datei: ', fr: 'Du fichier : ', es: 'Del archivo: ', pt: 'Do arquivo: ', tr: 'Dosyadan: ', uk: 'З файлу: ', zh: '来自文件：', ar: 'من الملف: ', pl: 'Z pliku: ', it: 'Dal file: ', sk: 'Z pliku: '}),
      enterManuallyHint: t({
        ru: 'Укажите вручную, если не подтянулось',
        en: 'Enter manually if it was not detected',
        kk: 'Егер анықталмаса, қолмен енгізіңіз',
        de: 'Manuell eingeben, falls nicht erkannt',
        fr: 'Saisir manuellement si non détecté',
        es: 'Ingresar manualmente si no fue detectado',
        pt: 'Inserir manualmente se não foi detectado',
        tr: 'Algılanmadıysa manuel girin',
        uk: 'Вкажіть вручну, якщо не підтягнулося',
        zh: '如果未自动检测到，请手动输入',
        ar: 'أدخل يدوياً إذا لم يتم اكتشافه',
        pl: 'Wprowadź ręcznie, jeśli nie wykryto',
        it: 'Inserisci manualmente se non rilevato',
        sk: 'Wprowadź ręcznie, jeśli nie wykryto',
      }),
      parsingDetails: t({
        ru: 'Детали парсинга',
        en: 'Parsing details',
        kk: 'Парсинг мәліметтері',
        de: 'Parsing-Details',
        fr: 'Détails d\'analyse',
        es: 'Detalles de análisis',
        pt: 'Detalhes de análise',
        tr: 'Ayrıştırma ayrıntıları',
        uk: 'Деталі парсингу',
        zh: '解析详情',
        ar: 'تفاصيل التحليل',
        pl: 'Szczegóły parsowania',
        it: 'Dettagli di analisi',
        sk: 'Szczegóły parsowania',
      }),
      generalInfo: t({ ru: 'Общая информация', en: 'General information', kk: 'Жалпы ақпарат', de: 'Allgemeine Informationen', fr: 'Informations générales', es: 'Información general', pt: 'Informações gerais', tr: 'Genel bilgiler', uk: 'Загальна інформація', zh: '一般信息', ar: 'معلومات عامة', pl: 'Informacje ogólne', it: 'Informazioni generali', sk: 'Informacje ogólne'}),
      bank: t({ ru: 'Банк', en: 'Bank', kk: 'Банк', de: 'Bank', fr: 'Banque', es: 'Banco', pt: 'Banco', tr: 'Banka', uk: 'Банк', zh: '银行', ar: 'البنك', pl: 'Bank', it: 'Banca', sk: 'Bank'}),
      bankDetectedBy: t({
        ru: 'Определено по',
        en: 'Detected by',
        kk: 'Қалай анықталды',
        de: 'Erkannt durch',
        fr: 'Détecté par',
        es: 'Detectado por',
        pt: 'Detectado por',
        tr: 'Algılayan',
        uk: 'Визначено по',
        zh: '检测方式',
        ar: 'تم الكشف بواسطة',
        pl: 'Wykryto przez',
        it: 'Rilevato da',
        sk: 'Wykryto przez',
      }),
      bankEvidence: t({
        ru: 'Основание',
        en: 'Evidence',
        kk: 'Негіздеме',
        de: 'Nachweis',
        fr: 'Preuve',
        es: 'Evidencia',
        pt: 'Evidência',
        tr: 'Kanıt',
        uk: 'Підстава',
        zh: '依据',
        ar: 'الدليل',
        pl: 'Dowód',
        it: 'Evidenza',
        sk: 'Dowód',
      }),
      otherBankMentions: t({
        ru: 'Упоминания других банков',
        en: 'Other bank mentions',
        kk: 'Басқа банктердің аталуы',
        de: 'Erwähnungen anderer Banken',
        fr: 'Mentions d\'autres banques',
        es: 'Menciones de otros bancos',
        pt: 'Menções de outros bancos',
        tr: 'Diğer banka bahisleri',
        uk: 'Згадки інших банків',
        zh: '其他银行提及',
        ar: 'إشارات إلى بنوك أخرى',
        pl: 'Wzmianki o innych bankach',
        it: 'Menzioni di altre banche',
        sk: 'Wzmianki o innych bankach',
      }),
      format: t({ ru: 'Формат', en: 'Format', kk: 'Формат', de: 'Format', fr: 'Format', es: 'Formato', pt: 'Formato', tr: 'Format', uk: 'Формат', zh: '格式', ar: 'الصيغة', pl: 'Format', it: 'Formato', sk: 'Format'}),
      parser: t({ ru: 'Парсер', en: 'Parser', kk: 'Парсер', de: 'Parser', fr: 'Analyseur', es: 'Analizador', pt: 'Analisador', tr: 'Ayrıştırıcı', uk: 'Парсер', zh: '解析器', ar: 'المحلل', pl: 'Parser', it: 'Parser', sk: 'Parser'}),
      processingTime: t({ ru: 'Время обработки', en: 'Processing time', kk: 'Өңдеу уақыты', de: 'Verarbeitungszeit', fr: 'Temps de traitement', es: 'Tiempo de procesamiento', pt: 'Tempo de processamento', tr: 'İşleme süresi', uk: 'Час обробки', zh: '处理时间', ar: 'وقت المعالجة', pl: 'Czas przetwarzania', it: 'Tempo di elaborazione', sk: 'Czas przetwarzania'}),
      extractedMetadata: t({
        ru: 'Извлеченные метаданные',
        en: 'Extracted metadata',
        kk: 'Шығарылған метадеректер',
        de: 'Extrahierte Metadaten',
        fr: 'Métadonnées extraites',
        es: 'Metadatos extraídos',
        pt: 'Metadados extraídos',
        tr: 'Çıkarılan meta veriler',
        uk: 'Витягнуті метадані',
        zh: '提取的元数据',
        ar: 'البيانات الوصفية المستخرجة',
        pl: 'Wyodrębnione metadane',
        it: 'Metadati estratti',
        sk: 'Wyodrębnione metadane',
      }),
      account: t({ ru: 'Счет', en: 'Account', kk: 'Есепшот', de: 'Konto', fr: 'Compte', es: 'Cuenta', pt: 'Conta', tr: 'Hesap', uk: 'Рахунок', zh: '账户', ar: 'الحساب', pl: 'Konto', it: 'Conto', sk: 'Konto'}),
      period: t({ ru: 'Период', en: 'Period', kk: 'Кезең', de: 'Zeitraum', fr: 'Période', es: 'Período', pt: 'Período', tr: 'Dönem', uk: 'Період', zh: '期间', ar: 'الفترة', pl: 'Okres', it: 'Periodo', sk: 'Okres'}),
      parsingStats: t({
        ru: 'Статистика парсинга',
        en: 'Parsing statistics',
        kk: 'Парсинг статистикасы',
        de: 'Parsing-Statistiken',
        fr: 'Statistiques d\'analyse',
        es: 'Estadísticas de análisis',
        pt: 'Estatísticas de análise',
        tr: 'Ayrıştırma istatistikleri',
        uk: 'Статистика парсингу',
        zh: '解析统计',
        ar: 'إحصائيات التحليل',
        pl: 'Statystyki parsowania',
        it: 'Statistiche di analisi',
        sk: 'Statystyki parsowania',
      }),
      foundTransactions: t({
        ru: 'Найдено транзакций',
        en: 'Transactions found',
        kk: 'Табылған транзакциялар',
        de: 'Gefundene Transaktionen',
        fr: 'Transactions trouvées',
        es: 'Transacciones encontradas',
        pt: 'Transações encontradas',
        tr: 'Bulunan işlemler',
        uk: 'Знайдено транзакцій',
        zh: '找到的交易',
        ar: 'المعاملات الموجودة',
        pl: 'Znalezione transakcje',
        it: 'Transazioni trovate',
        sk: 'Znalezione transakcje',
      }),
      createdTransactions: t({
        ru: 'Создано транзакций',
        en: 'Transactions created',
        kk: 'Жасалған транзакциялар',
        de: 'Erstellte Transaktionen',
        fr: 'Transactions créées',
        es: 'Transacciones creadas',
        pt: 'Transações criadas',
        tr: 'Oluşturulan işlemler',
        uk: 'Створено транзакцій',
        zh: '已创建的交易',
        ar: 'المعاملات المُنشأة',
        pl: 'Utworzone transakcje',
        it: 'Transazioni create',
        sk: 'Utworzone transakcje',
      }),
      processedLines: t({ ru: 'Обработано строк', en: 'Lines processed', kk: 'Өңделген жолдар', de: 'Verarbeitete Zeilen', fr: 'Lignes traitées', es: 'Líneas procesadas', pt: 'Linhas processadas', tr: 'İşlenen satırlar', uk: 'Оброблено рядків', zh: '已处理行数', ar: 'الأسطر المعالجة', pl: 'Przetworzone wiersze', it: 'Righe elaborate', sk: 'Przetworzone wiersze'}),
      errors: t({ ru: 'Ошибки', en: 'Errors', kk: 'Қателер', de: 'Fehler', fr: 'Erreurs', es: 'Errores', pt: 'Erros', tr: 'Hatalar', uk: 'Помилки', zh: '错误', ar: 'الأخطاء', pl: 'Błędy', it: 'Errori', sk: 'Błędy'}),
      warnings: t({ ru: 'Предупреждения', en: 'Warnings', kk: 'Ескертулер', de: 'Warnungen', fr: 'Avertissements', es: 'Advertencias', pt: 'Avisos', tr: 'Uyarılar', uk: 'Попередження', zh: '警告', ar: 'التحذيرات', pl: 'Ostrzeżenia', it: 'Avvisi', sk: 'Ostrzeżenia'}),
      processingLogPrefix: t({
        ru: 'Лог обработки (',
        en: 'Processing log (',
        kk: 'Өңдеу журналы (',
        de: 'Verarbeitungsprotokoll (',
        fr: 'Journal de traitement (',
        es: 'Registro de procesamiento (',
        pt: 'Log de processamento (',
        tr: 'İşleme günlüğü (',
        uk: 'Лог обробки (',
        zh: '处理日志 (',
        ar: 'سجل المعالجة (',
        pl: 'Dziennik przetwarzania (',
        it: 'Log di elaborazione (',
        sk: 'Dziennik przetwarzania (',
      }),
      processingLogSuffix: t({ ru: ' записей)', en: ' entries)', kk: ' жазба)', de: ' Einträge)', fr: ' entrées)', es: ' entradas)', pt: ' entradas)', tr: ' giriş)', uk: ' записів)', zh: ' 条记录)', ar: ' إدخالات)', pl: ' wpisów)', it: ' voci)', sk: ' wpisów)'}),
      actions: t({ ru: 'Действия', en: 'Actions', kk: 'Әрекеттер', de: 'Aktionen', fr: 'Actions', es: 'Acciones', pt: 'Ações', tr: 'Eylemler', uk: 'Дії', zh: '操作', ar: 'الإجراءات', pl: 'Akcje', it: 'Azioni', sk: 'Akcje'}),
      noCategory: t({ ru: 'Нет категории', en: 'No category', kk: 'Санат жоқ', de: 'Keine Kategorie', fr: 'Aucune catégorie', es: 'Sin categoría', pt: 'Sem categoria', tr: 'Kategori yok', uk: 'Немає категорії', zh: '无类别', ar: 'لا توجد فئة', pl: 'Brak kategorii', it: 'Nessuna categoria', sk: 'Brak kategorii'}),
      binPlaceholder: t({ ru: 'БИН', en: 'BIN', kk: 'БСН', de: 'BIN', fr: 'BIN', es: 'BIN', pt: 'BIN', tr: 'BIN', uk: 'БІН', zh: 'BIN', ar: 'رقم BIN', pl: 'BIN', it: 'BIN', sk: 'BIN'}),
      accountNumberPlaceholder: t({
        ru: 'Номер счёта',
        en: 'Account number',
        kk: 'Есепшот нөмірі',
        de: 'Kontonummer',
        fr: 'Numéro de compte',
        es: 'Número de cuenta',
        pt: 'Número de conta',
        tr: 'Hesap numarası',
        uk: 'Номер рахунку',
        zh: '账号',
        ar: 'رقم الحساب',
        pl: 'Numer konta',
        it: 'Numero di conto',
        sk: 'Numer konta',
      }),
      category: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
      branch: t({ ru: 'Филиал', en: 'Branch', kk: 'Филиал', de: 'Filiale', fr: 'Agence', es: 'Sucursal', pt: 'Filial', tr: 'Şube', uk: 'Філія', zh: '分支机构', ar: 'الفرع', pl: 'Oddział', it: 'Filiale', sk: 'Oddział'}),
      wallet: t({ ru: 'Кошелек', en: 'Wallet', kk: 'Әмиян', de: 'Wallet', fr: 'Portefeuille', es: 'Cartera', pt: 'Carteira', tr: 'Cüzdan', uk: 'Гаманець', zh: '钱包', ar: 'المحفظة', pl: 'Portfel', it: 'Portafoglio', sk: 'Portfel'}),
      noCategoryOption: t({ ru: 'Без категории', en: 'No category', kk: 'Санатсыз', de: 'Ohne Kategorie', fr: 'Sans catégorie', es: 'Sin categoría', pt: 'Sem categoria', tr: 'Kategorisiz', uk: 'Без категорії', zh: '无类别', ar: 'بدون فئة', pl: 'Bez kategorii', it: 'Senza categoria', sk: 'Bez kategorii'}),
      noBranchOption: t({ ru: 'Без филиала', en: 'No branch', kk: 'Филиалсыз', de: 'Ohne Filiale', fr: 'Sans agence', es: 'Sin sucursal', pt: 'Sem filial', tr: 'Şubesiz', uk: 'Без філії', zh: '无分支机构', ar: 'بدون فرع', pl: 'Bez oddziału', it: 'Senza filiale', sk: 'Bez oddziału'}),
      noWalletOption: t({ ru: 'Без кошелька', en: 'No wallet', kk: 'Әмиянсыз', de: 'Ohne Wallet', fr: 'Sans portefeuille', es: 'Sin cartera', pt: 'Sem carteira', tr: 'Cüzdansız', uk: 'Без гаманця', zh: '无钱包', ar: 'بدون محفظة', pl: 'Bez portfela', it: 'Senza portafoglio', sk: 'Bez portfela'}),
      notSelected: t({ ru: 'Не выбрано', en: 'Not selected', kk: 'Таңдалмаған', de: 'Nicht ausgewählt', fr: 'Non sélectionné', es: 'No seleccionado', pt: 'Não selecionado', tr: 'Seçilmedi', uk: 'Не вибрано', zh: '未选择', ar: 'غير محدد', pl: 'Nie wybrano', it: 'Non selezionato', sk: 'Nie wybrano'}),
      bulkCategoryTitlePrefix: t({
        ru: 'Назначить категорию (',
        en: 'Assign category (',
        kk: 'Санат тағайындау (',
        de: 'Kategorie zuweisen (',
        fr: 'Assigner une catégorie (',
        es: 'Asignar categoría (',
        pt: 'Atribuir categoria (',
        tr: 'Kategori ata (',
        uk: 'Призначити категорію (',
        zh: '分配类别 (',
        ar: 'تعيين الفئة (',
        pl: 'Przypisz kategorię (',
        it: 'Assegna categoria (',
        sk: 'Przypisz kategorię (',
      }),
      bulkCategoryTitleSuffix: t({ ru: ' шт.)', en: ' pcs)', kk: ' дана)', de: ' Stk.)', fr: ' pièces)', es: ' pzs)', pt: ' pçs)', tr: ' adet)', uk: ' шт.)', zh: ' 项)', ar: ' عنصر)', pl: ' szt.)', it: ' pezzi)', sk: ' szt.)'}),
      bulkCategoryHelper: t({
        ru: 'Категория будет применена ко всем выбранным транзакциям',
        en: 'The category will be applied to all selected transactions',
        kk: 'Санат барлық таңдалған транзакцияларға қолданылады',
        de: 'Die Kategorie wird auf alle ausgewählten Transaktionen angewendet',
        fr: 'La catégorie sera appliquée à toutes les transactions sélectionnées',
        es: 'La categoría se aplicará a todas las transacciones seleccionadas',
        pt: 'A categoria será aplicada a todas as transações selecionadas',
        tr: 'Kategori seçilen tüm işlemlere uygulanacaktır',
        uk: 'Категорія буде застосована до всіх вибраних транзакцій',
        zh: '该类别将应用于所有已选交易',
        ar: 'سيتم تطبيق الفئة على جميع المعاملات المحددة',
        pl: 'Kategoria zostanie zastosowana do wszystkich wybranych transakcji',
        it: 'La categoria verrà applicata a tutte le transazioni selezionate',
        sk: 'Kategoria zostanie zastosowana do wszystkich wybranych transakcji',
      }),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Бас тарту', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
      apply: t({ ru: 'Применить', en: 'Apply', kk: 'Қолдану', de: 'Anwenden', fr: 'Appliquer', es: 'Aplicar', pt: 'Aplicar', tr: 'Uygula', uk: 'Застосувати', zh: '应用', ar: 'تطبيق', pl: 'Zastosuj', it: 'Applica', sk: 'Zastosuj'}),
      exportButton: t({ ru: 'Экспорт в таблицу', en: 'Export to table', kk: 'Кестеге экспорттау', de: 'In Tabelle exportieren', fr: 'Exporter vers tableau', es: 'Exportar a tabla', pt: 'Exportar para tabela', tr: 'Tabloya aktar', uk: 'Експорт до таблиці', zh: '导出到表格', ar: 'تصدير إلى جدول', pl: 'Eksportuj do tabeli', it: 'Esporta in tabella', sk: 'Eksportuj do tabeli'}),
      exportLoading: t({
        ru: 'Экспорт в таблицу...',
        en: 'Exporting to table...',
        kk: 'Кестеге экспортталуда...',
        de: 'Wird in Tabelle exportiert...',
        fr: 'Exportation vers tableau...',
        es: 'Exportando a tabla...',
        pt: 'Exportando para tabela...',
        tr: 'Tabloya aktarılıyor...',
        uk: 'Експорт до таблиці...',
        zh: '正在导出到表格...',
        ar: 'جارٍ التصدير إلى جدول...',
        pl: 'Eksportowanie do tabeli...',
        it: 'Esportazione in tabella...',
        sk: 'Eksportowanie do tabeli...',
      }),
      exportSuccess: t({
        ru: 'Таблица создана успешно',
        en: 'Table created successfully',
        kk: 'Кесте сәтті құрылды',
        de: 'Tabelle erfolgreich erstellt',
        fr: 'Tableau créé avec succès',
        es: 'Tabla creada exitosamente',
        pt: 'Tabela criada com sucesso',
        tr: 'Tablo başarıyla oluşturuldu',
        uk: 'Таблицю успішно створено',
        zh: '表格创建成功',
        ar: 'تم إنشاء الجدول بنجاح',
        pl: 'Tabela została pomyślnie utworzona',
        it: 'Tabella creata con successo',
        sk: 'Tabela została pomyślnie utworzona',
      }),
      exportFailure: t({
        ru: 'Не удалось экспортировать в таблицу',
        en: 'Failed to export to table',
        kk: 'Кестеге экспорттау мүмкін болмады',
        de: 'Export in Tabelle fehlgeschlagen',
        fr: 'Échec de l\'exportation vers tableau',
        es: 'Error al exportar a tabla',
        pt: 'Falha ao exportar para tabela',
        tr: 'Tabloya aktarma başarısız',
        uk: 'Не вдалося експортувати до таблиці',
        zh: '导出到表格失败',
        ar: 'فشل التصدير إلى جدول',
        pl: 'Nie udało się wyeksportować do tabeli',
        it: 'Impossibile esportare in tabella',
        sk: 'Nie udało się wyeksportować do tabeli',
      }),
      exportConfirmTitle: t({
        ru: 'Подтвердите экспорт',
        en: 'Confirm export',
        kk: 'Экспортты растау',
        de: 'Export bestätigen',
        fr: 'Confirmer l\'exportation',
        es: 'Confirmar exportación',
        pt: 'Confirmar exportação',
        tr: 'Dışa aktarmayı onayla',
        uk: 'Підтвердіть експорт',
        zh: '确认导出',
        ar: 'تأكيد التصدير',
        pl: 'Potwierdź eksport',
        it: 'Conferma esportazione',
        sk: 'Potwierdź eksport',
      }),
      exportConfirmBody: t({
        ru: 'Вы уверены, что хотите экспортировать эту выписку в пользовательскую таблицу?',
        en: 'Are you sure you want to export this statement to a custom table?',
        kk: 'Бұл үзіндіді пайдаланушы кестесіне экспорттағыңыз келетініне сенімдісіз бе?',
        de: 'Sind Sie sicher, dass Sie diesen Kontoauszug in eine benutzerdefinierte Tabelle exportieren möchten?',
        fr: 'Êtes-vous sûr de vouloir exporter ce relevé vers un tableau personnalisé ?',
        es: '¿Está seguro de que desea exportar este extracto a una tabla personalizada?',
        pt: 'Tem certeza de que deseja exportar este extrato para uma tabela personalizada?',
        tr: 'Bu ekstreyi özel bir tabloya aktarmak istediğinizden emin misiniz?',
        uk: 'Ви впевнені, що хочете експортувати цю виписку в користувацьку таблицю?',
        zh: '您确定要将此对账单导出到自定义表格吗？',
        ar: 'هل أنت متأكد من رغبتك في تصدير هذا الكشف إلى جدول مخصص؟',
        pl: 'Czy na pewno chcesz wyeksportować ten wyciąg do niestandardowej tabeli?',
        it: 'Sei sicuro di voler esportare questo estratto conto in una tabella personalizzata?',
        sk: 'Czy na pewno chcesz wyeksportować ten wyciąg do niestandardowej tabeli?',
      }),
      exportConfirmConfirm: t({ ru: 'Экспортировать', en: 'Export', kk: 'Экспорттау', de: 'Exportieren', fr: 'Exporter', es: 'Exportar', pt: 'Exportar', tr: 'Dışa aktar', uk: 'Експортувати', zh: '导出', ar: 'تصدير', pl: 'Eksportuj', it: 'Esporta', sk: 'Eksportuj'}),
      submitForApproval: t({ ru: 'Отправить', en: 'Submit', kk: 'Жіберу', de: 'Einreichen', fr: 'Soumettre', es: 'Enviar', pt: 'Enviar', tr: 'Gönder', uk: 'Надіслати', zh: '提交', ar: 'إرسال', pl: 'Prześlij', it: 'Invia', sk: 'Prześlij'}),
      submitSuccess: t({
        ru: 'Выписка отправлена на утверждение',
        en: 'Statement submitted for approval',
        kk: 'Үзінді бекітуге жіберілді',
        de: 'Kontoauszug zur Genehmigung eingereicht',
        fr: 'Relevé soumis pour approbation',
        es: 'Extracto enviado para aprobación',
        pt: 'Extrato enviado para aprovação',
        tr: 'Ekstre onay için gönderildi',
        uk: 'Виписку надіслано на затвердження',
        zh: '对账单已提交审批',
        ar: 'تم إرسال الكشف للموافقة',
        pl: 'Wyciąg przesłany do zatwierdzenia',
        it: 'Estratto conto inviato per approvazione',
        sk: 'Wyciąg przesłany do zatwierdzenia',
      }),
      categoryButton: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
      categoryDrawerTitle: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
      categorySearchPlaceholder: t({ ru: 'Поиск', en: 'Search', kk: 'Іздеу', de: 'Suchen', fr: 'Rechercher', es: 'Buscar', pt: 'Pesquisar', tr: 'Ara', uk: 'Пошук', zh: '搜索', ar: 'بحث', pl: 'Szukaj', it: 'Cerca', sk: 'Szukaj'}),
      categoryAllOption: t({ ru: 'Все', en: 'All', kk: 'Барлығы', de: 'Alle', fr: 'Tous', es: 'Todos', pt: 'Todos', tr: 'Hepsi', uk: 'Всі', zh: '全部', ar: 'الكل', pl: 'Wszystkie', it: 'Tutti', sk: 'Wszystkie'}),
      categoryNoResults: t({
        ru: 'Категории не найдены',
        en: 'No categories found',
        kk: 'Санаттар табылмады',
        de: 'Keine Kategorien gefunden',
        fr: 'Aucune catégorie trouvée',
        es: 'No se encontraron categorías',
        pt: 'Nenhuma categoria encontrada',
        tr: 'Kategori bulunamadı',
        uk: 'Категорії не знайдено',
        zh: '未找到类别',
        ar: 'لم يتم العثور على فئات',
        pl: 'Nie znaleziono kategorii',
        it: 'Nessuna categoria trovata',
        sk: 'Nie znaleziono kategorii',
      }),
      categoryUpdated: t({
        ru: 'Категория выписки обновлена',
        en: 'Statement category updated',
        kk: 'Үзінді санаты жаңартылды',
        de: 'Kontoauszugskategorie aktualisiert',
        fr: 'Catégorie du relevé mise à jour',
        es: 'Categoría del extracto actualizada',
        pt: 'Categoria do extrato atualizada',
        tr: 'Ekstre kategorisi güncellendi',
        uk: 'Категорію виписки оновлено',
        zh: '对账单类别已更新',
        ar: 'تم تحديث فئة الكشف',
        pl: 'Kategoria wyciągu zaktualizowana',
        it: 'Categoria estratto conto aggiornata',
        sk: 'Kategoria wyciągu zaktualizowana',
      }),
      categoryUpdateFailed: t({
        ru: 'Не удалось обновить категорию выписки',
        en: 'Failed to update statement category',
        kk: 'Үзінді санатын жаңарту мүмкін болмады',
        de: 'Kontoauszugskategorie konnte nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour la catégorie du relevé',
        es: 'Error al actualizar la categoría del extracto',
        pt: 'Falha ao atualizar categoria do extrato',
        tr: 'Ekstre kategorisi güncellenemedi',
        uk: 'Не вдалося оновити категорію виписки',
        zh: '无法更新对账单类别',
        ar: 'فشل تحديث فئة الكشف',
        pl: 'Nie udało się zaktualizować kategorii wyciągu',
        it: 'Impossibile aggiornare la categoria dell\'estratto conto',
        sk: 'Nie udało się zaktualizować kategorii wyciągu',
      }),
      fixDroppedRow: t({ ru: 'Исправить', en: 'Fix', kk: 'Түзету', de: 'Korrigieren', fr: 'Corriger', es: 'Corregir', pt: 'Corrigir', tr: 'Düzelt', uk: 'Виправити', zh: '修复', ar: 'إصلاح', pl: 'Napraw', it: 'Correggi', sk: 'Napraw'}),
      alertNeedsFixTitle: t({
        ru: 'Нужно исправить перед отправкой',
        en: 'Fix required before submit',
        kk: 'Жіберу алдында түзету қажет',
        de: 'Korrektur vor dem Einreichen erforderlich',
        fr: 'Correction requise avant soumission',
        es: 'Se requiere corrección antes de enviar',
        pt: 'Correção necessária antes de enviar',
        tr: 'Göndermeden önce düzeltme gerekli',
        uk: 'Потрібне виправлення перед надсиланням',
        zh: '提交前需要修正',
        ar: 'مطلوب تصحيح قبل الإرسال',
        pl: 'Wymagana korekta przed przesłaniem',
        it: 'Correzione richiesta prima dell\'invio',
        sk: 'Wymagana korekta przed przesłaniem',
      }),
      alertReviewTitle: t({
        ru: 'Проверьте выписку перед отправкой',
        en: 'Review statement before submit',
        kk: 'Жіберу алдында үзіндіні тексеріңіз',
        de: 'Kontoauszug vor dem Einreichen prüfen',
        fr: 'Vérifiez le relevé avant soumission',
        es: 'Revise el extracto antes de enviar',
        pt: 'Revise o extrato antes de enviar',
        tr: 'Göndermeden önce ekstreyi inceleyin',
        uk: 'Перевірте виписку перед надсиланням',
        zh: '提交前请审核对账单',
        ar: 'راجع الكشف قبل الإرسال',
        pl: 'Przejrzyj wyciąg przed przesłaniem',
        it: 'Rivedi l\'estratto conto prima dell\'invio',
        sk: 'Przejrzyj wyciąg przed przesłaniem',
      }),
      alertReadyTitle: t({
        ru: 'Выписка готова к отправке',
        en: 'Statement is ready to submit',
        kk: 'Үзінді жіберуге дайын',
        de: 'Kontoauszug ist bereit zur Einreichung',
        fr: 'Le relevé est prêt à être soumis',
        es: 'El extracto está listo para enviar',
        pt: 'O extrato está pronto para enviar',
        tr: 'Ekstre gönderilebilir durumda',
        uk: 'Виписка готова до надсилання',
        zh: '对账单已准备好提交',
        ar: 'الكشف جاهز للإرسال',
        pl: 'Wyciąg jest gotowy do przesłania',
        it: 'L\'estratto conto è pronto per l\'invio',
        sk: 'Wyciąg jest gotowy do przesłania',
      }),
      alertReadyBody: t({
        ru: 'Все обязательные категории назначены. Данные выглядят корректно, можно отправлять.',
        en: 'All required categories are assigned. The data looks good and ready to submit.',
        kk: 'Барлық міндетті санаттар тағайындалды. Деректер дұрыс, жіберуге болады.',
        de: 'Alle erforderlichen Kategorien wurden zugewiesen. Die Daten sehen gut aus und können eingereicht werden.',
        fr: 'Toutes les catégories requises sont assignées. Les données semblent correctes et sont prêtes à être soumises.',
        es: 'Todas las categorías requeridas están asignadas. Los datos se ven bien y están listos para enviar.',
        pt: 'Todas as categorias obrigatórias foram atribuídas. Os dados estão corretos e prontos para enviar.',
        tr: 'Gerekli tüm kategoriler atandı. Veriler iyi görünüyor ve gönderilmeye hazır.',
        uk: 'Усі обов\'язкові категорії призначено. Дані виглядають коректно, можна надсилати.',
        zh: '所有必填类别均已分配。数据看起来正常，可以提交。',
        ar: 'تم تعيين جميع الفئات المطلوبة. تبدو البيانات جيدة وجاهزة للإرسال.',
        pl: 'Wszystkie wymagane kategorie zostały przypisane. Dane wyglądają dobrze i są gotowe do przesłania.',
        it: 'Tutte le categorie obbligatorie sono assegnate. I dati sembrano corretti e sono pronti per l\'invio.',
        sk: 'Wszystkie wymagane kategorie zostały przypisane. Dane wyglądają dobrze i są gotowe do przesłania.',
      }),
      alertStatementCategoryMissing: t({
        ru: 'Не выбрана категория выписки.',
        en: 'Statement category is not selected.',
        kk: 'Үзінді санаты таңдалмаған.',
        de: 'Kontoauszugskategorie ist nicht ausgewählt.',
        fr: 'La catégorie du relevé n\'est pas sélectionnée.',
        es: 'La categoría del extracto no está seleccionada.',
        pt: 'A categoria do extrato não está selecionada.',
        tr: 'Ekstre kategorisi seçilmedi.',
        uk: 'Категорію виписки не вибрано.',
        zh: '未选择对账单类别。',
        ar: 'لم يتم تحديد فئة الكشف.',
        pl: 'Kategoria wyciągu nie jest wybrana.',
        it: 'La categoria dell\'estratto conto non è selezionata.',
        sk: 'Kategoria wyciągu nie jest wybrana.',
      }),
      alertStatementCategoryDisabled: t({
        ru: 'Выбранная категория выписки отключена. Выберите активную.',
        en: 'Selected statement category is disabled. Choose an active category.',
        kk: 'Таңдалған үзінді санаты өшірілген. Белсенді санатты таңдаңыз.',
        de: 'Die ausgewählte Kontoauszugskategorie ist deaktiviert. Wählen Sie eine aktive Kategorie.',
        fr: 'La catégorie de relevé sélectionnée est désactivée. Choisissez une catégorie active.',
        es: 'La categoría de extracto seleccionada está desactivada. Elija una categoría activa.',
        pt: 'A categoria de extrato selecionada está desativada. Escolha uma categoria ativa.',
        tr: 'Seçilen ekstre kategorisi devre dışı. Aktif bir kategori seçin.',
        uk: 'Вибрана категорія виписки вимкнена. Виберіть активну.',
        zh: '所选对账单类别已禁用。请选择一个有效类别。',
        ar: 'فئة الكشف المحددة معطلة. اختر فئة نشطة.',
        pl: 'Wybrana kategoria wyciągu jest wyłączona. Wybierz aktywną kategorię.',
        it: 'La categoria dell\'estratto conto selezionata è disabilitata. Scegli una categoria attiva.',
        sk: 'Wybrana kategoria wyciągu jest wyłączona. Wybierz aktywną kategorię.',
      }),
      alertTransactionsCategoryMissing: t({
        ru: '{count} транзакций требуют категорию. Назначьте категории для всех строк.',
        en: '{count} transactions require a category. Assign categories for all rows.',
        kk: '{count} транзакцияға санат қажет. Барлық жолдарға санат тағайындаңыз.',
        de: '{count} Transaktionen benötigen eine Kategorie. Weisen Sie allen Zeilen Kategorien zu.',
        fr: '{count} transactions nécessitent une catégorie. Assignez des catégories à toutes les lignes.',
        es: '{count} transacciones requieren una categoría. Asigne categorías a todas las filas.',
        pt: '{count} transações requerem uma categoria. Atribua categorias a todas as linhas.',
        tr: '{count} işlem bir kategori gerektiriyor. Tüm satırlara kategori atayın.',
        uk: '{count} транзакцій потребують категорії. Призначте категорії для всіх рядків.',
        zh: '{count} 笔交易需要类别。为所有行分配类别。',
        ar: '{count} معاملة تتطلب فئة. قم بتعيين الفئات لجميع الصفوف.',
        pl: '{count} transakcji wymaga kategorii. Przypisz kategorie do wszystkich wierszy.',
        it: '{count} transazioni richiedono una categoria. Assegna categorie a tutte le righe.',
        sk: '{count} transakcji wymaga kategorii. Przypisz kategorie do wszystkich wierszy.',
      }),
      alertParsingErrors: t({
        ru: 'Обнаружено {count} ошибок парсинга. Проверьте детали и данные выписки.',
        en: '{count} parsing errors found. Review parsing details and statement data.',
        kk: '{count} парсинг қатесі анықталды. Толық мәліметтерді тексеріңіз.',
        de: '{count} Parsing-Fehler gefunden. Überprüfen Sie die Parsing-Details und die Kontoauszugsdaten.',
        fr: '{count} erreurs d\'analyse trouvées. Vérifiez les détails d\'analyse et les données du relevé.',
        es: 'Se encontraron {count} errores de análisis. Revise los detalles de análisis y los datos del extracto.',
        pt: '{count} erros de análise encontrados. Revise os detalhes de análise e os dados do extrato.',
        tr: '{count} ayrıştırma hatası bulundu. Ayrıştırma ayrıntılarını ve ekstre verilerini inceleyin.',
        uk: 'Виявлено {count} помилок парсингу. Перевірте деталі та дані виписки.',
        zh: '发现 {count} 个解析错误。请检查解析详情和对账单数据。',
        ar: 'تم العثور على {count} أخطاء تحليل. راجع تفاصيل التحليل وبيانات الكشف.',
        pl: 'Znaleziono {count} błędów parsowania. Przejrzyj szczegóły parsowania i dane wyciągu.',
        it: 'Trovati {count} errori di analisi. Rivedi i dettagli di analisi e i dati dell\'estratto conto.',
        sk: 'Znaleziono {count} błędów parsowania. Przejrzyj szczegóły parsowania i dane wyciągu.',
      }),
      alertParsingWarnings: t({
        ru: 'Есть {count} предупреждений парсинга. Рекомендуется проверить спорные строки.',
        en: '{count} parsing warnings found. It is recommended to review flagged rows.',
        kk: '{count} парсинг ескертуі бар. Белгіленген жолдарды тексеріңіз.',
        de: '{count} Parsing-Warnungen gefunden. Es wird empfohlen, markierte Zeilen zu überprüfen.',
        fr: '{count} avertissements d\'analyse trouvés. Il est recommandé de vérifier les lignes signalées.',
        es: 'Se encontraron {count} advertencias de análisis. Se recomienda revisar las filas marcadas.',
        pt: '{count} avisos de análise encontrados. Recomenda-se revisar as linhas sinalizadas.',
        tr: '{count} ayrıştırma uyarısı bulundu. İşaretli satırların incelenmesi önerilir.',
        uk: 'Є {count} попереджень парсингу. Рекомендується перевірити позначені рядки.',
        zh: '发现 {count} 个解析警告。建议检查标记的行。',
        ar: 'تم العثور على {count} تحذيرات تحليل. يُنصح بمراجعة الصفوف المُعلَّمة.',
        pl: 'Znaleziono {count} ostrzeżeń parsowania. Zaleca się przegląd oznaczonych wierszy.',
        it: 'Trovati {count} avvisi di analisi. Si consiglia di rivedere le righe contrassegnate.',
        sk: 'Znaleziono {count} ostrzeżeń parsowania. Zaleca się przegląd oznaczonych wierszy.',
      }),
      alertNoTransactions: t({
        ru: 'В выписке нет транзакций. Проверьте файл или параметры импорта.',
        en: 'No transactions found in this statement. Check file or import settings.',
        kk: 'Үзіндіде транзакциялар жоқ. Файлды не импорт баптауларын тексеріңіз.',
        de: 'Keine Transaktionen in diesem Kontoauszug gefunden. Überprüfen Sie die Datei oder die Importeinstellungen.',
        fr: 'Aucune transaction trouvée dans ce relevé. Vérifiez le fichier ou les paramètres d\'importation.',
        es: 'No se encontraron transacciones en este extracto. Verifique el archivo o la configuración de importación.',
        pt: 'Nenhuma transação encontrada neste extrato. Verifique o arquivo ou as configurações de importação.',
        tr: 'Bu ekstrede işlem bulunamadı. Dosyayı veya içe aktarma ayarlarını kontrol edin.',
        uk: 'У виписці немає транзакцій. Перевірте файл або параметри імпорту.',
        zh: '此对账单中未找到交易。请检查文件或导入设置。',
        ar: 'لم يتم العثور على معاملات في هذا الكشف. تحقق من الملف أو إعدادات الاستيراد.',
        pl: 'Nie znaleziono transakcji w tym wyciągu. Sprawdź plik lub ustawienia importu.',
        it: 'Nessuna transazione trovata in questo estratto conto. Controlla il file o le impostazioni di importazione.',
        sk: 'Nie znaleziono transakcji w tym wyciągu. Sprawdź plik lub ustawienia importu.',
      }),
      statementNamePrefix: t({
        ru: 'Выписка — ',
        en: 'Statement — ',
        kk: 'Үзінді — ',
        de: 'Kontoauszug — ',
        fr: 'Relevé — ',
        es: 'Extracto — ',
        pt: 'Extrato — ',
        tr: 'Ekstre — ',
        uk: 'Виписка — ',
        zh: '对账单 — ',
        ar: 'الكشف — ',
        pl: 'Wyciąg — ',
        it: 'Estratto conto — ',
        sk: 'Wyciąg — ',
      }),
      exportDescription: t({
        ru: 'Экспорт из выписки от {{dateFrom}} - {{dateTo}}',
        en: 'Export from statement {{dateFrom}} - {{dateTo}}',
        kk: 'Үзіндіден экспорт {{dateFrom}} - {{dateTo}}',
        de: 'Export aus Kontoauszug {{dateFrom}} - {{dateTo}}',
        fr: 'Exportation depuis relevé {{dateFrom}} - {{dateTo}}',
        es: 'Exportar desde extracto {{dateFrom}} - {{dateTo}}',
        pt: 'Exportar do extrato {{dateFrom}} - {{dateTo}}',
        tr: 'Ekstreden dışa aktarma {{dateFrom}} - {{dateTo}}',
        uk: 'Експорт з виписки від {{dateFrom}} - {{dateTo}}',
        zh: '从对账单导出 {{dateFrom}} - {{dateTo}}',
        ar: 'تصدير من الكشف {{dateFrom}} - {{dateTo}}',
        pl: 'Eksport z wyciągu {{dateFrom}} - {{dateTo}}',
        it: 'Esportazione da estratto conto {{dateFrom}} - {{dateTo}}',
        sk: 'Eksport z wyciągu {{dateFrom}} - {{dateTo}}',
      }),
      requireCategory: t({
        ru: '{{count}} требуют категории',
        en: '{{count}} require category',
        kk: '{{count}} санат қажет етеді',
        de: '{{count}} benötigen eine Kategorie',
        fr: '{{count}} nécessitent une catégorie',
        es: '{{count}} requieren categoría',
        pt: '{{count}} requerem categoria',
        tr: '{{count}} kategori gerektiriyor',
        uk: '{{count}} потребують категорії',
        zh: '{{count}} 项需要类别',
        ar: '{{count}} تتطلب فئة',
        pl: '{{count}} wymaga kategorii',
        it: '{{count}} richiedono categoria',
        sk: '{{count}} wymaga kategorii',
      }),
      selectCategoryHint: t({
        ru: 'Выберите категорию для каждой транзакции с пустой или отключенной категорией',
        en: 'Select a category for each transaction with an empty or disabled category',
        kk: 'Бос немесе өшірілген санаты бар әрбір транзакция үшін санат таңдаңыз',
        de: 'Wählen Sie eine Kategorie für jede Transaktion mit einer leeren oder deaktivierten Kategorie',
        fr: 'Sélectionnez une catégorie pour chaque transaction avec une catégorie vide ou désactivée',
        es: 'Seleccione una categoría para cada transacción con una categoría vacía o desactivada',
        pt: 'Selecione uma categoria para cada transação com uma categoria vazia ou desativada',
        tr: 'Boş veya devre dışı kategorisi olan her işlem için bir kategori seçin',
        uk: 'Виберіть категорію для кожної транзакції з порожньою або вимкненою категорією',
        zh: '为每笔类别为空或已禁用的交易选择类别',
        ar: 'حدد فئة لكل معاملة ذات فئة فارغة أو معطلة',
        pl: 'Wybierz kategorię dla każdej transakcji z pustą lub wyłączoną kategorią',
        it: 'Seleziona una categoria per ogni transazione con una categoria vuota o disabilitata',
        sk: 'Wybierz kategorię dla każdej transakcji z pustą lub wyłączoną kategorią',
      }),
      disabledSuffix: t({
        ru: ' — отключена',
        en: ' — disabled',
        kk: ' — өшірілген',
        de: ' — deaktiviert',
        fr: ' — désactivée',
        es: ' — desactivada',
        pt: ' — desativado',
        tr: ' — devre dışı',
        uk: ' — вимкнено',
        zh: ' — 已禁用',
        ar: ' — معطل',
        pl: ' — wyłączona',
        it: ' — disabilitata',
        sk: ' — wyłączona',
      }),
      unapprove: t({ ru: 'Снять с утверждения', en: 'Unapprove', kk: 'Бекітуден қайтару', de: 'Genehmigung zurückziehen', fr: 'Retirer l\'approbation', es: 'Desaprobar', pt: 'Desaprovar', tr: 'Onayı geri al', uk: 'Зняти з затвердження', zh: '取消批准', ar: 'إلغاء الموافقة', pl: 'Cofnij zatwierdzenie', it: 'Rimuovi approvazione', sk: 'Cofnij zatwierdzenie'}),
      pay: t({ ru: 'Оплатить', en: 'Pay', kk: 'Төлеу', de: 'Bezahlen', fr: 'Payer', es: 'Pagar', pt: 'Pagar', tr: 'Öde', uk: 'Оплатити', zh: '支付', ar: 'دفع', pl: 'Zapłać', it: 'Paga', sk: 'Zapłać'}),
      rollbackToApprove: t({
        ru: 'Вернуть на утверждение',
        en: 'Return to approve',
        kk: 'Бекітуге қайтару',
        de: 'Zur Genehmigung zurücksenden',
        fr: 'Retourner pour approbation',
        es: 'Devolver para aprobación',
        pt: 'Retornar para aprovação',
        tr: 'Onaya geri gönder',
        uk: 'Повернути на затвердження',
        zh: '退回审批',
        ar: 'إعادة للموافقة',
        pl: 'Wróć do zatwierdzenia',
        it: 'Torna all\'approvazione',
        sk: 'Wróć do zatwierdzenia',
      }),
      submitBlockedTooltip: t({
        ru: 'Назначьте категории для всех транзакций перед отправкой',
        en: 'Assign categories to all transactions before submitting',
        kk: 'Жіберу алдында барлық транзакцияларға санаттарды тағайындаңыз',
        de: 'Weisen Sie allen Transaktionen vor der Einreichung Kategorien zu',
        fr: 'Assignez des catégories à toutes les transactions avant de soumettre',
        es: 'Asigne categorías a todas las transacciones antes de enviar',
        pt: 'Atribua categorias a todas as transações antes de enviar',
        tr: 'Göndermeden önce tüm işlemlere kategori atayın',
        uk: 'Призначте категорії для всіх транзакцій перед надсиланням',
        zh: '提交前为所有交易分配类别',
        ar: 'قم بتعيين الفئات لجميع المعاملات قبل الإرسال',
        pl: 'Przypisz kategorie do wszystkich transakcji przed przesłaniem',
        it: 'Assegna categorie a tutte le transazioni prima di inviare',
        sk: 'Przypisz kategorie do wszystkich transakcji przed przesłaniem',
      }),
      confirmDeleteOne: t({
        ru: 'Удалить транзакцию?',
        en: 'Delete transaction?',
        kk: 'Транзакцияны жою керек пе?',
        de: 'Transaktion löschen?',
        fr: 'Supprimer la transaction ?',
        es: '¿Eliminar transacción?',
        pt: 'Excluir transação?',
        tr: 'İşlem silinsin mi?',
        uk: 'Видалити транзакцію?',
        zh: '删除交易？',
        ar: 'حذف المعاملة؟',
        pl: 'Usunąć transakcję?',
        it: 'Eliminare la transazione?',
        sk: 'Usunąć transakcję?',
      }),
      confirmDeleteMany: t({
        ru: 'Удалить {count} транзакций?',
        en: 'Delete {count} transactions?',
        kk: '{count} транзакцияны жою керек пе?',
        de: '{count} Transaktionen löschen?',
        fr: 'Supprimer {count} transactions ?',
        es: '¿Eliminar {count} transacciones?',
        pt: 'Excluir {count} transações?',
        tr: '{count} işlem silinsin mi?',
        uk: 'Видалити {count} транзакцій?',
        zh: '删除 {count} 笔交易？',
        ar: 'حذف {count} معاملات؟',
        pl: 'Usunąć {count} transakcji?',
        it: 'Eliminare {count} transazioni?',
        sk: 'Usunąć {count} transakcji?',
      }),
      assignCategoryForTransactions: t({
        ru: 'Назначить категорию для {count} транзакций',
        en: 'Assign category for {count} transactions',
        kk: '{count} транзакцияға санат тағайындау',
        de: 'Kategorie für {count} Transaktionen zuweisen',
        fr: 'Assigner une catégorie pour {count} transactions',
        es: 'Asignar categoría para {count} transacciones',
        pt: 'Atribuir categoria para {count} transações',
        tr: '{count} işlem için kategori ata',
        uk: 'Призначити категорію для {count} транзакцій',
        zh: '为 {count} 笔交易分配类别',
        ar: 'تعيين فئة لـ {count} معاملات',
        pl: 'Przypisz kategorię dla {count} transakcji',
        it: 'Assegna categoria per {count} transazioni',
        sk: 'Przypisz kategorię dla {count} transakcji',
      }),
      unapproveSuccess: t({
        ru: 'Выписка возвращена в Submit',
        en: 'Statement moved back to submit',
        kk: 'Үзінді Submit кезеңіне қайтарылды',
        de: 'Kontoauszug zurück in Submit verschoben',
        fr: 'Relevé retourné en soumission',
        es: 'Extracto devuelto a envío',
        pt: 'Extrato movido de volta para envio',
        tr: 'Ekstre göndermeye geri taşındı',
        uk: 'Виписку повернено в Submit',
        zh: '对账单已移回提交',
        ar: 'تم إعادة الكشف إلى الإرسال',
        pl: 'Wyciąg przesunięty z powrotem do przesłania',
        it: 'Estratto conto riportato all\'invio',
        sk: 'Wyciąg przesunięty z powrotem do przesłania',
      }),
      paySuccess: t({
        ru: 'Выписка переведена в Pay',
        en: 'Statement moved to pay',
        kk: 'Үзінді Pay кезеңіне ауыстырылды',
        de: 'Kontoauszug in Pay verschoben',
        fr: 'Relevé transféré en paiement',
        es: 'Extracto movido a pago',
        pt: 'Extrato movido para pagamento',
        tr: 'Ekstre ödemeye taşındı',
        uk: 'Виписку переведено в Pay',
        zh: '对账单已移至支付',
        ar: 'تم نقل الكشف إلى الدفع',
        pl: 'Wyciąg przeniesiony do płatności',
        it: 'Estratto conto spostato in pagamento',
        sk: 'Wyciąg przeniesiony do płatności',
      }),
      rollbackToApproveSuccess: t({
        ru: 'Выписка возвращена на утверждение',
        en: 'Statement moved back to approve',
        kk: 'Үзінді бекіту кезеңіне қайтарылды',
        de: 'Kontoauszug zur Genehmigung zurückgeschickt',
        fr: 'Relevé retourné pour approbation',
        es: 'Extracto devuelto para aprobación',
        pt: 'Extrato movido de volta para aprovação',
        tr: 'Ekstre onaya geri gönderildi',
        uk: 'Виписку повернено на затвердження',
        zh: '对账单已移回审批',
        ar: 'تم إعادة الكشف للموافقة',
        pl: 'Wyciąg przesunięty z powrotem do zatwierdzenia',
        it: 'Estratto conto riportato all\'approvazione',
        sk: 'Wyciąg przesunięty z powrotem do zatwierdzenia',
      }),
    },
    columns: {
      date: t({ ru: 'Дата', en: 'Date', kk: 'Күні', de: 'Datum', fr: 'Date', es: 'Fecha', pt: 'Data', tr: 'Tarih', uk: 'Дата', zh: '日期', ar: 'التاريخ', pl: 'Data', it: 'Data', sk: 'Data'}),
      counterparty: t({ ru: 'Контрагент', en: 'Counterparty', kk: 'Контрагент', de: 'Gegenpartei', fr: 'Contrepartie', es: 'Contraparte', pt: 'Contraparte', tr: 'Karşı Taraf', uk: 'Контрагент', zh: '对手方', ar: 'الطرف المقابل', pl: 'Kontrahent', it: 'Controparte', sk: 'Kontrahent'}),
      paymentPurposeShort: t({
        ru: 'Назначение платежа',
        en: 'Payment purpose',
        kk: 'Төлем мақсаты',
        de: 'Zahlungszweck',
        fr: 'Objet du paiement',
        es: 'Propósito del pago',
        pt: 'Finalidade do pagamento',
        tr: 'Ödeme amacı',
        uk: 'Призначення платежу',
        zh: '付款用途',
        ar: 'الغرض من الدفع',
        pl: 'Cel płatności',
        it: 'Scopo del pagamento',
        sk: 'Cel płatności',
      }),
      expense: t({ ru: 'Расход', en: 'Expense', kk: 'Шығыс', de: 'Ausgabe', fr: 'Dépense', es: 'Gasto', pt: 'Despesa', tr: 'Gider', uk: 'Витрата', zh: '支出', ar: 'مصروف', pl: 'Wydatek', it: 'Spesa', sk: 'Wydatek'}),
      income: t({ ru: 'Доход', en: 'Income', kk: 'Кіріс', de: 'Einnahme', fr: 'Revenu', es: 'Ingreso', pt: 'Receita', tr: 'Gelir', uk: 'Дохід', zh: '收入', ar: 'دخل', pl: 'Przychód', it: 'Entrata', sk: 'Przychód'}),
      category: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
      actions: t({ ru: 'Действия', en: 'Actions', kk: 'Әрекеттер', de: 'Aktionen', fr: 'Actions', es: 'Acciones', pt: 'Ações', tr: 'Eylemler', uk: 'Дії', zh: '操作', ar: 'الإجراءات', pl: 'Akcje', it: 'Azioni', sk: 'Akcje'}),
      transactionDate: t({ ru: 'Дата операции', en: 'Transaction date', kk: 'Операция күні', de: 'Transaktionsdatum', fr: 'Date de transaction', es: 'Fecha de transacción', pt: 'Data da transação', tr: 'İşlem tarihi', uk: 'Дата операції', zh: '交易日期', ar: 'تاريخ المعاملة', pl: 'Data transakcji', it: 'Data transazione', sk: 'Data transakcji'}),
      documentNumber: t({ ru: 'Номер документа', en: 'Document number', kk: 'Құжат нөмірі', de: 'Dokumentnummer', fr: 'Numéro de document', es: 'Número de documento', pt: 'Número do documento', tr: 'Belge numarası', uk: 'Номер документа', zh: '单据编号', ar: 'رقم المستند', pl: 'Numer dokumentu', it: 'Numero documento', sk: 'Numer dokumentu'}),
      counterpartyName: t({
        ru: 'Наименование контрагента',
        en: 'Counterparty name',
        kk: 'Контрагент атауы',
        de: 'Name der Gegenpartei',
        fr: 'Nom de la contrepartie',
        es: 'Nombre de la contraparte',
        pt: 'Nome da contraparte',
        tr: 'Karşı taraf adı',
        uk: 'Найменування контрагента',
        zh: '对手方名称',
        ar: 'اسم الطرف المقابل',
        pl: 'Nazwa kontrahenta',
        it: 'Nome della controparte',
        sk: 'Nazwa kontrahenta',
      }),
      counterpartyBin: t({
        ru: 'БИН/номер счёта контрагента',
        en: 'Counterparty BIN/account',
        kk: 'Контрагент БСН/есепшот',
        de: 'BIN/Kontonummer der Gegenpartei',
        fr: 'BIN/compte de la contrepartie',
        es: 'BIN/cuenta de la contraparte',
        pt: 'BIN/conta da contraparte',
        tr: 'Karşı taraf BIN/hesap',
        uk: 'БІН/номер рахунку контрагента',
        zh: '对手方BIN/账户',
        ar: 'BIN/حساب الطرف المقابل',
        pl: 'BIN/numer konta kontrahenta',
        it: 'BIN/conto della controparte',
        sk: 'BIN/numer konta kontrahenta',
      }),
      counterpartyBank: t({
        ru: 'Реквизиты банка контрагента',
        en: 'Counterparty bank details',
        kk: 'Контрагент банк реквизиттері',
        de: 'Bankdaten der Gegenpartei',
        fr: 'Coordonnées bancaires de la contrepartie',
        es: 'Datos bancarios de la contraparte',
        pt: 'Dados bancários da contraparte',
        tr: 'Karşı taraf banka bilgileri',
        uk: 'Реквізити банку контрагента',
        zh: '对手方银行信息',
        ar: 'تفاصيل بنك الطرف المقابل',
        pl: 'Dane bankowe kontrahenta',
        it: 'Coordinate bancarie della controparte',
        sk: 'Dane bankowe kontrahenta',
      }),
      debit: t({ ru: 'Дебет', en: 'Debit', kk: 'Дебет', de: 'Soll', fr: 'Débit', es: 'Débito', pt: 'Débito', tr: 'Borç', uk: 'Дебет', zh: '借方', ar: 'مدين', pl: 'Debet', it: 'Dare', sk: 'Debet'}),
      credit: t({ ru: 'Кредит', en: 'Credit', kk: 'Кредит', de: 'Haben', fr: 'Crédit', es: 'Crédito', pt: 'Crédito', tr: 'Alacak', uk: 'Кредит', zh: '贷方', ar: 'دائن', pl: 'Kredyt', it: 'Avere', sk: 'Kredyt'}),
      paymentPurpose: t({ ru: 'Назначение платежа', en: 'Payment purpose', kk: 'Төлем мақсаты', de: 'Zahlungszweck', fr: 'Objet du paiement', es: 'Propósito del pago', pt: 'Finalidade do pagamento', tr: 'Ödeme amacı', uk: 'Призначення платежу', zh: '付款用途', ar: 'الغرض من الدفع', pl: 'Cel płatności', it: 'Scopo del pagamento', sk: 'Cel płatności'}),
      categoryId: t({ ru: 'Категория', en: 'Category', kk: 'Санат', de: 'Kategorie', fr: 'Catégorie', es: 'Categoría', pt: 'Categoria', tr: 'Kategori', uk: 'Категорія', zh: '类别', ar: 'الفئة', pl: 'Kategoria', it: 'Categoria', sk: 'Kategoria'}),
      branchId: t({ ru: 'Филиал', en: 'Branch', kk: 'Филиал', de: 'Filiale', fr: 'Agence', es: 'Sucursal', pt: 'Filial', tr: 'Şube', uk: 'Філія', zh: '分支机构', ar: 'الفرع', pl: 'Oddział', it: 'Filiale', sk: 'Oddział'}),
      walletId: t({ ru: 'Кошелек', en: 'Wallet', kk: 'Әмиян', de: 'Wallet', fr: 'Portefeuille', es: 'Cartera', pt: 'Carteira', tr: 'Cüzdan', uk: 'Гаманець', zh: '钱包', ar: 'المحفظة', pl: 'Portfel', it: 'Portafoglio', sk: 'Portfel'}),
    },
  },
} satisfies Dictionary;

export default content;
