import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'reportsPage',
  content: {
    errors: {
      loadReport: t({
        ru: 'Не удалось загрузить отчёт',
        en: 'Failed to load report',
        kk: 'Есепті жүктеу мүмкін болмады',
        de: 'Bericht konnte nicht geladen werden',
        fr: 'Impossible de charger le rapport',
        es: 'Error al cargar el informe',
        pt: 'Falha ao carregar o relatório',
        tr: 'Rapor yüklenemedi',
        uk: 'Не вдалося завантажити звіт',
        zh: '无法加载报告',
        ar: 'فشل تحميل التقرير',
        pl: 'Nie udało się załadować raportu',
        it: 'Impossibile caricare il report',
        sk: 'Nie udało się załadować raportu',
      }),
    },
    labels: {
      // Page
      title: t({ ru: 'Отчёты', en: 'Reports', kk: 'Есептер', de: 'Berichte', fr: 'Rapports', es: 'Informes', pt: 'Relatórios', tr: 'Raporlar', uk: 'Звіти', zh: '报告', ar: 'التقارير', pl: 'Raporty', it: 'Report', sk: 'Raporty'}),
      subtitle: t({
        ru: 'Создавайте финансовые отчёты и экспортируйте документы',
        en: 'Generate financial reports and export documents',
        kk: 'Қаржылық есептерді жасаңыз және құжаттарды экспорттаңыз',
        de: 'Erstellen Sie Finanzberichte und exportieren Sie Dokumente',
        fr: 'Générez des rapports financiers et exportez des documents',
        es: 'Genere informes financieros y exporte documentos',
        pt: 'Gere relatórios financeiros e exporte documentos',
        tr: 'Finansal raporlar oluşturun ve belgeler dışa aktarın',
        uk: 'Створюйте фінансові звіти та експортуйте документи',
        zh: '生成财务报告并导出文档',
        ar: 'أنشئ تقارير مالية وصدّر المستندات',
        pl: 'Generuj raporty finansowe i eksportuj dokumenty',
        it: 'Genera report finanziari ed esporta documenti',
        sk: 'Generuj raporty finansowe i eksportuj dokumenty',
      }),

      // Tabs
      tabTemplates: t({ ru: 'Шаблоны', en: 'Templates', kk: 'Үлгілер', de: 'Vorlagen', fr: 'Modèles', es: 'Plantillas', pt: 'Modelos', tr: 'Şablonlar', uk: 'Шаблони', zh: '模板', ar: 'القوالب', pl: 'Szablony', it: 'Modelli', sk: 'Szablony'}),
      tabHistory: t({ ru: 'История', en: 'History', kk: 'Тарих', de: 'Verlauf', fr: 'Historique', es: 'Historial', pt: 'Histórico', tr: 'Geçmiş', uk: 'Історія', zh: '历史', ar: 'السجل', pl: 'Historia', it: 'Cronologia', sk: 'Historia'}),

      // Templates
      templatePnlName: t({
        ru: 'Прибыли и убытки (P&L)',
        en: 'Profit & Loss (P&L)',
        kk: 'Пайда мен шығын (P&L)',
        de: 'Gewinn und Verlust (G&V)',
        fr: 'Profits et pertes (P&L)',
        es: 'Ganancias y pérdidas (P&L)',
        pt: 'Lucros e perdas (P&L)',
        tr: 'Kâr ve Zarar (P&L)',
        uk: 'Прибутки та збитки (P&L)',
        zh: '损益表 (P&L)',
        ar: 'الأرباح والخسائر (P&L)',
        pl: 'Zyski i straty (P&L)',
        it: 'Profitti e perdite (P&L)',
        sk: 'Zyski i straty (P&L)',
      }),
      templatePnlDescription: t({
        ru: 'Сводка доходов и расходов с чистой прибылью за период',
        en: 'Income and expenses summary with net profit for a period',
        kk: 'Кезеңдегі таза пайдамен кіріс пен шығыс қорытындысы',
        de: 'Zusammenfassung der Einnahmen und Ausgaben mit Nettogewinn für einen Zeitraum',
        fr: 'Résumé des revenus et dépenses avec bénéfice net pour une période',
        es: 'Resumen de ingresos y gastos con beneficio neto para un período',
        pt: 'Resumo de receitas e despesas com lucro líquido para um período',
        tr: 'Bir dönem için net kârla birlikte gelir ve gider özeti',
        uk: 'Зведення доходів та витрат з чистим прибутком за період',
        zh: '期间净利润的收入和支出摘要',
        ar: 'ملخص الإيرادات والمصروفات مع صافي الربح لفترة',
        pl: 'Podsumowanie przychodów i wydatków z zyskiem netto za okres',
        it: 'Riepilogo di entrate e uscite con utile netto per un periodo',
        sk: 'Podsumowanie przychodów i wydatków z zyskiem netto za okres',
      }),
      templateBalanceName: t({ ru: 'Баланс', en: 'Balance Sheet', kk: 'Баланс парағы', de: 'Bilanz', fr: 'Bilan', es: 'Balance General', pt: 'Balanço Patrimonial', tr: 'Bilanço', uk: 'Баланс', zh: '资产负债表', ar: 'الميزانية العمومية', pl: 'Bilans', it: 'Stato Patrimoniale', sk: 'Bilans'}),
      templateBalanceDescription: t({
        ru: 'Снимок активов, обязательств и капитала',
        en: 'Assets, liabilities and equity snapshot',
        kk: 'Активтер, міндеттемелер және капитал суреті',
        de: 'Momentaufnahme von Vermögenswerten, Verbindlichkeiten und Eigenkapital',
        fr: 'Instantané des actifs, passifs et capitaux propres',
        es: 'Instantánea de activos, pasivos y patrimonio',
        pt: 'Instantâneo de ativos, passivos e patrimônio líquido',
        tr: 'Varlıklar, yükümlülükler ve özkaynak anlık görüntüsü',
        uk: 'Знімок активів, зобов\'язань та капіталу',
        zh: '资产、负债和权益快照',
        ar: 'لقطة للأصول والخصوم وحقوق الملكية',
        pl: 'Zdjęcie aktywów, zobowiązań i kapitału własnego',
        it: 'Istantanea di attività, passività e patrimonio netto',
        sk: 'Zdjęcie aktywów, zobowiązań i kapitału własnego',
      }),
      templateCashFlowName: t({
        ru: 'Отчёт о движении денежных средств',
        en: 'Cash Flow Statement',
        kk: 'Ақша ағыны туралы есеп',
        de: 'Kapitalflussrechnung',
        fr: 'Tableau des flux de trésorerie',
        es: 'Estado de Flujo de Efectivo',
        pt: 'Demonstração de Fluxo de Caixa',
        tr: 'Nakit Akış Tablosu',
        uk: 'Звіт про рух грошових коштів',
        zh: '现金流量表',
        ar: 'قائمة التدفقات النقدية',
        pl: 'Rachunek przepływów pieniężnych',
        it: 'Rendiconto Finanziario',
        sk: 'Rachunek przepływów pieniężnych',
      }),
      templateCashFlowDescription: t({
        ru: 'Притоки и оттоки денежных средств за период',
        en: 'Cash inflows and outflows over a period',
        kk: 'Кезеңдегі ақша ағындары мен кетулері',
        de: 'Mittelzuflüsse und -abflüsse über einen Zeitraum',
        fr: 'Entrées et sorties de trésorerie sur une période',
        es: 'Entradas y salidas de efectivo durante un período',
        pt: 'Entradas e saídas de caixa ao longo de um período',
        tr: 'Bir dönem boyunca nakit girişleri ve çıkışları',
        uk: 'Надходження та відтоки грошових коштів за період',
        zh: '期间现金流入和流出',
        ar: 'التدفقات النقدية الداخلة والخارجة خلال فترة',
        pl: 'Wpływy i wydatki pieniężne w danym okresie',
        it: 'Flussi di cassa in entrata e in uscita in un periodo',
        sk: 'Wpływy i wydatki pieniężne w danym okresie',
      }),
      templateExpenseByCategoryName: t({
        ru: 'Расходы по категориям',
        en: 'Expense by Category',
        kk: 'Санаттар бойынша шығыстар',
        de: 'Ausgaben nach Kategorie',
        fr: 'Dépenses par catégorie',
        es: 'Gastos por categoría',
        pt: 'Despesas por categoria',
        tr: 'Kategoriye göre gider',
        uk: 'Витрати за категоріями',
        zh: '按类别分列支出',
        ar: 'المصروفات حسب الفئة',
        pl: 'Wydatki według kategorii',
        it: 'Spese per categoria',
        sk: 'Wydatki według kategorii',
      }),
      templateExpenseByCategoryDescription: t({
        ru: 'Разбивка расходов по категориям с итогами',
        en: 'Breakdown of expenses by category with totals',
        kk: 'Жалпы сомалармен санаттар бойынша шығыстардың бөлінуі',
        de: 'Aufschlüsselung der Ausgaben nach Kategorien mit Gesamtsummen',
        fr: 'Ventilation des dépenses par catégorie avec totaux',
        es: 'Desglose de gastos por categoría con totales',
        pt: 'Detalhamento de despesas por categoria com totais',
        tr: 'Toplamlarla birlikte kategoriye göre gider dökümü',
        uk: 'Розбивка витрат за категоріями із підсумками',
        zh: '按类别分列支出明细及合计',
        ar: 'تفصيل المصروفات حسب الفئة مع الإجماليات',
        pl: 'Podział wydatków według kategorii z sumami',
        it: 'Ripartizione delle spese per categoria con totali',
        sk: 'Podział wydatków według kategorii z sumami',
      }),

      // Generator
      dateFrom: t({ ru: 'Дата с', en: 'Date from', kk: 'Бастап күні', de: 'Datum von', fr: 'Date de début', es: 'Fecha desde', pt: 'Data de início', tr: 'Başlangıç tarihi', uk: 'Дата з', zh: '开始日期', ar: 'التاريخ من', pl: 'Data od', it: 'Data da', sk: 'Data od'}),
      dateTo: t({ ru: 'Дата по', en: 'Date to', kk: 'Дейін күні', de: 'Datum bis', fr: 'Date de fin', es: 'Fecha hasta', pt: 'Data de fim', tr: 'Bitiş tarihi', uk: 'Дата по', zh: '结束日期', ar: 'التاريخ إلى', pl: 'Data do', it: 'Data fino a', sk: 'Data do'}),
      format: t({ ru: 'Формат', en: 'Format', kk: 'Формат', de: 'Format', fr: 'Format', es: 'Formato', pt: 'Formato', tr: 'Format', uk: 'Формат', zh: '格式', ar: 'الصيغة', pl: 'Format', it: 'Formato', sk: 'Format'}),
      generate: t({ ru: 'Сформировать отчёт', en: 'Generate report', kk: 'Есеп жасау', de: 'Bericht erstellen', fr: 'Générer le rapport', es: 'Generar informe', pt: 'Gerar relatório', tr: 'Rapor oluştur', uk: 'Сформувати звіт', zh: '生成报告', ar: 'إنشاء تقرير', pl: 'Generuj raport', it: 'Genera report', sk: 'Generuj raport'}),
      generating: t({ ru: 'Формирование…', en: 'Generating…', kk: 'Жасалуда…', de: 'Wird erstellt…', fr: 'Génération en cours…', es: 'Generando…', pt: 'Gerando…', tr: 'Oluşturuluyor…', uk: 'Формування…', zh: '生成中…', ar: 'جارٍ الإنشاء…', pl: 'Generowanie…', it: 'Generazione in corso…', sk: 'Generowanie…'}),
      backToTemplates: t({ ru: 'К шаблонам', en: 'Back to templates', kk: 'Үлгілерге қайту', de: 'Zurück zu Vorlagen', fr: 'Retour aux modèles', es: 'Volver a plantillas', pt: 'Voltar aos modelos', tr: 'Şablonlara dön', uk: 'До шаблонів', zh: '返回模板', ar: 'العودة إلى القوالب', pl: 'Wróć do szablonów', it: 'Torna ai modelli', sk: 'Wróć do szablonów'}),

      // History table headers
      historyTemplate: t({ ru: 'Шаблон', en: 'Template', kk: 'Үлгі', de: 'Vorlage', fr: 'Modèle', es: 'Plantilla', pt: 'Modelo', tr: 'Şablon', uk: 'Шаблон', zh: '模板', ar: 'القالب', pl: 'Szablon', it: 'Modello', sk: 'Szablon'}),
      historyPeriod: t({ ru: 'Период', en: 'Period', kk: 'Кезең', de: 'Zeitraum', fr: 'Période', es: 'Período', pt: 'Período', tr: 'Dönem', uk: 'Період', zh: '期间', ar: 'الفترة', pl: 'Okres', it: 'Periodo', sk: 'Okres'}),
      historyFormat: t({ ru: 'Формат', en: 'Format', kk: 'Формат', de: 'Format', fr: 'Format', es: 'Formato', pt: 'Formato', tr: 'Format', uk: 'Формат', zh: '格式', ar: 'الصيغة', pl: 'Format', it: 'Formato', sk: 'Format'}),
      historyGeneratedBy: t({ ru: 'Кем создан', en: 'Generated by', kk: 'Кім жасаған', de: 'Erstellt von', fr: 'Généré par', es: 'Generado por', pt: 'Gerado por', tr: 'Oluşturan', uk: 'Ким створено', zh: '生成者', ar: 'أنشأ بواسطة', pl: 'Wygenerowany przez', it: 'Generato da', sk: 'Wygenerowany przez'}),
      historyGeneratedAt: t({ ru: 'Дата создания', en: 'Generated at', kk: 'Жасалған күні', de: 'Erstellt am', fr: 'Généré le', es: 'Generado el', pt: 'Gerado em', tr: 'Oluşturulma tarihi', uk: 'Дата створення', zh: '生成时间', ar: 'تاريخ الإنشاء', pl: 'Data wygenerowania', it: 'Generato il', sk: 'Data wygenerowania'}),
      historySize: t({ ru: 'Размер', en: 'Size', kk: 'Өлшем', de: 'Größe', fr: 'Taille', es: 'Tamaño', pt: 'Tamanho', tr: 'Boyut', uk: 'Розмір', zh: '大小', ar: 'الحجم', pl: 'Rozmiar', it: 'Dimensione', sk: 'Rozmiar'}),
      historyDownload: t({ ru: 'Скачать', en: 'Download', kk: 'Жүктеу', de: 'Herunterladen', fr: 'Télécharger', es: 'Descargar', pt: 'Baixar', tr: 'İndir', uk: 'Завантажити', zh: '下载', ar: 'تنزيل', pl: 'Pobierz', it: 'Scarica', sk: 'Pobierz'}),
      historyEmpty: t({
        ru: 'История отчётов пуста',
        en: 'No reports generated yet',
        kk: 'Есептер тарихы бос',
        de: 'Noch keine Berichte erstellt',
        fr: 'Aucun rapport généré pour l\'instant',
        es: 'Aún no se han generado informes',
        pt: 'Nenhum relatório gerado ainda',
        tr: 'Henüz rapor oluşturulmadı',
        uk: 'Історія звітів порожня',
        zh: '尚未生成任何报告',
        ar: 'لم يتم إنشاء أي تقارير بعد',
        pl: 'Historia raportów jest pusta',
        it: 'Nessun report generato ancora',
        sk: 'Historia raportów jest pusta',
      }),
      historyReport: t({ ru: 'Отчёт', en: 'Report', kk: 'Есеп', de: 'Bericht', fr: 'Rapport', es: 'Informe', pt: 'Relatório', tr: 'Rapor', uk: 'Звіт', zh: '报告', ar: 'تقرير', pl: 'Raport', it: 'Report', sk: 'Raport'}),
      historyGenerated: t({ ru: 'Создан', en: 'Generated', kk: 'Жасалған', de: 'Erstellt', fr: 'Généré', es: 'Generado', pt: 'Gerado', tr: 'Oluşturuldu', uk: 'Створено', zh: '已生成', ar: 'تم الإنشاء', pl: 'Wygenerowany', it: 'Generato', sk: 'Wygenerowany'}),
      historyEmptyHint: t({
        ru: 'Выберите шаблон и создайте первый отчёт.',
        en: 'Select a template and generate your first report.',
        kk: 'Үлгіні таңдап, бірінші есепті жасаңыз.',
        de: 'Wählen Sie eine Vorlage und erstellen Sie Ihren ersten Bericht.',
        fr: 'Sélectionnez un modèle et générez votre premier rapport.',
        es: 'Seleccione una plantilla y genere su primer informe.',
        pt: 'Selecione um modelo e gere seu primeiro relatório.',
        tr: 'Bir şablon seçin ve ilk raporunuzu oluşturun.',
        uk: 'Виберіть шаблон та створіть перший звіт.',
        zh: '选择一个模板并生成您的第一份报告。',
        ar: 'اختر قالباً وأنشئ تقريرك الأول.',
        pl: 'Wybierz szablon i wygeneruj swój pierwszy raport.',
        it: 'Seleziona un modello e genera il tuo primo report.',
        sk: 'Wybierz szablon i wygeneruj swój pierwszy raport.',
      }),
      justNow: t({ ru: 'Только что', en: 'Just now', kk: 'Жаңа ғана', de: 'Gerade eben', fr: 'À l\'instant', es: 'Ahora mismo', pt: 'Agora mesmo', tr: 'Az önce', uk: 'Щойно', zh: '刚刚', ar: 'للتو', pl: 'Przed chwilą', it: 'Proprio ora', sk: 'Przed chwilą'}),
      minutesAgo: t({ ru: 'м назад', en: 'm ago', kk: 'мин бұрын', de: 'Min. zuvor', fr: 'min', es: 'min', pt: 'min atrás', tr: 'dk önce', uk: 'хв тому', zh: '分钟前', ar: 'د مضت', pl: 'min temu', it: 'min fa', sk: 'min temu'}),
      hoursAgo: t({ ru: 'ч назад', en: 'h ago', kk: 'сағ бұрын', de: 'Std. zuvor', fr: 'h', es: 'h', pt: 'h atrás', tr: 'sa önce', uk: 'год тому', zh: '小时前', ar: 'س مضت', pl: 'godz. temu', it: 'h fa', sk: 'godz. temu'}),
      yesterday: t({ ru: 'Вчера', en: 'Yesterday', kk: 'Кеше', de: 'Gestern', fr: 'Hier', es: 'Ayer', pt: 'Ontem', tr: 'Dün', uk: 'Вчора', zh: '昨天', ar: 'أمس', pl: 'Wczoraj', it: 'Ieri', sk: 'Wczoraj'}),
      daysAgo: t({ ru: 'дн. назад', en: 'days ago', kk: 'күн бұрын', de: 'Tage zuvor', fr: 'jours', es: 'días', pt: 'dias atrás', tr: 'gün önce', uk: 'дн. тому', zh: '天前', ar: 'أيام مضت', pl: 'dni temu', it: 'giorni fa', sk: 'dni temu'}),

      // Balance Sheet labels (kept for BalanceSheet.tsx compatibility)
      balanceSheetTitle: t({ ru: 'Баланс', en: 'Balance Sheet', kk: 'Баланс парағы', de: 'Bilanz', fr: 'Bilan', es: 'Balance General', pt: 'Balanço Patrimonial', tr: 'Bilanço', uk: 'Баланс', zh: '资产负债表', ar: 'الميزانية العمومية', pl: 'Bilans', it: 'Stato Patrimoniale', sk: 'Bilans'}),
      assets: t({ ru: 'Активы', en: 'Assets', kk: 'Активтер', de: 'Vermögenswerte', fr: 'Actifs', es: 'Activos', pt: 'Ativos', tr: 'Varlıklar', uk: 'Активи', zh: '资产', ar: 'الأصول', pl: 'Aktywa', it: 'Attività', sk: 'Aktywa'}),
      liabilities: t({ ru: 'Пассивы', en: 'Liabilities', kk: 'Пассивтер', de: 'Verbindlichkeiten', fr: 'Passifs', es: 'Pasivos', pt: 'Passivos', tr: 'Yükümlülükler', uk: 'Пасиви', zh: '负债', ar: 'الخصوم', pl: 'Pasywa', it: 'Passività', sk: 'Pasywa'}),
      asOfNow: t({ ru: 'На данный момент', en: 'As of now', kk: 'Қазіргі уақытта', de: 'Zum jetzigen Zeitpunkt', fr: 'À ce jour', es: 'A partir de ahora', pt: 'A partir de agora', tr: 'Şu itibariyle', uk: 'На даний момент', zh: '截至目前', ar: 'اعتباراً من الآن', pl: 'Na chwilę obecną', it: 'A partire da ora', sk: 'Na chwilę obecną'}),
      asOfDate: t({ ru: 'На дату', en: 'As of date', kk: 'Күніне', de: 'Zum Datum', fr: 'À la date du', es: 'A la fecha', pt: 'Na data', tr: 'Tarihe göre', uk: 'На дату', zh: '截至日期', ar: 'اعتباراً من التاريخ', pl: 'Na dzień', it: 'Alla data', sk: 'Na dzień'}),
      savingBalance: t({ ru: 'Сохранение...', en: 'Saving...', kk: 'Сақталуда...', de: 'Wird gespeichert...', fr: 'Enregistrement...', es: 'Guardando...', pt: 'Salvando...', tr: 'Kaydediliyor...', uk: 'Збереження...', zh: '保存中...', ar: 'جارٍ الحفظ...', pl: 'Zapisywanie...', it: 'Salvataggio...', sk: 'Zapisywanie...'}),
      balanceSaved: t({ ru: 'Баланс сохранён', en: 'Balance saved', kk: 'Баланс сақталды', de: 'Saldo gespeichert', fr: 'Solde enregistré', es: 'Balance guardado', pt: 'Saldo salvo', tr: 'Bakiye kaydedildi', uk: 'Баланс збережено', zh: '余额已保存', ar: 'تم حفظ الرصيد', pl: 'Saldo zapisane', it: 'Saldo salvato', sk: 'Saldo zapisane'}),
      exportBalance: t({ ru: 'Экспорт баланса', en: 'Export balance', kk: 'Балансты экспорттау', de: 'Saldo exportieren', fr: 'Exporter le solde', es: 'Exportar balance', pt: 'Exportar saldo', tr: 'Bakiyeyi dışa aktar', uk: 'Експорт балансу', zh: '导出余额', ar: 'تصدير الرصيد', pl: 'Eksportuj saldo', it: 'Esporta saldo', sk: 'Eksportuj saldo'}),
      exportExcel: t({ ru: 'Excel', en: 'Excel', kk: 'Excel', de: 'Excel', fr: 'Excel', es: 'Excel', pt: 'Excel', tr: 'Excel', uk: 'Excel', zh: 'Excel', ar: 'Excel', pl: 'Excel', it: 'Excel', sk: 'Excel'}),
      exportPdf: t({ ru: 'PDF', en: 'PDF', kk: 'PDF', de: 'PDF', fr: 'PDF', es: 'PDF', pt: 'PDF', tr: 'PDF', uk: 'PDF', zh: 'PDF', ar: 'PDF', pl: 'PDF', it: 'PDF', sk: 'PDF'}),
      balanceDifference: t({
        ru: 'Разница баланса',
        en: 'Balance difference',
        kk: 'Баланс айырмасы',
        de: 'Saldodifferenz',
        fr: 'Différence de solde',
        es: 'Diferencia de balance',
        pt: 'Diferença de saldo',
        tr: 'Bakiye farkı',
        uk: 'Різниця балансу',
        zh: '余额差异',
        ar: 'فرق الرصيد',
        pl: 'Różnica salda',
        it: 'Differenza di saldo',
        sk: 'Różnica salda',
      }),
      loadingEllipsis: t({ ru: 'Загрузка…', en: 'Loading…', kk: 'Жүктелуде…', de: 'Wird geladen…', fr: 'Chargement…', es: 'Cargando…', pt: 'Carregando…', tr: 'Yükleniyor…', uk: 'Завантаження…', zh: '加载中…', ar: 'جارٍ التحميل…', pl: 'Ładowanie…', it: 'Caricamento…', sk: 'Ładowanie…'}),
      noData: t({ ru: 'Нет данных', en: 'No data', kk: 'Деректер жоқ', de: 'Keine Daten', fr: 'Aucune donnée', es: 'Sin datos', pt: 'Sem dados', tr: 'Veri yok', uk: 'Немає даних', zh: '无数据', ar: 'لا توجد بيانات', pl: 'Brak danych', it: 'Nessun dato', sk: 'Brak danych'}),
      refresh: t({ ru: 'Обновить', en: 'Refresh', kk: 'Жаңарту', de: 'Aktualisieren', fr: 'Actualiser', es: 'Actualizar', pt: 'Atualizar', tr: 'Yenile', uk: 'Оновити', zh: '刷新', ar: 'تحديث', pl: 'Odśwież', it: 'Aggiorna', sk: 'Odśwież'}),
      generateAndDownload: t({
        ru: 'Сформировать и скачать',
        en: 'Generate & Download',
        kk: 'Жасау және жүктеу',
        de: 'Erstellen und herunterladen',
        fr: 'Générer et télécharger',
        es: 'Generar y descargar',
        pt: 'Gerar e baixar',
        tr: 'Oluştur ve indir',
        uk: 'Сформувати та завантажити',
        zh: '生成并下载',
        ar: 'إنشاء وتنزيل',
        pl: 'Generuj i pobierz',
        it: 'Genera e scarica',
        sk: 'Generuj i pobierz',
      }),
      cancel: t({ ru: 'Отмена', en: 'Cancel', kk: 'Болдырмау', de: 'Abbrechen', fr: 'Annuler', es: 'Cancelar', pt: 'Cancelar', tr: 'İptal', uk: 'Скасувати', zh: '取消', ar: 'إلغاء', pl: 'Anuluj', it: 'Annulla', sk: 'Anuluj'}),
    },
  },
} satisfies Dictionary;

export default content;
